### ISSUE TITLE
Create option(s) for analytics drilldown

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1000]
# User story

> As an API owner 
> I want to drill down to the results of the dashboard
> so that I can narrow down the results shown in charts based on my needs.
# Design
- Drilldown information to show by table. 2 styles, but same functionality

![apitable1](https://cloud.githubusercontent.com/assets/17976243/16484311/4019bc3e-3ec1-11e6-9bc3-7482e93ccaba.png)

![apitable2-drodown](https://cloud.githubusercontent.com/assets/17976243/16484316/47682192-3ec1-11e6-86c1-aa22601483bd.png)

![apitable2-hovered](https://cloud.githubusercontent.com/assets/17976243/16484321/4dd2a782-3ec1-11e6-8ebd-ce8dc2da6ebe.png)
# Definition of done

_to be further defined_
- [ ] API owner can view analytics 
  - [ ] per IP address
  - [x] per HTTP method 
  - [ ] per IP location (country, city?)
- [ ] API owner can apply more than one rule to the custom query
- [ ] API owner can return to a situation where  custom rules / no rules are applied with one single action

**Comment by Nazarah** [comment]
Do you mean this as a filtering option? that you want to see only particular details? I am not exactly sure about how the feature would work.

**Comment by bajiat** [comment]
@Nazarah This could also mean interacting with the charts 

See for example: http://dc-js.github.io/dc.js/vc/

**Comment by bajiat** [comment]
@brylie Would you be interested in this task? Let's check the estimate based on the UI designs.

**Comment by brylie** [comment]
@bajiat the screenshots and definition of done would imply adding per column filtering to the data table. Basically, the data table would allow for 'query building' by allowing search strings within each column. E.g. filter by IP column; filter by API key column; filter by IP country.

We agreed not to include the API key in the dashboard analytics, so we might need to remove that requirement.

We need to add the HTTP method as a column, if it is available.

**Comment by brylie** [comment]
We also need to select the 'final' set of columns for the table. Based on a [comment from @frenchbread](https://github.com/apinf/api-umbrella-dashboard/issues/536#issuecomment-152076725), the Analytics contain the following columns: 

```js
api_key: '**apiKey_id**',
       internal_gatekeeper_time: 17.1,
       internal_response_time: 39.7,
       user_email: '**user_email**',
       user_id: '**user_id**',
       user_registration_source: 'web',
       backend_response_time: 30,
       request_accept: 'application/json',
       request_at: '2015-10-01T01:16:24.758Z',
       request_connection: 'keep-alive',
       request_content_type: 'application/json',
       request_host: '**host**',
       request_ip: '**request_ip**',
       request_method: 'GET',
       request_scheme: 'https',
       request_size: 261,
       request_url: '**request_url**',
       response_age: 0,
       response_content_length: 9153,
       response_content_type: 'application/json; charset=utf-8',
       response_server: 'nginx',
       response_size: 9695,
       response_status: 200,
       response_time: 58,
       proxy_overhead: 28,
       request_ip_country: 'FI',
       request_ip_location: [Object],
       request_path: '**path**',
       request_query: {},
       request_hierarchy: [Object] 
```

**Comment by brylie** [comment]
@frenchbread would you like this task? I can co-pilot.

The task is basically to enable filtering on the table, and have the filtered results reflected in the dashboard charts.

**Comment by Nazarah** [comment]
In the drilldowns should we have option to make IP addresses clickable? so that if someone clicks on an IP address, a new browse tab opens and user gets redirected there?

**Comment by frenchbread** [comment]
Self-assigned

**Comment by nnn** [comment]
@Nazarah, no, that's for filtering only. When user clicks on IP address, it filters dashboard.

**Comment by Nazarah** [comment]
IN API-Umbrella, analytics can be drilled down based on multiple rules in a separate filtering feature.
Similar feature can be made for APINF. Possibly in different task:

![apitablefilter](https://cloud.githubusercontent.com/assets/17976243/16766418/aa0e122c-4842-11e6-8538-ae3a41c36e44.png)
![apitablefilterquery](https://cloud.githubusercontent.com/assets/17976243/16766419/aa0e32d4-4842-11e6-80b3-62e51c200333.png)
![apitablefilterqueryrules](https://cloud.githubusercontent.com/assets/17976243/16766420/aa106446-4842-11e6-872a-bb6d66e6da34.png)

**Comment by bajiat** [comment]
Closing during icebox cleaning. Users can interact with the charts and can clear the active filters.
