### ISSUE TITLE
Make API calls directly from documentation viewer with own API key

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1007]
# User stories

As an API consumer, I want to make API calls directly from the documentation browser with my Apinf API key so that I can make authenticated API calls.
As an API consumer, I want to make API calls directly from the documentation browser with my own API key from a proxy connected to Apinf so that I can make the call without typing the key myself.

**Comment by bajiat** [comment]
Let's visit this after updating Swagger UI to 3.0: #2349

**Comment by ilarimikkonen** [comment]
cleaning, closing
