### ISSUE TITLE
Compare two APIs in dashboard

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1011]
Allow API owners to compare the usage of the APIs e.g. for viewing their popularity

Related to #999

Customer's wish: "vertaa kahta API:a, piirtäisi määrät ja paikat kartalle eri värillä"
Translation: compare two APIs, draw amounts and locations in map with different colors
# User story

> As an API owner 
> I want to easily select two APIs for comparison 
> so that I can see their analytics in one view
# Design

_paste wireframe link here_
# Definition of done
- [ ] User can select the two APIs (from the APIs they own) for viewing
- [ ] User can see a view that contains analytics for two APIs
- [ ] User can switch either of the APIs to another one
- [ ] User can clear the selection and return to default view

_Open item: should this be available only if owner owns more than one API?_

**Comment by Nazarah** [comment]
Should one chart contain the comparison information for both APIs? From DB perspective, having one chart to show details of comparison is better, then user doesn't need to move her eyes from one chart to another.

**Comment by Nazarah** [comment]
Would there be any possibility to compare two APIs of the same category but one API is  owned by another user?

**Comment by bajiat** [comment]
Related to #2024
