### ISSUE TITLE
Include API lifecycle phase tag in catalog

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1016]
# User story

As an API consumer I want the APIs to have flags based on lifecycle phase so that I can distinguish testing APIs from production APIs in the catalog

**Comment by Nazarah** [comment]
1. This should be possible to do only by API owners for their own APIs, right?
2. Also, should we make this feature available in tabular view? 
because adding too many things in card view would make it clumsy
3. The option should also be included in individual API pages.

**Comment by bajiat** [comment]
Closing as completed.
