### ISSUE TITLE
Scratchpad in navigation

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#1024]
I stumbled upon "scratchpad" in ebookers. It automatically stores links to latest items I have looked. That seems handy. Perhaps the concept could be applied to apinf.io as well. 

![screenshot from 2016-06-02 08 11 40](https://cloud.githubusercontent.com/assets/1927158/15734552/bd65ff24-2899-11e6-87a8-50e9cb659759.png)

**Comment by Nazarah** [comment]
Closing this.
