### ISSUE TITLE
Need to know Lifecycle phases of API

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1032]
For showing life cycles of API in list/card view and  filtering lists based on that, we need life cycle phases. Also need to determine should an API will have only one stage at a time.

**Comment by brylie** [comment]
@Nazarah we started researching this question, and have a working document here:

http://apinf-documentation.readthedocs.io/en/latest/research/API_Lifecycle/

**Comment by bajiat** [comment]
Closing as completed.
