### ISSUE TITLE
Deleting feedback from api's doesn't ask confirmation

### ISSUE THREAD

**Issue by Laura-Sampo** [apinf/platform#1041]
Steps:

Visit https://nightly.apinf.io
Go to dashboard
Go to catalogue
Select any api
Go to feedback
Write feedback
Delete feedback

Feedback will be directly deleted, there doesn't come any "Are you sure?" -question. Should it come?

Screenshot:
![image](https://cloud.githubusercontent.com/assets/11177395/15820200/a41cbabc-2bf0-11e6-96d4-9267a6416b16.png)

**Comment by bajiat** [comment]
Closing as fixed. There is a confirmation dialog.
