### ISSUE TITLE
SDK generator

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1049]
This is an EPIC for allowing developers to view or download code samples or SDK's for the most frequently used programming languages

**Comment by philippeluickx** [comment]
How does this add more value over http://editor.swagger.io/ ? You can download code stubs there too. Might be a new feature though...

**Comment by philippeluickx** [comment]
We need to know better how our users workflow looks like. Moved this to icebox because added value is not clear.

**Comment by bajiat** [comment]
@philippeluickx My thinking is that Swagger editor would be primarily used by API owners to create documentation or to update existing, uploaded Swagger document. Hence, for developers we could integrate Swagger Codegen and provide e.g. a button to download code sample / SDK, if a Swagger file is available for a particular API.  Does this make sense?

**Comment by philippeluickx** [comment]
It does make sense. I checked for swagger-ui if there is any indication on that project if they would include codegen there, but no concrete pointers for this to happen.
So let's implement this then!
