### ISSUE TITLE
Host Apinf REST APIs in Apinf catalog

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1054]
# User story

> As an Apinf REST API owner I want to host the Apinf API through Apinf user interface so that I can monitor it's usage and use the proxy features

# Goal
- Add or update APInf  APIs to apinf.io
 - Provide at least
  - Name
  - URL
  - Description
  - lifecycle status
  - APInf logo
  - Link to OpenAPI endpoint

**Comment by brylie** [comment]
@bajiat good user story. There is at least one related issue in the NREL API Umbrella repository that could be of use here.

- https://github.com/NREL/api-umbrella/issues/211

**Comment by bajiat** [comment]
Task was completed by @matleppa 

Closing the issue
