### ISSUE TITLE
Determine how to make settings sub-fields conditionally required

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1058]
Some fields on the settings page should only be required if the setting is enabled. For instance, the API Documentation Editor host should be required if the API Documentation Editor setting is enabled.

Determine how to conditionally require and/or validate sub-settings when the feature is enabled on the settings page and wizard.
# Related

Related upstream support request:
- https://github.com/aldeed/meteor-simple-schema/issues/618

**Comment by ilarimikkonen** [comment]
tick the box
