### ISSUE TITLE
Use Swagger file validation method

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1075]
Swagger file validation method and library was included in task #523. The method is not used to validate the files and it needs to be moved from backend to client. 

This is an enhancement to Documentation Viewer. It is not urgently required for Documentation Viewer 1.0 since the Swagger UI is capable of validating the files.
# Definition of done
- Swagger files are validated after user has selected the file, but before adding the file to collection
- If the Swagger file does not pass validation, an error is thrown to the user and the file is not added to collection
- If the Swagger file passes validation, it is added to document collection

**Comment by philippeluickx** [comment]
+1
This should be done in both scenarios: uploading a file or pointing to a file through URL.
