### ISSUE TITLE
Show information about number of consumers for each APIs

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1086]
"As an API user I want to know how many call have been made to a particular API so that..."

**Comment by Nazarah** [comment]
Idea about showing the information
![1 card1- normal state](https://cloud.githubusercontent.com/assets/17976243/15890589/034fba82-2d79-11e6-8291-b6bd6646ea61.png)

![1 cardview-2](https://cloud.githubusercontent.com/assets/17976243/15890599/0c82a89e-2d79-11e6-9904-c23fd511e6e6.png)

**Comment by bajiat** [comment]
@Nazarah This is not probably number of calls but number of individual consumers?

**Comment by bajiat** [comment]
There is also a related user story for dashboard: #1003
