### ISSUE TITLE
Catalog as default first view for API consumers

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1097]
Dashboard can be a confusing view for a first time user since it will show blank content to a user, who is not an API owner or an APInf administrator. Let's consider showing catalog as the default first view for those users.

This would require selecting default view route after login based on user role:
- catalog for regular users (no role assigned)
- dashboard for api owners (and APInf administrators)

Suggestion: For checking the api owner role, check whether you can use similar method as for checking whether the user has access to submenu item "Manage API Backends"

Blocked by #1234
# Definition of done
- [ ] When the user logs in, their role is checked
- [ ] Based on the user role, user gets re-directed to
  - [ ] catalog (no user role, i.e. regular user)
  - [ ] dashboard (API owner = manager)
  - [ ] dashboard (APInf administrator)

One more option:
Logged-in users have links to both Catalog and Dashboard from front-page
(At the moment we have only Catalog for anonymous users and only Dashboard for logged-in users)

**Comment by Nazarah** [comment]
Should we consider an alternative to view the organizations?
Since we are going to introduce organization feature soon, so it would contain APIs belonging to a particular organization.
A user might be interested to view an organization and its associated APIs.

**Comment by bajiat** [comment]
@nazarah Can you elaborate your comment? Do you mean it should be a platform setting, whether the default view is organization or catalog?

**Comment by Nazarah** [comment]
@bajiat : It depends if we think of making a separate catalog to view the organization.
If we have only one single catalog, which has one API view and one Organization view, the above "Definition of Done" would be sufficient. 
However, if we implement organization catalog as a separate page than the already existing catalog, we need to decide what view should appear as default based on the role of a user (anonymous, regular user, manager or admin). 
And implementing this as a platform settings sounds good.
