### ISSUE TITLE
When user has no data in analytics chart, on clicking month

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1132]
When User doesn't have data populated on charts, selecting anything from filter pane (dropmenus, text box) give a browser alertbox with text. The text to some inconsistency in the table and is not written in a user friendly manner. The meaning might be confusing to the user.

sol: Fix alert text so that it is more intuitive. If possible, try no to show the text in browser alert window.

![image](https://cloud.githubusercontent.com/assets/17976243/16033355/365f05fa-3214-11e6-929b-48fa084526fb.png)

**Comment by bajiat** [comment]
@Nazarah Does this warning / UI text appear any more? I don't remember seeing this kind of warning. Can we close the issue?
