### ISSUE TITLE
Allow API owner to see analytics for all the APIs they own

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1159]
A single API owner may add more than one API to Apinf. The owner should have an option to view analytics for all APIs they own.
# User story

> As an API owner
> I want to select all APIs in the dashboard view 
> so that I can gain holistic insight on the usage of the APIs I own
# Design

_paste wireframe link here_
# Definition of done
- [ ] User has a method for selecting all owned API on dashboard page
- [ ] Based on the user selection, dashboard charts (and table) get updated
- [ ] User interface clearly indicates what API you are looking at (vs. looking at single API)
- [ ] User can switch back to any single APIs owned by this particular owner

**Comment by marla-singer** [comment]
@bajiat The same things are resolved in a new Dashboard

**Comment by Nazarah** [comment]
Closing the issue as new Dashboard is being implemented.
