### ISSUE TITLE
Rename Documentation TAB and make it more visible to user eye

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1163]
User Testing Result:
When use wants to upload swagger documentation, then he can be misled to go to API settings page to do so.
The Documentation tab itself doesn't indicate (from default view) that it is used for uploading or linking swagger documentation. This can be confusing for first time users.
To Do:
Change the tab name as "Swagger Documentation" iff this tab would only be used for uploading or linking Swagger document.

**Comment by Nazarah** [comment]
Additional Improvements:
1. Change the upload dialogue title as "Swagger Documentation for API"
2. Change the browse box field name as : Upload Swagger Documentation
3.  Change help text for the browse box as: "Upload a new document for your API using Swagger here at APINF's own server. Only json and yamm file types are supported."

**Comment by bajiat** [comment]
Closing the issue. Since Swagger is called Open API specification, we don't want to mention Swagger in the tab name. Also, I would like to keep the tab names short. Furthermore, we have a long term goal to move away from tabbed profile.
