### ISSUE TITLE
Indicate mandatory fields by adding "*" sign

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1171]
> As an APInf user I want to know, which fields are mandatory when filling or editing forms.

Currently there is no way to tell which fields are mandatory unless user keeps some fields empty and tries to save.
Use \* sign to indicate the mandatory fields.

See comment for a code line that fixes this for every autoform, which we user everywhere in platform for forms.
# Definition of done
- Any required field in our UI shows an indication for mandatory field.

**Comment by brylie** [comment]
Upstream issue: https://github.com/aldeed/meteor-autoform/issues/661
