### ISSUE TITLE
Create wrapper for API Groups

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#118]
Extend the Meteor API Umbrella package with API Groups methods
Ref. https://github.com/NREL/api-umbrella/issues/152 and #84.

This is related to [brylie:api-umbrella](https://atmospherejs.com/brylie/api-umbrella) on Atmosphere.

**Comment by Nazarah** [comment]
It is unsure if more data would be exposed from API Umbrella to platform.
Also the usecases are unclear.
Closing this.
