### ISSUE TITLE
API Monitoring

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1183]
This is an EPIC for monitoring API downtime/uptime, alerting owners and displaying the API status to API consumers (in catalog and on API details page)

**Comment by philippeluickx** [comment]
Inspiration can be found with competitors. E.g. https://www.apiscience.com/

**Comment by philippeluickx** [comment]
After discussion with @frenchbread and @nnn we scoped the Epic as follows:
- We prefer to monitor the API, not the host. The host could have an HTTP 200 response with a nice webpage showing "API currently under maintance"
- Some APIs have an URL where you can ping the status (e.g. https://status.github.com/api) but we assume this will be the minority. In any case, for these to work we would have to do a mapping ("status": "good" vs "up": "yes" vs "ping": 1)
- Daily ping will do for now, we can always easily adapt later.

Feature:
- In the form / wizard, the user can add a url that will be pinged daily
- If no url is added, monitoring is disabled (will show as a grey dot in catalog?)
- We clearly explain to the API owner what the functionatity is of adding the url: showing the quality of the API to users browsing the catalog + emails when it's down

Future features:
- Automatically select a default url to ping (that can be changed)
- Add a "custom" url for status, with mapping

**Comment by philippeluickx** [comment]
Some other services:

- https://www.runscope.com/
- https://ping-api.com/
- http://apimetrics.io/

**Comment by bajiat** [comment]
Also: https://smartbear.com/learn/performance-monitoring/what-is-api-monitoring/

**Comment by philippeluickx** [comment]
![image](https://cloud.githubusercontent.com/assets/836866/18273897/5b53476a-7448-11e6-8379-514f0cf45aa2.png)

**Comment by philippeluickx** [comment]
![image](https://cloud.githubusercontent.com/assets/836866/18274065/5276008c-7449-11e6-92be-5e1bc667d58d.png)

![image](https://cloud.githubusercontent.com/assets/836866/18274073/5f9b62c0-7449-11e6-8d61-27c73edeb627.png)

**Comment by bajiat** [comment]
One option is the approach above: give the owner an option to use API monitoring, but they would need to give the URL which would be monitored. At this stage, we could stick with giving them the option to give a single URL?

**Comment by brylie** [comment]
@phanimahesh just showed me a package for REST API monitoring that might serve as the basis for our API Monitoring epic:

https://github.com/upssert/upssert

Just a note.

**Comment by phanimahesh** [comment]
Though Postman is not open source, they have a command line companion [newman][] which is Apache-2 Licensed. Newman operates on Postman collections which can either be authored manually or exported from postman. The collection specification is open.

Postman the company also provides an api monitoring service in their paid plans, very likely built on newman itself.

Since we need an all opensource solution, a quick option would be to run newman on cron with html reports and build a simple web dashboard to track status and view reports.

[newman]: https://github.com/postmanlabs/newman

**Comment by ilarimikkonen** [comment]
deones!!!
