### ISSUE TITLE
Allow users to create and edit Swagger files

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1192]
Find a suitable place in Apinf UI for making Swagger editor available
# User stories

> As an API owner
> I want to create a Swagger file
> so that I can document or design my API in Apinf without going to another tool
> 
> As an API owner
> I want to edit a Swagger file
> so that I can correct errors in the document

Open issue: Where in the UI should the user find the Documentation editor?
# Definition of done
- [ ] Swagger editor is available for users in the Apinf UI
- [ ] User can upload a file to the editor for editing
- [ ] User can create a new Swagger file
- [ ] API owner can connect created or uploaded Swagger file to an API backend they own and thus store the file in the documentation collection
- [ ] API owner can edit a Swagger file for an API they own
  - [ ] API owner can select the file they have uploaded for their API
  - [ ] API owner can save the changes and publish them for their API
- [ ] User can download the file that is open in Swagger editor

**Comment by philippeluickx** [comment]
After discussion with @frenchbread and @nnn we decided to move this epic to icebox.

It is not clear where this feature request comes from. What is the added value for having the editor in this? 
Considering the workflow of API owners / API developers, creating a Swagger file in the editor, integrated in apinf might not be the best solution.

Arguments:
- A swagger file is part of the code. Therefore, it will probably be created and edited in the prefered IDE that the developer is using.
- A swagger file is substantial and will 1. know many revisions 2. be a result of many people collaborating. This belongs in source control. By integrating, this flow would be broken.

An alternative is to guide API owners / API developers towards best practices. Point them to the swagger editor (http://editor.swagger.io/) and plugins for IDEs (https://github.com/AtomLinter/linter-swagger). Encourage them to source control the file.

**Comment by Nazarah** [comment]
@bajiat in this [issue](https://github.com/apinf/platform/issues/1998) we have been discussing about integrating OpenAPI Designer editor to APInf API profile to add/update Swagger document or OpenAPI document. Will we be adopting the design style discussed in wireframe 3 & 4?

>3. If user clicks the link, the API is added automatically and user is redirected to API Documentation tab directly.
The editor appears in Edit mode with the API name and hostname already populated from the given inputs
![editing doc](https://user-images.githubusercontent.com/17976243/28364016-76addb9c-6c8b-11e7-9e07-91eb7a5ce884.png)
When OpenAPI Designer is accessed from tab, the About tab in the designer should not appear.
User can open the editor in browser, in which case, user will be navigated to the main OpenAPI Designer page with the populated inputs.
4. In any case, if a documentation exists in the API profile, an Edit API Document button appears in that tab.
On Clicking the button, the swagger file or Open API document opens in editable mode.
![api documentation editor](https://user-images.githubusercontent.com/17976243/28363917-09395708-6c8b-11e7-9102-ad52e1eba066.png)

**Comment by bajiat** [comment]
If there is a document in the Swagger Viewer and user presses Open editor, the whole document should be pre-populated based on the existing document. I'm not sure if this requires Open API Space integration.

**Comment by ilarimikkonen** [comment]
done
