### ISSUE TITLE
Allow only unique proxy backend base paths

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1200]
In order to avoid having the same API added to the catalog more than once, we should only allow unique API backends. (As a follow-up, we may need to give an option to API owners to report, if someone else have added their API)

# Definition of done
* [ ] User can only add an API with Add API Wizard, if the front-end prefix (proxy backend base path) is unique?
* [ ] If the user tries to add a pre-existing URL (with pre-existing frontend prefix?), they get an error saying that this API backend already exists.

**Comment by nnn** [comment]
Interested in this task.

**Comment by bajiat** [comment]
Check also:  https://github.com/NREL/api-umbrella/issues/252

**Comment by Nazarah** [comment]
I will add warning messages here

**Comment by jykae** [comment]
Depends on #1379 

Discussed with @brylie that we will deprecate autoform-wizard package and use simple autoform for adding API. Number of fields (4 fields) without proxy related fields will be ok for one page form.

**Comment by jykae** [comment]
@bajiat @brylie I assume it is "API base URL" that should be unique? Do we want to support versioning of API?
For example: api.test.com/v1/ and api.test.com/v2/ Can I add those as one API or do I need to add version 2 as a separate API?

**Comment by brylie** [comment]
The `frontend_prefix` is the field that needs to be unique. This is because Proxy API Backends that share frontend prefixes will 'collide' with one another.

**Comment by bajiat** [comment]
@nnn Would you be interested in pursuing this task?
