### ISSUE TITLE
Deprecated ApiDocs cleanings

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1208]
As part of issue #1199 I stumbled upon other places where deprecated ApiDocs collection is used.
- Check if these parts of code can be just removed or do they need updated to use new DocumentationFiles collection.

"
Deprecated ApiDocs collection is still used here, https://github.com/apinf/api-umbrella-dashboard/blob/develop/apis/client/api_backends/edit/form/autoform.js#L104
and here, https://github.com/apinf/api-umbrella-dashboard/blob/develop/apis/client/api_backends/import_documentation/import.js#L56
"

**Comment by bajiat** [comment]
@frenchbread Do you know anything about the ApiDocs collection?

**Comment by nnn** [comment]
@jykae, wasn't it resolved with #1205 PR?
