### ISSUE TITLE
Show percentage of 4XX and 5XX responses in HTTP Status Chart

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1215]
In the chart to be implemented on Sprint 25, hovering over the plots on HTTP Response Status chart shows the number of 2XX, 5XX and 4XX requests.
However for analytical purpose, it is  convenient to show what percentage of client and server error responses are of 4XX and 5XX type.
It is also good to know the total number of 4XX and 5XX responses
# User Story

> As an API Owner 
> I want to see percentage of 4XX and 5XX responses from the overall failed responses for API call 
> so that I can know how much failed responses are from client side and from server side for a specific period of API usage
# Wireframe

![apinf analytics charts2](https://cloud.githubusercontent.com/assets/17976243/16377809/da997a2c-3c70-11e6-862a-1cd59fc5573a.png)

**Comment by marla-singer** [comment]
@preriasusi The issue is outdated
