### ISSUE TITLE
Switch router

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1234]
Switch from Iron Router to FlowRouter in order to support more advanced routing features, like default views based on user role and breadcrumbs.
# User story

> As an Apinf architect/developer
> I want to enable FlowRouter in the project
> so that the project has a router that is maintained and I can use the advanced features
# Definition of done
- [x] FlowRouter is added to the project
- [ ] All routes have been converted to use FlowRouter
- [x] Iron Router is removed from the project
- [ ] All route-level subscriptions have been moved to template instances
- [ ] All route hooks have been converted to FlowRouter syntax
- [ ] Templates are double-checked so that autogenerated links use FlowRouter `path_for` or `url_for`

**Comment by bajiat** [comment]
Organization Management will cause backwards incompatible changes to routing. Let's switch the router at the same time.

**Comment by jykae** [comment]
interested
