### ISSUE TITLE
Edit 'API bookmarks' in catalog view displays mouse pointer text for all APIs

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1238]
# Steps
1. Visit https://nightly.apinf.io  
2. Login as registered user  
3. Go to Catalog view  
4. Go to filter bar : sort by 'Popularity' and select 'descending order' view  
5. Bookmark multiple APIs (eg. two or more) by clicking on 'flag' sign  
6. Click on 'My Bookmarks'  
7. Select grid view  
8. Edit all bookmarks one after other by clicking on flag sign  
# Findings

Edit all API bookmarks by clicking on 'flag' sign displays mouse pointer text 'Bookmark API' for all APIs. 
# Operating system

Linux : Ubuntu 14.04.03 LTS (Trusty)
# Browser
1. Mozilla Firefox 44.0
2. Google Chrome 48.0.2564.103  
# Screenshot:

![edit_onebookmark_change](https://cloud.githubusercontent.com/assets/13309358/16476598/a875c9a6-3e91-11e6-8e4f-dffb1dda161c.png)

**Comment by bajiat** [comment]
@saralavanip Which browser were you using?

**Comment by saralavanip** [comment]
@bajiat , I have been testing on these browsers:
1. Mozilla Firefox 44.0
2. Google Chrome 48.0.2564.103

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://nightly.apinf.io  and it is reproducible in IE browser. 

**Findings:**  
- Suomi view - > Catalog ->Mouse pointer text for 'Bookmark API' flag  shown in both English and Suomi language. 

**Browsers**: 
1. Internet Explorer 11  
2. Google Chrome  Version 54.0.2840.71 m

**Operating system** : Windows 10

**Screenshots** :    

![screenshot 28](https://cloud.githubusercontent.com/assets/13309358/19969101/f5b67470-a1df-11e6-8739-ca669ed37c3e.png)


![img_2004](https://cloud.githubusercontent.com/assets/13309358/19969040/b6fabca0-a1df-11e6-9ac9-3b560e621603.JPG)   

![img_2007](https://cloud.githubusercontent.com/assets/13309358/19969051/bebcefa8-a1df-11e6-96bc-35286f9af1f3.JPG)
