### ISSUE TITLE
Upgrade API Umbrella to 0.13

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1249]
API Umbrella 0.13 was recently released. Upgrade our nightly, and possibly production, to use the latest version.

**Comment by bajiat** [comment]
Update only if there is a Docker image

**Comment by bajiat** [comment]
@shaliko Should we close this? Is this completed?

**Comment by shaliko** [comment]
@bajiat No, I not started that story, currently docker-compose works with 0.12 version.
