### ISSUE TITLE
Search page query string not updating, always empty

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1250]
Latest develop & on nightly:

Search page query was reactive, now broken, query string always empty. :(

Works from front page & top navigation.

**Comment by bajiat** [comment]
@jykae I think in previous development the reactive query was not updated from API backend names, but rather from other queries user has made in the browser. I think this should be an enhancement where the reactiveness is in relation to the fields where the search is made from.

**Comment by jykae** [comment]
@bajiat discussed shortly, search box on frontpage could be also closer to APIs like on catalog page as it searches APIs and not everything possible from our application. This is also enhancement idea.
