### ISSUE TITLE
Add a Cancel button in Edit API page

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1257]
Now, the only way to exit from Edit API page is to click on submit button.
If user comes to the page and doesn't change anything, clicking Submit may confuse user to think if s/he made any changes before leaving.

# Definition of Done
* [ ] Add a Cancel button beside submit button
* [ ] No S-alert should be shown when user exits Edit API page using Cancel button

**Comment by bajiat** [comment]
This view does not exist any more. Closing issue.
