### ISSUE TITLE
TypeError: Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by frenchbread** [apinf/platform#1261]
### Observed
- On API Backend View page which should not exist - `TypeError: Cannot read property '_id' of undefined` error is shown. 
### Expected:
- 404 page is rendered
### Steps to reproduce:
- Open APInf on nighlty or locally
- Go to catalog
- Click on any API -> API backends page opens up
- Modify API's ID in the page URL to smth random & hit enter
- Open browser console -> `TypeError: Cannot read property '_id' of undefined`

**Comment by bajiat** [comment]
@frenchbread Can you describe the steps to reproduce this error?

**Comment by frenchbread** [comment]
Updated issue description.
