### ISSUE TITLE
Add missing i18n tokens/texts related to Submit API Feedback form

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1274]
Related to #965

Add missing i18n tokens/texts related to Submit API Feedback form:
- Send feedback form (opens from Feedback tab)
  - Topic
    - Feedback topic
  - Your message
    - Your message
  - Choose message type
    - (Select One)
    - Feedback
    - Error report
    - Feature request
  - Submit
  - Add new issue form (opens from Backlog tab)
  - Title
    - Title
  - Details
    - Description
  - Priority
    - (Select one)
    - High
    - Middle
    - None

**Comment by marla-singer** [comment]
@bajiat Verified on apinf.io and it is resolved
![2017-05-12 14 09 12](https://cloud.githubusercontent.com/assets/20643403/25995839/e35c31f2-371c-11e7-8a46-09e9986f370d.png)
![2017-05-12 14 09 43](https://cloud.githubusercontent.com/assets/20643403/25995860/f4f2433e-371c-11e7-999a-72ff39d58889.png)
