### ISSUE TITLE
Add missing i18n tokens/texts to Add New API Issue form

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1275]
Related to #965

Add missing i18n tokens/texts to Add New API Issue form:
- Title
  - Title
- Details
  - Description
- Priority
  - (Select one)
  - High
  - Middle
  - None

**Comment by bajiat** [comment]
Resolved in the latest localisation round. Closing the issue.

<img width="416" alt="feedback form translated to fi" src="https://cloud.githubusercontent.com/assets/11626388/24400250/6c977f9a-13b8-11e7-9b13-da22545caf3d.png">
