### ISSUE TITLE
Sort by 'Recency' and select ascending/descending order shows incorrect results

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1283]
# Steps
1. Visit https://nightly.apinf.io  
2. Login as registered user  
3. Go to catalog view  
4. Select sorting option and order (eg. 'Recency' and  'ascending' order)  
5. Click on 'Show all'  

# Expected Result
It must show APIs based on time stamp: starting from newest to oldest 

# Findings
-  Select sorting option and order shows incorrect result.
-  Selecting ascending order shows result in descending order and vice versa  

# Operating system
Linux : Ubuntu 14.04.03 LTS (Trusty) 

# Browser
1. Google Chrome 48.0.2564.103  
2. Mozilla Firefox 44.0

# Screenshot

![incorrect_order_ascending](https://cloud.githubusercontent.com/assets/13309358/16568590/d8db231a-4234-11e6-8ecd-95197bb1189b.png)  

![incorrect_order](https://cloud.githubusercontent.com/assets/13309358/16568595/e3ecacce-4234-11e6-9b71-a8a473d2ce86.png)  

![recency_ascending_bookmarks](https://cloud.githubusercontent.com/assets/13309358/16568623/2c0e5200-4235-11e6-9362-93be4b6768e6.png)

**Comment by brylie** [comment]
What is the expected sort result?

**Comment by saralavanip** [comment]
@baijat,  verified on https://nightly.apinf.io and it is reproducible.  

Screenshots:  

Ascending order: 
![selection_088](https://cloud.githubusercontent.com/assets/13309358/19856279/7baef78e-9f81-11e6-90e7-c1a88ec7f57f.jpg)

Descending order:   
![selection_087](https://cloud.githubusercontent.com/assets/13309358/19856193/0bfd7898-9f81-11e6-9718-5c0d447afa79.jpg)

**Comment by brylie** [comment]
@saralavanip please describe further your expectations of 'ascending' and 'descending'. Given the following two dates, how would they sort with 'ascending' and 'descending'?

- January 1, 2016
- December 31, 2016

**Comment by saralavanip** [comment]
@brylie , my understanding with regard to ascending and descending order of display is : 

If Date and Time format is mm/dd/yyyy and hh:mm:ss  
**Ascending order** : oldest -> newest   (eg. January 1, 2016 -> December 31, 2016 )  
      -  eg. if time stamp is considered along with date (eg. 20 days ago, 15 days ago, 2 days ago, 9 hours ago -> few seconds ago)     

**Descending order** : newest -> oldest (eg. December 31, 2016 -> January 1, 2016)   
   -  eg.if time stamp is considered along with date (eg. few seconds ago, 9 hours ago, 2 days ago, 15 days ago - > 20 days ago)

**Comment by brylie** [comment]
@saralavanip, thanks for the clarification.
