### ISSUE TITLE
Access denied error when publishing new API Backend

### ISSUE THREAD

**Issue by frenchbread** [apinf/platform#1290]
Getting error when publishing new API Backend:

```
insert failed: Access denied. No allow validators set on restricted collection for method 'insert'.
```

Even though, API Backend is successfully published.

**Comment by nnn** [comment]
Same thing. Error appears only the browser console.

**Comment by bajiat** [comment]
@jykae Please verify

**Comment by jykae** [comment]
@bajiat Has been probably fixed. Both adding api & proxy backend functions flawlessly on latest develop, using nightly.apinf.io Umbrella as proxy.

@frenchbread @nnn  steps to reproduce?

**Comment by frenchbread** [comment]
@jykae Basically they are:
- Login as admin/user
- Go to "Add API" page
- Fill the form fields
- Submit the form
- Open browser console and see error

But I was not able to reproduce it now.. Seems like this has been fixed by one of the earlier PRs.

**Comment by frenchbread** [comment]
If @nnn confirms that there is no error anymore, we can close this.

**Comment by saralavanip** [comment]
@bajiat, @frenchbread , verified this issue on https://nightly.apinf.io   
Findings:  
-  Adding API was successful but browser console shows error with UI rendering . Not sure if relevent here .  

Screenshot:    
![selection_095](https://cloud.githubusercontent.com/assets/13309358/19859013/64f44872-9f8c-11e6-9e00-720213084d60.jpg)

**Comment by jykae** [comment]
@saralavanip router warning should not be critical, this issue is pointing to DB permissions allow rules, insert failing.
