### ISSUE TITLE
Change tooltip message styling

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1301]
# Definition of Done
- [ ] Make description text justified
- [ ] Decrease the size of the font

**Comment by nnn** [comment]
Please, provide us with more details.

Why description text should be justified?
Why size of the font should be decreased? And to what size?

**Comment by Nazarah** [comment]
Please have a look at the following screenshots:

![image](https://cloud.githubusercontent.com/assets/17976243/16721551/d03fae56-4748-11e6-92da-7ac072d7414c.png)

![image](https://cloud.githubusercontent.com/assets/17976243/16721555/d83d1e86-4748-11e6-8407-865857a156fb.png)

1. If the help text is 1 liner, there is no problem of having it in larger font size. But when is has more more than one line, showing it in bigger fonts doesn't have a pleasant appearance. Beside, with smaller letter you can resize the tooltip holder and allow user to see more of the background.

2. I pasted the help text in Source San Pro, 10 font size with both left aligned and justified style. In the justified style, there is good use of spacing inside the tooltip holder and the overall appearance looks neat and good. Even for one liner texts, justified alignment looks better.

If we are using a separate class for tooltips in the css styling sheet, i guess you can simply change the parameter into "justified" so that previous and future tooltips would appear as so.
