### ISSUE TITLE
Catalogue sorting doesn't follow i18n recommendations

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#1303]
Catalogue sorting goes according to Unicode value, that does not serve any language.

http://cldr.unicode.org
http://unicode.org/reports/tr10/#Main_Algorithm
https://en.wikipedia.org/wiki/Unicode_collation_algorithm

You can also compare sorting in folders f pc, on mobile devices phonebooks, and similar sorting as in Apinf is not in use in any modern device that is made for people to use.

**Comment by brylie** [comment]
Some initial findings:

- MongoDB does not support sorting using the Unicode Collation Algorithm
- The UCA also defines the Default Unicode Collation Element Table, or DUCET, which defines the default sort order for all Unicode characters, regardless of language. ([Elastic search documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/sorting-collations.html))

**Comment by brylie** [comment]
It seems that Mongodb 3.4 and above now supports CLDR sorting, or something to that effect:

- https://derickrethans.nl/mongodb-collation-revised.html

We can determine how this affects our query sorting in the client (e.g. APIs catalog and Organizations catalog).
