### ISSUE TITLE
Redesign "My managed APIs" view

### ISSUE THREAD

**Issue by 55** [apinf/platform#1304]
Redesign "My managed APIs" view @ _/manage_
Think about better approach to list user's APIs.

Current look:

![my_managed_apis](https://cloud.githubusercontent.com/assets/7489044/16686497/340d2f06-451b-11e6-9fd4-5dbd682b8bd0.png)

**Comment by Nazarah** [comment]
@55 sorry for querying in a closed issue, but can u please tell me where this UI exist in APInf? I first thought its the dashboard view, but I was wrong.

**Comment by 55** [comment]
@Nazarah it doesn't anymore.
