### ISSUE TITLE
Make List of APIs appear sorted Alphabetically

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1305]
# Definition of Done
- [ ] APIs in the selection dropdown appear alphabetically sorted.
- [ ] Option for changing sorting order (A - Z or Z - A) in the dropdown.
- [ ] Sorting order works for both My APIs and Other APIs category.
- Open Question: Is it more viable to sort the APIs according to their status? Admin/Owner would put more emphasize on APIs that are either down or needs maintenance rather "good" status API

**Comment by bajiat** [comment]
@Nazarah Are you referring to the API selection drop down in Dashboard? If yes, what is the last check box about: "Sorting order works for both My APIs and Other APIs category". API owners should only be able to see their own API(s)

**Comment by Nazarah** [comment]
@bajiat : yes, the API selection dropdown in Dashboard.
If an APINF Admin is viewing the dashboard, then he is supposed to see APIS added by him and API added by others. 
So for that scenario, the sorting should also work.

**Comment by saralavanip** [comment]
@bajiat , Verified on staging v 0.42.0 : 'Select API dropdown menu: list sorted alphabetically in English and Suomi views.

Screenshot:  
English view: 
![english_selectapis_menu_sorted](https://cloud.githubusercontent.com/assets/13309358/24408022/306ff37c-13d5-11e7-97f7-2cdb82fd8d0c.png)   

Suomi view:  

![suomi_selectapi_menu_sorted](https://cloud.githubusercontent.com/assets/13309358/24408027/397fdbee-13d5-11e7-9b91-602daa200a50.png)

**Comment by bajiat** [comment]
@saralavanip Thanks for the verification. Closing the issue.
