### ISSUE TITLE
Sort and view 'My bookmarks' shows all APIs

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1309]
# Steps
1. Visit https://nightly.apinf.io  
2. Sign up  
3. Go to 'Catalog'  
4. Select Sorting by 'Name or  Number of bookmarks' (in ascending order)  
5. Click on 'My Bookmarks'  
# Expected Result

Notify user if bookmarks not available yet  
# Actual Result

Sort and view 'My bookmarks' shows all APIs   
# Screenshot

![sort_mybookmarks_unresponsive](https://cloud.githubusercontent.com/assets/13309358/16794530/ef871224-48e0-11e6-8bb1-9c82b55667cd.png)    

![sort_name_bookmarks_all](https://cloud.githubusercontent.com/assets/13309358/16794594/8357246c-48e1-11e6-8ab8-8d9ec23752f8.png)

**Comment by bajiat** [comment]
@saralavanip I could not reproduce the error with Chrome (v. 51.0.2...) Which browser were you using?

**Comment by bajiat** [comment]
@jykae Please verify

**Comment by jykae** [comment]
Shows bookmarks when there are bookmarks
<img width="1203" alt="nayttokuva 2016-11-02 kello 9 52 25" src="https://cloud.githubusercontent.com/assets/293452/19920572/29552e56-a0e2-11e6-82d8-ba5280922226.png">

Empty page when no bookmarks
<img width="1230" alt="nayttokuva 2016-11-02 kello 9 53 54" src="https://cloud.githubusercontent.com/assets/293452/19920591/511d4cca-a0e2-11e6-8c3b-d3e03a6ae85e.png">
