### ISSUE TITLE
"Copy API key" button is inline with text field

### ISSUE THREAD

**Issue by frenchbread** [apinf/platform#1312]
### How it looks now:

![screen shot 2016-07-13 at 11 32 13](https://cloud.githubusercontent.com/assets/2122679/16796917/c1d1af76-48ed-11e6-8db0-b9d90c421a7b.png)
### How it supposed to look:
- "Copy API key" button should be below the input field, not inline.

**Comment by nnn** [comment]
Closing this since we are using different layout.
