### ISSUE TITLE
Missing i18n texts in navbar

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1319]
# Steps
1. Visit https://nightly.apinf.io 
2. Click on 'Suomi' 
3. Click on 'API Catalog' 

# Findings
Catalog  view in Suomi has English text strings : 'signup', 'login', 'Added by' , time stamp (date when created)

# Screenshot
![suomi_catalog_engtext](https://cloud.githubusercontent.com/assets/13309358/16871696/19180fb0-4a91-11e6-8d62-b4dec47629ee.png)    

![suomi_catalog_table](https://cloud.githubusercontent.com/assets/13309358/16871772/859df564-4a91-11e6-9885-d929f8c4842c.png)

**Comment by bajiat** [comment]
'Added by' has been localised since the bug report was created.: Lisännyt

Sign up and login have been internationalised, but not localised.

**Comment by bajiat** [comment]
@jykae Can you take this one?

**Comment by jykae** [comment]
@bajiat yep

**Comment by jykae** [comment]
@bajiat signUp & login have been translated, but as they come from accounts package(s) translation is applied, found package that includes translations for meteor standard packages https://github.com/softwarerero/meteor-accounts-t9n (doesn't yet include Finnish, possibility for contribution!) 
Simpler one, "added by" just misses Finnish i18n string, maybe dropped out at some point(?)

**Comment by jykae** [comment]
@bajiat Looked wrong, signup & login texts can be translated without that package, but it would be good to keep in mind https://github.com/meteor-useraccounts/core/blob/master/Guide.md#i18n-support

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly,apinf.io

Screenshot: 
![screenshot 67](https://cloud.githubusercontent.com/assets/13309358/20389804/2fb91c0a-acd4-11e6-95aa-d4e80aaa53ac.png)  

![screenshot 70](https://cloud.githubusercontent.com/assets/13309358/20389830/552bdb08-acd4-11e6-87e8-8f060f909e7e.png)
