### ISSUE TITLE
Analytics timeframe: Show correct API analytics data for selected date range only

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1322]
# Issue

> The timeframe functionality now has "Sunday" as the default start time to display API request data. However if any date and day (i.e. not on sunday and is later in a week) is selected, the result shows data of time range outside the selection.
# Improvement Ideas
- [ ] Make sure chart analytics show results for selected time range only (nothing outside of it).
- [ ] Explicitly mention about the condition of holding "Sunday" as the start of week and data rendering to be done according to this.

**Comment by bajiat** [comment]
Check whether this is still valid when Dashboard 2.0 will be done
