### ISSUE TITLE
Show API backend prefix value next to API backend name

### ISSUE THREAD

**Issue by frenchbread** [apinf/platform#1327]
### How it looks now:

![screen shot 2016-07-15 at 16 18 20](https://cloud.githubusercontent.com/assets/2122679/16875371/c70795a8-4aa7-11e6-8eda-0ab3c6abab27.png)
### Use-case:

> Potentially different API managers can have different APIs with similar names.
### Definition of done:
- Add `frontend_prefix` value next to its API name to differentiate them

**Comment by bajiat** [comment]
An API owner should not be able to see someone else's API, right?

**Comment by frenchbread** [comment]
@bajiat Right, and this "feature" is already implemented.
