### ISSUE TITLE
Notify users when no analytics data available for selected API in dashboard view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1337]
# Steps
1. Visit https://nightly.apinf.io 
2. Login as registered user 
3. Add API backend 
4. Go to dashboard 
5. Select the above added API from drop down menu  
# Findings

 Users not notified if no analytics data available.  
# Screenshots

![notify_nodata](https://cloud.githubusercontent.com/assets/13309358/16978057/89a26878-4e62-11e6-8ced-af909513e722.png)    

![notify_nodata1](https://cloud.githubusercontent.com/assets/13309358/16978055/83bf22c0-4e62-11e6-9f96-b859b508c140.png)

**Comment by bajiat** [comment]
Check whether this is still valid when Dashboard 2.0 will be done
