### ISSUE TITLE
API Key should not be passed as a parameter

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1349]
Adding keys in URL is not a safe practice. It stays in (browser) history and call logs. (It is secured though: https://groups.google.com/forum/#!forum/api-craft)
Better option is to pass the key in the header of the requests, e.g. authentication header.

edit: found that URLs are secure, but still best practice to not include sensitive data in URLs

Edited by bajiat:
> Usernames, passwords, session tokens, and API keys should not appear in the URL, as this can be captured in web server logs, which makes them intrinsically valuable.
> NOT OK:
>https://example.com/controller<id>/action?apiKey=a53f435643de32 (API Key in URL)
Source: https://www.owasp.org/index.php/REST_Security_Cheat_Sheet

# Definition of done:
* [x] Remove instruction for passing API key in URL

**Comment by bajiat** [comment]
@philippeluickx Where and what kind of change are you proposing?

**Comment by philippeluickx** [comment]
@bajiat Common practice is to use HTTP headers for authentication. Changes should be minimal to implement this.
E.g. http://code.tutsplus.com/tutorials/http-headers-for-dummies--net-8039

**Comment by bajiat** [comment]
@philippeluickx Still unclear about the impact about this issue. Where in the UI does this occur?

**Comment by frenchbread** [comment]
This approach is implemented [here](https://github.com/frenchbread/apinf-dashboard-example/blob/master/server/methods.js#L12).

**Comment by philippeluickx** [comment]
@frenchbread so do we have multiple options (and parameter is the default) or is this something new?

**Comment by frenchbread** [comment]
@philippeluickx Did not really got your question. 

Meteor's `HTTP.GET` method takes options such as headers, parameters etc. Documented [here](https://docs.meteor.com/api/http.html#HTTP-call). So we could either pass credentials as headers or as a parameters.

**Comment by philippeluickx** [comment]
Ok, right. So you basically mean that if we want to implement using Headers instead of parameters, this is pretty standard behaviour?

**Comment by frenchbread** [comment]
@philippeluickx Yep.

**Comment by jykae** [comment]
@philippeluickx If we want really be secure about this we could set "pass API key header" as default, otherwise Umbrella accepts both anyway. What you think?
<img width="583" alt="nayttokuva 2016-11-18 kello 10 16 45" src="https://cloud.githubusercontent.com/assets/293452/20423296/357a0740-ad78-11e6-9df0-226aa25bdfe9.png">

**Comment by philippeluickx** [comment]
@jykae Sounds good to me. Default to the more safe behavior, but leave the other options open.
