### ISSUE TITLE
Investigate how to improve documentation

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1361]
Good read on https://bradfults.com/the-best-api-documentation-b9e46400379a#.a2nmn7koi

There are plenty of links to well designed APIs here, such as https://stripe.com/docs/api

This could be a great opportunity to analyze what is covered in a well designed Swagger file and where we have gaps that apinf.io could support.

Also in terms of interaction, we can improve a few things, such as sidebar menu.

**Comment by bajiat** [comment]
@philippeluickx Can I rename the issue to "Investigate how to improve API documentation"?

**Comment by philippeluickx** [comment]
Sure!
