### ISSUE TITLE
Star rating widget rendering issue

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1377]
On the 'Single API Backend' view, the star rating widget sometimes has rendering problems:

![screenshot from 2016-08-10 16-00-56](https://cloud.githubusercontent.com/assets/17307/17554539/f6c8758e-5f13-11e6-9a53-1f6d50c908ae.png)

# Steps to reproduce
1. run `meteor reset`
2. log in
3. visit any API Backend (after syncing from API Umbrella)

# Environment
- Ubuntu 16.04
- Firefox 49.2

**Comment by nnn** [comment]
Maybe already fixed in https://github.com/apinf/api-umbrella-dashboard/pull/1372/commits/b366f3d9e6039816aad7430913c36b0885744e1f

**Comment by bajiat** [comment]
@nnn Can you verify that it can be closed if/while working with #1377

**Comment by bajiat** [comment]
@nnn @brylie Can I close this issue?

**Comment by brylie** [comment]
I defer to @nnn
