### ISSUE TITLE
Change API settings export to match collection change

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1385]
Make sure that both API details and proxy backend settings can be exported from Export tab. (If possible, tab should be available only for admin and API owner)

Note that API settings can already be exported.

# Definition of done
* [x] User has possibility to download both API backend details and proxy API backends configurations (can be separate files, in which case user needs to be able to select what they want)
* [x] Minimum requirement is that user can download json
* [x] If possible, Export tab is only available for admins and API managers

**Comment by bajiat** [comment]
Partly blocked by #1233

**Comment by bajiat** [comment]
@nnn Would you be interested in this task?

**Comment by bajiat** [comment]
@nnn What is the status for this task? #1233 is closed.

**Comment by nnn** [comment]
@bajiat PR is ready for review.
