### ISSUE TITLE
API gives 404 when the base URL responds with 200

### ISSUE THREAD

**Issue by frenchbread** [apinf/platform#1386]
> API status widget on Api view gives `404` status code. At the same time API's base URL (https://<host>/<backend_prefix)) responses with `200`.

By default Status widget pings `https://<host>`. Consider changing this to `https://<host>/<backend_prefix>`. (Append API backends prefix to the URL)

**Comment by bajiat** [comment]
Suggestion: allow the owner to switch on the monitoring. Also allow them to pick / change the URL settings. Consider giving a default.
Open issue: what to do with the monitoring icon for the APIs that are not monitored? Hide it?

**Comment by bajiat** [comment]
Monitoring implementation has been changed to allow owner to identify which endpoint to monitor. Closing the issue
