### ISSUE TITLE
Charts not available in deployments created with single Docker image

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1395]
Dashboard does not get any data in nightly2 and in customer deployment. 

Upstream issue opened to NREL: https://github.com/NREL/api-umbrella/issues/284 

Task is blocked until the upstream issue is fixed

**Comment by bajiat** [comment]
@shaliko Can you give me an update about this task?

**Comment by shaliko** [comment]
Waiting answer from Nick https://github.com/NREL/api-umbrella/issues/284. Issue in Docker image for api-umbrella https://hub.docker.com/r/nrel/api-umbrella/tags/. For me it looks like ElasticSerach index broken and for fix it we need drop it (after that it starts work).

I enabled debug level for ElasticSearch and Ngix logs, added debug code to Lua scripts but not found the root case.

**Comment by bajiat** [comment]
@shaliko Can we close this issue?

**Comment by shaliko** [comment]
@bajiat Yes, fixed on apinf/platform side by add "curl" installation on start.

In future when  api-umbrella release new version with fixed issue we will drop installation curl from docker file https://github.com/apinf/platform/blob/227ccb956d1cac4d843ecca7d53ae62057dd00d7/docker-compose.yml#L20
