### ISSUE TITLE
Add username to Api URLs, to namespace frontend prefixes

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1400]
In order to allow the re-use of some frontend prefixes, e.g. `/maps/`, we can add the username in front of the frontend prefix.

The resulting route on the Proxy would be something like:

```
// In API Proxy (e.g. API Umbrella)
/{{ username }}/{{ frontend_prfix }}
```

We could also update the Apinf URL structure, to remove the API ID and rather use the frontend prefix:

```
// Apinf URL route
/api/{{ username }}/{{ url_slug }}
```

This might mean including the 'frontend_prefix' or 'url slug' in the Apis collection.

**Comment by bajiat** [comment]
Now that we have organization support, this should also apply to organizations and not just users. That might mean changing how to add api to determine whether you are adding it as a user or as an organization manager.

**Comment by preriasusi** [comment]
When API made by APInf user and then moved to organisation, it would require path to change, which is more or less an issue for old calls.

**Comment by ilarimikkonen** [comment]
use brain. do manually.
