### ISSUE TITLE
Version updates of open source components

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1401]
After the latest Swagger-UI update, some Swagger files for a client implementation broke.
We need to make sure that all OS components we use are working nicely together. We should test with real-life test data.

Might also be a good idea to analyze and include changelogs from these components in our releases of apinf, e.g. https://github.com/swagger-api/swagger-ui/releases

**Comment by brylie** [comment]
As reference, the Swagger UI upgrade task is here:

https://github.com/apinf/api-umbrella-dashboard/issues/1363

**Comment by brylie** [comment]
One other thing to note, it may not have been the Swagger UI upgrade that caused the bug. Rather, we had changed our swagger file routing pattern, which was bundled with our 0.2.28 release. See bug report #1409 for a description of the routing changes.

- https://github.com/apinf/api-umbrella-dashboard/releases/tag/0.2.28
- https://github.com/apinf/api-umbrella-dashboard/issues/1409
