### ISSUE TITLE
Consider how to secure API Umbrella elasticsearch from anonymous access

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1402]
By default, the API Umbrella Elastic server is publicly accessible. This means that anyone with the proper knowledge may be able to access complete analytics records for API Umbrella. Consider how to secure the API Umbrella Elastic server as part of our packaging and/or upstream.
# Related
- [Issue on API Umbrella issue queue](https://github.com/NREL/api-umbrella/issues/287)

**Comment by brylie** [comment]
@bajiat I moved this to `In Progress` column, since we are currently investigating.

@shaliko I added you to the task, since you are working on this currently.

**Comment by shaliko** [comment]
@brylie Can we close that issue? Now we run ElasticSearch in Docker private network, so ES not available for public Internet.
