### ISSUE TITLE
ApiBacklogItems collection security

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1414]
The ApiBacklogItems collection needs security rules, specifically for the following methods:
- insert
- update
- remove

**Comment by bajiat** [comment]
Only administrators and the owner(s)/manager(s) of the API in questions should be able to insert, update and remove the items. Please check this in database permissions.

**Comment by saransh-dev** [comment]
Hi @brylie @bajiat ,

I checked the condition "Only administrators and the owner(s)/manager(s) of the API in questions should be able to insert, update and remove the items", it is being fulfilled. I checked in `permission.js` of backlog and there are some functions which take care about `api owner` and `admin`. Then if user either api owner or admin then he/she can able to insert update or remove backlog.

Thanks & Regards,
Saransh
