### ISSUE TITLE
Feedback collection security

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1416]
The Feedback collection needs security rules, specifically for the following method:
- insert

Double check all collection security rules, to make sure only authorized users can perform database operations.

**Comment by marla-singer** [comment]
@preriasusi Closed this issue because the Feedback collection has correct permissions
https://github.com/apinf/platform/blob/ce852bf7f099283c42999b437102625a947c11f3/apinf_packages/feedback/collection/permissions.js#L9-L26
