### ISSUE TITLE
ApiMetadata collection security

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1419]
The ApiMetadata collection needs security rules, specifically for the following method:
- insert
- update

Double check all collection security rules, to make sure only authorized users can perform database operations.

**Comment by marla-singer** [comment]
@preriasusi Closed this issue because ApiMetadata collection has correct permissions
https://github.com/apinf/platform/blob/ce852bf7f099283c42999b437102625a947c11f3/apinf_packages/metadata/collection/permissions.js#L5-L39
