### ISSUE TITLE
FeedbackAnswers collection security

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1421]
The FeedbackAnswers collection needs security rules, specifically for the following method:
- insert

Double check all collection security rules, to make sure only authorized users can perform database operations.

Remove this collection, if it is no longer useful.

**Comment by marla-singer** [comment]
@preriasusi Closed this issue because no FeedbackAnswers collection exists. 
The application's got FeedbackVotes collection and that's correct permissions
https://github.com/apinf/platform/blob/ce852bf7f099283c42999b437102625a947c11f3/apinf_packages/feedback_votes/collection/permissions.js#L11-L47
