### ISSUE TITLE
Api_key can not be inputted in Swagger ui after 2.1.5 update

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#1430]
After Swagger upgrade #1363 field to input api_key is missing.

Change in file 'public/swagger/index.html' -  'addApiKeyAuthorization();' method was removed, with the field to input the api_key.

Open questions:

Why api_key related stuff was removed from file ''public/swagger/index.html' '?

How to input api_key currently? Does it maybe require some changes for Swagger file?

**Comment by preriasusi** [comment]
I think this is not valid anymore.

**Comment by marla-singer** [comment]
@preriasusi On my opinion, this task isn't relevent. Because Swagger was implemented as npm package on project and we don't use files from "public/swagger" anymore
