### ISSUE TITLE
Instruct user about API Profile tabs after adding an API

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1445]
Implement a Bootstrap Tour that instructs the user to go to the proxy settings after the user has added an API. Otherwise, users who want to use a proxy might not know they need to set it in the Proxy tab.

# Definition of done
* [ ] Implement the described scenarios using the BootStrap Tour: http://bootstraptour.com/api/ 

# Design

## Scenarios

1. API Owner adds an API and is redirected to Details tab in API Profile. Using BS Tour, User is given instructions to browse to Proxies tab and asked to add a proxy.

2. API Admin adds an API but has not configured a proxy before. This results with Proxy tab not appearing in API profile. In Profile->settings. BS tour should prompt the user there to add a proxy.

## Wireframes

* Scenario 1

1. After API Owner is redirected to Details tab, BS tour start automatically, Dialogue indicates Proxy tab.
Tab gets highlighted (if possible)
![proxytabusagescenario1](https://cloud.githubusercontent.com/assets/17976243/18283490/2a4d7d90-746e-11e6-850a-db482efbc239.png)

2. (Clicking next) User gets redirected to Proxy tab and BS tour proceeds.
![proxytabusagescenario2](https://cloud.githubusercontent.com/assets/17976243/18283595/af6b188e-746e-11e6-8a2d-6a3a6d4b1016.png)

3. (clicking next) BS tour ends with prompting user to save proxy settings and to use API Management functionalities.
![proxytabusagescenario3](https://cloud.githubusercontent.com/assets/17976243/18310878/c7fd18ac-7509-11e6-9eaa-e4f4c3046342.png)

* Scenario 2

1. When no Proxy is available for the API to attach, BS tour guides Adminr to go to Settings under profile name to add a proxy (API Umbrella, Kong, or other)
![proxytabusagescenario5](https://cloud.githubusercontent.com/assets/17976243/18339615/3d301ce2-75a9-11e6-9cef-e3a335c67a79.png)

2. (clicking next)BS tour navigates to Settings and prompts to configure an API proxy
(wireframe pending as the new settings tab UI is still not available)

3. (clicking next)BS tour makes appearance of the Proxy tab under API profile.
![proxytabusagescenario6](https://cloud.githubusercontent.com/assets/17976243/18339677/9f1c80a8-75a9-11e6-9d28-ae58a15ca36b.png)

4. (clicking next) BS tour ends with prompting user to save proxy settings and to use API Management functionalities.
![proxytabusagescenario3](https://cloud.githubusercontent.com/assets/17976243/18339726/d27c2052-75a9-11e6-85f3-d26552465f08.png)

**Comment by Nazarah** [comment]
Link to BootStrap Tour:
http://bootstraptour.com/
click Demo to watch

**Comment by Nazarah** [comment]
Need to review the scenarios and associated wireframes.
For scenario 2, need view of new settings page to create wireframes.
@bajiat : would you be interested?

**Comment by bajiat** [comment]
@Nazarah Suggestion for the text in wireframe 3 in scenario 1:

Save the proxy settings and the different API management features like Dashboard are available for your API.
Save the proxy settings and start using different API management features like the Dashboard.

Scenario 2: only admin can add a proxy to the platform

**Comment by Nazarah** [comment]
@brylie: need to discuss the scenarios with you

**Comment by brylie** [comment]
I have started working on this task, but quickly encountered trouble when trying to import Bootstrap Tour:

- https://github.com/sorich87/bootstrap-tour/issues/570

I will try a different library, while this issue hopefully is discussed/resolved upstream.

**Comment by Nazarah** [comment]
@brylie : as you recommended I looked with http://introjs.com/, and it seems well.
We can use the style "progress bar" with it. 
But I was wondering that is it possible to use the "hint style" for scenario 2.
Because based on my understanding, the tour navigates you to different part of a page without requiring any action from the user in the actual webpage.
But according to scenario 2. (3rd wireframe), we are guiding APINF Admin to work in the proxy tab.
but in actual case, the proxy tab has not appeared yet in the profile as the admin has not added anything in setting page.
So my question is, can we implement this scenario? other wise I can redesign it, s,t. it stays in the same profile page all the time

**Comment by brylie** [comment]
> But according to scenario 2. (3rd wireframe), we are guiding APINF Admin to work in the proxy tab.
but in actual case, the proxy tab has not appeared yet in the profile as the admin has not added anything in setting page.
So my question is, can we implement this scenario? other wise I can redesign it, s,t. it stays in the same profile page all the time

@Nazarah lets move the second scenario into a 'Guided tour for Apinf administrators' task, where we can show a new administrator how to configure Apinf.

**Comment by brylie** [comment]
@Nazarah thanks for your feedback on the visual appearance of the tour. I have used the brand primary color to indicate the current step, with help from @nnn.

@Nazarah Relatedly, I would like to add the **Quick tour** button as part of this task, as you suggested. One open question, what FontAwesome icon might be good for the **Quick tour**button?

http://fontawesome.io/icons/
