### ISSUE TITLE
Exploratory testing: adding proxy and adding API without proxy

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1461]
Continue exploratory manual testing particularly for multiproxy changes. Note that the platform is temporarily disconnected from API Umbrella dialog, so you can only add APIs, but you cannot use any Umbrella related features. For example, Dashboard does not contain any data and there is no place to modify backend settings.)

Document the test cases, if not already documented. (Update if necessary.) Report any findings as issues giving steps to reproduce, expected outcome and actual outcome and stating the testing environment like OS, browser name and the browser version.

# Definition of done
* [x] Define platform settings, but do not add / define a proxy
* [x] Add an API (Note that the wizard has been removed)
  * [x] Check that API gets added to the catalog and you can bookmark it
* [x] Editing API settings: logo, description 
* [x] Export API settings
* [ ] Add the proxy settings for the platform
* [ ] Check the new sidebar menu for settings
* [x] Update test case document

Also, go through the test cases in test cases document, but for the time being skip any tests related to proxy (rate limiting, API key, viewing dashboard etc.)

**Comment by saralavanip** [comment]
Reported and updated issues:  
#1472 
#1473 
#1477 
#1501

**Comment by saralavanip** [comment]
Verified resolved issues: 
#1471  
#1473
