### ISSUE TITLE
'Delete' account not responding

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1477]
Steps:  

1.Visit https://nightly2.apinf.io  
2.Create account by clicking on 'Sign up'   
3.Navigate to 'Account' section    
4.Click on 'Delete Account'    
5.Click on 'Delete' button in user confirmation dialog box   

Findings: 
- Clicking on 'Delete' button doesn't respond. It  allows to close user confirmation dialog. 
- It doesn't display successful dialog    
- Logs out but still shows 'Account' view
  
Expected Result: Delete account should be complete and must display successful dialog.    

Browser:   

1. Mozilla Firefox 48.0 
(Mozilla Firefox for Ubuntu Canonical – 1.0 )   
2. Google Chrome 52.0.2743.116

Operating System:  
1. Ubuntu 16.0 LTS

Screenshot:  

![selection_010](https://cloud.githubusercontent.com/assets/13309358/18166445/f18cb926-7053-11e6-804c-de023d5565c1.png)  

![selection_009](https://cloud.githubusercontent.com/assets/13309358/18166455/f94893e2-7053-11e6-8d3f-4f43ea2878ce.png)

**Comment by bajiat** [comment]
@saralavanip Can you add info on your environment, particularly browser and version?

**Comment by saralavanip** [comment]
@bajiat , please find the browser details updated . 

Browser:   
1. Mozilla Firefox 48.0 
(Mozilla Firefox for Ubuntu Canonical – 1.0 )   
2. Google Chrome 52.0.2743.116

Operating System:  
1. Ubuntu 16.0 LTS
