### ISSUE TITLE
Disable Add proxy button if one proxy exists

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1484]
While we are currently only supporting one proxy (one API Umbrella per deployment), disable the Add proxy button from Settings / Proxies if administrator has added one proxy to the deployment.

# Definition of done
* [x] Admin users can see the Add proxy button only if no proxy has been added to the platform
* [x] Collection allow/deny rule has been added
  * [x] `insert` is only allowed when no Proxies exist

**Comment by bajiat** [comment]
@brylie The definition of done is missing the two changes required for collections / schemas. Can you please add them?

**Comment by brylie** [comment]
@bajiat done.

**Comment by frenchbread** [comment]
Interested

**Comment by Nazarah** [comment]
Possible implementation: Simply make the Add Proxy Button Disable and on mouse hover show the following message.
"You already have a Proxy available to attach your API. Please select the Proxy. You can add a new Proxy only after your have deleted the existing one."
