### ISSUE TITLE
Admin approval for user registrations

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1486]
It should be possible for admins to manually approve user registrations. Any new user will only be able to login after they have been approved by and admins. This needs to be a platform setting, where admins select whether they want to have manual user approval or not. Compare with Rocket Chat user registration flow.
# User story

> As an Apinf administrator I want to be able to define whether all users need to be approved by an administrator after registration
> 
> As an Apinf administrator I want to be able to easily approve / dismiss registered users after they have signed up so that I can control who has access to my (organizations's) deployment.
# Requirements
- Settings page: 'admin approval needed for user registrations'
  - boolean setting
  - if setting is enabled, users can register and admin must approve
  - if setting is disabled, users can register with regular registration flow
    - email validation may still occur in this step
- Page for admins to click to approve pending registrations 
- Notification on Admin screen when user registrations are pending

**Comment by philippeluickx** [comment]
Should we have the other side of the flow as well? So that admins can invite users?

**Comment by bajiat** [comment]
User flow needed.

**Comment by preriasusi** [comment]
Admin's invitation option in another task.

**Comment by Nazarah** [comment]
need to look at rocketchat registration flow
