### ISSUE TITLE
Allow admin pre-approval for APIs added to platform

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1488]
Allow administrators to check any new API after a user has added one. This requires a setting for the deployment (whether APIs are pre-approved or not in this deployment). It also requires notification for the admin for any new APIs and a user notification that your API will be available in the catalog once it has been approved. Should we also consider the flow for rejecting an API?
# User story

> As an Apinf administrator I want to be able to check any APIs that are added to the platform before they are published in the catalog

**Comment by bajiat** [comment]
Add an UI for APIs that are pending approval
Email notification for approved APIs and rejected APIs
API moderator user role? Moderator needs to be able to see the profile view
Notification module
Can the owner access the profile page and edit it, if the API is pending approval? Suggestion: should not be able to see it
Description field should be mandatory in Add API flow/form

**Comment by preriasusi** [comment]
The point to limit that anyone can't add anykind of API can be in other way also: To limit only Admin to be able to add API.  Estimation for that is 3.
