### ISSUE TITLE
Request access to closed API

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1489]
EPIC for closing APIs so that API is published in catalog, but it only shows limited information and has a e.g. button for the developer / user to request access to the API or a method for API owner to invite users to the API.
This task requires feedback from the team on possible options to allow only certain users to see/use the API with the _smallest_ possible implementation.

Field level visibility of the API in catalog.
Group of allowed users
Method for getting the access: email invititation from owner, administraor can manually add users (by email address) or request button.

**Comment by bajiat** [comment]
Feedback from @philippeluickx Does this require a new user role: API user that is tied to  particular API(s) to which user has been granted access?

**Comment by philippeluickx** [comment]
We might want to create a seperate epic with user roles functionality. This requires the definition and management of roles and we have to implement permissions as well.

**Comment by preriasusi** [comment]
1.0  Only allow API owner to  limit catalogue visibility for users on Apinf side. 
    Estimation: 5
    (Possible before MIndTrek)

2.0 Allove API owner to control developers who can make calls on proxy level:
    Estimation: ?
   Study story needed.
