### ISSUE TITLE
Successful dialogues for upload/delete project logo in 'Branding' view are not legible

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1501]
# Steps
1. Visit https://nightly2.apinf.io 
2. Login as admin 
3. Navigate to 'Branding' section 
4. Upload project logo by clicking on 'upload logo' 
5. Delete the uploaded logo by clicking on trashcan sign 
# Expected Result

Successful dialogues must be more clearer and understandable.  
# Findings
-  Successful in upload/delete project logo.  
-  Successful dialogs are not legible , missing text.
# Browser
1. Mozilla Firefox 48.0 
   (Mozilla Firefox for Ubuntu Canonical – 1.0 )  
2. Google Chrome 52.0.2743.116
# Operating System
1. Ubuntu 16.0 LTS  
# Screenshots:

![upload_logo_dialog](https://cloud.githubusercontent.com/assets/13309358/18309442/1a4d9cc4-7502-11e6-909e-788288a26e93.png)  

![delete_logo_dialog](https://cloud.githubusercontent.com/assets/13309358/18309446/207ee972-7502-11e6-9d16-5d58f9952add.png)

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://nightly.apinf.io and it is not reproducible. This issue can be closed.  

Screenshots:  
  
![screenshot 29](https://cloud.githubusercontent.com/assets/13309358/19999871/67dc2de0-a27d-11e6-915f-4f9f98706d77.png)  

![screenshot 30](https://cloud.githubusercontent.com/assets/13309358/19999879/774f0d56-a27d-11e6-9cc0-9a75a0f2d994.png)

**Comment by bajiat** [comment]
@saralavanip Thanks for the verification. Closing the issue.
