### ISSUE TITLE
Localise available UI texts

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1504]
Proofread the English UI texts and translate them into Finnish.

# Definition of done
* [ ] Upload the English and Finnish UI texts into OneSky.
* [ ] Proofread the English UI texts and make changes where necessary.
* [ ] Translate the missing or changed UI texts into Finnish.
* [ ] Have the Finnish UI texts proofread.

**Comment by Nazarah** [comment]
Interested to co-pilot

**Comment by preriasusi** [comment]
Ready to localise in OneSky.
