### ISSUE TITLE
User not notified after successful edit/update 'Branding' details

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1506]
# Steps
1. Visit https://nightly2.apinf.io  
2. Login as admin  
3. Go to Branding section  
4. Update/edit Branding details (eg. site title or site slogan)  
5. Click on 'Update' button  
# Findings
-  First click on 'Update' button doesn't respond though the details are updated. It remains highlighted until next click.  
-  User not notified about successful update.  
# Browser
1. Mozilla Firefox 48.0 
   (Mozilla Firefox for Ubuntu Canonical – 1.0 )  
2. Google Chrome 52.0.2743.116  
# Operating System
1. Ubuntu 16.0 LTS  
# Screenshot

![edit_update_branding](https://cloud.githubusercontent.com/assets/13309358/18342675/aa6f72ee-75b8-11e6-950a-97a038e23e38.png)

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io 

Findings:  
- Update/Edit 'Branding' details is successful but user not notified.

**Comment by philippeluickx** [comment]
@mauriciovieira If you are going to write unit tests for this, check out https://www.meteortesting.com/

**Comment by mauriciovieira** [comment]
After strugling with the recommended meteor way of doing unit tests. I decided to try the way Rocket.Chat does tests, using chimp in a end2end way. 

Related: https://github.com/xolvio/chimp/issues/433

**Comment by mauriciovieira** [comment]
I believe that we can test server methods using a setup similar to the recommended on meteor guides, such as https://github.com/gagarinjs/meteor-mocha

**Comment by mauriciovieira** [comment]
@philippeluickx this link points to a book that's being written at least since February and never gets released http://quality.xolv.io/. Nevertheless, the test runner that is being used by Rocket.Chat, chimp.js, was made by this xolvio. :-) Thanks for the tip.

**Comment by mauriciovieira** [comment]
closed by #2617
