### ISSUE TITLE
Edit Proxy backend and store the changes in API Umbrella

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1510]
If user edits the Proxy backend settings in te Proxies tab in API profile view, the changes will need to be reflected in API Umbrella.

# Definition of done
* [x] The edited proxy backend data/settings gets properly updated in API Umbrella

**Comment by bajiat** [comment]
@nnn Would you be interested in this task? May require some pair programming.

**Comment by bajiat** [comment]
@nnn What is the status of this task?

**Comment by nnn** [comment]
@bajiat started working on it, have a PR opened. Planning on finishing it during Tuesday.
