### ISSUE TITLE
Allow owner to switch on API monitoring

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1512]
Currently the API monitoring in APInf is providing false results. See error #1386. We should allow the owners to select whether the API is being monitored or not and to choose the URL. At first phase, we are not providing authentication for monitoring.

See also comments and screenshots from Monitoring EPIC #1183. 

# User story
> As an API owner I want to be able to switch on API monitoring

> As an API owner I want to be able to select the URL that is being monitored

# Definition of done
* [x] API owner can enable the API monitoring either from API settings or from Monitoring tab..
* [x] API owner can select / give the URL to be monitored. 
  * [ ] Optionally, give a default for URL and allow them to change/edit. 
* [x] Monitoring happens with http request instead of pinging.
* [x] If monitoring is enabled, the monitoring call is made once in hour(?)
* [x] Only show the monitoring icon in API profile and catalog, if API is being monitored (owner has switched that on)

# Wireframe

When Monitoring is not enabled
![apimonitoring](https://cloud.githubusercontent.com/assets/17976243/18904758/66c33c82-8568-11e6-86dd-b393d4344089.png)

On enabling API monitoring, the URL field gets activated. Owner is allowed to use only GET method for API monitoring. Owner should add path to the base URL of the API to get valid results about API status. info icon should describe how the API process works. 
![apimonitoring2](https://cloud.githubusercontent.com/assets/17976243/18904766/726fae44-8568-11e6-8f65-2fb90d5305b2.png)

For APIs with Monitoring Enable, small circles indicating API health should appear in API profile (see wireframe2), card view and table view in API catalog (indicated with squares)
![apimonitoringcatalogview](https://cloud.githubusercontent.com/assets/17976243/18904352/573c4c10-8566-11e6-9bdd-beaadbea458e.png)

![apimonitoringtableview](https://cloud.githubusercontent.com/assets/17976243/18904363/5f063a82-8566-11e6-89a3-7941baf5cdfc.png)

**Comment by Nazarah** [comment]
@bajiat need some clarification. Currently in API catalog and profile page, we show a green/yellow/red circle to indicate if API is running or not. 
Should we show that circle now only if API monitoring is enable for an API? 
If so, then I don't think we need any new icon to show that the API is being monitored.

**Comment by Nazarah** [comment]
@marla-singer Please include the following text under info icon:

"Please provide a valid path to the base URL of your API to get valid results about API status. API monitoring is done using HTTP requests. You can use GET method only so that accidental data insertion in your API is prevented."

**Comment by bajiat** [comment]
@nazarah 
"Only show the monitoring icon in API profile and catalog if API is being monitored (owner has switched that on)"
The basic idea was - but not communicated very clearly in the definition of done-  to use the same icon as we are using now, aka dot with different colors. However, we should not show anything (= no icon) for those APIs for which the owner has not enabled the monitoring. How does that sound to you?

**Comment by Nazarah** [comment]
@bajiat simple and clean solution. Like it.
Already uploaded the necessary wireframes.

**Comment by brylie** [comment]
@marla-singer as per our chat:

- Here is the reference js: https://github.com/apinf/platform/blob/develop/apis/client/view/status/status.js

**Comment by brylie** [comment]
Please see the Meteor [HTTP documentation](https://docs.meteor.com/api/http.html) for reference when writing the HTTP request code.

**Comment by bajiat** [comment]
@marla-singer @brylie 

Http method is needed for sure (with a recommendation to use get or even default)?
Could protocol, host and path be one field?
Monitoring frequency could be a sensible default at first and we would later add a feature to modify frequency
Header - enhancement? Or should we actually have the Apinf API key?
Is port needed or not? I have no idea.

**Comment by bajiat** [comment]
See also https://cloud.githubusercontent.com/assets/836866/18273897/5b53476a-7448-11e6-8379-514f0cf45aa2.png

**Comment by brylie** [comment]
> Could protocol, host and path be one field?
> 
> @bajiat 

Jep. That would be a simple start.
