### ISSUE TITLE
Add a setting for SMTP configuration

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1514]
It would be good to replace the current mailgun settings with more generic  SMTP configurations in the platform settings e.g. for validating emails during user registration and for sending monitoring notification emails to API owners.

# User story
> As an Apinf administrator 
I want to be able to give configuration settings for SMTP
so that I can enable email notifications and email verification

# Definition of done
* [x] SMTP configuration exists in Settings  schema.
  Open issue: should this replace the mailgun settings?
* [x] SMTP configuration fields are available in Settings UI.
* [x] The fields for SMTP configuration are validated.

# Wireframe

![smtpsettings](https://cloud.githubusercontent.com/assets/17976243/18463979/a957659c-7996-11e6-9caf-ed380bf3afb2.png)

**Comment by jykae** [comment]
@bajiat @brylie About open issue: Do we keep 3rd party Mailgun still around if admin does not have existing mail server to use?

**Comment by jykae** [comment]
@Nazarah Fields we need for mail setup "username", "password", "SMTP host", "SMTP port" based on smtp://USERNAME:PASSWORD@HOST:PORT/
from https://docs.meteor.com/api/email.html

**Comment by brylie** [comment]
Jep. Deprecate the Mailgun module, if possible. [Mailgun can be used via SMTP](https://documentation.mailgun.com/quickstart-sending.html#send-via-smtp).

**Comment by Nazarah** [comment]
@jykae : in https://nightly.apinf.io/settings, there is a pane called "Mail". Are we going to replace this existing pane with "SMTP Settings"? or we should keep both?
![image](https://cloud.githubusercontent.com/assets/17976243/18463275/829eb45a-7991-11e6-87bc-cbd792678e46.png)

**Comment by Nazarah** [comment]
@jykae Wireframe is available. Please review and give your feedback

**Comment by jykae** [comment]
@Nazarah I would keep the panel title "Mail" and yes, let's replace the mail panel with new fields.
How about the contact form? Do we want enable it automatically for front page when mail settings are enabled, or provide on/off toggling for that?

**Comment by brylie** [comment]
For simplicity, lets provide a toggle for contact form as an enhancement task. For now, the contact form should be disabled until *Mail* settings are configured.

@bajiat thoughts?

**Comment by jykae** [comment]
Status: Got mail working, fields added yesterday. Will finetune UI today, and push commits upstream to related PR, https://github.com/apinf/platform/pull/1561
