### ISSUE TITLE
Schema and collection for storing API monitoring status

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1515]
In order to notify the API owners only when their API monitoring status changes, we need to store the API monitoring statuses in a collection. This collection would also allow us later to create chart/analytics about API monitoring.

# Definition of done
* [x] Schema and collection for API monitoring status exists.
* [x] The response for every monitoring call/request is stored in the collection along with the time and date of request.
* [x] The collection is linked to the API collection.

**Comment by brylie** [comment]
As per our Rocket.Chat discussion:

The design is up to you, but it might be good to allow the API owner to configure settings such as:
- how often the status is checked
- full url (including host and path) to be checked
- what *status code* to expect
- header values, such as authentication, to be passed to each request

**Comment by brylie** [comment]
Ping @bajiat @Nazarah
