### ISSUE TITLE
Exploratory testing: Initial multiproxy features

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1531]
Continue exploratory manual testing particularly for multiproxy changes. The platform is still partly disconnected from API Umbrella and hence you cannot use most Umbrella related features. 

Document the test cases, if not already documented. (Update if necessary.) Report any findings as issues giving steps to reproduce, expected outcome and actual outcome and stating the testing environment like OS, browser name and the browser version.

# Definition of done

Test the following in nightly:
* [ ] Add API1 without connecting it to a proxy
* [x] Add API2 and connect it to a proxy
* [ ] Check the details page for API1 and API2: their base URL's should be different
* [x] Test Get API key and Copy API key buttons (moved to API profile page)
* [ ] Export API settings (Note: tab should be available for owners and admins only)
* [x] Add an API backlog item and save it
  * [x] Edit the API backlog item
  * [x] Delete the API backlog item
* [x] Delete and API you have added
* [x] Check the Swagger viewer (different implementation)

In development environment, you can also check the following
* [ ] Check that dashboard is not available if there is no proxy
* [ ] Add the proxy settings for the platform
* [ ] Check the new sidebar menu for settings

Remember also to update test cases document

**Comment by saralavanip** [comment]
Reported issues:  
#1562
#1565  
#1566  
#1567  
#1570

**Comment by saralavanip** [comment]
Verified resolved issue #1566 in local develop environment.
