### ISSUE TITLE
Determine how to handle API Umbrella base URL consistently in project

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1535]
The Proxies collection schema contains a sub object for apiUmbrella settings. The `apiUmbrella` object contains a host field that is used in two ways in our code:
1. when making calls to **API Umbrella Admin API**
   - e.g. for integration with API Umbrella
2. when displaying **Base URL** to end user, where API has a **Proxy Backend** configured
   - e.g. for users who call the API through the Proxy

In both cases, the URL takes slightly different structure:
1. `http://base.url/api-umbrella/`
2. `http://base.url/<proxy_base_path>`

Determine what input to take in the Proxy Settings form, and how to construct the URLs in both of the above scenarios.

**Comment by jykae** [comment]
My opinion is that this would be closely related to api-umbrella wrapper code, related to Umbrella Admin API v1 what path Admin API lives. So I would handle that path inside wrapper so that our code would not need to know what path Admin API lives.

**Comment by brylie** [comment]
I was thinking of a regex for the url this morning. In effect, we want the URL to
- start with *http* or *https*
- then, '://'
- then, one or more alphanumeric characters, periods (.), or hyphens (-)

As an aside, I would like to introduce a regex library that would allow us to define our regular expressions in a similar manner to the above list. One option would be the [regularity](https://www.npmjs.com/package/regularity) library.
