### ISSUE TITLE
Api documentation isn't uploaded

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1536]
Don't work feature with upload api documentation 

**Step to reproduce**

1. Run the last code on localhost
2. Create new Api and go to Documentation tab
3. Click on "Manage" button
4. Click on "Choose file" button and choose file

**Observed behavior**

When choosing file, it isn't uploaded and have error on console
` Exception in delivering result of invoking '/DocumentationFiles.files/insert': 
TypeError: Cannot read property '_id' of undefined
`

**Expected behavior**

File must be uploaded

**Environment**
Chrome 52.0
Debian 8

**Comment by bajiat** [comment]
@brylie Can you take a look whether it got resolved?

**Comment by marla-singer** [comment]
@bajiat I did new copy of project and It's working correct. Maybe It was problem on local Mongo or something.

**Comment by brylie** [comment]
@bajiat should we close this issue?

**Comment by marla-singer** [comment]
@bajiat It was problem on my side, not in project. Please close thie issue like not relevant
