### ISSUE TITLE
Copy API key -button does not work on Safari

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#1538]
Go to profile settings in Safari browser..

Press button "Copy API key".

Try to paste somewhere.

Expected: api key in clipboard.

Reality: Nothis has bee copied.

**Comment by bajiat** [comment]
@preriasusi It is possible to hightlight the key and copy it from browser without using the button, so there is at least a workaround for this.

**Comment by nnn** [comment]
@preriasusi works for me.
Safari 10.0.1
macOS 10.12.1
