### ISSUE TITLE
Useless tabs are shown for end user

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#1539]
When end user goes to API catalogue in APInf, there's same tabs for every API -  (Details, Documentation, Metadata, Feedback, Backlog, Export and Settings), whether there's content on page or not.

For example backlog tab usually says "No backlog items found for this API.". Since only API owner can only modify this, the whole tab could be hidden in case there are not backlog for the API. 

For many APIs only couple tabs are valid, rest of the tabs says "go away, nothing to see here".

Hiding useless tabs form API consumer is a good option if no content can be added there.

--- Following content added by @bajiat 2017-02-13 ----

# Note
* API owner and admin can always see all API tabs regardless of whether there is any content on the pages or not.
* Regular users and anonymous users can never see Export, Settings and Proxy tabs.
  * regular user = logged in, not admin and not manager of current API
* Details tab (default tab) is always available for all users, when the API is public.
* For private APIs, only API owners and allowed users can see the API profile page.
* Feedback tab should always be visible.

# Definition of done
* [ ] If there is no content on the Backlog tab, anonymous and regular users cannot see the tab.
* [ ] If there is no content on the Metadata tab, anonymous and regular users cannot see the tab.
* [ ] If there is no content on the Documentation tab, anonymous and regular users cannot see the tab.

Related to #1102

**Comment by Nazarah** [comment]
Should we hide the tabs from anonymous users and API consumers if they don't contain any data added by admin or API owner?
I'd like to keep the Feedback tab available to everyone.
anonymous users can view the given feedbacks and logged in API consumers can give feedback there.

**Comment by bajiat** [comment]
Yes, feedback tab should be available even if there is no feedback. Unless we want to give a possibility to the API owner to select whether Feedback tab is available for this API.

**Comment by nnn** [comment]
Interested.
