### ISSUE TITLE
User not notified if details missing/invalid while saving the proxy settings

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1562]
Steps:  
1.Visit https://nightly.apinf.io    
2.Create account clicking on 'Sign up'     
3.Add API Backend      
  - Enter API name    
  - Click on 'Add API'    

4.Go to 'Catalog' and click on 'My APIs' tab     
5.Click on API added above      
6.Click on 'Proxy'   
    - Enter invalid proxy base path / keep the text field empty   
    - Enter API base path (eg. / )   

7.Click on 'Save proxy settings' button    
8.Go to 'Details' view  

Findings:  
- Successful in saving proxy settings    
- User not notified if details are invalid/missing  
- Details view gets updated showing Base URL with text  'undefined '    

Expected Result: User must be notified if details are missing/invalid while saving proxy settings.   

Browser:    
Mozilla Firefox 48.0 
(Mozilla Firefox for Ubuntu Canonical – 1.0 )   

Operating System:    
Ubuntu 16.0 LTS     

Screenshot:  
![add_api_no_proxypath](https://cloud.githubusercontent.com/assets/13309358/18436238/ffb7f024-78ff-11e6-9802-3a5888d398d9.png)    

![base_url_undefined](https://cloud.githubusercontent.com/assets/13309358/18436241/05640e90-7900-11e6-96ad-9efb66fbb93a.png)

**Comment by bajiat** [comment]
@brylie Can you verify if there is a bug?

**Comment by brylie** [comment]
We can also verify this as part of @nnn's task, working with unique frontent prefixes.

**Comment by bajiat** [comment]
@nnn Could you take this?

**Comment by saralavanip** [comment]
@bajiat , verified the resolved issue on https://nightly.apinf.io and it is not reproducible.
