### ISSUE TITLE
API key partly shown when clicked on 'Get API key' tab

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1567]
Steps:  

1.Visit https://nightly.apinf.io   
2.Sign up   
3.Add API Backend   
4.Go to 'Catalog' and click on API added above   
5.Click on 'Get API' key      
 
Findings:  
-  'Copy API Key' tab appears and API key is partly shown      
- Click on 'Copy API Key' shows multiple successful dialogs    

Browser:   
1. Mozilla Firefox 48.0 
(Mozilla Firefox for Ubuntu Canonical – 1.0 )   
2. Google Chrome 52.0.2743.116

Operating System: Ubuntu 16.0 LTS  

Screenshot:  
![selection_025](https://cloud.githubusercontent.com/assets/13309358/18468101/19a402ba-79ab-11e6-8a03-bb77f22f9c59.png)      

![copy_api_key_mdialogs](https://cloud.githubusercontent.com/assets/13309358/18468264/d1b2e51a-79ab-11e6-8cd9-f5a0b4d384e2.png)

**Comment by bajiat** [comment]
@saralavanip Showing the key only partly in the UI is a feature.

**Comment by saralavanip** [comment]
@bajiat , verified the resolved issue: 'showing multiple messages' on https://nightly.apinf.io .
