### ISSUE TITLE
API document upload help text out of date

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#1571]
Go to api catalogue as admin. 

Go to documentation.

Click manage

Check help text of 'Upload documentation'

It says: 'You can also choose to create a new documentation for your APIs using swagger at our own server '. 

I don't think Apinf has anything to generate Swagger documentation at the moment.

**Comment by bajiat** [comment]
@preriasusi Let's check whether we would be able to change this when proofreading the English UI texts. Should be possible, if the help text is included in the i18n file.
