### ISSUE TITLE
Delete API logo not working

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1576]
Steps:  
1.Visit https://nightly.apinf.io  
2.Sign up  
3.Add API Backend  
4.Go to 'Catalog' and click on API added above  
5.Go to 'Settings'  
6.Upload API logo  
7.Delete API logo by clicking on 'trashcan' sign  
8.Click on 'OK' for user confirmation     

Expected Result: Successful in deleting API logo  
Actual Result: User unable to delete API logo     

Browser:     
1. Mozilla Firefox 48.0 
(Mozilla Firefox for Ubuntu Canonical – 1.0 )   
2. Google Chrome 52.0.2743.116

Operating System: Ubuntu 16.0 LTS

**Comment by marla-singer** [comment]
Fix this issue. The problem was due to the old variable name "apiBackend"

**Comment by saralavanip** [comment]
Verified this resolved issue in local develop environment.
