### ISSUE TITLE
Click on 'Search' icon closes search field

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1583]
Steps:  

1.Visit https://nightly.apinf.io   
2.Login   
3.Go to 'Catalog'   
4.Click on 'Search' icon (magnifying glass sign)   
 
Expected Result: It must show up search field for the user to enter search word    
Actual Result: Click on 'Search' icon closes search field  

Browser:
1. Mozilla Firefox 48.0 
(Mozilla Firefox for Ubuntu Canonical – 1.0 )   
2. Google Chrome 52.0.2743.116

Operating System: Ubuntu 16.0 LTS

**Comment by nnn** [comment]
@saralavanip please confirm.

**Comment by philippeluickx** [comment]
This is still an issue on staging, not sure if this fix got released already?

**Comment by saralavanip** [comment]
Verified resolved issue on local develop but this issue is still reproducible on https://nightly.apinf.io

**Comment by saralavanip** [comment]
@nnn , verified resolved issue on https://nightly.apinf.io  and it works as expected.
