### ISSUE TITLE
'Date created' not updating in catalog view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1595]
Steps:  
1,Visit https://nightly.apinf.io  
2.Sign in as API owner    
3.Go to 'Catalog' view    
4.Sort by 'Date created'  

Findings:   
- Shows the 'Date created' details text "Added a few seconds ago" for all APIs in the list.  

Expected Result: Sort by 'Date created' must show correct details when created for respective APIs.   

Browser:   
1. Mozilla Firefox 48.0   
2. Google Chrome 52.0.2743.116

Operating System: Ubuntu 16.0 LTS    

Screenshot:  
![catalog_allapis_same_date_created](https://cloud.githubusercontent.com/assets/13309358/18579981/98c05ba4-7c01-11e6-9471-01a58b3a58a8.png)

**Comment by bajiat** [comment]
See also #1652

**Comment by brylie** [comment]
Pr #1661 fixes this issue:

![screenshot from 2016-09-29 14-30-01](https://cloud.githubusercontent.com/assets/17307/18952149/52f524ec-8651-11e6-839b-f5fceb0e36ac.png)
