### ISSUE TITLE
Copy API Key success alert appearing twice on click

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1612]
When clicking the *copy API Key* button on the API view, the success alert appears twice:

![screenshot from 2016-09-22 12-17-53](https://cloud.githubusercontent.com/assets/17307/18742792/bbc489a6-80be-11e6-9946-beed639399d0.png)

Determine why the alert appears twice, and fix the issue.

**Comment by marla-singer** [comment]
@brylie Interested
