### ISSUE TITLE
Limit visibility of API to certain users

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1615]
Allow API owner to limit catalog and API profile visibility of an API to certain users.

# User story

> As an API owner
I want to restrict the visibility of my API to certain users
so that I can publish my API e.g. to partners
but to keep it hidden from the general public

**Comment by bajiat** [comment]
@brylie Can you check the tasks that have Closed APIs 1.0 label and are in planning? Are we missing a collection/schema?

**Comment by brylie** [comment]
@bajiat #1623 is a good place to look at the collection/schema design. In effect, we have two likely options:

- store 'authorized users' or some similar array directly in the Api document
- create a 'authorization groups' collection with foreign key fields for 'authorized users' and 'Api'

We can also determine whether to stick to convention and store user ID, or what storing email addresses would look like.
