### ISSUE TITLE
Allow only administrators to add APIs to a deployment

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1616]
The point to limit that anyone can't add any kind of API can be in other way also: To limit only Admin to be able to add API. 

# Definition of done
* [x] There is a setting where admins can select that only admins can add APIs in this deployment.
* [x] When admin has selected this admin only setting
  * [x] The link to Add API is not visible to other type of users than admins.
  * [x] Other users than admins don't have insert privileges on the APIs collection.

# Wireframe

![addapiadminprivilege](https://cloud.githubusercontent.com/assets/17976243/18868276/40f60b96-84b0-11e6-8a66-dc0a39a42b1a.png)

One more suggestion if there are future needs to implement more privileges based on user roles.
There can be a separate module named "User Role and Privileges"
This view would contain access privileges to different APINF users (Admin, API Owner, API Consumer) as radio buttons.
N - non accessible
R - Only view mode
W - View and Edit

Once a new privilege is introduced, this can be added in all three role panes.

![addapiadminprivilege2](https://cloud.githubusercontent.com/assets/17976243/18868358/9898df4a-84b0-11e6-85d7-cfea6d5bf243.png)

**Comment by bajiat** [comment]
@frenchbread Would you be interested in this task?

**Comment by frenchbread** [comment]
@bajiat self-assigned

**Comment by Nazarah** [comment]
@frenchbread : (from rocket chat, based on your sample wireframe)

Rename the header as "Access to API"

I think that in upcoming times, there would be other access privileges specific to roles.
So should any privilege for a role can be selected with radio buttons? with N - NONE, R - READ and W - WRITE accesses?
this could be added as a separate view called Role Privileges under Settings

**Comment by Nazarah** [comment]
@frenchbread wireframes added as you suggested.
Also added the wireframe to arrange privileges specific to user roles.

**Comment by bajiat** [comment]
@Nazarah Let's keep this simple for starters. So let's only do the simple setting now (first wireframe). I would rename it: "Access to API" to "Adding APIs" or "Publishing APIs"

The second wireframe we would consider later. For clarity, I would not include it in this issue. (Also, I do not understand the combination "Adding an API" and Read privilege.)
