### ISSUE TITLE
Include star rating widget in API profile and Catalog

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1618]
Reintroduce star rating into platform. Needs to be visible and editable in API catalog and API profile.

# Definition of done
* [x] Bookmarking icon and terminology needs to be distinct from star rating
  * [x] Bookmarking is called bookmark, icon can be freely chosen
  * [x] Rating uses star metaphor in icons, terminology refers to rating
* [x] Star rating is visible in Catalog (both card and table view)
* [x] Star rating is visible in API profile
* [ ] User can add and edit their rating 
  * [ ] in Catalog  (both card and table view)
  * [x] in API profile

# Wireframes

1. API Card View

![apicardnewbookmark-1](https://cloud.githubusercontent.com/assets/17976243/19039600/56f29ba2-8989-11e6-9f78-1f1d78f32f17.png)

2. API Table View

![apitablenew](https://cloud.githubusercontent.com/assets/17976243/19039623/683fedec-8989-11e6-92bc-24c51253f477.png)

3. API Profile

![apiprofilestar bookmark](https://cloud.githubusercontent.com/assets/17976243/19039667/8f3b248e-8989-11e6-99b5-0d1e89c6aca9.png)

**Comment by bajiat** [comment]
@Nazarah: Wireframe needed refers to bookmark icon and placement of bookmark and star rating in catalog and API profile

**Comment by bajiat** [comment]
@nnn Would you be interested in this task?

**Comment by nnn** [comment]
@Nazarah when will you have time for this wireframe?
We can work together on ideas.

**Comment by nnn** [comment]
Also #1625 is related to this task, and kinda depends.

**Comment by Nazarah** [comment]
@nnn lets work together.
