### ISSUE TITLE
Audit translation tokens

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1619]
Go through the en. i18n.json file. Make a project-wide search and check that each token is used. If a token is not used/found, remove the token.

**Comment by brylie** [comment]
Here is a list of all translation tokens that are in use in our HTML and JavaScript:

> aboutApinf_contributors
aboutApinf_credits
aboutApinf_documentation
aboutApinf_doneButton_text
aboutApinf_homepage
aboutApinf_intro
aboutApinf_openSource
aboutApinf_projectLinks
aboutApinf_projectVersions
aboutApinf_sourcecode
aboutApinf_sponsors
aboutApinf_support
aboutApinf_title
account_delete_button_text
account_delete_title
account_delete_warning
account_details
account_details
addApiBacklogItem_addBacklogItem_button
addApiBacklogItem_modalTitle
apiBackendRating_anonymousError
apiBacklog_addBacklogItem_buttonText
apiBacklog_mainTitle
apiBacklogList_noApiBacklogItemsFound
apiDetails_baseUrl_headingText
apiDetails_deleteButton
apiDetails_description_headingText
apiDetails_usageInstructions_headingText
apiDetails_usageInstructions_requestHeaders_text
apiDetails_usageInstructions_urlParameters_text
apiDocumentation_APICall_Warning_Message
apiDocumentation_APICall_Warning_Title
apiDocumentation_Link_Title
apiDocumentation_manageDocumentation_buttonText
apiDocumentation_No_Link_Manager_Message
apiDocumentation_No_Link_Message
apiDocumentation_No_Swagger_Manager_Message
apiDocumentation_No_Swagger_Message
apiDocumentation_sdkGenerateButton
apiDocumentation_Title
apiDocumentation_tooltipSDKGeneratorButton
apiDocumentation_Viewer_Title
apiDocumentationEditor_notAvailable
apiExport_api_description
apiExport_api_title
apiExport_json_button
apiExport_json_button
apiExport_proxy_description
apiExport_proxy_title
apiExport_title
apiExport_yaml_button
apiExport_yaml_button
apiIntro_doneLabel
apiIntro_nextLabel
apiIntro_previousLabel
apiIntro_quickTour_button_text
apiIntro_skipLabel
apiIntro_steps_backlog_intro
apiIntro_steps_details_intro
apiIntro_steps_documentation_intro
apiIntro_steps_export_intro
apiIntro_steps_feedback_intro
apiIntro_steps_metadata_intro
apiIntro_steps_proxy_intro
apiIntro_steps_settings_intro
apiIntro_steps_welcome_intro
apiKeys_copyButtonText
apiKeys_copySuccessful
apiKeys_getApiKeyButton
apiKeys_getApiKeyButton_processing
apiKeys_getApiKeyButton_success
apiLogo_resumable_acceptedExtensions
apiLogo_resumable_successfully_uploaded
apinf_usernotloggedin_error
apiProxy_headerText
apiSettings_deleteApiText
apiSettings_deleteApiTitle
apiSettings_panelTitleAbout
apiSettings_panelTitleManage
apiSettings_uploadLogo_heading
apiSettings_uploadLogoText
backlogItem_deleteButton_text
backlogItem_editButton_text
branding_panel_title
branding_save
branding_update
catalogue_bookmarkTooltip_nonUser
catalogue_bookmarkTooltip_nonUser
catalogue_BookmarkTooltip_user
catalogue_paginationButtons_next
catalogue_paginationButtons_previous
catalogue_Title
catalogue_toolbar_filterOptions_myApis
catalogue_toolbar_filterOptions_myBookmarks
catalogue_toolbar_filterOptions_showAll
catalogue_toolbar_sortBy_title
catalogue_toolbar_sortMenuOptions_averageRating
catalogue_toolbar_sortMenuOptions_bookmarkCount
catalogue_toolbar_sortMenuOptions_dateCreated
catalogue_toolbar_sortMenuOptions_name
catalogue_toolbar_sortMenuOptions_sortAscending
catalogue_toolbar_sortMenuOptions_sortDescending
catalogue_toolbar_toggleCollapse
catalogue_toolbar_viewMode_grid
catalogue_toolbar_viewMode_table
catalogueGrid_addedBy
catalogueTable_added
catalogueTable_addedBy
contactForm_email_label
contactForm_email_placeholder
contactForm_message_label
contactForm_message_placeholder
contactForm_name_label
contactForm_name_placeholder
contactForm_reset
contactForm_submit
contactForm_successMessage
Dashboard
dashboard_mainTitle
dashboard_noApisTitle
deleteAccount_closeButton
deleteAccount_confirm_text
deleteAccount_confirmDelete
deleteAccount_success_message
deleteAccount_title
deleteApiConfirmation_cancelButton
deleteApiConfirmation_confirmDeleteInformation
deleteApiConfirmation_confirmDeleteMessage
deleteApiConfirmation_confirmDeleteNote
deleteApiConfirmation_deleteButton
deleteApiConfirmation_header
deleteApiConfirmation_successMessage
deleteBacklogItem_cancelButton_text
deleteBacklogItem_confirmation_text
deleteBacklogItem_deleteButton_text
deleteBacklogItem_modalTitle
editApiMetadata_editApiMetadataForm_title
editApiMetadata_editButton
editApiMetadata_submitButtonText
editBacklogItem_modalTitle
editBacklogItem_submit_buttonText
emailTemplates_verifyEmail_message
emailTemplates_verifyEmail_title
emailVerification_successMessage
feedback_feedbackForm_button
feedback_feedbackForm_description
feedback_feedbackForm_title
feedback_main_title
feedback_no_feedback
feedback_remove_button
feedback_view_button
feedbackForm_successMessage
flagApiModal_removeApiFlag_insertMessage
flagApiModal_removeApiFlag_successMessage
flagApiModal_removeApiFlag_updateMessage
flagApiSchema_DefunctText
flagApiSchema_inappropriateText
homeBody_contactUs_heading
homeBody_contactUs_text
homeBody_feature_section_heading1
homeBody_feature_section_heading2
homeBody_feature_title1
homeBody_feature_title1_text
homeBody_feature_title2
homeBody_feature_title2_text
homeBody_feature_title3
homeBody_feature_title3_text
homeBody_feature_title4
homeBody_feature_title4_text
homeBody_feature_title5
homeBody_feature_title5_text
homeBody_feature_title6
homeBody_feature_title6_text
homeBody_feature_title7
homeBody_feature_title7_text
homeBody_feature_title8
homeBody_feature_title8_text
homeBody_openSource_imageAltText
homeBody_section1_heading
homeBody_section1_text
homeBody_section1_text_extra
homeBody_section2_heading
homeBody_section2_text
homeBody_section2_text_extra
homeBody_section3_communityLinkText
homeBody_section3_heading
homeBody_section3_text
homeBody_section3_text_extra
homeFooter_dashboardLink_text
homeHeader_apiCatalogue
homeHeader_dashboardLink_text
homeHeader_signIn
homeHeader_signUp
homeHeader_toggleNavigation
import_ApiConfiguration_Drop
import_ApiConfiguration_File
import_ApiConfiguration_Preview
import_ApiConfiguration_Title
import_ApiConfiguration_Upload
import_ApiDocumentation_File
import_ApiDocumentation_Title
importApiConfiguration_errorMessage
importApiConfiguration_jsonError_message
importApiDocumentation_fileExtensionError_message
importApiDocumentation_fileReadError_message
latestApiBackends_DateAdded
latestApiBackends_DateAdded
latestApiBackends_Heading
latestApiBackends_MoreInfo
latestApiBackends_NotFound
login
loginVerify_errorMessage
manageApiDocumentationModal_AddedFile_Message
manageApiDocumentationModal_CreateDocumentation_CancelButton
manageApiDocumentationModal_CreateDocumentation_SaveButton
manageApiDocumentationModal_CreateDocumentation_Title
manageApiDocumentationModal_DeletedFile_ConfirmationMessage
manageApiDocumentationModal_DeletedFile_Message
manageApiDocumentationModal_DocumentationLink_Title
manageApiDocumentationModal_FileType_Message
manageApiDocumentationModal_hints_createApiDocumentation
manageApiDocumentationModal_hints_documentation_link
manageApiDocumentationModal_hints_uploadApiDocumentation
manageApiDocumentationModal_LinkField_Updated_Message
manageApiDocumentationModal_openDocumentationEditor
manageApiDocumentationModal_SizeLimit_Message
manageApiDocumentationModal_Title
manageApiDocumentationModalUploadButton
masterLayout_sidebar_AddAPIBackend
masterLayout_sidebar_APIBackends
masterLayout_sidebar_Catalogue
masterLayout_sidebar_ManageAPIBackends
masterLayout_sidebar_Users
navbar_aboutButton_text
notAuthorized_Message
notAuthorized_Title
notFound_Message_Part1
notFound_Message_Part2
notFound_Title
pageTemplate_header_text
profile_Header
profile_setUsername
profile_UpdateButton
profile_updatedSuccess
profile_usernameIsTaken"
profile-usernameInvalid
proxyBackendForm_advancedSettings_title
proxyBackendForm_apiBasePath_helpText
proxyBackendForm_apiPort_helpText
proxyBackendForm_deleteButton
proxyBackendForm_deleteErrorMessage
proxyBackendForm_deleteSuccessMessage
proxyBackendForm_disableApiKey_helpText
proxyBackendForm_proxyBasePath_helpText
proxyBackendForm_publishErrorMessage
proxyBackendForm_saveButton
proxyBackendForm_successMessage
proxyBackendForm_update_successMessage
sdkCodeGeneratorModal_errorText
sdkCodeGeneratorModal_errorTextInvalidHost
sdkCodeGeneratorModal_Title
searchField_button
searchField_placeholder
searchPage_addedPrefix
searchPage_noResults
searchPage_pageHeader
searchPage_searchForm_helpText
searchPage_searchForm_placeholderText
searchPage_searchResultsHeader
settings_apiDocumentation_editor
settings_github
settings_mail
settings_mail_fromEmail_hint
settings_mail_fromEmail_label
settings_mail_password_label
settings_mail_smtpHost_label
settings_mail_smtpPort_label
settings_mail_toEmail_hint
settings_mail_toEmail_label
settings_mail_username_label
settings_save
settings_schema_onlyAdminsCanAddApis
settings_sdkCode_generator
settings_successMessage
setupNeededModal_body
setupNeededModal_title
setupNeededModal_viewBrandingButton
setupNeededModal_viewSettingsButton
signIn
signup
signUp
statisticsSummary_captionRequests
statisticsSummary_captionResponseRate
statisticsSummary_captionResponseTime
statisticsSummary_captionUniqueUsers
statusCheck_ApinfWebApp
statusCheck_ApiUmbrella
statusCheck_Elasticsearch
statusCheck_Title
statusCheck_Updated
swaggerUi_swaggerDocumentInvalidText
templateName_pageElement_additionalText
umbrella_createuser_error
updatePassword_submitButton_text
updatePasswordForm_successMessage
uploadApiLogo_confirm_delete
uploadApiLogo_successfully_deleted
uploadApiLogoButton
uploadProjectLogo_acceptedExtensions
uploadProjectLogo_confirm_delete
uploadProjectLogo_successfully_deleted
uploadProjectLogo_successfully_uploaded
userMenu_account
userMenu_branding
userMenu_profile
userMenu_settings
userMenu_signout
viewApi_Details_Title
viewApi_Metadata_Contact_email
viewApi_Metadata_Contact_phone
viewApi_Metadata_Contact_title
viewApi_Metadata_NotFound
viewApi_Metadata_Organization_title
viewApi_Metadata_Service_serviceLevelAgreement
viewApi_Metadata_Service_title
viewApi_Metadata_Service_validSince
viewApi_Metadata_Service_validUntil
viewApi_Metadata_Title
viewApiNavigationMenu_backlog
viewApiNavigationMenu_details
viewApiNavigationMenu_documentation
viewApiNavigationMenu_export
viewApiNavigationMenu_feedback
viewApiNavigationMenu_metadata
viewApiNavigationMenu_proxy
viewApiNavigationMenu_settings
viewApiSettigs_saveButton_text
viewApiStatus_statusMessage_ClientError
viewApiStatus_statusMessage_ErrorCodeText
viewApiStatus_statusMessage_ErrorCodeText
viewApiStatus_statusMessage_ErrorCodeText
viewApiStatus_statusMessage_RedirectError
viewApiStatus_statusMessage_ServerError
viewApiStatus_statusMessage_Success
visibilitySwitch_labelText
visibilitySwitch_offText
visibilitySwitch_onText

**Comment by brylie** [comment]
@bajiat my apologies. Here are the i18n tokens I missed:

> flagApiButton_buttonText_active
flagApiButton_buttonText
flagApiModal_titleText
flagApiModal_removeButton
flagApiModal_saveButton
flagApiModal_cancelButton
responseTimeDistributionChart_title
responseTimeDistributionChart_help_text
statusCodeCountsChart_title
statusCodeCountsChart_help_text
tickButtons_hour
tickButtons_day
tickButtons_week
tickButtons_month
apiSelectPicker_selectAPI
dashboardDataTable_title
dashboardDataTable_help_text
dashboardDataTable_timeStamp
dashboardDataTable_requestCountry
dashboardDataTable_requestPath
dashboardDataTable_requestIP
dashboardDataTable_responseTime
dashboardDataTable_responseStatus
dashboardDataTable_pageCount
dashboardDataTable_prevPage
dashboardDataTable_prevPage
dashboardDataTable_nextPage
dashboardDataTable_nextPage
requestsOverTimeChart_title
requestsOverTimeChart_help_text
requestsOverTimeChart_showingRecordsCount
feedback_sendFeedback
proxies_addProxy
proxies_pageHeader
proxies_noProxiesFound
proxyItem_editProxy
proxyItem_removeProxy
removeProxy_modalLabel
removeProxy_confirmRemoveProxy
removeProxy_cancelRemove
settingsMenu_profile
settingsMenu_account
settingsMenu_branding
settingsMenu_settings
settingsMenu_proxies
settings_addingApis

**Comment by brylie** [comment]
@frenchbread when creating i18n tokens in templates, please do not include a space before the underscore:

```html
<!-- not like this -->
{{ _ 'token' }}

<!-- like this instead -->
{{_ 'token' }}
```

**Comment by bajiat** [comment]
@brylie These ones I have most probably already removed:
apiSelectPicker_selectAPI
dashboardDataTable_help_text
dashboardDataTable_nextPage
dashboardDataTable_nextPage
dashboardDataTable_pageCount
dashboardDataTable_prevPage
dashboardDataTable_prevPage
dashboardDataTable_requestCountry
dashboardDataTable_requestIP
dashboardDataTable_requestPath
dashboardDataTable_responseStatus
dashboardDataTable_responseTime
dashboardDataTable_timeStamp
dashboardDataTable_title
feedback_sendFeedback
flagApiButton_buttonText
flagApiButton_buttonText_active
flagApiModal_cancelButton
flagApiModal_removeButton
flagApiModal_saveButton
flagApiModal_titleText

**Comment by bajiat** [comment]
Committed the changes to my local branch.
