### ISSUE TITLE
Organize API Profile header

### ISSUE THREAD

**Issue by nnn** [apinf/platform#1625]
I notice that we are adding new components to API Profile header and it starts to look clumsy.
### Proposition:

- [ ] Organize existing components, if needed move some components out from header
- [ ] Plan (ex. wireframe) position of future components based on backlog

**Comment by Nazarah** [comment]
@nnn what are your ideas about making the improvements

**Comment by nnn** [comment]
@Nazarah mostly to fix items position

**Comment by brylie** [comment]
I think we need to review this PR as a group. Ping @bajiat @Nazarah
