### ISSUE TITLE
Deleting an API needs to delete also Proxy backend

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1627]
If owner deletes an API from Apinf, proxy backends needs also to be deleted. Also, the corresponding API backend needs to be deleted from API Umbrella.

# Definition of done
- [x] Clicking 'Delete' on the API Profile: Settings tab deletes the Api from API Umbrella

**Comment by bajiat** [comment]
@brylie Can you provide details?

**Comment by brylie** [comment]
@bajiat I added a single condition to the definition of done. This seems like a relatively minor task, in that it is only calling a method within the delete button within the 'delete API backend' method.

**Comment by bajiat** [comment]
@jykae Would you be interested in this task?
