### ISSUE TITLE
Sprint 32 exploratory testing

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1636]
# Definition of done
* [x] Check that dashboard is not available if there is no proxy
* [ ] Add the proxy settings for the platform
* [x] Check the new sidebar menu for settings
* [x] Add API 1 without connecting it to a proxy
* [x] Add API 2 and connect it to a proxy
* [x] Check the details page for API 1 and API 2: their base URL's should be different
* [x] Get an API key for API 1
* [x] Copy API key
* [x] Edit the proxy backend settings for API 2 (API profile, Proxy tab)
* [x] Check that you can make calls after editing
* [x] Disable checking for API key for API 2 and try to make calls without API key
* [x] Export API settings (Note: tab should be available for owners and admins only)
* [x] Check the usage instructions from API profile Details tab (i.e. default view)
* [x] Test the Swagger viewer
* [x] Check that you as API owner can select your API in dashboard from the list of APIs

**Comment by preriasusi** [comment]
"Export API settings (Note: tab should be available for owners and admins only)"

You can even export settings in staging even thought you are not logged in at all.

**Comment by saralavanip** [comment]
Reported issues:  
#1689 
#1692  
#1699  
Verified and updated issues:   
#1687  
#1685 
#1588  
#1689
