### ISSUE TITLE
Warning: Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1640]
Warning showing up in my console when navigating to the detailview of an API. Tested on nightly

Related?
http://stackoverflow.com/questions/26629835/meteor-v-1-0-and-ironrouter

**Comment by bajiat** [comment]
@philippeluickx What is the error message?

**Comment by bajiat** [comment]
@frenchbread Is this related to #1565 and #1605?

**Comment by bajiat** [comment]
@brylie You had an idea where this message is coming from.

**Comment by brylie** [comment]
@bajiat the problem may be within the [`viewApi` route code](https://github.com/apinf/platform/blob/develop/apis/client/lib/router.js#L15-L33).

**Comment by ilarimikkonen** [comment]
not reproduced
