### ISSUE TITLE
Clicking on "click here" to add API backend on empty dashboard does not work

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1643]
On nightly. When you have no API backends, there is this text:

> You don't have any API Backend you manage. 
> To add an API Backend, click here.

Clicking on "click here" does nothing.

**Comment by bajiat** [comment]
@frenchbread Could you verify whether you get the same error?

**Comment by bajiat** [comment]
@frenchbread Would you have time to take a look at the bug?

**Comment by bajiat** [comment]
Suggestion for the text:

You don't have any API Backend you manage. 
Add an API Backend

The second line could be a link

**Comment by frenchbread** [comment]
@bajiat I'd suggest @nnn to take a look at this bug, since he's more familiar with the placeholder on dashboard page

**Comment by frenchbread** [comment]
As said in #1641:
> Since we deprecated addApiBackend-wizard, the pathFor value (the URL) has not been changed. Changing the href parameter value for <a> tag should resolve this.
