### ISSUE TITLE
Sync from Umbrella not functioning as expected

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1654]
<img width="875" alt="nayttokuva 2016-09-29 kello 10 38 34" src="https://cloud.githubusercontent.com/assets/293452/18945017/1949b534-8631-11e6-9a5f-ed7a36344aac.png">

Cool API is added from frontend, others are added by synchronization. Missing fields.
Should we disable this or fix?

**Comment by bajiat** [comment]
Part of #1533
