### ISSUE TITLE
Export API proxy configuration fails

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1655]
Export JSON returns json file with "undefined" string.

Export YAML returns exception:

<img width="582" alt="nayttokuva 2016-09-29 kello 11 32 48" src="https://cloud.githubusercontent.com/assets/293452/18946743/e994fe54-8638-11e6-8b13-5aae6073a0df.png">

**Comment by bajiat** [comment]
@jykae I could not reproduce the error. Can you add steps to reproduce? Or check if the error still exists?

**Comment by bajiat** [comment]
@jykae Can you check this one?

**Comment by jykae** [comment]
@bajiat assigned

**Comment by jykae** [comment]
@bajiat this is fixed, all exports work in latest develop.

credits go to @nnn 

<img width="1014" alt="nayttokuva 2016-10-28 kello 10 52 31" src="https://cloud.githubusercontent.com/assets/293452/19798980/bc86707a-9cfc-11e6-8623-7a73747562e2.png">

**Comment by jykae** [comment]
I will close this one.
