### ISSUE TITLE
Rate limiting response_headers should work like radio button

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1684]
Left as enhancement:
User should be able to select only one **'show rate limit in response headers'** value when multiple rate limit rules are defined. This is used as the primary `response_headers` value on API Umbrella, and there can be only one primary rule.

<img width="1162" alt="nayttokuva 2016-10-03 kello 17 59 02" src="https://cloud.githubusercontent.com/assets/293452/19042031/1c00efd0-8993-11e6-8ece-ae9672ac2a19.png">

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and it works as expected.

Screenshot:  

![screenshot 65](https://cloud.githubusercontent.com/assets/13309358/20386993/b045145e-acc6-11e6-9b21-1a16df216b1f.png)
