### ISSUE TITLE
Investigate whether user account emails are required to be unique

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1685]
We would like to ensure that user account emails are unique in our system. Most likely, this is already handled by our accounts package, but we want to be certain. Test whether users can sign-up with duplicate email accounts.

**Comment by saralavanip** [comment]
Verified this test scenario on https://nightly.apinf.io. 
Findings: 
- Currently it doesn't allow 'Sign up with duplicate user names or emails accounts'

**Comment by brylie** [comment]
OK, thanks @saralavanip.

@bajiat should we close this issue, since the user emails/usernames are unique?

**Comment by bajiat** [comment]
@brylie I will close the issue.
