### ISSUE TITLE
Administrators cannot see private APIs when not in the managers list

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1686]
Originally reported by @marla-singer in #1669 

Right now, Apinf admin users **can't see private APIs**

# Screenshots

1. User is Apinf Administrator. Catalog has 4 apis
![joxi_screenshot_1475577095313](https://cloud.githubusercontent.com/assets/20643403/19071215/9851aad0-8a37-11e6-8159-9612bdc23d7c.png)

2. Log in like one of api owner. Set api as private
![joxi_screenshot_1475577239491](https://cloud.githubusercontent.com/assets/20643403/19071219/9f6a2d88-8a37-11e6-8284-b3c3eb0e30d7.png)

3. Log in like Apinf administrator. Catalog has 3 apis
![joxi_screenshot_1475577184490](https://cloud.githubusercontent.com/assets/20643403/19071226/a47bb86e-8a37-11e6-9fd9-e31352224422.png)

**Comment by bajiat** [comment]
@marla-singer Can I assign this task to you?

**Comment by marla-singer** [comment]
@bajiat Let me check, maybe this problem was resolved in PR #1697.

**Comment by marla-singer** [comment]
@bajiat Yeah, like I supposed It already resolved. Admin has permissions watch others private api. See screenshot below. 
![joxi_screenshot_1475828770357 1](https://cloud.githubusercontent.com/assets/20643403/19183470/2973746c-8c81-11e6-8870-a5a958350277.png)

**Comment by jykae** [comment]
Yes, added admin cases also for #1697

**Comment by bajiat** [comment]
@jykae Great! Can you add "closes #1686" to your PR

**Comment by jykae** [comment]
@bajiat Yep
