### ISSUE TITLE
'Get API key' feature missing in API view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1687]
Steps:  
1.Visit https://nightly.apinf.io  
2.Create account by clicking on 'Sign Up'  
3.Go to API Backends and click on 'Add API Backend'  
4.Enter details and click on 'Add' button 

Findings:  
- 'Get API Key' feature is not available in API view 

Expected Result: Get API key feature must be available in API view

**Comment by bajiat** [comment]
@saralavanip Did you attach the API to a proxy? We have separated publishing API (to Catalog) and adding proxy / API management features. After you have added an API, go to Proxy tab and attach the API to a proxy.

**Comment by saralavanip** [comment]
@bajiat , Thanks for the update. 
Rechecked feature 'Get API Key' available only if API is connected to proxy.

**Comment by bajiat** [comment]
@saralavanip Thanks for verifying.

Closing the issue
