### ISSUE TITLE
No response while edit and submit 'Proxy' form

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1689]
Steps:  
1.Visit https://nightly.apinf.io  
2.Create account by clicking on 'Sign Up'  
3.Go to API Backends and click on 'Add API Backend'  
    -Enter Name 
    -Enter Description    
    -Enter URL (Eg. https://developers.google.com/books/)  
4.Enter details and click on 'Add' button  
5.Click on 'Proxy'  
6.Enter the proxy details  
    -Enter 'Proxy Base path' (eg./test_google_books/ )   
    -Enter  API base path (eg. / )    
    -Click on 'Save&Publish' button    
7.Edit the details (eg. proxy base path with ('/test_google_ebooks/ ) 
8.Click on 'Save&Publish' button    

Expected Result: Notify user with successful message or error messages if any. 
- Details view must show updated API URLs : https://nightly.apinf.io:3002/test_google_ebooks/     

Actual Result: No response while edit and submit form. 
- Refreshing page updates the proxy details in the form, but doesn't update the URLs in 'Details' view.  
- The API URLs in 'Details' view are shown as : https://nightly.apinf.io:3002/test_google_books/

**Comment by bajiat** [comment]
@saralavanip Try refreshing the page and see if the changes actually got saved. This is quite likely a bug, but we would like to get more details.

**Comment by saralavanip** [comment]
@bajiat , Refreshing page would update its details in proxy form, but doesn't update API URL or URL in usage instructions(Details view).

**Comment by bajiat** [comment]
@marla-singer Could you take this one as well? It's related to the user instructions.

**Comment by marla-singer** [comment]
@bajiat Yes, I'm taking it.

**Comment by marla-singer** [comment]
@bajiat This issue isn't relevent. Verified on nightly. Now Proxy settings work correctly so URL in 'Details' tab is updated as expected.
