### ISSUE TITLE
'Email Reset password link' not working

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1692]
# Steps  
1. Visit https://nightly.apinf.io    
2. Create account by clicking on 'Sign up'   
    -  Enter username    
    -  Enter email address  
    -  Enter password    
3. Click on 'Register'   
4. Log out   
5. Click on 'Login'    
    -  Enter username    
    -  Click on 'Forgot password'    
6. Enter 'Email address'    
7. Click on 'Email Reset link'    

# Expected Result
 Reset password link must be sent to the given email address

# Findings
-  'Reset password link' not sent to the given (registered) email address    
-  Displays successful message 'Email Sent'

**Comment by bajiat** [comment]
@marla-singer Could you verify this error once nightly is back online? It is possible that email has not been enabled, but check if this error exists if there are email settings.

**Comment by marla-singer** [comment]
@bajiat Do you mean this email settings? 
![joxi_screenshot_1475845510781](https://cloud.githubusercontent.com/assets/20643403/19190764/f97307f6-8ca7-11e6-979a-dcec5a2e4fc0.png)

**Comment by marla-singer** [comment]
@jykae Could you please set the right email settings on nightly? My attempts of set the correct email settings on localhost didn't culminated successful. Well, you remember I faced with this problem when was reviewing the feature 'Verification e-mail' the last time

**Comment by marla-singer** [comment]
@bajiat If there are email settings, I have an error "Interval server error"
But it also can be because of the incorrect mail settings :worried:
![joxi_screenshot_1476091764023 1](https://cloud.githubusercontent.com/assets/20643403/19232034/2309e536-8ee6-11e6-90a7-ae6e10f18684.png)

**Comment by brylie** [comment]
This seems to be resolved, at least on apinf.io. It was probably related to settings, or was fixed right before Mindtrek.
