### ISSUE TITLE
'Add API backend' not updating dashboard view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1699]
# Steps  
1. Visit https://nightly.apinf.io    
2. Sign up   
3. Go to API Backends  and click on 'Add API Backend'  
4. Enter details    
5. Click on 'Add' button   
6. Go to 'Proxy'   
7. Enter proxy configuration details    
8. Click on 'Save&Publish' button    
9. Go to 'Dashboard'    

# Expected Result
Dashboard view must be updated while API backend added successfully.

# Findings  
Added API still shows 'No APIs to Manage' in dashboard view  

# Screenshot
![dashboard_view_no_api_added](https://cloud.githubusercontent.com/assets/13309358/19144906/e2f5c0a2-8bb4-11e6-8b06-9f8913efe9fe.jpg)

**Comment by bajiat** [comment]
@frenchbread Any ideas?

**Comment by frenchbread** [comment]
@nnn Could you please check this one, since you've been woking on this feature?

@bajiat

**Comment by bajiat** [comment]
@saralavanip Could you verify this once nightly is available? This is probably resolved.

**Comment by bajiat** [comment]
@saralavanip Can you verify this in nightly?

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://nightly.apinf.io  

Findings: 
- Only the latest API added is shown in dashboard view. So, analytics can be viewed only for the latest API, but not for the previously added APIs.  

Screenshots:    
![selection_022](https://cloud.githubusercontent.com/assets/13309358/19594401/8a54ab36-978d-11e6-870b-e53c872504c3.jpg)     

![selection_020](https://cloud.githubusercontent.com/assets/13309358/19594431/9db70976-978d-11e6-92c4-1ae6dd70333c.jpg)    

![selection_024](https://cloud.githubusercontent.com/assets/13309358/19594472/db7fdc6a-978d-11e6-8093-c22b917d7dce.jpg)

**Comment by bajiat** [comment]
@saralavanip Can you provide more information?
- Are all of these APIs you own?
- Can you select from the list?
- What is it you can / cannot see?
- Do you have any calls for any of them?

**Comment by saralavanip** [comment]
@bajiat , here are the more details:

- Yes, I added these APIs : 'My APIs'    
- Only the latest API added is shown in 'Select API's' list  and it can be selected.
- 'Select-API's doesn't show previously added API's so cannot view their related analytics.
- I have calls for previously added APIs and they cannot be viewed.  
- I can view only the analytics of latest API added.

**Comment by marla-singer** [comment]
@bajiat Unfortunarly I don't have the old apis and couldn't reproduce it on nightly. Nevertheless, I looked for the old someone else's apis and didn't find any one with fill proxy. 
Now all Sarala's apis are available on Dashboard: **Test_Data_Api**, **Test_LanguageAPI**, **Test_CalendarAPI**

![2016-10-26 12 50 23](https://cloud.githubusercontent.com/assets/20643403/19722387/2bc17fe0-9b7f-11e6-91cd-45748fb1a5ef.png)

On apinf.io I detected another thing: no one apis are available on Dashboard. It can be explained by error in browser console: `TypeError: Cannot read property 'currentUserIsManager' of undefined`
But it doesn't repeat on nightly or dev environment

**Comment by bajiat** [comment]
@marla-singer 

I can reproduce this even in nightly. I'm logged in with my **non-admin** account. With this account I have added two APIs, see screenshot for My APIs:

<img width="717" alt="nightly-myapis" src="https://cloud.githubusercontent.com/assets/11626388/19724384/84a08f62-9b88-11e6-8fc3-8cbe979974f7.png">

But if I go to Dashboard, I can see only one of them in the Select API list:

<img width="664" alt="nightly-dashboard" src="https://cloud.githubusercontent.com/assets/11626388/19724409/a0c3c2a4-9b88-11e6-8064-a81704db36c4.png">

**Comment by bajiat** [comment]
In **apinf.io**, if I'm logged in as **owner**, I see the only API I have added there in Dashboard:
<img width="680" alt="apinf-dashboard" src="https://cloud.githubusercontent.com/assets/11626388/19724507/5856a436-9b89-11e6-833c-4fdd105a7018.png">

If I'm logged in as **admin**, I should see all APIs added to the platform, but I see only admin API.

<img width="673" alt="apinf-dashboard-admin" src="https://cloud.githubusercontent.com/assets/11626388/19724563/a5b562da-9b89-11e6-8435-ccdd9393730f.png">

**Comment by marla-singer** [comment]
@bajiat Please don't forget that you can see apis in Dashboard if your apis are connected to proxy.
Your second api "PTV TestingAddingAPI" **doesn't have proxy backend**
![joxi_screenshot_1477482488962](https://cloud.githubusercontent.com/assets/20643403/19724878/54901452-9b8b-11e6-9b6e-fbfc54150df2.png)

**Comment by marla-singer** [comment]
@bajiat 
>In apinf.io, if I'm logged in as owner, I see the only API I have added there in Dashboard:

These is the correct behaviour. Owner can see only own apis in Dashboard

>If I'm logged in as admin, I should see all APIs added to the platform, but I see only admin API.

These isn't correctly. But it appears only on apinf.io, can't catch error on localhost yet

**Comment by bajiat** [comment]
@marla-singer 
> Please don't forget that you can see apis in Dashboard if your apis are connected to proxy.
Your second api "PTV TestingAddingAPI" doesn't have proxy backend

You are right about this, I did not check the proxy settings. My bad. But I went and added the proxy settings to the other API in nightly and I still only see one API in the  Select API list: Kasviplanktonrajapinta. I even checked that in another browser to see it was not a browser issue.

**Comment by bajiat** [comment]
>In apinf.io, if I'm logged in as owner, I see the only API I have added there in Dashboard:
>These is the correct behaviour. Owner can see only own apis in Dashboard

I agree with you that this is 100% correct behavior.

The behavior for admin user in apinf.io is pretty weird. It should show My Apis (if any), Other APIs (if any) and admin API for admins. Hard to understand why there would be a difference between nighly and apinf.io.

**Comment by marla-singer** [comment]
@bajiat It's strange. As Apinf administrator I can see your api on nightly. I will try to reproduce it on localhost
![dashboard](https://cloud.githubusercontent.com/assets/20643403/19725705/b8ce4a3e-9b8f-11e6-8c21-74420e7f19c6.png)

**Comment by marla-singer** [comment]
@bajiat Yeah! Could do it on nightly :sweat_smile: Don't know why it so, but reproducing it good too

**Comment by brylie** [comment]
I have verified that only the latest API backend with proxy configuration shows up in the **Select API(s)** dropdown, as a non-admin user. Here is a screen capture:
![peek 2016-10-26 15-24](https://cloud.githubusercontent.com/assets/17307/19725795/497afd5c-9b90-11e6-84a0-c8604e4683bb.gif)

**Comment by marla-singer** [comment]
@brylie Nope, it isn't so. New api  pushes old api form Dashboard filtering.
Screenshots:
1. I'm owner and have only one old api
![joxi_screenshot_1477485136918](https://cloud.githubusercontent.com/assets/20643403/19726081/c17a44e2-9b91-11e6-8a2e-e44d82cc772f.png)

2. Go to Dashboard and can see my api in filtering
![dashboard-1](https://cloud.githubusercontent.com/assets/20643403/19726156/17e58e4a-9b92-11e6-9f7e-846b085dfa93.png)

3. Create another one. I have two apis
![joxi_screenshot_1477485136918 1](https://cloud.githubusercontent.com/assets/20643403/19726165/24f17c20-9b92-11e6-8b98-936b3224dca0.png)
![joxi_screenshot_1477485136918 2](https://cloud.githubusercontent.com/assets/20643403/19726173/2f67116a-9b92-11e6-9b44-3dbd931794eb.png)

4. Go to dashboard and see the last one
![dashboard-2](https://cloud.githubusercontent.com/assets/20643403/19726174/34cd8fd0-9b92-11e6-9a64-4431e58b82a6.png)

5. Go to last api and delete all proxy backend information. Go to dashboard and see the next
![joxi_screenshot_1477485136918 3](https://cloud.githubusercontent.com/assets/20643403/19726180/3eb0d3a4-9b92-11e6-80f0-2e2227a46da4.png)

5. Go to last api and delete it. Go to dashboard and see the first api!
![dashboard-3](https://cloud.githubusercontent.com/assets/20643403/19726189/474891be-9b92-11e6-9e70-1f5a6fc7a560.png)

**Comment by brylie** [comment]
Right, that was what my screencast was supposed to show. I deleted the original comment while rendering a new screencast:

![peek 2016-10-26 15-43](https://cloud.githubusercontent.com/assets/17307/19726339/24b2d172-9b93-11e6-92a1-0c69d39b261c.gif)

**Comment by marla-singer** [comment]
@bajiat @brylie Start to work on this issue

**Comment by brylie** [comment]
@marla-singer ok. Go ahead and assign yourself here.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io and it works as expected. 

Screenshots:  
![screenshot 58](https://cloud.githubusercontent.com/assets/13309358/20301254/3b3a4266-ab2b-11e6-87de-643fc6bc48e5.png)

![screenshot 57](https://cloud.githubusercontent.com/assets/13309358/20301260/42dc0af4-ab2b-11e6-9bb2-fa106a7b8471.png)
