### ISSUE TITLE
Incorrect work of deleting file

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1701]
Step to reproduce:
1. Go to Documentation tab and open Manage model.
2. Choose file and delete it . Don't click another button. Only **Choose file** and **Delete file**

Found result: Swagger body didn't remove
Screenshot:
![joxi_screenshot_1475742125450](https://cloud.githubusercontent.com/assets/20643403/19145330/268aa998-8bb7-11e6-8220-de32a0a48ef9.png)

Expected result: Empty scope 
Screenshot:
![joxi_screenshot_1475742151977](https://cloud.githubusercontent.com/assets/20643403/19145407/7861ef7e-8bb7-11e6-80ec-e6653c8b4b51.png)

**Comment by saralavanip** [comment]
@marla-singer , verified this issue on https:nightly.apinf.io . The swagger document text  also rendered in 'Details' view of all 'My APIs' . Please find the screenshot  attached.  

Screenshot:  
![allapis_view_swaggertest](https://cloud.githubusercontent.com/assets/13309358/19149975/350b9124-8bcd-11e6-8269-30c075ef882b.jpg)
