### ISSUE TITLE
Check platform and branding settings on migration.apinf.io

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1711]
Make sure that migration.apinf.io has relevant settings that are valid for production environment

# Definition of done
* [ ] admins for Apinf and Api Umbrella
* [ ] proxy
* [ ] Elasticsearch
* [ ] OAuth
* [ ] SDK generator
* [ ] email (to and from)
* [ ] branding, incl. Apinf logo

**Comment by bajiat** [comment]
@shaliko: Can you make sure @jykae has access?

**Comment by shaliko** [comment]
@bajiat Checked with @jykae, he is admin now.
