### ISSUE TITLE
Fix one automated test

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1713]
Our UI has changed quite significantly since automated tests were created. Take one automated test case and update it to match current UI.

You can find the tests and any related instructions from https://github.com/apinf/apinf-testing.

**Comment by marla-singer** [comment]
@apinf/developers I'm working on the issue "adding api"

**Comment by nnn** [comment]
on "registrationtests.js"

**Comment by marla-singer** [comment]
### Changes from my side
1. common.js
 - Fix Log in
 - Fix navigation to Dashboard
 - Fix sign up
 - Fix deleting user
2. addapibackendutils.js
 - Rewrite feature of adding api
3. addapibackend.js
 - Rewrite condition for require fields, for unique field
 - Fix "after hook"

**Comment by jykae** [comment]
I'm taking viewapibackend.js

**Comment by marla-singer** [comment]
I'm workingn on manageapibackend.js : the part of document manipulation.

**Comment by jykae** [comment]
@marla-singer have you fixed common.js ? viewapibackend.js has dependencies to it, could you open PR upstream?

**Comment by marla-singer** [comment]
@jykae Shoul I open PR in thie repo?

**Comment by jykae** [comment]
@marla-singer yep, in this repo. Include just common.js if you have some fixes for it, other files could have separate PRs. common.js is dependency for most

**Comment by marla-singer** [comment]
@jykae Done. https://github.com/apinf/apinf-testing/pull/2

**Comment by philippeluickx** [comment]
Just wanted to say: hooray for tests!
