### ISSUE TITLE
Write one unit test case

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1714]
This task is for 2nd week of sprint 33. Get your feet wet with unit testing. 
# Resources
- Meteor Guide: [Testing](https://guide.meteor.com/testing.html)

**Comment by mauriciovieira** [comment]
👏

**Comment by bajiat** [comment]
@brylie Can you link the Meteor guide.

**Comment by brylie** [comment]
Done.

**Comment by mauriciovieira** [comment]
Related to #1506

**Comment by mauriciovieira** [comment]
More resources

http://www.east5th.co/blog/2016/05/02/meteor-unit-testing-with-testdoublejs/
http://courses.ics.hawaii.edu/ics314s17/morea/testing/reading-screencast-meteor-unit-testing.html
