### ISSUE TITLE
Mail settings don't exist, but verification email is enabled

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1719]
Verified on the nightly. Mail settings don't exist.
Sign out and go to Login page. 

Found result on screenshots:
![joxi_screenshot_1475846958641](https://cloud.githubusercontent.com/assets/20643403/19191601/dd3d25d6-8cab-11e6-8bbe-a6934947764d.png)
![joxi_screenshot_1475847022739](https://cloud.githubusercontent.com/assets/20643403/19191604/dfadb18c-8cab-11e6-8c08-bc2b1d8b09c9.png)

Expected result: Don't show on  users verification if mail settings don't exist

**Comment by brylie** [comment]
I am working on this issue and will disable the *re-send verification email* link when email is not configured.
