### ISSUE TITLE
User unable to login

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1725]
Steps:

1. Visit https://nightly.apinf.io  
2. Click on 'login'  
3. Enter username  
4. Enter password  

Expected Result: Successful login with registered username/email and password   
Actual: Displays message 'Sent you an email. Please verify' .No email sent to registered email address. If clicked on 'Send again' -enter registered email address-shows 'Already verified' 

Browser:   
1. Mozilla Firefox 48.0   
(Mozilla Firefox for Ubuntu Canonical – 1.0 )     
2. Google Chrome 52.0.2743.116 

Operating System: Ubuntu 16.0 LTS

Screenshot:  
![selection_006](https://cloud.githubusercontent.com/assets/13309358/19232445/7bd79be8-8ee8-11e6-9e54-a3cc8b8aa42c.jpg)    

![selection_007](https://cloud.githubusercontent.com/assets/13309358/19232613/67f80ca6-8ee9-11e6-88a4-bdd99653813a.jpg)

**Comment by bajiat** [comment]
@brylie Please check if your PR is closing this issue as well.
