### ISSUE TITLE
User unable to Register

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1726]
Steps:

1. Visit https://nightly.apinf.io    
2. Click on 'Sign up'    
3. Enter username      
4. Enter  'Email' address   
5. Enter 'Password'    
6. Click on 'Register'   

Expected Result: Successful Register/ create account and confirmation email sent to the user successfully.  
Actual Result: Displays 'Email sent. Please verify' , but no confirmation email sent to the user.  

Browser:   
1. Mozilla Firefox 48.0   
(Mozilla Firefox for Ubuntu Canonical – 1.0 )   
2. Google Chrome 52.0.2743.116    

Operating System: Ubuntu 16.0 LTS

Screenshot:    
![selection_008](https://cloud.githubusercontent.com/assets/13309358/19232935/4018c566-8eeb-11e6-9ca9-992a35c7f071.jpg)

**Comment by bajiat** [comment]
@brylie Please check if your PR is closing this issue as well.
