### ISSUE TITLE
Email verification issues

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1727]
Login attempt verifier should turn off, when mail is disabled. Currently turning on is only happening.
Method: https://github.com/apinf/platform/blob/develop/settings/server/methods.js#L31
is called from:
https://github.com/apinf/platform/blob/develop/settings/server/startup.js
https://github.com/apinf/platform/blob/develop/settings/client/autoform.js#L6

Related: #1725 #1726

**Comment by bajiat** [comment]
@brylie Please check if your PR is closing this issue as well.
