### ISSUE TITLE
Allow user with admin role to login without email verification

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1728]
To prevent further so called "black box lock-out" happening, allow users with admin role to log in without verified email address

Related: #1725 #1726 #1727

**Comment by bajiat** [comment]
+1

**Comment by bajiat** [comment]
Potential idea: set all existing **admin** users email verified as true, when email verification is enabled.

**Comment by bajiat** [comment]
@marla-singer Would you be interested in this task?

**Comment by marla-singer** [comment]
@bajiat Yeah, why not. Your potential idea is the same as my one
