### ISSUE TITLE
Modify Quick tour message for the following

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1729]
- [ ] Documentation
- [ ] Metadata
- [ ] Backlog
- [ ] Export
- [ ] Settings
- [ ] Proxy

**Comment by Nazarah** [comment]
* Documentation
![image](https://cloud.githubusercontent.com/assets/17976243/19235111/54967634-8ef8-11e6-916d-1c932fd891de.png)
> "You can upload and share documentation describing your API here. API users can afterwards download example code in their preferred language/platform."

* Metadata
![image](https://cloud.githubusercontent.com/assets/17976243/19235157/929bda0a-8ef8-11e6-9432-15bde5ec8b35.png)
> "You can provide organizational, contact and service related information about your API here."

* Backlog
![image](https://cloud.githubusercontent.com/assets/17976243/19235172/b05a5a9e-8ef8-11e6-9b55-88623c3e523a.png)
> "You can add upcoming API features with priorities for the community to see."

* Export
![image](https://cloud.githubusercontent.com/assets/17976243/19235192/d58dc224-8ef8-11e6-985b-242f58ff48af.png)
> "You can download .json or .yaml file about your API here  for backup and migration."

* Settings
![image](https://cloud.githubusercontent.com/assets/17976243/19235228/17c40978-8ef9-11e6-8a7d-ade4d23e1fc1.png)
> "You can edit API settings and also delete your API here."

* Proxy
![image](https://cloud.githubusercontent.com/assets/17976243/19235244/322240fa-8ef9-11e6-8fee-e66036f306d3.png)
> "You can attach your API to a proxy here and. This allows to use various API management features (e.g. Analytics, API Key, etc.)"

**Comment by bajiat** [comment]
I would keep the current wording: shorter, straight to the topic. Closing the issue.
