### ISSUE TITLE
Dashboard - Dropdown doesn't populate list of APIs

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1731]
# Steps to reproduce
* login to nightly.apinf.io
* make sure you have an API and is connected to a proxy.
* click on dashboard.
* Click on "Select API" dropdown.
* Result: dropdown doesn't populate list of APIs for which analytics can be viewed.
![image](https://cloud.githubusercontent.com/assets/17976243/19235820/aebae3a8-8efc-11e6-98d9-71691557842e.png)

# Expected Result
* List of APIs for which proxy has been configured should appear in the dropdown

# Test Environment
* OS: Windows 8
* Browser: Chrome

**Comment by nnn** [comment]
I don't have this bug, the latest develop. Did you add any?

**Comment by bajiat** [comment]
@brylie Can you verify whether it was fixed already?

**Comment by brylie** [comment]
Jep. This may be resolved in recent commits.
