### ISSUE TITLE
API tabs: Console error on API Details

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1733]
Verified on nightly

**Steps**: Go to any api and open Console tab in Dev Tools
**Error**: `Exception in template helper: Error: $in needs an array`
**Screenshot**:
![2016-10-10 15 41 13](https://cloud.githubusercontent.com/assets/20643403/19236478/574a25c6-8f00-11e6-8528-f2e0fdb1cbaf.png)

**Comment by bajiat** [comment]
@marla-singer What are the steps to reproduce this console error?

**Comment by marla-singer** [comment]
@bajiat Nothing specific. Just go to nightly, open console in your browser and go to any api

**Comment by nnn** [comment]
@bajiat interested

**Comment by bajiat** [comment]
@marla-singer Can this error still be reproduced?

**Comment by marla-singer** [comment]
@bajiat No one error in console. The issue isn't already relevant

**Comment by bajiat** [comment]
Thanks @marla-singer! Closing the issue
