### ISSUE TITLE
Update password: Incorrect 'current password' error

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1734]
Steps:

1. Visit https://nightly.apinf.io  
2. Login  
3. Navigate to 'Account' view  
4. Go to 'Update password'  
5. Enter incorrect current password   
6. Enter valid new password  
7. Confirm new password: Repeat entering the same above password   
8. Click on 'Change password'  

Expected Result: Displays error message 'Invalid Current password' or highlights 'Current password' field with error message.  
Actual Result: Displays 'User confirmation' dialog and error message simultaneously.   
                    -    Error message is not explanatory: "Incorrect password [403] "

Screenshot:   
![incorrect_currentpwd_2msgs](https://cloud.githubusercontent.com/assets/13309358/19236593/df5a5d46-8f00-11e6-92e7-1472bcd85efc.jpg)

**Comment by bajiat** [comment]
@saralavanip Confirm password change is not an APInf dialog. It is a system or browser password manager dialog. can we close this?

**Comment by brylie** [comment]
@saralavanip I added a blank line after the 'steps:' line, and a dot ( . ) after the '1' in your issue description. These little details allow Github to render the list correctly.

**Comment by brylie** [comment]
I will try changing my password today, to reproduce this issue.

**Comment by brylie** [comment]
I am able to change my password on the current `develop` branch:

![screenshot_20161011_142059](https://cloud.githubusercontent.com/assets/17307/19268599/fca73be0-8fbd-11e6-96dd-a77156a75258.png)

Please make sure to disable your password manager when testing this feature.

**Comment by bajiat** [comment]
Works as expected. Closing the issue.
