### ISSUE TITLE
API tabs: doesn't work feedback vote

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1735]
Verified on nightly
Doesn't work feedback vote

**Steps**: 
1. Go to API and add any feedback
2. Click on arrow (up or down)

**Found**: Console error `Error invoking Method 'submitVote': Internal server error [500]` and nothing else

**OS**: debian 8
**Browser**: Chrome

**Comment by nnn** [comment]
@bajiat interested

**Comment by bajiat** [comment]
Please check different user roles: API owner, user who created the feedback, other regular user.

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and it works as expected.
