### ISSUE TITLE
Update password error

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1737]
# Steps
1. Visit https://nightly.apinf.io  
2. Login  
3. Navigate to 'Account' view  
4. Go to 'Update password'  
5. Enter correct 'Current password'  
6. Enter  'New password'  (eg. same as above current password)  
7. Confirm new password: Repeat entering the same above password  
8. Click on 'Change password'  

Expected Result: Notify user if current and new passwords are same or no change found. 

Actual Result: Displays successful message 'Password updated'      
# Browser
1. Mozilla Firefox 48.0 
2. Google Chrome 52.0.2743.116
# Operating System

 Ubuntu 16.0 LTS

**Comment by brylie** [comment]
@bajiat this does not seem to be a bug. It possibly an enhancement, but I am not sure how this negatively impacts the user.

In effect, someone can change their password to the same password, without any problem.

**Comment by brylie** [comment]
I recommend closing this issue, or filing it as an enhancement (with a description of how it might negatively affect an user).
