### ISSUE TITLE
API Profile - Remove "Bookmark/Unbookmark" text from the button

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1738]
As enhancement remove "Bookmark/Unbookmark" text from the button leaving just an icon.
There should be a clear indication of bookmarked state as well unbookmarked.

![image](https://cloud.githubusercontent.com/assets/17976243/19237065/75b369b6-8f03-11e6-846f-2631ec1f85c8.png)

**Comment by nnn** [comment]
We were planning to remove text at all, leaving just an icon.
"Remove Bookmark" will take too much space.

**Comment by Nazarah** [comment]
Good solution. As long as there is the correct text/icon, don;t have any problem.
