### ISSUE TITLE
Call API : Analytics not shown on dashboard

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1739]
Steps:

1. Visit https://nightly.apinf.io  
2. Login  
3. Add API Backend with proxy  
4. Go to API Details view  
5. Call API : click  on URL in usage instructions  
6. Go to Dashboard  

Expected Result: 
- Analytics shown for above selected API   

Findings:
    
-  'Select API' drop down menu doesn't list the API s added  
-  Analytics not shown in Dashboard view       

Browser:

1. Mozilla Firefox 48.0 
  - (Mozilla Firefox for Ubuntu Canonical – 1.0 )       
2. Google Chrome 52.0.2743.116     

Operating System: Ubuntu 16.0 LTS    

Screenshot:  
![selection_009](https://cloud.githubusercontent.com/assets/13309358/19237517/f0bdbc90-8f05-11e6-966f-fa8ecefb2c33.jpg)

**Comment by brylie** [comment]
@saralavanip I added a new line directly after the 'steps:' line in your issue description. It seems that markdown lists must be preceeded by a blank line. Also, thanks for improving the markdown in your issue reports, as it helps improve readability :smiley:

**Comment by brylie** [comment]
I am working with this code today, so will try to reproduce this bug.

**Comment by brylie** [comment]
I was able to duplicate this bug using the latest `develop`. Following the steps to reproduce, no APIs appear in the 'select api' dropdown menu as a non-admin user.

**Comment by frenchbread** [comment]
Check #1754
