### ISSUE TITLE
API Profile - Proxy Tab: show alert/error texts using css alert text to separate them from rest of other texts

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1740]
If an error text appears under proxy base path or API base path fields, it can't be distinguished from other texts.
Add css alert class to separate the error texts
![image](https://cloud.githubusercontent.com/assets/17976243/19237748/1f29bfd8-8f07-11e6-9be2-d730146cb88d.png)

**Comment by nnn** [comment]
Already in develop with this commit https://github.com/apinf/platform/pull/1722/commits/5c75a190a38ca494544f4415e257d655d4d85695
