### ISSUE TITLE
pathFor couldn't find a route named "manageApiBackends"

### ISSUE THREAD

**Issue by frenchbread** [apinf/platform#1743]
![screen shot 2016-10-10 at 16 46 39](https://cloud.githubusercontent.com/assets/2122679/19238212/267fb632-8f09-11e6-90df-0cce9b701aeb.png)

### Actual behaviour:
- Clicking on "Manage APIs" does not do anything.
- `pathFor couldn't find a route named "manageApiBackends"` is logged in browser console

### Expected
- My managed APIs page opens

**Comment by bajiat** [comment]
Alternative option: remove the link to Manage APIs
