### ISSUE TITLE
Api tabs: anonymous user has access to feedback manipulation

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1744]
Verified on nightly
Anonymous user has access to feadback manipulation

**Steps**:

1. Create any feedback in api
1. Sign out
1. Go to this api and open Feedback tab

**Found result**:
![joxi_screenshot_1476109134917](https://cloud.githubusercontent.com/assets/20643403/19239308/15c0cbe2-8f0e-11e6-8183-e534bdfa4bbd.png)

**Expected result**: Remove feedback must be available only to api owner.

**OS**: debian 8
**Browser**: Chrome 52

**Comment by nnn** [comment]
@bajiat interested

**Comment by brylie** [comment]
We need to wrap the following lines in an `{{# if api.currentUserCanEdit }}`.

https://github.com/apinf/platform/blob/develop/feedback/client/single/single.html#L20-L34

**Comment by brylie** [comment]
We also need to add allow rules for `update` and `delete` on the Feedback colleciton:

https://github.com/apinf/platform/blob/develop/feedback/collection/permissions.js#L8

Only `api.currentUserCanEdit` approved users should be able to edit/delete.
