### ISSUE TITLE
Allow Admin users to see Admin API analytics on the Dashboard

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1751]
Currently, there is no way for Admin users to view usage statistics about the Admin API. This may be useful for diagnostic purposes, such as detecting performance bottlenecks.

Add an option to the *Select API* dropdown, that only Admin users can see, so that we can display analytics from the `/api-umbrella/` endpoint on the dashboard:

![screenshot_20161011_104652](https://cloud.githubusercontent.com/assets/17307/19262797/a5895814-8fa1-11e6-918f-123121c2a513.png)

# Example code

```html
<!-- Admin API -->
<optgroup label="Admin" >
  <option value="/api-umbrella" >
    Admin API
  </option>
</optgroup>
```

**Comment by brylie** [comment]
Ping @frenchbread

**Comment by bajiat** [comment]
@frenchbread What is your estimate for this?

**Comment by frenchbread** [comment]
@bajiat Done, pushing the code..
