### ISSUE TITLE
Proxy tab: endSubmit hook isn't called

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1758]
Verified on staging

**Steps**:
1. Create an api and go to Proxy tab
2. Leave proxy_path and api_path empty and set "Disable API key"
3. Click on the button "Save & Publish"

**Found**: Nothing happened. No success/error message. The "Save & Publish" button is disable
![joxi_screenshot_1476185349824 1](https://cloud.githubusercontent.com/assets/20643403/19269035/b5681a4e-8fc0-11e6-8085-63a136b2f5eb.png)

**Expected**: ain't sure which behaviour is expected. These must be message about "Your settings successful saved" or "All fields are required". Nevertheless, the "Save & Publish" button must be available after any results, success or error.

**Comment by marla-singer** [comment]
These is repeted with "Rate limits" too
![joxi_screenshot_1476186191337](https://cloud.githubusercontent.com/assets/20643403/19269105/287677f6-8fc1-11e6-86c9-586c491a653c.png)

**Comment by bajiat** [comment]
@marla-singer You have not provided anything in Proxy base path and API base path. Those are mandatory fields.

**Comment by marla-singer** [comment]
@bajiat So it must show message about this

**Comment by bajiat** [comment]
You are right about that.

**Comment by ilarimikkonen** [comment]
fixed!
