### ISSUE TITLE
Enable 'API key requirement' allows Call API without API Key

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1762]
# Steps
1. Visit https://staging.apinf.io  
2. Login    
3. Add API Backend    
    -  Enter Name  
    -  Enter Description  
    -  Enter URL  
4. Go to Proxy  
5. Enter proxy configuration details   
6. Select option 'Disable API key requirement'  and Save   
7. Go to API Details view    
8. Do not 'Get API key'  
9. Call API : click  on URL in usage instructions  (URL without API key)    
10. Go to 'Proxy'  
11. Enable API Key requirement      
12. Click on 'Save&Publish'    
13. Call API :  click on URL in usage instructions  (URL without API Key)     

# Expected Result 
Call API  without API key should be unsuccessful    
  
# Actual Result 
Call API without API Key was successful while 'enabled API Key requirement '    

# Browser
1. Mozilla Firefox 48.0 
2. Google Chrome 52.0.2743.116     

# Operating System
Ubuntu 16.0 LTS

**Comment by bajiat** [comment]
@saralavanip Why is the expected result here "Call API without API key should be unsuccessful"?

**Comment by saralavanip** [comment]
@bajiat : Selected option 'API key required' while calling API ( in step 11) and user must be notified to 'Get API key' from the feature available in API Details view.

**Comment by bajiat** [comment]
@saralavanip But the option in the Proxy tab is "Disable API key requirement". 

API key is required if you do **not** select that option.

**Comment by saralavanip** [comment]
@baijat, In step:6 selected option 'Disable API key requirement' (API key not required while calling API)  and in step:11 deselected option 'Disable API key requirement' (API key required while calling API)

**Comment by marla-singer** [comment]
@bajiat I'll try to clarify.
Steps:

1. Create a new user
2. Go to api which is connected to proxy backend
3. In Usage instruction you can see:
call the API **with your key** in the URL parameters: https://staging.apinf.io:3002/joku/
![joxi_screenshot_1476259065928](https://cloud.githubusercontent.com/assets/20643403/19302002/f75acfaa-906a-11e6-88da-9f83e40d8d7d.png)

However, **call the api without api key is impossible on default**. You can do it only if api owner specifies that. But usage instruction lets me call the api without api key

I hope my explanation helps you

**Comment by bajiat** [comment]
@marla-singer Thanks!

**Comment by bajiat** [comment]
related to #1759

**Comment by marla-singer** [comment]
@bajiat Interested in

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io and it is not reproducible.
