### ISSUE TITLE
Dashboard needs a state for owner that has not connected API to proxy

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1763]
1. Visit https://nightly.apinf.io (or current `develop` branch)
2. Sign up (a **non-admin** user)
3. Add an API (**do not** add a Proxy Backend)
4. Go to Dashboard

# Expected results
- Dashboard should inform user that they need to connect API to a proxy in order to see anything on Dashboard.
- console should contain no errors
  - `getElasticSearchData` should not be called

# Observed result
## Anonymous user
- Dashboard displays 'You don't have any API you manage

## Non-admin user
- Dashboard shows empty charts and empty Select API list. 
- There is also a long console error from Elastic Search

```js
Object { stack: "Meteor.makeErrorType/errorClass@htt…", error: "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[73kkJjeUTGy5qRZSFB6xHw][api-umbrella][0]: SearchParseException[[api-umbrella][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{"should":[[]]}},"filter":{"range":{"request_at":{"gte":1473664331176,"lte":1476256331177}}}}},"sort":[{"request_at":{"order":"desc"}}],"fields":["request_at","response_status","response_time","request_ip_country","request_ip","request_path","user_id"]}]]]; nested: QueryParsingException[[api-umbrella] [_na] query malformed, must start with start_object]; }{[73kkJjeUTGy5qRZSFB6xHw][api-umbrella-logs-v1-2016-02][0]: SearchParseException[[api-umbrella-logs-v1-2016-02][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{"should":[[]]}},"filter":{"range":{"request_at":{"gte":1473664331176,"lte":1476256331177}}}}},"sort":[{"request_at":{"order":"desc"}}],"fields":["request"[…], reason: undefined, details: undefined, message: "[SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[73kkJjeUTGy5qRZSFB6xHw][api-umbrella][0]: SearchParseException[[api-umbrella][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{"should":[[]]}},"filter":{"range":{"request_at":{"gte":1473664331176,"lte":1476256331177}}}}},"sort":[{"request_at":{"order":"desc"}}],"fields":["request_at","response_status","response_time","request_ip_country","request_ip","request_path","user_id"]}]]]; nested: QueryParsingException[[api-umbrella] [_na] query malformed, must start with start_object]; }{[73kkJjeUTGy5qRZSFB6xHw][api-umbrella-logs-v1-2016-02][0]: SearchParseException[[api-umbrella-logs-v1-2016-02][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{"should":[[]]}},"filter":{"range":{"request_at":{"gte":1473664331176,"lte":1476256331177}}}}},"sort":[{"request_at":{"order":"desc"}}],"fields":["reques"[…], errorType: "Meteor.Error" }
```
# Screenshots
See the console log for anonymous users. In effect, anonymous users should probably be redirected to register/login.

## Anonymous user visiting Dashboard
![screenshot_20161012_131951](https://cloud.githubusercontent.com/assets/17307/19306492/9d8b86ea-907e-11e6-9536-6f67d73edb83.png)

## Non-admin user with no APIs
A new user, with no APIs. The correct message is visible, but there is a console error.

![screenshot_20161012_132604](https://cloud.githubusercontent.com/assets/17307/19306700/94d21d6a-907f-11e6-8bee-cc56cbfea79c.png)

## Non-admin user with one (or more) API(s)
Here is a regular user with one API. Note:
- the **Select API(s)** dropdown is empty
- Dashboard charts render
  - no results in charts
- console error from `getElasticSearchData`

![screenshot_20161012_132815](https://cloud.githubusercontent.com/assets/17307/19306765/eb77a1f8-907f-11e6-9d31-e99113428064.png)

**Comment by bajiat** [comment]
@brylie Please add screenshot and/or console log

**Comment by brylie** [comment]
```js
Object { stack: "Meteor.makeErrorType/errorClass@htt…", error: "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[73kkJjeUTGy5qRZSFB6xHw][api-umbrella][0]: SearchParseException[[api-umbrella][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{"should":[[]]}},"filter":{"range":{"request_at":{"gte":1473664331176,"lte":1476256331177}}}}},"sort":[{"request_at":{"order":"desc"}}],"fields":["request_at","response_status","response_time","request_ip_country","request_ip","request_path","user_id"]}]]]; nested: QueryParsingException[[api-umbrella] [_na] query malformed, must start with start_object]; }{[73kkJjeUTGy5qRZSFB6xHw][api-umbrella-logs-v1-2016-02][0]: SearchParseException[[api-umbrella-logs-v1-2016-02][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{"should":[[]]}},"filter":{"range":{"request_at":{"gte":1473664331176,"lte":1476256331177}}}}},"sort":[{"request_at":{"order":"desc"}}],"fields":["request"[…], reason: undefined, details: undefined, message: "[SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[73kkJjeUTGy5qRZSFB6xHw][api-umbrella][0]: SearchParseException[[api-umbrella][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{"should":[[]]}},"filter":{"range":{"request_at":{"gte":1473664331176,"lte":1476256331177}}}}},"sort":[{"request_at":{"order":"desc"}}],"fields":["request_at","response_status","response_time","request_ip_country","request_ip","request_path","user_id"]}]]]; nested: QueryParsingException[[api-umbrella] [_na] query malformed, must start with start_object]; }{[73kkJjeUTGy5qRZSFB6xHw][api-umbrella-logs-v1-2016-02][0]: SearchParseException[[api-umbrella-logs-v1-2016-02][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{"should":[[]]}},"filter":{"range":{"request_at":{"gte":1473664331176,"lte":1476256331177}}}}},"sort":[{"request_at":{"order":"desc"}}],"fields":["reques"[…], errorType: "Meteor.Error" }
```

**Comment by brylie** [comment]
@frenchbread we need to add a third conditional check to the dashboard:

- a user who has added an API, but who has **not** added a Proxy for the API
  - the dashboard should tell the user they need to also configuer a Proxy
  - dashboard charts should **not** render
  - there should be no call to elasticsearch (which throws exceptions)

**Comment by Nazarah** [comment]
In case API owner doesn't connect her API to a proxy and navigates to dashboard page, the following message should appear:
"You have not yet connected your API to a proxy. To see analytics of your API usage, browse your API from Catalog and configure a proxy from the API profile."
The catalog can be a hyperlink that redirects the user to catalog page.

**Comment by frenchbread** [comment]
> a user who has added an API, but who has not added a Proxy Backend for the API

@brylie This should be implemented already, please check. The message currently shows that "Not Apis or Proxy backends" added. But technically this check is done using proxy backends only.

**Comment by brylie** [comment]
@frenchbread, @bajiat and I tested this morning, right before adding this issue. Please see steps to reproduce.

**Comment by brylie** [comment]
@frenchbread and @bajiat, I have added screenshots for the following three scenarios:

- anonymous user accessing Dashboard
- regular user with no APIs accessing Dashboard
- regular user with one (or more) API(s) accessing Dashboard

There are console errors in all three cases. In the third case, the Dashboard renders, but the **Select API(s)** dropdown is empty and there is no chart data.

**Comment by bajiat** [comment]
@brylie Thanks for the verification and the screenshots.

Assigning to @jykae.

**Comment by jykae** [comment]
@bajiat @brylie For anonymous user redirect to signup/login OR not-authorized page?

**Comment by brylie** [comment]
Cool. That way they will get redirected to Dashboard after they sign in or register.

**Comment by jykae** [comment]
Next case normal user without APIs:

<img width="1271" alt="nayttokuva 2016-10-12 kello 14 38 15" src="https://cloud.githubusercontent.com/assets/293452/19308694/a744a8f0-9089-11e6-831a-4fa8bf66a91d.png">

Not getting console errors like in @brylie 's screenshot

**Comment by brylie** [comment]
I will try to add steps to reproduce from a fresh clone.

**Comment by brylie** [comment]
I was able to reproduce the second use case (regular user with one API having no ProxyBackend) with the following steps:

1. delete my working folder
1. clone the repository
1. make sure I am on `develop` branch
1. npm install
1. run meteor
1. create **admin** user
1. configure Proxy (with proper settings)
1. sign-out
1. create **non-admin** user
1. add API as **non-admin** user
  - do not add Proxy Backend settings for the API
1. go to Dashboard

## Screenshot
![screenshot_20161012_145746](https://cloud.githubusercontent.com/assets/17307/19309217/3f5bf006-908c-11e6-8f0a-ad322d141227.png)

## Environment
I have duplicated this issue with the following browsers:

- Chromium 53.0.2785.143 Built on Ubuntu , running on neon 16.04 (64-bit)
- Firefox 49.0

Desktop:
- Ubuntu / KDE Neon

**Comment by jykae** [comment]
Reproduced, line 166 should probably not be happening https://github.com/apinf/platform/blob/develop/dashboard/client/dashboard.js#L166

proxyBackendsAdded state is false like, it works ok.

**Comment by frenchbread** [comment]
I was able to reproduce. 

### Suggestion for fixing:

- Completely remove Meteor method `proxyBackendsAdded` & instance function where is it used
- Probably change `instance.proxyBackendsAddedState = new ReactiveVar(false);` default value to `true` - this won't affect functionality, but will add a little delay.
- Refactor code [here] (probably with removing console.errors)(https://github.com/apinf/platform/blob/develop/dashboard/client/dashboard.js#L171):
    From this
    ```js
    instance.proxyBackendsAdded()
        .then(proxyBackendsAdded => {

          if (proxyBackendsAdded) {
            // Make a call
            instance.checkElasticsearch()
              .then((elasticsearchIsDefined) => {
                if (elasticsearchIsDefined) {
                  instance.getChartData(params)
                    .then((chartData) => {
                      // Update reactive variable
                      instance.chartData.set(chartData);
                      instance.chartDataLoadingState.set(false);
                      instance.proxyBackendsAddedState.set(true);
                    })
                    .catch(err => console.error(err));
                } else {
                  console.error('Elasticsearch is not defined!');

                  Router.go('/catalogue');
                }
              })
              .catch(err => console.error(err));
          } else {
            instance.proxyBackendsAddedState.set(false);
            console.error('Proxy backends and/or APIs are not added.');
          }
        })
        .catch(err => console.error(err));
    ```
    To this
    ```js
    const proxyBackends = ProxyBackends.find().fetch();

    if (proxyBackends.length > 0) {
      // Make a call
      instance.checkElasticsearch()
        .then((elasticsearchIsDefined) => {
          if (elasticsearchIsDefined) {
            instance.getChartData(params)
              .then((chartData) => {
                // Update reactive variable
                instance.chartData.set(chartData);
                instance.chartDataLoadingState.set(false);
                instance.proxyBackendsAddedState.set(true);
              })
              .catch(err => console.error(err));
          } else {
            console.error('Elasticsearch is not defined!');
            Router.go('/catalogue');
          }
        })
        .catch(err => console.error(err));
    } else {
      instance.proxyBackendsAddedState.set(false);
      console.error('Proxy backends and/or APIs are not added.');
    }
    ```

This change will show placeholder on dashboard saying "No proxy backends found.."

**Comment by frenchbread** [comment]
@jykae Actually I won't suggest changing `instance.proxyBackendsAddedState = new ReactiveVar(false);` to `true` because in this case when logged in as admin, dashboard will first render placeholder (while chart data is still loading) and then remove it & show charts. Keeping it as `false` will still show the placeholder, but only if there are no proxyBackends added (so not by default but after checking).

**Comment by jykae** [comment]
@frenchbread thanks for insight. Check related PR #1775 and add related comments there. I have fix almost like that, just using Meteor.call to check proxyBackendsAdded. Do you want to review?

**Comment by frenchbread** [comment]
@jykae Ok, cool. I'll assign myself.
