### ISSUE TITLE
IE11 - on clicking Bookmark , user gets back to APINF landing page

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1767]
# Reproduction Steps:
1. go to https://staging.apinf.io/
2. go to API catalog or profile page
3. Click on Bookmark

# Result
* User gets back to APINF landing page
* Happens both for bookmark / remove bookmark action
![bookmark-ie11](https://cloud.githubusercontent.com/assets/17976243/19306925/a0f5e602-9080-11e6-9ea5-d7e29b834958.gif)

# Expectation:
* On clicking bookmark icon, user should remain in the same page

# Testing environment 
* Windows 8
* IE 11

**Comment by bajiat** [comment]
Was able to reproduce this with IE11.  

@brylie You had an idea what is the problem: anchor?

**Comment by nnn** [comment]
@bajiat interested

**Comment by brylie** [comment]
This may be due to the use of anchor tags `<a>` around the bookmark buttons, at least on the API Card template. The markup only needs to be a `<button>` element, rather than an `<a class="btn ...">`.

**Comment by bajiat** [comment]
@marla-singer Could you take a look at this task? Should be a small fix based on the comment above by @brylie

**Comment by marla-singer** [comment]
@bajiat Okay, I will try to fix it

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://nightly.apinf.io and https://staging.apinf.io and it is not reproducible. 

Browser: IE 11 
Operating System: Windows 10
