### ISSUE TITLE
Secondary sorting criteria is not clear in APINF catalog

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1768]
When the APIs are sorted based on Number of Bookmarks and Average rating, it is not clear how the APIs appear (by names or creation date in the case two APIs have same alphabet in their names or same creation time). There should be some indicator to show this. (e.g. sorting criteria: no of bookmarks (asc) with API names in Asc order)

**Comment by bajiat** [comment]
@Nazarah How do you sort them with two criteria at the same time? Does this happen in some specific browser?

**Comment by Nazarah** [comment]
@bajiat this is not Browser specific
I am adding the screenshot here
![image](https://cloud.githubusercontent.com/assets/17976243/19309248/67d568aa-908c-11e6-9aed-9635ab8c96c9.png)

right now the sorting order is no. of bookmarls asc. order. but if you see the API names, there is no order (as./ dec.) orders in them. Also it is not clear if one PAI was added before another.
SO what I suggest here is that if 2 APIs have similar number of bookmarks and the sorting order is No. of bookmarks asc., then the API whose name comes 1st in alphabet should be displayed 1st.
