### ISSUE TITLE
for "Access Denied" or "403 Forbidden" page, show a link to return to Catalog page

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1776]
![image](https://cloud.githubusercontent.com/assets/17976243/19310378/75459586-9092-11e6-962c-f95acf19c969.png)

**Comment by nnn** [comment]
We had "Return to a previous page" link, which takes user to any previous page. Is it missing now?
"403 Forbidden" template is for any "Access Denied" situations not only for catalog.

**Comment by Nazarah** [comment]
The link was missing the time I checked.
I found the situation while I was checking access to private API then found it.

**Comment by nnn** [comment]
@Nazarah, we have it working at 404 page.
https://apinf.io/some-broken-path

**Comment by bajiat** [comment]
The link on 404 page does not actually work.
