### ISSUE TITLE
No notice user about successful deleting user account

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1787]
Verified on apinf.io

1. Create a new user 
2. Go to Account
3. Click on Delete account and confirm

Found results: Route to main page and no notice
Expected results: Route to main page and notice user about successful deleting

**Comment by marla-singer** [comment]
@nnn I don't think it's enhancement. The notice implemented by doesn't work correct
Look at there: https://github.com/apinf/platform/blob/develop/users/client/account/delete/delete.js#L22

**Comment by nnn** [comment]
@marla-singer oh, okay, got it, I am sorry. Yes it's a bug then.

**Comment by brylie** [comment]
Check that the following lines work:
https://github.com/apinf/platform/blob/develop/users/client/account/delete/delete.js#L18-L22

Try:

- Moving the sAlert lines to before the Router.go line
- Check that the i18n text returns, and is not `undefined`

**Comment by jykae** [comment]
Reason & solution: https://github.com/juliancwirko/meteor-s-alert#closing-alerts-on-route-change
Default for s-alerts is to clear out messages when route changes, we can override it or change default behaviour in global configuration. I am overriding for this bugfix.

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and it works as expected.  

Screenshot:  
![screenshot 49](https://cloud.githubusercontent.com/assets/13309358/20298418/78f30bf4-ab1e-11e6-96c7-a338b6a8f6ca.png)
