### ISSUE TITLE
Axis on any chart in dashboard doesn't show what is being measured and the measurement unit

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1788]
It is hard to comprehend what the charts are presenting in terms of measurements and their units

![image](https://cloud.githubusercontent.com/assets/17976243/19507890/65b593ea-95de-11e6-8083-eb47f5b48f71.png)

**Comment by marla-singer** [comment]
@Nazarah @bajiat Have to be fixed in a new Dashboard

**Comment by Nazarah** [comment]
@marla-singer will close the issue as soon as new dashboard is on nightly.

**Comment by marla-singer** [comment]
![joxi_screenshot_1504863978922 1](https://user-images.githubusercontent.com/20643403/30206219-12686b80-9494-11e7-8056-3b3aa19652de.png)

**Comment by Nazarah** [comment]
@marla-singer Feedback
1. rename Requests, number as "API Requests". 
I don't believe we need to mention the unit as number as the graph itself is self-explanatory.
For API Response Time, the axis title and unit makes sense.
