### ISSUE TITLE
Dashboard: on clicking info icons, no popup appears describing the purpose of the charts and table

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1789]
Locations:
API Request Timeline 
![image](https://cloud.githubusercontent.com/assets/17976243/19508102/ed04b1fe-95df-11e6-8fae-775b781e8f72.png)

HTTP Status Codes
API response Time
![image](https://cloud.githubusercontent.com/assets/17976243/19508108/f6b7e3ec-95df-11e6-970f-12630b08889f.png)

Analytics Data
![image](https://cloud.githubusercontent.com/assets/17976243/19508124/0ced9c06-95e0-11e6-8b90-7a3d168d39dd.png)

**Comment by nnn** [comment]
@bajiat interested

**Comment by bajiat** [comment]
@nnn Can you please estimate?
@Nazarah Can you help with texts?

**Comment by Nazarah** [comment]
API Request Timeline:

You can use this chart to view number of requests your API has received for a specific time period.
You can see API requests for a single API or a combination of them.
The overview information and other charts will be updated when you interact with API request Timeline. 

HTTP Status Code:

You can use this chart to see the HTTP responses generated by your API for the requests it receives for a specific time period.
You can filter the chart with response type for a single API or a combination of them.
The overview information and other charts will be updated when you interact with HTTP Status Codes. 

API Response Time:

You can use this chart to see the number of responses generated by your API and its response time for the requests it receives for a specific time period.
You can see the response time (on X-axis in milliseconds) and number of responses generated (Y-axis) for a single API or a combination of them.
The overview information and other charts will be updated when you interact with API Response Time. 

Analytics Data:

The table provides detailed information about each request your API receives for a specific time period.
You can know the country and the IP address from where the request was generated.
You can also identify the method to which an API request was made.
Information in the table is rendered based on the filtering of the charts and combination of APIs.
