### ISSUE TITLE
Allow users to change branding color

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1793]
Allow system admins to change main branding color from branding settings.

>  As an Apinf customer, I want to change the bright blue color to my company's or organization's brand color
so that Apinf deployment is in line with our other web pages and it matches with our logo color(s).

# Definition of done
* [ ] User can change the branding color in branding settings.
* [ ] User can use a color picker to either type the color value (RGB or HEX)
* [ ] The setting affects
  * [ ] nav bar
  * [ ] cover photo
  * [ ] search box
  * [ ] language option active, if possible
  * [ ] settings menu list group item active, if possible
  * [ ] API navigation tab active, if possible
  * [ ] intro.js bullet active, if possible
  * [ ] catalog active pagination, if possible
* [ ] User can also change the font color for text (links) in navbar

**Comment by bajiat** [comment]
@brylie @Nazarah 
Add the packages for color picking and any comments you might have

**Comment by brylie** [comment]
@Nazarah and I like the [jscolor](http://jscolor.com/) package.

**Comment by Nazarah** [comment]
consider when user selects a lighter color as brand, texts and link fonts are in contrast with the selected color.

**Comment by Nazarah** [comment]
A suggestion to include an option to check color contrasts of both background and text in the brand setting page.

**Comment by Nazarah** [comment]
Right now, when we change to a different branding color than the standard APInf one, highlighted topbar item has a white background when hovered on it. In standard APInf color, the hovered item gets highlighted with a darker shade than the primary color.
A library to include darker background color when a topbar item is hovered should be included here.

**Comment by brylie** [comment]
After reviewing with @Nazarah, I did a bit of searching and found a package called [TinyColor](http://bgrins.github.io/TinyColor/). TinyColor has some [useful methods for working with colors](https://github.com/bgrins/TinyColor) including:

- [lighten](https://github.com/bgrins/TinyColor#lighten)
- [darken](https://github.com/bgrins/TinyColor#darken)
- [readability](https://github.com/bgrins/TinyColor#readability-1)

The lighten and darken do as their name suggests, while the readability returns the WCAG readability rating for a pair of colors.

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and it works as expected.
