### ISSUE TITLE
Research if Selenium IDE HTML files could be converted to JS

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1798]
Would save lots of time if we could generate tests with Selenium IDE and output tests as JavaScript.

This one uses sync-wd to run tests and has conversion functions to output JS:
https://www.npmjs.com/package/selenium-html-js-converter

Also look if there are other options for conversion if above one **doesn't work**

**Comment by jykae** [comment]
Testing conversion for @Nazarah 's anonymous user tests in apinf-testing repo

**Comment by jykae** [comment]
Converted successfully, running with Phantom is really fast, so would need to add some waits explicitly. Takes also nice screenshot on test failure point 8-)

**Comment by jykae** [comment]
@Nazarah your yesterday's work in JS.
![nayttokuva 2016-10-26 kello 11 34 57](https://cloud.githubusercontent.com/assets/293452/19718941/5f5379f8-9b70-11e6-846b-ae3f02cb6dfc.png)

**Comment by jykae** [comment]
HTML files don't have info about usage of implicitWait, I'll try if I can add it somehow for generated JS.

**Comment by jykae** [comment]
Reported issue for author:
https://github.com/flyingfisher/selenium-html-js-converter/issues/14
and a question:
https://github.com/flyingfisher/selenium-html-js-converter/issues/15

**Comment by jykae** [comment]
Issue with setWindowSize, https://github.com/flyingfisher/selenium-html-js-converter/issues/16

Defaults to very narrow window, cannot find Catalogue link as it's collapsed.

Screenshot taken by PhantomJS when exception happens:
![exception click](https://cloud.githubusercontent.com/assets/293452/19723406/d735aadc-9b83-11e6-84b7-6c5a48bb59c2.png)

**Comment by jykae** [comment]
setWindowSize would need solution, otherwise great package. Putting this on hold.

**Comment by jykae** [comment]
Got answer from author @flyingfisher but unfortunately package is not maintained, just possible bugs are fixed.

**Comment by FirassKoubaa** [comment]
any possible solutions ?

**Comment by jykae** [comment]
@FirassKoubaa FYI window resizing was our only problem with the package, looks like reported possible bug is now commented, tested & closed https://github.com/flyingfisher/selenium-html-js-converter/issues/16#issuecomment-288405849

I am no longer in this project, @bajiat maybe Apinf-team would like to try if it works out now, and used parameter format (missing comma) was just wrong like commented in the issue.
