### ISSUE TITLE
Move automated tests to main repository

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1802]
To be able to run the automated tests easily as part of our dev cycle (e.g. when submitting PR to review), the tests should be part of the platform repository instead apinf-testing repo.

Proposed workflow for issues before submitting PR's to review
1. Lint you code
2. Make sure any database migration is taken care of
3. Merge conflicts
4. Run automated tests
5. Mark you PR as 'ready to review'
# Definition of done
- [x] Move the JS tests to our main repository to /test
  ' [ ] If possible, try to preserve the commit history
- [x] Set up an NPM alias to run tests, e.g. npm test

**Comment by bajiat** [comment]
@apinf-developers Please comment the workflow described in this issue

**Comment by brylie** [comment]
The following article describes the steps needed to merge the repositories while preserving commit history:

http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

**Comment by jykae** [comment]
@brylie thanks for link. I think currently open PRs would be nice to get in apinf-testing "master" before this. Notified authors of open PRs.

**Comment by jykae** [comment]
@bajiat that workflow would be good to have in guidelines, issue for that adding that to https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md ?

**Comment by brylie** [comment]
@bajiat I agree that we should have a separate issue to add the 'PR workflow steps' to our contributing guide. The steps look good, but don't need to be part of this task.

**Comment by bajiat** [comment]
@brylie They don't need to be part of this task. They were raised for discussion. I can create another task for adding steps.

**Comment by jykae** [comment]
@bajiat @brylie all existing tests have been now fixed & merged to apinf-testing, and careful moving of tests can be done with commit history preserved.

**Comment by jykae** [comment]
@bajiat @brylie Moving done, npm test part to discover

**Comment by brylie** [comment]
OK. Add a new line under script like so:

```json 
...
"scripts": {
    "lint": "eslint .",
    "pretest": "npm run lint --silent",
    "test": "test command"
  },
...
```

**Comment by brylie** [comment]
Woohoo!

**Comment by marla-singer** [comment]
@brylie Early. We must fix it in addition :D
