### ISSUE TITLE
API Profile: in Feedback tab, anonymous user (not logged in) can see view and remove options for a feedback

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1817]
# Steps to reproduce:
* go to nightly.apinf.io
* without signing in, go to any API profile
* click on Feedback tab

# Result
* user can see View and Remove Button for a feedback.
* User can view or remove a feedback

![image](https://cloud.githubusercontent.com/assets/17976243/19683369/a93e6a5c-9aba-11e6-8091-e6ec9c1a3d0a.png)

# Expected Result:
* User should not be able to see any of the buttons or to perform any actions for it
* open question: should an anonymous user be able to view feedbacks to an API

# Environment
* OS: Windows 8
* Browser: any

**Comment by marla-singer** [comment]
@Nazarah I think any user can View feedback. Otherwise why do we have the vote system for feedback item?

**Comment by Nazarah** [comment]
@marla-singer : if only the View Feedback button stays there, it is fine. Currently any user not logged in can delete previously given feedback. I'm more concerned about this

**Comment by bajiat** [comment]
@Nazarah I think this was resolved in #1744, which was merged yesterday.  This is the situation in nightly today: 

<img width="882" alt="1817" src="https://cloud.githubusercontent.com/assets/11626388/19717208/2b62c066-9b68-11e6-841a-7a67472c91a3.png">

**Comment by marla-singer** [comment]
@bajiat Yes, but we hid View button too. I think we should came back it, it's easy

**Comment by bajiat** [comment]
I'll create another issue for View button and close this one as resolved.
