### ISSUE TITLE
In Search APIs page, searchbox doesn't function

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1820]
# Steps to reproduce:
* go to nightly.apinf.io
* click search button from topbar
* click search button in searchbox
* in Search APIs page, type "api" and click on search button in the searchbox

# Result
* no search for specific API doesn't take place
![searchboxbug](https://cloud.githubusercontent.com/assets/17976243/19723815/ca51f292-9b85-11e6-8db1-73af1a472e7d.gif)

# Expected Result
* Search button should be functioning
* should return a new search result

# Environment
* OS: Windows 8
* Browser: any

**Comment by jykae** [comment]
@bajiat Estimate 1d in waffle, query parameters is not updated to Router parameters (or something is undefined..)

**Comment by jykae** [comment]
@bajiat Found reason: we have 2 elements with id="search-text", navbar search & search page input.
