### ISSUE TITLE
Proxy settings never save when submitting invalid host

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1822]
When submitting proxy settings for an API with an invalid host, the Proxy Settings form never submits. The end-user is not informed of any problem, even though API Umbrella likely rejected the submission since the host does not exist.

# Steps to reproduce

1. Add an API
  - enter any title and description
  - for the host, **enter a domain name that does not exist**
2. Go to the API details page
3. Click the Proxy tab
4. Enter proxy details
5. Click 'Save and Publish'

# Expected result
The proxy form should indicate to the user that the submission has failed, exiting the 'pending' state.

# Observed result
The proxy form remains in the 'pending' state, never completing the submission.

# Screencast
![peek 2016-10-26 15-33](https://cloud.githubusercontent.com/assets/17307/19726158/1e88e864-9b92-11e6-8d76-15e71a917a41.gif)

**Comment by marla-singer** [comment]
@brylie It happens because we don't have the special conditions in this line. 
https://github.com/apinf/platform/blob/develop/proxy_backends/client/form/autoform.js#L41
When host is invalid, error isn't catched and response has structure:
```javascript
errors: {
 ["failed [422] {"errors":{"servers[0].host":["Could not resolve host: no address for proxy.api"]}}"]
}
http_status: 422
result: {}
```

I detected it when was debbuging

**Comment by marla-singer** [comment]
@bajiat Interesting

**Comment by brylie** [comment]
@marla-singer thanks for the details. How difficult do you suppose this would be to fix?

**Comment by marla-singer** [comment]
@brylie If me guess is correct, it's about a hour. We don't save the proxy settings, if  hostis invalid, yes?And notify user about invalid host

**Comment by bajiat** [comment]
@marla-singer Sold! This is also yours, if you have time in addition to #1699

**Comment by bajiat** [comment]
@brylie So we need explicitly to tell them that they need to go to Settings tab?

**Comment by marla-singer** [comment]
@bajiat Nope, It's obviously, I think

**Comment by Nazarah** [comment]
@brylie, according to @bajiat can we somehow verify the host while adding the API? a simple Pinging using HTTP GET? if no response is found, we can reject adding the API

**Comment by brylie** [comment]
That would mitigate the issue. We would still have a potential problem if API Umbrella rejects the Proxy settings for *any* reason, since we are not handling failure in the code @marla-singer mentioned.

**Comment by bajiat** [comment]
I'm ok with alerting user and going back to edit mode.

**Comment by bajiat** [comment]
We can decide whether we want to check host already when API is added to Catalog later.
