### ISSUE TITLE
Reintroduce cover photo

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1823]
The possibility to upload a cover photo for APInf landing page has been removed from Branding settings. Since cover photo was part of APIKA landing page requirements, it should be reintroduced. Also, it gives more options for re-branding in general and also branding apinf.io.
# User story

> As an APInf administrator
> I want to use a cover photo on landing page
> to make my APInf deployment better match with other brand related web pages or tools.
# Definition of done
- [x] Admin can upload a cover photo from Branding settings.
- [x] If cover photo is uploaded, the landing page shows the cover photo in cover photo area.
- [x] Admin can replace a cover photo, if possible.
- [x] Admin can delete a cover photo.
  - [x] Cover photo area shows primary branding color after cover photo has been deleted.
  - [x] Image is removed from collection.

# Wireframes
![apinfcoverphoto](https://cloud.githubusercontent.com/assets/17976243/20136084/b8f8765a-a67b-11e6-8438-c92f3d873c9c.png)
![apinfcoverphoto2](https://cloud.githubusercontent.com/assets/17976243/20136085/b8f877ae-a67b-11e6-855a-ba0535812cf1.png)

**Comment by Nazarah** [comment]
It also should be made sure that whatever picture is selected for cover picture, the landing page texts are visible in contrast with the picture.

**Comment by jykae** [comment]
@Nazarah I can't think of algorithm how we can adjust text color by colors in cover photo (of course that is possible, but goes over my poor knowledge). 
However we can probably provide way to adjust text color. Good notice.

**Comment by jykae** [comment]
Hm, this looks nice, http://www.kennethcachia.com/background-check/

**Comment by jykae** [comment]
Interested

**Comment by Nazarah** [comment]
The link looks good.
@bajiat is the option to change cover photo would come from settings page? Or admin can change it directly from the landing page as well?

**Comment by bajiat** [comment]
@marla-singer Could you take this task? If you need advice on file handling, you could ask e.g. @nnn who has implemented code already for this feature

**Comment by marla-singer** [comment]
@bajiat yes, can take it

**Comment by marla-singer** [comment]
@bajiat @Nazarah Right now I place the button "Upload cover photo" below the button "Upload Logo". Save it so?

**Comment by marla-singer** [comment]
@bajiat Cover photo looks like this:
![joxi_screenshot_1478683218530](https://cloud.githubusercontent.com/assets/20643403/20133097/25fac9a6-a677-11e6-8c77-37eb3a15586b.png)

**Comment by Nazarah** [comment]
@marla-singer can you add this dialogue when user tries to delete the cover photo from branding page?
"Cover photo area will show primary branding color after photo has been deleted. The image will be removed from the collection." Buttons: Delete cover photo and Cancel

**Comment by marla-singer** [comment]
@Nazarah Okay, I'll add

**Comment by jykae** [comment]
Reopen as this feature was reverted.
