### ISSUE TITLE
Allow anonymous user to View feedback

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1824]
When fixing #1817, anonymous user being able to remove feedback, also View feedback button was removed. As a quick fix, reintroduce View button for anonymous users.

I will create another  enhancement task for showing feedback e.g. as accordeon or panel and also checking editing options for feedback. This is just a quick fix.

**Comment by marla-singer** [comment]
@bajiat Interesting

**Comment by bajiat** [comment]
@marla-singer It's yours if you have  time for it in addition to #1699

**Comment by marla-singer** [comment]
@bajiat No problem, I have time
