### ISSUE TITLE
Harmonize API feedback and API backlog

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1826]
Select a style for API feedback and API backlog issues and use the same style (e.g. accordeon, panel) on both tabs. Ensure button consistency. 
# Definition of done
- [x] Backlog and Feedback have the same style for items.
- [x] There are no View buttons
- [x] Removing and editing is allowed for
  - [x] all admins
  - [x] The API owner/manager
  - [x] the original writer of feedback item

Open issue: if admin or API owner edits a feedback item created by another user, should there be some notification for 'edited'?

**Comment by Nazarah** [comment]
Interested in designing

**Comment by jykae** [comment]
@bajiat On feedback delete, I think it's also OK to delete related Feedback votes?

**Comment by bajiat** [comment]
@jykae Yes, if it only deletes the votes for that particular item to be deleted.

**Comment by jykae** [comment]
@bajiat Yep, just the votes of that particular feedback. We were not doing that before.
```
// 1. Remove feedback votes
FeedbackVotes.remove({ feedbackId: feedbackItemId });
// 2. Remove feedback item
Feedback.remove(feedbackItemId);
```

**Comment by jykae** [comment]
Posted preview https://github.com/apinf/platform/pull/1921#issuecomment-260653084
