### ISSUE TITLE
Issues with login in apinf.io

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1832]
# Problems:
1. When user already has an account try to login in apinf.io, it shows "We have sent you an email. Please verify your email address". 
   User can't login and doesn't receive any email address
   ![image](https://cloud.githubusercontent.com/assets/17976243/19799180/ef667890-9cfd-11e6-98f7-e7e6f0001540.png)
2. After verifying email address, when user clicks login from topbar, it doesn't redirect him/her to login page
3. steps to reproduce:
   - click verify email link from login page
   - verify your email.
   - After getting confirmation message, click Login from topbar
4. Result:
   - User doesn't get redirected to login page
5. Expected Result:
   - User should be able to be redirected to login page
6. Environment
   - OS: Windows 8
   - Browser: any

**Comment by brylie** [comment]
This could be a configuration issue with apinf.io. We should double check the settings, and make sure to deploy our latest release ASAP.

**Comment by nnn** [comment]
@Nazarah please double check if you're still not able to login.

**Comment by Nazarah** [comment]
@nnn tested in https://apinf.io/
I can login now without needing to verify my email.
Closing the issue.
