### ISSUE TITLE
Sign up allows user to login without completing email verification

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1836]
# Steps
1. Visit https://staging.apinf.io 
2. Click on 'Sign up'  
3. Enter username  
4. Enter email 
5. Enter Password  
6. Re-enter the same password for confirmation  
7. Click on 'Register'  
# Findings
-  Click on 'Register' leads to automatic login  
-  Email verification message sent to the user  
-  Allows to logout-login without completing email verification  
# Expected Result

User not allowed to login without completing email verification   
# Browser
1. Mozilla Firefox 48.0 
   (Mozilla Firefox for Ubuntu Canonical – 1.0 )  
2. Google Chrome 52.0.2743.116
# Operating System

Ubuntu 16.0 LTS

**Comment by bajiat** [comment]
I was able to reproduce this in staging, but not in apinf.io.

**Comment by brylie** [comment]
I can reproduce locally. I have tested with three different email/accounts, so it is a consistent bug.

**Comment by brylie** [comment]
Ping @bajiat @saralavanip. This was closed by a PR, please verify it is fixed.

**Comment by saralavanip** [comment]
@bajiat , @brylie , verified this resolved issue on https://nightly.apinf.io and it works as expected. This issue can be closed.
