### ISSUE TITLE
Meteor version update

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1851]
We are currently on version 1.4.1.1 at time of writing this issue. Check out release notes, what has been changed and try upgrading to newer version

Production build (using https://github.com/jshimko/meteor-launchpad) has issue with --unsafe-perm option, that might get solved on upgrade.

Related: https://github.com/jshimko/meteor-launchpad/issues/11

**Comment by bajiat** [comment]
Update to 1.4.2

**Comment by jykae** [comment]
Release info about 1.4.2 http://info.meteor.com/blog/announcing-meteor-1.4.2
