### ISSUE TITLE
API owner is always admin in detail view

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1854]
On production. When in the catalog the user is someone "not admin", in the detailview it shows "admin".

**Comment by marla-singer** [comment]
@philippeluickx It happens when api doesn't have owner any more (user deleted account) or api was created by user, who sighed up via GitHub

**Comment by bajiat** [comment]
@marla-singer Thanks for checking. Why is the user then displayed in the Catalog, if it is one of the cases described by you? I'll post an example from apinf.io: same API in Catalog and in API profile.

**Comment by bajiat** [comment]
Compare the following screenshots in apinf.io: owner is shown in Catalog, but not in profile view:

<img width="878" alt="catalog in production" src="https://cloud.githubusercontent.com/assets/11626388/19920323/bd1dd126-a0e0-11e6-8c25-2fa3fade3786.png">

<img width="882" alt="api profile production" src="https://cloud.githubusercontent.com/assets/11626388/19920327/c75f5696-a0e0-11e6-9b41-0fbe44ece33f.png">

**Comment by jykae** [comment]
Good find, taking look

**Comment by jykae** [comment]
@marla-singer I tried both cases described on latest develop, works as expected. Is this behaviour happening only in production?

**Comment by jykae** [comment]
Nightly has same issue, trying to reproduce there.

**Comment by marla-singer** [comment]
@jykae Let me know if you can't reproduce it, I'll try too

**Comment by jykae** [comment]
@marla-singer On nightly, my own APIs with user I am signed in show right both catalogue & API profile.

**Comment by marla-singer** [comment]
@jykae 
Second case: Sign in like GitHub user, create an api and sign out. In API profile owner will be _admin_. Look above in Taija's screenshot.

What did you check?

**Comment by jykae** [comment]
@marla-singer Ok, now got that locally. When I log in with that Github user the profile page shows the user right.

**Comment by jykae** [comment]
Problematic line https://github.com/apinf/platform/blob/develop/apis/collection/helpers.js#L59

On the client we publish only currentUser when user is logged in, Meteor.users can be queried only on server side for security.
