### ISSUE TITLE
If Github username is taken, routing to user profile fails

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1864]
Solution for Github username taken has been broken at some point of development, when we have improved settings. Route is wrong. Results 404 page not found.

![joxi_screenshot_1478161060047](https://cloud.githubusercontent.com/assets/20643403/19959356/26a936c2-a1b7-11e6-8840-c70de16a7458.png)

Overall implementation of this might be also bit too complex.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io 

Findings: 
- Sign In with unique GitHub account works as expected.
- Sign In with GitHub account's email address which is also associated with another apinf account  displays 'Email already exists' . 

Screenshot: 
![apinf_landing_page_error](https://cloud.githubusercontent.com/assets/13309358/20424137/fba4532c-ad7c-11e6-84dc-0473e7c8db2f.PNG)
