### ISSUE TITLE
Register/Sign In with Github when email registered using local registration

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1866]
Results email already registered, makes sense, but maybe we should allow linking to existing account?

<img width="664" alt="nayttokuva 2016-11-03 kello 10 14 14" src="https://cloud.githubusercontent.com/assets/293452/19959349/b4b11af6-a1ae-11e6-9541-009239b2adc2.png">

**Comment by marla-singer** [comment]
@jykae Hm.. I think nope, we shouldn't. Maybe it's the attacker :suspect:

**Comment by jykae** [comment]
@marla-singer user should of course have access to that local account with email verified, not automatic linking, and stealing local account :)

**Comment by brylie** [comment]
Cool. Perhaps we could instruct the user to log in or reset their password.

**Comment by preriasusi** [comment]
Taking this into the spring to solve issues with logins especially with Github. Let's see what issues related to this.

**Comment by preriasusi** [comment]
To be closed. Let's re-write/swap  the Github authentication module.
