### ISSUE TITLE
Remove Horizontal scrollbar from APINF landing page

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1867]
# Issue
Right now, on navigating to APINF landing page, browser shows a horizontal scroll bar.
Landing page doesn't contain any additional content that can be visible only by horizontal scrolling.
Also keeping horizontal scrollbar in browser unnecessarily is considered to be a violation to aesthetics.

![image](https://cloud.githubusercontent.com/assets/17976243/19997819/b758e964-a271-11e6-8c78-6054fbc371f7.png)

# Environment
OS: Windows 8
Browser: Chrome, Firefox

**Comment by bajiat** [comment]
Could this be related to div.content-wrapper?

**Comment by bajiat** [comment]
@nnn Could you take a look at this?

**Comment by jykae** [comment]
Can't find what is causing this, asked @nnn to take a look.

Happens also on OSX, Chrome 54.0.2840.87 (64-bit) and Firefox 49.0.2

**Comment by bajiat** [comment]
Also happens on Internet Explorer 11.

**Comment by jykae** [comment]
width 1200px seems to be breakpoint for this behaviour

**Comment by Uzmani** [comment]
Hi. I'm new to the open source community and a first time contributor.  This seems like a good first bug for me to resolve.  Can I be assigned to this?

**Comment by nnn** [comment]
Easy fix:

`body {
  overflow-x: hidden;
}`

**Comment by Uzmani** [comment]
@nnn, the 'overflow-x: hidden' will work.  However, the root issue that's causing the horizontal scroll are the images in the "getting started" and "completely open source" sections.  The bootstrap class 'col-lg-push-1' is pushing the that div outside of the .container width.

The solution I suggest would be to remove the 'col-lg-push-1' from the html and float:right the image.

**Comment by nnn** [comment]
@Uzmani we will accept pull-request :)

**Comment by bajiat** [comment]
@Uzmani Thanks for taking the initiative and for being interested in the APInf project!
