### ISSUE TITLE
Multiple API Umbrella proxies can be added in Settings

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1868]
Re-enable the button that allows admin to add more than one proxy to a deployment.

# Definition of done
* [x] Admin can add more than one API Umbrella proxy in Settings.

**Comment by jykae** [comment]
Interested

**Comment by jykae** [comment]
@bajiat @brylie what we do with syncApiBackends that is called after adding proxy? It might become quite complex on multiple proxies.

<img width="1268" alt="nayttokuva 2016-11-07 kello 11 15 39" src="https://cloud.githubusercontent.com/assets/293452/20052235/c94a16fe-a4db-11e6-8dc3-83de1a0fb092.png">

**Comment by brylie** [comment]
Perhaps we don't need to sync the API Backends? Removing the sync function would simplify things greatly.

**Comment by Nazarah** [comment]
@jykae @bajiat 
![image](https://cloud.githubusercontent.com/assets/17976243/20090216/6e2026c4-a594-11e6-8d59-0fc798176ad6.png)

Should we give info icons beside each field indicating what does each field do and an example of what value can be put there? Or the Admin would know this information in advance?

**Comment by brylie** [comment]
@Nazarah please add your suggestion as an enhancement issue.
