### ISSUE TITLE
Allow API owner to select one from several configured proxies

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1869]
If there is more than one API Umbrella proxy defined for deployment, allow the API owner to select one of them in the Proxy backend settings.

# Definition of done
* [x] If there is more than one API Umbrella defined, owner can select any of the defined proxies, when adding or editing proxy backend settings.
* [x] If there is only one API Umbrella defined, a simple solution is available for defaulting to the only API Umbrella.
* [x] Proxy base path will come from selected proxy.
* [x] Show an alert to owner, if switching between proxies: "This change will potentially break API calls from applications, if API users are not warned about the change."

Open issues: If owner changes the proxy, do we need to delete the proxy backend from the original proxy? Users will have a broken link, is it our responsibility to notify or is it owner's responsibility to warn the users?

# Wireframes

* In API profile Proxy tab, a dropmenu would appear depending on if there are more than 1 proxy available for selection. 
Open question: in case of only one proxy avialable, should we show the name as hard coded? 
![apiprofilemultiproxyselector](https://cloud.githubusercontent.com/assets/17976243/20094287/3c340b48-a5a9-11e6-83ca-9490bbecacc4.png)

* On selecting a specific proxy, associated fields for that proxy would be populated. In the case for only one available proxy, the fields can appear instantly Proxy tab is selected for viewing:

![apiprofilemultiproxyselector2](https://cloud.githubusercontent.com/assets/17976243/20098746/02647186-a5be-11e6-8d44-bae4e8b8def7.png)

![apiprofilemultiproxyselector3](https://cloud.githubusercontent.com/assets/17976243/20098753/09635f9c-a5be-11e6-8add-27f943e2c038.png)

* When API owner tries to switch from one proxy to another, the following alert window should appear:
![apiprofilemultiproxyselector4](https://cloud.githubusercontent.com/assets/17976243/20098762/12d95d4c-a5be-11e6-85cb-79e5e46da898.png)

**Comment by jykae** [comment]
Interested

**Comment by Nazarah** [comment]
Open Question: Need to consider the scenario when owner wishes to switch from one proxy to another...Alert message?

**Comment by bajiat** [comment]
@marla-singer Could you take this task?

**Comment by marla-singer** [comment]
@bajiat yes, take it.

**Comment by bajiat** [comment]
@marla-singer Great! Can you please estimate the task in days?

**Comment by marla-singer** [comment]
@bajiat Well, I'm not sure, maybe 2-3 days. 

> Show an alert to owner, if switching between proxies: "This change will potentially break API calls from applications, if API users are not warned about the change."

Is it essential to notice user in process switching? Can it be simply static senteces like:
"Be careful: Changing proxy will potentially break API calls from applications, if API users are not warned about the change."

**Comment by Nazarah** [comment]
@marla-singer Are you talking about the owner seeing the progress that the proxy has been switched to another one? I think there a simple feedback dialogue would be good. When the process is done an confirmation dialogue as well. However, I think API users should be notified about the change because they would see a broken link in the API profile page

**Comment by bajiat** [comment]
I think the first step is to warn the owner that they are making a breaking change (from the point of view of API users).

We don't have a notification feature in APInf yet, but notifying the users after proxy has been changed could be considered part of it, when we build one.

**Comment by Nazarah** [comment]
Alert message when API owner tries to switch proxy:
"**Caution!** Changing the proxy will change the call URL and will potentially break API calls from applications. Please inform your API consumers about this change and suggest them to check whether or not they need to obtain new API key from the newly selected proxy."****

**Comment by marla-singer** [comment]
> Open question: in case of only one proxy avialable, should we show the name as hard coded?

@Nazarah Yes, i think, we will show the name as hard code like "**Current proxy is apiUmbrella**" or something that. 
Wireframes look the same like I supposed :)

**Comment by bajiat** [comment]
@Nazarah The current task is about selecting from more than one API Umbrella proxies. So the in the Select Proxy menu you should be able to somehow differentiate between the different API Umbrella proxies in some way. So the selection does not happen between different proxy types, but between different instances of API Umbrella.

**Comment by marla-singer** [comment]
@bajiat It doesn't metter, it's just the name. The values for dropdown list will be taken from collections.

**Comment by Nazarah** [comment]
Use the standard Boot Strap alert popup to display when user want to switch a save a different proxy. This refers to wireframe picture 4.
Changing the wireframe picture 2 and adding them in GitHub repo.

**Comment by marla-singer** [comment]
> Open issues: If owner changes the proxy, do we need to delete the proxy backend from the original proxy? Users will have a broken link, is it our responsibility to notify or is it owner's responsibility to warn the users?

@bajiat Don't have any answers for this question. So I don't know what to do? Save these data or deleted

**Comment by marla-singer** [comment]
@bajiat Another open issue: What behaviour is expected if user select one proxy in list, save settings then select the first item "Select ... " ? Now I hide the form. 
**The question is** delete or not proxy backend configuration? If doesn't delete then we should also hide information about proxy in Details tab. 

I'm confused :confused:

**Comment by marla-singer** [comment]
Another case:
Selected proxy №2 in dropdown list
Then navigate to Proxies page and delete this proxy settings
What behaviour is expected?

**Comment by bajiat** [comment]
> @bajiat Another open issue: What behaviour is expected if user select one proxy in list, save settings then select the first item "Select ... " ? Now I hide the form. 

What if you warn first (text suggested by Nazia) and ask for a confirmation: "Do you really want to change the proxy?"

**Comment by bajiat** [comment]
If user makes a concious decision after being warned, I would say we need to delete from API Umbrella.

Ping @brylie

**Comment by brylie** [comment]
@marla-singer please aim for simplicity here.

Just start with a basic autoform where the user can select a proxy from a dropdown. If the AutoForm event is `update`, then warn the user that the update might have side effects.

We can add enhancements at a later point. For now, all we need is for the user to be able to select a proxy from a list.

**Comment by brylie** [comment]
> If owner changes the proxy, do we need to delete the proxy backend from the original proxy? Users will have a broken link, is it our responsibility to notify or is it owner's responsibility to warn the users?

Yes, delete the backend from the first proxy. Make sure the owner understands the potential side-effects by showing an alert.

It is the owners' responsibility to consider and communicate changes to the API users.

**Comment by brylie** [comment]
> Another open issue: What behaviour is expected if user select one proxy in list, save settings then select the first item "Select ... " ? Now I hide the form.
The question is delete or not proxy backend configuration in our data base? Delete or not from apiUmbrella?

Any time the proxy is changed, and the changes are saved locally:
- warn the administrator of possible side effects
  - loss of analytics data
  - API user broken links
- remove the backend from the previous proxy

Note: selecting the 'Select a Proxy' option from the dropdown and clicking save is functionally the same as changing to a different proxy.

**Comment by marla-singer** [comment]
@bajiat @brylie Thanks for answers! I understood all
