### ISSUE TITLE
Allow only selecting one API from API select list

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1871]
This is a temporary solution to allow owner and admin to select only one API at a time for the dashboard.

# Definition of done
* [ ] User (either owner or admin) can select only one API from the menu.
* [ ] APIs connected to different proxies are shown in the same list. This applies to owners, if they have connected their APIs to different proxies and to admins, if there is more than one proxy.
  *Note: APIs do not need to be distinguished by proxy.*

**Comment by Nazarah** [comment]
@bajiat : are we going to remove the multiple option selector from the API dropmenu in dashboard? We also need to give the information about selecting only one API at a time either as an info tip or as an alert when user tries to select more than 1 API.

**Comment by bajiat** [comment]
@Nazarah I think it would be sufficient to close the menu when one API has been selected. Wouldn't that indicate the user that now you have made a choice and dashboard is updated based on that choice. Not sure if this work implementation-wise, though.
