### ISSUE TITLE
Allow analytics query to be sent to the right API Umbrella proxy

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1872]
When selecting API from the Select API list, the analytics query needs to be sent to the correct proxy (= the one connected to the selected API).

# Definition of done
* [ ] Analytics query is made to the correct proxy path.

*Consider whether the query should be made to ElasticSearch or API Umbrella Admin API. The latter is more secure and more future proof.*

**Comment by bajiat** [comment]
@marla-singer Can we assign this to you? If yes, what would be your estimate?

**Comment by marla-singer** [comment]
@bajiat sure, assign it to me. Estimate about 5 days and I can continue a work after merge of related task https://github.com/apinf/platform/pull/1923
