### ISSUE TITLE
Notify users that time zone used in dashboard is UTC

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1878]
Check what is the time zone shown for requests on dashboard. If it is not UTC (Universal Time Coordinated), change the time to UTC on server (or create a continuation task). Notify user about the time zone in use with a UI text: "Analytics base time in UTC"

**Modification:** The task will be to notify user that server time is used for displaying data. Also the timezone of the server will be shown. No changes into UTC (if server time is not in UTC) will be made.

**Comment by bajiat** [comment]
@shaliko Is it safe to assume that the servers are using UTC time?

**Comment by shaliko** [comment]
@bajiat I don't see any issue.

**Comment by jykae** [comment]
@bajiat In the longer term perspective, I propose to have timezone preference in user profile, so that user could select how to see times in UI.

Though just informing that time is UTC is faster to implement.

**Comment by Nazarah** [comment]
### Wireframes

**Timezone information on Dashboard**

![dashboardservertimezone](https://user-images.githubusercontent.com/17976243/41148246-335a7b54-6b11-11e8-8d2e-404030afe48d.png)

**Timezone information on API Analytics**

![analyticsproxytimezone](https://user-images.githubusercontent.com/17976243/41148159-ff09fc4e-6b10-11e8-9796-7ab360faf418.png)
