### ISSUE TITLE
Link pre-releases to automated build script

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#188]
When building project releases, include a deployment step, if the build succeeds.
## Definition of done
- [ ] Create Jenkins script to automate deployment of pre-releases.
- [ ] Schedule Jenkins script to run on determined intervals.

**Comment by ashakunt** [comment]
This can be easily managed by jenkins. It has lot of plugins to do that. If we have a special script that must be run, then that can also be hooked to run with jenkins.

**Comment by brylie** [comment]
An example [Jenkins deployment script](https://forums.meteor.com/t/jenkins-shell-script-for-anyone-interested/6364) was just posted to the Meteor forums.

**Comment by brylie** [comment]
The script uses [Meteor Up](https://github.com/arunoda/meteor-up).

**Comment by JuusoV** [comment]
This will be finished off tomorrow morning (14/7/2015) with @ashakunt
