### ISSUE TITLE
Automated testcase suite for signed in user

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1882]

**Comment by bajiat** [comment]
Open issue: Create user programmatically and discard the user? How will it work with email validation?

**Comment by Nazarah** [comment]
Test cases:

1. User visits APINF page, checks about and bottom portions of the landing page
2. User registers, verifies the email sent and logins to APINF
(question: should we create a new user everytime the script is run?
how to add a manual step in Selenium IDE to check later by the person running the script. This is needed to verify the email received)
3. User sees the topbar menu
4. User visits the catalog page and checks the options (sorting, switching between views)
5. User opens and API profile and checks the tabs and other information.
(question: should he made a call using the information?
what about trying out swagger documentation)
[alternate suggestion: ^^ the above 2 can be done when user adds an API on his own and can make API calls as well use swagger documentation]
6. User adds an API
[would be better to use url and other things of the petshop API]
7. User sets up proxy settings for the API
8. User verifies that he can get API key
9. User verifies he can access Dashboard and see different charts and tables.
[does user needs to twig with chart?]
10. created user is deleted after the test
[should we logout and login as an admin and perform this step?]

**Comment by Nazarah** [comment]
@bajiat I will discuss with @brylie to see what can be done here.

**Comment by Nazarah** [comment]
an idea of adding an API can be the one used in Mindtrek for APINF.

**Comment by Nazarah** [comment]
@brylie need your help to see if Selenium supports adding a manual step in a testcase which can be checked as a success by the person who is running the script.

**Comment by Nazarah** [comment]
@shaliko : do we still have the API that you designed for Mindtrek? We can use that one for the case when user tries to add an API.
Also it would be good if the swagger documentation is available.

**Comment by brylie** [comment]
@Nazarah here is the Mindtrek API:

https://apinf.io/api/5YqohtnKpEYFR5wbt
