### ISSUE TITLE
wireframe for "Create an eMQTT dashboard to fit MQT analytics data structure"

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1888]
#1881

**Comment by Nazarah** [comment]
Keeping it into Blocked as the main task would start once the dashboard is ready to be placed in APINF.
I can suggest GUI changes or additions that time.

**Comment by bajiat** [comment]
@Nazarah Do you still want to keep this issue or should we close it?

**Comment by bajiat** [comment]
This issue was moved to apinf/emq-analytics-dashboard#5
