### ISSUE TITLE
Write a blog post about open source / open development

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1895]
Write a blog post and publish it on Medium. Topic: open source and/or open development. It should be a 3-4 minute read.

## Definition of done
- [x] Come up with a topic for the post.
- [x] Create an outline of the blog post.
- [x] Write a draft copy.
- [x] Have the draft reviewed by team member(s).
- [x] Finalize the text.
- [x] Find or create relevant graphics.
- [x] Submit to Medium.

**Comment by philippeluickx** [comment]
@brylie I can set you up on medium.com . Let me know when you have an account.
Once all is set up, you can create a draft on medium.com and every editor can read it and provide feedback. Very useful.

**Comment by brylie** [comment]
The post has been [published on Medium](https://medium.com/@brylie/degrees-of-open-b023a3d8a321)
