### ISSUE TITLE
Icons color should be independent from Primary color settings

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1906]
Now we can change primary color in Branding section. But if primary color is white, the icons disappear
**Screenshots:**
- nightly.apinf.io
![joxi_screenshot_1478692406547](https://cloud.githubusercontent.com/assets/20643403/20137658/cae9643a-a68c-11e6-8d52-5a873571d225.png)

- The primary color is white
![joxi_screenshot_1478692370997](https://cloud.githubusercontent.com/assets/20643403/20137647/bd5b572e-a68c-11e6-9ca9-da4c02f6b1a9.png)

**Comment by ilarimikkonen** [comment]
we shall not do this
