### ISSUE TITLE
Warn admin user, if removing a proxy from platform settings

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1920]
If admin user wants to remove a proxy from Settings, that can (or rather will) break all API calls made to the connected proxy backends. User should be asked for a confirmation for removing the proxy with a message like this:

 "You are about to remove a proxy that has NN proxy backends connected to it. Removing the proxy will mean that API calls made to any of the connected API backends will break. Are you sure you want to remove the configured proxy?"

**Comment by jykae** [comment]
@bajiat I modified the proposed string so that we don't need to break it in 2 parts.
```
NN proxy backends are connected to this proxy. Removing the proxy will mean that API calls made to any of the connected API backends will break.
```
This part is shown in confirmation modal header:
```
Are you sure you want to remove the configured proxy?
```
