### ISSUE TITLE
Catalog view: Click on 'Next' redirects to homepage in IE browser

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1922]
# Steps  
1. Visit https://nightly.apinf.io  
2. Signup  
3. Go to Catalog   
4. Go to next page by clicking on 'Next'  (or eg. click on '2' )

# Expected Result 
Redirects to the next page (eg. page 2) successfully    

# Actual Result  
Redirects to homepage  

# Browser 
Internet Explorer 11 

# Operating System  
Windows 10

**Comment by marla-singer** [comment]
@bajiat Since we have used another implementation of pagination for APIs catalog it should be reproduced.
Tested it in IE 11 and no errors are on my side.
@saralavanip Please verify

**Comment by saralavanip** [comment]
@bajiat , @marla-singer , Verified this issue on nightly v 0.44.0, IE 11  browser and it is not reproducible.
