### ISSUE TITLE
Proxy view: Delete 'Proxy backend configuration' details and save not working

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1926]
# Steps  
1. Visit https://nightly.apinf.io 
2. Sign Up  
3. Add API Backend  with proxy 
4. Go to 'Proxy'  
5. Delete 'Proxy backend configuration' details  
6. Click on ' Save and Publish' button  

# Expected Result  
Delete 'proxy backend configuration' details and save settings successfully

# Findings  
-  Currently this feature is not working   
-  Click on 'Save &Publish' button notifies user to fill in the required fields  

# Browser  
1.  Google Chrome version 54 
2.  Internet Explorer 11  

# Operating System 
Windows 10  

# Screenshot  
![screenshot 47](https://cloud.githubusercontent.com/assets/13309358/20267447/84090a3e-aa83-11e6-9f61-229ff0dcf348.png)

![screenshot 48](https://cloud.githubusercontent.com/assets/13309358/20267664/78ff988c-aa84-11e6-9bc2-f1d51276cf9c.png)

**Comment by bajiat** [comment]
Check whether this has been resolved.

**Comment by marla-singer** [comment]
@bajiat The feature works correctly as for me. When a user clicks on "Save & Publish" and doesn't fill all required fields, there are to show the message "Please fill in the required fields". I don't actually understand why action "Delete all information and click on Save button" expects behaviour "Delete 'proxy backend configuration' details and save settings successfully" when datafor saving are not available.

**Comment by bajiat** [comment]
@saralavanip I'm closing the issue based on comments from @marla-singer
