### ISSUE TITLE
Add html ids for following elements in APINF.

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1933]
Add an id to a page element. This helps automatic testing to interact with page elements.

1. API Search page --> no of returned results. [currently it appears as em]

As a minimum, add this one missing id. If you can and have time, find more missing elements.

**Comment by matleppa** [comment]
There exists a correction in development branch in file search/client/search.html
by adding following id: <h3 id="search-results-title"> .
Done by:
alfredjkwak committed on Nov 7 2016

**Comment by bajiat** [comment]
The id is missing from the em. Use e.g. search-results-count. 

See screenshot.
