### ISSUE TITLE
The proxy backend form is closed when proxy path isn't unique

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1935]
Verified on nightly.apinf.io, multi-proxy case

### Steps:

1.Create an api
2. Go to Proxy tab and add the next values:
 - **Proxy**: Nightly umbrella
 - **Proxy base path:** /new-proxy-path/
 - **Api base path:** /
3. Click on button Save & Publish

### Found:
 - The form is closing and user can't understand why
### Reason:
- The proxy base path isn't unique
### Expected:
- The form is opened and an error message is shown

**Comment by jykae** [comment]
Assigned by @bajiat

**Comment by jykae** [comment]
@bajiat @marla-singer can't figure out any simple solution for this. Error is caused on insert/update for unique constraint, autoForm finished onError & resets form. This looks like caused by design. Template helper "showForm" checks proxyId value from ReactiveVar. 

Any smart ideas are welcome.

**Comment by brylie** [comment]
@apinf/core Lets have a chat/discussion tomorrow to think how this should be better designed.
