### ISSUE TITLE
Proxy backend configuration isn't deleted form previously Proxy instance

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1936]
Verified on nightly, multi-proxy case

Test it if you have an access  to:
- https://nightly.apinf.io:3002/admin/
- https://nightly-second-umbrella.apinf.io:3002/admin/

### Steps
1. Create an api
2. Go to Proxy tab and add proxy backend configuration for **Nightly Umbrella** proxy
3. Save it and go to admin panel to https://nightly.apinf.io:3002/admin/login#/apis
4. Verified the existence of your api on **Nightly Umbrella**
5. Change proxy to **Second nightly** and Save it 
5. Verified the deletion of your api from **Nightly Umbrella**
1. Verified the existence of your api on **Second nightly**
1. Change the proxy again

### Found result
- Proxy backend configuration was updated
- Api wasn't deleted form **Second nightly**
- Api was appeared on **Nightly Umbrella**

### Expected
- Api must be deleted form previously Proxy

### Resons
- It happens because MongoDB storages the old value of apiUmbella id and deletion doesn't happen
- onSuccess hook is run earlier then getting apiUmbrella id. 
onSucces hook: https://github.com/apinf/platform/blob/develop/proxy_backends/client/form/autoform.js#L195
getting apiUmbrella id:https://github.com/apinf/platform/blob/develop/proxy_backends/client/form/autoform.js#L185

**Comment by jykae** [comment]
@marla-singer Reproduced, reading code, working on fix
