### ISSUE TITLE
Update the description of Details tab in multi-proxy case

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#1938]
In multi-proxy case Details tab have the wrong description
![joxi_screenshot_1479458989975](https://cloud.githubusercontent.com/assets/20643403/20424238/dcd78c08-ad85-11e6-8d99-379f1ea4a2e9.png)

**Comment by marla-singer** [comment]
It was done in this PR https://github.com/Digipalvelutehdas/APIKA/pull/60

**Comment by bajiat** [comment]
@Should this issue be closed?

**Comment by marla-singer** [comment]
@bajiat Yes
