### ISSUE TITLE
Release testing

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1939]
Test the 0.35 release in staging.apinf.io. Report any bugs or enhancement needs. Update test cases document, if needed.

# New and improved items in release:
- [x] Multiple API Umbrella proxies can be added in Settings
- [x] If several API Umbrella proxies have been added to deployment, API owners can choose to which proxy they connect their APIs
- [x] Get API key and Copy API key button works in multiproxy setup
- [x] Cover photo can be added in platform branding
_ [ ] Language selection bar follows the branding color, when color is default
- [x] Branding form can be saved without adding social media links
- [x] Style for API backlog and API feedback harmonized
- [x] Bootstrap date picker taken into use in Metadata tab service valid from/until fields
- [x] Show a link to return to previous page, when user sees Access denied, Forbidden and Page not found template

**Comment by saralavanip** [comment]
Reported issues:  
https://github.com/apinf/platform/issues/1954    
https://github.com/apinf/platform/issues/1955    
https://github.com/apinf/platform/issues/1956
