### ISSUE TITLE
Usage instructions not updated when API connected to another proxy

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1954]
# Steps  
1. Visit https://staging.apinf.io 
2. Login as admin 
3. Go to 'Proxies' 
4. Add multiple proxies and save (eg. proxy 1 , proxy 2)
5. Sign out 
6. Sign Up / Sign In as owner 
7. Add API (eg. API 1) with proxy (eg. proxy 1)
8. Click on 'Get API key'  
9. Add another API (eg. API 2) with proxy (eg. proxy 2)
10. Go to 'Details' view of above added API 2  

# Findings  
Usage instructions have the same API key as API 1  before getting API key for API 2 which is proxy specific 

# Expected Result
Usage  instructions must be updated 

# Screenshots  
![selection_148](https://cloud.githubusercontent.com/assets/13309358/20603217/2f6bc280-b269-11e6-96df-51cd88c68f67.jpg)     

![selection_149](https://cloud.githubusercontent.com/assets/13309358/20603227/38160b98-b269-11e6-8204-b34086b8b512.jpg)

**Comment by brylie** [comment]
This may still need attention, reopening. Also, there may be a regression with the 'get' / 'copy' API key button.

**Comment by jykae** [comment]
@brylie can you point the regression? I thought I fixed it with bigger issue on changing proxy last year.

**Comment by brylie** [comment]
I am not sure. We can perhaps close it again.
