### ISSUE TITLE
Incomplete translation of 'Branding' page in Suomi view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1955]
# Steps  
1. Visit https://staging.apinf.io  
2. Go to language bar and select 'Suomi' 
2. Login as admin  
3. Go to 'Branding'   

# Findings  
Incomplete translation of 'Branding' page in Suomi view.  
- Text field titles, button title text for 'Upload cover photo' are in English language   

# Screenshot  
![suomi_branding_view_english_text](https://cloud.githubusercontent.com/assets/13309358/20621547/99ed78da-b307-11e6-91e4-116308dfeb88.PNG)

**Comment by saralavanip** [comment]
@bajiat , Suomi views of 'Sign Up' and 'Sign In' pages are not translated  as well. 

Screenshots:  
![suomi_view_signup_page](https://cloud.githubusercontent.com/assets/13309358/20831586/4d9a44e0-b88e-11e6-8b0c-61772ce5313c.PNG)   

![suomi_view_signin_page](https://cloud.githubusercontent.com/assets/13309358/20831633/8966eeba-b88e-11e6-8add-ad4226243892.PNG)

**Comment by bajiat** [comment]
I assume that there are no i18n tags for the missing branding texts, because they were not included in the translation round that was just completed. Check at least the following UI strings: 
- Upload cover photo (button)
- Colors (panel title)
- Primary (field title)
- Primary text (field title)
- Social media (panel title)

**Comment by bajiat** [comment]
@manzapanza I'm unassigning you since you have already added the missing i18n tags and your PR was closed. 

This issue can be completed in next translation round.

**Comment by bajiat** [comment]
Translation round completed. To be verified from nightly.

**Comment by bajiat** [comment]
Verified in nightly, all strings now have a Finnish translation. Closing as resolved
