### ISSUE TITLE
Automatic changelog

### ISSUE THREAD

**Issue by jykae** [apinf/platform#1957]
To reduce manual work for releases,
try out https://github.com/skywinder/github-changelog-generator

# Definition of done
* [x] Check the options for creating automatic changelog and make a proposal

**Comment by nnn** [comment]
Tried out [GitHub Changelog Generator](https://github.com/skywinder/github-changelog-generator), works like a charm.
[Output example](https://gist.github.com/nnn/44d00b24022fb648814d29036fbebce2) was generated by command:
```
github_changelog_generator --token [my token]
```
Usage:
https://github.com/skywinder/github-changelog-generator/wiki/Advanced-change-log-generation-examples#basic-usage

Here are the alternatives:
https://github.com/skywinder/Github-Changelog-Generator/wiki/Alternatives

**Comment by nnn** [comment]
@bajiat let know, if you need a demo for this.

**Comment by jykae** [comment]
Great that you decided to embrace automation :)

**Comment by nnn** [comment]
Tested with @bajiat on Windows. Couldn't make it work, due to existing bug, but since she is switching to Ubuntu, won't spend time to make it work on Windows.

@apinf/developers if anybody has a desire to test this package - please do. If you have other suggestions, post them here.

**Comment by shaliko** [comment]
@nnn @bajiat We can create simple web app, that will generate for us report from browser, based on "https://github.com/skywinder/github-changelog-generator".

**Comment by nnn** [comment]
@shaliko yeah, sure, it would be nice, but I think it doesn't worth our efforts, since this is a biweekly dealio.

**Comment by shaliko** [comment]
Docker version:

```
docker run -it --rm -v $(pwd):/app prooph/github-changelog-generator --token=067c491e.... --since-tag=0.39.0  -u apinf -p platform
```

**Comment by nnn** [comment]
@brylie @bajiat ready for review. What are next steps here?

**Comment by brylie** [comment]
It seems like, to some extent, this process relies on Github metadata such as label, milestone, issue description, etc. 

As a follow up to this task, we should include some brief note(s) about how our development process should use the Github metadata, so this package will correctly identify our changes. E.g. what labels does it look for?

**Comment by bajiat** [comment]
@nnn Could you create the changelog.md file to apinf develop branch?

**Comment by frenchbread** [comment]
Here is one possible approach for generating changelogs - [conventional-changelog]( https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli)

Tested it just now & works fine. Basically all that is needed is an NPM package installed globally. So it should work on Windows as well.

This lib has an Atom extension as well, but I couldn't get it working [there](https://github.com/conventional-changelog/atom-conventional-changelog/issues/4)
