### ISSUE TITLE
Improve project structure

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/platform#1958]
The current project filesystem has about 30 directories and does not seem to follow any guideline. This makes the code difficult to understand and evolve. The [meteor website](https://guide.meteor.com/structure.html) has some guidelines to structure a meteor app using ES 2015 modules, but there might be other good ways as well.

What I envision for tidying up the filesystem is:
- [ ] list all directories that can be structured using ES 2015
- [ ] open an issue for refactor each of these modules
- [ ] update the documentation accordingly and incrementally

**Comment by mauriciovieira** [comment]
@brylie @bajiat my first big suggestion.

**Comment by brylie** [comment]
For what it's worth, we did put some thought into the current structure, and documented it in our [contributor guidelines](https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md#file-structure). This is not to say our structure will never change, but rather we intentionally grouped code into feature modules at the root level of the project. When viewing the root level of the project, you can see our feature modules such as *dashboard*, *catalog*, *api*, etc.

**Comment by mauriciovieira** [comment]
I understand, but still it seems to much for the root directory. What about moving all modules into a `modules` subdirectory, leaving `public`, `docker`, `modules` (and maybe a few other directories) in the root?

**Comment by brylie** [comment]
Sure, we might even convert the modules to git submodules. 

A 'grand vision' would be to architect Apinf in a similar manner to Drupal, where each feature is a module and can be managed from a 'Modules' administrative view, including fetching and installing modules from NPM. The NodeRed platform has a similar module management UI:
![peek 2016-11-30 12-38](https://cloud.githubusercontent.com/assets/17307/20749181/00055890-b6fa-11e6-8c3b-eae41b16afa1.gif)

**Comment by ilarimikkonen** [comment]
wow
