### ISSUE TITLE
To prepare automated testing for adding an API, consistent ids of "Name" "Description" and "URL" fields are not available

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1960]
![image](https://cloud.githubusercontent.com/assets/17976243/20793233/b4c2480e-b7ce-11e6-9710-da3fcb773869.png)

The fields mentioned above have their IDs change each time the page is reloaded
I tried with targeting the html attributes name and data-schema-key, but doesn't work

**Comment by marla-singer** [comment]
@Nazarah You can find this element using CSS selector. 
Selector for this element is `"#addApiForm input[name="name"]"`
For field Description is `"#addApiForm inut[name="description"]"`
It means that find **input** element where attribute _name_ has value **_name_** and input element is child of element with id _addApiForm_

More details about CSS selectors:
http://www.w3schools.com/cssref/css_selectors.asp

I hope it helps you

**Comment by Nazarah** [comment]
@marla-singer this is something haunted but the attribute name actually did the trick! 0_0
but for some weird reason it was always throwing "exception handler not found" the previous day.
Now I am able to add the API backend.
Thanks a lot for your help. :)
