### ISSUE TITLE
Catalog:  Filter 'My APIs / Bookmarks' from 'Next' page not working

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1962]
# Steps  
1. Visit https://nightly.apinf.io  
2. Sign in 
3. Add APIs 
4. Go to Catalog  (default is 'Show all' )
5. Select and bookmark any API   
6. Go to next page by clicking on 'Next' / page 2   
7.  Click on My APIs/ My Bookmarks  

# Expected Result
Displays all 'My APIs /My Bookmarks' successfully   

# Actual Result
Shows an empty page   

# Screenshot   
![catalog_next_myapis_empty_page](https://cloud.githubusercontent.com/assets/13309358/20829129/6e01f7e2-b883-11e6-9b47-aae9c1371854.PNG)

![catalog_nextpage_mybookmarks](https://cloud.githubusercontent.com/assets/13309358/20829099/43c23172-b883-11e6-9d8d-46f7b4030d90.PNG)

**Comment by jykae** [comment]
Interested
