### ISSUE TITLE
Add 'Append Query String Parameters' field to Proxy Backend form

### ISSUE THREAD

**Issue by santeriv** [apinf/platform#1965]
# User story
> As an **API Manager**
I want to **add query parameters to every API request** made from the proxy
so that end users do not need to see or add the query parameters themselves

# Context
 API Umbrella, or primary proxy, has a field called 'Append Query String Parameters' on the Backend configuration form. However, we have not 'mirrored' the 'query string parameters' field in our user interface.

## API Umbrella screenshot
![API Umbrella showing query parameters and request headers fields](https://cloud.githubusercontent.com/assets/17307/20966119/8bdb27b4-bc81-11e6-83ba-bc5e06f9f088.png)

# Feature
Add the 'query string parameters' field to our schema and user interface.

# Original idea
To make calling of prefix simple even with queryParams 

https://apinf.io/myPrefix -> https://proxyproxyservicesite.com/query?queryParam1=http://www.finalproxytarget.site/catalog/subcatalog/show.php&queryParam2=find('%20.my-class%20div')&queryParam3=true

Instead of (mapping myPrefix to query)

https://apinf.io/myPrefix?queryParam1=http://www.finalproxytarget.site/catalog/subcatalog/show.php&queryParam2=find('%20.my-class%20div')&queryParam3=true

(Tried - perhaps it is older version of apinf - in APIKA -> https://umbrella.digipalvelutehdas.fi/urheilukellot/?api_key=YOUR_KEY&site=gigantti.fi/catalog/puhelimet-ja-gps/fi-urheilukellot/urheilukellot&selector=find(%27a.product-name%27)&forceText=true )

And leaving for the user's responsibility all the queryparams.

**Comment by santeriv** [comment]
First fix proposal is in https://github.com/apinf/platform/pull/1964

**Comment by bajiat** [comment]
@santeriv Thanks for taking an interest in APInf and contributing! Your PR is being reviewed.

**Comment by nnn** [comment]
Interested.

**Comment by brylie** [comment]
@santeriv thank you for opening this feature request. We are excited to include it in the next Apinf release (0.41.0)!

Please feel free to propose any other features that would be helpful to you or your organization.
