### ISSUE TITLE
Renew Let's encrypt certificate not working

### ISSUE THREAD

**Issue by shaliko** [apinf/platform#1971]
Renew Let'e encrypt certificate now working.

Issue related to wrong generated renewal script.

https://github.com/smashwilson/lets-nginx/blob/master/entrypoint.sh#L141

**Comment by bajiat** [comment]
Let's check if we can close. let's discuss by chat.

**Comment by shaliko** [comment]
No new releases here https://hub.docker.com/r/smashwilson/lets-nginx/, so issue not fixed yet.
