### ISSUE TITLE
Create a basic REST API

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1974]
This is a task for developers who will be working during 27 - 30 Dec. Design and create a basic REST API. Figure out how to host it. Consider adding it to apinf.io, when it's ready.

The purpose is to get more familiar with the role of API owner.

This is not a central task for sprint, it is only a side task for the days between Christmas and New Year. So it should  be a small project that does not spill over to January.

**Comment by philippeluickx** [comment]
I would suggest to either start really naive (so google how to create an API and follow roadbump to roadbump) or then start really pro (design driven API, use SDK generation,...)
It would be nice to keep a sort of diary, where you can outline the steps you took, the frustrations you had and solutions you found.

**Comment by ilarimikkonen** [comment]
nope
