### ISSUE TITLE
Capture and track application exceptions

### ISSUE THREAD

**Issue by shaliko** [apinf/platform#1986]
As developer I want get catch and logs exceptions from runtime. 

- Will be good have dashboard with bugs.
- Integration with GitHub issues.
- Capture runtime environment like Browser version, OS platform, etc...

My personal preference https://airbrake.io, but any tool will be good.

# To do's
* Look into open source alternatives for capturing exceptions
* Make a documented proposal with pros and cons
* Store the research and proposal in docs repository

# Definition of done (to be created by assignee)

**Comment by brylie** [comment]
What would be a minimum idea that we could build and expand on? E.g. how far could text file or database logging take us towards the goal?

**Comment by brylie** [comment]
[Sentry](https://docs.sentry.io/) is an open source exception monitoring and reporting tool.

We are trying to stick close to the open source exosystem throughout our project stack, even internal DevOps tools. Lets find out what open source options we have here.

**Comment by philippeluickx** [comment]
+1 on Sentry. I have used it and it has been a breeze. We do have to get the approval maybe, as it becomes a paid service when using SaaS model and reach a certain threshold?

https://www.quora.com/Why-would-you-use-Airbrake-over-Sentry

Also checked quickly if we have an integration with meteor and there I only found https://github.com/deepwell/meteor-raven and some older forum posts.

Some others to consider:
- https://newrelic.com/
- https://www.appdynamics.com/
- https://www.datadoghq.com/ (less popular)

**Comment by philippeluickx** [comment]
Blogpost from 2016 still uses to older meteor-raven plugin:
https://ianhowson.com/blog/connecting-meteor-to-sentry/

Also note that there is a fork that is still being maintained: https://github.com/dVelopment/meteor-raven

**Comment by philippeluickx** [comment]
Obviously there is also https://kadira.io/

**Comment by ccsr** [comment]
+1

**Comment by bajiat** [comment]
Research document was merged.

**Comment by brylie** [comment]
Re-opening, so we can follow through and install a solution to catch application exceptions.

cc: @marla-singer

**Comment by mauriciovieira** [comment]
What was the decision? Does @jawidahmadi still has a link to post here?

**Comment by brylie** [comment]
@bajiat may we set up an exception tracking service on our Nightly server, as a test?

**Comment by marla-singer** [comment]
@mauriciovieira [Link to document](https://github.com/apinf/docs/blob/master/docs/research/Capture_Track_Application_Exception.md)
But it doesn't contain any decision about what to use

**Comment by mauriciovieira** [comment]
@marla-singer Spasibo. I will suggest another solution there 👍

**Comment by philippeluickx** [comment]
What would be the correct criteria to trial one service and move forward with this?

**Comment by brylie** [comment]
I motion that we move forward with [@mauriciovieira's proposed exception tracking solution](https://github.com/apinf/docs/blob/master/docs/research/Capture_Track_Application_Exception.md#elk-stack--open-source-logger). 

If we have a basic consensus, the next step would get approval from @bajiat to work on this during the sprint cycle. We would probably need support from @shaliko to configure this on one or more of our deployments.

**Comment by philippeluickx** [comment]
I like the OS of the proposal. Just quickly checked what the situation is with Kadira (since they stopped developing for meteor) and I have the impression everything is OS-ed as well?
https://github.com/kadira-open/kadira-server
Pros: it's built for meteor
Cons: no-one is maintaining it

So +1 on @mauriciovieira proposal

**Comment by bajiat** [comment]
Go ahead with adding the exception tracking as long as it does not affect work with dashboard or eMQ integration.

**Comment by shaliko** [comment]
@mauriciovieira @brylie @marla-singer @philippeluickx Another interesting option https://github.com/errbit/errbit
https://www.npmjs.com/package/airbrake-notice

Setup errbit server will require few minutes and probably I can reuse it in other Sampo projects.

**Comment by mauriciovieira** [comment]
@shaliko this solution would  be the best if we had something similar to [FiLog](https://github.com/FGM/filog) to send to the Airbrake/Errbit server, or if we could plug FiLog with [airbrake-notice](https://www.npmjs.com/package/airbrake-notice) somehow. 

Anyways, [https://github.com/errbit/errbit](errbit) server seems to be the quickest setup and the @apinf/architects should come up with some coding infrastructure with the standard way for logging errors.

**Comment by brylie** [comment]
@mauriciovieira the [errbit](https://github.com/errbit/errbit link is broken :wink:

**Comment by brylie** [comment]
Also, how do errbit and Sentry compare? My vote is leaning towards Sentry, but I can be easily swayed, since I don't have any practical experience here :smile_cat:

**Comment by shaliko** [comment]
@brylie Sorry, not noticed your question.

> Also, how do errbit and Sentry compare?

1) Errbit it's open source clone on Airbrake, so comparing you can find here https://github.com/apinf/docs/blob/master/docs/research/Capture_Track_Application_Exception.md
2) Many of Airbrake SDK tools can be used for send data to Errbit.

**Comment by shaliko** [comment]
@brylie https://www.slant.co/versus/964/5110/~sentry_vs_airbrake

**Comment by shaliko** [comment]
@brylie Looks like Sentry biting Airbrake https://www.quora.com/Why-would-you-use-Airbrake-over-Sentry

**Comment by phanimahesh** [comment]
FWIW, I vote for Sentry, self hosted. If for some reason sentry can't be used, my next vote would be to do it the hard way with ELK.

**Comment by shaliko** [comment]
@phanimahesh Yep, I already booked sentry.samposoftware.com.
