### ISSUE TITLE
Horizontal scroll bar in production frontpage

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1995]
Go to apinf.io (production). There is a horizontal scroll bar on the frontpage.

Seems like it's not present on other pages.

Edit: not really awake here, meaning horizontal - not vertical (thanks @Nazarah )

**Comment by Nazarah** [comment]
@philippeluickx Think it should be "horizontal", right?
![image](https://cloud.githubusercontent.com/assets/17976243/22417327/52696e34-e6dc-11e6-99cb-5feb84dd62d2.png)

**Comment by philippeluickx** [comment]
Yes!

**Comment by bajiat** [comment]
@philippeluickx I can't see the scrollbar and I remember there was a pull request fixing this. If you can't see it in nightly, it should be resolved.

**Comment by nnn** [comment]
Resolved here https://github.com/apinf/platform/pull/1934
