### ISSUE TITLE
Add API to APInf by uploading a Swagger file

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1998]
# Goal
An API owner can add an API by uploading a Swagger file or pointing to a Swagger file. The Swagger file is also connected as the documentation file for that API.

# Solution proposal
- This could be the primary option on the page: Add an API by adding a Swagger OpenAPI design file
  - The Swagger/OpenAPI fields need to be matched with the API fields in the API schema.
  -  In this case lifecycle status needs to be added afterwards.
- Secondary option: If you don 't have the file, fill in the d API form 
In this case, e.g. description can be taken from the Swagger description field etc.

# Wireframe
1. Add API page now has the option to upload a swagger json/yaml file or Open API document from the usual add fields (name, host, etc)
The document can also be linked from GitHub
This option (upload button) is appeared as focus when user comes to the page for the 1st time.
The usual add fields appear disabled.
![swagger uploader](https://user-images.githubusercontent.com/17976243/28363683-1bdde244-6c8a-11e7-9ee5-f996efe22f8f.png)

**p.s.** User at a time can use the uploader or the link field. selecting one disables the other or erases existing content in that field

2. On clicking API Name field, the above options get disabled.
If user selects Design lifecycle phase, Link text appear to prompt user to use OpenAPI Designer.

![normal add](https://user-images.githubusercontent.com/17976243/28363823-a021852e-6c8a-11e7-943c-792ade6c1d12.png)

3. If user clicks the link, the API is added automatically and user is redirected to API Documentation tab directly.
The editor appears in Edit mode with the API name and hostname already populated from the given inputs

![editing doc](https://user-images.githubusercontent.com/17976243/28364016-76addb9c-6c8b-11e7-9e07-91eb7a5ce884.png)

When OpenAPI Designer is accessed from tab, the About tab in the designer should not appear.
User can open the editor in browser, in which case, user will be navigated to the main OpenAPI Designer page with the populated inputs.

4. In any case, if a documentation exists in the API profile, an Edit API Document button appears in that tab.
On Clicking the button, the swagger file or Open API document opens in editable mode.

![api documentation editor](https://user-images.githubusercontent.com/17976243/28363917-09395708-6c8b-11e7-9102-ad52e1eba066.png)

**Comment by xylix** [comment]
@Nazarah The "link in Github" should probably just be "link api specification" or something like that. I think it should allow  linking from anywhere.   

Otherwise looks good. 

Adding user APIs to the Apinf catalog with only an Open API specification provided by them will require some parsing of the swagger file but that should be doable.

**Comment by bajiat** [comment]
@Nazarah Why does the uploaded API / documentation file appear in the Open API designer window in step 3?

**Comment by Nazarah** [comment]
@bajiat thanks for noticing this. With the integration, upload button should not be present in the Documentation tab in API profile. the correction needs to be made in the wireframe. However, I'd ask @tulir and @xylix to confirm about it.

**Comment by xylix** [comment]
@nazarah Why shouldn't the upload button be visible?

**Comment by Nazarah** [comment]
@xylix please clarify me in the following things:
If we upload a swagger/OpenAPI file while creating the API, in the Documentation tab, the file would be visible both in view mode and edit mode. Also in that tab, there is an option to upload a swagger file. So in such case, is it required to have the upload button in OpenAPI Designer appearing? It seems redundant to have 2 upload buttons.

**Comment by xylix** [comment]
@Nazarah Well, if user wants  to upload when they are in edit mode, it would be annoying to have to leave edit mode. 

However, we have many buttons right now and disabling button(s) would make the UI more simpler which is good in my opinion.

I am pretty sure it's quite easy to disable button(s) when the designer is in an iframe.

**Comment by deligence-dharmendra** [comment]
Hi @preriasusi 
I think such type of functionality already exists in the APInf app under Add API section. If I'm not wrong.

Please advise

**Comment by preriasusi** [comment]
@deligence-dharmendra Yes it does. Let's close this one ...
