### ISSUE TITLE
Analytics per API per user

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1999]
# User stories
As an API owner I want to be able to see usage analytics for my API for a particular user so that I can identify both most frequent users and hobby users.
As an API owner I want to be able to see which users have most problems with my API so that I can solve the problems.
As an API owner I want to be able to see usage analytics  for my API for a particular user for a month so that I can charge for the API usage.

# Description

This is the first step towards API monetization: being able to identify and see how much a user has used a particular API. This should be possible for both individual API user and for the API owner.

Analytics per API consumer is also a customer wish for dashboard for a customer , who is not interested in monetization, but rather finding users with problems or serving the most frequent users well.

# To be considered
* User is a filter for dashboard
  * Filter from a prepopulated list
  * Intelligent search
* Allow select a user either by username or email. API keys should not be disclosed.
  * Easily find the most frequent users
  * Easily find the users with most problems

**Comment by Nazarah** [comment]
closing this. too old issue.
