### ISSUE TITLE
Define Privacy policy and terms of use texts for apinf.io

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#2002]
We should have them.

Related: https://github.com/apinf/platform/issues/578

**Comment by bajiat** [comment]
I think we should have
1. an UI for adding privacy policy and terms of use
2. texts for privacy policy and terms of use for our own deployments

**Comment by philippeluickx** [comment]
I'm ok with having them editable, but I would rather go for a sensible default that can be adapted.

**Comment by philippeluickx** [comment]
https://github.com/RocketChat/Rocket.Chat/commit/8908120386d68a7a3890bac05ebf40c1e1216b18

Rocket chat seems to have them?

**Comment by philippeluickx** [comment]
There are some generators:

- https://www.iubenda.com/
- https://termsfeed.com/privacy-policy/generator/
- https://www.freeprivacypolicy.com/

More into the area of CC:

- https://wiki.creativecommons.org/wiki/CC-inspired_projects_for_Terms_of_Service_and_Privacy_policies

Machine readable privacy policy?

- http://softwareengineering.stackexchange.com/questions/257660/is-there-something-like-creative-commons-licenses-for-privacy-policies

**Comment by philippeluickx** [comment]
First draft of the Privacy policy, based on Sampo Software policy:

Privacy Policy
APInf Oy | User Register 
Personal Data Act (523/99) 10, 24 § 
APInf Oy (”Controller”) is committed to safeguard the privacy of those persons (“User") using the services, products and websites (“Services”) distributed, published or otherwise made available by the Controller, including our website at apinf.io as well as any other services provided to you by the Controller. This Privacy Policy provides Users information on how the Controller processes Users’ personal data and how the Controller protects the same. Personal data refers to personally identifiable information, such as a name, address and Email address. We encourage the User to read this document before using our Services. 
 
1. The purpose of processing the personal data 
Personal data may be processed for the purposes of using, maintaining and developing the Services. The Controller commits to adhere to the provisions of the Personal Data Act and other such applicable laws and regulations pertaining to processing of personal data, as well as process personal data in compliance with good processing practice. The Controller will pursue to take appropriate measures in order to prevent unauthorized access to personal data, any inappropriate use thereof and any possible inaccuracies. All personnel processing personal data are obliged to keep such information strictly confidential. 
 
2. Content of the register, regular sources of information, accuracy of personal data
The register will consist of the following information:
Name and e-mail address
Billing information, including credit card information and your billing address
Information concerning Service usage
Location information (such as zip code or postal code and country)
The IP Internet (IP) address and URL of the Web site that sent you to the APInf’s registration page
Demographic information provided by you (such as language, gender and age, and, if applicable, software program and content preferences and personalization information)
Whether you logged into or out of a APInf's website, or changed your password or billing information.
Navigation throughout any Service, time spent and any other usage statistics of the User.
The above information will be collected from Users when they become registered Users of our software programs upon completion of the registration process on APInf's website. 
 
3. Disclosed data 
The Controller will not disclose personal data stored in the register to third parties for direct marketing, market research, polls or public registers. In exceptional circumstances personal data may be disclosed to third parties if required under any applicable law or regulations or order by competent authorities, or in order to enforce our Terms of Use (https://apinf.io/terms-of-use) and to investigate possible infringing use of the Services, as well as to guarantee safety of the Services. The Controller may use external service providers to provide technical solutions for processing stored data and access the stored data by using a technical interface. The Controller will not transfer data to countries outside the European Union or the European Economic Area. 
 
4. Data protection and the principle how the personal data is secured
The register will be maintained in external service providers’ servers with appropriate safeguards, such as password protection, granting the access to the stored information only to the Controller. The register is protected by appropriate industry standard, technical and organizational safety measures. The database will be accessible only to those persons expressly authorized by the Controller. 
 
5. Website cookies 
What is a cookie? A cookie is a string of information stored in a text file that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. Cookies do lots of different jobs, like letting you navigate between pages efficiently, remembering your preferences, and generally improve the user experience. They can also help to ensure that advertisements you see online are more relevant to you and your interests. The Controller uses cookies to help it identify and track visitors, their usage of the Website, and their Website access preferences. Users who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using the Website, with the drawback that certain features of the Website may not function properly without the aid of cookies. Your cookie settings can also be adjusted by configuring your browser settings. For a video about cookies visit www.google.co.uk/goodtoknow/data-on-the-web/cookies. The cookies will not enable the Controller to access and review information stored on a User’s computer. The Controller will neither store nor review any information gathered through cookies. 
 
6. APInf’s use of remarketing with the Service’s Analytics 
APInf website uses nalytics solutions to track the visitors on its site. The data collected through analytics solutions is only used internally for creating and offering better services through APInf’s website.
 
7. Information on the processing of personal data

Users are entitled to review any information collected on him/her and stored in the register. When User wishes to use the above right to review stored information, User should send a signed request thereof to the Controller using the contact details below. The Controller may, at its own initiative or upon a User’s request complement, correct or delete incomplete, inaccurate or outdated personal data.
You may opt-out of receiving promotional emails by following the instructions in those emails. If you opt-out, the Controller may still send You non-promotional customer information, such as emails about Your account, providing the Services or the Controller’s ongoing business relations.
 
8. Changes to the Privacy Policy 
The Controller may change this Privacy Policy from time to time, and at the Controller‘s sole discretion. All changes hereto will be made available on this website, which is why the Controller encourages Users to frequently check this page for any changes to this Privacy Policy. Changes hereto will not prejudice Users’ rights without their consent. The Controller will inform the Users of material changes by sending an email or other such applicable way.
 
9. Controller and the person in charge 
The User may at any time contact the Controller at the address below. APInf Oy Business ID: 2810151-6 Address: ? Finland Contact email: [privacy@apinf.io] www: https://apinf.io

10. APInf’s Service collects information concerning other services available in the Internet. APInf collects information when those external services are accessed, such as IP address, date and time of the request.
APInf is not responsable for the usage of any external service. Users are advised to read the Terms of Use and Privacy Policy of each service seperatly.


Privacy policy last updated on 08.03.2017

**Comment by philippeluickx** [comment]
Terms of use first draft:
TERMS AND CONDITIONS
These Terms of Use (“Terms”) apply to your ('you') use of services, products and websites (“Services”) distributed, published or otherwise made available by APInf Oy (Business ID: 2810151-6; 'APInf’, ‘us’, or 'we'), including our website at apinf.io as well as any other services provided to you by APInf. These Terms together with our privacy policy (https://apinf.io/privacy-policy) which is incorporated by reference govern the relationship between you and APInf regarding your use of our Services. These Terms affect your legal rights and obligations, so if you do not agree to the Terms, do not use the Services. 

The use of our Services is subject to the following Terms:

The content of the pages of this website is for your general information and use only. It is subject to change without notice.

As a user, you are solely responsible for providing correct information about you and or your business. Also, as a personal user or business it will be your responsibility to pay all the taxes in your country as they are applicable.
Before you plan to purchase any of the services, we strongly recommend you to try out the services in our free tier. 

APInf provides certain Services that are developed under Open Source Software licenses. This means that the software is available for you to use and contribute, within the constraints of the applicable license.
APInf hosts these Services in a Software as a Service (SaaS) offering.

Software support or maintenance services are provided subject to a separate agreement (if any). 

APInf may make available Software updates from time to time.

Fees: The usage fees shall be as specified in our price list is in force when the bill is generated. All prices are subject to change. If the prices change, APInf will notify you, and provide you an opportunity to review those changes to your usage fees and shall give you at least 30 days’ notice. The notice may be provided by email. Applying those changes to you is not subject to you approval of the changed pricing. If you do not approve such new usage fees, you can opt-out of the service at any time you wish. Otherwise the new fees shall be applicable between APInf and you.

You agree to pay the applicable fees in consideration of the License in accordance with the provisions of these Terms.

All payments are non-refundable. Prices shown do not include any duties, sales, use, excise or similar taxes. All taxes shall be added to prices shown and you agree to pay same.

Warranty: APInf provides the services “as is” and “as available” and makes no warranties, express or implied. Your use of the service is at your sole risk.
APInf disclaims all warranties and representations (express or implied, oral or written) with respect to these terms, the service, any of the content provided via the service.

Neither we, nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.


Limitation of liability: APInf shall not be liable to you in contract, tort, or otherwise, whatever the cause thereof, for any loss of profit, business or goodwill or any indirect, special, consequential, incidental or punitive cost, damages or expense of any kind, howsoever arising under or in connection with this Agreement, even if any of the foregoing were reasonably foreseeable. However, under no circumstances shall APInf’s liability exceed fifteen percent (15%) of the total compensation paid by you to APInf under these Terms during a period of twelve (12) months immediately preceding the claim.

Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.


From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).

Force Majeure: APInf shall not be liable for any delay or failure to perform resulting from causes outside the reasonable control of APInf, including without limitation any failure to perform hereunder due to unforeseen circumstances or cause beyond APInf’s control such as acts of God, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, strikes, or shortages of transportation facilities, fuel, energy, labor or materials.

You may terminate your license at any time by removing the software from your system and/or deleting your user account on apinf.io.
APInf retains the right to terminate your user account and remove any content provided by you, without providing any reasons.


These Terms shall be governed by and construed in accordance with the laws of Finland, excluding its choice of law provisions.

Any disputes, differences or questions between the parties with respect to any matter arising out of or relating to these Terms shall be finally settled by the Helsinki District Court.
If a dispute concerning a sales contract cannot be resolved through negotiation between the parties, the consumer can submit the matter to the Consumer Disputes Board (www.kuluttajariita.fi) for resolution.

Before taking the matter to the Consumer Disputes Board, the consumer should contact the Local Register Offices' Consumer Advisory Service (www.kuluttajaneuvonta.fi).
The Online Dispute Resolution website (http://ec.europa.eu/odr) is an official website managed by the European Commission dedicated to helping consumers and traders resolve their disputes out-of-court.

Terms of use last updated on 08.03.2017

**Comment by bajiat** [comment]
Should we mention the following even though we are not storing them yet?
> Billing information, including credit card information and your billing address
> Information concerning Service usage
> Location information (such as zip code or postal code and country)

**Comment by bajiat** [comment]
I added the address to privacy policy.

**Comment by philippeluickx** [comment]
It's better to be covered. It's on the roadmap, so at least we won't forget it then.

**Comment by bajiat** [comment]
texts defined, cosing the issue. To be added to the front page, when the UI is available.

**Comment by philippeluickx** [comment]
@bajiat how do we not forget to add the texts once this features is deployed? Do we have a ticket for that? Otherwise I would keep this open...
