### ISSUE TITLE
Timeline rendering problem

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2003]
(Screenshot is taken from APIKA)

# Reproduction Steps

1. Sign in and go to https://apika.digipalvelutehdas.fi/dashboard
2. Select API Hello Apinf Demo from dropmenu
3. Give the time range 10.01.2016 to 01.02.2016
4. Observe the timeline

# Result

Horizontal axis on API request timeline shows time range from Jan 1st 2017 to Jan 31 2017, although the time range is from October 2016 to February 2017.
Also the time divider "Month" is being selected which indicates usage in the current month. However, the date range shows time more than 1 month.

![image](https://cloud.githubusercontent.com/assets/17976243/22498017/52be989a-e85e-11e6-97ae-e08f36a2ac55.png)

# Expected Result:

Request timeline should be rendered according to the date range given.
For particular date range none of the specific time dividers (Hour/Day/Week/Month) would get selected.

**Comment by marla-singer** [comment]
@bajiat Have to be fixed in a new Dashboard

**Comment by bajiat** [comment]
Closing, since we are in the progress of implementing the new version/generation of dashboard.
