### ISSUE TITLE
Fully test eMQ REST API workflow with eMQ

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2005]
_From @bajiat on February 2, 2017 12:51_

Make sure eMQ is using users and access control rules added by the REST API.

# Definition of done
## Admin user access
* [x] Create **Admin user** to use EMQ REST API

## Test publishing
Using the **Admin user**:
* [x] Create **EMQ user** via REST API
* [x] Create **ACL rule** for the **EMQ user** to publish to a topic
* [x] Try **publishing** to that topic as **anonymous user**
* [x] Try **publishing** to that topic as the **EMQ user**

## Test subscription
* [x] Create another **EMQ user**
* [x] Create **ACL rule** for the user to **subscribe to a topic**
* [x] Try subscribing as **anonymous user**
* [x] Try subscribing as **authorized user**

_Copied from original issue: apinf/meteor-oembed-blog#38_

**Comment by frenchbread** [comment]
https://github.com/apinf/emq-rest-api does not write data into PostgreSQL (even though all credentials and configurations are correct). No error messages are shown either.

**Comment by brylie** [comment]
@frenchbread as mentioned earlier. Please open issues in the EMQ REST API repository, so we can track and fix the problems you encounter.

**Comment by frenchbread** [comment]
Also I've created two data tables for `mqtt_user` and `mqtt_acl` as in the docs: https://github.com/emqtt/emq-auth-pgsql

**Comment by brylie** [comment]
@frenchbread make sure to set the `connection` adapter to *postgres* in [/config/models.js](https://github.com/apinf/emq-rest-api/blob/master/config/models.js#L20)

**Comment by frenchbread** [comment]
@brylie Updated the `connection` value and it worked! Thanks.

---
After creating new `emq_user`, data tables were created automatically:
![screen shot 2017-02-09 at 16 38 04](https://cloud.githubusercontent.com/assets/2122679/22787782/2730fbf8-eee6-11e6-96b5-fa8233c315ec.png)

And just added `emq_user` itself: 
![screen shot 2017-02-09 at 16 41 31](https://cloud.githubusercontent.com/assets/2122679/22787921/a2a8c2a2-eee6-11e6-8607-31547b90701b.png)

**Comment by brylie** [comment]
Alright great! Now, we need to continue with the other tests. See the checkboxes in the definition of done.

cc: @bajiat

**Comment by frenchbread** [comment]
Faced an issue while trying to authenticate admin user via POSTMAN - https://github.com/apinf/emq-rest-api/issues/3

**Comment by frenchbread** [comment]
Modified schema & tested adding ACLs to EMQ postgres DB via `emq-rest-api`

Next, would need to modify `emq-user` schema. Since currently it's quite generic & need to make to fit EMQ

**Comment by brylie** [comment]
Specifically, what fields do you need to add/remove? Where is the reference schema/documentation?

**Comment by brylie** [comment]
The initial schema was designed to follow these instructions:

- EMQ Auth pgsql: [auth table](https://github.com/emqtt/emq-auth-pgsql#auth-table)
- EMQ Auth pgsql: [acl table](https://github.com/emqtt/emq-auth-pgsql#acl-table)

**Comment by frenchbread** [comment]
Related PR: https://github.com/Digipalvelutehdas/emq-rest-api/pull/4
Related Issue: https://github.com/apinf/emq-rest-api/issues/2
