### ISSUE TITLE
API names in Select API menu need to be sorted alphabetically

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2006]
_From @bajiat on February 2, 2017 12:41_

Related to #338

In the current dashboard, the Select API list on the dashboard shows the APIs in an order that seems random from the user point of view. If you own a lot of APIs or you are an admin, it can be difficult to find the relevant API.

Sort the list alphabetically according to current database default.

Locale appropriate sorting to be solved as an enhancement later, unless it is easy to find the solution.

_Copied from original issue: apinf/meteor-oembed-blog#37_

**Comment by marla-singer** [comment]
@bajiat Interested

**Comment by bajiat** [comment]
@marla-singer Can you please estimate the task?
