### ISSUE TITLE
Avoid use root user in Docker image

### ISSUE THREAD

**Issue by shaliko** [apinf/platform#2008]
Image apinf/platform runs as the root user which might not be permitted by your cluster administrator.

![openshift_web_console](https://cloud.githubusercontent.com/assets/36139/22588924/f1959ca0-ea18-11e6-9d4e-3c75c452348d.jpg)

Probably need start from update base Docker image "jshimko/meteor-launchpad", can be the easiest way.

**Comment by shaliko** [comment]
Just upgrade base image "jshimko/meteor-launchpad" not fixed issue.

**Comment by shaliko** [comment]
Created an issue in "jshimko/meteor-launchpad" repo
https://github.com/jshimko/meteor-launchpad/issues/34

**Comment by bajiat** [comment]
@shaliko I may have accidentally deleted your description of the issue. Sorry for that.

**Comment by shaliko** [comment]
We can close that issue, here was found some fix that we can use for openshift/kubernetis deployment https://github.com/jshimko/meteor-launchpad/issues/34
