### ISSUE TITLE
API profile: Proxy backend tab doesn't have completed translation

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2011]
![joxi_screenshot_1486123683725](https://cloud.githubusercontent.com/assets/20643403/22590887/9c98c862-ea22-11e6-9a9d-2be710a712ed.png)

![joxi_screenshot_1486123554801](https://cloud.githubusercontent.com/assets/20643403/22590868/7bb9bfa2-ea22-11e6-8b63-8e44aa3f2c5a.png)

**Comment by bajiat** [comment]
@marla-singer Are the strings included in the English i18n file?

**Comment by marla-singer** [comment]
@bajiat Checked it. Nope, they are not

**Comment by marla-singer** [comment]
![joxi_screenshot_1486123683725](https://cloud.githubusercontent.com/assets/20643403/22590887/9c98c862-ea22-11e6-9a9d-2be710a712ed.png)
In process of work, I detected that fixing of specified phrase is too complex. I asked an advice to @brylie.We decided to remove the first option `(Select one proxy)` from dropdown list mentioning that it is just a 'placeholder' text, rather than an option. 

Now when the proxies are two and more and user click on Proxy tab, there will be shown an empty form and will be selected the first proxy in list.

@bajiat Do you not mind to remove placeholder `(Select one proxy)` from dropdown list?

**Comment by bajiat** [comment]
@marla-singer Go ahead and remove

**Comment by marla-singer** [comment]
@bajiat I suggest deleting all placeholder texts if a value from the list is required. For example, adding feedback. The message type is required then value`(Select one)` can be removed.
![joxi_screenshot_1487431173909 1](https://cloud.githubusercontent.com/assets/20643403/23094306/75e17084-f607-11e6-9f16-0ff0ac74ced0.png)

The other hand, the lifecycle status is optional then value `(Select status)` must be
![joxi_screenshot_1487431173909](https://cloud.githubusercontent.com/assets/20643403/23094319/9531a01c-f607-11e6-9599-9fabe5479c44.png)

Anyway, Interested
