### ISSUE TITLE
API catalog: Tooltip title "Avarage rating" doesn't have translation

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2012]
![2017-02-03 15 09 15](https://cloud.githubusercontent.com/assets/20643403/22590945/06ae472c-ea23-11e6-9500-d885ac41ae5f.png)

**Comment by bajiat** [comment]
@marla-singer Is the string included in the English i18n file?

**Comment by marla-singer** [comment]
@bajiat Checked it. Nope, they are not
