### ISSUE TITLE
API profile: SDK generate modal form doesn't have the translation

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2014]
Verified on nightly.apinf.io
API profile -> Documantation tab -> SDK generate button
![joxi_screenshot_1486124252582](https://cloud.githubusercontent.com/assets/20643403/22591140/00d7ca2a-ea24-11e6-8a35-a17d657df1c8.png)

**Comment by bajiat** [comment]
@marla-singer Are the srings included in the English i18n file?

**Comment by marla-singer** [comment]
@bajiat Checked it. Nope, the are not
