### ISSUE TITLE
API profile: Feedback form doesn't have the translation

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2016]
1. API profile -> Feedback tab -> Send feedback button

![joxi_screenshot_1486124408880](https://cloud.githubusercontent.com/assets/20643403/22591198/561f7a28-ea24-11e6-91de-8de4f72946da.png)

List from **Choose message type** should also have the translation
![2017-02-03 15 20 23](https://cloud.githubusercontent.com/assets/20643403/22591238/8763c2b0-ea24-11e6-9930-08838c44c156.png)

2. Feedback message type doesn't have the translation as well
![joxi_screenshot_1486124622276](https://cloud.githubusercontent.com/assets/20643403/22591278/c6a905d4-ea24-11e6-857b-71fbd5aa30dd.png)

I'm not sure about the second point. Ping @bajiat

**Comment by bajiat** [comment]
@marla-singer Not sure what I was supposed to comment

**Comment by marla-singer** [comment]
@bajiat Is it okay that Freed back type will be on English? Or should it have a translation as well?
![joxi_screenshot_1486124622276](https://cloud.githubusercontent.com/assets/20643403/22591278/c6a905d4-ea24-11e6-857b-71fbd5aa30dd.png)
