### ISSUE TITLE
Dashboard: Fix tooltip width and height.

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2017]
# Issue:

Right now, tooltips on Dashboard doesn't have a standard height and width. It is too long in height. For this reason, when a tooltip appears, horizontal scrollbar appears on browser screen.

![image](https://cloud.githubusercontent.com/assets/17976243/22591312/a1a47a8c-ea1c-11e6-81c1-595d3a94a4a2.png)

**Comment by kyyberi** [comment]
The tooltip box should "open/grow" inwards. Possibly be just slightly transparent (10%) to bring lightness in the UX.
