### ISSUE TITLE
Frontpage: Add a block indicating how to Add an API

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2019]
# User Story
An API owner coming to APInf for the 1st time might wish to know how to add his API quickly to APInf.
It would be great to show the steps via static image or recorded videos.

> "As an API Owner, I want to know how to add an API to APinf with quick and simple instructions."

# Requirement
* [ ] Position a place holder in "Are you an API owner" section with static images (blocks) giving instructions on how to add an API.
* [ ] A link to Add API page.

**Open question**: Can we use videos uploaded at Youtube to show this?

**Comment by kyyberi** [comment]
Make the barrier minimal by stating something like "Adding your API takes less than a minute"
