### ISSUE TITLE
Write unit test(s) to ensure API Umbrella user is created when Apinf user signs up

### ISSUE THREAD

**Issue by brylie** [apinf/platform#202]
When Apinf users sign up, we are
1.  creating a corresponding user on API Umbrella
2. getting a returned user object
3. creating an ApiUmbrellaUser in Apinf
4. connecting the users via an ID field.

This process happens in [accounts.coffee#52-72](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/accounts.coffee#L52-L72)

Definition of done
- [ ] Write unit tests to cover each step in the above process.
- [ ] Run the tests to demonstrate success of the feature

**Comment by bajiat** [comment]
@mauriciovieira This could be an interesting case for integration test. Could you consider working on this after first unit test?

**Comment by mauriciovieira** [comment]
@bajiat yes. this would be a case for full end-to-end test using docker. Related (#2417)

**Comment by Nazarah** [comment]
If we have to replace API Umbrella with proxy 42 at some point, then the idea and associated works would be obsolete. Closing this.
