### ISSUE TITLE
Frontpage: Icons at "Are you an API Owner" should be able to navigate users to blogs with detailed information

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2020]
# User Story
Right now, icons at "Are you an API Owner" section only give brief information. There is hardly any way to know more information for a new API owner about APInf features other than browsing APInf. It would be prudent if there were clickable links (when applicable) that redirect user to apinf.org blogs (or any other blogs), where users may found out detailed information about APInf via related blogposts.
> "As an API Owner, I want to know in details what features I can use to perform different tasks in APInf"

(related to #2019)

# Requirements:
[ ] From Branding menu, there should be option to give block URLs giving details about API publishing, Api Management, API tracking etc.
[ ] When URL is available, "Are you an API Owner" section should show "Read more" clickable links (where applicable) below icon and brief texts. Clicking on the link would redirect the users to specific blog posts.

**Open Question** : Should we resize the icons and texts so that there is accommodating space to show tutorial/blocks about Adding an API in "Are you an API Owner" section?

**Comment by nnn** [comment]
Related https://github.com/apinf/apinf.github.io/issues/14
