### ISSUE TITLE
Frontpage: Add a block indicating how to use an API

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2021]
# User Story
An API consumer coming to APInf for the 1st time might wish to know how to call existing APIs hosted in APInf
It would be great to show the steps via static image or recorded videos.

> "As an API Consumer, I want to know how to make call to an API in APInf with quick and simple instructions."

# Requirement
* [ ] Position a place holder in "Are you an API User" section with static images (blocks) giving instructions on how to add an API.

**Open question**: Can we use videos uploaded at Youtube to show this?

**Comment by kyyberi** [comment]
IMHO simple video in Youtube could be embedded. Create APInf 101 video list in youtube in which we create 1-3 minute clips about features.
