### ISSUE TITLE
Swedish translations for UI texts

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2026]
We need to have swedish translations for the UI if we intend this to be part of national solution for public sector in Finland.

**Comment by Nazarah** [comment]
Interested

**Comment by kyyberi** [comment]
Do we know people with fluent Swedish skills? :) I know one but he's pretty occupied with other stuff.

**Comment by kyyberi** [comment]
I can do a few translation myself, but the longer texts are out of my skillset.

**Comment by kyyberi** [comment]
Did a few low hanging fruit translations to OneSky

**Comment by ilarimikkonen** [comment]
unless there is a clear business case, no
