### ISSUE TITLE
Wireframe for "Allow swagger URL and not just swagger file"

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2027]
#1993

**Comment by Nazarah** [comment]
wireframes are uploaded in the issue #1993

**Comment by bajiat** [comment]
@Nazarah Please also keep the option to add a link to external documentation, which is not Swagger. The two options mentioned in the issue only relate to content shown in the Swagger UI. The API owner might also have non-Swagger documentation on a web page.

**Comment by bajiat** [comment]
Based on a discussion with @Nazarah, we decided that the link field could be used both for Swagger link and link to any other external documentation. If the link points to a Swagger file, it is shown in the Swagger UI. If the URL points to any other resource, it is displayed as a link in the external documentation section.
