### ISSUE TITLE
Customer journey for API owner

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2029]

**Comment by Nazarah** [comment]
A good template to use here is this:
http://files.thisisservicedesignthinking.com/tisdt_cujoca.pdf
It is free to use

**Comment by Nazarah** [comment]
Cards made on the previous day's discussion is placed in the following trello board:
https://trello.com/b/ElD941vf

**Comment by philippeluickx** [comment]
@Nazarah board not found... is it public or do I need access somehow?

**Comment by bajiat** [comment]
@philippeluickx: @Nazarah will take a look at the problem

**Comment by philippeluickx** [comment]
Started first with the customer journey of the API user (simpler) - first draft in the docs in SVG format, definitely not complete yet. Comments are welcome! https://github.com/apinf/docs/blob/965db11cc0930747bead2ebf8cc1d3adbea6a6c4/docs/UX/customer_journey.svg

**Comment by philippeluickx** [comment]
Updated the first customer journey.

**Comment by kyyberi** [comment]
Lets have a chat about this @philippeluickx

**Comment by bajiat** [comment]
Customer journey task not relevant in this board. Closing the issue in Github.
