### ISSUE TITLE
API names in Connect API to Organization dropmenu needs ordering

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2033]
_From @Nazarah on February 1, 2017 7:48_

# Issue

Right now, the APIs in the Connect API to Organization appears randomly. It is not understandable whether they appear as date created. They are not alphabetically sorted either.
![image](https://cloud.githubusercontent.com/assets/17976243/22498920/04833914-e864-11e6-9d1d-959e39592d3f.png)

# Possible Solution

Showing the APIs appearing in alphabetically ascending order would be the quickest possible solution. this would even prevent the confusion of showing APIs as date created (earliest or latest).

_Copied from original issue: Digipalvelutehdas/APIKA#338_

**Comment by bajiat** [comment]
Related to #37

**Comment by bajiat** [comment]
@marla-singer Could you take this as well, since it is related to #37. Please estimate, if interested.

**Comment by bajiat** [comment]
_From @marla-singer on February 6, 2017 8:14_

@bajiat Yes, I will. The tasks are not related but I can take both.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https:/nightly.apinf.io v 0.40.0 and it is not reproducible.
