### ISSUE TITLE
Allow API owner to add oembed content for an API

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2035]
_From @bajiat on December 13, 2016 12:3_

Related to #16

Todo
* [ ] permissions
* [ ] related media (show/hide)

# Definition of done

* [ ] API owner can find a button or similar to add content to API profile.
* [ ] Pressing the button opens a form or modal to add the necessary fields (e.g. link, title, description) for the content
* [ ] The content of the form is stored in a collection.
* [ ] When there is no content, only the owner sees the panel with the button that allows to add the oembed content. (In other words, hide the block if there is not content and user is not manager of current API or admin.)
* [ ] Only the API owner can delete and edit each oembed object.

Open issue: attribution information (added by and/or original author)

# Wireframe

1. On API Profile detail page, a button for adding Oembd content will appear on the Oembd Pane.
![oembdadd](https://cloud.githubusercontent.com/assets/17976243/21813852/34c45848-d760-11e6-9435-d890d8ebea0c.png)
![oembdadd](https://cloud.githubusercontent.com/assets/17976243/21960090/142676dc-dae6-11e6-92e3-0bf3bb422034.png)

2. On clicking the button, a dialogue would appear with necessary fields to add a new Oembd contents.
Fields included: Name, URL, Description, Preview checkbox (checking this would show in which platform the original content is added. e.g. Youtube, Twitter, Wordpress, etc.
![oembdadddom](https://cloud.githubusercontent.com/assets/17976243/21813897/53a49f20-d760-11e6-81b7-d6a96ce9c699.png)

_Copied from original issue: Digipalvelutehdas/APIKA#127_

**Comment by bajiat** [comment]
_From @Nazarah on January 3, 2017 6:23_

@bajiat @brylie : I created low fidelity design as part of issue #83, and there I also included the design idea of adding oembd content. I am adding those wireframes here. The wireframes are based on card components of bootstrap:
https://v4-alpha.getbootstrap.com/components/card/
when you finalize the design, I can make high fidelity wireframes and post them there.

**Comment by bajiat** [comment]
_From @Nazarah on January 9, 2017 7:48_

Alternate design suggestions
Designed this feature as part of issue #83, so adding the associated wireframes with this.
1. The Add oembd feature appears as a card in the API profile view.
Below that cards appear a group of added contents with their previews
![apiprofile1](https://cloud.githubusercontent.com/assets/17976243/21600957/b6d28866-d18c-11e6-90f9-7fbe2cc6d862.png)

![mockup_2](https://cloud.githubusercontent.com/assets/17976243/21600972/e58cade4-d18c-11e6-9c69-da9b888d66db.png)


2. On clicking Add button, a dialogue/form would appear on foreground to add a new content.
![mockup](https://cloud.githubusercontent.com/assets/17976243/21600903/f4374378-d18b-11e6-9585-01f9aa0aed51.png)

3. On clicking Add, the newly added content appears as a card on the top of the oembd content card groups. In Addition to the given information in the add form, the card also shows who added the content and what time the content was added.

**Comment by bajiat** [comment]
"Add an oembd content" should be renamed to be less technical. If you want, you can add a text that explains user that this adds embedded content that user can click and view in the original source. Give examples of content types (blog posts, videos, presentations)

**Comment by bajiat** [comment]
_From @Nazarah on January 10, 2017 16:14_

@bajiat added the suggested changes to wireframes. Please have a look and verify

**Comment by bajiat** [comment]
@Nazarah The changes are looking ok to me. Just one thing to nitpick about: the title of the section "Embedded Contents". In this meaning, the word "content" is an incountable. So keep also the title of section in singular: "Embedded Content"

**Comment by bajiat** [comment]
_From @Nazarah on January 15, 2017 3:49_

Sorry for missing the text modification while creating the wireframe. Added the changes and uploaded the wireframe. Closing the issue #145

**Comment by bajiat** [comment]
_From @snittoor on February 6, 2017 3:24_

@bajiat : interested in this.

**Comment by bajiat** [comment]
_From @Nazarah on February 6, 2017 8:18_

I will need to add an extra wireframe for the case when API owner has not yet added any Oembed content.

**Comment by bajiat** [comment]
@matleppa @jawidahmadi To be assigned to you.

**Comment by jawidahmadi** [comment]
@brylie  ready for review.
