### ISSUE TITLE
Use API Umbrella Admin API to get Dashboard Analytics

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2036]
_From @brylie on December 12, 2016 13:30_

# Context
We currently get API Umbrella analytics directly from Elasticsearch via its public HTTP API.

![apinf-dashboardelasticdata-methods](https://cloud.githubusercontent.com/assets/17307/22692507/16aca830-ed48-11e6-9ceb-b26bb70d2cbf.png)

[API Umbrella 0.14](https://github.com/NREL/api-umbrella/milestone/10) is planned to disable the public HTTP interface for Elasticsearch by default. This is a [security enhancement](https://github.com/NREL/api-umbrella/issues/287).

# Task
We need to start fetching Dashboard analytics directly from the API Umbrella Admin API. There is a 'drilldown analytics' endpoint that takes several parametrs:

![screenshot_20161212_152802](https://cloud.githubusercontent.com/assets/17307/21101002/9eff06c4-c07f-11e6-8155-c6c198e259af.png)

## Integration code
In order to support the `analytics` endpoint, we need to either
- modify our Meteor API Umbrella package to include a GET method for the analytics endpoint
- determine a different approach to API Umbrella integration altogether
  - we have suggested an [easier approach to integration](https://github.com/NREL/api-umbrella/issues/211) in an upstream issue

_Copied from original issue: Digipalvelutehdas/APIKA#121_

**Comment by bajiat** [comment]
_From @shaliko on December 16, 2016 14:35_

After implement that feature we will not need direct connect from Platform to ElasticSearch and can update docker-compose file. At lease drop 2 lines https://github.com/apinf/platform/blob/develop/docker-compose.yml#L14-L15

**Comment by bajiat** [comment]
_From @Nazarah on December 19, 2016 4:0_

Will this have any impacts on UI in current APInf?

**Comment by bajiat** [comment]
@Nazarah It should not make any difference. It affects the server methods for fetching data. Potential impact: removing ElasticSearch from Proxies in settings menu. If something is not available through admin API, that could affect charts and filtering. The current assumption is that the same data would be available.

**Comment by bajiat** [comment]
@brylie First step is to list what needs to be changed.

**Comment by brylie** [comment]
@bajiat OK, I am auditing the code now.

**Comment by brylie** [comment]
Closing this issue, since we will likely continue to use Elasticsearch directly for Analytics data.
