### ISSUE TITLE
Filter APIs by Lifecycle status, 'Clear all' button not available in results view

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2037]
_From @saralavanip on January 24, 2017 10:35_

# Steps  
1. Visit https://staging.apinf.io (version 0.39.0)   
2. Login as admin/owner   
3. Add APIs  with Lifecycle status (eg. Testing)
3. Click on 'APIs' 
4. Bookmark any APIs  
5. Filter APIs by Lifecycle status clicking on 'filter' icon 
5. Select an option (eg. 'Testing') from drop down menu

# Findings  
-  Filter APIs by Lifecycle status is successful and they are listed as expected. 
-  'Clear all' button not available in this view 
-  If user clicks on  'My APIs' or My Bookmarks without clearing the above results ,it displays empty page. 

# Screenshot    
![no_clearall_button_api_filter_results_view](https://cloud.githubusercontent.com/assets/13309358/22243631/d9fcd242-e230-11e6-87c4-2b6c7b95457b.PNG)

_Copied from original issue: Digipalvelutehdas/APIKA#284_

**Comment by bajiat** [comment]
> If user clicks on 'My APIs' or My Bookmarks without clearing the above results ,it displays empty page.

This is not a bug. The filter should persist if it has not been cleared. You can find the Clear button by pressing the filter button again.

However, this is not consistent with the Organization page that has a Clear all button.

I would suggest removing the text about filtering and the Clear all button from Organization profile to keep the pages consistent. Any comments from @Nazarah or @apinf/developers ?

**Comment by bajiat** [comment]
Suggestion from planning meeting: 
* [ ] Remove the text about filtering from Organization page
* [ ] Remove Clear all button from Organization page
* [ ] Set the filter button to active on both API Catalog page and on Organization page, when user has selected a filter.

**Comment by Nazarah** [comment]
Wireframes based on the requirements:
When a filtering is applied in organization profile/ API catalog, the filtering button gets highlighted.
This indicates that a filtering has been used to show results.
![filteringorganization](https://cloud.githubusercontent.com/assets/17976243/22686585/4d145ac8-ed2d-11e6-9f2e-398a39feafc1.png)

![filteringapicatalog](https://cloud.githubusercontent.com/assets/17976243/22686597/599d376a-ed2d-11e6-913f-d39593a0fba3.png)

@bajiat however, I'd still be favoring to show the filtering criteria text and a clear button in the front view.
User in this way doesn't need to have more than one click to open the filter menu know how the result is being filtered and how to clear up the result. This would be good in the long run when organization/API have multiple criteria to be used for filtering.
The simple solution could be also used to in API catalog by just lowering the set of API cards below than their current position.
