### ISSUE TITLE
Add eslint check to travis build

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2045]
_From @mauriciovieira on January 15, 2017 13:50_

Currently, there is no static code check in the [continuous integration](https://travis-ci.org/Digipalvelutehdas/APIKA). It is desirable to add a eslint check during pull requests because that will help avoiding the introduction of new bugs.

# Definition of done
* [x] Add eslint check to continuous integration (#237)
* [ ] Make eslint to check all directories
  * [x] about (#237)
  * [x] api_catalog (#237)
  * [x] api_keys (#237)
  * [x] apis
    * [x] apis/client (#282)
    * [x] apis/collection (#316)
    * [x] apis/flags (#317)
    * [x] apis/logo (#318)
    * [x] apis/server (#252)
  * [x] apis_authorization (#281)
  * [x] backlog (#341)
  * [x] bookmarks (#350)
  * [x] branding (#351)
  * [x] core (#352)
  * [x] dashboard (#353)
  * [x] docker
  * [x] documentation (#354)
  * [x] elasticsearch (#355)
  * [x] feedback (#2070)
  * [x] feedback_votes (#2070)
  * [x] home (#2082)
  * [x] metadata (#2083)
  * [x] monitoring (#2084)
  * [x] node_modules
  * [x] organization_apis (#260)
  * [x] organizations (#260)
  * [x] proxies (#2103)
  * [x] proxy_backends (#2104)
  * [x] public
  * [x] ratings (#2105)
  * [x] scripts
  * [x] search (#2106)
  * [x] settings (#2108)
  * [x] setup (#2109)
  * [x] status (#2110)
  * [x] users (#2111)

_Copied from original issue: Digipalvelutehdas/APIKA#236_

**Comment by bajiat** [comment]
_From @mauriciovieira on January 15, 2017 13:50_

@bajiat I am working on this. I talked to @brylie Friday and we think it's a good idea.

**Comment by bajiat** [comment]
_From @mauriciovieira on January 15, 2017 15:10_

I am doing this 'locally', and it seems we'll have a long work to do. According to https://travis-ci.org/mauriciovieira/platform/builds/192108795, there are _1656 problems (1358 errors, 298 warnings)_  right after the latest Jan 12th commit (https://github.com/mauriciovieira/platform/commit/0c6b28f7d00ee1eb9328e0341fa829cdd095e827) 

What I propose is to not add all directories in a single step, but one directory at a time, and fix the lints progressively.

**Comment by bajiat** [comment]
_From @mauriciovieira on January 15, 2017 15:12_

And I am pretty sure this step will help us not to introduce new bugs to the code. We already have a https://docs.meteor.com/packages/audit-argument-checks.html added to the eslintrc, and it found a lot of non-checked arguments in the code.

**Comment by bajiat** [comment]
_From @mauriciovieira on January 15, 2017 16:22_

I already set up travis ci to run for pull requests and am fixing one issue at at time in https://github.com/Digipalvelutehdas/APIKA/pull/237. Notice the red x for each commit.

**Comment by bajiat** [comment]
_From @mauriciovieira on January 16, 2017 11:39_

@brylie @bajiat I think it's better not to try to lint all directories at once, in this issue. In my opinion, it is better to merge more often, 1 new PR per directory. 

I am finishing the 3 first directories in alphabetical order, and will open an issue for each unlinted directory.

**Comment by bajiat** [comment]
_From @mauriciovieira on January 16, 2017 11:41_

The work is being done in #237

**Comment by bajiat** [comment]
_From @mauriciovieira on January 18, 2017 11:11_

`apis/server` lint is being worked on #252

**Comment by bajiat** [comment]
_From @mauriciovieira on January 18, 2017 22:47_

https://github.com/Digipalvelutehdas/APIKA/pull/252/commits/74328de51413e0bce410206c8c5cd46d68a6cfd4 is a smarter idea to sort this problem out. 

Every time a developer changes a file, they should just remove it from `.eslintignore` and fix the eslint errors.

@brylie what do you think?

**Comment by bajiat** [comment]
_From @brylie on January 19, 2017 12:12_

@mauriciovieira, I linted the Organizations and Organization APIs modules in PR #260.

**Comment by bajiat** [comment]
_From @mauriciovieira on January 20, 2017 10:49_

@brylie @bajiat I left a message on the 3 open pull requests (#246, #255, #266) , telling how the developers can incorporate the current state of these changes into their branches.

**Comment by bajiat** [comment]
_From @brylie on January 21, 2017 3:48_

Great, thanks!

**Comment by mauriciovieira** [comment]
🎆 🎉 🎉
