### ISSUE TITLE
In Suomi setting, Filtering option in API catalog needs Finnish translations

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2046]
_From @Nazarah on February 1, 2017 7:30_

![image](https://cloud.githubusercontent.com/assets/17976243/22498444/2bab81ac-e861-11e6-9c72-94e22f8f8ff0.png)

![image](https://cloud.githubusercontent.com/assets/17976243/22498472/46154140-e861-11e6-9a06-6a166012ffb3.png)

_Copied from original issue: Digipalvelutehdas/APIKA#337_

**Comment by bajiat** [comment]
_From @marla-singer on February 1, 2017 9:11_

@bajiat Verified it on nightly, it is reproduced as part. 
1. Help text "Filter options" has the translation.
2. Filter form has the translation.
3. Phases doesn't have because of no tags for that

**Comment by marla-singer** [comment]
@bajiat Interested
