### ISSUE TITLE
Align the lifecycle status tag in API profile with the API name

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2049]
_From @Nazarah on January 30, 2017 8:37_

# UI Issue
Right now the lifecycle status doesn't appear aligned with the API name. This is not good aesthetics. 

![image](https://cloud.githubusercontent.com/assets/17976243/22416596/33777182-e6d8-11e6-916e-0efb0e435a2b.png)

# Solution
1. place the tag s.t. API name and the tag are in the same line.
OR
2. if the tag is smaller in height than API name font size, then place the tag mid-aligned with the API name font size.

_Copied from original issue: Digipalvelutehdas/APIKA#319_

**Comment by marla-singer** [comment]
@bajiat It's already resolved. Verified on nightly
![joxi_screenshot_1486711661559](https://cloud.githubusercontent.com/assets/20643403/22817988/a45c2cfc-ef7b-11e6-902a-c593c4e6f291.png)
