### ISSUE TITLE
Registered user able to edit or delete others feedback 

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2051]
_From @saralavanip on January 27, 2017 9:59_

# Steps  
1. Visit https://staging.apinf.io (version 0.39.0) 
2. Login as owner of API 
3. Go to 'APIs' 
4. Select  an API (eg. TestAPI ) 
5. Go to 'Feedback' view
6. Enter details: Topic , Message, Choose message type (eg. error report) 
7. Click on 'Send' button 
8. Logout 
9. Again login as a registered user who do not own any API  
10. Navigate to 'APIs' 
11. Select the same API as in above step 4 (eg. TestAPI ) 
12. Go to 'Feedback' view     

# Expected Result 
Registered users or owners of API are not allowed to edit or delete others feedback report. 

# Actual Result  
- Registered users are able to edit or delete others feedback report (Screenshot 1)   

# Findings
- If registered user chooses message type: 'feature request' and submit feedback, then the edit/delete options are not available. (as shown in screenshot 2)   

# Screenshot  1
![registered_user_edit_delete_feedback_report](https://cloud.githubusercontent.com/assets/13309358/22366937/b35f42f6-e487-11e6-9ea0-1fe89359fe09.PNG)  

# Screenshot 2 
![registered_user_feedback_view](https://cloud.githubusercontent.com/assets/13309358/22366955/c0664706-e487-11e6-9bcc-3d61b47ceb44.PNG)

 

_Copied from original issue: Digipalvelutehdas/APIKA#312_

**Comment by bajiat** [comment]
_From @nnn on February 2, 2017 10:24_

![https staging apinf io apis dyeyhzg2wywcnfwai](https://cloud.githubusercontent.com/assets/7489044/22545694/66196a52-e942-11e6-861b-675ac53f668b.png)

@saralavanip not able to reproduce it on Staging, please confirm.

**Comment by nnn** [comment]
Confirmed with @saralavanip
