### ISSUE TITLE
Title and page title should be the same

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2054]
_From @kyyberi on January 25, 2017 5:38_

Perhaps it would make more sense to use word "Rajapintaluettelo" (now "Rajapinnat") in the top menu as well since the title in the page is "Rajapintaluettelo". Or visa versa: use Rajapinnat in the menu and in page title as well. 
![kuvakaappaus 2017-01-25 07-36-15](https://cloud.githubusercontent.com/assets/1927158/22279107/313e57d8-e2d1-11e6-9afe-10a43fb119b1.png)

_Copied from original issue: Digipalvelutehdas/APIKA#291_

# Definition of done
* [ ] Change the English string for the following UI texts in en.i18n.json
  * [ ] Page title: *API Catalog*  > *APIs*
  * [ ] Page title: *Organization Catalog* > *Organizations*
* [ ] Translate to Finnish (responsibility of @bajiat)

**Comment by bajiat** [comment]
_From @kyyberi on January 25, 2017 5:39_

Same formatting applies to Organizations view as well.

**Comment by jawidahmadi** [comment]
Ready for review.
