### ISSUE TITLE
Bookmark API, info text remains displayed in Organization profile

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2055]
_From @saralavanip on January 24, 2017 8:47_

# Steps 
1. Visit https://staging.apinf.io (version 0.39.0)   
2. Login as admin   
3. Add Organization 
4. Go to above added organization profile 
6. Click on 'Connect API to organization'
7. Select any API from drop down menu  
8. Click on 'Connect' button  
9. Bookmark the above API added clicking on 'flag' icon  

# Findings 
-  The info text for bookmark or unboomark API remains displayed. 
-  Refresh page doesn't display bookmark info text though.    

# Operating system 
Windows 10  

# Browsers 
1. Internet Explorer 11  
2. Mozilla Firefox v 51.0.1

# Screenshot  
![bookmark_api_info_text](https://cloud.githubusercontent.com/assets/13309358/22240140/5e28c6a2-e222-11e6-96ac-dc01770a8494.PNG)

![unbookmark_info_remains](https://cloud.githubusercontent.com/assets/13309358/22240061/fc7ad896-e221-11e6-8363-dc4b5fff2912.PNG)  

![bookmark_api_info_text_api_cards](https://cloud.githubusercontent.com/assets/13309358/22240051/ef71b714-e221-11e6-984b-83773b2d07a9.PNG)

_Copied from original issue: Digipalvelutehdas/APIKA#283_

**Comment by bajiat** [comment]
The steps are slightly confusing, but the problem is that the bookmark tooltip does not get dismissed when you press anywhere in the UI.

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://staging.apinf.io v 0.40.0 and it is reproducible in both Firefox and IE browsers. 

Screenshot:  

1. Mozilla Firefox  v 51.0.1 
![bookmark_tooltip_firefox](https://cloud.githubusercontent.com/assets/13309358/22776909/2fa573d0-eeba-11e6-8766-0962d5313bf0.PNG)    

2. Internet Explorer 11   
![boomark_unbookmark_ie](https://cloud.githubusercontent.com/assets/13309358/22776980/75e9b89c-eeba-11e6-9ff6-4b2fe9a6d6eb.png)

**Comment by bajiat** [comment]
The issue is not yet closed. I only closed the APIKA issue, because I moved it from APIKA to APInf backlog.

**Comment by bajiat** [comment]
@nnn Would you be interested?

**Comment by nnn** [comment]
@saralavanip does this happen when you try to bookmark API in API Catalogue as well?
I am not able reproduce it in Firefox. Could you please double-check if it is still reproducable?

**Comment by saralavanip** [comment]
@nnn , Yes, this issue is also reproducible while bookmark API in API catalog(grid view) as well , Firefox browser (v 51.0.1)  
Screenshot:   
![bookmark_api_catalog_view_firefox](https://cloud.githubusercontent.com/assets/13309358/23750102/10cad89e-04d4-11e7-95fb-f0cec47c7857.PNG)

**Comment by ilarimikkonen** [comment]
cant repro, closing
