### ISSUE TITLE
Publication permissions for Users publication

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2056]
Ensure that User collection publications are secure.

# Definition of done
* [ ] Users collection publications check for Admin role, when more than one user document is returned
* [ ] If non-sensitive user data is returned from a `Meteor.users` publication, just check that current user is logged in (to avoid publishing user details to anonymous users)
* [ ] Only admin or individual user should have access to individual user document

_From @bajiat on January 19, 2017 9:32_

_Copied from original issue: Digipalvelutehdas/APIKA#259_

**Comment by bajiat** [comment]
@marla-singer @brylie Check if this was already resolved.

**Comment by marla-singer** [comment]
@bajiat What the idea of this issue? It doesn't have description

**Comment by brylie** [comment]
@marla-singer this issue is related to your work with the User Management page. Basically, we want to check any publication related to Meteor users, to see that only Admin users can access 'all user data'. The publication security should match our UI security checks.

**Comment by marla-singer** [comment]
@brylie Could you please create Definition of done?

**Comment by brylie** [comment]
@marla-singer added definition of done. It is not precise, but is generally the direction we want to go.

**Comment by brylie** [comment]
@marla-singer would you please open issues for your observations above? That way we can divide the work as a team, and try to fix them ASAP. :smile:

**Comment by marla-singer** [comment]
@brylie I will create issues for points "Found error", "User accessibility" and about subscripted data on API page, Organization page and Dashboard page. 

>APIs and Organisations catalogue
Apis and Organisations collections have all information about items. But not all are used. Is it really necessary? Can we limit some fields? We can start, for example, from Organisations catalogue.

Is it the relevant task?

>Settings data
meteor_accounts_loginServiceConfiguration collection is available from every page. Document contains field clientID.

Is it the relevant task?

**Comment by brylie** [comment]
> APIs and Organisations catalogue
Apis and Organisations collections have all information about items. But not all are used. Is it really necessary? Can we limit some fields? We can start, for example, from Organisations catalogue.

Lets open that task as a 'cleanup'

**Comment by brylie** [comment]
> Settings data
meteor_accounts_loginServiceConfiguration collection is available from every page. Document contains field clientID.

That might just be a side effect of how Meteor Accounts works. Probably not a big deal.

**Comment by bajiat** [comment]
@marla-singer Thanks for opening the issues based on your research?

Can I close this original issue or is there any work required for checking the Users publication permissions still? I'm not sure, if they can be checked from UI, but maybe @brylie could comment that.

**Comment by brylie** [comment]
> is there any work required for checking the Users publication permissions still?

I double checked this project and our meteor-accounts-bootstrap-3 module. [The only publication I could find that publishes all users](https://github.com/apinf/platform/blob/develop/users/collection/server/publications.js#L8-L9) seems secure enough, since It only publishes the `username` field. Should we check for Admin role inside of the `all UsersUsernamesOnly` publication?

**Comment by marla-singer** [comment]
@brylie Nope. Username needs for API catalog to display username in card

**Comment by brylie** [comment]
OK, we can close this issue then, it seems.

cc: @bajiat
