### ISSUE TITLE
Don't show icons on organization profile for contacts

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2057]
_From @marla-singer on January 10, 2017 12:39_

Now contacts of manager are no required fields. If there are empty then icons in organization header can confused users.

### Examples
**Good**
![joxi_screenshot_1484051773112](https://cloud.githubusercontent.com/assets/20643403/21806479/8c6e5bae-d74a-11e6-9511-74c6dc302df3.png)
**Not very good**
![joxi_screenshot_1484051849606 2](https://cloud.githubusercontent.com/assets/20643403/21806505/bbac144c-d74a-11e6-817d-9c70b436ee60.png)
![joxi_screenshot_1484051849606 1](https://cloud.githubusercontent.com/assets/20643403/21806507/bd8085be-d74a-11e6-8e45-45bcac15c68e.png)
![joxi_screenshot_1484051849606](https://cloud.githubusercontent.com/assets/20643403/21806511/bf0d371a-d74a-11e6-951b-831b9c67c5f6.png)

### Suggestion
- Show icons if situation so requires
![joxi_screenshot_1484051917775 1](https://cloud.githubusercontent.com/assets/20643403/21806534/e404ffbc-d74a-11e6-8de1-6021af295858.png)
![joxi_screenshot_1484051917775](https://cloud.githubusercontent.com/assets/20643403/21806539/e5f252b6-d74a-11e6-925c-19e2ae5e694c.png)

_Copied from original issue: Digipalvelutehdas/APIKA#215_

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on nightly and it is not reproducible.
