### ISSUE TITLE
API cards with "added a few seconds ago" are confusing

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2065]
_From @bajiat on December 21, 2016 12:47_

APIs that have either been migrated or synced from API Umbrella have the text "added a few seconds ago" in API cards and in search results instead of the original time when these APIs were added. This is probably because Umbrella does not store information about the date and time when an API was added.

This "added a few seconds ago" text never changes/updates. 

Proposal: Don't display the "Created -- ago" if we have no record of actual date/time added in the document object

<img width="218" alt="added a few seconds ago" src="https://cloud.githubusercontent.com/assets/11626388/21390431/a7621c7c-c78f-11e6-914f-da0f80d0a25a.png">

_Copied from original issue: Digipalvelutehdas/APIKA#177_

**Comment by snittoor** [comment]
@bajiat :  I could not reproduce the data locally.

**Comment by marla-singer** [comment]
@bajiat
