### ISSUE TITLE
APInf in DIY home automation

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2067]
As a DIY home automation developer I would like to use APInf to manage APIs in my local network. Some of the APIs might have public interface, but mostly they work only in local network. DIY home automation is preferred to be build from open source components and that fits us perfectly. 

One option is to use RaspberryPi3 as hardware. There are many development boards that could be used here. 

Just getting API management up and running is not enough though. To actually make it convincing use case, we need to add at least one device with API to the management. What that could be? Most simple thing might be lights control related. There are IoT light bulbs for example.

**Comment by kyyberi** [comment]
Alright. First step is to get APInf in RPI3. Then lets see the use case for demo. Anyway, the result should be a nice story where API management is not the core issue. The application on top of API management should be either funny or useful.

**Comment by kyyberi** [comment]
Application idea: sensor to monitor if mail box (200 meters away and outside) has new mail. Notify me in facebook chat if mail arrives.

**Comment by kyyberi** [comment]
Suggested start is: 
1. install Meteor (https://meteor.com)
2. make sure Git is installed
3. clone our apinf/platform repository (https://github.com/apinf/platform)
4. cd into the cloned directory
5. type `meteor npm install && meteor

**Comment by kyyberi** [comment]
pi@raspberrypi:~ $ sudo apt-get install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version.
git set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ curl https://install.meteor.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7786    0  7786    0     0   3796      0 --:--:--  0:00:02 --:--:--  3798
Unusable architecture: armv7l
Meteor only supports i686 and x86_64 for now.
pi@raspberrypi:~ $

**Comment by kyyberi** [comment]
https://meteor-universal.tumblr.com/

**Comment by kyyberi** [comment]
git clone --depth 1 https://github.com/4commerce-technologies-AG/meteor.git
meteor/meteor --version

It just hangs after downloading some packages

**Comment by kyyberi** [comment]
looks like it is not as straight forward as it might sound at first

**Comment by kyyberi** [comment]
pi@raspberrypi:~ $ meteor/meteor --version
meteor: updating npm dependencies -- meteor-deque...
modules-runtime: updating npm dependencies -- install...
modules: updating npm dependencies -- reify...
promise: updating npm dependencies -- meteor-promise, promise...
ecmascript-runtime: updating npm dependencies -- meteor-ecmascript-runtime...
babel-compiler: updating npm dependencies -- meteor-babel...
babel-runtime: updating npm dependencies -- regenerator-runtime,
meteor-babel-helpers...
ddp-client: updating npm dependencies -- faye-websocket, lolex,
permessage-deflate...
npm-mongo: updating npm dependencies -- mongodb...
logging: updating npm dependencies -- cli-color...
xmlbuilder: updating npm dependencies -- xmlbuilder...
Unreleased, running from a checkout at ffdadac (grafted, HEAD,
origin/release-1.3.4.1-universal, origin/HEAD, release-1.3.4.1-universal)

**Comment by kyyberi** [comment]
pi@raspberrypi:~/platform $ git clone https://github.com/apinf/platform.git
cd platform
pi@raspberrypi:~/platform $ ../meteor/meteor npm install && meteor
.... installs a lot...
> bcrypt@0.8.7 install /home/pi/platform/node_modules/bcrypt
> node-gyp rebuild

**Comment by kyyberi** [comment]
pi@raspberrypi:~/platform $ ../meteor/meteor

**Comment by kyyberi** [comment]
Do we need to make ARM version distribution? Perhaps fork the main repo to platform-arm...

**Comment by kyyberi** [comment]
If so, maintenance gets a bit trickier

**Comment by shaliko** [comment]
@kyyberi if you don't have target develop on Raspberry PI, I can assist you for try run Platform as docker image on Raspberry PI. You will no need source code, git and other dependencies, just docker and docker-compose.

**Comment by brylie** [comment]
@kyyberi and @shaliko I will create two issues, based on this thread:

- enhance/test Docker compose, so our Docker image works on Rasberry Pi (ARM-based micro-development board)
- Release Node.js (de-meteorized) version of Apinf
  - consider how to automate 'node package' when making new releases

**Comment by kyyberi** [comment]
@shaliko that sounds intriguing. Lets wait for @brylie's comment.

**Comment by philippeluickx** [comment]
@kyyberi what version of Nodejs do you have? I've had issues before with having a wrong version.
I suggest to use https://github.com/creationix/nvm so you can manage your Nodejs versions on your pc.

Currently supported version of Nodejs for meteor 1.4 is Nodejs 4 (https://guide.meteor.com/1.4-migration.html)

**Comment by kyyberi** [comment]
In my rest RPI3 I dont have node.js yet.

**Comment by shaliko** [comment]
@kyyberi For Install Node.JS

```
apt-get update && apt-get -qy install curl && \
    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && \
    apt-get update && \
    apt-get -qy install nodejs
```

**Comment by kyyberi** [comment]
thanks. Lets see which way we go. I most likely install node there anyway today.

**Comment by kyyberi** [comment]
Decision has been made that we'll go forward with this track. Has it already been decided should we go with Docker or de-meteorized path? If we push docker in other directions, then that might make more sense as platform point of view.

**Comment by bajiat** [comment]
I would go for Docker, or in fact already asked @shaliko to contribute in #2071, since Docker is used for all installations as our standard package. Let me know if there are strong objections to this.

**Comment by kyyberi** [comment]
+1
