### ISSUE TITLE
Add fullpage width background image in organization view

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2068]
As organization manager I would love to add fullpage width image in the upper part of the organisation view. Now the part is grey color (see attached)
<img width="913" alt="screenshot at helmikuuta 06 13-21-57" src="https://cloud.githubusercontent.com/assets/1927158/22645370/49102a38-ec6f-11e6-8412-830363068039.png">
. This really would make the page look like "ours".

# Goal

Organization manager can add, edit and delete a cover image. The cover image is displayed in the header of the organization page.Respect the aspect ratio of the image. If needed, hide part of the image.

# Definition of done
To be defined by assignee

# Wireframes
1. In Settings tab for Organization profile, the General section contains a  cover photo uploader. It appears with additional help text
![organizationsettings4none](https://cloud.githubusercontent.com/assets/17976243/24240453/5307c2b2-0fba-11e7-9594-2cfa78f8c2ff.png)

2. On selecting a photo to upload, a preview of the photo appears at the Organization profile header.
User can drag the photo to reposition it. 
This is indicated by a text on transparent panel.
Save and Cancel button appears below the picture to save the picture after repositioning or cancel uploading.
While this view appears, logo picture (if any) and Organization information panes (e.g. Name, Description, Link and Contact info, transparent panel to hold the beforementioned information, social media platform, etc.) will disappear. [e.g. repositioning cover photo in facebook]
![organizationsettings4dragcover](https://cloud.githubusercontent.com/assets/17976243/24240479/65c61160-0fba-11e7-8726-d0b940258a95.png)

3. After Save is clicked, the cover picture appears according to the reposition on Organization profile.
Organization information panes (e.g. Name, Description, Link and Contact info) reappear.
![organizationsettings4onlycover](https://cloud.githubusercontent.com/assets/17976243/24240486/7106ef90-0fba-11e7-8243-36e84881c00f.png)

**Comment by Nazarah** [comment]
Are you considering to upload/update header picture from the hheader position itself?
In Facebook profile, we can change/upload our cover picture from that specific place holder.
Also we can drag it up or down to reposition.
Do you want something similar to that?
Or you want this to be configured from the Organization profile settings tab?

**Comment by nnn** [comment]
Interested.

**Comment by Nazarah** [comment]
@nnn can you please give the link of the package that you proposed for photo uploading?

**Comment by bajiat** [comment]
Issue related to #2352.
