### ISSUE TITLE
Enhance/test Docker compose to work on Rasberry Pi

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2071]
> As a home-automation developer
I would like to run Apinf on a Rasberry PI (or other micro-development board)
so that I can manage my home-based IoT APIs

# Task
Enhance/test Docker compose, so our Docker image works on Rasberry Pi (ARM-based micro-development board).

# Related issue
- [APInf in DIY home automation](https://github.com/apinf/platform/issues/2067)

**Comment by kyyberi** [comment]
Lets try this. I'll do testing on my RPI3. I just need some help in getting started.

**Comment by shaliko** [comment]
@kyyberi I can try first test today on my raspberry pi in the second part of the day.

**Comment by kyyberi** [comment]
Excellent. Keep us updated :)

**Comment by mauriciovieira** [comment]
:+1:

**Comment by shaliko** [comment]
@brylie Please clarify task.

"I would like to run Apinf" that mean run full task of components (Platform, MongoDB, api-umbrella and still need ElasticSearch) or just Platform?

**Comment by brylie** [comment]
@kyyberi probably means to run the whole stack:

- Apinf + MongoDB
- API Umbrella + Elasticsearch

Basically, he is considering that someone interested in home automation would want a local **API Proxy** and **Management Interface**, so they can manage their local IoT devices from within their home.

@kyyberi any corrections/clarifications?

**Comment by brylie** [comment]
@shaliko also, please contact @bajiat before undertaking any new tasks. We need to think holistically about our current workload and priorities, and @bajiat has a good perspective of our current trajectory.

**Comment by shaliko** [comment]
@brylie OK, today I do just 20 min tests.

**Comment by kyyberi** [comment]
No, @brylie described the need pretty accurately, whole stack.

**Comment by shaliko** [comment]
@brylie @kyyberi @bajiat I was not able start Platform on Raspberry Pi because all our docker images (Platform, MongoDB, API-umbrella) will not work on ARM architecture.

We can solve that issue by create new Docker images for ARM and I am pretty sure that will not have issue with Platform, MongoDB, ElasticSearch but migrate API-umbrella can require some time.

@bajiat Ping me if we need continue contribute to that task.

**Comment by brylie** [comment]
> We can solve that issue by creating new Docker images for ARM, and I am pretty sure that will not have an issue with Platform, MongoDB, ElasticSearch but migrate API-umbrella can require some time.

@shaliko thanks for looking in to this. If desirable, we can open one or more follow up tasks for creating the Docker containers you mention.

CC: @kumargs @bajiat @ccsr

**Comment by shaliko** [comment]
@brylie I can contribute to it if you think it will be useful.

**Comment by bajiat** [comment]
@shaliko Let's see if we could get some community help for this. But you could give an estimate how much time would be required for migration for each of these from you:
* Platform
* MongoDB
* ElasticSearch
* API-umbrella

**Comment by shaliko** [comment]
@bajiat 

- Platform (1 day)
- MongoDB probably just found right image. Like this https://hub.docker.com/r/fpommerening/rpi-mongo/
- ElasticSearch - the same, just found right version of existing docker image.
- API-umbrella - hard to estimates, a lot of software inside of theis docker image.

**Comment by brylie** [comment]
@shaliko we can leave this issue open, with the help wanted label. Are you creating a different issue to track this idea?

**Comment by shaliko** [comment]
@bajiat 

- Platform (1 day)
- MongoDB probably just found the right image. Like this https://hub.docker.com/r/fpommerening/rpi-mongo/
- ElasticSearch - the same, just found right version of existing Docker image.
- API-umbrella - hard to estimates, a lot of software inside of the docker image. We can create small task for couple hours, I will make some tests and then can give more accureate estimation.

And we will need some time for tests whole components together on Raspberry PI. More concern about performance and how it will work after reboot. The host will not have domain name so should be configured with static IP or another aproach.

**Comment by shaliko** [comment]
@brylie Sorry, I accidentally closed it.

**Comment by brylie** [comment]
No worries :smile_cat:

**Comment by kyyberi** [comment]
Excellent. I'll be your test developer when you @shaliko have a little howto documentation for me to use.

**Comment by bajiat** [comment]
@shaliko Based on a prioritization meeting yesterday, we would like you to contribute to this task. #2115 has higher priority, so this is the next task after that.

**Comment by shaliko** [comment]
@bajiat Great, right after #2115 I will start from build Platform ARM docker image, so @kyyberi will able test it with settings on api-umbrella from nightly, then will switch to ARM docker image for api-umbrella.

**Comment by kyyberi** [comment]
related to EPIC #2067

**Comment by shaliko** [comment]
@kyyberi @brylie I started from run MongoDB v 3.x because the thought that it will be the most challenging, but after I successfully start MongoDB v 3.0.9 on raspberry I found that Meteor can't work on armv7l architecture (raspberry pi).

```
Meteor only supports i686 and x86_64 for now.
```

https://github.com/meteor/meteor/issues/442

Currently, we can't start Meteor on the raspberry pi.

**Comment by shaliko** [comment]
Actually I found few instructions how run it, will try apply on our current code base https://crater.io/posts/go5Ne2NBqfb6ALYo3/help-installing-meteor-on-a-raspberry-pi-2

**Comment by brylie** [comment]
Ok, we might just have to build the app for production, as a plain Node.js app.

**Comment by shaliko** [comment]
@brylie Just notice you, that I created new repo on DockerHub for rpi docker image.

https://hub.docker.com/r/apinf/rpi-platform/ - currently for tests, so I not contributed to write description text.

**Comment by shaliko** [comment]
1) [Install Raspbian on Raspberry PI](https://www.raspberrypi.org/downloads/raspbian/) 
2) Install docker and docker-compose:
```
$ curl -sSL get.docker.com | sh
$ sudo systemctl enable docker
$ sudo systemctl start docker
$ sudo apt-get install python-pip
$ sudo pip install docker-compose
$ sudo usermod -aG docker pi
```
3) Create docker-compose.yml file with content: 
```
version: '2'
services:
  apinf:
    image: apinf/rpi-platform:0.40.0
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb/apinf_db
      - ROOT_URL=http://192.168.1.34
      - PORT=8080
    depends_on:
      - mongodb
    ports:
      - "80:8080"
  mongodb:
    restart: always
    image: ftavares/rpi-mongo:3.0.9
    command: bash -c "rm -f /data/db/mongod.lock && chown mongodb:nogroup /data/db && chmod 777 /data/db && mongod"
    volumes:
      - mongodb_data:/data/db
volumes:
    mongodb_data: {}
```

Where "192.168.1.34" is IP of your Raspberry Pi in local network (replace it).

4) Run docker-compose:
```
docker-compose up -d
```
5) Visit in browser URL http://192.168.1.34
6) Configure Proxy (I will share the credentials separately).

Know issues:

- "Wrong URL schema for Swagger UI" https://github.com/apinf/platform/issues/2165
- We need to find a way for reliably freeze IP address in the local network, currently after reboot, Raspberry PI can take new IP address and we will need change docker-compose file.

**Comment by kyyberi** [comment]
For the second item in known issues... so we would need some info from "ifconfig" and then modify /etc/network/interfaces to have static IP (and other needed settings). 

"iface eth0 inet dhcp" -> "iface eth0 inet static"
Then add: 
address [Perhaps just pick one we define, might have conflicts with other devices in same network in some cases]
netmask [your netmask]
network [your destination]
broadcast [your broadcast range]
gateway [your gateway]

**Comment by kyyberi** [comment]
Thanks @shaliko for instructions. I will do the test on Friday evening.

**Comment by kyyberi** [comment]
I was thinking to record the test eg make a video out of it. If the test seems succesfull I'll publish it in Youtube. To make this a little more convincing I would need to come up with a simple example how to should it in action. Perhaps simple API and call it with curl. That might be enough. We have that hello world API which we have used in events. Perhaps that could be used in local network? What do you think?

**Comment by shaliko** [comment]
@kyyberi I think the video will be very good, but without proxy backend API-umbrella and emqttd, it will be useless.

We need finish second part for able show really good demo.

**Comment by kyyberi** [comment]
Agreed. I just tested the setup first. I confirm that all works. Only at the end I had to slightly modify one (last) command. I had to run 
```sudo docker-compose up -d``` 
to get it working. Without sudo it was not able to connect to Docker daemon.

**Comment by kyyberi** [comment]
Perhaps it might be worth checking how we could inject apinf to platforms like https://home-assistant.io/ and showcase the value for doing it. That probably is larger effort which requires time and money.

**Comment by kyyberi** [comment]
I would say that we need to break this issue into separate issues. I call the effort so far a success. We have a way to install Apinf platform to RPI3 in minutes. It's not flawless but it's a good start. 

Next step is to install first proxy under the platform management. I would leave now Umbrella for a moment it if does not go forward with minimal effort. Instead I would go towards emqtt and find a way to get emqtt broker running on RPI3 as easily as apinf platform. In home automation realtime APIs are more often used than REST  APIs (gut feeling). 

Therefore I suggest we close this issue and I'll make at least two issues: 
- how to set static IP for apinf platform on RPI3
- create easy install instructions to get emqtt running on RPI3 (configure with apinf)

When those are done, we can move forward. I know we need to build the analytics view to Apinf for emqtt but that is high priority and going to be developed in parallel with this. 

Opinions?

**Comment by kyyberi** [comment]
Closing this as done. See reasoning above.

**Comment by shaliko** [comment]
@kyyberi Sorry for the long delay with the response missed that notification.

I am OK with pause work on api-umbrella port on ARM architecture. It looks like will be big part of work https://github.com/NREL/api-umbrella/issues/336.
