### ISSUE TITLE
Release node.js 'package' of Apinf software

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2072]
In order to support wide deployment targets, where Meteor.js might not be available, we can provide a 'de-meteorized' version of our platform. De-meteorizing basically means 'compiling' to node.js. That would mean that Apinf could run anywhere node.js can be installed, which is quite a lot of places.

# Related issue
- [APInf in DIY home automation](https://github.com/apinf/platform/issues/2067)

**Comment by kyyberi** [comment]
+1

**Comment by mauriciovieira** [comment]
But what would happen after this? We'd keep both versions, just maintaing the _demeteorized_ version, keep working on the meteor version and run a conversor?

A quick search gave me https://github.com/onmodulus/demeteorizer

**Comment by brylie** [comment]
Perhaps we could take notice of how [Rocket.Chat provides multiple deployment methods](https://github.com/RocketChat/Rocket.Chat#deployment). I.e. we can provide at least a couple of options for deployment, such as:

- Docker
- mup (which uses Docker now)
- demeteorized node.js
- OpenShift (see work in progress by @shaliko)

**Comment by kyyberi** [comment]
Exploring automated toolchain to produce multiple deployments would probably make sense.
