### ISSUE TITLE
Suomi view: user info text untranslated in Organization profile

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2076]
# Steps  
1. Visit https://staging.apinf.io  (version 0.40.0) 
2. Login as admin  
3. Add Organization 
4. Go to above added 'Organization' profile view  
5. Change language to 'Suomi' 

# Findings  
-  User info text 'Organization doesn't have APIs connected' in English language  
-  Similarly organization 'Settings' page is partly untranslated: info text for 'upload logo' , 'Email' is in English language.

# Screenshot  
![untranslated_organization_page](https://cloud.githubusercontent.com/assets/13309358/22686852/8465e7ca-ed2e-11e6-8638-d67d629ac640.PNG)   

![suomi_view_organization_view_untranslated](https://cloud.githubusercontent.com/assets/13309358/22686869/8ea378d8-ed2e-11e6-9a10-518149dfd5c0.PNG)   

![orga_settings_suomi](https://cloud.githubusercontent.com/assets/13309358/22687227/cd818a62-ed2f-11e6-901e-12081459dcdd.PNG)

**Comment by bajiat** [comment]
Verified in nightly, closing as resolved.
