### ISSUE TITLE
Navigate from one organization profile to another flashes info text

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2081]
# Steps  
1. Visit https://staging.apinf.io (version 0.40.0)  
2. Login as admin  
3. Add organizations (eg. organization 1, organization 2)
4. Go to organization catalog 
5. Navigate from one organization profile to another 

# Findings  
 Info text 'No organizations available. Add organization'  is flashed while navigating from one organization profile to another.  

# Browsers  
- Google Chrome Version 55.0.2883.87 (64-bit)  
- Internet Explorer 11 

# Operating system 
Windows 10

**Comment by marla-singer** [comment]
@saralavanip As I understood you told the situation as on screen below?
![2017-02-08 11 23 00](https://cloud.githubusercontent.com/assets/20643403/22728889/4ed91b86-edf1-11e6-975e-d742998ab018.png)

**Comment by saralavanip** [comment]
@marla-singer , Yes exactly, thanks for the screenshot. I tried to upload screencast of this scenario but found that Github doesn't allow  .mp4 file format.
