### ISSUE TITLE
User have to create totally unique proxy base path

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2093]
Now we have the rule that user must create the unique proxy base path. But we need to limit it more. Don't let user create the proxy base path if the first section of this path has is the part of other API

On local, I have three different APIs with the next settings. Bring to your notice that APIs have the different URL. 

![joxi_screenshot_1486625338473 2](https://cloud.githubusercontent.com/assets/20643403/22773384/f673dee6-eeb2-11e6-92e2-cd04b3e7a70b.png)
![joxi_screenshot_1486625338473 3](https://cloud.githubusercontent.com/assets/20643403/22773667/6cccfd42-eeb4-11e6-94cd-2740960b9715.png)
![joxi_screenshot_1486625338473 4](https://cloud.githubusercontent.com/assets/20643403/22773672/7012ed5e-eeb4-11e6-9b11-d6370a9bbcd4.png)

### Found &expected
1.  When I call **` https://nightly.apinf.io:3002/alternative/ `**
it redirects to **` https://music.yandex.ru/genre/alternative/`** that's **correct**
3. When I call **`https://nightly.apinf.io:3002/alternative/artists/ `**
it redirects to **`https://music.yandex.ru/genre/alternative/artists/`** that's **wrong**. 
**Expected:** `http://petstore.swagger.io/test-elastic/`
2. When I call **` https://nightly.apinf.io:3002/alternative/rock/ `**
it redirects to **` https://music.yandex.ru/genre/alternative/rock/`** that's **wrong**. 
**Expected:** `https://learn.javascript.ru/courses/nodejs`

**Comment by brylie** [comment]
We are not committing to resolve this issue right away, but want to get a better understanding of the underlying parts. I have self-assigned and will look for upstream issues or discussions that might give us better understanding.

**Comment by brylie** [comment]
This seems related to the API Umbrella internal **matching order** field:

![screenshot_20170210_122004](https://cloud.githubusercontent.com/assets/17307/22823321/bc960bf2-ef8b-11e6-8f98-6081cfafaad9.png)

The **matching order** field tells API Umbrella in which order to route requests. API Backends with lower matching order value will be routed before higher level routes, when their frontend prefix matches, even when a higher level route may be a more accurate route.

**Comment by brylie** [comment]
In the spirit of this issue title, we might consider 'solving' this challenge by allowing multiple, explicit frontent prefixes per Proxy Backend. This aligns with the design of API Umbrella:

![screenshot_20170210_124709](https://cloud.githubusercontent.com/assets/17307/22824110/306e33bc-ef8f-11e6-8534-e020f70fd7e7.png)

Then we can change our code to *not* use wildcard queries for getting/deleting analytics data, rather relying on the explicit frontend prefix.

**Comment by brylie** [comment]
*Caveat emptor*: this would require that API managers explicitly define *every* desired frontend prefix, rather than allowing for the 'catch all' prefixing that API Umbrella allows.

**Comment by brylie** [comment]
Opened an upstream support request: https://github.com/NREL/api-umbrella/issues/342

**Comment by bajiat** [comment]
@brylie We would need to unblock this issue. Can you get some advice from our developers?

**Comment by bajiat** [comment]
This is becoming even more urgent because of monetization and  new dashboard. Let's resolve this during sprint 51.

**Comment by bajiat** [comment]
@brylie Please invite @matleppa, @marla-singer and @phanimahesh for a meeting to discuss both proxies and our domain model. Should happen 25 - 29 September

**Comment by brylie** [comment]
Invite sent for next Tuesday (2017-09-26).

**Comment by brylie** [comment]
Notes from our meeting with @bajiat, @matleppa, @Nazarah, and @phanimahesh:

Wen resolving this issue, we want to be consistent across the followint APInf features:

- API Catalog namespaces
    - e.g. `/user_or_organization_slug/api_slug/`
- Proxies/brokers
    - API Umbrella frontend prefixes
    - eMQ topic prefixes
- Dashboards
    - API Umbrella dashboard
    - eMQ dashboard

Wireframes will be needed for at least:
- Add API user flow/screen(s)
- Add Proxy Backend user flow/screen(s)
- Namespaced API management screen
    - view of all managed APIs, allowing them to be reordered for proper request resolution

Hypothetical user flow for adding an API
- Ask whether it is a personal or organization API
    - only organization managers will be able to add APIs to their organization, otherwise the option will not be available

Hypothetical user flow for adding Proxy Backend
- While validating form input (specifically the frontend prefix), make sure prefix conforms to uniqueness criteria (to be determined)
- warn user about overlapping frontend prefixes
- help user to manage the **matching order** of APIs they manage
    - either personal or organization APIs
        - possibly grouped by personal or each organization which they manage
    - possibly with different groupings depending on related proxy


Things we would like to allow:

- nested frontend prefixes of arbitrary depth. E.g.
    - /hsl/transit/
    - /hsl/transit/busses/
    - /hsl/busses/realtime/
    - /hsl/busses/schedules/
    - /hsl/transit/trains/
    - /hsl/trains/realtime/
    - /hsl/trains/schedules/
- users may manage APIs for several contexts:
    - personal APIs
    - organization APIs
    - APIs on multiple proxies
- users may even be part of multiple organizations

**Comment by brylie** [comment]
I have summarized our discussion in the above comment, and will need to hand this task off to another champion.

**Comment by preriasusi** [comment]
#2319
