### ISSUE TITLE
Add API page is a bit boring and confusing

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2096]
Adding API to catalog - it's a good idea to make it as easy as possible! However, for example the field URL can be misunderstood and even become (possibly) show-stopper for some API owners. 

URL can be understood as company url, API documentation url, API endpoint....

In addition, this is the first function/page API owner is faced with. It has to be appealing and inspiring! Below is my cheese and feeble scrible about the page. Sorry for the low quality, but It was created while drinking morning coffee. 

![idea](https://cloud.githubusercontent.com/assets/1927158/22815677/92538d90-ef65-11e6-8ea3-c51016bb6959.jpg)

# Requirements:
* [ ] Add inviting texts encouraging new users to add API (e.g. "Simple steps. Takes less than a minute"
* [ ] Renaming fields names to more intuitive ones (e.g. URL -> API Endpoint)
* [ ] Giving less technical and more humane help texts explaining the purpose of each field and what value can be put there.
* [ ] Making Mandatory fields more visible.
* [ ] Using CSS Alert class to highlight unfilled mandatory fields with meaningful alert texts.

# Wireframe
added a low-fi wireframe that was in discussion from this [issue](https://github.com/apinf/platform/issues/1998)
If this works well, Devs and I can think about high fidelity sketches
![addapi](https://user-images.githubusercontent.com/17976243/29406851-05fea1de-834b-11e7-907b-a070ecd72e36.png)

**Comment by kyyberi** [comment]
Perhaps the lifecycle status could be clickable, since dropdown is a bit clumsy to use. 
![screenshot at helmikuuta 10 11-44-02](https://cloud.githubusercontent.com/assets/1927158/22822191/0bc53234-ef87-11e6-983a-a2a09808cfa1.png)

**Comment by Nazarah** [comment]
about making the page interactive, user can be scrolled down at bottom once s/he fills up a field by pressing enter. 
User can always scroll up and down to see fields s/he has filled up or not.
The life cycle statuses can be shown with boot strap tags and with familiar colors. (e.g. blue for design, etc.)

**Comment by bajiat** [comment]
@kyyberi I think the quality is more than enough. We can get the point from the sketch and it does not take too much of time for creating it on paper. 

In general, I like the idea, assuming that it is still just one screen and not going back to the wizard mode. 

If we use clickable labels for lifecycle, we should definitely use the same LAF for labels as elsewhere in the UI (color, size, font)

**Comment by kyyberi** [comment]
Yes, no wizard, just one pager. I agree about the labelling, just did not have time to change colors when drafting.

**Comment by kyyberi** [comment]
@Nazarah lets pick this one as topic for our UX meeting today

**Comment by Nazarah** [comment]
Some requirements this task needs can be seen from this issue:
https://github.com/apinf/platform/issues/2235

**Comment by preriasusi** [comment]
Re-done with next. Closing.
