### ISSUE TITLE
Adding Chatbots to APINF

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2100]
# Context

Old fashioned contact forms might not help users to get instant response. User has to wait for an email from administrator to get back to his question and it is time consuming. For simple tasks like providing contact information or querying abut basic functionalities (e.g. adding an API, making a call to API) can be made interactive and time saving by adding chatbots. This may also work to establish direct communication with developers behind a specific API.

> "As an API consumer, I want to use chatbots, so that I can communicate interactively and get helpful information in a time-saving manner."

# Related link:

* Use of Chatbots with API demostrantion in APIOps: https://www.youtube.com/watch?v=W2XrwoeXtPk&t=643s&list=PL0YyRgsdKp0oko1qGSK_Dk1UzAzVioYJ1&index=3

# Possible places for the use of Chatbots:
1. Collecting contact information (front page)
2. Providing information about how to use APINF throughout the site.
3. establishing direct connection to API manager / developer through slack channels.

**Comment by kyyberi** [comment]
More information https://www.youtube.com/watch?v=HzsTi-kJe30

**Comment by kyyberi** [comment]
See also https://github.com/apinf/apinf-bot/issues

**Comment by philippeluickx** [comment]
http://www.pandorabots.com/

**Comment by philippeluickx** [comment]
We got apibot.ai as a domain. I propose we test this first as a seperate service and we can integrate later on if this proves succesful. Let's not bloat apinf.io at this stage.
