### ISSUE TITLE
Design APInf REST API for Catalog endpoints

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2102]
# Description

**Questions:** 
- Where is the list of existing endpoints?
- What is the used data model? Is it visible somewhere other than inside code? (should be)
- How are operation authentications handled? 
- What are the conventions for error handling? 

**Methods POST:** 
eg. add something new. Returns created data object on success. 

- Add organization
- Add API

Do we put PUT methods to other issue? Those are used normally to update existing object. Using POST for that is breaking the convention used in larger API community. 

**Methods PUT:** 
eg. update existing object (just information to be updated is required, not the whole metadata set)

- update organization
- update API

# User story
# Definition of done
* to be updated with @kyyberi

**Comment by bajiat** [comment]
@brylie Document the datamodel
@kyyberi Create api design and mentor
@matleppa Study how we create the endpoints and participate in design with @kyyberi

**Comment by kyyberi** [comment]
Do we have a folder in repository where we should store design (swagger)?

**Comment by kyyberi** [comment]
Design will be done in Swaggerhub.com and from there I can sync result to given repository folder.

**Comment by kyyberi** [comment]
Working environment https://app.swaggerhub.com/api/kyyberi/APInf-REST-API/MVP @matleppa, create an account to swaggerhub and I'll share the API space to you.

**Comment by kyyberi** [comment]
How do we auth admin users?

**Comment by brylie** [comment]
It uses a token-based authentication very similar to OAuth2, but perhaps not OAuth2.

**Comment by kyyberi** [comment]
good

**Comment by brylie** [comment]
The [Meteor Restivus documentation](https://github.com/kahmali/meteor-restivus#logging-in) has an example of a user logging in. In a nutshell, the user can POST their credentials to the authentication endpoint, and receives an `authToken` in return.

**Comment by kyyberi** [comment]
https://apinf.io/api/TYf33t5B6D6fwamKt

**Comment by kyyberi** [comment]
Could you @jawidahmadi do the review of the design?

**Comment by brylie** [comment]
@jawidahmadi here are a couple of API design guides that can inform our API design:

- Google [Api Design Guide](https://cloud.google.com/apis/design/)
- Zalando [RESTful API guidelines](http://zalando.github.io/restful-api-guidelines/)

**Comment by brylie** [comment]
Specifically, check out the [Zalando API Design Principles](http://zalando.github.io/restful-api-guidelines/design-principles/DesignPrinciples.html#api-design-principles).

**Comment by brylie** [comment]
Re: updating specific fields on a document, without updating the whole document: See the Google [HTTP Standard Methods: Update](https://cloud.google.com/apis/design/standard_methods#update) documentation.

**Comment by kyyberi** [comment]
I would recommend looking at http://apistylebook.com/design/guidelines/ for guidelines instead of pointing out single one or two. Out of curiosity @brylie , what is the reason to raise Zalando as an example?

**Comment by jawidahmadi** [comment]
response code for No Content 204
PUT is Idempotent, consider using it to create
POST is safe, consider using it to update

**Comment by brylie** [comment]
> Out of curiosity @brylie , what is the reason to raise Zalando as an example?

The Zalando API Design Guide seem well considered and organized. The documentation is also [open source on Github](https://github.com/zalando/restful-api-guidelines), so we could contribute back or adapt them to our needs.

**Comment by philippeluickx** [comment]
Getting error in my console when clicking show/hide (Swagger viewer):

35d5778….js?meteor_js_resource=true:21 Uncaught TypeError: Cannot read property 'pushState' of undefined(…)toggleEndpointListForResource @ 35d5778….js?meteor_js_resource=true:21callDocs @ 35d5778….js?meteor_js_resource=true:22dispatch @ 35d5778….js?meteor_js_resource=true:30m.handle @ 35d5778….js?meteor_js_resource=true:30

**Comment by philippeluickx** [comment]
It is not clear to me what "API updates" are (/apis/updates/). Is it just a series of possible parameters? Then it should be in just /apis/?

**Comment by philippeluickx** [comment]
Try out example for /apis/updates/ gives me
`https://apinf.io:3002/kyyberi/APInf-REST-API/1.0.0/apis/updates/?since=7d&id=undefined&limit=undefined&new_apis_only=false&lifecycle=undefined`

- port 3002?
- kyyberi?

**Comment by brylie** [comment]
@philippeluickx, the try out examples are prone to failure, because this API is in the **Design** phase. This means, the endpoints do not yet exist. We are currently seeking feedback on the design itself, rather than testing functionality.

**Comment by philippeluickx** [comment]
PUT /apis/{id} has a question in the description:

> Do we need an indication, which field(s) to update?

Not sure if this is the best approach in a design-phase API?

**Comment by philippeluickx** [comment]
Do we need better instructions for pagination?

**Comment by philippeluickx** [comment]
@kyyberi already touched upon it: how about authentication? What actions you need to have authentication, which ones can you do anonymously?

**Comment by brylie** [comment]
> Getting error in my console when clicking show/hide (Swagger viewer):
>
> ```
> 35d5778….js?meteor_js_resource=true:21
>Uncaught TypeError: Cannot read property 'pushState' of undefined(…)
> toggleEndpointListForResource @ 35d5778….js?meteor_js_resource=true:21
> callDocs @ 35d5778….js?meteor_js_resource=true:22
> dispatch @ 35d5778….js?meteor_js_resource=true:30
> m.handle @ 35d5778….js?meteor_js_resource=true:30
```

That may be related to issue #2211. Please post the error message there.

**Comment by kyyberi** [comment]
@philippeluickx Excellent points above. Could you add your API design related feedback and questions to feedback tab? That is where I assume we actually would like to see feedback. I will not ask them to come to Github and add an issue.

**Comment by philippeluickx** [comment]
@kyyberi Done!
Quick feedback on the feedback process (meta-feedback?):
- Too complex - 3 fields to fill in for a simple feedback?
- Modal - not the right UI (discussion can be found online, but consensus is driving towards not using modals for this purpose)
- Not clear what happens with my feedback. Who gets the feedback, how do I get notified about replies?

**Comment by brylie** [comment]
@philippeluickx can you open a Github issue for your Feedback meta-feedback? That way we can improve the Feedback module as part of a design/development task.

**Comment by kyyberi** [comment]
I heard there was discussion about PUT and POST methods. It is common practice that both can be used to create new object in the system. PUT is valid for creating a resource, but only if the client has the privilege of naming the resource. In our case that is not the case. We identify objects by ID and that is never defined by client. Thus in our API design new items are always created with POST. PUT is used to update existing object.

**Comment by kyyberi** [comment]
Reason to have /apis/updates is that it gives you just updates (delta) about changes. Putting all in one method (/apis/) makes it bloated and hard to understand/communicate.

**Comment by kyyberi** [comment]
Did some improvements to show more clearly, which methods require authentication. Closing this issue and pushing it to external developer review.

**Comment by philippeluickx** [comment]
/apis/updates: So it's kind of a revision history?

**Comment by kyyberi** [comment]
Yeah

**Comment by philippeluickx** [comment]
My suggestion would be to rename it to revisions then. It's more concrete.

**Comment by kyyberi** [comment]
I asked ext developer(s) opinion about the path and they say both is fine, but like original "updates" better.

**Comment by kyyberi** [comment]
Before implementation we might want to check that harvestor data model is synced and supported by POST/PUT methods https://github.com/apinf/api-harvester
