### ISSUE TITLE
Update personas

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2117]
There are currently three personas defined for APInf: one API owner, two developers. Let's take a critical look at the personas, see if we need to re-name (Apitalist and APIOps?) and update or even start from scratch.

**Comment by kyyberi** [comment]
To me as newbie it seams that the focus has been mostly on technical support. API manager doing proxy settings and looking at how well they serve. The other side of the "API manager" role is monetisation and service level etc. That is APItalist. 

So far the other role has been "developer" or consumer. APIOps includes both sides; API consumer and API developer. Both look after automation and that is what APIOps is about - automized and standardised API value chain. We have decided to support APIOps network and use that as our "testing" community. Therefore unifying stories would make us more easily understandable and clear. 

Downside: I admit that terms APItalist and APIOps are new and need pushing and also require time to be better known. However, we are not the only people who push APIOps. That is understood elsewhere too especially by people who know DevOps. APItalist is a different story. Supporting and using the above names could make sense and furthermore differentiate us a little bit more from other API management solutions. 

If nothing else, I would like to have better discussion about the subject with team.  There's times blog post coming from medium/apinf tomorrow about the subject (APItalist and APIOps).

**Comment by kyyberi** [comment]
To me it sounds that we need a story teller. We might become blind to obvious paths. Perhaps we should consider getting some help from partners.

**Comment by Nazarah** [comment]
Interested

**Comment by bajiat** [comment]
@kyyberi I think you are absolutely right about the need to have a persona also for the business person at the API owner side, the Apitalist.

I'm ok with using Apitalist and APIOPS terms for personas, but would like to differentiate between API owners and API consumers in technical side. So I would prefer not using APIOPS for both owner and consumer persona.

**Comment by Nazarah** [comment]
idea: build up a skeleton of personas from the notes in customer journey.
iterate the process as we get more connections with APIOps and APItalists

**Comment by Nazarah** [comment]
# Persona 1

![aleksanteri jokinen](https://cloud.githubusercontent.com/assets/17976243/24036923/71770c86-0b04-11e7-957d-eac7bcbf9b0a.png)

**Name:** Alesanteri jokinen
**Nationality:** Finnish
**Age:** 30+
**Expertise:** Graduated in CSE; builds Android app
**Occupation:** Android Developer in "XYZ" Organization, GitHub community contributor
**Hobbies:** Playing Video Games and Cats

**Preference:**
* Likes to get notification when changes are made to API, especially documentation Updates and alerts when API goes down.
* Usually uses an API based on the user ratings about its performance.
* Prefers swagger documentation where he can try out methods.


**Scenario**
Aleks decides to design an Android app. 
The app would allow an user to set a 5 minute reminder for a preferred bus route. User can select a bus route and preferred busstop based on the city s/he been living. The app is functionable across Finland.
Aleks search in google with "bussiaikataulu API" and sees that the search result is returning APIs designed specifically for Helsinki and Tampere city. 
Aleks want to add services of Turku as well, but don't see anything specific for the city in search result.
So he searches again with the keywords "bussiaikataulu rajapinta turku" and comes across the site "Föli", used to get timetable for buses in Turku.
Gorint to this site, he discovers a link "Sovelluskehittäjille" that redirects him to the API Data Interface page.
However, the page only gives source of data with on provision to try out methods used in the API.
Aleks returns to the previous search result and goes to API Suomi to look for HSL API. However, he doesn't see nay rating or review for the API.

**Comment by Nazarah** [comment]
A very good article for creating and using persona in commercial product development:
http://www.uxbooth.com/articles/creating-personas/

This article projects the idea of developing persona suggested by Alan Cooper, one of the leading UX figures in the community. I used his suggestions in my Masters thesis as well.

**Comment by bajiat** [comment]
@Nazarah Should this issue be renamed to Create an API consumer persona so that you will be able to close it? Then you can create new issue(s) for other personas.

Also, change Aleks to Aleksi in the text.

**Comment by bajiat** [comment]
ping @Nazarah Please see my previous comment.

**Comment by Nazarah** [comment]
closing this issue as  the persona was added in the doc and new persona creation issue was added.
