### ISSUE TITLE
Add interesting and useful APIs to apinf.io catalog

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#2120]
We should add some good APIs to our apinf.io instance.
One decent-looking source is https://github.com/APIs-guru/openapi-directory, which even has an API that we can integrate: https://apis.guru/api-doc/

# Definition of done
* [ ] Each team member adds at a minimum 2-3 APIs to apinf.io
* [ ] Add a logo and documentation, if possible
* [ ] Optionally, connect the API to the proxy

**Comment by kyyberi** [comment]
In long term I would use planned harvester for this. Harvester will be stand-alone server which sits in between catalogs (other apinf instances and other repositories) and our apinf.io service. It collects periodically meta information about APIs and pushes them to apinf.io. We'll create this anyway to support collecting X-Road APIs from liityntäkatalogi (https://liityntakatalogi.suomi.fi/en_GB/)

While that is planned and implemented, we need to do that by hand. That would be short term response to the need identified by @philippeluickx

**Comment by philippeluickx** [comment]
https://github.com/APIs-guru/openapi-directory actually has a harvester updating the APIs automatically every 48h when changes occur. At least that's what is mentioned on the repo.

**Comment by kyyberi** [comment]
Woohoo! It's a race! :)

**Comment by Nazarah** [comment]
from a Makeup Maniac. ;)

http://makeup-api.herokuapp.com/

right now the added API can only find makeup brands. 
It would be great to be able to search by type as well.
looking forward to get a solution here: #2115  :)

**Comment by bajiat** [comment]
1 API added to catalog, added also logo and documentation link

**Comment by jawidahmadi** [comment]
I added from radio energy  and radio  basso.

**Comment by manzapanza** [comment]
I just found this list of public apis:
https://github.com/toddmotto/public-apis#food-and-drink

There are a lot of public apis organized by category. I will start testing the BreweryDB api and then I will add to apinf.

**Comment by bajiat** [comment]
Closing the issue.
