### ISSUE TITLE
Add UI to add and view Privacy policy and terms of use

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2122]
# User story
> As an admin, 
I want to be able to add privacy policy and terms of use to my deployment
so that I can meet the legal requirements.

> As a user
I want to be able to see the privacy policy and terms of use
so that I know whether it is safe to register and give my user data.

# Definition of done
* [x] Branding settings contain an option for adding a text or uploading a text file 
  * [x] for privacy policy.
  * [x] for terms of use.
* [x] Text or file is stored.
* [x] Template footer needs to show links to
  * [x] privacy policy
  * [x] terms of use.
* [x] Links are only visible if the texts have been added.
* [x] There is a view/partial view/modal to show each of them.

# Wireframe
* In Setting -> Branding page, there is a new panel for adding Privacy Policy and Terms of Use panel.
The panel comes before Colors pane and after site slogan field. (adding these is more important than changing color, so this pane should appear on top)
The panel includes two file uploaders, one for Privacy Policy and one for Terms of Use.
A help icon displays the text when clicked: "You can upload Privacy Policy and Terms of Use information as htm or html files. After uploading the file(s), related link(s) will appear on the site footer."
![brandingpage](https://cloud.githubusercontent.com/assets/17976243/23300458/505f60ec-fa8e-11e6-8dd7-448130eabed0.png)

* HTML files can be uploaded here that defines Privacy Policy and Terms of Use for the site
![brandingpage2](https://cloud.githubusercontent.com/assets/17976243/23300474/5f362376-fa8e-11e6-8b82-4af6aa8c5f8c.png)
Attempting to upload a file with unsupported extension would prevent the upload.  An alert text (made with CSS alert class) would be shown below related file uploader button
![brandingpage3](https://cloud.githubusercontent.com/assets/17976243/23300537/9cf94274-fa8e-11e6-8e8d-afc4260b02c0.png)

* On adding privacy policy and terms of use files, links to see them appear in front page footer
Terms of Use link also appears on the registration page.
![footer](https://cloud.githubusercontent.com/assets/17976243/23201747/a8bf57b2-f8e3-11e6-82fe-cc102132fbcb.png)
![registrationpage](https://cloud.githubusercontent.com/assets/17976243/23201758/b703addc-f8e3-11e6-85c0-33bb0bc32c40.png)
When no file is uploaded, these links will not appear.

* On clicking any of these links, user will be redirected to the related page on the site.
(e.g. https://apinf.org/privacy_policy or https://apinf.org/terms_of_use)
![privacypolicy](https://cloud.githubusercontent.com/assets/17976243/23202032/e0cd31a0-f8e4-11e6-892b-50979c8bd4f3.png)

**Comment by bajiat** [comment]
@nnn Would you be interested? If yes. please estimate

**Comment by bajiat** [comment]
@Nazarah 
> Should we show alert with css alert class when someone wants to upload a file extension that is not .html? like a message "Only html file format is supported." and prevent the file uploading? Or we should include an info icon that provides this information?

At least we should give the alert that the only supported file extensions are htm or html. But I think the best option is to do both: alert for wrong file format and a help text (info icon)

**Comment by Nazarah** [comment]
@bajiat added the mentioned modifications in the wireframes.
