### ISSUE TITLE
Automate the localisation round

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2124]
We are using [OneSky](https://www.oneskyapp.com/) as our online localisation tool for translating and proofreading our translations. At the moment, the files are manually uploaded to the service and manually exported from there after they have been translated, proofread and marked as finalized. After the export, a PR is raised in APInf.

Study automating the toolchain of 
* getting the new strings to OneSky 
* bringing the back to APInf once they are finalized.

**Comment by kyyberi** [comment]
Something around this has been studied in #2050
