### ISSUE TITLE
Helper function to "promisify" method calls

### ISSUE THREAD

**Issue by jykae** [apinf/platform#2126]
Consider adding helper function to core helper functions, use of Promises would make chained Meteor calls easier to read.

Reference: https://forums.meteor.com/t/start-using-async-await-instead-of-promises-and-callbacks/17037/52

**Comment by alfredjkwak** [comment]
Blog post also released: https://blog.meteor.com/using-promises-on-the-client-in-meteor-fb4f1c155f84#.dlpuuizcu

**Comment by mauriciovieira** [comment]
This could be useful especially in callback chained functions we have inside our core.

**Comment by marla-singer** [comment]
Close this issue because the helper function is done
https://github.com/apinf/platform/blob/71770c6117bfc40a0404258ec75e720fccd8850a/apinf_packages/core/helper_functions/promisify_call.js#L9-L17
