### ISSUE TITLE
Research API monitoring options

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2129]
Check monitoring services and whether they could be integrated with APInf. One of the criteria is a REST API for starting monitoring and getting monitoring data back. Supports multi-level criteria for monitoring, such as thresholds set by API managers. The service must also be fully open source.

# Definition of done
* [x] Research more than one option.
* [x] Present the results in a [comparative document](https://github.com/apinf/docs/blob/master/docs/research/API_Monitoring_Service.md) not settling on one of the options.
* [x] Document must contain pros and cons.
* [ ] Document can contain a recommendation.
* [x] Document is stored in docs repository.
* [x] Check and document the license for each option.

**Comment by brylie** [comment]
@Nazarah what are some user scenarios we will be testing with the API Monitoring feature? I would like to include relevant information in my research. E.g. if we believe sending SMS messages will be useful, I want to check what *Notifications* the monitoring solutions support.

**Comment by philippeluickx** [comment]
Make sure to check https://github.com/apinf/platform/issues/1183

I thought there was an open source component from a competitor, but couldn't find it. There are some github repo's though that deal with API monitoring:
- https://github.com/sanathp/statusok
- https://github.com/firehol/netdata (19K stars, but not sure if relevant)
- https://github.com/fzaninotto/uptime

**Comment by Nazarah** [comment]
"" **To be continued..** "

1. the following things to consider:
* server load
* amount of data coming down (result shown as pagination)
* encryption level
* quality of controller code
* Data and transactions important to API owner / Manager

 (resounce: https://smartbear.com/learn/performance-monitoring/guide-to-api-monitoring/)

**Comment by brylie** [comment]
@Nazarah I have added a few rows to the table, based roughly on your comment.

**Comment by brylie** [comment]
Also reviewing the Smartbear article [What is API Monitoring?](https://smartbear.com/learn/performance-monitoring/what-is-api-monitoring/)
