### ISSUE TITLE
APIOps community plan

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2135]
# Make a plan

Draft a plan for how we connect/use/contribute with APIOps community. 

## Define 

- Our role in it. 
- Aims
- How we monetize and what (how to sell; what are the products)
- How to engage developers (gifts, who pays them?) One community "accepted" gift for speakers is Amazon gift card. What else could it be?

**Comment by kyyberi** [comment]
https://github.com/APIOps/community-resources/blob/master/community-plan-2017.md

**Comment by philippeluickx** [comment]
404?

**Comment by kyyberi** [comment]
meh, I renamed it. https://github.com/APIOps/community-resources

**Comment by bajiat** [comment]
@kyyberi @philippeluickx Shall I close this issue in Github?

**Comment by philippeluickx** [comment]
I think this should be managed in Odoo from now on.
