### ISSUE TITLE
Lifecycle status readability should be optimized

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2136]
# Story
In listing the APIs I find it a bit blurry or hard to read given lifecycle status label texts 
![screenshot at helmikuuta 20 08-54-23](https://cloud.githubusercontent.com/assets/1927158/23114984/c5956664-f74a-11e6-8c16-4478af1c8331.png)

# Definition of done
- [ ] Design how to make it better; font face, lightness, etc
- [ ] readability is implemented

**Comment by kyyberi** [comment]
This is just minor thing, but it started to annoy me. Perhaps because it's Monday...

**Comment by mauriciovieira** [comment]
Maybe you just want to remove 'font-weight: bold;' from the label?

**Comment by amardeep-deligence** [comment]
Lifecycle status label texts seems fine now,

![apinf lifecycle status readability issue](https://user-images.githubusercontent.com/19850550/31045116-124a5038-a5fa-11e7-8bb4-a7d1f67f1cd5.png)

**Comment by Nazarah** [comment]
@amardeep-deligence to be honest, this looks smaller to me.
Creates difficulty in reading them.
I think we should increase the font size and labels while increasing the sharpness of both of them.
Perhaps crispier.
WHat do you think?

**Comment by saransh-dev** [comment]
@Nazarah, Yes if we increase font size and labels then it will be more readable.

**Comment by Nazarah** [comment]
@saransh-dev go with it.
