### ISSUE TITLE
Document APInf datamodels

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2145]
# Definition of done
* [ ] Create a datamodel for APInf collections
* [ ] Create an entity relationship model
* [ ] Store the models / diagrams in docs repository

**Comment by brylie** [comment]
![screenshot_20170221_110038](https://cloud.githubusercontent.com/assets/17307/23157748/157108e8-f825-11e6-968e-8ab76de3ba4e.png)

**Comment by brylie** [comment]
Updated work-in-progress:

![screenshot_20170221_131241](https://cloud.githubusercontent.com/assets/17307/23162588/76c0ae20-f837-11e6-8162-d7c7fd658951.png)

**Comment by brylie** [comment]
Update as of this morning, for stand-up:

![screenshot_20170222_105232](https://cloud.githubusercontent.com/assets/17307/23203893/1b997f7a-f8ed-11e6-929c-1f369b38f66c.png)

**Comment by brylie** [comment]
Work-in-progress showing all collections:

![screenshot_20170222_134257](https://cloud.githubusercontent.com/assets/17307/23210133/e1151c66-f904-11e6-8c40-3aa82d780076.png)

**Comment by brylie** [comment]
Work-in-progress showing all collections with most/all relationships:

![apinf-0 40 0-datamodel](https://cloud.githubusercontent.com/assets/17307/23212048/906505d4-f90d-11e6-91e9-df9434d59427.png)

**Comment by bajiat** [comment]
Comment from @matleppa Please add indication of uniqueness
