### ISSUE TITLE
API catalog: Hourglass disappears earlier than the time API list gets visible

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2148]
![apicatalog](https://cloud.githubusercontent.com/assets/17976243/23124679/f2b23790-f776-11e6-9009-8e0fb42e8b03.gif)

**Expected result** : hourglass gif/animation should disappear only after the API list appears in the view

**Comment by marla-singer** [comment]
@bajiat @Nazarah After improving performance of APIs catalog this issue isn't reproduced even in production site where a lot of API items in catalog

**Comment by Nazarah** [comment]
Closing the issue.
