### ISSUE TITLE
APINF nightly: API key is not possible to retrieve

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2149]
# Reproduction steps

1. Login to nightly.apinf.io and add an api.
2. Configure proxy for the API. ( I added Nightly Umbrella).
3. Click on the Get API Key button.

# Result
The S-alert shows key is retrieved successfully but the button gets disabled and keeps showing on "processing".
On refreshing the page, Get API Key button reappears.
No key is shown in the API profile.
![apikey](https://cloud.githubusercontent.com/assets/17976243/23125376/16ac6938-f77a-11e6-85b8-4bd174c78973.gif)

# Expected Result:
on clicking Get API key, key should appear immediately on profile.

# Environment
nightly.apinf.io, windows 8, chrome

**Comment by bajiat** [comment]
@Laura-Sampo was able to reproduce the same error

**Comment by bajiat** [comment]
@marla-singer Didn't you fix an identical error some time ago?

**Comment by marla-singer** [comment]
@bajiat No, I didn't fix it. The problem was because of server settings, no code.

**Comment by marla-singer** [comment]
@bajiat I'm checking it on local

**Comment by marla-singer** [comment]
Maybe problem is on API-umbrella side. Need to repeate it later

**Comment by bajiat** [comment]
@marla-singer ok, thanks for the information. Please check again later.
