### ISSUE TITLE
Proxy path validation blocks adding huuto.net API

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2152]
As a real world example, I tried to add huuto.net API to catalog and add root of the API to proxy. According to huuto.net API documentation, their root is "/1.1/".  http://dev.huuto.net/methods.html#root

![kuvakaappaus 2017-02-20 18-53-46](https://cloud.githubusercontent.com/assets/1927158/23134648/498a44d2-f79e-11e6-845c-8674c16c6d7d.png)

![kuvakaappaus 2017-02-20 18-57-18](https://cloud.githubusercontent.com/assets/1927158/23134697/6df32686-f79e-11e6-82dd-93f3bd103f15.png)

**Comment by bajiat** [comment]
@brylie Please verify the error and see where the problems lies

**Comment by brylie** [comment]
It looks like we just need to allow '.' character in our [API/Proxy base path regular expressions](https://github.com/apinf/platform/blob/develop/proxy_backends/collection/regex.js#L3).

**Comment by brylie** [comment]
We can use the Wikipedia section on [types of URL characters](https://en.wikipedia.org/wiki/Percent-encoding#Types_of_URI_characters) to guide our regex design.

**Comment by brylie** [comment]
There is a good [discussion about URL characters on StackOverflow](http://stackoverflow.com/questions/1856785/characters-allowed-in-a-url), that has a few solutions and mentions some security considerations.
