### ISSUE TITLE
Responsive UI and mobile UX

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2155]
Eventhough APInf is not used heavily from mobile devices in every day life of API manager or API consumer, it is still the first touch point for the masses. As you know well, people access services from mobile more often than desktop nowadays. Yes, the percentage of mobile users varies depending on user segment and context, but still. We don't have the luxury to loose possible API consumers' interest towards us with lowsy mobile UX. Great mobile UX has been default for years already. Here's a snapshop of our current mobile UX. 

![screenshot_2017-02-21-07-32-37](https://cloud.githubusercontent.com/assets/1927158/23154009/4c64add4-f814-11e6-91c0-39bcdf06d7ba.png)

The text is way too small and first impression is repelling.

**Comment by marla-singer** [comment]
@kyyberi It will be profit for us if we have the mobile application as well. As I know MeteorJS supports the Apache Cordova that will provide creating the mobile app
https://guide.meteor.com/mobile.html

**Comment by Nazarah** [comment]
I suggest to conduct a mobile usability test. I can take the responsibility for it. This would identify issues to fix and places where we can make improvements.
