### ISSUE TITLE
If a regular expression fails, inform user about the reason

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2160]
Currently, if regular expression fails, user gets a message aboutit failing, but no information about what was wrong with the string they have typed. Hence, it is difficult for the user to fix this.

# Options:
* Include the rule for the regular expression (e.g. allowed characters)
* Show the exact error (e.g. dot is not allowed)

**Comment by kyyberi** [comment]
So in other words we are not going to support all existing APIs? For example this is working API call https://api.huuto.net/1.1/categories. What is the excuse that I say to developer why Huuto.net API is not available?

**Comment by kyyberi** [comment]
https://stackoverflow.com/questions/6777274/can-urls-contain-dots-in-the-path-part

**Comment by kyyberi** [comment]
Basicly it is a question of practice over standard. Are we in the position to say that customer can not put dots in urls?

**Comment by kyyberi** [comment]
I believe the dot will be acceptable :) #2152

**Comment by bajiat** [comment]
@kyyberi This issue was not about disallowing full stop for paths, it was a general improvement throughout the UI to provide more useful information, if regex fails
