### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#2163]
Automated performance testing will indicate performance issues and also give us a better understanding on our app.
This could be link to ongoing DDOS research https://github.com/apinf/platform/issues/1953.

more info: https://en.wikipedia.org/wiki/Software_performance_testing

**Comment by mauriciovieira** [comment]
This can be done at https://github.com/apinf/apinf-testing repository

**Comment by ilarimikkonen** [comment]
unless there is a clear customer case, no
