### ISSUE TITLE
Wrong URL schema for Swagger UI

### ISSUE THREAD

**Issue by shaliko** [apinf/platform#2165]
If we run Platform with HTTP, but the proxy host will be configured with HTTPS, Swagger UI will try to make a request using HTTP instead of HTTPS.

Swagger UI:
![raspberry_pi_and_slack_-_2glab](https://cloud.githubusercontent.com/assets/36139/23166111/44fb606a-f850-11e6-93b1-d9af59e63716.jpg)

Proxy settings:
![raspberry_pi](https://cloud.githubusercontent.com/assets/36139/23166126/5af123f0-f850-11e6-868a-95da035740cb.jpg)

Reproduced issue when tested Raspberry PI setup where I can't generate Let's encrypt certificate.

**Comment by kyyberi** [comment]
Why can't Let's encrypt certificate be created?

**Comment by shaliko** [comment]
@kyyberi In raspberry Pi case we assume run it in local network.

1) We can't generate SSL certs for IP address https://community.letsencrypt.org/t/certificate-for-static-ip/84/2
2) Would not be possible to issue a cert for a local IP, because everyone could issue a cert for it's own local IP (192.x.x.x).
