### ISSUE TITLE
Effect of General Data Protection Regulation (GDPR) to apinf

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2166]
Check out what kind of effects this might have. There is strong mydata aspect in it. 

http://ec.europa.eu/justice/data-protection/document/index_en.htm

# Goal
- Understand the impact on APInf clients (consent management)
- Research and document 
- Define next steps

**Comment by kyyberi** [comment]
<img width="784" alt="screenshot at helmikuuta 21 21-32-31" src="https://cloud.githubusercontent.com/assets/1927158/23181334/4a0ed190-f87d-11e6-9607-2500db9dfc42.png">

**Comment by mauriciovieira** [comment]
This might be related to [current discussion](https://github.com/apinf/platform/pull/2600#issuecomment-307081705) on EMQ

**Comment by ilarimikkonen** [comment]
dealt with ; closing
