### ISSUE TITLE
Showing footer in every pages in APInf

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2169]
# Usability Issue

With the current implementation of Privacy Policy and Terms of Use, this information can be accessible only from Front page footer and Registration page. 
However, the user might wish to access it from any page at any time. 
With the current implementation, user will need to navigate to front page everytime s/he wishes to view them.

# Enhancement
Showing the current site footer in every page as APInf doesn;t have any infinity scrolling feature.
This would increase information accessibility, as the links for privacy policy and terms of use appear over the footer.

**Comment by marla-singer** [comment]
@bajiat It's already done

**Comment by bajiat** [comment]
@marla-singer Thanks for noticing.

Closing the issue as already implemented.
