### ISSUE TITLE
Normalize ApiMetadata and Organizations collections

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2184]
ApiMetadata collection contains organization (and organization contact) data, while there already is an organization collection. 

![screenshot_20170303_131020](https://cloud.githubusercontent.com/assets/17307/23549447/0015c388-0015-11e7-977c-b5356693f16e.png)

# Goal
All data is stored in database once or in one collection only.

![screenshot_20170303_132750](https://cloud.githubusercontent.com/assets/17307/23549524/53f731b2-0015-11e7-9460-5db4eee5d707.png)

# Definition of done
* [x] Organization fields exist only in Organizations collection
* [x] API Metadata object contains `organizationId` field
  * [x] `organizationId` field is a string, containing the ID of an Organization document
* [x] API Metadata UI displays fields from the related organization document, if connected
* [x] Schema migration has been defined from old database structure to new changes

**Comment by marla-singer** [comment]
@bajiat Interested

**Comment by bajiat** [comment]
@marla-singer Assigned to you. Can you please estimate?

**Comment by marla-singer** [comment]
@bajiat

**Comment by marla-singer** [comment]
We need to migrate the data from the old structure to a new one, if possible. **What to do with old `organization` data from ApiMetadata document?** We can archive the data as an option but a user will not have access to the data.

**Comment by marla-singer** [comment]
I've tested migration and feature on local. Described the different cases and results.

### Case №1
- ApiMetadata contained information about Contact and Service
- API was connected
### Result after migration
- Organization block has information about connected organization
- Contact & Service information are still here

### Case №2
- ApiMetadata contained information about Contact and Service
- API was not connected
### Result after migration
- Contact & Service information are still here
- Organization block is empty as before

### Case №3
- ApiMetadata contained information about Organization & Contact
- API was connected
### Result after migration
- Contact information is still here
- Organization block has information about connected organization
- Old information from organization block is not displayed and is stored in database

### Case №4
- ApiMetadata contained information about Organization & Contact
- API was not connected
### Result after migration
- Contact information is still here
- Organization block isn't displayed and information is stored in database

### Case №5
- ApiMetadata didn't contain information
- API was connected
### Result after migration
- Contact & service blocks are empty as before
- Organization block has information about connected organization

### Case №6
- ApiMetadata contained information about Contact and Service
- API was not connected
### Result after migration
- Nothing happened

**Comment by marla-singer** [comment]
### Cases after migration
Description of feature work when a user connects/disconnects API to organization
- When API is connected to an organization:
    - API Metadata will be created, if it doesn't have information before, and will have information about connected organization
    - API Metadata will be updated, if it has information about Contact or Service before, and will have information about connected organization as well

- When API is disconnected from an organization:
    - API Metadata will be removed totally, if it doesn't have information about Contact or Service
    - API Metadata will be updated, if it has information about Contact or Service.

**Comment by marla-singer** [comment]
@bajiat If everything works as expected, I will label my PR is ready

**Comment by bajiat** [comment]
@marla-singer 
We should not create an organization based on the old data on the API Metadata tab, you are definitely right about this.
Where do you store the old data from metadata tab after migration, if there is no organization? I'm not sure it is needed, if there is no way to see or to take any actions about it.
