### ISSUE TITLE
Create a description about Catalogue harvester

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2186]
# Description
Planned harvester could have features such as
* get meta data of public APIs from X-Road (Finland) and push to apinf.io catalog
* enable harvesting of other API-catalogues with RSS feed or metadata API.
* enable timing configuration of each source harvesting
* collect log of operations
 * Own database
 * User interfaces: API and UI
* Conflict resolution
* Security and trust

# Goal
Needs, purpose, data flow diagram(s) for API catalog harvester documented

**Comment by bajiat** [comment]
First version of description created by Philippe:https://github.com/apinf/api-harvestor/blob/master/requirements.md
