### ISSUE TITLE
Create user documentation for administrator

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2187]
Administrator needs a Getting started guide for the settings and configurations the admin needs to make before a new deployment is made publicly available.

Note: task requires cooperation with sales and support.

# Goal
Based on first customer deployment projects, a first draft of the guide is available

# Definition of done
- [x] Administrator guide repository exists
  - [x] Copyleft license
- [x] Initial Administrator documentation structure and content exist
- [ ] Documentation is available to read online 
  - [ ] Optional download PDF/EPUB

**Comment by kyyberi** [comment]
Isn't this half way done now? Could someone add link to results?

**Comment by brylie** [comment]
The current Apinf Administrator Handbook release is in its own repository:
https://github.com/apinf/apinf-administrator-handbook

Additional changes to the handbook can be made in subsequent tasks.

@bajiat and @ccsr where should we host the Apinf Administrator Handbook HTML files (e.g. what should be the domain/path and hosting situation)?

**Comment by bajiat** [comment]
Either the Documentation link in apinf.com or apinf.org should lead to a **user** documentation page that (among other things) would contain admin handbook or there could be a link in apinf.io footer to documentation.

**Comment by brylie** [comment]
Cool, what URL would the Admin Handbook link point to? Where should we host the Admin Handbook HTML files?

**Comment by bajiat** [comment]
Is it possible to have both apinf.com/documentation and apinf.org/documentation depending on which one the user has as the URL?

**Comment by brylie** [comment]
Yes. One domain can function as an alias for another, which would preserve sub-paths. Which should be our **primary** URL/path?

**Comment by ccsr** [comment]
Primary path is apinf.com

**Comment by bajiat** [comment]
apinf.com
