### ISSUE TITLE
Allow Organization manager to add media content

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2188]
# User story
> As an organization manager
I want to add media content in organization view
so that I can promote organization news and APIs and communicate to developers

# Goal
Organization manager can easily add media content to the organization view

# Definition of done

* [ ] Organization manager can add new related media content related to Organization (same way as media related to API)
* [ ] Related media content is stored into collection
* [ ] Organization manager can modify related media content
* [ ] Organization manager can delete related media content
* [ ] Related media content related to Organization is visible when Organization is selected (either under APIs tab or under new tab (or possibly some other way)

# Wireframes

*Version 1*
1. A new tab appears in the organization page. It is called Media Content. Organization manager can see a pane with an add button there. There is also informative text informing the manager that no content has yet been added there. For regular users, when no content is added, they won;t be able to see the Tab.
![organization](https://cloud.githubusercontent.com/assets/17976243/23704617/7bf4a8c8-040e-11e7-89b5-73a474b200db.png)
2. On clicking the button pop up appears containing Name and URL.
Note: make sure the help text below title and Cancel button is added. In the last work they were missed.
![organization2](https://cloud.githubusercontent.com/assets/17976243/23704651/a5afc440-040e-11e7-94c2-66b33ea55117.png)
3. After Saving Name and URL, the contents appear in the related pane. For a large number of contents, pagination is supported.
![organization3](https://cloud.githubusercontent.com/assets/17976243/23704686/c77e3610-040e-11e7-9eba-c39e03883326.png)

*Version 2*

This design contains both organization APIs and Content Media in the same tab.
The tab is renamed as Details.
The APIs now appear in a separate Pane (Headerless) with the Filtering and Connect API to Organization actions included. 
For a large number of APIs, pagination is supported.
Media Content Pane appears just below the API pane.
The functionality is as same as described in *Version 1*.
When no content is added, regular users won't be able to see the pane.
This is a good design to maintain smaller numbers of tabs.
![organization4](https://cloud.githubusercontent.com/assets/17976243/23704764/20995cfc-040f-11e7-8819-4c821422c7ad.png)

![organization5](https://cloud.githubusercontent.com/assets/17976243/23704778/2e87d80c-040f-11e7-960b-7d0a97cc5e61.png)

![organization6](https://cloud.githubusercontent.com/assets/17976243/23704787/3af6277e-040f-11e7-8e48-cdd8713808af.png)

[Comparisation of two implementation alternatives:](https://github.com/apinf/docs/blob/attach-related-media/attach-related-media)

# Data model (sketch)
![screenshot_20170309_141514](https://cloud.githubusercontent.com/assets/17307/23749877/faf340c0-04d2-11e7-8fe1-7a857161cb84.png)

**Comment by Nazarah** [comment]
Should we use Embded here thta is similar to API profile?

**Comment by bajiat** [comment]
@nnn has promised to help with migration

**Comment by Nazarah** [comment]
@kyyberi @bajiat Right now in API profile, OEMBDED contents appear in the Details tab along with API description field and API End Point field. For organization view, should this be integrated in the same tab as API? or we will be having a new tab a well?
We have been thinking for a while to replace the tabbed view of profile page, so I am not convinced myself that we should have a separate tab to show the contents.
If we are showing it in the same tab where organization APIs are shown, I suggest to rename the tab as well.

**Comment by marla-singer** [comment]
> If we are showing it in the same tab where organization APIs are shown, I suggest to rename the tab as well.

However, don't forget that an organisation can have a lot of API and OEMBDED can be hidden in this case.

**Comment by Nazarah** [comment]
@marla-singer : agreed with that point. One solution to that is to have pagination to see APIs as well. Right now there is also a pagination option to see OEMBDED contents in API profile. However, it has been considered for a while that should we opt for a different view of profiles than a tabbed view. Since Organization profile is still a new thing and there are options to try out new things, we can always go with a new design here

**Comment by matleppa** [comment]
@Nazarah Jawid and I are beginning to plan the implemention of this issue. 
You mention here a possibility for new design. 
Do you already have some thoughts about the mentioned new design?

**Comment by Nazarah** [comment]
@bajiat @matleppa @jawidahmadi : the wireframes are available in the main description.
There are two versions of the design with related descriptions given.
Please have a look, suggest the changes and decide which one would you like to implement.

**Comment by bajiat** [comment]
@Nazarah We cannot see the wireframes. Can you specify where they could be found?

**Comment by bajiat** [comment]
@Nazarah What should in your opinion happen with API pagination in version2, if there is no media content? Is it anyway limited to one row only?

**Comment by Nazarah** [comment]
@bajiat I just checked the API catalog and currently, in default view, we are showing six rows of APIs. For Catalog page, i think it is fine. But for showing APIs in organization profile page, this might be a bit more. We can try out with two rows. However, there is also this consideration that organization visitors can't see the media pane when there is no media added. So for them, the view consists of only APIs. They can have more rows of APIs to view. For Organization Manager, we need to make sure both the API pane and the media pane appears in the default view s.t. s/he doesn't need to scroll down to get to that pane.

**Comment by bajiat** [comment]
@jawidahmadi @matleppa What is the estimate to complete this task?
