### ISSUE TITLE
Include template text about license in each source file in apinf/platform

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2191]
According to EUPL license instructions, it would be good practise to have a notice about the license in each source file. Refer to: https://joinup.ec.europa.eu/sites/default/files/ckeditor_files/files/EUPL%201_1%20Guidelines%20EN%20Joinup.pdf

> For that, the software code itself
must refer to the licence or contain the licence.
The standard way to do this is to put the full
licence text in a file called “COPYING” (or
“LICENCE”), and then put a short notice at the
top of each source file, naming the copyright,
date, holder and licence, and informing the
reader where to find the full text of the licence. 

# Copyright notice and license text to be added
```
/*
* Copyright 2017 Apinf Oy
*
* Licensed under the EUPL, Version 1.1 or – as soon they
will be approved by the European Commission - subsequent
versions of the EUPL (the "Licence");
* You may not use this work except in compliance with the
Licence.
* You may obtain a copy of the Licence at:
*
* https://joinup.ec.europa.eu/software/page/eupl5
*
* Unless required by applicable law or agreed to in writing, software distributed under the Licence is
distributed on an "AS IS" basis, 
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and limitations under the Licence.
*/
```
# Goal
The text above is inserted to source files in apinf/platform in Github. Script or other automated method is preferred.

**Comment by philippeluickx** [comment]
We can also make life easier for devs by providing a template and promoting plugins such as https://atom.io/packages/file-header

This way, you won't forget the license when you create a new file.

In any case, also update contributer guidelines with relevant info and the text.

**Comment by nnn** [comment]
My suggestion based on discussion with @brylie:
 
/*
Copyright 2017 Apinf Oy
This file is covered by the EUPL license. 
You may obtain a copy of the licence at https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence-eupl-v11
*/
