### ISSUE TITLE
Add copyright and license information to About window

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2196]
We should mention our copyright and our (new) license in the APInf About window (about.html).

# To do
* [ ] Add copyright text to About window 
* [ ] Add license information to About window

# Proposal:
- **Copyright** 2017 Apinf Oy
- **License** Licensed under [EUPL]( https://joinup.ec.europa.eu/software/page/eupl) v.1.1

**Comment by marla-singer** [comment]
@bajiat Is placement okay or change order?
![joxi_screenshot_1488556654232](https://cloud.githubusercontent.com/assets/20643403/23558084/5efdaa2c-0043-11e7-8e11-edc85c10acab.png)

**Comment by marla-singer** [comment]
Can you please spicify the headers order? Is the next order good?
- Versions
- Project links
- Credits
- Copyright and license

**Comment by bajiat** [comment]
@marla-singer I would prefer this order:

- Versions
- Copyright and license
- Project links
- Credits

**Comment by marla-singer** [comment]
@bajiat The result is
![joxi_screenshot_1488793714891](https://cloud.githubusercontent.com/assets/20643403/23604798/4489aafe-026b-11e7-8b2a-55032737f406.png)
