### ISSUE TITLE
How to set static IP in Dockerized installation on RaspberryPi

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2198]
Discover novel method to set static IP address on RaspberryPi when deploying APinf platform on it. Minimum is instructions how to do it, anything more automated / simple is plus. 

Related to #2071

**Comment by kyyberi** [comment]
One way to do it would be crontab. Assign wanted IP on reboot 
```sudo crontab -e: @reboot sudo ifconfig eth0 192.168.2.1```

**Comment by Nazarah** [comment]
@ilarimikkonen since u work with raspberryPi, can u take a look in this one? perhaps experiment?

**Comment by ilarimikkonen** [comment]
nope
