### ISSUE TITLE
API and Organization logos not visible in grid view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2208]
# Steps  
1.Visit https://nightly.apinf.io   v 0.41.0
2.Navigate to Organizations / API catalog    

# Actual Result  
API and Organization logos not shown in grid view 

# Expected Result   
API and Organization logos must be shown in both grid and table views  

# Screenshot  

Grid view   
![api_grid_view_logos_invisible](https://cloud.githubusercontent.com/assets/13309358/23460127/53691a56-fe8c-11e6-91bf-42d2ec79117e.PNG)

Table view  
![api_table_view_logos_visible](https://cloud.githubusercontent.com/assets/13309358/23460088/fe7d8bee-fe8b-11e6-9c5d-d1cc8919641f.PNG)    

![org_table_view_logos_visible](https://cloud.githubusercontent.com/assets/13309358/23460151/7675ec54-fe8c-11e6-9637-376f24490300.PNG)

**Comment by kyyberi** [comment]
If the logos should be visible in front page as well, they are not. 
![kuvakaappaus 2017-03-01 15-05-27](https://cloud.githubusercontent.com/assets/1927158/23460989/93e7ac38-fe90-11e6-8c85-a2e0cbac9890.png)

**Comment by saralavanip** [comment]
Verified this issue on staging v 0.41.0 and it was reproducible.

**Comment by bajiat** [comment]
This is not reproducible in nightly. Logos are visible.

**Comment by marla-singer** [comment]
@bajiat We haven't done the release on staging
