### ISSUE TITLE
Untranslated texts in various views

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2209]
# Step  
1.Visit https://nightly.apinf.io   v 0.41.0
2.Login  as admin/owner of API  
3.Change language to 'Suomi'  

# Findings  
Untranslated texts in various views: Title texts ,input field title texts ,help texts are in English language  

# Screenshots     

1. API 'Details' view: 

![suomi_view_partially_translated_text](https://cloud.githubusercontent.com/assets/13309358/23460722/5fab9660-fe8f-11e6-843b-37771028a8f6.PNG)    

2. Add Media dialog: 

![suomi_view_add_related_media_dialog](https://cloud.githubusercontent.com/assets/13309358/23460922/4e40b9cc-fe90-11e6-867e-fd1b945f2516.PNG)    

![suomi_view_add_related_media](https://cloud.githubusercontent.com/assets/13309358/23741435/1e82aafc-04b1-11e7-8620-01057e88d16d.PNG)

3. Users view:  

![suomi_view_users](https://cloud.githubusercontent.com/assets/13309358/23460905/3b0f77e4-fe90-11e6-84a0-2db144b1a89a.PNG)    

4. 'Update Roles' dialog:  

![suomi_view_users_update_roles](https://cloud.githubusercontent.com/assets/13309358/23460917/482578d4-fe90-11e6-82a0-dbcbc7598002.PNG)  

5. Organization 'Settings' view:  

![suomi_view_org_settings](https://cloud.githubusercontent.com/assets/13309358/23460937/5c7cc27e-fe90-11e6-9f26-80b08bf108cd.PNG)   

6. API 'Settings' view: 

![suomi_view_settings](https://cloud.githubusercontent.com/assets/13309358/23460946/6431a80e-fe90-11e6-8969-bc46b40082d1.PNG)

7. Add Backlog Item view:  
![suomi_add_backlogitem_view](https://cloud.githubusercontent.com/assets/13309358/23889132/286a2de2-0894-11e7-81d0-e357c805eda0.PNG)

**Comment by saralavanip** [comment]
This is reproducible on staging v 0.41.0

**Comment by marla-singer** [comment]
@saralavanip @bajiat 
- **API 'Details' view:** (1), **Add Media dialog** (2), **Add Backlog Item view** (7) should be fixed after Translation round
- **Organization 'Settings' view** (5), **API 'Settings' view**(6) can be fixed
- **Users view** (3) and **'Update Roles' dialog:**(4) are the 3rd party library and doesn't support from our code

**Comment by bajiat** [comment]
The following are fixed
- API 'Details' view: (1)
- Add Media dialog (2)
- Add Backlog Item view (7) 
- Organization 'Settings' view (5)
- API 'Settings' view(6) 

As explained above, Users view (3) and Update Roles dialog (4) are from a 3rd party library.

**Comment by saralavanip** [comment]
@bajiat , verified on staging v 0.46.0 and it is not reproducible.
