### ISSUE TITLE
Swagger documentation method expanding links do not work

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2211]
# Steps  
1. Visit https://nightly.apinf.io   
2. Navigate to "Ampersand test" API documentation tab
3. Try to click links identified in the below pic. 
![kuvakaappaus 2017-03-01 15-14-48](https://cloud.githubusercontent.com/assets/1927158/23461450/a7ae5526-fe92-11e6-8fb3-22316d8b0927.png)

# Actual Result  
Nothing happens. 

# Expected Result   
It should list the methods as below for APIs operations list (from swaggerhub documentation viewer): 
![kuvakaappaus 2017-03-01 15-23-16](https://cloud.githubusercontent.com/assets/1927158/23461557/1580f630-fe93-11e6-9949-b7731b4e4f11.png)

**Comment by marla-singer** [comment]
@kyyberi @bajiat Checked a browser console. It throws the errors:
- When you open an API page, an error is
`Uncaught TypeError: $.param.fragment is not a function(…)`
- When you click on a link, an error is
`Cannot read property 'pushState' of undefined(…)`

Tried to find the same bugs. Could find this one https://github.com/swagger-api/swagger-ui/issues/551#issuecomment-55750206

**Comment by philippeluickx** [comment]
From https://github.com/apinf/platform/issues/2102

Getting error in my console when clicking show/hide (Swagger viewer):

```javascript
35d5778….js?meteor_js_resource=true:21
Uncaught TypeError: Cannot read property 'pushState' of undefined(…)
toggleEndpointListForResource @ 35d5778….js?meteor_js_resource=true:21
callDocs @ 35d5778….js?meteor_js_resource=true:22
dispatch @ 35d5778….js?meteor_js_resource=true:30
m.handle @ 35d5778….js?meteor_js_resource=true:30
```

Update: also same error when clicking on "POST" or "GET" etc. when trying to close it.

**Comment by brylie** [comment]
Might it be worth updating our Swagger UI dependncy? I am not sure the underlying problem here, but an upgrade might contain a fix.

**Comment by marla-singer** [comment]
@brylie Now we have the three different required jQuery:
1. `jquery-bbq` module installs and uses the local jQuery library version 1.x (the first one)
2. `swagger-ui-browserify` module installs and uses the local jQuery library version 1.x (the second one). But this module needs to use the patched jquery by jquery-bbq (`$.param.fragment` function)
3. `jQuery` module by 2.x version is installed in our project.

The solution is downgrade jQuery version in our project and re-install node packages. In this case, `jquery-bbq` and `swagger-ui-browserify` will not install jQuery on local folder and will use jQuery from our project.

**Comment by brylie** [comment]
> The solution is downgrade jQuery version in our project and re-install node packages.

I am not sure that we should choose that solution. In general, we are trying to keep our dependencies up to date, so downgrading jQuery would be contrary to those efforts.

**Comment by brylie** [comment]
For reference, we have opened an [upstream issue regarding jQuery BBQ](https://github.com/swagger-api/swagger-ui/issues/1762), which was closed some time ago. I requested the issue be re-opened.

**Comment by marla-singer** [comment]
@bajiat We can close it because that was resolved also on apinf.io site because we are using a new Swagger UI

**Comment by bajiat** [comment]
Closing as per suggestion.
