### ISSUE TITLE
Wrong size Swagger UI icon

### ISSUE THREAD

**Issue by nnn** [apinf/platform#2212]
## Swagger UI icon has wrong size, it's too big

![swagger-big-icon](https://cloud.githubusercontent.com/assets/7489044/23461609/49981822-fe93-11e6-8df6-a22b21d0678c.png)

### Steps to reproduce
- Go to API wit Swagger documenation uploaded

### Environment
- Reproducable on nightly
- Locally with the latest develop branch

**Comment by marla-singer** [comment]
@nnn Duplicate of #2200

**Comment by kyyberi** [comment]
Just reported the same :) #2213

**Comment by kyyberi** [comment]
No it's not duplicate of #2200 - that is about ampersand. This one is about the swagger logo.
