### ISSUE TITLE
'SDK Code Generator' feature unavailable in 'Documentation' view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2216]
# Steps  
1.Visit https://nightly.apinf.io  v 0.41.0  
2.Login as admin  
3.Go to Settings  
4.Enable 'SDK Code Generator'  
5.Enter 'Host'   (eg. https://swagger.apinf.io )  
6.Click on 'Save'  
7.Go to APIs 
8.Select  any API 
9.Go to 'Documentation' 

# Findings  
'SDK Generate' feature not available in 'Documentation' view

**Comment by marla-singer** [comment]
@saralavanip SDK Code generator is available if API has a swagger documentation.
Repeated by myself and it's not reproduced. I logged as ordinary user and navigated to no my API
![joxi_screenshot_1488461432141](https://cloud.githubusercontent.com/assets/20643403/23509113/c1486638-ff65-11e6-8c3e-d442bef2ed77.png)

**Comment by saralavanip** [comment]
@marla-singer , Yes , verified uploading swagger document->generate SDK file
Findings: 
- Shows error message 'code generator server incorrect...'   
- upload swagger document shows a large icon in the viewer 

Screenshot:    
![code_generator_error](https://cloud.githubusercontent.com/assets/13309358/23511037/876251fa-ff64-11e6-8ee3-5fa6d08ed1ba.PNG)

**Comment by saralavanip** [comment]
Verified this issue on staging v 0.41.0 and it is reproducible.

**Comment by bajiat** [comment]
Is this still reproducible or is swagger.apinf.io running?

**Comment by bajiat** [comment]
@shaliko Is swagger.apinf.io up and running?

**Comment by shaliko** [comment]
@bajiat No, will take a look at it today. I waited for details about our DNS for able tests Docker swarm (cluster) on that simple services. If the test will be a success, we will start tests Docker swarm for Apinf setup.

**Comment by shaliko** [comment]
@bajiat I was deployed swagger.apinf.io and http://sdkgen.apinf.io forget notice on Friday.

**Comment by shaliko** [comment]
@saralavanip @bajiat Can we close that issue, swagger.apinf.io was deployed?

**Comment by marla-singer** [comment]
SDK generator works as expected

**Comment by shaliko** [comment]
@saralavanip @bajiat Can we close that issue, swagger.apinf.io was deployed?

**Comment by saralavanip** [comment]
@shaliko  , verified resolved issue on staging v 0.42.0 and it is not reproducible.
