### ISSUE TITLE
Implement high priority endpoints for Apinf REST API

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#222]
Based on [Apinf API design document](https://github.com/apinf/docs/tree/master/docs/develop/REST-API), identify high-priority endpoints. Create server code for endpoints.
# Resources

The following documents can be used and improved upon for the design process.
- [API Design Document](https://github.com/apinf/docs/blob/master/docs/develop/REST-API/API-Design.md)
- [API-Docs.swagger](https://github.com/apinf/docs/blob/master/docs/develop/REST-API/API-Docs.swagger)
## Definition of done
- [ ] Identify high-priority endpoints for Apinf.
- [ ] Implement get methods for the endpoints.
# Related

Related #994  #159.

**Comment by kyyberi** [comment]
This is something community could design with swagger in the next meetup.

**Comment by brylie** [comment]
@kyyberi that would be great! How may I help? E.g. I could identify our system collections, or explain the basic organization of our data.

**Comment by brylie** [comment]
I have updated the task description with links to our existing design document and swagger file.

**Comment by kyyberi** [comment]
Thanks Brylie. This is good task for the apiops community. At least I will continue with the design at the next api jam on 28th day

**Comment by kyyberi** [comment]
We will consider also the api standards used by white house people https://github.com/WhiteHouse/api-standards

**Comment by kyyberi** [comment]
Basic data structure descriptions would be nice.

**Comment by kyyberi** [comment]
@brylie some sort of taxonomy would definitely help us. In fact I see that as a mandatory definition of harmonized API design and implementation.

**Comment by kyyberi** [comment]
There is already API in Umbrella. What is the reason to create another one?
http://apiumbrella.io/docs/admin-api/

**Comment by brylie** [comment]
@kyyberi after discussing with @ccsr, we concluded that Apinf should have its own API for API Umbrella configuration options and additional features not found in API Umbrella.

The taxonomy for the API can probably be derived from our [collections](https://github.com/apinf/api-umbrella-dashboard/tree/develop/both/collections). We can basically provide CRUD endpoints around each MongoDB collection.

**Comment by kyyberi** [comment]
@brylie sounds good!

**Comment by kyyberi** [comment]
Hmm..we will work on this today and post results to hackpad https://digipalvelutehdas.hackpad.com/apijam28112015#API-Jam-28.11.2015

**Comment by kyyberi** [comment]
Group wanted to work with National Libraty of Finland APIs. Lesson learned: if you want community to work with something, you need to be there as one of the team members. I was a bit awkward position in the API Jam.

**Comment by brylie** [comment]
@kyyberi right, we will have to work on that in the future. I cannot attend events on Saturdays, but may be available on Friday evenings, for example.

**Comment by bajiat** [comment]
Closing the issue, since Catalog and Management APIs are already available.
