### ISSUE TITLE
Registering to APInf should be done using a single SignIn Framework

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2232]
# Usability Issue
It is difficult to maintain multiple sign in/ registration accounts (e.g. GitHub, Google). Often they need to be upgraded which takes time and effort. Also user might not be interested in creating a separate account for APInf and may want to register there with their own preferred account. Incorporating single sign in framework will address the above problems.

**Comment by kyyberi** [comment]
Creating accounts for each service is not what users anymore want. IMHO we should push reuse of existing accounts in registration and put local account creation a bit hidden but still available option. In addition the register page should have inspiring and enthuastic message like "Hey! We made it eay for you, just use your existing accounts to register or sign in!"
