### ISSUE TITLE
"Add API" link on top-bar should be designed as CTA (Call To Action)

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2234]
# Usability Issue
Righ now, Add API option in top-bar is not highlighted enough from other menu options. After signing in User may have the choice to navigate through the entire site. But APInf should bring more attention to the main action of a platform by focusing and highlighting it in user's vision.

# Suggestion
Show the Add an API as a CTA in the topbar (i.e. highlighting the placeholder with different color, bigger font size, etc)

**Comment by marla-singer** [comment]
@Nazarah I think the navbar links must be the same kind. The good idea is add CTA in the front page, not navbar.

**Comment by Nazarah** [comment]
@marla-singer : I am OK with changing the position of CTA as long as they are there.
Since Add API is a primary action, wherever it is, navbar or other places, it should be highlighted enough to catch user's attention.
for example, if you got to Hitch: https://www.hitchhq.com/
You'd see that they are highlighting their sign up option on top menu.
This might be their interest that users sign in, but it easily catches user's eyes and the option is at nav bar.
This can be decided together as long as we can highlight what we encourage the users to do once they sign in.

**Comment by Nazarah** [comment]
Done in Next. Closing.
