### ISSUE TITLE
Redesigning Add API page

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2235]
# Requirements:
* [ ] Add inviting texts encouraging new users to add API (e.g. "Simple steps. Takes less than a minute"
* [ ] Renaming fields names to more intuitive ones (e.g. URL -> API Endpoint)
* [ ] Giving less technical and more humane help texts explaining the purpose of each field and what value can be put there.
* [ ] Making Mandatory fields more visible.
* [ ] Using CSS Alert class to highlight unfilled mandatory fields with meaningful alert texts.

**Comment by bajiat** [comment]
Related to #2334
