### ISSUE TITLE
Intuitive instructions about making calls to API

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2239]
# Usability Issue
Right now, API profile points out the endpoint where users can call the API. However, the detailed instructions are missing. It becomes really difficult for novice/less techy users for understanding how to use the API for their Apps or other purposes.
On Usability test performed on 03.03.2017, user was asking about how the calls work. So we might also need some visualizations about it.

# Enhancement
**Open Question**: what can be an intuitive, simple and easy method to show how to use a specific API or integrate it as part of an App?
* [ ] EMBDED content about instructions on making calls to an API and using it in an App? [done my API manager/ developer]
* [ ] Separate section in API profile page with API usage instructions
* [ ] generalized tutorial in youtube?
* [ ] Instruction in API documentation?

**Comment by kyyberi** [comment]
At best Swagger driven documentation should give you the examples and even test drive the API.

**Comment by Nazarah** [comment]
I am thinking about persons who are quite new in using/managing APIs. They might have heard about swagger for the 1st time. To me, API owners should have some quick start tutorial or separate documentation in a different platform than swagger to get started in 3 minutes. And API profile should somehow highlight that option.
