### ISSUE TITLE
Diagram the permissions model

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2241]
# Goal
- Document the user roles and their permissions in a diagram
- Store the diagram in docs repository

# Outcome
![screenshot_20170321_134924](https://cloud.githubusercontent.com/assets/17307/24146401/3a641602-0e3e-11e7-9e04-df38a9891923.png)

## Source files
- https://github.com/apinf/docs/blob/master/docs/develop/Architecture/Apinf-systemModel.png
- https://github.com/apinf/docs/blob/master/docs/develop/Architecture/Apinf-permissionsModel.xml
- https://github.com/apinf/docs/blob/master/docs/develop/Architecture/Apinf-permissionsModel.svg

**Comment by brylie** [comment]
Before starting, I want to see how other projects or people diagram software permission models. I will post any interesting findings to this comment.

# Atlassian
![Jira permissions diagram](https://confluence.atlassian.com/jirasoftwarecloud/files/764478244/764478249/4/1449038097076/Permissions.png)

**Comment by brylie** [comment]
@apinf/core @apinf/developers please review.

**Comment by frenchbread** [comment]
Really good work! 👍 

Just wondering if permission levels for Analytics dashboard should be explained in this document as well?

**Comment by brylie** [comment]
@frenchbread good point. I will consider how to add those to the diagram ASAP.

**Comment by brylie** [comment]
@frenchbread I added the Analytics to the model. See if it aligns with your understanding.

**Comment by marla-singer** [comment]
**Autherticated User** can add Feedback, can set Rating and Get API key
**API Manager** can add Backlog in his own API

**Comment by marla-singer** [comment]
Additionally part 2:
**Organization manager** and **Admin user** can edit Settings in Organization.

**Comment by frenchbread** [comment]
@brylie My understanding is that API Dashboard has two states:

### API Manager
- Can view analytics for **all** APIs added by him/her

### Admin
- Can view analytics for the **entire** APIs collection

**Comment by Nazarah** [comment]
>![screenshot_20170309_162109](https://rawgit.com/apinf/docs/master/docs/develop/Architecture/Apinf-0.41.0-userPermissionsModel.png)

At this picture, under API Manager, the tab for "Proxy" should be added for public/private API block.

**Comment by brylie** [comment]
Thanks all. I have added changes based on your feedback.

> My understanding is that API Dashboard has two states

@frenchbread I do not have a separate block for the dashboard, rather choosing to use a square for 'Analytics'. This is to keep the diagram simple, and indicate the analytics are related to a given API.

**Comment by bajiat** [comment]
What about admin user who can add proxies? And add/edit settings (incl. branding)? Does this need to be visualized?

**Comment by bajiat** [comment]
This diagram is missing the admin permissions for the settings and system proxy. To be reviewed once they have been added.

**Comment by bajiat** [comment]
Thanks to @brylie for documenting the permissions and making the changes. I would say this issue is ready to be closed. Any objections?

**Comment by bajiat** [comment]
@brylie This looks fine to me. Please close after adding a link to any of the diagram documents.

**Comment by brylie** [comment]
Added links to the source files (in three formats).
