### ISSUE TITLE
Staging: password given at Sign in Page retains in Sign up page

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2261]
# Reproduction steps:
* go to nightly.apinf.io and try to sign in with a unregistered email and password.
* After the "Login Forbidden" text appears, navigate to sign up page

# Result:
* password field in Sign up page retains the previous value given in password field of Sign in page.
* On returning back to sign in, the given password exists as well

![password_retain](https://cloud.githubusercontent.com/assets/17976243/23692587/5273a8ae-03d8-11e7-8e81-5e4577ca03a1.gif)

# Expected Result
* given password values should not be retained in any other page.
* On page reload or navigation, all unsaved values should be cleared off the fields.

# Environment
nightly, Windows 8, Chrome

**Comment by marla-singer** [comment]
@Nazarah Em. I think it's Chrome feature. Test it with another browsers

**Comment by Nazarah** [comment]
@marla-singer just tasted with firefox (latest version). Could produce it there. So not a browser specific problem.

**Comment by kyyberi** [comment]
I can't login with Github. Process starts, but is never finished.

**Comment by Nazarah** [comment]
This is the functionality of the Meteor account package.
So unless we won't shift to a different platform, there is nothing much to be done. 
Closing this.
