### ISSUE TITLE
API Profile Feedback form missing options in Finnish lang

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2262]
## Description
User is not able to send feedback to API owner because in the form last option is selecting "Message type" and in Finnish UI there is not dropdown, just text box. 

Service: https://nightly.apinf.io/

## Steps to reproduce

- change UI language to Finnish
- pick an (any) API (open API profile)
- open feedback tab
- click "send feedback"
- in the form last option is just text box (no options as there is in English language).

<img width="581" alt="lomake_fi" src="https://cloud.githubusercontent.com/assets/1927158/23706510/24b32806-0417-11e7-89cb-ec145781fb3f.png">

Possibly missing i18n strings for Finnish?

**Comment by kyyberi** [comment]
Furthermore dropdown should be changed to clickable selection (icons) for the sake of usability

**Comment by bajiat** [comment]
This was resolved in the last translation round. Available in nightly, not in release yet.

<img width="451" alt="laheta palautetta" src="https://cloud.githubusercontent.com/assets/11626388/24245740/c7a53412-0fcc-11e7-8c0b-e03fe5218dd6.png">

Closing as resolved.
