### ISSUE TITLE
Allow blacklisting API users

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2263]
# User stories
As an APInf admin
I want to be able to blacklist any API user
who is misusing APIs

As an API owner
I want to be able to blacklist any API user
who is misusing my API

# Goal
- Misuse can be temporarily or permanently prevented
- Blacklisted user gets a notification
- The setting / blacklisting can be reverted

**Comment by kyyberi** [comment]
At some point part of this should be at least partially automated. When we get monitoring in the framework we can catch some of the abuse cases and blacklist user without owners manual intervention.

**Comment by Nazarah** [comment]
Thsi requires changes made in the API Umbrella.
In APInf, there is no definite way to know who is using the APIs.
So Unless specific customer requests arise, closing this.
