### ISSUE TITLE
Create easy install instructions to get emqtt running on RPI3 (configure with apinf)

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2264]
## Story
This one is continuing the project APInf in DIY home automation, see #2071. In the first phase we got [APInf up and running on RPI3](https://medium.com/apinf/get-control-of-diy-home-automation-55dcf2a6655e#.hlf9w542a). Now we need to get proxy under it. Getting API Umbrella on RPI3 seems to be somewhat more complex and time consuming task, so it makes more sense to go with MQTT proxy first. In addition, I believe (not a fact) that MQTT is more usable in DIY home automation than REST APIs. 

Therefore As DIY home automation builder I want to have MQTT broker in my API management and be able to manage my MQTT broker and users using it. At this phase we don't want to use it. We just want **easy way to install it and prepare it for use**. Again as in first phase, using docker might make sense, but I leave that to the more skillful people to define. Review to be done by installing the proxy with given instructions. 

Using the APInf and proxy is the next phase, which will be handled under another issue. 

## Definition of done (TBD by assignee)

- Create docker image for MQTT on Raspberry PI.
- Share docker image on DockerHub under apinf account and share source code of Docker file on GitHub.
- Extend [docker-compose.yml](https://github.com/apinf/platform/issues/2071#issuecomment-281345453) with MQTT service.
- Add installation instructions to [INSTALL.md](https://github.com/apinf/platform/blob/develop/INSTALL.md)

**Comment by kyyberi** [comment]
@bajiat defines a spot when this can be done.

**Comment by shaliko** [comment]
@kyyberi @bajiat Please check "Definition of done".

**Comment by kyyberi** [comment]
@shaliko loosk good. I don't have anything to add at this point.

**Comment by shaliko** [comment]
@phanimahesh @kyyberi  what do you think, can we use https://mosquitto.org/ ? I found that it can be easy installed on Raspberry PI.

**Comment by kyyberi** [comment]
I don't have the skills or knowledge to make statement. If we aim to get something to the dashboard from mqtt broker, does selecting mosquitto make our future path much harder? If not, then lets go with the mosquitto. If yes, then the question is how much additional work it require and how to maintain the package in the future. Any deviation from "standard" APInf mean probably more maintenance tasks.

**Comment by shaliko** [comment]
@jawidahmadi Did you accidentally close that task?

**Comment by kyyberi** [comment]
Probably, opened again.

**Comment by kyyberi** [comment]
Any updates for this? Expected date to do test install with instructions to Raspberry?

**Comment by preriasusi** [comment]
Let's put to ice box for a while. If someone starts to work with this, then let's move it to in progress ...
