### ISSUE TITLE
Footer: Details missing

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2267]
# Steps 
1.Visit https://staging.apinf.io (v 0.41.0)  

# Findings   
Footer : details missing -> Github and Twitter icons (links), 'Powered by: Apinf Oy'    

# Screenshot  

Staging 
![staging_footer_details_missing](https://cloud.githubusercontent.com/assets/13309358/23748895/3d357ae8-04ce-11e7-86ac-91eb56f5afb5.PNG)
 
Nightly  
![nightly_footer_details](https://cloud.githubusercontent.com/assets/13309358/23748924/5c666abc-04ce-11e7-93a2-996b3a114e55.PNG)

**Comment by marla-singer** [comment]
@saralavanip Change Branding settings

**Comment by saralavanip** [comment]
@marla-singer , Ok! related to admin settings and works as expected.Thanks! closing this issue.
