### ISSUE TITLE
Dashboard console error when rendering proxy backend select widget

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2268]
The dashboard on nightly.apinf.io is currently rendering blank. The following error is in the console:

```js
TypeError: Cannot read property 'name' of undefined
    at e.apiName (c984729….js?meteor_js_resource=true:447)
```

# Steps to reproduce
1. Log in as **admin** to nightly.apinf.io
2. Press Dashboard link

# Expected result
You are able to select an API for viewing

# Actual result
You see a blank page with only the title Dashboard

# Screenshot
<img width="607" alt="empty dashboard" src="https://cloud.githubusercontent.com/assets/11626388/23987056/1fda4e8a-0a30-11e7-9a7f-719a1e35677f.png">

This may be due to a missing subscription in the Dashboard code:

![screenshot_20170309_150406](https://cloud.githubusercontent.com/assets/17307/23751372/a8e1333a-04d9-11e7-9e8e-a18b61b6558e.png)

**Comment by marla-singer** [comment]
@brylie Nope. Looks like the subscription is not ready. On local it's ok. I have data on a client side in nightly. But the error I have as well.
![2017-03-09 18 41 55](https://cloud.githubusercontent.com/assets/20643403/23757571/46caf946-04f8-11e7-94c5-94f81c1dc622.png)

**Comment by marla-singer** [comment]
But on the another hand, we actually wait for readiness of subscription. 
https://github.com/apinf/platform/blob/develop/dashboard/client/dashboard.html#L6

**Comment by marla-singer** [comment]
@brylie It repeats when the user is admin. I checked it as manager, wasn't reproduced.

**Comment by marla-singer** [comment]
I detected the reason. Dashboard page has only managed APIs data. The error isn't reproduced for a manager because in this case, all needed data is on the client side. But when a user is admin, the client side doesn't have needed data and there throws error

**Comment by brylie** [comment]
Thanks @marla-singer.

@bajiat, should we prioritize this issue? E.g. for next sprint perhaps?

**Comment by bajiat** [comment]
Yes, we should prioritize definitely prioritize this.

**Comment by marla-singer** [comment]
@bajiat Interested

**Comment by bajiat** [comment]
@marla-singer It's yours. Please estimate.
