### ISSUE TITLE
Multiproxy: Add and connect API to proxy shows error

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2269]
# Steps  
1.Visit https://staging.apinf.io (v 0.41.0)  
2.Login 
3.Add API 
4.Connect API to proxy (eg, API Umbrella: https://staging.apinf.io:3002)  

# Findings    
- Connect API to 'Staging proxy' shows error : 'API key invalid....'     
- Connect API to 'Second nightly' proxy shows error 'Cannot read property length of null'      

# Screenshot  
![connect api to proxy shows error](https://cloud.githubusercontent.com/assets/13309358/23752407/d6bfb958-04dd-11e7-88cb-f81ab8c97a79.PNG)  

![connect_api_second-nightly_error](https://cloud.githubusercontent.com/assets/13309358/23752415/dfa6d146-04dd-11e7-80c9-772bdbc1fe48.PNG)

**Comment by marla-singer** [comment]
@saralavanip "API umbrella" proxy has the old incorrect credentials. I created a new one with name "API-umbrella new". Please check it again.
What about the Second nightly - the server works unstable. Please check multi-proxy case with "Nightly umbrella". This should work as expected.

**Comment by saralavanip** [comment]
@marla-singer , Add API->connect API to proxy: 'Nightly Umbrella' / 'API Umbrella new' / Second nightly is working as expected.  

Change API proxy to ->API Umbrella new/ Second nightly is not responding.

**Comment by manzapanza** [comment]
@marla-singer @saralavanip The second error also happens when the proxy configuration has some wrong data.

**Comment by marla-singer** [comment]
@manzapanza Check it on https://nightly.apinf.io

**Comment by bajiat** [comment]
@marla-singer Can this issue be closed?

**Comment by marla-singer** [comment]
@bajiat Yep

**Comment by bajiat** [comment]
Thanks for the confirmation! Closing.
