### ISSUE TITLE
'Filter by' not working when clicking labels on Organization rofile

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2270]
When viewing an Organization Profile, clicking the API Lifecycle status labels does not trigger a filter action.

![peek 2017-03-09 15-40](https://cloud.githubusercontent.com/assets/17307/23752648/e3f06b44-04de-11e7-81f5-fb5289bd0c0b.gif)

**Comment by marla-singer** [comment]
@brylie It was added in develop branch a couple hours ago. You should test it tomorrow

**Comment by brylie** [comment]
OK, thanks. Forgot about the timing of deployments. Just in the habit of creating issues as soon as I observe them, so I don't forget.
