### ISSUE TITLE
Feedback improvements

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#2271]
Quick feedback on the feedback process (meta-feedback?):

- Too complex - 3 fields to fill in for a simple feedback?
- Modal - not the right UI (discussion can be found online, but consensus is driving towards not using modals for this purpose)
- Not clear what happens with my feedback. Who gets the feedback, how do I get notified about replies?

**Comment by kyyberi** [comment]
+1
related to #2265

**Comment by kyyberi** [comment]
Example from use 
![kuvakaappaus 2017-03-09 18-23-30](https://cloud.githubusercontent.com/assets/1927158/23759566/cdf81b5e-04f5-11e7-98be-e4d8a384b5da.png)

As API designer I would like to respond to questions. In addition, we'll come to situation that we have pretty soon 50+ items in feedback. Perhaps there should be similar to Github filtering (open/closed?)
