### ISSUE TITLE
Understandable URLs for APIs and organizations

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2279]
It might not sound a big issue but we need to have human understandable URLs for APIs.
This hardly is one: https://apinf.io/api/TYf33t5B6D6fwamKt (APInf Catalog REST API). Suggestion is to make it something like https://apinf.io/apis/APInf-Catalog-REST-API 

Note that in path I used plural "apis" which is the practice in REST APIs (in our catalogue API as well). This would make REST API and web behave with the same logic here. This would be just additional fine tuning and part of productisement.

**Comment by kyyberi** [comment]
Same goes for organizations.

**Comment by marla-singer** [comment]
@kyyberi The organization profile already has the friendly url
https://nightly.apinf.io/organizations/darias-organization
https://nightly.apinf.io/organizations/zoo
https://nightly.apinf.io/organizations/test-new-organization

**Comment by kyyberi** [comment]
Good! I've been working mostly with the production version so I'm not always uptodate about what's in the staging. 

What are the problems you refer to?

**Comment by marla-singer** [comment]
The tail of URL is the ID of API in the database. And it is the easy way to know ID of current API - get it from URL. So it's possible but can take a time to remove from ID to friendly (slug) URL for APIs. It just a remark from me to keep it in mind.

**Comment by philippeluickx** [comment]
Related to https://github.com/apinf/platform/issues/1400

We should go like Github. Namespace either organization or user. Then the uniqueness comes from combination of org/user + slug.

Slugs can be auto-increment. https://github.com/todda00/meteor-friendly-slugs

**Comment by kyyberi** [comment]
If we go with github model, it means that APIs can not be moved from person or organization to another without breaking the applications using given APIs. Change in the slug affects API paths, right?

**Comment by philippeluickx** [comment]
That's where lifecycle comes in I assume? Your argument is true even without using apinf.io. If I decide to rename my company "foo" to "bar" then I would probably also have to change my api url from api.foo.com to api.bar.com.
Feedback welcome!

**Comment by bajiat** [comment]
@marla-singer Would you be interested in this? Just the URL slug. Namespacing would be solved separately.

**Comment by marla-singer** [comment]
@bajiat Without namespaceing it's a large work. If 5 days estimate is okay, I can take it.

**Comment by philippeluickx** [comment]
@marla-singer could you explain why it would be so much work?

**Comment by marla-singer** [comment]
@philippeluickx As I told above now URL for API contains the semantic mean. - it's ID of current API. And our code bases on this ID: API profile, Documentation, Feedback, Metadata, Backlog, Settings - [all tabs on API profile page.](https://github.com/apinf/platform/blob/develop/apis/client/profile/view.js#L25-L52) 
@brylie Or do I overrate?

**Comment by marla-singer** [comment]
I leave my estimates the same - 5 days

**Comment by philippeluickx** [comment]
I don't think slug is replacing the ID. It only is used for URL resolution?
At least that's how I've seen it done in other platforms.

Also please implement it in a way that namespacing can be added later. Or would it be easier with doing namespace at the same time?

**Comment by marla-singer** [comment]
@philippeluickx As I remembered, we discussed namespace for Proxy backend request to API-umbrella, not for API URL. And this task doesn't have any relationship to namespace

**Comment by philippeluickx** [comment]
Ah ok, my bad.

Comment about slug not replacing ID still relevant though.

**Comment by brylie** [comment]
> @brylie Or do I overrate?

@marla-singer I trust your instinct. Lets agree to keep the work simple for now, and just focus on unique URL slugs for APIs. We can discuss namespacing further in the related issue, since it does not seem to block this issue.

**Comment by bajiat** [comment]
@marla-singer I trust your estimate on this, but I'm curious to know why is it large work without namespacing? You can self-assign in any case.

**Comment by marla-singer** [comment]
@bajiat What namespacing do you mean? Issue description doesn't contain any information about that, just only friendly URL for APIs. The namespace was discussed in [this issue](https://github.com/apinf/platform/issues/2115#issuecomment-280638220) for frontend prefix of proxy backend
If you meant namepsacing like as `https://apinf.io/daria/apis/TYf33t5B6D6fwamKt` then it's not a big deal. But I don't really understand why these issues are related. There are two different task as for me.

**Comment by bajiat** [comment]
@marla-singer 
You commented earlier
> Without namespaceing it's a large work

That is why I asked.

**Comment by marla-singer** [comment]
I tried to explain it above

**Comment by brylie** [comment]
> API contains the semantic mean. - it's ID of current API. And our code bases on this ID: API profile, Documentation, Feedback, Metadata, Backlog, Settings

The tabs on the API Profile are appended to the end of the URL as relative paths (prefixed by #). So, we shouldn't have to touch routing for any of the components other than the API Profile itself.

**Comment by marla-singer** [comment]
ok, I will try to leave it as simple as possible
