### ISSUE TITLE
Footer code for platform admin

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#2288]
# Scenario
As owner of an installation of APInf, I want to analyze how users are going through the platform. What do they do, where do they drop off, where do they come from etc.

# Solution
There are a lot of 3rd party tools that are typically integrated with a line of Javascript code added in the bottom of the master template. By adding a field for admins to fill out, we can support any of these.

**Comment by nnn** [comment]
Interested.

**Comment by nnn** [comment]
Instead of creating our own solution, I propose to use much more safe package:
https://github.com/okgrow/analytics

### Currently Supported Analytic Services

Amplitude
Chartbeat
comScore
Google Analytics
HubSpot
Intercom
Keen IO
KISSmetrics
Mixpanel
Quantcast
Segment.io

**Comment by nnn** [comment]
@brylie @philippeluickx let's discuss potential security risk here. Maybe it's not wise to allow users to paste JS code directly in to the project.

**Comment by jawidahmadi** [comment]
hotjar is recommended by @philippe to add for collection for admin site's statistics. There are free and paid version of hotjar, both require registration. We need a generic e-mail address to proceed with registration.
There are also a need for Google Analytics subscription, if Apinf already possess a subscription, it is good to reuse it in this context.

**Comment by philippeluickx** [comment]
By the way, the choice of these services should not be baked in. This would only be what we want to implement on our instance.

**Comment by brylie** [comment]
OKGrow:analytics [creates its analytics settings object at startup](https://github.com/okgrow/analytics/blob/master/client/constants.js#L4-L5) (provided in a [settings.json](https://github.com/okgrow/analytics#configuration)). I can't figure out a way to get the OKGrow to check for analytics settings at run-time, without submitting a patch to the upstream project. Here is a brief experiment I tried in Meteor.shell:


```js
> const testAutorun = Tracker.autorun(function () {
  const settings = Meteor.settings;
  console.log('settings changed')
});

> Meteor.settings.test = 'test';
> Meteor.settings.test1 = 'test';
```

**Comment by bajiat** [comment]
@marla-singer Can you take this task as well?

**Comment by marla-singer** [comment]
@bajiat Yes, I can
