### ISSUE TITLE
Click on filter tab 'My organizations' shows user info. text momentarily

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2289]
# Steps  
1.Visit https://staging.apinf.io  (v 0.41.0)    
2.Login as admin 
3.Add organizations 
4.Go to Organization catalog 
5.Click on filter tab 'My organizations'  

# Findings 
- Click on filter tab 'My organizations' shows user info. text  momentarily "No organizations available....Click on 'Add Organization' button to add one "   
- Click on My organizations->click on 'Show all' also shows the same info text momentarily.  
- Similar to above findings: navigate from API catalog to Organization catalog shows info text "No organizations available......"

**Comment by marla-singer** [comment]
@saralavanip Can you please test this issue as well? 

It isn't reproduced on my side. I think this problem is resolved but developers didn't close it

**Comment by saralavanip** [comment]
@marla-singer , Verified this resolved issue on staging v 0.46.0 and it is not reproducible.We can close this issue.

**Comment by marla-singer** [comment]
Closed this issue as resolved
