### ISSUE TITLE
User unable to Export: API or proxy configuration in YAML or JSON formats 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2291]
# Steps  
1.Visit https://staging.apinf.io   v 0.41.0
2.Login as admin/owner 
3.Add API
3.Go to API catalog 
4.Select API added above
5.Click on 'Export' 
6.Go to 'Export API/Proxy configuration'  
7.Click on 'Export .yaml / Export .json  '   

# Expected Result  
Successful  export  API / proxy configuration in .yaml or .json formats    

# Actual Result  
Click on 'Export. yaml or Export .json  not responding

**Comment by manzapanza** [comment]
@saralavanip @marla-singer  This happens when the api doesn't have a proxy configurated. In this case maybe we should hide the export proxy buttons?

**Comment by marla-singer** [comment]
@manzapanza Check it on https://nightly.apinf.io

**Comment by manzapanza** [comment]
@marla-singer You mean that the export tab disappear?

**Comment by marla-singer** [comment]
@manzapanza Nope. Export working. It works as expected

**Comment by manzapanza** [comment]
@marla-singer You are right. I will test it better!

**Comment by manzapanza** [comment]
@marla-singer I created the api [BreweryDB](https://nightly.apinf.io/apis/7FsWbpbayYTLYJQP2) without a proxy configured. If you try to **Export proxy configuration** you will download a file **apiProxyConfig.json** with "undefined" as content. So it's doesn't works. In this case, when the api proxy is not configurated, we should hide (or disable) only the **Export proxy configuration** or show an alert with a message like "No proxy configuration to export".

As enhancement, I would like to have the api name in the file name like "BreweryDB-ProxyConfig.json" and ""BreweryDB-Config.json".
