### ISSUE TITLE
User not notified if no 'My APIs' available

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2293]
#Steps 
1.Visit https://staging.apinf.io  ( v 0.41.0 )  
2.Sign up 
3.Go to APIs catalog  
4.Click on filter tab 'My APIs' 

#Findings  
- Shows empty page   
- Users might be notified with info text eg. "There are no APIs that you manage...Add API"    

Screenshot  
![no_myapis_empty_page](https://cloud.githubusercontent.com/assets/13309358/23906890/1855580c-08d8-11e7-8965-5fc7cc196665.PNG)

**Comment by wuder4** [comment]
Now it shows:
No APIs found with the selected life cycle status
