### ISSUE TITLE
Sign Up/Sign In with Github account not responding

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2295]
# Steps    
1.Visit https://staging.apinf.io   (v 0.41.0) 
2.Navigate to Sign Up 
3.Click on 'Register with Github account'  
4.Enter username and password  
5.Click on 'Sign In' button   

# Expected Result    
- Successful Sign up with Github account 
- User logged in to https://staging.apinf.io  

# Actual Result     
- Remains in 'Sign Up' page  
- Github login view shows info text 'Sign In to Github to continue with nightly.apinf.io' 

# Screenshot   
![staging_register_with_github_account](https://cloud.githubusercontent.com/assets/13309358/23909673/0b97c3c2-08e0-11e7-85f6-f4b94dce0823.PNG)   

![signup_page](https://cloud.githubusercontent.com/assets/13309358/23910465/7abac3c4-08e2-11e7-91b2-54f3b4038b8a.PNG)

**Comment by bajiat** [comment]
@saralavanip Closing. Should not be reproducible now, I have modified the Github registration settings for staging and tested sign up.
