### ISSUE TITLE
Architecture documentation for FIWARE

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2302]
# Goals
Prepare and deliver documentation/diagram about
* run-time architecture and api management components
* how to configure api management

# Work in progress
![screenshot_20170321_110024](https://cloud.githubusercontent.com/assets/17307/24139679/b9b260a8-0e25-11e7-8458-b1045f47cfa0.png)

**Comment by brylie** [comment]
@apinf/core please review this work-in-progress diagram. Feedback is welcome.

**Comment by bajiat** [comment]
Should we close this issue?
