### ISSUE TITLE
Organization page branding

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2303]
# User story
As an organization manager,
I would like to configure my organization's page
and add branding elements to the page.

# Customer requests
* Cover image
* Handling organization logos: no scrunching allowed
* Configurable social media link
* Configurable number of APIs 
* Configurable number of media items 
* RSS feed about APIS: triggered by adding an API
* Pinning featured APIs to the top of the API catalog
  * visual indication of featured API needed
* API catalog sorting options: time added and alphabetical (internationalised) sorting
* Consolidate settings into one place
* Number of APIs and number of bookmarked/ liked APIs
* Top bar colors to reflect organization colors

**Comment by kyyberi** [comment]
We probably should provide color scheme tool like this http://www.pictaculous.com/ Build colormap from logo colors.
