### ISSUE TITLE
Displaying organization logos: no scrunching allowed

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2306]
# Goal

Organization logo aspect ratio is maintained on the organization page. 
This means that other content next to the logo is shifted to make room the logo, if necessary, when the page is rendered.
Logo upload is moved in to  Branding configuration in Settings page.

# Definition of done
To be defined by assignee

# Wireframe
1. In Organization Settings tab, the General section contains a Logo uploader with help text.
![organizationsettings4none](https://cloud.githubusercontent.com/assets/17976243/24240521/9ce7556e-0fba-11e7-805c-3b79582a7612.png)

2. On uploading the logo, it will appear in the Organization profile Page header.
The aspect ratio of the picture should be maintained so that the height and width changes accordingly to accommodate the picture within the max dimension values.
![organizationsettings4onlylogo](https://cloud.githubusercontent.com/assets/17976243/24240529/a7b372ca-0fba-11e7-8b2a-59771e83926f.png)

3. A new addition to the organization logo placeholder is to allow a white border on the logo to be uploaded. 
This would be helpful in distinguishing the logo from cover picture (if uploaded any). ex: See Facebook user profile page.
The picture border changes its dimension based on the changed aspect ratio of the uploaded logo
![organizationsettings4all](https://cloud.githubusercontent.com/assets/17976243/24240544/b369c376-0fba-11e7-9127-04ffffde0fc6.png)

**Comment by Nazarah** [comment]
Need clarification: will we have a separate panel called "Banding Configuration" in Settings tab of Organization profile? Because from the Settings page under User profile, we are able to change only site logo and background image.

**Comment by bajiat** [comment]
@Nazarah There is a task for consolidating settings. That task also contains the Branding Configuration. (You can come up with a better name)

**Comment by Nazarah** [comment]
@bajiat @matleppa I've added the wireframes in the issue with descriptions. 
Please take a look and give me your feedback.
An additional task thta needs to be done is to reposition the logo placeholder and header text placeholders so that they are aligned with the start of the tabs. 
This is also to make place for logo picture border.
So, should I define a new task for this?

**Comment by nnn** [comment]
Resolved by #2386
