### ISSUE TITLE
Configurable social media links

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2307]
# Goal

* Owner can define links to social media to be shown on the header part of the page. 
* There is a predefined list for social media for which a link can be added: Twitter, Facebook, Instagram. Linkedin.
* There is a logo for each of the social media in the same way as for the contact information
* Adding the links is not mandatory
* When a link has been added, it is displayed in the header area. If it is empty, the logo is not displayed

Open issue: Is it enough for the logo to act as the link?
Depend on #2317 

# Definition of done
- [x] Create fields in schema.js
- [x] Display form on the page of Settings tab
- [x] Display icons on the header
- [x] Styles icons

# Wireframe
![organizationsettings4all](https://cloud.githubusercontent.com/assets/17976243/24242828/b472a998-0fc1-11e7-9beb-a4cc605d95bd.png)

**Comment by marla-singer** [comment]
@bajiat Interested on the next sprint

**Comment by kyyberi** [comment]
And LinkedIn

**Comment by Nazarah** [comment]
Should we show the added logos in Organization profile header? 
If we have small numbers of logos, then they can be accommodated in the header. Otherwise, we can always use a simple share button and be clicking this would show available social platforms in a small menu.
We also can show them below profile page, but this would require users to scroll down and this might create issues with visibility and access.
Need Clarification: Will organization manager be configuring the social media links from Settings tab in organization profile?

**Comment by Nazarah** [comment]
https://sharebutton.co/

A good option to try on. Can be forked from Github as well. We can always change the button style with a share icon and place this on organization header.

**Comment by bajiat** [comment]
@marla-singer Assigned to you. Please estimate.

**Comment by marla-singer** [comment]
@Nazarah I think it should be the same as Branding page has the Social Media block. Is it?
![joxi_screenshot_1490013084151](https://cloud.githubusercontent.com/assets/20643403/24099822/4bc4516c-0d82-11e7-937d-be51305e87f6.png)
In API profile header I image all icons will have a grey color and when a user hovers on icons, the color will be changed

**Comment by marla-singer** [comment]
As a draft
![joxi_screenshot_1490096483350](https://cloud.githubusercontent.com/assets/20643403/24145921/7e966586-0e44-11e7-9a09-d5302cf40c42.png)

**Comment by Nazarah** [comment]
@marla-singer : I have something a bit different in my mind considering how to show the fields for social media.
At first we are supporting four platforms: Facebook, Twitter, Instagram and LinkedIn.
So we can simply use one field for each with the field name specific for a platform.
Manager can directly add the URL and save it.
Second, we are considering to remove BS panels to give the page a cleaner and simpler look.
So there is a separate social media section defined with H3 header style and whitespaces to separate it from other sections.
The fields appear under the section header.
thirdly, we need to keep in mind that there can be cover picture for the organization.
So the picture contrast may actually reduce the visibility of social media platforms.
So we need to place those in a transparent panel, s.t. whatever the cover picture might be, the icons  have better visibility. 
(example: go to any youtube channel and see in the channel page how the social media platforms are displayed over the channel cover picture)
@bajiat looking for your feedback as well.

**Comment by marla-singer** [comment]
@Nazarah No problem. Your wireframe looks nicer :+1:

**Comment by marla-singer** [comment]
> Second, we are considering to remove BS panels to give the page a cleaner and simpler look.
So there is a separate social media section defined with H3 header style and whitespaces to separate it from other sections.
But I don't see any Save button.

**Comment by marla-singer** [comment]
@Nazarah Which kind of icons should I use? Image or font awesome?

**Using image**
![joxi_screenshot_1490175848125](https://cloud.githubusercontent.com/assets/20643403/24195078/6f168670-0f09-11e7-88f3-ea3fba7d10b6.png)

**Using font awesome**
![joxi_screenshot_1490180965047](https://cloud.githubusercontent.com/assets/20643403/24195085/714700c8-0f09-11e7-8aec-1f7f01ed35ed.png)

**Comment by Nazarah** [comment]
@marla-singer I am sorry I forgot to Add Save buttons in relevant sections.
I have a question. Can we do Auto Save as the values are given in fields/drop menus?
If not, I'd like to use a global Save button instead of adding one for each section. That might make the GUI messy. I'd still experiment with it and give the wireframes.

About the Social Media, please use the images. They gives more originality.

**Comment by Nazarah** [comment]
@marla-singer is this ok now?
![organizationsettings4all](https://cloud.githubusercontent.com/assets/17976243/24239316/2f2b71bc-0fb6-11e7-886a-091fe8d609c1.png)

**Comment by Nazarah** [comment]
@marla-singer also considering having the social media icons on a transparent panel.
This would increase their visibility when there is a cover picture.
The panel color can be #000000 with 80% opacity rate.

**Comment by marla-singer** [comment]
@Nazarah Yes, sure, I'm remembering about it. Just show you a draft :) Work in process
