### ISSUE TITLE
Number of APIs shown on the organization page

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2308]
# Goal

Allow the organization manager to define the number of APIs to be shown on the organization profile page in one view. This should happen in organization settings / branding configuration.
This also requires pagination for the API block.

# Definition of done

* [ ] Add a select list
* [ ] Select list is populated by numbers in 4, 8, 12, 16, 20, 24.
* [ ] On each number change, the display on the organizations-api catalog page should change. Number of api catalog to display, must be dependant on selected number of selec list.
* [ ] Implement on state chage event handler. 
 
# Wireframe
1. There is a section called Content Management under Settings tab in Organization Profile.
A dropmenu named "Number of APIs to appear on Organization default view".
The APIs numbers can be selected from here.
By default, the number is shown.
The dropmenu shows the following numbers to select from: 4, 8, 12, 16, 20, 24 [numbers taken from API profile].
![organizationsettingsapinumber](https://cloud.githubusercontent.com/assets/17976243/24288623/ca02fd4c-1086-11e7-97e0-63c707209c3a.png)

2. Based on the selected number, API cards appear in General tab of the organization (with pagination if needed)
![organization6](https://cloud.githubusercontent.com/assets/17976243/24193823/41674be0-0efc-11e7-99d8-0f5d26e4b870.png)

**Comment by Nazarah** [comment]
Right now, both in API catalog and Organization profile page, 4 APIs are shown in each row. Should we have a dropmenu in Settings tab having numerics that are multiple of 4? Or organization manager would be able to give manual entry to that number?

**Comment by bajiat** [comment]
If the screen is smaller, then it is not 4 APIs, right?

**Comment by Nazarah** [comment]
@jawidahmadi I hope the wireframes are clearer now. :)

**Comment by bajiat** [comment]
Blocked by #2341
