### ISSUE TITLE
Number of media items shown on the organization page

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2309]
# Goal

Allow the organization manager to define the number of media items to be shown on the organization profile page in one view.
Configurable mode requires changes to pagination feature.

# Definition of done
* [x] Update the organization model by added new field for number of medias.
* [x] Add view for the number of medias, use a dropdown list and save button.
* [x] Add a controller to trigger the button event.
* [x] Add a functionality to update the organization model upon user click on button.
* [x] Add an alert message to confirm the action is successful.   
# Wireframe
1. There is a section called Content Management under Settings tab in Organization Profile.
A dropmenu named "Number of Media Items per page".
The media item numbers can be selected from here.
By default, the number is shown.
The dropmenu shows the following numbers to select from: 4, 8, 12, 16, 20, 24 [numbers taken from API catalog].
![organizationsettingsmedianumber](https://cloud.githubusercontent.com/assets/17976243/24288684/055db918-1087-11e7-912a-b00131ece979.png)

2. After Saving, based on the selected number, Media content cards appear in General tab of the organization (with pagination if needed)
![organization6](https://cloud.githubusercontent.com/assets/17976243/24242642/0c5a2826-0fc1-11e7-8dfb-1cc1feb2aefe.png)

**Comment by Nazarah** [comment]
We have to keep in mind that right now, Media content cards get rendered based on the size of their preview. So if we add pagination as well as letting organization manager to define the number, this might have effect on the look and feel of the media content panel.
Right now, in API profile page, 4 contents  are shown in each row. Should we have a dropmenu in Settings tab having numerics that are multiple of 4? Or organization manager would be able to give manual entry to that number?

**Comment by matleppa** [comment]
Displaying the media items is implemented such a way, that same functionality is used both with media items attached to APIs and attached to Organizations.
 Thus changes in concerning Organizations easily affect also to APIs.

Should there be:
A) only one setting affecting pagination of related media in Organization case and 
     i) same setting affecting in APIs case
    ii) no setting for APIs, but a hard-coded default value 

B) one pagination setting affecting Organization case and 
    i) another one affecting Organization case
   ii) no setting for APIs, but a hard-coded default value 

C) pagination setting  of related media items for each individual Organization and 
    i) pagination setting of related media items for each individual API
   ii) no setting for APIs, but a hard-coded default value
