### ISSUE TITLE
RSS feed about APIS: triggered by adding an API

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2310]
# Goal

Allow information about organization APIs to be harvested to outside systems like RSS readers Zapier through creating a RSS feed about of all organization APIs, newest on top, oldest as last.

Open issue: level of detail about APIs

# Definition of done
* [ ] Searching for RSS feed generator
* [ ] Selecting schema(s) for joining attributes
* [ ] Querying for APIs related to an organization
* [ ] Passing the result of query in XML format 

# Resources
- [Node RSS](https://github.com/dylang/node-rss) - library for generating RSS feeds

**Comment by bajiat** [comment]
@jawidahmadi has promised to mentor.

**Comment by brylie** [comment]
@bajiat the description for this task is somewhat ambiguous, as is also evident by the changes made in the PR.

If I am understanding the task correctly, we want **an RSS feed for each Organization**, which will **return APIs belonging to a single organization**. Is this correct?

**Comment by bajiat** [comment]
Yes, RSS feed for APIs of each organization. So each organization has its own feed,.

Details to be included:
- Name (in Atom this is 'title')
- URL - The URL is either the API URL or the proxy URL, depending on whether the API is connected to a proxy (in Atom this is 'link')
- Description (In Atom this is 'summary')
- Date and time (In Atom this is 'updated', use the Atom format)
