### ISSUE TITLE
Pinning featured APIs to the top of the API catalog

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2311]
# Goal
* Organization manager can select certain APIs to be "Featured APIs" for this organization.
* The Featured APIs are displayed at the top of API area on the organization page, either as their own row or as first APIs.
  * If the APIs are sorted by name Featured APIs always precede any other APIs.  sorting by name means Featured APIs sorted by name followed by all other APIs sorted by name. Likewise for sorting by time added.
* Have a small visual indication of featured API on the API card.

# Definition of done
* [x] all users can see the featured API cards shown in own area above the area for all APIs
* [x] maximum amount of featured APIs per organization at a time is 4
* [x] organization manager can see a pin button in the upper right corner of API card
* [x] by pressing pin button the API card is marked as featured/not featured, which updates both screen view and the list of featured APIs
* [x] list of featured API card is attached to Organization
* [x] if featured API is deleted or disconnected from Organization, it is removed from Organization's featured API list

# Wireframe
Here is the new card
![cardapidesign prototypepin](https://cloud.githubusercontent.com/assets/17976243/24292535/69e9357e-1096-11e7-8bac-2a06062d6f43.png)
A Thumbtack icon appears at the corner of the API card.
we can use the following font [Awsome icon](http://fontawesome.io/icon/thumb-tack/)
Color: #555555
on mouse hover, there can be a tooltip telling organization manager about the featured API option.
When the icon is clicked, the API becomes featured and the icon gets opaque
![cardapidesign prototypepinned](https://cloud.githubusercontent.com/assets/17976243/24292600/b1b21eb6-1096-11e7-86e9-13d8319ca27a.png)

appearance of featured API in the API section in organization profile.
This should maintain the sorting rules explained above
![featuredapi](https://cloud.githubusercontent.com/assets/17976243/24353620/07e83f4c-12f7-11e7-87e1-136f3b07b0ea.png)

**Open question**: would normal user viewing organization profile would see the opaque pin version of the API card that indicates the API to be a featured one?

**Comment by Nazarah** [comment]
Need clarification:
1. suppose there are three APIs: A1, A2 and B1.
A2 and B1 are featured APIs.
So when APIs are "sorted by name", would they appear as the following: A2, B1, A1?

2. Are we implementing sorting functionality for APIs in Organization Profile Page? 
Or this is something the manager would configure from the Settings tab?
(i.e. a new panel that defines how the APIs would be sorted: name, time added, starrating, etc.)

3. Would organization manager be able to make the APIs "featured" from the API cards themselves? (e.g. a clickable icon on the card?)

**Comment by bajiat** [comment]
@Nazarah 
1. Exactly, like you said: A2, B1, A1. Featured always comes before other APis. Each group (featured, other) needs to be sorted internally by the selected sorting criteria.
2. Yes, there is a task for sorting.
3. That would probably be the easiest way to select featured apis.

**Comment by Nazarah** [comment]
@bajiat @brylie added a sample of the new card.
Please have a look and tell me about your feedback.

**Comment by bajiat** [comment]
I like your suggestion. The icon clearly communicates that this API is pinned to the top. The only thing I'm worried about is that are we having too many items in one card at the mo.

**Comment by Nazarah** [comment]
I understand your concern.
We can always decide if we wish to remove/hide some elements out of the card.
Another alternative for this can be made in Settings tab
Under Content Management Section, we can provide a dropmenu with check box that would show all connected APIs to that organization.
On checking, the respective API would become Featured.
For this approach, we can show the featured APIs cards in a different color tone and can convey this with help text in Organization Details tab.

**Comment by brylie** [comment]
What about a drag and drop on the Organization Profile  page? We haven't worked with drag and drop, but it is very intuitive for users.

E.g. there would be a 'featured' section above the APIs listing. When no APIs have been featured for that organization, the featured section is empty (shown only for managers). When a manager drags an API from the APIs listing into the Featured section, it gets added to the Featured AIs list.

Behind the scenes, we would store the Featured API IDs as an array of strings.

**Comment by Nazarah** [comment]
Personally I'd like to go with the pin option on API card.
Yeah there is the concern that we are putting too many information over the card, but we can always redesign the card to include only ,minimal required info.
Also I have concern about drag and drop feature in mobile view.
It wouldn't be usable to perform this action due to the limitation of screen size and browser performance in mobile screen.
On the other way pinning is simple and only one click.
We can always mention the size of the card appearance in mobile view when we are implementing this feature. so that pin (to be developed) and bookmark (current) functionalities are big enough to be manipulated with touch screen.

**Comment by philippeluickx** [comment]
What problem are we solving with this feature and is that problem big enough?
To me this feels like feature bloat.

It might become a valid concern at some point, but I think this just shouldn't get top priority at this moment. I'd love to get some customer requests before implementing this.

**Comment by Nazarah** [comment]
For drag and drop, we need to consider that APInf can be used to mobile phones as well.
So the drag and drop will have usability issues to function with small screen size and browser performance.
With the concern about too many contents in API cards, we can always redesign the card to include the minimal information and functionality needed.
Besides for the mobile view, we can always make sure the the page is rendered in the mobile screen in such a way that the Pin icon is big enough to be tapped to work with.

**Comment by Nazarah** [comment]
For showing featured APIs, we should include an info tip explaining how the sorting works with featured API.

**Comment by bajiat** [comment]
@Nazarah Update with new card design

**Comment by Nazarah** [comment]
@bajiat @matleppa : here is the Pinning option in the new API card
* **API Card Unpinned**
![apicardunpinned](https://cloud.githubusercontent.com/assets/17976243/24693236/475197a6-19e5-11e7-84c9-664800ebc114.png)
<br></br>
<br></br>
* **API Card Pinned**
![apicardpinned](https://cloud.githubusercontent.com/assets/17976243/24693269/6c6e3cb0-19e5-11e7-83cc-6a6fc67b6a1b.png)

I don't yet have any image of how the card is going to be.
I designed it based on what I remember from the review of the card.
Plase confirm with @nnn

**Comment by bajiat** [comment]
If we would like to define the maximum number of Featured APIs, we could also consider "plan B"
# API card
- API pin is visible 
  - only on organization page
  - if current user can manage organization

# When the pin is pressed
- an array of FeaturedAPIs on organization document is updated. There is a maximum number of 4 API ids in array. 
- if the maximum was already reached, the array is not updated and user gets an SAlert about maximum number being reached

# When an organization page is opened, Featured APIs are visible as their own section, if there are any (= ids in the array)

Alternative option would be a setting for Featured APIs available on Settings tab. Github allows admin user to select Featured repositories from a dropdown list and there is a maximum number.

@Nazarah Do you prefer to use the pin or a setting, if we try to achieve the max number of featured apis? 

<img width="346" alt="github customize pinned repos" src="https://cloud.githubusercontent.com/assets/11626388/24954814/8b99b700-1f89-11e7-9c57-6d38cd294b3a.png">

**Comment by bajiat** [comment]
The dropdown list could perhaps look like this:

<img width="171" alt="bootstrap-multiselect" src="https://cloud.githubusercontent.com/assets/11626388/24954911/ed86360a-1f89-11e7-9375-a763c116440b.png">

**Comment by brylie** [comment]
After discussion, I propose we consider the following data model:
![screenshot_20170412_154328](https://cloud.githubusercontent.com/assets/17307/24958087/c88ada7e-1f96-11e7-81cc-b6bb197ae3e6.png)


This might make it easy to remove 'featured' APIs in the following scenarios:
- un-featuring an API
- deleting an API
- deleting an Organization

**Comment by Nazarah** [comment]
after  a discussion with @matleppa we decided the following
1. APIs would appear with pins on cards on Organization profile.
2. There would be 2 sections: Featured APIs and below All APIs
each section label should have a field to indicate the number of items  (i.e. APIs) contained within them.
3. On clicking Pin icon on API card, the API would appear both in Featured APIs section and All APIs section. On Unpinning action from any section, the API in question will be removed from the Featured APIs section
4. If no Featured APIs are available to show, we should either hide the section or show the follwoing text in italic: No API is available below the section label.

**Comment by brylie** [comment]
@matleppa and I just spoke and agreed that it is a good idea to just store the `featuredApiIds` array directly in the Organization document. This is mainly for **simplicity**, since we don't have to introduce a whole new collection to the project (with all the accouterments that accompany any colleciton).

**Comment by matleppa** [comment]
While implementing this feature, I've began to think that the sorting do not necessarily need to affect the  featured API cards, because there is only maximum of 4 of them.  Sorting by name might be enough, there is no additional value in sorting them by other criteria.

In addition to that, the implementation stays simpler, when featured API functionality is encapsulated as its own. This way the sorting and filtering buttons remain as a part of presentation of All APIs both on screen and also by functionality.
