### ISSUE TITLE
Add sorting for APIs on Organization page

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2312]
# Goal
* User viewing the Organization page can select the sorting for the APIs on the organization page: time added and alphabetical (internationalized) sorting. 
* Simplify the sorting widget used on the API catalog page.
* Make sure the simplified widget can be later reused in the API catalog.)

# Definition of done
* [ ] To be defined by assignee

# Wireframes
**Version 1**
![organizationapisorting1](https://cloud.githubusercontent.com/assets/17976243/24288057/a3ca85d4-1084-11e7-9c6d-f3528b2be8c7.png)
* The API section under Organization profile Details tab has now a "Sort by" drop menu. (beside filtering button)
* The default sorting option is "Names (A - Z)"
* The ascending and descending buttons are removed by simply placing sorting option types in the drop menu (e.g. Names (A - Z), Newest Created, Bookmarks and Ratings.)
![organizationapisorting](https://cloud.githubusercontent.com/assets/17976243/24352218/588e40dc-12f1-11e7-9069-f0af20efc05e.png)

**Version 2**
Got this idea from [this article](https://www.safaribooksonline.com/library/view/mobile-design-pattern/9781449368586/ch04.html)
Since we have 4 sorting types, we can show them as buttons.
Selecting one option would highlight the button and others would remain in their normal states.
This reduces no. of clicks and increases visibility.
![organizationapisorting2](https://cloud.githubusercontent.com/assets/17976243/24352227/679a8810-12f1-11e7-80fb-b3a9cd9d58de.png)

**Open Question:** Should we have cookies to remember users choice of sorting? s.t. when they revisit the page, they see the APIs sorted with the previously selected option?

**Comment by bajiat** [comment]
One idea for simplifying the widget is removing the ascending and descending sorting options. Time added would always be sorted newest first. Alphabetical sorting would be always ascending (e.g. in English this would mean only A > Z, not Z > A).

**Comment by Nazarah** [comment]
@bajiat @brylie added the wireframes. Please have a look and give your feedback.

**Comment by bajiat** [comment]
Perhaps we could use shorter names: Bookmarks instead Number of bookmarks, Rating instead of Average rating?

**Comment by Nazarah** [comment]
@bajiat Done. Please let me know which version we can go with.

**Comment by bajiat** [comment]
I would go with the drop-down menu even if it requires more clicks. It just takes so much less space. Just consider, which is the more sensible default: name or newest created.

**Comment by bajiat** [comment]
'Newest created' should be replaced by 'Latest'
