### ISSUE TITLE
Frontpage footer: click on SignUp/SignIn links shows 404 error message

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2316]
# Steps:  
1.Visit https://apinf.io   v 0.41.0  
2.Go to frontpage footer  
3.Click on  'SignIn' or 'SignUp' links  

# Result
shows 404 error 'Page Not found'  

# Screenshot  
![apinf_frontpage_signin_link](https://cloud.githubusercontent.com/assets/13309358/24032519/1b3b9c14-0af1-11e7-9944-de02226ae2e2.PNG)    

![signin_signup_link_404error](https://cloud.githubusercontent.com/assets/13309358/24032551/4c66af22-0af1-11e7-9ef1-5acb57da94c4.PNG)

**Comment by marla-singer** [comment]
@saralavanip @bajiat It's resolved on nigtly.apinf.io. Must be available for staging after release
