### ISSUE TITLE
Organization view: Click on any API shows user info. text momentarily

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2320]
# Steps 
1.Visit https://apinf.io  v 0.41.0 
2.Login as admin/owner  
3.Click on Organizations
4.Go to any organization
5.Select and click on any API 

# Findings  
- shows info message "This Organization doesn't have any connected APIs " momentarily 
- Also reproducible on nightly V 0.41.0

**Comment by marla-singer** [comment]
The miracle doesn't happen. Reopen it

**Comment by bajiat** [comment]
Related to #2486 - could this be resolved by the suggested fix?

**Comment by bajiat** [comment]
@55 See if this is fixed by  or related to #2486
