### ISSUE TITLE
API profile page: Organization name should be a link

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2321]
# User story
As an end user
I want to easily access organization page from the API page.

# Goal
If an API has been connected to an organization, the header area of the API profile contains the name of the organization. The organization name should be a link to the Organization page.

<img width="517" alt="organization name should be link" src="https://cloud.githubusercontent.com/assets/11626388/24036233/595136b6-0b01-11e7-8db6-c9bd88a163e1.png">

**Comment by nnn** [comment]
Interested.
