### ISSUE TITLE
Organize Apinf community Code of Conduct review

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2338]
As members of the larger Apinf community, we are responsible for treating each other with respect and acceptance. To this end, we have adopted a community Code of Conduct document, which sets guidelines for appropriate community conduct.

Since the Code of Conduct is relatively new, we need to review it as a team, so we understand and can modify the document to meet our needs.

# References
- [Apinf Contributor Code of Conduct](https://github.com/apinf/platform/blob/develop/CODE_OF_CONDUCT.md)
- [2017-03-14 Apinf team reflection](https://github.com/apinf/docs/blob/master/docs/organization/minutes/2017-03-14-team-self-reflection.md)

**Comment by bajiat** [comment]
@brylie Please add a link
