### ISSUE TITLE
Re-design the API card so that logo shapes can be preserved

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2342]
Re-design the API card so that logo shapes can be preserved. Maximum height and width needs to be defined, though.

### Definition of done
- [x] Create the new style for API card and reviewed it

**Comment by bajiat** [comment]
@Nazarah Please comment this issue.

**Comment by philippeluickx** [comment]
My suggestions:
- Keep it as square. Inform the user on upload what the adviced size is (e.g. 500x500 px)
- Use a library to turn any other type of image to a 500x500 square - e.g. https://github.com/jwagner/smartcrop.js/
- Make sure we cache some of the picture sizes automatically. E.g. if we use a 50x50 picture in the cards, then cache that
