### ISSUE TITLE
Upgrade Swagger UI to 3.x

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2349]
Swagger UI 3.x was released on 2017-03-19. We should consider upgrading to the recent release ASAP, for improved features and possibly stability.

- https://www.npmjs.com/package/swagger-ui

# Related
#2211 - swagger UI documentation sections not expanding

## Upstream
- [Ampersand character being escaped in rendered documentation](https://github.com/swagger-api/swagger-ui/issues/2700)

**Comment by bajiat** [comment]
@marla-singer Would you be interested in another Swagger task as well? This should perhaps be completed before #2372.

**Comment by marla-singer** [comment]
@bajiat Perhaps it will not be able completed before 2373 task.
First at all,we are using `swagger-ui-browserify` package in our project which is **based on** `swagger-ui`.
How I see this task:
1. Install `swagger-ui` v 3.x and tested it
2. If it doesn't work, will update `swagger-ui` package version in `swagger-ui-browserify`
3. Tested `swagger-ui-browserify` package with new `swagger-ui` version
4. If everything is okay, push request changes to owner `swagger-ui-browserify`
5. Otherwise try to fix it

**Comment by brylie** [comment]
@marla-singer how does your idea affect the task estimate?

**Comment by marla-singer** [comment]
@brylie Well, directly-proportional. My estimate is 1-5 days
1 day: Everything is okay and `swagger-ui` package works as expected then I will remove `swagger-ui-browserify` package and update `swagger-ui`
5 days: Nothing is okay and I will implement a new realization for `swagger-ui-browserify`package for Swagger UI v 3.0

**Comment by marla-singer** [comment]
@brylie @bajiat 
1. Couldn't use it as npm package. Meteor starts with errors.
2. The new Swagger version doesn't have any examples how it can be used. 
3. Not sure that the new version is more stabled as previously. For example, this issue https://github.com/swagger-api/swagger-ui/issues/2816

**Comment by brylie** [comment]
What kind of errors did you get with the NPM package?

**Comment by marla-singer** [comment]
@brylie
```
modules.js?hash=bddc49d…:57580 Uncaught TypeError: Cannot read property 'prototype' of undefined
 at extend (modules.js?hash=bddc49d…:57580)
 at modules.js?hash=bddc49d…:57595
 at modules.js?hash=bddc49d…:57603
 at meteorInstall.node_modules.yaml-js.lib.composer.js (modules.js?hash=bddc49d…:57839)
 at fileEvaluate (modules-runtime.js?hash=0969a31…:207)
 at require (modules-runtime.js?hash=0969a31…:130)
 at modules.js?hash=bddc49d…:57307
 at meteorInstall.node_modules.yaml-js.lib.yaml.js (modules.js?hash=bddc49d…:57566)
 at fileEvaluate (modules-runtime.js?hash=0969a31…:207)
 at require (modules-runtime.js?hash=0969a31…:130) 
```
Related issue https://github.com/swagger-api/swagger-ui/issues/2849

But I am continuing to investigate troubles with NPM packages. The current result is:

2. Swagger-UI library needs a lot of dependencies like `react, react-redux, react-addons-perf, react-collapse, react-dom, react-height, react-hot-loader, react-immutable-proptypes and etc`. 
I created empty Meteor project and made `npm i -S swagger-ui` after that `node_modules` contains 285(!) folders.

2. Swagger-UI uses `node-gyp` [that is installed not so easy ](https://github.com/nodejs/node-gyp#installation). I've got a long warning list during installing swagger-ui package, you can see output [here](https://pastebin.com/fcyW74pr). Then it appears all time when I'm installing any package.

1. Swagger-UI is written using React framework. New swagger needs to use React Component for rendering layout. This React Component has input parameters as others React components and renders in layout. I suppose we need to write this component by hand in our project to rendering Swagger layout.

4. The only one method I could find to start up Swagger it is to add swagger as external links.
```html
  <script src="/swagger-ui-bundle.js"></script>
  <script src="/swagger-ui-standalone-preset.js"></script>
```
In this case it works
![joxi_screenshot_1491416493764](https://cloud.githubusercontent.com/assets/20643403/24720458/dfff60f4-1a45-11e7-88ba-33d674929289.png)

**Comment by brylie** [comment]
This sounds good. What would the changes to our project look like?

**Comment by marla-singer** [comment]
@brylie The assumed changes are:

1. Remove `swagger-ui-browserify` npm package
1. Remove `swagger-ui` npm package
1. Add scripts `swagger-ui-bundle.js` and `swagger-ui-standalone-preset.js` in folder  `/public`
1. Fix style for new Swagger view
1. Create issue about adding realization feature in new Swagger: Try-out methods, updating proxy base path and proxy host, insert API key into Swagger

**Comment by bajiat** [comment]
Is this in progress? Will you open the new issues?

**Comment by marla-singer** [comment]
@bajiat Nope. I'm waiting for feedback from @brylie

**Comment by brylie** [comment]
I think the changes are OK, but we have just been struggling with Swagger UI in general. It seems like we may need to write 'kludgy' fixes to control the try out methods and insert API key into Swagger. By 'kludgy', I mean somewhat *inelegant* and *brittle*, although I could be wrong altogether.

@marla-singer what are your thoughts on how we would handle the three related issues?
- try-out methods
- proxy base path
- API key
