### ISSUE TITLE
Add a transparent panel at Organization Profile Header to display textual Information

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2352]
# Issue
Since we will be supporting organization cover photo, this might conflict with the visibility of textual information that is shown on Organization header. This would also affect on the visibility of social media platform that would be included in future. So we need some way to make the information visible to users.

# Suggestion
showing organization textual information and social media platform logos on transparent panes.
This would increase the visibility even in the worst case a cover photo with a lot of details is uploaded.
The panel color is #000000 with 80% Opacity rate

* Organization profile with no logo/cover picture
![organizationsettings4none](https://cloud.githubusercontent.com/assets/17976243/24240655/176220f8-0fbb-11e7-9a8e-eea8b8b1296c.png)

* After adding logo/cover picture
![organizationsettings4all](https://cloud.githubusercontent.com/assets/17976243/24240676/2e2d2ecc-0fbb-11e7-903d-cb1025001545.png)

**Comment by bajiat** [comment]
Related to #2068

**Comment by bajiat** [comment]
Closing. The cover photo and the text box (header area) on the Organization page will be separated.
