### ISSUE TITLE
Nightly: Can't upload jpeg image as cover photo in the site

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2354]
Tried to upload a picture taken on monday photo session.
The picture format is jpeg.
On selecting the picture from desktop, S-alert appears mentioning the supported format.
Picture doesn't get uploaded at all

**Comment by bajiat** [comment]
I was able to upload a cover picture from the same photo session (jpg, 630 kB).

**Comment by bajiat** [comment]
@Nazarah @marla-singer 
Since this is not a bug and a photo can be uploaded, should we close this? Do you want to open another issue for any size restrictions or user texts?

**Comment by marla-singer** [comment]
As for me, we can close it

**Comment by Nazarah** [comment]
closing the issue. A related usability issue is reported in #2357
