### ISSUE TITLE
Branding Page: No indication of max size of cover photo

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2358]
# Issue
Right now, there is no information given about the max size of the site cover photo. So if User uploads a photo that exceeds the max limit, the photo doesn't get uploaded and the s-alert show incomplete message about it.

# Enhancement
* [ ] Add help text close to cover photo field indicating max size and supported format
* [ ] add a new s-alert showing message that the max size limit exceeded and to upload a photo which is within the max size.

**Comment by bajiat** [comment]
+1

**Comment by deligence-dharmendra** [comment]
Hi @Nazarah 
I have gone through the existing code and functionality , There is no rules define for cover photo max size,
Please advise me.

**Comment by Nazarah** [comment]
@deligence-dharmendra after consulting to @matleppa I suggest you two try out the following:

1. create a new field defining max limit of cover image under the schema for Branding DB.
The field type would be integer and field value would be the maximum size of the cover image allowed to be uploaded. This option would allow site admin to configure the value from the Branding page.

Or,

2. The maximum size limit could be hard coded and the size of the uploaded image is compared against the hardcoded value. If the uploaded image exceeds the hardcoded value, then S-alert appears telling the user that max limit has been exceeded and the file size needs to be within the max size.

I am also tagging @marla-singer to tell her opinion on the provided suggestions.

**Comment by Nazarah** [comment]
@deligence-dharmendra can you please also investigate another issue? I am trying to upload a .jpg image with size 5.9 MB. In Branding schema, .jpg extension is in the allowed type for cover image. However, I am unable to upload the file and s-alert tells only .jpg, .png and another extension is supported.
I am adding the GIF file here.
If you want, I can open another issue.
![tuxntqfeg4](https://user-images.githubusercontent.com/17976243/32771372-249d795a-c92b-11e7-9e9b-7a3dcfa74f5c.gif)

**Comment by marla-singer** [comment]
@Nazarah The last gif doesn't relate to image size. I think the problem is in extension (as the alert message says). Maybe your picture has extension as JPG or JPEG but the code expectes `jpg` or `jpeg`. JPG isn't the same as 'jpg' and JPEG isn't the same as 'jpeg'
That's all

**Comment by Nazarah** [comment]
@marla-singer would you consider adding the additional extensions JPG and JPEG in the CoverImageField?
I am thinking the scenario that Site admin might get confused with the case sensitivity of the extensions and can assume s/he can upload supported extensions regardless their case (jpg or JPG and jpeg or JPEG).

**Comment by marla-singer** [comment]
> @marla-singer would you consider adding the additional extensions JPG and JPEG in the CoverImageField?

Yes, kind of. Need to improve our function that checks a file extension. I will open an issue and fix it during today.



What about max size of picture. My opinion is to start from the easy way and I pick the second point and realise **"Add help text close to cover photo field indicating max size and supported format"**

> The maximum size limit could be hard coded and the size of the uploaded image is compared against the hardcoded value. If the uploaded image exceeds the hardcoded value, then S-alert appears telling the user that max limit has been exceeded and the file size needs to be within the max size.

**Comment by deligence-dharmendra** [comment]
Hi @marla-singer, @Nazarah 
I have assign the max file size 10 mb  hard coded value.is it ok?

**Comment by Nazarah** [comment]
@deligence-dharmendra good job! Lets go with this for the time being. Also please consider showing an alert if user still uploads a a file bigger than 10 MB despite the help text telling otherwise.
@marla-singer thanks for your feedback.
