### ISSUE TITLE
Misaligned text of feedback type

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2359]
**Descriptions:**
When type is **Feature request**, the type text is misaligned in Suomi view

### Steps

1. Login
2. Select any API -> Navigate to Feedback tab
3. Click on the button "Send Feedback"
4. Fill up the form and select "message type" as **Feature request**
5. Submit form
6. Change the language to Suomi

### Expected 
- The elements are misaligned.

![joxi_screenshot_1490354280899](https://cloud.githubusercontent.com/assets/20643403/24292089/d06576a4-109c-11e7-9192-60f3e36d5273.png)

**Comment by bajiat** [comment]
A general rule of thumb when allocating space for text is that it can expand 20-30% when it is translated. So it might be a good idea if we would allow some expansion space in markup for text, if possible.

**Comment by bajiat** [comment]
@marla-singer Can you add steps to reproduce?

**Comment by marla-singer** [comment]
@bajiat Done

**Comment by Vellames** [comment]
@mauriciovieira ready to review
