### ISSUE TITLE
Issue with Try Out button in Swagger UI

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2372]
# Issue
Try Out button in swagger editor in documentation tab seems not working.
The API endpoints, URL, proxy and proxy base path are defined correctly.
Results can be obtained using Postman, but swagger UI seems not working.

# Reproduction
* Create an API with the following information
  - API URL: http://makeup-api.herokuapp.com
  - Proxy: Nightly Umbrella
  - Proxy basepath suffix: /makeup-api/
  - API Basepath suffix: /api/v1/products.json
  - Example Screenshot:
![image](https://cloud.githubusercontent.com/assets/17976243/24403489/cd8869a6-13c5-11e7-8a37-3bccafc6a86e.png)
  - get API key and then disable API key requirement
  - upload the json file given as (2nd) Comment
  - enable GET method
  - Try out the GET method with the this field value: **product_type** = _lipstick_
![image](https://cloud.githubusercontent.com/assets/17976243/24403756/02b560c4-13c7-11e7-8df4-550cf4ec1355.png)

# Result
* the curl request doesn't return any value
![image](https://cloud.githubusercontent.com/assets/17976243/24443634/10187c92-146c-11e7-8e95-8b7c1a3b79dd.png)

* tried the same request using postman and the request returned search result for "lipstick"
![image](https://cloud.githubusercontent.com/assets/17976243/24443655/25379ab8-146c-11e7-9877-f044c7fca711.png)

# Consideration
* check out the json file to see if it has something to do with the way Definition is written

# API to test with:
https://nightly.apinf.io/apis/makeup-api

**Comment by Nazarah** [comment]
{
    "swagger": "2.0",
    "info": {
        "title": "MakeUP API",
        "description": "Be beautiful with readlily available Makeup Info! ;)",
        "version": "1.0.1"
    },
    "host": "makeup-api.herokuapp.com",
    "schemes": [
        "http"
    ],
    "basePath": "/api/v1",
    "produces": [
        "application/json"
    ],
    "paths": {
        "/": {
            "get": {
                "summary": "Product Types",
                "description": "The Products endpoint returns search information about *MakeUP*  products based on different brands. Currently the following brands are available - almay, anna sui, annabelle, benefit, burt's bees, butter london, cargo cosmetics, china glaze, covergirl, dalish, dr. hauschka, e.l.f., essie, iman, l'oreal, marcelle, maybelline, milani, mineral fusion, misa, mistura, moov, nyx, orly, pacifica, physicians formula, piggy paint, pure anada, revlon, salon perfect, sante, sinful colours, smashbox, stila, suncoat, wet n wild, zorah. The response includes the display name and other details about each product, and lists the products in the proper display order.",
                "parameters": [
                    {
                        "name": "product_type",
                        "in": "query",
                        "description": "The type of makeup being searched for (i.e. lipstick, eyeliner). Will return a list of all products of this type",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "product_category",
                        "in": "query",
                        "description": "Sub-category for each makeup-type. (ie. lip gloss is a category of lipstick). Will return a list of all products of this category",
                        "type": "string"
                    },
                    {
                        "name": "product_tags",
                        "in": "query",
                        "description": "Options each product could be tagged with. (ie. vegan). each product can have multiple tags. If tags exist it will be in the product types under 'By Tag'. Will return a list of products filtered by all tags indicated",
                        "type": "string",
                        "format": "list"
                    },
                    {
                        "name": "brand",
                        "in": "query",
                        "description": "Brand of the product. Will return all products for each brand",
                        "type": "string"
                    },
                    {
                        "name": "price_greater_than",
                        "in": "query",
                        "description": "Will return a list of products with price greater than indicated number (exclusive)",
                        "type": "number",
                        "format": "float"
                    },
                    {
                        "name": "price_less_than",
                        "in": "query",
                        "description": "Will return a list of products with price less than indicated number (exclusive)",
                        "type": "number",
                        "format": "float"
                    },
                    {
                        "name": "rating_greater_than",
                        "in": "query",
                        "description": "Will return a list of products with a rating more than indicated number (exclusive)",
                        "type": "number",
                        "format": "float"
                    },
                    {
                        "name": "rating_less_than",
                        "in": "query",
                        "description": "Will return a list of products with a rating less than indicated number (exclusive)",
                        "type": "number",
                        "format": "float"
                    }
                ],
                "tags": [
                    "Products"
                ],
                "responses": {
                    "200": {
                        "description": "An array of products",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Product"
                            }
                        }
                    },
                    "default": {
                        "description": "Unexpected error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Product": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string",
                    "description": "Unique identifier representing a specific makeup product for a given Category, type and/or brand"
                },
                "description": {
                    "type": "string",
                    "description": "Description of the makeup product."
                },
                "product_display_name": {
                    "type": "string",
                    "description": "Display name of makeup product."
                },
                "product_brand": {
                    "type": "string",
                    "description": "Name of the brand the makeup product belongs to"
                },
                "product_type": {
                    "type": "string",
                    "description": "Type of the makeup product. e.g. Lipstick, Eyeshadow, etc."
                },
                "product_category": {
                    "type": "string",
                    "description": "Category within a specific makeup type. e.g. Powder blush or Cream blush"
                },
                "product_tag": {
                    "type": "string",
                    "format": "list",
                    "description": "tags associated with the specific makeup product"
                },
                "image": {
                    "type": "string",
                    "description": "Image URL representing the product."
                },
                "price": {
                    "type": "number",
                    "format": "float",
                    "description": "price of the makeup product"
                }
            }
        },
        "Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "format": "int32"
                },
                "message": {
                    "type": "string"
                },
                "fields": {
                    "type": "string"
                }
            }
        }
    }
}

**Comment by Nazarah** [comment]
Original Documentation: http://makeup-api.herokuapp.com/

**Comment by brylie** [comment]
Might be fixed by #2349

**Comment by bajiat** [comment]
@marla-singer Do you think this could be related to #2388 ? Or is there another issue with Swagger Try out?

**Comment by marla-singer** [comment]
@bajiat Definitely, it's different task

**Comment by brylie** [comment]
Good find @marla-singer!

**Comment by bajiat** [comment]
Haven't we struggled with the https/http already quite a few times?

**Comment by kyyberi** [comment]
Since the http without s is the problem, then we should not allow uploading of such API specs which use HTTP. User should be notified that we do not support HTTP, but only HTTPS. Solution is to parse spec upon upload or when URL is given and then check if HTTPS is used. (Better UX)

User should not notice that at this point the way we discovered it. (Really bad UX)

**Comment by bajiat** [comment]
@marla-singer Could you work on this together with @Nazarah to find the most optimal solution?

**Comment by marla-singer** [comment]
@bajiat Sure

**Comment by bajiat** [comment]
Can you estimate this together?

**Comment by marla-singer** [comment]
@kyyberi Can you please help with format help text for developers?
I thought up "Application platform support only HTTPS protocol. Specification of documentation must have schema `https`"

**Comment by Nazarah** [comment]
@marla-singer just want to understand this scenario: what would happen id an API mentions both http and https protocols in the swagger documentation but the API endpoint has only http protocol. (check the above swagger documentation and original API description [here](http://makeup-api.herokuapp.com/))

**Comment by marla-singer** [comment]
@Nazarah Well, our platform will check it "Correct document" but requests will not work. And we can't do anything because it is liability of API owner

**Comment by Nazarah** [comment]
@marla-singer I understand your point. However, Fo such scenario, I'd like to alert user about this possible action. That when they click Try Out button with http as their endpoint protocol, APInf detects the request and rejects it as well as alerts the user about the used protocol. Also may be some suggestion to modify the end point. Would it work?

**Comment by marla-singer** [comment]
@Nazarah I thought about it tonight. I suggest allowing API owner to download any correct documentation file with http schema too. And notify API owner and users that **"Application platform supports only HTTPS protocol. Perhaps request calling via Swagger will work incorrectly."**

**Comment by Nazarah** [comment]
@marla-singer excellent!
A minor change in the 2nd line of the alert text:
"**Requesting via Swagger might not work correctly.**"
