### ISSUE TITLE
Add transparent layer on top of cover photo

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2373]
# User story
As an APInf admin, 
I want users to be able to read the site title and the site slogan.

# Goal
Whenever user uploads a cover photo, an transparent layer is added on top of the photo to maintain readability of the text. The area of the transparent layer should match the cover photo area.
To match with other branding elements, the transparency color should be taken from the primary branding color. Transparency level should be XX.
Contrast between text (secondary branding color) and the layer color.

### Definition of done
- [x] New input  fields for overlay color and transparency on Branding page
- [x] New fields for overlay color and transparency values in Branding schema
- [x] Cover image overlay matches the image area
- [x] Cover image overlay color and transparency changes according to given values

# Wireframe
1. In Branding settings, two new fields, "Cover Image Overlay" and "Overlay Transparency" appear under Colors panel.
"Cover Image Overlay": standard color picker used in APInf
"Overlay Transparency": selects the transparency of the overlay
<br></br>
<br></br>
![brandingpage4](https://cloud.githubusercontent.com/assets/17976243/24649145/bd787c2c-192e-11e7-85b4-c2ce68d225a9.png)

2. After saving the selected color and transparency rate, the added overlay appears on the homepage over site photo.
<br></br>
<br></br>
![frontpage1-1](https://cloud.githubusercontent.com/assets/17976243/24649211/fdf89322-192e-11e7-9bf6-42098f946738.png)
<br></br>
<br></br>
![mobile1](https://cloud.githubusercontent.com/assets/17976243/24649232/0b938db6-192f-11e7-9340-fcf666e2ed67.png)

**Comment by Nazarah** [comment]
@bajiat @matleppa @jawidahmadi should we consider of providing an opacity/tranperancy selector in the branding page for this feature?
The wireframes I designed was focused on the color #000000 with opavity 80%
In photoshop tutorial video, I've also seen people are usually using the color black or #000000 and then modifying the transparency or blurriness of the photo.
I am yet not 100% confident about having the same color as that of branding to choose for transparency layer.

**Comment by matleppa** [comment]
Is it OK to let user to decide both cover image overlay color and opacity?

**Comment by Nazarah** [comment]
@matleppa Added the wireframes according to your suggestion.
The field names should be "Cover Image Overlay" and "Overlay Transparency".
