### ISSUE TITLE
Search box and button

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2374]
# User story
> As a mobile user, 
I want to be able to activate the search box for writing and to press the search button
so that I don't have to zoom in to the page to do a search.

# Goal
* Add more height to the search box
* Remove the border around the search bar
* Move the search button below the search box and make it larger
* Color of search button ?
* If possible, implement search in a reactive manner

# Wireframe
Laptop View
![frontpage1-1](https://cloud.githubusercontent.com/assets/17976243/24896345/2831bc7c-1e9d-11e7-8ff6-7fe9f263fc84.png)
<br></br>
<br></br>
Mobile
![mobile1](https://cloud.githubusercontent.com/assets/17976243/24896374/47259004-1e9d-11e7-8af7-130142e086e6.png)

**Comment by Nazarah** [comment]
should we consider a future issue to customize default colors for buttons?

**Comment by bajiat** [comment]
Comment from @nnn Optionally, check for search reactivity from file commits.

**Comment by nnn** [comment]
Interested.

**Comment by Nazarah** [comment]
@nnn added the wireframes in the issue.
Please have a look and let me know the if there is some alteration u want to implement.
also consider this issue while implementing: #2418 
This is regarding to a separate controller to change button colors and overview panel in front page
