### ISSUE TITLE
APIs as first section below cover photo

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2375]
# User story
As an APInf admin
I want users to see interesting (newest) APIs at the top of the page
so that they want to see more and visit the catalog.

# Goal
* APIs can be found as the first section after the cover photo.
* If possible, the size of the API card is adjusted for the mobile view (one card per row) to make it more easily clickable
  * see if you can use the same card, but use 12 columns in extra small screen size
* Number of APIs to be shown: 8
* There is no underlining or line below the header "Latest APIs"
* There is button to see "More APIs". If the user presses the button, they are redirected to the Catalog
  * Button color comes from Branding settings (primary color). Note that button text color needs to have sufficient contrast

### Definition of done
- [x] APIs displayed as first section below cover photo
- [x] Title "Latest APIs" has no underlining
- [x] Eight APIs are shown
- [x] One API card on a row in small device screens
- [x] A button with text "More APIs"
- [x] Pressing button redirects to the Catalog
- [x] Button color is the Primary color on Branding settings

# wireframe
1. Laptop view
![frontpage1-1](https://cloud.githubusercontent.com/assets/17976243/24702370/27c1cf1a-1a07-11e7-8739-89799cbe0aa3.png)

2. Mobile View

![mobile1](https://cloud.githubusercontent.com/assets/17976243/24702473/8b2cd446-1a07-11e7-8237-0714aba5713e.png)
<br></br>
<br></br>
![mobile3](https://cloud.githubusercontent.com/assets/17976243/24702492/a0297048-1a07-11e7-82db-19684311e009.png)

**Comment by Nazarah** [comment]
should we consider a future issue to decide which APIs to show in the Featured API section?

**Comment by bajiat** [comment]
@Nazarah I have already created one: see #2379

**Comment by Nazarah** [comment]
@bajiat Since we will be having a new API style (considering we are accommodating different logo sizes), should we consider showing the new style in the front page?

**Comment by marla-singer** [comment]
@Nazarah The new style will be applied for every API card in whole site: front page, APIs catalog, Search result, Organization Apis

**Comment by Nazarah** [comment]
@bajiat @matleppa 
Some concerns:
Soon we might be having the new API card which looks somewhat like this:
<br></br>
![api card](https://cloud.githubusercontent.com/assets/17976243/24653461/97454660-193e-11e7-90a5-5c0af5979b18.png)
With mobile view, accommodating 8 cards woudn't be a problem, but in normal screen this might create some rendering issue.
If u check the wireframes above, from my sketching, we needed an extra row to show last 2 latest APIs.
So devs may need to carefully design the redering fucntion here according to screen size.
Below is an example of the Mashapp front page: (mobile view: samsumg galaxy note 3)
<br></br>
![screenshot_2017-04-04-13-10-48](https://cloud.githubusercontent.com/assets/17976243/24653610/2b877096-193f-11e7-8d36-3d77ea1cc09f.jpg)
I needed to zoom out the site in my browser view to have this size (their site needs the fixing)
Moreover, they had only three APIs to feature (vs. we are considering showing 8 latest APIs to show)

**Comment by nnn** [comment]
What rendering issue you are referring to?

**Comment by Nazarah** [comment]
@nnn please see the wireframes for laptop screen.
it might be something to do with my work in PS, but with square cards, I somewhat ended up placing 3 cards in a row.
If I had put 4, then the card size became smaller and the content blurry
in real implementation, would we face any problem like that? Just need a confirmation.

**Comment by Nazarah** [comment]
@nnn please forget about the concern.
The problem was from my side with the PS.
Sorry for the inconvenience.
I have fixed and added the wireframes.

**Comment by nnn** [comment]
`in real implementation, would we face any problem like that? `
No, we won't.

Another question, is how many APIs per row we wanna display in the mobile view?
My suggestion is one per row. In order to fit two per row we need to make them smaller and it kinda defeats the purpose. Anyway, just something to keep in mind.

**Comment by Nazarah** [comment]
@nnn The only concern about showing one card per row in mobile view is that there would be a lot of scrolling to go to the bottom of the section and view other information (overview, footer, etc).
I'd suggest try out both options (2 per row  and 1 per row) with the new card style and decide which suits better.
