### ISSUE TITLE
New style and place for platform statistics

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2376]
# Goal
* Change the aesthetics of the platform statistics (users, apis etc.) according to the wireframe
* Open issue: How is the color of the area defined? Is it a pre-defined color or based on a branding setting?
* Remove the header "At a glance"
* Also, remove the text sections of the front page entirely.
# Definition of done
* [x] Remove resources related to At a glance
* [x] Remove resources related to Getting started section
* [x] Remove resources related to Reach out to developers
* [x] Remove resources related to Completely open source
* [x] Check that all dependencies about the above resources are removed 
# Wireframe
![frontpage1-3](https://cloud.githubusercontent.com/assets/17976243/24702630/4f4b08fc-1a08-11e7-8930-d773cfcbd026.png)

**Comment by Nazarah** [comment]
+1 with the color setting from branding page.
In addition, we should also have an option to disable this feature from the Branding menu, as some platform user might not be willing to use any statistics yet.

**Comment by jawidahmadi** [comment]
@Nazarah inform me as you're ready with wireframe please.

**Comment by Nazarah** [comment]
I have added the wireframe
@jawidahmadi @bajiat : I was thinking that when I was designing the wireframes in the very 1st phase, I thought about APInf color and tried to incorporate something there (e.g. dark grey, orange).
So from that Design I kept the buttons and overview pane orange and other parts grey.
This was having a good contrast.
Now if we configure the button colors and overview panel colors from the primary brand color, almost all elements become of the same color (e.g. top bar, button, overview panel, etc.)
In such case, the front page kind of loses its contrast and vibrancy.
Should We consider a separate controller to configure overview and button colors?

**Comment by bajiat** [comment]
Having a controller for Search button, See more and statistics area would make sense. Probably should be a separate issue.

**Comment by Nazarah** [comment]
Separate issue related to this problem is reported at: https://github.com/apinf/platform/issues/2418

**Comment by jawidahmadi** [comment]
@bajiat Could you add comment related to Nazia's equerries please?

**Comment by bajiat** [comment]
@jawidahmadi I have commented above. Based on the comment @Nazarah created the separate issue for controller: #2148. The issue is in Planning column.
