### ISSUE TITLE
Changes to footer

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2378]
# Goal
* Footer is visible on every page, not only front page
* Footer color matches the title bar
* Footer contains
  * About link
  * Language selection
  * Social media icons (if defined in Branding settings)
  * Privacy policy and terms of use (if defined)
* Social media icons should be larger and same style as on organization page

# Wireframes
1. Thinking 1st about mobile friendly approach:
- social media icons are placed on top and now have bigger size
- About Us, Sign In, Sign Up and Language menu are placed next. Language can be changed from dropmenu
- Since Privacy Policy and Terms of Use are upto platfom users to show, this appears at the bottom row apart from other elements.
- A footer note about "Powerd by APInf Oy appears at bottom right corner"
<br></br>
<br></br>
![footer-mobile](https://cloud.githubusercontent.com/assets/17976243/25219025/a40bb2d4-25b5-11e7-90a0-775b5b9a2b0b.png)

2. Based on the Mobile 1st approach, the footer should appear somewhat like below in laptop/monitor
<br></br>
<br></br>
![frontpage1-3](https://cloud.githubusercontent.com/assets/17976243/25219006/89885ce6-25b5-11e7-8a04-fe3cf026f427.png)

**Comment by nnn** [comment]
Interested.

**Comment by marla-singer** [comment]
@bajiat Need wireframe for this task.
Questions are:
- Leave or remove the quick links Sign In/Sign Up/ Sign Out?
- How to implement the language bar?
- How to separate a footer slogan and links Privcy, Terms, About?

**Comment by 55** [comment]
@marla-singer language bar should not a part of this take anymore, since we decided to leave it on the top of the page for mobile and desktop view.

**Comment by marla-singer** [comment]
@55 Really great

**Comment by marla-singer** [comment]
@Nazarah Can you please help me with this task? I don't know how to design footer and relate is with the statistic block. The current result you can see above

**Comment by Nazarah** [comment]
@marla-singer I am on it.

**Comment by Nazarah** [comment]
@marla-singer added the wireframes.
Please consider if there can be improvements made on the placement of different link texts on the footer.
The descriptions are along with the wireframe.
Also consider if we should make the link texts' color similar to that of brand text color.
to me, the blue link text colors don't suit with dark BG for some reason.
Also consider to have new field in Branding page to give link for "About Us".

@bajiat : looking for your feedback.
Should we consider to remove the top language bar in a separate task?

**Comment by bajiat** [comment]
The 'About Us' link is not about "us", e.g. about people. That information is on another site. The link is for the modal that informs the user about the software: version etc. So it should be 'About'.

**Comment by bajiat** [comment]
Other than that I'm ok with the wireframe.

**Comment by brylie** [comment]
> Should we consider to remove the top language bar in a separate task?

I second that we should consider removing the top language bar in a second task. The reason is, I don't feel a consensus about idea to move the language bar to the footer. Moving this decision to a separate task gives a bit more room to reach a common understanding/agreement.

**Comment by bajiat** [comment]
The language choice can be moved to the footer, go ahead with that.

**Comment by kyyberi** [comment]
Language selection takes too much space in current location. That could be used more efficiently and with more important information. Take it to the footer.
