### ISSUE TITLE
Show featured APIs instead of latest APIs on front page

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2379]
The front page should/could be used for show casing the most interesting / featured APIs so that users would want to go and look for more in the APInf catalog.

Open issue:
Should we have functionality to allow e.g. admin to select the Featured APIs or should there be automatic selection criteria based e.g. on the following:
* popularity
* lifecycle stage (e.g. production only)
* stability

**Comment by Nazarah** [comment]
We also need to consider APIs that are connected to a proxy to get more statistics about the API.

**Comment by preriasusi** [comment]
already implemented on nightly. Seems to be solved this issue.
