### ISSUE TITLE
Adding Proxy settings fails in staging

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2381]
I added API to catalog (https://staging.apinf.io/apis/issue-reporting-api-turku) - that went fine
I added swagger file - that went fine. 
Tried to set proxy - that failed. Gives me error about API key. 

## Settings
<img width="1174" alt="screenshot at maaliskuuta 29 13-17-29" src="https://cloud.githubusercontent.com/assets/1927158/24450075/237be7d6-1482-11e7-827a-d6f54e91f302.png">

## Error
![api_key](https://cloud.githubusercontent.com/assets/1927158/24450051/0536faf4-1482-11e7-968e-7e9398c9e358.jpeg)

**Comment by marla-singer** [comment]
@kyyberi API Umbrella proxy doesn't work. Please use "Nightly Umbrella" or "API-umbrella new"

**Comment by kyyberi** [comment]
ok. Thanks!

**Comment by kyyberi** [comment]
Worked. Next problem is that try out of GET methods do not work. I have no method to debug what might be the reason. 

This is the actual API call that should be done: ```https://api.turku.fi/feedback/v1/services.json``` with ```https://nightly-second-umbrella.apinf.io:3002/feedback_turku/services.json``` but result is empty / 404 Not Found.

**Comment by bajiat** [comment]
@kyyberi: @marla-singer is working on the GET methods, there is an issue with path

@shaliko / @marla-singer Why is the staging API Umbrella not working? Should we remove it from available proxies?

**Comment by bajiat** [comment]
@shaliko / @marla-singer Could you please check why is the staging API Umbrella not working? Or is this resolved? Should we remove staging API Umbrella from available proxies?

**Comment by shaliko** [comment]
@bajiat @kyyberi @marla-singer @brylie Yesterday I found that server "nightly-second-umbrella.apinf.io" wad dropped. Chandra asked in chat who using particular IP in April, not got the response and disabled it.

Are we need to re-create that server? Looks like staging have a lot of backends, so I am not sure that we really need "nightly-second-umbrella"?

Anyway, we need clean-up apis on staging that was related to "nightly-second-umbrella".

**Comment by brylie** [comment]
We probably don't need to recreate the server, but I defer to @bajiat.

Lets figure out how to clean up the related proxy backends. This is a tricky situation, and might also occur in a production deployment (such as if an organization decides to disable or migrate an remote proxy).

**Comment by shaliko** [comment]
@brylie Just drop APIs from UI will not work? 

Or another way, when we drop some API proxy we will drop all related API's, but we will need a prompt message for your about "Danger zone".

**Comment by brylie** [comment]
> @brylie Just drop APIs from UI will not work?

We can either manually remove or re-configure the Proxy Backends in this case. (cc: @bajiat).

> Or another way, when we drop some API proxy we will drop all related API's, but we will need a prompt message for your about "Danger zone".

That is a good idea. We can plan that as an enhancement.
