### ISSUE TITLE
Swagger proxy host is not relevant with multi-proxie case

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2388]
When an API is connected to a proxy, Swagger have to call request via proxy. 

Now it happens incorrectly. Swagger take the first proxy settings instead of specified.

Related #2381 

### Steps for reproduce
1. Make sure you have couple proxies with different URL host (nightly and staging)
2. Connect your API **to the second proxy in your proxies list** (important point)
3. Upload the swagger file 
4. Call GET request 

### Expected
- Request is sent using specified proxy in proxy backend configuration

### Found
- Request is sent using the first proxy in list

**Comment by bajiat** [comment]
@marla-singer Can you please add Steps to reproduce with expected and actual result? That would also help the reviewer and the tester.
