### ISSUE TITLE
Create function / pattern for text contrast

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2391]
# Description
Since we allow changing button and background colors through branding settings, we must ensure that UI text remains legible regardless of color selections by user.

# User story
As an APInf end user, I need to text on page to contrast with the background
so that I can see what I am reading.

# Goal
Create a pattern or function for checking background and text contrast. This should be a reusable utility.
Comply with Web Content Accessibility Guidelines AA.

**Comment by bajiat** [comment]
Possible options
* contrast widget to warn users on branding page, if the primary and secondary colors don't have sufficient contrast.
* Changing the color value if the contrast is not sufficient.

**Comment by matleppa** [comment]
@baijat @Nazarah  Do you have a strong view about how to warn user in case there is not enough contrast? Should it be sAlert or some other way?
