### ISSUE TITLE
Anonym user watch an empty page instead of API profile

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2393]
### Steps
1. Visit nightly.apinf.io as anonymous user 
2. Navigate to APIs catalog
3. Click on any API

### Expected
Watch the selected API profile

### Found
An empty page and errors in browser console

### Reason
Maybe problem with `publishComposite` function

Related issues #2384, #2369

**Comment by bajiat** [comment]
I was unable to reproduce in nightly. Tried with these steps

1. Go to nightly.apinf.io as anonymous user (browser: IE)
2. Click Catalog
3. Click [EbooksAPI](https://nightly.apinf.io/apis/ebooks-api)

I don't see an entire blank page. Instead I see this: 

<img width="769" alt="api profile anonymous user ebooks-api" src="https://cloud.githubusercontent.com/assets/11626388/24955651/f7286e14-1f8c-11e7-9621-2aa5f2733152.png">
