### ISSUE TITLE
Filter by 'Life Cycle phase': Notify user when no APIs found with selected status

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2396]
# Steps 
1.Visit https://staging.apinf.io v 0.42.0 
2.Login  
3.Go to API catalog 
4.Filter by 'Life Cycle' status (eg. deprecated)  

# Findings  
- When no 'APIs' found by selected status , the sorting result is shown as: 'Filtered by "Deprecated" "Clear All"
- Sort result could notify user eg. "No APIs found with the selected life cycle status"      

# Screenshot  
![sort_results_lifecycle_status](https://cloud.githubusercontent.com/assets/13309358/24548872/70687638-161f-11e7-9832-d1c726aa525e.PNG)

**Comment by bajiat** [comment]
@Nazarah Is the suggested notification text ok for you? "No APIs found with the selected life cycle status"

**Comment by Nazarah** [comment]
@bajiat I beleive the text should be the same for all cases, whenever a search query doesn't return a result. A simple text "No API found." is sufficient for this.

**Comment by wuder4** [comment]
Now it shows this error every time you have 0 results in API catalog. eg. if you look at your bookmarks and you have no APIs in bookmarks. It tells you:
No APIs found with the selected life cycle status

If the error says "No API found." it would not be a problem

**Comment by saralavanip** [comment]
@bajiat , observed on staging v 0.50.0 : Related screenshots below.  
 

![staging_0 50 0_myapis_incorrect_msg](https://user-images.githubusercontent.com/13309358/30583075-93f1f1a6-9d2e-11e7-8224-5639463960ac.PNG)   

![staging_v0 50 0_no_apis_incorrect_msg](https://user-images.githubusercontent.com/13309358/30583085-a0b6ae54-9d2e-11e7-9cd5-5b24fcfdda64.PNG)   

![staging_v0 50 0_mybookmarks](https://user-images.githubusercontent.com/13309358/30583194-f636a7ee-9d2e-11e7-88aa-82be756b5032.PNG)

**Comment by Nazarah** [comment]
@Vellames what is the status for this issue? It has been in Progress for 2 months.

**Comment by preriasusi** [comment]
Not repro in production 0.50.0 at apinf.io.
