### ISSUE TITLE
Allow admin to add eMQ as a proxy

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2398]
# User story
> As an admin user
I want to add eMQ proxy to my deployment
so that real-time apis can be managed through the UI.

# Goal
API admin can add eMQ proxy to the deployment through Proxies view.
Admin is able to add the following configuration information for the eMQ broker:
- eMQ proxy URL
- eMQ Elasticsearch (analytics) endpoint
- eMQ API URL
- eMQ API credentials

**Comment by kyyberi** [comment]
Excellent! Nice that we are approaching eMQ proxy usage via platform!

**Comment by bajiat** [comment]
@frenchbread Can you add an estimate to this issue?

**Comment by frenchbread** [comment]
@bajiat Added estimation
