### ISSUE TITLE
In the Swagger viewer, there is a huge Swagger logo image at the top of the page.

### ISSUE THREAD

**Issue by Olli-palkkaus** [apinf/platform#2408]
When I upload the Swagger document, the page that shows the Swagger viewer shows a huge Swagger logo before showing the actual Swagger viewer. The same behaviour is also on APInf own API page: https://apinf.io/apis/TYf33t5B6D6fwamKt , so I am assuming it is nothing wrong in my Swagger doc.

Steps to reproduce:

1. Go to https://apinf.io/apis/TYf33t5B6D6fwamKt

Observed behavior: Large Swagger Logo before the viewer.

Expected bahavior: The Swagger API viewer immediately visible when you come to the page.

![image](https://cloud.githubusercontent.com/assets/10129347/24599713/1f247820-185a-11e7-878e-a0fa5c0a662f.png)

**Comment by bajiat** [comment]
Thanks for your interest in APInf! The problem with the Swagger icon has been fixed. It is available in release [0.42.0](https://github.com/apinf/platform/releases/tag/0.42.0). The fix is not available in apinf.io yet.

For reference, the issue fixing the problem was #2213
