### ISSUE TITLE
Implement branding color design and usage in platform

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2418]
# Usability Issue
If we allow primary color settings from branding page to determine colors of buttons, button texts, statistics pane and its text (and possibly chatbot), then we would lose the wow effect and vibrancy that we are trying to achieve.
Example below of the screen shot where the site looks vibrant and appealing with 2 set of color:
![frontpage1-3](https://cloud.githubusercontent.com/assets/17976243/24751265/8b9ded28-1ad1-11e7-8cf1-6118368d19f6.png)

<br></br>
<br></br>
Example below of the screen shot where the site looks vibrant and appealing with 2 set of color:
![frontpage1-3](https://cloud.githubusercontent.com/assets/17976243/24750865/20d28d4c-1ad0-11e7-816f-2370891e0514.png)

This may also create aesthetics issue when there is no landing page cover photo.

# Enhancement
* [ ] Separate controllers under Branfing Menu's Color Panel
* [ ] one controller will be used to select button colors and color of statistics panel on landing page
* [ ] one controller will be used text color of the above places.

**Open Question:** Should we consider these controllers to determine the color of chatbot and primary buttons through out the site?

 # Related issue
https://github.com/apinf/platform/issues/2376

# Wireframe
![image](https://cloud.githubusercontent.com/assets/17976243/25938509/1e08fa1e-3638-11e7-9b08-1b42e9fc0fcd.png)
we propose the following solution: (following bootstrap solution)
Primary Color : primary color in bootstrap
Accent Color : secondary color in bootstrap
Colors can be fixed from branding page.
The action buttons can follow the accent color.
Text color contrast based on the color and its placement should be configured using CSS

**Comment by bajiat** [comment]
@brylie Can you comment about the button styles?

**Comment by brylie** [comment]
What buttons will use this color? What is the extent of this idea?

We have buttons throughout our application. For consistency, we might consider allowing the other buttons to be branded, which would mean this idea extends beyond the front page.

Also, there are several button styles, defined by Bootstrap, which could all hypothetically be overridden:

![screenshot_20170412_155135](https://cloud.githubusercontent.com/assets/17307/24958425/eb431b66-1f97-11e7-81d8-b938d0ec8609.png)

**Comment by brylie** [comment]
For context, the primary and secondary branding colors are used on pages beyond the front page. While this task specifically mentions only the front page, it is easy for these ideas to take root and grow beyond their original scope.

I am just concerned about 'scope creep' and growing complexity in our project.

**Comment by brylie** [comment]
What will the branding color settings page look like with these new settings? What will we call the settings? E.g. we currently have **primary** and **secondary** branding colors, so we need to conceptualize these additional branding colors.

**Comment by brylie** [comment]
@nnn would you please also add your thoughts and ideas on how we handle branding color settings?

**Comment by Nazarah** [comment]
@brylie in APinf, I found the use of Info, Danger (for deleting and API or other items) and Add button (for adding swagger document and media items).
Also the primary actions o adding an organization or API doesn't appear as buttons, they appear in the nav bar.
If you want you can hard code this specific button colors.
Other than that, it is good to give some flexibility to customers to select their preferred colors through out  platform and the front page.
We can always keep the info icon in blue with an "i" icon and the delete button can be in standard BS color.

**Comment by brylie** [comment]
> I am yet not concerend with the feature creep idiology.

In the immortal, and somewhat heart wrenching, words of [LeVar Burton](https://en.wikipedia.org/wiki/LeVar_Burton): "you don't have to take my word for it"

- Interaction Design Foundation - Glossary of Human Computer Interaction: [Featuritis](https://www.interaction-design.org/literature/book/the-glossary-of-human-computer-interaction/featuritis-or-creeping-featurism)
- Wikipedia: [Feature creep](https://en.wikipedia.org/wiki/Feature_creep)
- Technopedia: [ Creeping Featuritis ](https://www.techopedia.com/definition/18600/creeping-featuritis)
- c2 wiki [Creeping Featuritis](http://wiki.c2.com/?CreepingFeaturitis)

It's not just developers who struggle, **featuritis is a usability issue** too:

![Featuritis usability](https://pbs.twimg.com/media/BVLNvydCUAIT7fx.jpg)

**Comment by Nazarah** [comment]
after a discussion with @brylie and @philippeluickx we propose the following solution: (following bootstrap solution)
**Primary Color** : primary color in bootstrap
**Accent Color** : secondary color in bootstrap
Colors can be fixed from branding page.
The action buttons can follow the accent color.
Text color contrast based on the color and its placement should be configured using CSS
For example, in front page, the colors going to effect like the following:
![frontpage1-1](https://cloud.githubusercontent.com/assets/17976243/25425287/267bfce8-2a74-11e7-884b-e34164181ab6.png)
![frontpage1-3](https://cloud.githubusercontent.com/assets/17976243/25425286/2677e022-2a74-11e7-88b8-c5526cc3d121.png)

Asking for others' feedback and new solutions as well.
@kyyberi 
@preriasusi

**Comment by 55** [comment]
I would suggest to keep footer color neutral and predefined, e.g. grey, black or white.

**Comment by Nazarah** [comment]
Another option is to provide a CSS editor in the branding page, so that Site admin can decide with the look and feel using their customized markup sheets.

**Comment by brylie** [comment]
@Nazarah did you mean to close this issue?

**Comment by Nazarah** [comment]
@brylie yes. @bajiat preferred the bootstrap solution of Primary and Accent color for platform branding.
so we should have a separate implementation issue for this. 
we can reference this issue in the implementation issue.
For future consideration we can see how effective CSS editor would be for branding purpose  and ideas can be proposed in its own issue.

**Comment by brylie** [comment]
@bajiat what steps should we take to continue this work?

**Comment by bajiat** [comment]
@Nazarah Can you please create an issue with your proposal for the Primary and Accent color? We already have an issue for CSS editor.

**Comment by Nazarah** [comment]
on it.
