### ISSUE TITLE
Organization page misaligned

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2426]
# Steps 
1.Visit https://nightly.apinf.io v 0.42.0 
2.Go to Organizations  
3.Select any organization   

# Findings 
Organization page misaligned   

# Screenshot  
![organization page misaligned](https://cloud.githubusercontent.com/assets/13309358/24792093/4a11101a-1b85-11e7-8d31-cffa188bdaef.PNG)

**Comment by nnn** [comment]
@saralavanip what exactly do you mean?

**Comment by saralavanip** [comment]
@nnn , I compared this organization view with previous version and assumed as a blank space below navbar. Later I got to know this is for added feature 'cover image' in organization view.

**Comment by nnn** [comment]
Should be close this issue?

**Comment by saralavanip** [comment]
@nnn , yes we can close this issue.
