### ISSUE TITLE
APIs/Organizations Catalog filter : mouse point on tabs shows multiple help texts

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2436]
# Steps  
1.Visit https://nightly.apinf.io  v 0.42.0 
2.Go to APIs / Organizations 
3.Change language to Suomi
4.Mouse pointer on filter tabs : Ascending/descending , grid/table  

# Findings 
- Shows help text in both Finnish and English languages  
- Change language back to English: shows help text multiple times in English language   

# Screenshots  
![apis_catalog_filter_tabs_multiple_texts_suomiview](https://cloud.githubusercontent.com/assets/13309358/24896632/6ba8eeac-1e9e-11e7-9d10-75c4b54efd2f.PNG)   

![apis_catalog_filter_tabs_multiple_texts1_suomiview](https://cloud.githubusercontent.com/assets/13309358/24896638/756ff124-1e9e-11e7-95f6-2d9ca92856b9.PNG)    

![api_catalog_filter_tabs_english_multiple_texts](https://cloud.githubusercontent.com/assets/13309358/24896826/47e8515a-1e9f-11e7-90ac-a2ca318f997c.PNG)

![org_catalog_filter_english_multiple_texts](https://cloud.githubusercontent.com/assets/13309358/24896834/52c853f4-1e9f-11e7-8bd4-bfea9eebcb5c.PNG)

**Comment by bajiat** [comment]
@saralavanip Please mention the browser information

**Comment by saralavanip** [comment]
@bajiat , added browser details to the bug report.
