### ISSUE TITLE
APInf Catalog (APIs) API implementation

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2441]
# Goal
API consumer can call the **API** endpoints and use the methods defined in the Catalog API design document.

# Related resources
We have produced a Swagger file with Organization API endpoints, which can be accessed on our [APInf deployment](https://apinf.io/apis/TYf33t5B6D6fwamKt).

This is also related to issue #2440

**Comment by bajiat** [comment]
@marla-singer Would you be interested in this?

**Comment by marla-singer** [comment]
@bajiat Yes. But I can not estimate it because I don't understand the entire idea and what do I do in this task

**Comment by kyyberi** [comment]
The idea is there, look at the documentation https://apinf.io/apis/TYf33t5B6D6fwamKt

**Comment by bajiat** [comment]
@marla-singer Could you take this task?

**Comment by marla-singer** [comment]
@bajiat Yes, I can
