### ISSUE TITLE
Create first version of integration and automated testing plan

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2446]
Taking into account our plans for continuous integration, devise a first version of automated testing plans.

# Goals
Document the following
- level of automated testing (we are not even aiming for 100% coverage)
- types of automated testing
- how to select the test cases
- testing framework recommendation
- role of manual testing
- first practical steps

# Related
Consider also cross-platform automated testing

**Comment by bajiat** [comment]
@mauriciovieira Would you be interested in this task?

**Comment by ashakunt** [comment]
The idea behind having a testing and integration framework in place is to facilitate best quality code, strong (and standard) coding guidelines. The following comments will have information about the proposed plan.

**Comment by ashakunt** [comment]
Top level highlight:
* All development will happen only in feature branches
* After successful review and **Gate 1** is passed, the branch is merged to **develop**
* **develop** is tested regularly with **BIT** on Travis CI
* Every night, **develop** is tested with **Gate 2** and upon success, **develop** is deployed to **nightly.apinf.io**
* Before every release, **Gate 3** is triggered and based on its success, the build is promoted from **develop** to **master**;  and relevant release tags are created.
* Release to **apinf.io** and customers will be handled manually as of now.

**Comment by ashakunt** [comment]
Terminologies defined / Gates:

* **GATE 1** / **BIT** (Basic Integration Tests)
    * Unit tests
    * LINT checks
    * Other mandatory checks (e.g. checking il8n tokens)
    * Sandbox setup with basic functionality working (to be defined)
* **GATE 2**
    * Unit tests
    * Smoke tests (automation level 100%)
    * System tests (automation level 100%)
    * Tests in Smoke and System tests packages must be defined
* **GATE 3**
    * Release tests
    * Regression tests
    * Security tests
    * Penetration tests 
    * Tests in every package must be defined
    * At this stage, testing will be combination of Manual and Automation testing (40:60)
    * This gate will also execute **Gate 1** and **Gate 2** tests

Terminologies defined / delivery end points
**nightly.apinf.io**: latest content of **develop** deployed every night.
**staging.apinf.io**: pre-release (and release candidate; after release). 
**apinf.io**: stable, last release

**Comment by ashakunt** [comment]
To make the above plan successful, efforts are required from all teams. Below is the list of items needed from relevant teams.
* **From devops**
    * Script for deployment of API Umbrella 
    * Script for cleaning the API umbrella instance 
    * Script to deploy APINF instance for testing during the CI process (or a docker instance)
    * Script to deploy APINF to remote server (e.g. nightly.apinf.io, staging.apinf.io, apinf.io)
* **From developers**
    * Unit tests
    * UI tests
    * Other relevant tests
    * Script to run-tests.sh
    * Define any specific pre-conditions to the tests

The above scripts will be used in CI setup (e.g. Jenkins)  to facilitate running of tests.

**Comment by ashakunt** [comment]
Testing frameworks: 

* For unit testing: Mocha
* For UI testing: Selenium - Robot

**Comment by ashakunt** [comment]
First steps:

* [ ] Run a demo / dummy tests in Travis => get a tests package
* [ ] Setup local Jenkins instance(s) and run the tests package there
* [ ] Check if`xvfb` can be used for running UI tests (so jenkins can be located in cloud)
* [ ] Improve the test package coverage to include: unit tests, lint, il8n checks 
* [ ] Define tests that should be run in every package (BIT, SmT, SyT) and gate (1, 2, 3)

We should aim to have **fully automated Gate 1 and Gate 2**. Practically, at this point, its not possible to have a fully automated **Gate 3**. We aim to start with a balance of 60% automated and 40% manual testing.

**Comment by ashakunt** [comment]
**Role of manual testing**: 
----
is very important. First of all, it gives an experienced first hand feedback of the software. Next, this should include **Regression testing** of all the bug fixes that have been made in the sprint (unless, there are automated tests for the bug fix).

**Comment by ashakunt** [comment]
**Updating the definition of done**: 
----
DoD should now include the following
* **Gate 1** and **BIT** passed
* More than two unit tests (including at least one positive and one negative test scenario). It is recommended to have at least as many negative scenarios tests as possible already. 
* If applicable, more than one UI test to check the behavior of the feature on the deployment.

**Comment by ashakunt** [comment]
@bajiat : we should now start to define the tests in different packages (BIT, SmT, SyT, Release, Regression)

@mauriciovieira @ccsr  @brylie comments above available for review .

**Comment by kyyberi** [comment]
@ashakunt this sounds awesome!

**Comment by ccsr** [comment]
@phanimahesh please align with this. We are setting servers for this.

**Comment by ashakunt** [comment]
A presentation was shared with the team. A document will be created in github to have summaries of the whole plan.
