### ISSUE TITLE
Documentation is not visible for anonymous and regular user

### ISSUE THREAD

**Issue by nnn** [apinf/platform#2448]
All three types of documentation are not visible for anonymous user
Maybe something wrong with subscription/publication 
See [this](https://github.com/apinf/platform/issues/1102#issuecomment-291045516) comment for reference.

## Steps to reproduce

1. Add API or go to existing as a manager/admin
2. Upload documentation or add by external URL or specify external URL
3. Log out and go to created/updated API

## Expected behavior

Anonymous user should be able to see documentation

**Comment by marla-singer** [comment]
@nnn The issue is related to #2393

**Comment by bajiat** [comment]
@brylie Can you diagnose this problem?
