### ISSUE TITLE
Collection support for events

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2451]
## Story

As Hackathon organizer I want to collect selected APIs to one view (collection) and be able to give hackathon participants clear simple URL (such as apinf.io/collections/eduhack). APIs in collection are selected from /apis list by organizers of the event.

**Comment by kyyberi** [comment]
* Who can create collections? Anyone? 
* We list collections as organizations?

**Comment by kyyberi** [comment]
Another way to create collections is tagging. Each API is given tags and we list all APIs with given tag.

**Comment by kyyberi** [comment]
This will be raised to top 5 probably pretty soon @bajiat

**Comment by bajiat** [comment]
If tagging would be used, this one would assume free-tagging. I'm iceboxing this until it makes it to the top 5.
