### ISSUE TITLE
Concept and low fidelity wireframes for DX score

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2452]
# Description
We want to encourage API owners in taking into account developer experience for their APIs. One of the ways to enourage this would be an incentive system, which gamifies the progress of adding e.g. information, documentation and media to the API profile. 

# Goal
- Define and document which parts of the API profile enhance the developer experience. 
- Consider how to gamify this and how to create a sense of progress
- Also, think of easy ways to show completeness (percentage, points etc. ) and to go from viewing score / completeness to improving the score. 
- Benchmark other solutions (like LinkedIn profile completion).
- Consider both short term and long term vision.
- Create at least low fidelity wireframes for current profile.

See also the EPIC description and links from the comments for #2297

# Wireframes

1. API Users can see DX score of an API on the API profile heading.
It is represented with a Conical flask with a number associated with it.
The number represents DX value of an API
<br></br>
![lowfi1](https://cloud.githubusercontent.com/assets/17976243/25695754/014d10ca-30bd-11e7-836e-f9573ce307c1.png)

2. API owners can identify different fields where DX score is applicable throughout the API profile.
The DX specific field has conical flask appearing beside the field name.
<br></br>
<br></br>
![lowfi2](https://cloud.githubusercontent.com/assets/17976243/25696788/20127aa0-30c1-11e7-842e-4d74d08543fa.png)

On clicking the flask icon, a tooltip appears.
The tooltip contains messages to notify how a specific field can be used to improve DX of the API.
<br></br>
<br></br>
![lowfi2_2](https://cloud.githubusercontent.com/assets/17976243/25696799/2f0e9e62-30c1-11e7-84a3-baf610b72a28.png)

![lowfi2_3](https://cloud.githubusercontent.com/assets/17976243/25696806/33d38d2c-30c1-11e7-8985-3a8c82327310.png)

3. When a new DX score is achieved, it appears as a notification.
the total dx point also appears
![lowfi1_2](https://cloud.githubusercontent.com/assets/17976243/25696871/8840ffca-30c1-11e7-8138-afefc5f9266c.png)

4. At the bottom part of Details tab, a new section "API DX" appears.
This section contains some logo indicating different aspects of the API and its profile (e.g. General Information, Documentation, Performance, Related Media, etc.).
Initially the logos are disabled.
When all subfields under each criteria logo are filled up, the logo becomes green.
<br></br>
<br></br>
![lowfi2_4](https://cloud.githubusercontent.com/assets/17976243/25697180/a3e380f8-30c2-11e7-977b-63576731bb9d.png)

5. (depending on the placement: either Details Tab or Settings) API owners should be able to see how much score they earn on filling up a specific field. 
The field names along with allocated DX score should be visible to API owner.
The fields that are completed will appear green.
The rest will appear as grey.
<br></br>
<br></br>
![lowfi1_5](https://cloud.githubusercontent.com/assets/17976243/25697195/b9d40afe-30c2-11e7-80e7-25840ac43a75.png)

6. In Brand Setting, we can add a new section, where site admin can decide the DX score for each specific fields.

**Comment by bajiat** [comment]
## Some references:
- https://www.voices.com/help/talent/what-is-profile-completeness
- http://www.linkedin-makeover.com/2012/02/20/linkedins-new-requirements-for-a-100-complete-profile/
-https://blog.couchsurfing.com/product-update-profile-completeness-percentage/

## Related article
- http://www.dtelepathy.com/blog/design/ux-how-drive-deep-user-engagement

**Comment by bajiat** [comment]
@kyyberi Anything to add to this concepting task?

**Comment by Nazarah** [comment]
[Why API Developer Experience Matters More Than Ever](http://nordicapis.com/why-api-developer-experience-matters-more-than-ever/)

Can we implement checking the following criteria with a monitoring system/existing proxy in APInf?
This seems to be a good idea on to rank a profile or its completeness
![image](https://cloud.githubusercontent.com/assets/17976243/25385068/6e2434d8-29cb-11e7-8adc-65494b027375.png)

Some additional things can be considered as well:
* existenc of multiple data source
* improving filtering
* searching
* checking API rate
   - Ability to return list of items in once call

**Comment by Nazarah** [comment]
From issue #2297 the initial DX can be achieved the the following existing APInf features for API profile

- title
- description
- documentation
- backlog

Not sure with the estimate, but we can say about 80% completeness of API profile if the above fields are filled. The eventual progress happens when API owner starts adding advanced criteria in the API profile.

**Comment by Nazarah** [comment]
[Building an Empathic API](http://blog.hellosign.com/the-rise-of-developer-experience/)

*  **Documentation**
- Clear and Up-To-Date
- logically organized sections
- clear API reference

* **Getting Started**
- How-Tos
- Quick Starts
* **Ease of Use**
- reducing non-coding setup requirements. (_creating accounts, apps, signing up for a paid plan, or talking to a sales person_)
- SDKs in multiple language. Make them open source so communitycan submit pull requests (Ruby, Python, NodeJS, PHP, and Java)

* **Ease of Debugging**
- API Dashboard

* **Easy to Get Help**
- Dedicated API Suport Team
- GitHub and StackOverflow issues

**Comment by Nazarah** [comment]
Badges ca be associated with API profile to create motivations among API developers to remain in ranking by providing good DX
https://openbadgefactory.com/fi/
https://www.discendum.com/etusivu/

**Comment by Nazarah** [comment]
Proposing two phase development of DX:

1. Using existing APInf Features
2. Integrating newly developed features as future development strategy

1. existing APInf Features:
- on providing complete information when Adding an API (Name, Description, API end point and lifecycle status), profile will be 60% complete. 
All of the above fields need to be filled in order to get this progress. 
On providing only mandatory information, profile can be shown as 55% complete.
A badge can be associated with this progress (name and look needs to be decided later). Badge will be displayed only when profile has 60% progress.
- When API owner is redirected to the API profile, this notification can appear immediately (consider how FB games notified when you achieve a new rank or reach a level). 
- Badges can appear to both API owner and consumers. 
But the progress should be visible only to API owner.
- Further progress can be added when Ower adds a swagger document (75%) and starts addng backlog to profile (80%). On getting 80% progress, API profile gets another badge after wards.
- After wards profile progress becomes a bit slower to achieve and it involves setting up advanced settings. (e.g. adding a proxy)

**Comment by Nazarah** [comment]
**Considering the existing features in APInf**
We should have a new feature for API owner to know how much the profile is complete by comparing points given for adding a specific field. 
This feature should include a list of APInf features for API profiles and a numbers associated with them when a particular field is filled.
The fields can be categorized as completed and incomplete filed
Similar to [this article](https://www.voices.com/help/talent/what-is-profile-completeness), the points distributed can be:

**General**
* API Name = 4
*  Description = 4
* API Endpoint = 4
* API Logo = 4
* Metadata = 4

**Advanced**
* Lifecycle Status = 5
* Swagger Documentation = 5
* One Related Media = 5 
* API connected to an Organization = 5
* Backlog (atleast 1) = 5
* Public/Private visibility (with API profile getting point on being public) = 4

**Technical**
* SDK Generation (min. 5 popular languages) = 5
* Adding an end point to monitor = 5
* Adding API to a proxy = 5
* Enabling Key requirement  = 5
* append query string parameter =5
* Set request Header =5 
* Rate limit mode = 5

Write now the total comes as 84. But we can think about increasing points/adding more fields for profile completeness scores to make it a total of 100.
Also for fields like Media, Backlog, etc, for adding one new element would increase the point score.
Also completing the each field in the above categories, we can give a new Badge

**Questions**
1. Should we assign point when lifecycle status goes to **Production**?
2. Should we have specific point when a media content named **"Tutorial/How-to/Getting Started"**? this can have a weight of 10 points
3. Should we treat adding a **proxy**  and making **API key** available in one criterion? Associated with it is **Disabling API Key Requirement**. What about the putting the fields  **Adding proxy base path**
**adding API base path** in the same criterion?
4. Should we consider **user ratings**?
5. Does APInf support the number of languages that can be used to generate SDKs? Or it is managed by swagger externally/. If it has to do something outside APInf, then for most popular 5 language, we can give point 5 for their SDks. For every single language added, we can give one point more.

We also need to decide that when a score of 100 is received, do we say the profile is complete? or we keep going on? Like earning the next 100 point would give a new badge?

@bajiat @kyyberi @philippeluickx looking for your feedback and suggestions.

**Comment by Laura-Sampo** [comment]
My opinion comes a bit late, but i don't like the scores. Setting scores for different fields looks complicated to me. Might be tempting for the young generation who likes mobile games, but what about others?
Did we consider some bar as maybe in LinkedIn, which shows that your "profile" is 70% ready and which fields you should still fill in to get optimized results?

**Comment by Nazarah** [comment]
@Laura-Sampo A percentage can always be an option although that would be numeric as well.
After a discussion with @philippeluickx and @kyyberi we thought to propose a DX score which would be 100 in total. This can be incroporated in UI (e.g. "70 out of 100") if everyone decides about it.
However, I am more into choosing a number.
The reason behind is that, in LinkedIn, when you keep on adding information on profile, it gets updated and doesn't fall usually.
But what if your API had a high DX score in the beginning and you decided not to take care of it? (e.g. updating documentation, keeping API performance consistent, going back to consumer queries, etc.) the DX doesn't remain same. 
If we think about near future implementation, we can always add features to measure and assign appropriate DX to a profile.
I understand your concern here, considering both are profiles. But if you put an API profile and a Professional profile in LinkedIn side by side, you'll see that the context of use is different.

**Comment by Nazarah** [comment]
after a discussion with @bajiat we propose the following:
- on any lifecycle status, the API profile DX should be updated. On changing the lifecycle phase next time, the DX score will not be affected. Only removing the status would decrease the DX.
- Quick Start as OEMBD content might be too complicated to decide. Perhaps having a related media should add some points to DX score. but it should not be as high as 10.
- DX score for SDK should be part of the swagger documentation score, not something separate on its own.
This is swagger codegen is always available when there is a valid swagger file.
- On disabling API key requirement, the given score will be deducted. (-5) [reason, if we had a customer and a consumer dashboard, they could follow the API calls for a particular API where they were using the related API key]
- need use cases for "DX score on rate limiting"
- API performance monitring should have a higher max score (ex: 30). This should be determined from the threshold value of performance at a particular period,  API responses (HTTP statu codes for example), API response time, etc. At worst the score can also be negative, in such case,Overall DX value would decrease.

**Comment by Nazarah** [comment]
**question** what happens to the DX score of an API that has been deprecated? Should we freeze the scoring? change the DX icon color?

**Comment by kyyberi** [comment]
Deprecated does not have dx score.

**Comment by brylie** [comment]
how we should consider users' feedback in rating an API or looking at the response rate from API owners to user's questions.
