### ISSUE TITLE
Dashboard onload - dont load first statistics

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2459]
## Description

When user goes to dashboard, it automatically starts loading statistics for first API in the list. I do not want to wait until that is done to select API I actually want to see. 

## Fix 
Don't autoload any stats for any API. Let user select API to discover.

**Comment by marla-singer** [comment]
@kyyberi @bajiat Have to be fixed in anew Dashboard page

**Comment by marla-singer** [comment]
@preriasusi Already done with new Dashboard. The issue is outdated
