### ISSUE TITLE
APInf Service design guidelines

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2462]
# Description
Come up with a list of principles for service design in APInf. Max 7-10 items with descriptions.

**Comment by kyyberi** [comment]
Suggestion: lets just adopt this https://www.leanservicecreation.com/

**Comment by 55** [comment]
@bajiat @Nazarah what is the status of this task? I would like to help with it.

**Comment by Nazarah** [comment]
@55 we wanted to start it this sprint, but it was not possible because of other priorities. But you are more than welcome to participate. We will be having a discussion tomorrow around 10 AM, so please do join us.
