### ISSUE TITLE
Uncaught Error: Configuration options must be set before AccountsTemplates.init!

### ISSUE THREAD

**Issue by frenchbread** [apinf/platform#2465]
Error is thrown in the browser console during local development. As meteor server restarts automatically when any change is made to the project code, it causes browser to force page refresh automatically as well, after the first page refresh (right after some code change is made), following error is thrown:

### Error message in the browser console
```
Uncaught Error: Configuration options must be set before AccountsTemplates.init!
```

Second page refresh "resolves" the issue.

## Steps to reproduce
  1. When having app running locally and browser tap opened on any page (for example - `/api/<api_name>` open editor and make some change to force meteor restart server & refresh browser page.
  2. The age will be refresh with an error in the console. (This does not happen every time)

## ScreenShot
![screen shot 2017-04-18 at 17 55 31](https://cloud.githubusercontent.com/assets/2122679/25137531/b07b6b1e-2460-11e7-9d8a-61d6a17be5b6.png)

## Observed
   1. Error in the browser console
   2. API Data is not loaded

## Expected
   No errors in the console  & data API data loading fine (on first page auto refresh)

## Software versions
  - macOS `10.12.4`
  - Node `v7.4.0`
  - v8 - `5.4.500.45`
  - Meteor - `1.4.3.1`
  - Chrome - `60.0.3073.0 canary (64-bit)`

**Comment by marla-singer** [comment]
@frenchbread Try to use below condition in line - https://github.com/apinf/platform/blob/develop/core/client/lib/router.js#L23

```js
if (Roles.subscription.ready() && AccountsTemplates._initialized && !FlowRouter._initialized)
```
And please  describe the result. On my side it is rare case so I can not say exactly if it helps

**Comment by frenchbread** [comment]
@marla-singer Many thanks for this fix. After adding this line, I don't get error in the console anymore, thus, browser page remains blank, without any content and page refresh is still needed.

In addition to that condition line, I'd add

```js
import { AccountsTemplates } from 'meteor/useraccounts:core';
```

**Comment by bajiat** [comment]
@brylie Can you take a look?

**Comment by brylie** [comment]
@frenchbread can you still produce this error on `develop`?

**Comment by frenchbread** [comment]
@brylie Yes, issue still appears. (Just tested)

**Comment by brylie** [comment]
This seems to be a local development issue, as was originally reported. I am also experiencing the issue locally, but do not believe it is happening on deployments. 

@bajiat: perhaps we can close the issue or move it to icebox?

**Comment by bajiat** [comment]
I'm closing it. If we find that it is actually causing problems with development in local environment or happening on deployments, we can re-open.
