### ISSUE TITLE
Frontpage: 'About' link missing on navbar

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2475]
# Steps 
1.Visit https://staging.apinf.io (v 0.43.0)   
2.Go to Navbar 

# Findings  
'About' link missing on navbar      

# Screenshot  
![about_missing_in_frontpage](https://cloud.githubusercontent.com/assets/13309358/25218207/b311fbf6-25b2-11e7-8e24-ee73dc15760f.PNG)

**Comment by 55** [comment]
It has been removed on purpose.
Now it's a part of page footer (see https://github.com/apinf/platform/issues/2378)
