### ISSUE TITLE
Experiment with using yarn instead of npm

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2476]
# Description
Try using yarn commands instead of nmp in development. Document any problems.

Experiment will take place during 2nd wk of sprint 41

**Comment by bajiat** [comment]
@marla-singer and @frenchbread Would you be interested in joining this experiment next week? More information available from @brylie and @phanimahesh

**Comment by frenchbread** [comment]
@bajiat Sounds good! I am in.

**Comment by marla-singer** [comment]
@bajiat Me too

**Comment by brylie** [comment]
Cool. Will someone open a PR with the Yarn .lock file against our `develop` branch?

**Comment by marla-singer** [comment]
@brylie I can

**Comment by mauriciovieira** [comment]
Travis also should use yarn.
