### ISSUE TITLE
Organization Settings:Title texts untranslated in Suomi view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2484]
# Steps 
1.Visit https://staging.apinf.io  v 0.43.0 
2.Login as admin 
2.Add Organization 
3.Go to Settings 
4.Change language to 'Suomi' 

# Findings  
Title texts are partially translated in Suomi view 

# Screenshot  
![suomi_view_org_settings_title_texts_untranslated2](https://cloud.githubusercontent.com/assets/13309358/25281423/0679d954-26b6-11e7-8b21-d34529bf4a6a.PNG)     

![suomi_view_org_settings_title_texts_untranslated1](https://cloud.githubusercontent.com/assets/13309358/25281529/5b1944b8-26b6-11e7-82a9-f5ff9d23a1af.PNG)     

![apis_sort_options_untranslated](https://cloud.githubusercontent.com/assets/13309358/25330828/9ddb08e2-28e9-11e7-8d69-3c84014cc9a5.PNG)

**Comment by bajiat** [comment]
Closing as resolved
