### ISSUE TITLE
Organization view: Sort APIs flashes user message momentarily

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2486]
# Steps  
1.Visit https://staging.apinf.io   v 0.43.0 
2.Login as admin 
3.Go to Organizations 
4.Select and click on organization (eg. Test2_organization)   
5.Go to APIs 
6.Sort APIs (eg. by Bookmarks/Newest created)  

# Findings 
Sort APIs flashes user message " This organization doesn't have any connected APIs........"  momentarily

**Comment by bajiat** [comment]
Suggestion by @brylie: Show a spinner, if the template subscription is not ready.

**Comment by 55** [comment]
Interested.

**Comment by bajiat** [comment]
@55 Please estimate.
