### ISSUE TITLE
Calls via REST proxy fails

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2491]
# Steps to reproduce

- Go to apinf.io
- Add API (name, desc, lifecycle production)
- Go to proxy settings and put
<img width="917" alt="screenshot at huhtikuuta 25 09-11-06" src="https://cloud.githubusercontent.com/assets/1927158/25371018/23375272-2997-11e7-991f-7d248c88f2a2.png">

- Try to call API via proxy. ```https://apinf.io:3002/turku_feedback_v1/services.json?api_key=oJOTXpoZxxxxxxxxxxxxxxxxxxxxxxxxxx```

Response ```{"message":"no API found with those values"}```

Original call to API is working [https://api.turku.fi/feedback/v1/services.json](https://api.turku.fi/feedback/v1/services.json)

**Comment by kyyberi** [comment]
This bug is now stopping us to continue with customer paid job. We time to fix this to have Turku APIs (3 APIs) working via apinf.io in a few weeks (sooner is better) since we need to prepare a workshop for developers and businesses and in that we use given APIs via the apinf platform.  I would assume that this kind of bug would be high in priority since it's basic functionality of the platform.

**Comment by kyyberi** [comment]
Of course there's a chance (possibly even high) that I don't know how the platform is used.

**Comment by marla-singer** [comment]
@kyyberi Try to change the settings of Proxy and change API site as
**URL:** api.turku.fi
**API base path:** /feedback/v1/

Because API umbrella has API host as "api.turku.fi" not "api.turku.fi/feedback/v1/"

**Comment by kyyberi** [comment]
Ok. I'll try.

**Comment by kyyberi** [comment]
That was the fix. Problem Existed Between Keyboard And Chair. Perhaps the UI needs a little tweaking as well.
