### ISSUE TITLE
Frontpage statistics misaligned

### ISSUE THREAD

**Issue by jawidahmadi** [apinf/platform#2493]
There is an issue at the frontpage in statistics block. The number and APIs text appear horizontally.  In the html file the <p> tag is missing for API's count. 

![statisticscount](https://cloud.githubusercontent.com/assets/24959733/25384319/8c94a284-29c8-11e7-8413-41187ab3dbe4.jpg)

**Comment by 55** [comment]
Interested.

**Comment by bajiat** [comment]
@55 Please estimate

**Comment by jawidahmadi** [comment]
The bug occurred at develop, however, the bug is not occurring at production.

**Comment by saralavanip** [comment]
@taija, Verified this resolved issue on https://staging.apinf.io v 0.46.0 and it is not reproducible.
