### ISSUE TITLE
Rate limiting info in headers (swagger) missing

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2498]
I added IP address based rate limiting to one of the APIs in apinf.io. Then I looked at the documentation (swagger). I tried a method (from swagger) and all works but in headers section I can't see any information about rate limiting. 

<img width="893" alt="screenshot at huhtikuuta 26 14-50-25" src="https://cloud.githubusercontent.com/assets/1927158/25433059/bcfcbb74-2a8f-11e7-976a-711afaad0961.png">

With Postman I was able to see rate limiting info. 

```
Access-Control-Allow-Credentials →false
Access-Control-Allow-Origin →*
Age →0
Cache-Control →no-cache
Connection →keep-alive
Content-Encoding →gzip
Content-Type →application/json; charset=utf-8
Date →Wed, 26 Apr 2017 11:48:28 GMT
Expires →-1
Pragma →no-cache
Server →openresty
Transfer-Encoding →chunked
Via →kong/0.10.1, http/1.1 api-umbrella (ApacheTrafficServer [cMsSf ])
X-AspNet-Version →4.0.30319
X-Cache →MISS
X-Kong-Proxy-Latency →0
X-Kong-Upstream-Latency →25
X-Powered-By →ASP.NET
X-RateLimit-Limit →50
X-RateLimit-Remaining →47
```

**Comment by bajiat** [comment]
@kyyberi Can you give us the name of the API so that we can try to reproduce?
