### ISSUE TITLE
Choose Dashboard chart library

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2503]
# Goal
- Proposal for handling aggregations on server side
- Proposal for chart library that can be used for both REST and eMQ dashboards

NOTE: aggregation work is ongoing in issue #2556 

# Charting library goal
Choose between the following chart libraries:
- [ECharts](https://ecomfe.github.io/echarts-doc/public/en/index.html)
- [NVD3](http://nvd3-community.github.io/nvd3/examples/site.html)

**Comment by frenchbread** [comment]
FYI the current, "fresh", implementation of an EMQ dashboard uses NVD3 charting library in addition to aggregated data requests from ES, so it can be used as a starting point. [emq-analytics-dashboard repo](https://github.com/apinf/emq-analytics-dashboard). Moveover data like `topics` lists and `event` types are also fetched from ES in separate requests, which makes the dashboard more dynamic.

**Comment by brylie** [comment]
I don't want to contribute to 'analysis paralysis', but I recently learned about a library called [ECharts](https://ecomfe.github.io/echarts/index-en.html). 

ECharts is created by Baidu and is used in API Umbrella. It seems really well designed, with
- [high level API](http://echarts.baidu.com/echarts2/doc/doc-en.html#Chart-Types)
- [many types of charts](https://ecomfe.github.io/echarts/doc/example-en.html)
- responsive design (try re-scaling the demo charts)
- [active development](https://github.com/ecomfe/echarts/graphs/contributors)
- fast rendering speed (based on Canvas library called [ZRender](http://ecomfe.github.io/zrender/))
- [custom build tool](http://ecomfe.github.io/echarts-builder-web/)
- many other [high-level features](https://ecomfe.github.io/echarts/doc/feature-en.html)

Possible downsides might include:
-  it is not based on D3, which is pretty much a de-facto data visualization framework

**Comment by frenchbread** [comment]
@brylie Nice one. `ECharts` has some good tools which you can interact with right on the chart. The scariest part though, when moving to a new charting lib, is a chance to loose data synchronisation feature between charts (IMO), but looks like it is somehow supported by ECharts:

![Image](https://ecomfe.github.io/echarts/doc/asset/img/connect.gif)

In addition, we need to decide what we need from the dashboard and what to show there. Using aggregated data means getting rid of data table (at least out of the box).

@kyyberi Do you have some vision on that?

**Comment by kyyberi** [comment]
Unfortunately I have no time to follow Github issues. Design issues such as this should be discussed face to face at the office when ever there is need and chance for it.

**Comment by frenchbread** [comment]
If the charting library is still not selected, my suggestion is to go with NVD3.

**Comment by brylie** [comment]
Alright, we are traveling right now and @marla-singer is on vacation, so I wanted to give the decision one more week or so :smiley_cat:

**Comment by Nazarah** [comment]
@brylie @frenchbread I'd have a look at today on this.

**Comment by 55** [comment]
Agree here with @frenchbread. @apinf/developers are already familiar with DC and NVD3.
ECharts is good project, but I haven't found enough reasons to switch to it. 

P.S. also it looks like 90%+ Github issues [discussions](https://github.com/ecomfe/echarts/issues) are in chinese.
