### ISSUE TITLE
Additional feature for new Swagger UI

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2504]
Swagger v3 has not only new UI but new realization as well. The main idea is to know can we realize this features and do that. 

### Additional features
- API call with api_key via Swagger UI (Related #2497)
- Try-out method
- Calling request via Proxy Backend
- Rate limiting info in headers (Related #2498). This feature is not available in old Swagger but can we implement in new one?

**Comment by brylie** [comment]
@bajiat @philippeluickx please add this to the prioritized backlog.
