### ISSUE TITLE
Mobile view: Change active menu style in navbar s.t. the menu text is visible

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2507]

**Comment by Nazarah** [comment]
![image](https://cloud.githubusercontent.com/assets/17976243/25650127/6916b24a-2fe3-11e7-94ca-1a59235f65ef.png)

**Comment by bajiat** [comment]
@marla-singer Is this related to the hard-coded text color?

**Comment by marla-singer** [comment]
@bajiat I have no idea
@55  Is this related to the hard-coded text color?

**Comment by 55** [comment]
@marla-singer I will take a look at this. As far as I remember that's because we are using the same active class color for both navbars.
