### ISSUE TITLE
Wireframe and implement RSS feed buttons for API Catalog and Organization Profile

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2508]
We now have two types of RSS feeds enabled:

- All APIs - all APIs listed in our catalog
- Organization APIs - APIs that belong to a specific organization

In order to help users find the RSS feeds we need at least two things:

- an RSS button for each type of feed
  - e.g. one on the API Catalog and one on the Organization Profile
- RSS metadata in template markup for auo-discovery
  - https://www.petefreitag.com/item/384.cfm

# Goal
- Produce one or more wireframes showing the placement of RSS buttons
- implement the RSS buttons
- implement the auto-discovery markup

# Wireframe
1. API Catalog
button style: http://fontawesome.io/icon/rss-square/
color: #ff9d00
![rssapicatalog](https://user-images.githubusercontent.com/17976243/26872716-31920a1e-4b80-11e7-9888-b2ad81028ed5.png)

2. Organization Profile
![rssorganizationprofile](https://user-images.githubusercontent.com/17976243/26872724-39f1b312-4b80-11e7-9475-c403d02644a4.png)

**Comment by mauriciovieira** [comment]
We also need to add the meta tags for autodiscovery. Related issue: #2521

**Comment by brylie** [comment]
> We also need to add the meta tags for autodiscovery.

@mauriciovieira please read closer the task description.

**Comment by Nazarah** [comment]
I need a few clarification. Correct me if my assumption is wrong:

1. RSS feed in the APInf Catalog would be used to notify user about addition of a new API. This will not work if the added API is private and that particular user doesn't have access to that API, right?

**Comment by mauriciovieira** [comment]
@Nazarah when the API is private, publishing via RSS would be a way to make it publicly available, so in my opinion RSS publication should not make any effect for private APIs.

**Comment by saransh-dev** [comment]
Hi @brylie , What action should perform after click on RSS feed button on both API Catalog and Organization Profile ? Please advise.

**Comment by brylie** [comment]
> What action should perform after click on RSS feed button on both API Catalog and Organization Profile ?

The RSS feed button should be a hyperlink to the RSS feed. In most browsers, the feed would be rendered as XML, if the user clicks. This allows someone to copy the RSS link and add it to their own RSS viewer.

Some examples can be seen on [NASA RSS Feeds](https://www.nasa.gov/content/nasa-rss-feeds) page.
