### ISSUE TITLE
Make final development decision regarding REST framework

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2513]
After considerable discussion and debate, we have reached a tentative agreement about how to develop the APInf REST API. Two teams, 'customers and communities' and 'architecture', have weighed in on the decision. 

As a follow-up, it is important to get the perspective of lead developers (@apinf/developers).

# Goal
- review discussions, packages, and issues related to this decision
  - [Define APInf platform API architecture](https://github.com/apinf/platform/issues/2336)
  - packages
    - [Simple REST](https://github.com/stubailo/meteor-rest)
    - [Restivus](https://github.com/kahmali/meteor-restivus)
    - [Restivus Swagger](https://github.com/apinf/restivus-swagger/)
      - [potential fork of Restivus Swagger](https://github.com/apinf/restivus-swagger/issues/4#issuecomment-282654120)
- review existing API code (which uses the Restivus package)
- make final decision about how to proceed with APInf REST API development

**Comment by brylie** [comment]
Another consideration would be to use Meteor webapp to handle the API request/response https://docs.meteor.com/packages/webapp.html

**Comment by brylie** [comment]
Another concern is that neither Restivus or Simple REST provide an easy way to do error handling, according to @dcantore.

**Comment by brylie** [comment]
A general idea regarding the swagger file, is that it can be generated via any means (whatever tool or process). This means we don't necessarily have to define the OpenAPI spec file as part of our API definition. The double-edge of the sword is that we want to **ensure the OpenAPI spec file correctly describes the API structure**, meaning it should be easy to maintain along with the API code.

**Comment by brylie** [comment]
@dcantatore, we would be really grateful if you could summarize your experiences with Restivus and Simple REST. Would you kindly provide us with some pros and cons that you have noticed?

P.S. I am still going to talk to our Project Manager about adding you as a collaborator to Restivus Swagger today.

**Comment by brylie** [comment]
After some research and experimentation, we decided to continue with Restivus. We also welcome @dcantatore as a collaborator on the Restivus Swagger package.

**Comment by mauriciovieira** [comment]
@brylie @marla-singer sorry for arriving late to the discussion. To be really frank, what matters for me mostly is the testability of the solution. I don't think that restivus or meteor-rest or anything else is going to be difficult to test since we can do an end2end testing approach (not ideal case) with [supertest](https://github.com/visionmedia/supertest), just like [rocket.chat](https://github.com/RocketChat/Rocket.Chat/tree/e0b584c9acad4b3321d5291a538877df1164d08f/tests/end-to-end/api) is doing.
