### ISSUE TITLE
Navbar covers content of Setting pages

### ISSUE THREAD

**Issue by manzapanza** [apinf/platform#2516]
The Navbar covers content of Setting pages like Profile, Account, Branding, Settings and Proxies.

- Go to https://nightly.apinf.io and sign in
- Visit https://nightly.apinf.io/settings/profile

![selection_151](https://cloud.githubusercontent.com/assets/1139716/25659974/863799dc-2fe0-11e7-8d78-e1e6bac8bb5f.png)

**Comment by Nazarah** [comment]
There should be equal amount of spacing (e.g. AP catalog, organizaiton catalog) added at the start of the page when this view gets loaded.
