### ISSUE TITLE
Console errors when navigating away from Organization Profile

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2517]
When navigating from the Organiation Profile, there is a console error:

```js
TypeError: Cannot read property 'apisPerPage' of undefined
```

![peek 2017-05-03 15-22](https://cloud.githubusercontent.com/assets/17307/25660480/13230b90-3015-11e7-8c9f-3e2cbd411c65.gif)

# Steps to reproduce
1. navigate to any Organization Profile
2. click a link to a different route (such as a related API)

# Likely cause
When creating a new organization, the organization settings are not defined. Hence, `apisPerPage` will not be accessible. Make sure our code is safe where we use the `apisPerPage` property.

**Comment by Vellames** [comment]
I tried to reproduce the steps to get the error, but nothing is shown on my console
