### ISSUE TITLE
Add RSS meta tag when appropriate

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/platform#2521]
# Goal

Allow rss readers to automatically add the RSS provided for each page.

# Definition of done

The generated html code for API's and Organizations should have the _link type=application/rss+xml_ meta tag.
 
More information [how to add rss autodiscovery to your site](http://www.petefreitag.com/item/384.cfm) 

# Related issues

#2310, #2478, #558, #2508

**Comment by mauriciovieira** [comment]
@bajiat please review this issue

**Comment by kyyberi** [comment]
Why is this in icebox? Lack of development resources or lack of information?

**Comment by mauriciovieira** [comment]
@kyyberi I did put in icebox so that @bajiat could take a look and prioritize.

**Comment by mauriciovieira** [comment]
@vellames please read the related issues

**Comment by Vellames** [comment]
@mauriciovieira I think that i found a problem: The api feed always return all apis
`apinf_packages/apis/collection/server/rss.js`

Can i open a issue and add a way to retrieve only a specific API?

**Comment by mauriciovieira** [comment]
@matleppa can you help @Vellames here?

**Comment by matleppa** [comment]
OK, what kind of help is needed?

**Comment by Vellames** [comment]
@matleppa i dont saw a way to get the feed of a specific API. ever i request `rss/apis/slug=someslug` the feed returns all APIs. I see that in the method, you dont expect any query params and always returns all APIs. 
Can you implement the query like organizations feed?

**Comment by Vellames** [comment]
@matleppa i dont saw any way to get a specific feed for an api, so i open this issue #2865
