### ISSUE TITLE
Unable to upload picture (logo) to API

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2529]
## Reproduce

- Go to apinf.io
- log in with github (I'm admin)
- Open https://apinf.io/apis/turku-street-maintenance-api (I added the API)
- Go to settings tab
- Click "Upload logo"
- Select picture

## Result 

At the bottom there is notification that upload is ok. Logo is never displayed in either API profile page or API listing. Logo used below. 
![turkukaupunki](https://cloud.githubusercontent.com/assets/1927158/25733027/0794d976-315e-11e7-94c3-c9570e87c626.png)
 

## Expected result

User given logo is displayed at API profile page.

**Comment by kyyberi** [comment]
I was able to upload same logo for a different API that was added 10 days ago. The above API was added after release update.

**Comment by marla-singer** [comment]
@bajiat Interested

**Comment by kyyberi** [comment]
I was able to add logo to new API I added. Still I can't add logo to the referred API.

**Comment by bajiat** [comment]
@marla-singer It's yours. Please estimate.
