### ISSUE TITLE
Change language not responsive until next click

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2530]
# Steps    
1.Visit https://staging.apinf.io   (v 0.44.0 ) 
2.Go to Footer 
3.Change language to 'Suomi'   (select 'Suomi' from drop down menu)  

# Findings  
- Single click on selected language is not responsive       

# Operating system  
Windows 10   

# Browsers  
- Mozilla Firefox   v 53.0.2   
- Google Chrome  v 57.0.2987.133   

# Screenshot  
![change_language_error](https://cloud.githubusercontent.com/assets/13309358/25736124/98c5a5a0-3178-11e7-8a3a-a0e247f4bef8.PNG)

**Comment by bajiat** [comment]
@saralavanip Can you add browser information?

**Comment by saralavanip** [comment]
@bajiat ,  Please find the browser details added to the report.
