### ISSUE TITLE
Jumbled text in Internet explorer

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2531]
# Steps  
1.Visit https://staging.apinf.io  (v 0.44.0)     

# Findings  
- Jumbled text  
- Footer misplaced    

# Browser 
Internet Explorer 11 

# Operating system 
Windows 10     

# Screenshots  
![ie_interpolated_text_footer_misplaced](https://cloud.githubusercontent.com/assets/13309358/25736310/b4063e28-3179-11e7-89a8-71f774a92e18.PNG)

![ie_logged_in](https://cloud.githubusercontent.com/assets/13309358/25736344/e96a2462-3179-11e7-811e-00ebccbcc4bb.PNG)

**Comment by 55** [comment]
Interested.

**Comment by bajiat** [comment]
@55 Please estimate

**Comment by 55** [comment]
Most probably it has something to do with recent footer or language bar work.
Investigating.

**Comment by marla-singer** [comment]
@55 The problem comes from `flex` property. I hope it will help you https://github.com/philipwalton/flexbugs

**Comment by 55** [comment]
@marla-singer yes, first thing I thought about.

**Comment by 55** [comment]
@saralavanip please confirm, when available on staging or/and nightly.

**Comment by saralavanip** [comment]
@55 , @bajiat , verified this resolved issue on staging v 0.46.0 and it is not reproducible.
