### ISSUE TITLE
Pagination missing APIs / page

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2534]
I opened API:Suomi organization view from https://apinf.io/organizations/api-suomi

## Expected result
Full rows of API cards as long as there is APIs. Last page can contain uneven row.  

## Current result
On each page, there is still space for 2 more API cards, but for some reason there is no cards. 

<img width="1164" alt="screenshot at toukokuuta 06 15-46-15" src="https://cloud.githubusercontent.com/assets/1927158/25772444/6dc9dcf8-3273-11e7-9006-272db9ef8da7.png">

**Comment by marla-singer** [comment]
@kyyberi For some reasons there sets "10 API cards per page". You can change this behavior in Settings tab -> Number of APIs per page feature

**Comment by kyyberi** [comment]
found it. Thanks
