### ISSUE TITLE
API number is inconsistent in Organization Card and Organization Profile

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2535]
# Reproduce:
1. go to https://nightly.apinf.io and navigate to organization catalog. (sign in as admin)
2. observe API number in organization card for "Daria's Organization" (shows 5 APIs)
![image](https://cloud.githubusercontent.com/assets/17976243/25792932/47141834-33d2-11e7-968d-a957f8c7e553.png)
3. Go to the organization profile.

# Result
In organization profile, only 3 APIs appear.
Found this issue only for this particular organization
![image](https://cloud.githubusercontent.com/assets/17976243/25792995/99a420f8-33d2-11e7-9be4-4ec891381f0e.png)

# Environment
* nightly.apinf.io
* Windows 8
* Chrome borwser

**Comment by Vellames** [comment]
@Nazarah 
I dont know why, but i cant access https://nightly.apinf.io/, the page never loads
I create a simple bot to add some APIS, so i added over than  200 APIS and 8 organizations, i linked some APIS with some organizations and the count was right for all them
how can i get the database to check the problem? if the error only appears for a specific organization, i think that the better solution is clone the environment to check the database

**Comment by Vellames** [comment]
I did some testing in my local environment. The situation is as follows:
Organization cards at `https: // nightly.apinf.io / organizations` are counting all apis (including private api).
The list of apis in the organization profile is counting only public apis
Thats the difference

I will open a PR to fix this :)

**Comment by Nazarah** [comment]
@Vellames thanks for finding the problem. :)
If you are accessing as APInf site admin, then you should be able to see private APIs as well.
Also If you are the manager of an Organization and a private API is connected to the organization, then you automatically become the API Manager.
In this case, you should be able to see the API as well.

**Comment by marla-singer** [comment]
@Nazarah Specifically for this case the problem is incorrect data in database. I think so because it is reproduced only for this Orgnaization
