### ISSUE TITLE
Organization cover image visible only for Admin and Organization manager

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2536]
When cover image has been set for an Organization, it should be visible for all users, who are watching the Organization. 

Now it is visible only for Admin and the Organization Manager.

**Comment by 55** [comment]
Same for logo in Organizaion and API views.

**Comment by marla-singer** [comment]
@bajiat Interested

**Comment by bajiat** [comment]
Closing as duplicate for #2543
