### ISSUE TITLE
Organization view: Logo and cover image not visible

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2543]
# Steps 
1.Visit https://staging.apinf.io  (v 0.44.0)   
2.Login as owner   
3.Go to Organization catalog
4.Select and click on any organization (eg. Test2_organization)    

# Expected Result    
Organization cover image and its logo must be visible for all users     

# Actual Result  
Organization cover image, logo not visible for owners and visible only for admins or organization managers  

# Screenshot     
![login_owner_org_logo_invisible](https://cloud.githubusercontent.com/assets/13309358/25886309/ae75d5d2-3565-11e7-93dc-dbff9cbbc8ae.PNG)   

Admins can view the organization cover image and logo;  

![login_admin_org_logo_visible](https://cloud.githubusercontent.com/assets/13309358/25886313/b5acc694-3565-11e7-9cb1-0f1c49e73e48.PNG)

**Comment by marla-singer** [comment]
@bajiat Interested

**Comment by bajiat** [comment]
@marla-singer Please estimate.
