### ISSUE TITLE
Add API redirects to API catalog view  

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2544]
# Steps 
1.Visit https://staging.apinf.io  (v 0.44.0)   
2.Login as owner   
3.Click on 'Add API'  
4.Fill the form  
5.Click on 'Add API' 
# Expected Result    
Successful 'Add API' must redirect to API 'Details' view      

# Actual Result  
Add API redirects to API catalog view

**Comment by Nazarah** [comment]
were able to produce in nightly.apinf.io

**Comment by saralavanip** [comment]
@bajiat , @brylie , Verified on staging v 0.46.0 and it is reproducible.

**Comment by marla-singer** [comment]
@bajiat @brylie I tested it on staging as well and it is not reproducible :confused:

**Comment by brylie** [comment]
@saralavanip could you please try clearing your browser cache? Also, what browser(s) have you used to reproduce this issue?

**Comment by saralavanip** [comment]
@brylie , verified clearing browser cache and it is not reproducible.Thanks!
