### ISSUE TITLE
URL issue in organization profile when clicking browser back button

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2547]
# Reproduction Steps

1. go to nightly.apinf.io and navigate to organization catalog
2. go to an organization profile.
3. observe the URL
4. click browser back button

# Result
* browser immediately doesn't redirect to Organization Catalog
* URL gets a suffix SortBy added in it
* Need another click i browser back button to go back to organization profile.
![organization url](https://cloud.githubusercontent.com/assets/17976243/25897822/26ea29e2-3592-11e7-9242-b00ab6fcb38e.gif)

# Environment
* Google Chrome
* Windows 8

**Comment by bajiat** [comment]
@marla-singer Is this by design or against the design?

**Comment by marla-singer** [comment]
@bajiat against the design
