### ISSUE TITLE
API Profile Documentation: Page needs to be reloaded to close Authorize dialogue

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2548]
# Reproduction Steps:
* Go to nightly.apinf.io
* Go to documentation tab of an API that has a valid swagger (Try APInf User API)
* click on the Authorize button

# Result
* Authorize dialog doesn't have any close button to close the dialog.
* Page needs to be reloaded or navigated back to the previous page to close the dialog
![doctabauthorization](https://cloud.githubusercontent.com/assets/17976243/25898709/f12ab4bc-3595-11e7-97ac-8332c9d7f5d5.gif)

# environment
* google chrome
* windows 8

**Comment by bajiat** [comment]
@Nazarah This is Swagger Ui, not our implementation. Did you try to click the grey area outside of the modal?

**Comment by Nazarah** [comment]
@bajiat yes I did.
Nothing happens with several mouse clicks.
Yes that might be swagger UI, but it shows bad UX for users when they need to go back to catalog page and return to the API profile from there (2 clicks) or to reload the page to navigate back to Detail tab (1 click/keypress).
If there is some means for us to close the modal from APInf itself, it should be implemented.
