### ISSUE TITLE
Filter only APIs with Swagger documentation

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#2550]
I was just searching APis from APInf to try quickly. I would like to get a working API (in beta or production state, not in design state) with working Swagger documentation. I was browsing apinf.io, but I could not find it quickly.

# Goal
- The catalog can be filtered to contain only APIs that fulfil the following two criteria:
  - API is in production or testing state
  - API has a Swagger file (uploaded or linked)

# Wireframes

1. On APInf Catalog, the control bar has a new button "APIs with Documentation" (beside My Bookmarks)
![apiswithdocumentation](https://user-images.githubusercontent.com/17976243/31227075-3e757e7c-a9e1-11e7-988b-2ae4c1afc5bf.png)

2. On clicking the button, it gets selected.
The catalog gets sorted with APIs that include documentations (swagger, openAPI or external)
Also the number of APIs containing documentations appear beside the page title.
![apiswithdocumentation2](https://user-images.githubusercontent.com/17976243/31227168-82bacb50-a9e1-11e7-94ef-0f9514383048.png)

This should be applicable for the control bar in Tabular view of API catalog.

**Comment by bajiat** [comment]
The idea is useful. I'm iceboxing it only, because it is not high-priority right now.

**Comment by Nazarah** [comment]
I'd kind of disagree about its priority.
I struggle a lot, even in production site to look for an API that has  swagger documentation.
I need to go to an API, click on documentation tab, and then return back to catalog if I don't get any swagger.
So 3 clicks are needed to decide whether or not the API is useful to me.
Having a filter to see if an API has a swagger with a filter and perhaps some indication in the PAI card would dramatically reduce all these wasted efforts.
If I become frustrated using my own product, I can only guess reactions from the end users. :-/

**Comment by kyyberi** [comment]
Should be higher in priority.

**Comment by amardeep-deligence** [comment]
In apis we already have a form for filters, So we can modify existing form and provide options for swagger API filter as well:

![suggested solution for 2550](https://user-images.githubusercontent.com/19850550/30641753-e05b887a-9e25-11e7-9a85-5fa07cfa4250.png)

**Comment by Nazarah** [comment]
@amardeep-deligence I would prefer to have a button labeled as "APIs with Documentation" appearing beside My Bookmarks. This is more visible to users. Filtering would require users to discover the functionality that they need to use filters to separate APIs with documentation. While searching for API documents, users would be concentrating search and found more than filtering results.
On clicking APIs with Documentations button, All APIs containing Swagger/OpenAPI/external non swagger documents would apppear would appear in the catalog.

**Comment by amardeep-deligence** [comment]
@Nazarah Yes it seems better. What about showing APIs for more then one Life cycle phase at a time? For that we need to make 'Life Cycle Phases' select-box multi-select right?

**Comment by Nazarah** [comment]
@amardeep-deligence An API can have only one life cycle at a time.
However, in the filter, (for example) if you want to see what APIs are in Production or Deprecated phases at the same time, I suggest to include checkboxes in the filtering option for lifecycle phases.

n.b. sorry for the late response.

**Comment by Nazarah** [comment]
@amardeep-deligence added the wireframe. Please check them out.
Please follow the button styling of the existing buttons. (in this case the group of buttons)
This should be applicable to the button for both normal, focused and selected states.

**Comment by Nazarah** [comment]
@amardeep-deligence for improving the filtering option, please open a new issue.
