### ISSUE TITLE
Missing meta tags for social media

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2552]
Current implementation does not have any (sharing and discoverability) significant meta tags 

https://apinf.io/apis/turku-issue-reporting-api

```
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/f5758bfd51dfc85b4098546f55422eac4701d250.css?meteor_css_resource=true">  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/3ba4ba26f3cdfa348c0d29520769f09d32371053.css?meteor_css_resource=true">
<meta name="fragment" content="!">
<link rel="icon" sizes="16x16 32x32" href="/favicon.png?v=2">
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

```

## Expected result

- Basic OG meta tags http://ogp.me/
- Twitter summary card tags #2551

**Comment by mauriciovieira** [comment]
#2521 is related.

**Comment by bajiat** [comment]
@brylie Please comment this, because there seem to be some restrictions on header content in run-time

**Comment by brylie** [comment]
Basically, we can only modify the platform `<body> ... </body>` at runtime. We can only make changes within the `<head> ... </head>` tags at compile time, meaning they have to be 'hard coded'. I am not sure of a way around this.

**Comment by brylie** [comment]
There are a few Q&A / discussions related to this issue, so we might be able to find a way forward:

- http://stackoverflow.com/questions/11281405/how-to-integrate-facebooks-open-graph-in-a-meteor-application
- https://webdevelopment7636.wordpress.com/2017/02/15/social-share-with-meteor/

**Comment by kyyberi** [comment]
Possibly helpful, no idea of quality or coverage regarding our needs https://github.com/lookback/meteor-seo

**Comment by mauriciovieira** [comment]
@manzapanza have you worked on something related? I can't find the issue.

**Comment by saransh-dev** [comment]
Hello Kyyberi,

I don't find the issue on https://apinf.io/apis/turku-issue-reporting-api
I am getting the meta tags:-
```html
<meta property="og:image" content="https://apinf.io/gridfs/ApiLogo/md5/9505e59749ec7b70d6a3958d7117bf45" dochead="1">
<meta property="og:title" content="Turku Issue reporting API" dochead="1">
<meta property="og:description" content="undefined" dochead="1">
<meta property="og:url" content="https://apinf.io/apis/turku-issue-reporting-api" dochead="1">

<meta property="twitter:card" content="summary" dochead="1">
<meta property="twitter:title" content="Turku Issue reporting API" dochead="1">
<meta property="twitter:description" content="undefined" dochead="1">
<meta property="twitter:image" content="https://apinf.io/gridfs/ApiLogo/md5/9505e59749ec7b70d6a3958d7117bf45" dochead="1">
```

Please advise where the issue occurs.

Thanks.

Regards,
Saransh

**Comment by kyyberi** [comment]
With: https://apinf.io/apis/turku-issue-reporting-api I dont see any mentioned element in source code

<img width="1209" alt="screenshot at marraskuuta 06 13-02-42" src="https://user-images.githubusercontent.com/1927158/32438346-d04c9112-c2f2-11e7-92e2-9ebb5fecd5d1.png">

**Comment by Nazarah** [comment]
@saransh-dev would you like to take this issue?

**Comment by saransh-dev** [comment]
Hi @kyyberi, when I inspect the page https://apinf.io/apis/turku-issue-reporting-api  and got meta tags but while checking page source then not meta tags appear.

Please check below attachment.

<img width="1680" alt="metatag" src="https://user-images.githubusercontent.com/29011434/33368849-ccc1a63a-d518-11e7-81e2-29a8c4d54c4b.png">
