### ISSUE TITLE
UI Enhancement for Add proxy view

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2553]
![image](https://cloud.githubusercontent.com/assets/17976243/25934418/5c9d1f88-3626-11e7-9a2e-23d6a4e1da81.png)

1. Add examples in texts (italic and appearing disable) to fields: (can be the same style as that of HTTP API URL
    - a. Host
    - b. Port
2. Rename HTTP API URL as **Configuration API Endpoint**
3. Give Infor Tip explaining what is TLS. The message should contain the full meaning of TLS.

**Comment by 55** [comment]
Interested.

**Comment by bajiat** [comment]
@55 Please estimate.
