### ISSUE TITLE
Reworking on Organization Profile Settings Page

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2555]
# Usability Issue
With the current Settings page, fields that get changed frequently are often not quickly accessible. User needs to browse and look carefully to find the desired field. It would be prudent if accessing and editing field were quick and easy.

# Example Fields
* TBD

# Suggestion
- Having inline editing fields in profile view to make changes on fly
- fields would include text fields/area to edit textual information and social media links and dropdown to show number of item cards appearing in the view.
- inline editing would be visible to only organization  manager
- some settings like adding organization manager, removing connected api from organization, deleting organization should stay in Settings tab, etc.

**Comment by bajiat** [comment]
Settings are not visited all the time, so I would icebox this for the time being.
