### ISSUE TITLE
Create a small project for data aggregation

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2556]
# Goal

* Share the available data structure to dashboard designer team.
* In dialog with the dashboard design, decide on the expected /data structure and granularity.
* Data from API Umbrella Elastic Search is aggregated on the server side before passing the data to client.
* There is a functioning dashboard based on the wireframe options from dashboard design team.

# Work-in-progress
The project has been started and initial work has been committed to [apinf/api-umbrella-dashboard](https://github.com/apinf/api-umbrella-dashboard).

## API Umbrella data structure
API Umbrella analytics are based on nginx log structure, and are [documented in code](https://github.com/NREL/api-umbrella-router/blob/master/test/integration/logging.js#L206-L298) ([also here](https://github.com/NREL/api-umbrella-router/blob/master/config/elasticsearch_templates.json#L85-L149)). 

We have added further details and examples in our [API Umbrella analytics structure](https://github.com/apinf/docs/blob/master/docs/develop/Integration/Elasticsearch-data-structure.md) document.

See the [related dicussion](https://github.com/NREL/api-umbrella/issues/140#issuecomment-110226345) in API Umbrella backlog.

**Comment by bajiat** [comment]
@marla-singer Would you be interested to cooperate with @brylie on this task? We would like this to be a team effort.

@mauriciovieira and @frenchbread Could you comment and mentor?

**Comment by frenchbread** [comment]
Sure

**Comment by mauriciovieira** [comment]
yes

**Comment by brylie** [comment]
NODE (added to task description):The project has been started and initial work has been committed to [apinf/api-umbrella-dashboard](https://github.com/apinf/api-umbrella-dashboard).

**Comment by marla-singer** [comment]
@brylie What is the next step?

**Comment by frenchbread** [comment]
Good work so far!

**Comment by brylie** [comment]
@marla-singer the next steps are to:

1. [choose the visualization library](https://github.com/apinf/platform/issues/2503)
2. build one or more charts
  - use a dedicated server method for each chart, so we can use custom aggregations
3. determine how charts can share/communicate filter state (based on [known API Umbrella analytics fields](https://github.com/apinf/docs/blob/master/docs/develop/Integration/Elasticsearch-data-structure.md)
  - e.g. time range, response code, etc

**Comment by brylie** [comment]
After reading and reflecting over the past week, I believe it is important to take a step back and consolidate our thinking about the dashboard project. There are a lot of ideas, sketches, and an active discussion to draw from. 

The general overview we should produce is known as a **project brief**. The project brief describes a project from a high level, taking into account stakeholders, viewers, goals, available resources, etc. I have started to draft an [APInf Dashboard Brief document](https://github.com/apinf/docs/blob/master/docs/design/dashboard/dashboard_design_brief.md), and contributions are welcome.

**Comment by bajiat** [comment]
We are now bringing the dashboard reiteration to the main apinf project. Hence, I'm closing the side project issue.
