### ISSUE TITLE
Design options for dashboard

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2557]
As a continuation of dashboard re-thinking, work in dialog with the development team to create at least low-fidelity wireframes for dashboard. Optimally, try HTML mockups with interactivity to try different chart options and see how they feel from user perspective.

# Related Issue
#2024

**Comment by 55** [comment]
Interested.

**Comment by Nazarah** [comment]
interested

**Comment by bajiat** [comment]
I will participate as much as I can, but the main assignees are @55 and @Nazarah

**Comment by Nazarah** [comment]
a few points discussed with @55 and @philippeluickx:
* does API owner wish to know which services are using her API? web based? app? specific platform?
knowing this helps the API owner to decide:
* if security measures are needed to improve for web-based services?
* if API owner shoudd put more emphasis on a particular platform (ex. most API owners are using his API for android, having specific tutorial for using the API for android apps., etc.)
* how to improve and maintain the API as a product? (more tutorial, better documentation, improving performance, etc.)

**Comment by Nazarah** [comment]
Also showing information about showing API information
* what information and visualization API owner wants to see when s/he ahs only one API
* How an Organization manager wants to see API information when he has more than 1 API to manage? (all APIs? only down APIs? or both Down and Slow APIs).

**Comment by Nazarah** [comment]
Some ideas on determining overall system status from @kyyberi 's feedback
* If API owner has 20 APIs, and every APIs have an average response time below 30 MS --> System status can be shown OK
* 98.5% calls are below 30ms --> users are happy. (plumber reference)
* 90% and more call responses are below 30ms -> status green

Here is a sample reference about how GitHub shows its overall status

**Comment by Nazarah** [comment]
We also need to consider the default view of dashboard, now that we have both API Umbrella and EMQ as proxies and chart view would be different for APIs using different proxy.
API owners should be notified that Dashboard view will differ from API to API because of the selected proxy.
This is applicable if we keep on showing the 1st API when dashboard is loaded for the 1st time.
An alternative is to prompt API owner to select an API. Afterwards, dashboard gets loaded.

**Comment by Nazarah** [comment]
A draft concept have been created about the new dashboard and associated view from ideas combined.
After a discussion with @philippeluickx and @55 we have made the following proposals:
* questions and usecases arisen from the discussion should be added as separate versions in the sketch
* (atleast 3) customer journey are needed to show the usecases
* sketches should portray 1-2 usecases and be associated with specific customer journey.

Here are some images of the the combined sketches and questions:
![fromilya1](https://cloud.githubusercontent.com/assets/17976243/26402242/20c4fadc-4092-11e7-8d4a-a4d7dbdf6205.jpg)
![fromilya2](https://cloud.githubusercontent.com/assets/17976243/26402244/20ca4352-4092-11e7-9406-8507d9fefc22.jpg)
![fromilya3](https://cloud.githubusercontent.com/assets/17976243/26402243/20c59ece-4092-11e7-8023-8fbd4af386fd.jpg)

**Open Question:** pixel perfect final wireframes for specific backlog issues regarding to dashboard epic?

**Comment by Nazarah** [comment]
Comments from the discussion with @ashakunt from API dashboard usecases

1. We need to consider dashboard features and functionality based on what kind of API we are using and monitoring. 
**Admin API** (ex. activating  business account / locking an account / creating password), 
**Service APIs** (e.g. creating a ticket, submit a feedback) and
**Organization APIs** (doing certain tasks, e.g. an API having an endpoint to send a push notification, etc.) have different purposes. So their visualization and monitoring would be different on Dashboard.

Also Dashboard should be used both for **Overview** and **Monitoring.** (suggestion of quick action as well?)

2. **Average response time of an endpoint** can be important (e.g. an API has 3 endpoints that created ticket by appointment, mobile and paper, respectively. Monitoring individual response time can be crucial)

3. possibilities of **realtime action** (e.g. Pinging an API endpoint, getting response time for that moment, etc.)

4. **No. of calls** may be suitable for some APIs, not all.

5. **Monitoring specific endpoint**. Customization of parameters that can be added to monitor for a specific endpoint. (e.g. Facebook API has 3 endpoints to view timeline in web, android and iOS. So specific services might be using a specific endpoint)

7. **Configuration of thresholds** for every metrics used in Dashboard.

8. **Notification feature**: whom to inform, how to inform (audio/video/email), scheduling notification sending time.

9. **Time period** (DD/WW/MM) may be more important for average response time, not all metrics.

10. **Predicting/showing issues** that might arise from change in value for a specific metric.

11. **History**

6. (possible future feature) **Geolocation**: overview of calls redirected to a specific server location (e,g, server located in Finland. Here, Response time and Pinging can be important in this case to know an monitor CPU overload and bandwidth usage of that specific server)

@55 could you take a look and see if I missed something?

**Comment by philippeluickx** [comment]
I have the feeling that there's a lot of ideas floating around here. There is the monitoring aspect and then the analytics. There is API content (e.g. response time), metadata (e.g. # of tickets opened on apinf.io). There is different roles and needs.

Would it make sense to first do a broad analysis of all the information that would make sense, outside the scope of dashboard? Think about what questions all the different roles have.
After this we can then focus on what knowledge is the most important and would fit in an overview.

**Comment by brylie** [comment]
After reading and reflecting over the past week, I believe it is important to take a step back and consolidate our thinking about the dashboard project. We have a lot of ideas, sketches, and an active discussion to draw from. 

The general overview we should produce is known as a **project brief**. The project brief describes a project from a high level, taking into account stakeholders, viewers, goals, available resources, etc. I have started to draft an [APInf Dashboard Brief document](https://github.com/apinf/docs/blob/master/docs/design/dashboard/dashboard_design_brief.md), and contributions are welcome.

**Comment by 55** [comment]
@bajiat should be close this?

**Comment by bajiat** [comment]
@55 yes, we should close this.

**Comment by brylie** [comment]
I have expressed concern about the current design proposals during daily. To summarize my concerns:

1. we were only presented with a single design option
    - there may have been other options discussed, but they were not presented for comparison
    - having only one design opption available, conversations turned to defending or shoehorning the proposed design onto customer needs and the 'dashboard' concept
2. developers were purposefully excluded from the design process
3. the wireframe does not meet our internal, or common, definitions of the word *Dashboard*
    - it does not summarize most information for at-a-glance, intuitive understanding
    - pagination is not a common feature for dashboards
    - the design does not help the user intuitively grasp the magnitude of values, rather it simply displays the raw numbers
    - a sparkline does not supplement the numbers, as it is also a somewhat low information data display

**Comment by brylie** [comment]
We met to create a design brief, and created a [shared definition of the concept of information dashboard](https://github.com/apinf/docs/blob/master/docs/design/dashboard/dashboard_design_brief.md#information-dashboard).

**Comment by brylie** [comment]
I found the commit related to the proposed wireframes. Here is the design proposal:

![screenshot_20170615_100703](https://user-images.githubusercontent.com/17307/27169401-70ebe936-51b2-11e7-8559-eecff5cab78d.png)

**Comment by brylie** [comment]
Also for reference, here is the [ current 'detail view'](https://github.com/apinf/docs/blob/93f7f574ce22f5b96da15e4b9cdf4508ea2113fd/docs/Wireframes/Dashboard/New%20Dashboard/apinf-dashboard-details-simple.pdf) wireframe:

![screenshot_20170615_112439](https://user-images.githubusercontent.com/17307/27172337-84825902-51bd-11e7-99d7-af48ddf5a82b.png)

**Comment by brylie** [comment]
# Characteristics of a dashboard
Stephen Few has worked extensively in the field of Information Design, and offers several characteristics common to Information Dashboards:

> Dashboards:
> - are visual displays
> - display information for specific objectives
> - fit on a single computer screen
> - are used to monitor information at a glance
> - clearly state their messages without taking up much space
> - are customized to specific requirements (for a person, group, function, or otherwise)
>
> -- [Information Dashboard Design](https://www.perceptualedge.com/library.php#Books) by Stephen Few

# Dashboard mistakes we may be making
The current proposed wireframe may be making one or more mistakes common to dashboard projects:

> - Exceeding the boundaries of a single screen
> - supplying inadequate context for the data
> - choosing inappropriate display media
> - arranging information poorly
> - highlighting important information ineffectively or not at all
>
> [Information Dashboard Design](https://www.perceptualedge.com/library.php#Books) by Stephen Few

In addition, the current design wireframes 
1. fragment the data into large cells and 
2. take the viewer away from the dashboard context to get a sense of change over time.

# Sharp contrast with current dashboard
The proposed dashboard wireframes are in sharp contrast from our current dashboard. 

The change from a rich data representation to a grid of numbers might surprise our users who are already familiar with the data dashboard.

![screenshot_20170615_114200](https://user-images.githubusercontent.com/17307/27172938-a92e6f1e-51bf-11e7-9966-fde8c7ef6349.png)

# Examples of information dashboards
We can  draw on the experience of other dashboard designers, and build a unified display similar to the following:

---

> ![Dashboard insight example](http://www.dashboardinsight.com/CMS/2ea6d7e7-1cff-4e5e-81b9-6c59a1e6545e/XLCubed_Information_Dashboard_Design.png)
> [Information Dashboard Design](https://www.perceptualedge.com/library.php#Books) by Stephen Few

---

> ![screenshot_20170615_114336](https://user-images.githubusercontent.com/17307/27173008-e446e126-51bf-11e7-93e9-d4488dd6abda.png)
> [Information Dashboard Design](https://www.perceptualedge.com/library.php#Books) by Stephen Few

---

> ![Sales dashboard example](http://www.startuplifeblog.com/wp-content/uploads/2010/04/salesdashboard.png)
>
> Sales dashboard example from [Information Dashboard Design](https://www.perceptualedge.com/library.php#Books) by Stephen Few

---

> ![screenshot_20170615_114951](https://user-images.githubusercontent.com/17307/27173264-c33e076a-51c0-11e7-85f7-ecea9da865b3.png)
> UX Magazine - [Four Cognitive Design Guidelines for Effective Information Dashboards](http://uxmag.com/articles/four-cognitive-design-guidelines-for-effective-information-dashboards)

**Comment by brylie** [comment]
Here is a sketch of one possible dashboard design based on the current wireframes and the UX Magazine article [Four Cognitive Design Guidelines for Effective Information Dashboards](http://uxmag.com/articles/four-cognitive-design-guidelines-for-effective-information-dashboards)

![dashboard-design-sketch](https://user-images.githubusercontent.com/17307/27179124-ea048f9e-51d5-11e7-8881-4c2b902a667d.jpg)

**Comment by kyyberi** [comment]
Close it

**Comment by bajiat** [comment]
Among the wireframes/designs made by @55 and @nazarah were also such that they had some of the charts incorporated into the overview site along with the numbers. Based on the discussion in the meeting we had as a team, the first view was simplified. So the design alternatives have been shared, but they were shared in a meeting.

Also, I would say that initial design should be made by the designers without the developers. Dialog takes place after the initial design. (Besides, in our case there was a developer involved from the start, since one of the designers is also a developer.)

Closing the design options issue.
