### ISSUE TITLE
Suomi view: untranslated text in 'Organization' view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2558]
# Steps  
1.Visit https://staging.apinf.io  v 0.44.0  
2.Login as admin 
3.Add organization    
4.Go to above added Organization profile 
5.Change language to 'Suomi'   

# Findings    
User info. and button title text  for 'Add Related Media' are in English language  

# Operating system    
Windows 10     

# Browsers    
- Mozilla Firefox   v 53.0.2    
- Google Chrome  v 57.0.2987.133  

# Screenshot  
![suomi_view_untranslated_text_organization page](https://cloud.githubusercontent.com/assets/13309358/26000966/839aad5e-3733-11e7-8af6-3e2a5970e793.PNG)

**Comment by bajiat** [comment]
Fixed in release 0.46.0 Closing the issue.
