### ISSUE TITLE
wireframe for "Wireframe and implement RSS feed buttons for API Catalog and Organization Profile"

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2562]
#2508

# API Catalog
1. button style: http://fontawesome.io/icon/rss-square/
color: #ff9d00
![rssapicatalog](https://cloud.githubusercontent.com/assets/17976243/26627821/63872e36-4604-11e7-971e-938626a38fa0.png)

# Organization Profile
![rssorganizationprofile](https://cloud.githubusercontent.com/assets/17976243/26627982/07ef7a82-4605-11e7-8504-9f41132a6168.png)

**Comment by Nazarah** [comment]
I am looking at use cases and asking users how they might want to use RSS feed regarding API updates. So putting this task as blocked for a short while.

**Comment by Nazarah** [comment]
A few cases where RSS button is needed are given by @kyyberi 

1. Automating social media publication. On adding a new API to an organization, the news is tweeted automatically (with/without the help of an automation tool e.g. Zapier). hashtags can be used additionally by automation tools to reach the news to the appropriate audience.

2. slackbots/ rocketchat bot can read RSS and show information about new API in given channel.

3. An assumption for not favoring automated email/weekely email digest is that developers might not be too keen on reading emails. They can unsubscribe updates from APInf catalog/organization and the email might be put into spam folder.

**Comment by Nazarah** [comment]
@mauriciovieira since you have participated in #2508, can you please review this? thanks.

**Comment by 55** [comment]
@Nazarah about RSS subscription: http://rss-tutorial.com/rss-how-to-subscribe-to-feeds.htm

**Comment by mauriciovieira** [comment]
@Nazarah the wireframes are good. we have the buttons and publish the meta tags.

**Comment by mauriciovieira** [comment]
👍 LGTM

**Comment by Nazarah** [comment]
Closing the issue.
Wireframes are attached in the original issue #2508
