### ISSUE TITLE
Staging: footer text "Powered by: Sampo Software Oy."

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2567]
Staging.apinf.io still says "Powered by: Sampo Software Oy." IIRC this was changed previously to APInf, but I might be wrong. 

<img width="823" alt="screenshot at toukokuuta 15 22-02-00" src="https://cloud.githubusercontent.com/assets/1927158/26074357/2d95644c-39ba-11e7-855c-e22317885109.png">

**Comment by bajiat** [comment]
Thanks for noticing this. The text can be changed from Branding settings: Site footer. I have fixed it now for staging.

**Comment by kyyberi** [comment]
This should not be in branding settings. Powered by APInf should be hard coded.
