### ISSUE TITLE
Using BootStrap Primary and Accent Colors to customize Branding

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2574]
# Definition of Done
- [ ] Branding Settings includes new Color picker fields **Primary Color** and **Accent Color**
- [ ] Above controllers follow BootStrap's guideline for choosing primary and secondary colors throughout the site
- [ ] Primary Color affects: Navbar, Footer
- [ ] Secondary Color affects: frontpage buttons, primary action buttons (Add API, Add Organization), most buttons in API profile/ Organization Profile (except Delete), front page overview pane, Chatbar (in future)
- [ ] text color on elements with primary/secondary color gets chosen based on contrasting color (using CSS).
- [ ] Info icon beside label should indicate how the colors affect which elements in the site.

# Wireframes:
![1e08fa1e-3638-11e7-9b08-1b42e9fc0fcd](https://cloud.githubusercontent.com/assets/17976243/26141250/97b901b0-3ae3-11e7-9a7b-80eab858258e.png)

**Comment by Nazarah** [comment]
**Areas affected by Primary Color**
* Navbar (web view) and Topbar (mobile view)
* Footer
* Settings Menus (Profile, Account, Branding, Settings Proxy)

**Areas affected by Accent Color**
* Add API button (add API view)
* Add Organization button (catalog and add organization view)
* API profile
      - All action buttons (Except Save and Delete)
* Organization profile
      - All action buttons (Except Save and Delete)

**Open question**: do we need to use accent color in Save buttons? It seems ok if we leave Save as green and Cancel as grey

**Comment by preriasusi** [comment]
Branding is now done in next. Old APInf branding is not a priority. Closing now.
