### ISSUE TITLE
Multi proxy: Dashboard analytics not shown

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2587]
# Steps  
1.Visit https://staging.apinf.io v 0.44.1 
2.Login as admin 
3.Add API 
4.Connect to proxy (eg. staging/API-Umbrella New /Second nightly)   
5.Get API key 
6.Call API  
7.Go to dashboard  
8.Check analytics for the above API 

# Findings     
- Analytics not shown though API call is successful. It shows user message "No data found...."    (screenshot 1)    
- Case 1: Change proxy->Call API->Dashboard->Result: Analytics not shown   

- Case 2: Dashboard shows analytics if API connected to proxy: 'Nightly Umbrella' 
Steps:   
Add API ->connect to proxy: 'Nightly Umbrella'->Call API: shows 404 error->Go to Dashboard->Result: shows API analytics, API Request Timeline not shown  (screenshots 2,3 & 4 below)       

# Screenshots  

Screenshot 1    
![dashboard_analytics_no_data_found](https://cloud.githubusercontent.com/assets/13309358/26235393/84015d20-3c73-11e7-8cb5-69c0d0564099.PNG)   

Screenshot 2   
![api_call_404_error](https://cloud.githubusercontent.com/assets/13309358/26235426/b7471e7c-3c73-11e7-9d18-23e8201053c3.PNG)    

Screenshot 3 
![api_nightly_umbrella_proxy_dashboard_analytics](https://cloud.githubusercontent.com/assets/13309358/26235486/19f612bc-3c74-11e7-8988-8415595ca2c8.PNG)

Screenshot 4    
![dashboard_analytics_data](https://cloud.githubusercontent.com/assets/13309358/26235560/a31a2f2e-3c74-11e7-8083-5e7bceaf01ac.PNG)

**Comment by bajiat** [comment]
Closing this, since this bug concerns the old dashboard.
