### ISSUE TITLE
Me as a Apinf.io user can't see my own email address.

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#2589]
Login to Apinf.io. You can see your username, but you can't see your email address.

**Comment by marla-singer** [comment]
Yeah, I agree, this feature is useful and easy for developing.

@Nazarah I prepared couple screen how it can look. Can you please leave your feedback?

1. Display e-mail in input field which has attribute "readonly" and has the light gray background

![joxi_screenshot_1499244024311.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2814d778e3d0f005c2de7/125516c66e82c728ace21e0d46e29b822abd90aa9decba4db755ff801617732a7056f77f20d7b77bee13394d4d1f0cf31b0d0c00eef39b2ea3b43f22df585fedd7395a76cf3812acb8d41eb857bd25995397f4edd4189fb5646fb2c99d452c1d041288fb543ca29d4fc95dfe43e14947e9.png)

2. Display email as plain text
![joxi_screenshot_1499244024311 (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2814d778e3d0f005c2de7/125516c66e82c728ace21e0d46e29b822abd90aa9decba4db755ff801617732a7056f77f20d7b77bee133b495e465cb053181d1ba6acda6fb4bc2e758f5e08bf84690b74c06914aeb1871cbf01ec218c1982b3ae965e82b96371b8d6d6056b5c17129bfd5b3fa19d42c15af24fe04b50ac1b3e71ab.png)

**Comment by Nazarah** [comment]
Good work @marla-singer 
Just as a suggestion, perhaps place the email after the user name?
Also, as a future implementation, should we have a password change option there as well?

**Comment by marla-singer** [comment]
> Just as a suggestion, perhaps place the email after the user name?

@Nazarah Yes, we can. 

> Also, as a future implementation, should we have a password change option there as well?
A password change option is available in Account section

**Comment by Nazarah** [comment]
Let's go with the 2nd version!!
