### ISSUE TITLE
Browser tab shows different message instead "APInf" name

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2591]
# Reproduction Step

* Go to apinf.io 
* Look at Browser Tab (or hover the mouse on it)

# Result
"Get Control of your digital resource" message appears on browser tab and tool tip
![image](https://cloud.githubusercontent.com/assets/17976243/26238496/00336222-3c82-11e7-8557-86d27d45e746.png)

# System
* Windows 8
* Chrome (latest)

# Suggestion
* "APInf - Develop. We do the REST." this message sound more suitable to appear on browser tab.
This represents both our Platform name and slogan.
* the current message can also be kept with "- APInf" inserted as suffix (check homepages of [Dropbox Business](https://www.dropbox.com/business), [Airbnb](https://www.airbnb.com/) in browser tab for example.)

**Comment by matleppa** [comment]
This would probably need in Branching collection  a new field (in addition to field siteTile) perhaps siteWindowTitle, to contain the text for browser tab.

**Comment by deligence-dharmendra** [comment]
Hi, @matleppa
we need to add new field "siteWindowTitle, to contain the text for browser tab and existing site title contain the text for branding slogan. i'm right?

**Comment by deligence-dharmendra** [comment]
Hi, @matleppa
Please ignore (upper) first comment. we need to add new field "siteWindowTitle, to contain the text for browser tab and existing site title contain the text for branding site title. i'm right?

**Comment by 55** [comment]
@deligence-dharmendra window title should consist of siteTile + pageTitle (which is unique to every page: API Name, Settings, Branding, API Catalog etc.). No need for new field at Branding.

**Comment by deligence-dharmendra** [comment]
Hi @55 
Currently browser tab title and branding site title value comes from the same field "branding site tile",
if we don't add new field for browser tab title and only concatenate page title value with site tile then.
branding title would be appears like-> "Get control of your digital resources"
and browser tab would be appears like  -> "Get control of your digital resources Branding"
Please advise.

**Comment by 55** [comment]
@deligence-dharmendra you are talking about `siteSlogan`.

My suggestion is to construct window title from `siteTitle`, which usually an application name (APInf) + `pageTitle` (API Name, Settings, Branding, API Catalog etc.).

Final title will be: **APInf - Branding** or **APInf - API Catalog** etc.
