### ISSUE TITLE
New localisation round

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2595]
Proofread English UI texts (source). Add missing translations and update changed UI texts for the Finnish language.

# Definition of done
* [x] Proofread the new/uppdated English UI texts. 
    * [ ] Change if needed
* [x] Upload texts to Onesky
* [x] Translate into Finnish
* [ ] Organize proofreading for the Finnish UI texts
* [ ] Export texts from Onesky
* [ ] Make a PR for Finnish UI texts

**Comment by Nazarah** [comment]
@bajiat let me know if I can help with Proofreading the English texts
