### ISSUE TITLE
Cannot read property 'localeCompare' of undefined (on Dashboard)

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2598]
# Original report
@bajiat reported this as a continuation in issue #2528

> admin cannot see a dashboard, while an API owner can.

> Screenshot of dashboard when logged in as admin:
<img width="918" alt="apinf-io dashboard for admin" src="https://cloud.githubusercontent.com/assets/11626388/26254831/8738e506-3cc0-11e7-9b6e-9b326809110a.png">

@marla-singer found a console error:

> @bajiat There is another error
```
Exception in template helper: TypeError: Cannot read property 'localeCompare' of undefined
    at https://apinf.io/f17eb29eefa56790710e0243be547d699ce26efc.js?meteor_js_resource=true:416:25757
    at Array.sort (native)
    at Array.sort (https://apinf.io/swagger/bundle.js:1:23319)
    at Object.proxyBackends (https://apinf.io/f17eb29eefa56790710e0243be547d699ce26efc.js?meteor_js_resource=true:416:25722)
    at https://apinf.io/f17eb29eefa56790710e0243be547d699ce26efc.js?meteor_js_resource=true:119:31360
    at https://apinf.io/f17eb29eefa56790710e0243be547d699ce26efc.js?meteor_js_resource=true:119:17194
    at https://apinf.io/f17eb29eefa56790710e0243be547d699ce26efc.js?meteor_js_resource=true:119:31993
    at Function.e._withTemplateInstanceFunc (https://apinf.io/f17eb29eefa56790710e0243be547d699ce26efc.js?meteor_js_resource=true:120:5707)
    at https://apinf.io/f17eb29eefa56790710e0243be547d699ce26efc.js?meteor_js_resource=true:119:31900
    at Object.p.call (https://apinf.io/f17eb29eefa56790710e0243be547d699ce26efc.js?meteor_js_resource=true:136:1929)
```

**Comment by brylie** [comment]
This seems related to the orphan proxy backend on apinf.io. The specific line of code is this:

```
// Sort the proxy backend list by API name
proxyBackends.sort((a, b) => {
  return a.apiName.localeCompare(b.apiName, language);
});
```

When there is an orphan ProxyBackend, there is no corresponding API name.

**Comment by brylie** [comment]
How do you propose we avoid this problem, and related problems? E.g. should we manually clean up the database? Write a migration that removes all orphaned ProxyBackends?

**Comment by bajiat** [comment]
The orphaned proxy backend in question was manually removed. Should we close this issue or icebox it?

**Comment by brylie** [comment]
My vote is to close the issue.
