### ISSUE TITLE
Wireframe(s) for API Umbrella and eMQ dashboard

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2608]
# Description
Based on ideas from #2557
* get familiar with available data from ElasticSearch: https://github.com/apinf/docs/blob/master/docs/develop/Integration/Elasticsearch-data-structure.md
* Select charting library, related issue #2503
* Collaborate with developers
* Divide the ideas to "implement now" and "implement later"
* Produce final low-fidelity wireframe(s) to select from for the "implement now" ideas

**Comment by 55** [comment]
I got familiar with available ElasticSearch data, charting library was selected. There was a meeting with developers and their ideas were included and considered. 

Based on overall work, including ideas from #2557: 
- ideas to "implement now" with low-fidelity wireframe(s) are available here:
https://github.com/apinf/docs/tree/master/docs/Wireframes/Dashboard/New%20Dashboard

- "implement later" a.k.a "ideas":
https://github.com/apinf/docs/tree/master/docs/Wireframes/Dashboard/New%20Dashboard/Future%20implementation%20and%20ideas

**Comment by brylie** [comment]
Here is an example dashboard design, based on our discussion of **user needs** and the [dashboard design brief document](https://github.com/apinf/docs/blob/master/docs/design/dashboard/dashboard_design_brief.md):

![screenshot_20170615_171644](https://user-images.githubusercontent.com/17307/27185626-9eda89a6-51ee-11e7-9da1-e35cae13fce3.png)

I can add annotations regarding specific design elements ASAP.

**Comment by brylie** [comment]
Here is an example dashboard design, based on our discussion of **user needs** and the [dashboard design brief document](https://github.com/apinf/docs/blob/master/docs/design/dashboard/dashboard_design_brief.md):

![screenshot_20170615_171644](https://user-images.githubusercontent.com/17307/27185626-9eda89a6-51ee-11e7-9da1-e35cae13fce3.png)

I can add annotations regarding specific design elements and the user needs they serve ASAP.

We are also working to build Elasticsearch queries/aggregations to support the dashboard charts.

**Comment by Nazarah** [comment]
@brylie please do Mobile 1st design approach to see how the implemented view actually looks in mobile screen.

**Comment by Nazarah** [comment]
Also in future implementation, we may need to accommodate endpoints to Dashboard, indicating how many out of total endpoints of an API might need attention and preferably some list of them. Please consider this aspect while designing or implementing.

**Comment by brylie** [comment]
>  please do Mobile 1st design approach to see how the implemented view actually looks in mobile screen.

It looks like we can use Bootstrap to show/hide page elements on mobile views:

http://getbootstrap.com/css/#responsive-utilities

E.g. we can have a slightly different mobile-first view that hides the charts and shows only the numbers. We might be able to figure out a way that mobile users could toggle the charts' visibility too.

**Comment by brylie** [comment]
> Also in future implementation, we may need to accommodate endpoints to Dashboard, indicating how many out of total endpoints of an API might need attention and preferably some list of them.

Yes. That sounds similar to how API Umbrella allows 'drill-down' analytics. I.e. it is aggregating the same statistics at different "levels" of the API path:

- /example-api/
- /example-api/level-1/
- /example-api/level-1/level-2/
