### ISSUE TITLE
Organization 'Suomi view': User info. text shown in both English and Finnish languages

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2609]
# Steps  
1.Visit https://staging.apinf.io  v 0.45.0 
2.Login as admin 
3.Add organization  
4.Connect APIs to organization  
5.Go to above added organization  view  
6.Change language to 'Suomi'  

# Findings 
- Shows user info text "The organization doesn't have any featured APIs....." in both Finnish and English languages
    

# Screenshot  
![org_view_partially_translated](https://cloud.githubusercontent.com/assets/13309358/26540211/f00027da-4458-11e7-839b-88443478f2b1.PNG)

**Comment by bajiat** [comment]
The texts displayed in the screenshot are two different texts: one is for featured APIs, one is just APIs connected to the organization. The one above was not translated yet, the one below was already translated. 

Closing as resolved: both UI texts are available in Finnish in the 0.46.0 release.

**Comment by bajiat** [comment]
<img width="744" alt="organization apis" src="https://user-images.githubusercontent.com/11626388/27538354-31de778c-5a80-11e7-8437-d17799d8dd00.png">
