### ISSUE TITLE
Page numbers on dashboard

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2610]
when you have full list of requests. Pages shows 1 more page that you actually have. You cant navigate to this extra page with buttons (eg. you have 20 requests and display 10 requests each page. The indicator says 1/3 and 2/3 but you can't go to 3/3 and it would be empty anyway).

**Comment by bajiat** [comment]
@wuder4 Can you provide some more context to this? Maybe a screenshot?

**Comment by wuder4** [comment]
![dashboard_pagenumbers](https://user-images.githubusercontent.com/28555452/27073086-4af0ded6-502b-11e7-8c93-ed8118e0d141.png)
Here you can see page numbers go up to x/6. When i'm on page 5 I cant click next page anymore.
In this API I have 50 requests and it shows 10 per page.

**Comment by bajiat** [comment]
Closing this as 'wontfix', since we are currently reimplementing the dashboard
