### ISSUE TITLE
Add ability to login with FIWARE account (OAuth 2.0)

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2611]
FIWARE offers OAuth 2.0 authentication. Determine how to enable a 'Login with FIWARE' option on the accounts login screen, similar to the Github login. 

# Goal
Offer FIWARE login as an option for end-users, so we can align with the FIWARE initiative.

**Comment by Nazarah** [comment]
does it support single user credential service? (e.g. users wishes to register and signin to APinf using his gmail account?)

**Comment by brylie** [comment]
FIWARE authentication would be an option similar to GMail. Internally, we would store information related to the external authentication service, as we currently do with Github authenticated users.

**Comment by bajiat** [comment]
In addition to enabling the login in login screen, we would need a setting for the IdM. Could the IdM settings have their own page? The page should be accessible from the same menu as Settings and Proxies.

**Comment by bajiat** [comment]
I have created a separate issue for  login Settings
