### ISSUE TITLE
Sorting according to bookmarks or rating

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#2613]
I go to apinf.io. I want to see best rated or most bookmarked apis.

I choose to sort according to bookmarks or ratings.

The result is as a default the most bookmarked/best rated APIs are shown last in a list.

--- Added by @bajiat 2017-08-29 ----

# Proposal
* [ ] Remove toggling buttons
* [ ] Keep options for sorting by
  * [ ] Name
  * [ ]  Number of bookmarks > rename as Most popular?
  * [ ] Rating > rename as Highest rated?
  * [ ]  Date created > rename as Latest?
* [ ] The following always must be sorted in descending order: Number of bookmarks, Rating, Date created
* [ ] For alphabetic sorting there are two options:
  * only have ascending sorting
  * Add two separate items in menu Name A-Z and Name Z-A
* [ ] The implementation must not remove the language-specific sorting for names (can be tested by adding APIs that start with Ä and Ö that must be sorted after Z in ascending sorting)

# Wireframe
![image](https://user-images.githubusercontent.com/17976243/29912457-68837272-8e3a-11e7-858f-a6714625eb1b.png)

**Comment by Nazarah** [comment]
We can use the sorting functionality for APIs connected to an organization.
Currently APIs connected to an organization can be sorted as: Alphabetically (A -Z), Most Recently Created, most bookmarks and highest starratings.

**Comment by bajiat** [comment]
@preriasusi  Thanks for the feedback. Each sorting option can be  toggled to sort ascending or descending.  

The default is ascending , which mostly makes sense for alphabetic sorting. Descending sorting as the default would make sense for Number of bookmarks, Average rating and Date created.  But it is possible to toggle using buttons for ascending and descending sorting.

One option to enhance this would be to remove the toggle altogether and choose sensible defaults for each of the sorting options. 

Labeling this as enhancement.

**Comment by bajiat** [comment]
As a reference, see Sorting options from API Marketplace:
![mashape sorting.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/551116a6d52f6a7100417fce/125516c66e82c728ace21e0d46e595892b8393accffab051b054fe936b0a65633b0ba92e7391a172fd172e535c0d1ba815585910f9fb802ea5b63c268b5b5dead47f4366846c4ff8e7df46f554f832815d84bfb68b49c0ec3d25e08288463a1e070ac4.PNG)

**Comment by Nazarah** [comment]
@preriasusi what do you think about the following options?
Most Bookmarked
Highest Rating
Most Recent
Names (A - Z)
Names (Z - A)

@bajiat Currently we have the options My APIs and My Bookmarked as buttons on the sorting controller. 
Do you want them to be included in the sorting dropdown as well?
I would suggest against it, as these options are more for Quick Access, rather than sorting.

**Comment by bajiat** [comment]
I would leave the My APIs and My Bookmarked as buttons and keep them out of sorting. They are filters rather than sorting options.

**Comment by Nazarah** [comment]
@bajiat @preriasusi wireframe is added. Please have a look and leave your feedback.

**Comment by bajiat** [comment]
Looks good to me. Would it be too bold to rename "Most bookmarked" as "Most popular"?

**Comment by Nazarah** [comment]
@bajiat since these are options within a menu, I'd suggest to keep them as normal text. I can't recall if I have seen some options within sorting menu to be bold to differentiate from others.
Is there any reason u wish to make them bold?

**Comment by Nazarah** [comment]
>@bajiat since these are options within a menu, I'd suggest to keep them as normal text. I can't recall if I have seen some options within sorting menu to be bold to differentiate from others.
Is there any reason u wish to make them bold?

@bajiat apologies for not getting the comment at 1st turn. :P 
The option names sounds better.
I'd add them  in the wireframe.

**Comment by saransh-dev** [comment]
@marla-singer @brylie Hi, I have almost implemented this task but I have little confusion regarding "The implementation must not remove the language-specific sorting for names (can be tested by adding APIs that start with Ä and Ö that must be sorted after Z in ascending sorting)"

 As I have researched on package `kurounin:pagination`, there is no option to get result and sort on the basis of Ä and Ö.

 I think I need to implement some extra code for this on client side after getting data.

 Please advise.

**Comment by marla-singer** [comment]
@saransh-dev We already have the implementation for local name sorting. 
https://github.com/apinf/platform/blob/develop/apinf_packages/api_catalog/client/api_catalog.js#L167-L170

**Comment by Nazarah** [comment]
@saransh-dev I would be adding the wireframe with finalized option names later.
But for your convenience, I am writing down the option names in the sorting dropdown:
Most Bookmarked
Highest Rating
Most Recent
Names (A - Z)
Names (Z - A)

@bajiat I had a thought and decided to go with "Most Bookmarked". Because if we put "Most Bookmarked" and "Highest Rating" together, it would appear indicating the same information (i.e. how much an API is evaluated by users with star rating) instead of distinguishing them in terms of information type.

**Comment by saransh-dev** [comment]
@Nazarah I have renamed the options as you suggested above. Please review below PR.
https://github.com/apinf/platform/pull/2886

**Comment by bajiat** [comment]
@Nazarah 

I think Most popular and Highest rating are different. Rating refers to quality, popularity would be how many people have bookmarked. (Popularity could also be how many users the API has, but at the moment we can't use that as a measurement.)
