### ISSUE TITLE
Development setup

### ISSUE THREAD

**Issue by shaliko** [apinf/platform#2620]
The goal is to get rid of the requirement for work with nightly on development setup.

My general setup for Ruby on Rails and Go lang app:

1) docker-compose.yml for development that will run few services required for development like postgres, redis, Elasticsearch.
2) `DB seed` task that will fill DB by data that is required by the application across all environments (development, production, staging).
3) `DB sample` task for populating the database with a small set of realistic sample data so that as a developer you can use the application without having to create a bunch of stuff or pull down production data.

So new developer just need run docker-compose up for start services (DB, queue, etc...) and run `DB seed`,  `DB sample`.

1) We can configure docker-compose for Apinf that will start Api-umbrella, MongoDB, ElasticSearch, MQTT proxy, etc...
2) Write `DB seed` and `DB sample` tasks. 
3) Probably for API-umbrella we can't create a proxy in `DB sample` task because getting API key require generate it from the browser, but for that case, we can provide small instruction.
4) Never touch Nightly in development.

//cc @mauriciovieira @brylie

**Comment by bajiat** [comment]
Work estimate from @shaliko and @marla-singer :
Step 1: 1 day
Step 2: 1 day
Step 3: 3-5 days,

Needs to be verified that the approach will work for Windows developers.

**Comment by ilarimikkonen** [comment]
not needed anymore
