### ISSUE TITLE
Configure continuous deployment 

### ISSUE THREAD

**Issue by shaliko** [apinf/platform#2621]
As a developer, I want to deploy a new version of Apinf to all our setups when a new release is ready. So we need configure continues deployment on the new release.

The goal:

1) Configure all setups for check new release (new available [version of Docker image](https://hub.docker.com/r/apinf/platform/tags/)).
2) Do not create release until code will be tested on staging.
3) Configure Travis CI for build new Docker release image when the release will be created on GitHub.
4) All our setups will detect the new image, pull it and restart.

I see only one stopper for that task before setup continues deployment we need to implement that feature "Capture and track application exceptions" #1986, otherwise, we will not detect if something wrong on customer setup.

//cc @bajiat @brylie @mauriciovieira

**Comment by brylie** [comment]
@ashakunt would you also add your thoughts here? Please also share your document containing the CI vision.

**Comment by brylie** [comment]
> I see only one stopper for that task before setup continues deployment we need to implement that feature "Capture and track application exceptions" #1986

@shaliko I propose we run a small experiment with one of the exception tracking solutions under discussion. That way we can have some practical experience to determine a way forward. Thoughts?

**Comment by shaliko** [comment]
> @shaliko I propose we run a small experiment with one of the exception tracking solutions under discussion. That way we can have some practical experience to determine a way forward. Thoughts?

Sounds right to me. In general, that is 2-4 hours of the work task but delayed for a log time. @marla-singer can manage that task.

**Comment by shaliko** [comment]
"2-4 hours" estimation for #1986

**Comment by brylie** [comment]
cc: @bajiat
