### ISSUE TITLE
Buttons in the UI must have an ID associated with them

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2623]
Almost none of the buttons at apinf.io have valid way to locate them in automated testing. Common way to locate them is to add unique id to the buttons.

**Comment by ashakunt** [comment]
@wuder4 can you please point out the buttons and their locations which do not have the IDs?

**Comment by wuder4** [comment]
Its easier to say that any bar that you can add text to has ID:
![searchbar id](https://cloud.githubusercontent.com/assets/28555452/26715179/53bcfd62-477d-11e7-90c2-94ad359e5aa7.png)  
Then there are 3 buttons "More APIs" above contact us, language selection button and "about" button at the end of the page.

**Comment by ashakunt** [comment]
Thanks, @wuder4. @brylie @bajiat Not only buttons, but all the UI elements in the page dom should have valid and unique IDs. This is a requirement for Automation Testing.

**Comment by mauriciovieira** [comment]
@wuder4 I think this can be added on the go, while creating the automated tests. I added some ids/classes while doing #2522

**Comment by wuder4** [comment]
When in "add API" page the text fields have id but they are random and change every time you reload the page.

**Comment by bajiat** [comment]
I have given the task to add id's to @wuder4 at least for the id's he is stuck with and has identified as missing. Some mentoring may be required from @55, @mauriciovieira or @ashakunt concerning the contribution process and how to add the id's and what is the correct format.

**Comment by mauriciovieira** [comment]
ok. I think it is a good opportunity to document a convention on our [guidelines](https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md#contributing-code) if you find current code not standardized, @wuder4
