### ISSUE TITLE
Organization view: Sort APIs shows user info. text momentarily

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2627]
# Steps  
1. Visit https://staging.apinf.io  v 0.45.0 
2. Login as admin 
3. Add organization  
4. Connect APIs to organization  
5. Go to above added organization  view  
6. Sort APIs (eg. select options Newly created/Ratings/Bookmarks)  

# Findings   
Select 'Sort by' options from drop down menu shows user info text "The organization doesn't have any featured APIs momentarily"    

# Screenshot

![organization_sort_by_user_info_text](https://cloud.githubusercontent.com/assets/13309358/26729618/d4e3f074-47b6-11e7-9dc7-42d10018e927.PNG)

**Comment by marla-singer** [comment]
@saralavanip It isn't bug. There are two different parts with APIs and featured APIs.
Features APIs blog is appeared or disappeared using Pin
![joxi_screenshot_1499169254195 1](https://user-images.githubusercontent.com/20643403/27829164-d11125fe-60c8-11e7-92fc-6b43cb24afc3.png)
![joxi_screenshot_1499169254195](https://user-images.githubusercontent.com/20643403/27829170-d3870f4c-60c8-11e7-91df-c6c47abefad0.png)

@brylie @bajiat On my opinion we can close this issue

**Comment by bajiat** [comment]
Closing as wontfix.
