### ISSUE TITLE
Privacy policy and Terms of use start with site title

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2628]
I have added the Privacy policy and Terms of use texts to apinf.io. When I view the texts in the respective paged the title of the page contains the site slogan "Get control of your digital resources" even though that is not part of the added text in branding settings.

Screencapture from Branding:
<img width="435" alt="privacy policy in branding" src="https://cloud.githubusercontent.com/assets/11626388/26826695/a5d44478-4ac2-11e7-8f23-9fd5d4e2b533.png">

Screencapture from the Privacy policy page with the Site slogan as a part of the header:
<img width="897" alt="privacy policy page" src="https://cloud.githubusercontent.com/assets/11626388/26826799/0f57fcf0-4ac3-11e7-8de3-df47918c6571.png">

**Comment by saralavanip** [comment]
@bajiat , observed similar issue on staging v 0.45.0 . 
Screenshot:   
![privacy_policy_start_with_site_title](https://user-images.githubusercontent.com/13309358/27132962-4db4bc7a-5119-11e7-8b5f-8991ea9acc4e.PNG)

**Comment by 55** [comment]
@saralavanip we need to wait for new release deployed there. Its fixed locally and it's already on nightly.

**Comment by saralavanip** [comment]
@55 , Ok, thanks for the update.

**Comment by saralavanip** [comment]
@bajiat  , @55 , Verified this resolved issue on https://staging.apinf.io v 0.46.0 and it is not reproducible.
