### ISSUE TITLE
Connect API to eMQ proxy shows 'Get API key' 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2633]
# Steps  
1.Visit https://staging.apinf.io   v 0.45.0  
2.Login  
3.Add API  
4.Connect above API to eMQ proxy  
5.Click on 'Save and Publish'      

# Findings    
- Shows 'Get API key' button and when clicked displays error message "No proxy found"  
- shows status  as 'Processing....' for indefinite time

# Screenshot    
![emq_get_api_key](https://user-images.githubusercontent.com/13309358/26929386-2a4288be-4c62-11e7-80b7-63ae03ebee40.PNG)

![emq_get_api_key_no_proxy_error](https://user-images.githubusercontent.com/13309358/26929310-ce97646c-4c61-11e7-9174-231e6f84db8e.PNG)

**Comment by frenchbread** [comment]
Hmm.. I'm guessing this has been fixed: https://github.com/apinf/platform/issues/2573, https://github.com/apinf/platform/pull/2597

**Comment by marla-singer** [comment]
@frenchbread I think it will be applied on the next release

**Comment by bajiat** [comment]
@saralavanip Please verify this bug report on release 0.46.0 on staging

**Comment by saralavanip** [comment]
@bajiat , verified on staging v 0.46.0 and it is not reproducible. Hence closing this issue.
