### ISSUE TITLE
Titles for logo and cover photo informations on Branding page

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2635]
In Branding page all parameters but Logo and Cover photo have titles. 
In case they are not given, in upload button there is mentioned, which parameter is in question. However, when they are given, there is only the picture and remove button for each.

# Goal
* [ ] Add a title for "Site logo" to Branding settings
* [ ] Add a title for "Cover image" to Branding settings

See wireframe for placement of titles.

**Comment by bajiat** [comment]
<img width="428" alt="branding wireframe" src="https://user-images.githubusercontent.com/11626388/29812181-71eaf9da-8cae-11e7-9928-e9cc3f1628c2.png">

**Comment by bajiat** [comment]
<img width="428" alt="branding wireframe" src="https://user-images.githubusercontent.com/11626388/29812224-91f72190-8cae-11e7-869e-2adbbf10ba6c.png">

**Comment by bajiat** [comment]
<img width="428" alt="branding wireframe2" src="https://user-images.githubusercontent.com/11626388/29812251-a416a788-8cae-11e7-95b6-d70f288eaead.png">

**Comment by bajiat** [comment]
@Nazarah Please review the suggested titles?

**Comment by Nazarah** [comment]
@bajiat ok from my side

**Comment by saransh-dev** [comment]
@bajiat @Nazarah @matleppa Please tell me the branch name from where I will get the code of site logo and cover image. Still, i have take clone from `develop` branch and I am not able to see the portion so site logo and cover image on the web app. Thanks.

**Comment by saransh-dev** [comment]
I got the code. Thanks
