### ISSUE TITLE
Implement server-aggregated Nr of calls over time chart

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2637]
To get the server-aggregated dashboard kickstarted, we will start with two charts: number of calls over time and response times charts. This task is about implementing the Number of calls chart.

# Goal
* Proxy call logs (from API Umbrella) for the selected API backend are aggregated on the server side for the current timeframe
* Chart is created based on the server-aggregated data
* Simplest possible first implementation: week is the default timeframe 
* Chart is tested with a heavy-set of data for calls, utilise for example a script that automatically makes calls to one API

# Wireframes
To go to the chart for Response time chart, User needs to click on any place of the overview pane (API name dropdown, metrics card).
![image](https://user-images.githubusercontent.com/17976243/27372433-502d50bc-566d-11e7-91c9-3070c561fd64.png)
On click, user is navigated to a new page, where s/he can see the average response time chart.
![image](https://user-images.githubusercontent.com/17976243/27373941-bc17f124-5672-11e7-962e-9967fffb846f.png)
A line chart should be used to represent the number of API calls like [this example](http://nvd3.org/examples/lineWithFocus.html)
The x-Axis should indicate the timeline in weekly basis (Last 7 days)
The y- axis should indicate Number of API calls in (in thousand units? like 1K, 5K, etc.)

**Comment by bajiat** [comment]
@matleppa has promised to co-pilot

**Comment by brylie** [comment]
Related issue in greenfield project:

- https://github.com/apinf/api-umbrella-dashboard/issues/3

**Comment by bajiat** [comment]
Closing this experimental issue
