### ISSUE TITLE
Create Swagger file(s) for APInf API(s) to apinf.io

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2638]
Since our platform contains a working API, which allows registered users to interact with the platform through REST in addition to the GUI, the production version of the Swagger file must be published in apinf.io. Currently, apinf.io only contains a design version for the Catalog API.

# Options
* Publish the documentation as single Swagger file.
* Divide the API into Catalog and Management. Management refers to Users and Organizations.

# Goal
* APInf API can be found from the apinf.io Catalog as one of the APIs and it is connected to a proxy
* The Swagger file has either uploaded or linked to apinf.io as documentation for APInf API
* The  Swagger file contains a description text which describes the purpose and usage of the API along with the information of how to make authorized calls.

**Comment by Nazarah** [comment]
interested.

**Comment by bajiat** [comment]
@kyyberi Anything missing from the description of the task?

**Comment by kyyberi** [comment]
In the end APInf platform APIs are presented as separate APIs: APInf Catalog API and APInf Management API. In this task result should be one big Swagger containing both. DevOps will be given a separate task to find out automated method to split Swagger to two files, add more profound description in the description attribute in Swaggers from separate markup files maintained in Github. Reasoning: developers have different needs. Some need just catalog and providing just enough information for them as logical package (Catalog API) we lower the barrier and learning curve. Some need to use management. Same logic. In the future we'll have "APInf Flow API" which is realtime data about performance of APIs. 

Anyway, the Swagger file discussed in this issue should be pulled from code comments, not written manually.

**Comment by bajiat** [comment]
@Nazarah has promised to work on the description.

**Comment by bajiat** [comment]
Descriptions  are handled by @matleppa
