### ISSUE TITLE
wireframe for "Add pricing table to front page"

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2640]
#2568
#2642

**Comment by Nazarah** [comment]
1. Front page
Pricing option appears in front page in between Latest APIs section and Contact form section.
Pricing section can be enabled to appear in front page via settings.
The free and paid schemes appear in the pricing section.
Schemes can be customized from pricing module under settings.
For Free scheme, the CTA is Browse APIs (to hook newcomers in APInf to look through the catalog page. when they wish to bookmark or get API key, we prompt them to register/sign in.
For paid scheme, the CTA is to sign up to add API. 
![pricing](https://user-images.githubusercontent.com/17976243/26968396-8e63c5ee-4d0a-11e7-975a-97b90da313a9.png)

**Comment by Nazarah** [comment]
** Pricing Module**
1.Pricing module appears as a separate menu in site configuration.
![pricing4](https://user-images.githubusercontent.com/17976243/26969034-f3630084-4d0c-11e7-9096-1effdd902a92.png)

The reason for this is to keep the pricing module only for APInf instance. 
If anyone else wishes to use this, they can fork the code
![image](https://user-images.githubusercontent.com/17976243/26968554-159673ea-4d0b-11e7-9647-72ac1cefaa54.png)

2. The module can be enabled to appear on front page by checking the check box.
currency can be selected from the related dropmenu and an option to name the module in front page is also given.
![image](https://user-images.githubusercontent.com/17976243/26968699-a00b0220-4d0b-11e7-94be-95c8b8dcda9b.png)

3. Pricing schemes can be added by clicking the **Add New Scheme** button
On clicking a button additional fields to define a scheme appears.
Each scheme has title, type, description, additional condition and a button to add scheme features.
Title and type dropmenu are mandatory.
Information given in these fields appear in the front page (please refer to comment 1 image)
![image](https://user-images.githubusercontent.com/17976243/26968827-1ead1b18-4d0c-11e7-9ded-e06c6d446f50.png)
Scheme can have two types: **Free - Daily** and **Paid -Daily**
For free schemes, no additional field to quote price appears.
An added scheme can be deleted by clicking the delete icon

4. For a paid scheme, additional fields to quote price appears. They are:
* **Number. of Free Calls**
* **Number. of Next Paid Calls.**
* 2 fields to quote **Price** in defined currency per **Number of Calls**.
![image](https://user-images.githubusercontent.com/17976243/26969098-3c3f7cb0-4d0d-11e7-95b1-2659d856f4b6.png)
Site admin can add scheme features for a specific scheme by clicking Add Scheme Feature button.
They can be deleted if needed by clicking associlated delete button.
Also additional condition for a scheme can be added via respective text field.
(please refer to the image in comment 1 to see how the highlighted information appears)
![image](https://user-images.githubusercontent.com/17976243/26969167-75bd55b6-4d0d-11e7-9351-5e07de2b0de1.png)

5. On clicking Save, the price module would be saved and appear in front page.

**Comment by Nazarah** [comment]
![image](https://user-images.githubusercontent.com/17976243/26969535-bf5ad3b4-4d0e-11e7-9937-d444ead97ac2.png)
an advanced option to customize a paid scheme is to add several pricing option.
(e.g. after  free 30000 calls, next 500000 calls have a rate of 20 cents per 1000 calls.
and afterwards, next 1000000 calls have  a rate of 15 cents per 2000 calls.)
added pricing options can be deleted as well.

**Comment by 55** [comment]
Based on the wireframes, here is the HTML/CSS code to implement proposed elements for the home page, this will be pasted into the `Custom HTML block` field at branding page:

```HTML
<div class="container" id="custom-block">
  <div class="text-center">
    <h2 style="margin-top:2em;">Start using APIs for free</h2>
    <p style="font-size:16px; margin-top:1em; margin-bottom:1em;">
      Get access to hundreds of APIs and start using the in no times.
      <br>
      Get community collaboration to build your services
    </p>
    <a class="btn btn-primary btn-lg" href="/apis">
      Browse APIs
    </a>
  </div>
  <h2 class="text-center" style="margin-top:2em;">Manage your own APIs</h2>
  <div style="max-width:600px; margin: 2em auto 0 auto; font-size: 16px; text-align: center;">
    <table class="table" style="margin-bottom:0.5em;">
      <thead>
        <tr>
          <th style="text-align: center; font-weight: 400;">
            API calls per day
          </th>
          <th style="text-align: center; font-weight: 400;">
            Price
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            0 - 30,000
          </td>
          <td style="font-weight: 600;">
            FREE
          </td>
        </tr>
        <tr>
          <td>
            30,000+<sup style="font-size: 0.6em; vertical-align: top; position: relative; top: 0.5em;">*</sup>
          </td>
          <td>
            0.5¢/1000
          </td>
        </tr>
      </tbody>
    </table>
    <p style="font-size:11px;">
      *
      with up to 10Gb/day with 0.05€ per every additional gigabyte of usage.
    </p>
    <p class="text-center" style="font-size:16px; margin-top:1em;">
      No contract and credit card needed.
    </p>
    <a style="margin-top:1em;" class="btn btn-primary btn-lg" href="/sign-up">
      Sign up to add API
    </a>
  </div>
</div>
```
