### ISSUE TITLE
Organization settings: User unable to upload logo/cover image 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2641]
# Steps  
1.Visit https://staging.apinf.io v 0.45.0  
2.Login as admin  
3.Go to  'Organizations'   
4.Click on 'Add organizations'  
5.Enter organization details: Name and URL   
6.Click on 'Save'  
7.Go to above organization 'Settings'    
8.Click on 'Upload logo/cover image '    

# Expected Result  
Successful uploading logo/cover images   

# Actual Result  
Upload logo/cover images not successful but displays successful message  

# Screenshot  
![upload_logo_successful_message](https://user-images.githubusercontent.com/13309358/26969426-5b04a0ca-4d0e-11e7-924e-c323f48cbe65.PNG)          

![upload_cover_image_successful_msg](https://user-images.githubusercontent.com/13309358/26969787-a7d20b62-4d0f-11e7-87f8-b3e42e9f7126.PNG)

**Comment by bajiat** [comment]
@brylie promised to investigate.

**Comment by 55** [comment]
Tested it locally:

### Steps
1. Visit http://localhost:3000
2. Login as admin
3. Go to 'Organizations'
4. Click on 'Add organizations'
5. Enter organization details: Name and URL
6. Click on 'Save'
7. Go to above organization 'Settings'
8. Click on 'Upload logo/cover image '
9. Refresh page
10. Go to above organization 'Settings'
11. Click on 'Upload logo/cover image '

### Result
Successful uploading logo/cover images

### Steps
1. Visit http://localhost:3000
2. Login as admin
3. Go to 'Organizations'
4. Click on 'Add organizations'
5. Enter organization details: Name and URL
6. Click on 'Save'
7. Go to above organization 'Settings'
8. Click on 'Upload logo/cover image '
9. Click on 'Delete organization '
10. Click on 'Add organizations'
11. Enter organization details: Name and URL
12. Click on 'Save'
13. Go to above organization 'Settings'
14. Click on 'Upload logo/cover image '

### Result
Successful uploading logo/cover images

**Comment by 55** [comment]
@saralavanip please confirm once it is on https://staging.apinf.io.

**Comment by saralavanip** [comment]
@55 , @bajiat , verified this resolved issue on staging v 0.46.0 and it is not reproducible.
