### ISSUE TITLE
User research for dashboard wireframes

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2643]
There are currently two wireframes for dashboard: overview with all managed apis (paginated if necessary) and detailed view for single API. 

# Goal
* Interview 2-4 API owners
  * Show the simplified clickable wireframes
  * Observe the user interaction.
  * Make follow-up questions to verify whether they are getting the information they need.

**Comment by Nazarah** [comment]
[Scripts](https://github.com/apinf/docs/blob/master/docs/design/dashboard/Prototype-Testing-Asim.md) from the interview with @ashakunt

**Comment by Nazarah** [comment]
[Scripts](https://github.com/apinf/docs/blob/master/docs/design/dashboard/Prototype-Testing-Jarkko.md) from the interview with @kyyberi

**Comment by Nazarah** [comment]
[Scripts](https://github.com/apinf/docs/blob/master/docs/design/dashboard/Prototype-Testing-Vesa.md) from the interview with @preriasusi

**Comment by Nazarah** [comment]
The user interviews are completed and the scripts are added in GitHub.
I tried to reach Tuukka for an interview in the beginning of the sprint with an email, but he didn't respond.
Since the sprint is about to end and we targeted with 3 interviews, I am closing this issue.
