### ISSUE TITLE
User API, a user is removed, but id remains in Organization manager list

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2645]
Problem:
When a user, who is a manager in one or more Organizations, is removed, the user's id remains in Organization(s) manager list(s).

When Organizations manager list is displayed, it looks like the user id is removed, because the deleted users email address is not visible. However, the user id still remains in list.

What to do?
- when user is deleted, a new check is needed whether the user is a manager in any Organization. In case yes, the user's id must be removed from manager list(s).
- also it needs to be checked, if there are other similar lists, where deleted user's id needs also to be removed.
- it needs to be decided, what to do in case the deleted user is the last manager in Organization (or in another similar list): 
a) add extra confirmation ("Are you really removing the last manager?"), if yes, then remove. 
b) prohibit removal of user and inform ("User cannot be removed, because of being only manager in XXX Organization. Nominate another manager or remove Organization and then try again")
c) just remove id from list, which most likely causes problems afterwards.

Same checking functionality needs to be implemented both in UI operation and in REST API operation.

**Comment by bajiat** [comment]
Scope:
- Select option c) for the REST implementation: remove id from the list
- Create a function for removing the id. The function should be reusable for the UI.

Also, create an issue for an enhancement of user deletion if user is deleted through UI and is an organization manager.
