### ISSUE TITLE
Add inline help to chart widgets

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#266]
Add inline help to inform user about interactive filtering of chart widgets
## Definition of done
- [ ] Add inline help on chart page describing how to interact with charts.

**Comment by elnzv** [comment]
Blocked by #307.
Once dashboard markup ready, will add something like this:

```html
<span class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>
```

**Comment by elnzv** [comment]
Related branch:
https://github.com/apinf/api-umbrella-dashboard/tree/feature/help-block-charts

Now it is working for one block only.

**Comment by bajiat** [comment]
Closing during icebox gardening.
