### ISSUE TITLE
Warning for connected APIs when a proxy is removed

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2661]
# Description
When a proxy is removed from Proxies in APInf, the admin should be warned about the connected APIs. The warning message could potentially contain the number or a list of the connected APIs.

# Proposal
"You are removing a proxy. There are currently 57 APIs that are connected to this proxy. Are you sure you want to continue?"

**Comment by Nazarah** [comment]
a slight modification to the suggested text:
"**Warning*!*You are about to remove a proxy. There are currently 57 APIs connected to this proxy. Are you sure you want to continue?"
> "You are removing a proxy. There are currently 57 APIs that are connected to this proxy. Are you sure you want to continue?"

**Comment by marla-singer** [comment]
@Nazarah @bajiat We already have this feature
Verified on nightly.apinf.io
![joxi_screenshot_1497957274201.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2814d778e3d0f005c2de7/125516c66e82c728ace21e0d46e29b822abd90aa9decba4db755ff801617732a7e5df67c22d2b77aef13394d4d1f0cf31b0d0c00eef39b2ea3b43f22df585fedd7395a76cf3812acb8d41eb857bd25995397f4edd4189fb5646fb2c99d452c1c031288fb5432a99c4cca50ff4de64447e9.png)

**Comment by Nazarah** [comment]
Can we change the confirmation dialog to the newly proposed one? We can also add this line:
"Removing the proxy would break all API calls made to the connected API backends." This sentence should be placed before "Are you sure..." sentence.

**Comment by marla-singer** [comment]
@Nazarah Please write the full text of message.
Now:
**Title**
Are you sue that you want to remove proxy?
**Body**
2 proxy backends are connected to this proxy. Removing the proxy will mean that API calls made to any of the connected API backends will break.

Write your suggest the same

**Comment by Nazarah** [comment]
**Title:**
Removing Proxy

**Body Text:**
**Warning!** You are about to remove a proxy. 
There are currently 57 APIs connected to this proxy.
Removing the proxy would break all API calls made to the connected API backends.
Are you sure you want to continue?

**Buttons:**
Ye, No

**Comment by marla-singer** [comment]
@bajiat Can you please provide updated Finish translate for above text? I'd like to update both Finish and English text

**Comment by bajiat** [comment]
I will translate **any missing or updated texts** during the next translation round from EN to FI and then import the texts to Github from the localisation tool. So it is ok to just update the English.
