### ISSUE TITLE
Rest-API, API creator ID is missing from managerID list

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2665]
# REST-API
when creating new API using rest-API the user  ID does not carry on to the API and ManagerID list is null.

![rest_api](https://user-images.githubusercontent.com/28555452/27128488-602c17b6-5107-11e7-9dba-636b3b030784.png)

# Steps to reproduce
1. login to nightly rest-API service
2. create API by posting to /apis

## Expected result
1. API you just created has created by "username" in catalog.
2. you can change settings in nightly.apinf.io

## Reality
1. API has created by admin text in catalog. 
2. you cant change settings in nightly.

**Comment by bajiat** [comment]
@wuder4  Thanks for the clearly reported issue. What does "you can't change settings in nightly" (step 2) mean?

**Comment by wuder4** [comment]
> What does "you can't change settings in nightly" (step 2) mean?

You are just a regular user who sees details and documents. Nothing else.
