### ISSUE TITLE
[REST API] unify error responses content

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2667]
When requested operation can not be fullfilled, REST API returns an error response.
However, at the moment the contents of error responses vary quite a lot. 

In some cases the returned error code is enough, but in some cases additional information is needed in order to help REST API user.

It needs to be decided, on which level additional error information is provided, so that the error message contents are unified in all methods of REST API.

More information of use of error response. 
https://tools.ietf.org/html/rfc7807

**Comment by mauriciovieira** [comment]
Interested
