### ISSUE TITLE
[tests] Admin user tests in Gate 1

### ISSUE THREAD

**Issue by ashakunt** [apinf/platform#2671]
Copy over the issue from apinf/docs repository (https://github.com/apinf/docs/issues/57). 

In Gate 1 we should test branding, proxy, site settings and organizations but we cant just give admin password into github.

**Comment by ashakunt** [comment]
cc: @wuder4

**Comment by ashakunt** [comment]
This should use the test seeding. @phanimahesh can you help in that?

**Comment by wuder4** [comment]
Gate 1 tests don't have any cases that need admin access. Al thought this same problem is in Gate 2.

**Comment by phanimahesh** [comment]
Apologies for late response, somehow this issue got buried in my notifications and I missed the earlier ping.

I'm not familiar with meteor enough to know recommended seeding methods. But yes, the solution to this is to just seed an admin user and use that account in tests.

**Comment by preriasusi** [comment]
@phanimahesh Could you share Ci credentials for @anarva

**Comment by anarva** [comment]
@phanimahesh, my suggestion is to add the username and password as an environment variable to the test system. Could you help me do that or alternatively grant me the admin rights to the test system?

**Comment by phanimahesh** [comment]
We don't have a currently running jenkins instance, it was shut down during migrations and hasnt been brought back up. I'll have to get it back up and running first.

Are we not running these tests in travis?

**Comment by anarva** [comment]
@phanimahesh Yes, sorry, my mistake. :) Please ignore my previous comment.
