### ISSUE TITLE
[tests] changing tabs in APIs

### ISSUE THREAD

**Issue by ashakunt** [apinf/platform#2672]
Copied over from https://github.com/apinf/docs/issues/58

You cant setup any APIs to have proxy address or delete them if you cant click tabs in the APIs page. Tabs have id's but they are in list so you cant click list with selenium.  
![list_id](https://user-images.githubusercontent.com/28555452/27330894-ebb49842-55c3-11e7-9c3f-fd3045f8a912.png)
If you add id to that link the site will break and it wont change to that tab if you click that new id.

**Comment by ashakunt** [comment]
cc: @wuder4

**Comment by wuder4** [comment]
Solved this problem by  clicking the icon next to the text. 

![apitab](https://user-images.githubusercontent.com/28555452/27830330-9c9a1014-60ce-11e7-948b-fe1b16e3a767.png)

You can use it almost like id. just replace id=asd with css=i.fa.fa-file-text
And it should work

you need to add i. in front of the locator and replace spaces with dots
