### ISSUE TITLE
REST API: Problems with $ref operator when generating Users swagger document

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2675]
### Background
When swagger document about Users routes is generated, because of restrictions in restivus-swagger.js, the related declarations included in program code can not be used, a workaround has to be used.

The workaround is to add a *paths* section into main swagger creation part and explicitly declare Users related paths, methods and fields.

(Swagger document is created in *platform/core/server/apis.js*.
User routes API functionality is in *platform/users/collection/servers/apis.js*, but the explicit creation of swagger document for Users routes is in *platform/core/server/apis.js*.)

In many cases same field definitions are needed in several methods. In order to avoid redundancy, in swagger document there is *$ref* operator to be used in including same field definitions in several methods. 

### Problem
However, there seems to be some problems when $ref operator is used with explicit Users related definitions. 
- existing field declarations (used with other paths) could not be found in same swagger object, when called from Users path --> an external object for Users related field declarations needed to be created.
- declarations in external object with $ref operator are not visible in YAML for swagger (because external object is not included in YAML) --> the declarations needed to be written instead of referenced

### What to do
Use of $ref operator needs to be closely investigated in order to get rid of overlapping definitions and declarations, which then could be replaced with references, *if is is possible*.

**Comment by matleppa** [comment]
@dasha presented a solution to get rid of duplicate definitions for parameters used in Users path. 
When extra duplicate definitions were not needed, the $ref operator became usable, thus solving this problem.

**Comment by marla-singer** [comment]
@matleppa I don't agree with you. I found that you have a lot of unused parameters with type "in: body". I'm not sure that we can close this issue in current PR
![joxi_screenshot_1498730133034](https://user-images.githubusercontent.com/20643403/27682237-89368f6e-5cca-11e7-9198-c66fe31f330f.png)

**Comment by marla-singer** [comment]
Close this issue as resolved by PR #2711
