### ISSUE TITLE
Organization view: Edit or delete previously added media posts not working

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2680]
Prerequisite: Related media posts exist already in Organization view
# Steps  
1.Visit https://staging.apinf.io  v 0.46.0  
2.Login as admin 
3.Go to organization  
4.Edit (eg: Title)  or delete previously added related media   

# Findings  
- Edit or delete previously added posts not working.   
- Edit or delete currently added posts works as expected.

# Screenshots  
![edit_delete_existing_related_media_not_working](https://user-images.githubusercontent.com/13309358/27419122-ed71d41e-5727-11e7-8819-f927c3480113.PNG)    

![delete_existing_related_media_post_not_working](https://user-images.githubusercontent.com/13309358/27419131-f842bf34-5727-11e7-83a2-d762e5bb855e.PNG)

**Comment by bajiat** [comment]
@marla-singer What is the status of this issue? Is it in progress?

**Comment by bajiat** [comment]
@marla-singer What is the status of the issue? Is it in progress or should it be  reassigned?

**Comment by marla-singer** [comment]
@bajiat No, it was blocked because I couldn't reproduce it. Unassigned by myself

**Comment by 55** [comment]
Not reproducible anymore.
