### ISSUE TITLE
Organizations view: 'Sort by' dropdown menu misplaced in Edge browser 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2686]
# Steps  
1.Visit https://staging.apinf.io v 0.46.0  
2.Login as admin 
3.Go to 'Organizations' view  

# Findings  
'Sort by' dropdown menu misplaced in Edge browser     

# Operating system 
Windows 10  

# Browser 
Microsoft Edge v 25.10586.672.0   

# Screenshot  
![sortby_menu_misplaced_edge_browser](https://user-images.githubusercontent.com/13309358/27439468-add68be4-5770-11e7-9edb-663904b123e0.PNG)

**Comment by bajiat** [comment]
I was able to reproduce this in Edge.
