### ISSUE TITLE
Make sure development environment is using node v4

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/platform#2687]
@apinf/developers, according to [meteor guide](https://guide.meteor.com/1.4-migration.html), meteor 1.4 uses node.js version 4.

> The headline feature of Meteor 1.4 is the upgrade to Node version 4.  [...]

As a side note, it's also worth to [notice](https://blog.meteor.com/announcing-meteor-1-4-4-11027f33e3bf) that Meteor 1.6's goal is to use node.js v6:

> Longer term goals along with periodic status updates are outlined in Roadmap.md. Worth noting here is that the effort to upgrade Meteor to Node 6 and beyond has recently made substantial progress. There’s even a very early preview release you can try, though please keep in mind that no version of Meteor 1.6 is ready for production yet.

Currently, there's an [nvmrc](https://github.com/apinf/platform/pull/2654/commits/5342eae8e22cf6f428c6d50e83a64e56b1fcfac8) file as a reminder that [travis is running node.js v4](https://github.com/apinf/platform/blob/9a61f021e51eeeb8c4d669be9b593e188158f387/.travis.yml#L4) in our builds.

So, [as raised](https://github.com/apinf/platform/pull/2654#discussion_r123315550) by @phanimahesh, we should make sure we're using node.js v4 on development machines. 

A good solution is to install [nvm](https://github.com/creationix/nvm) and run `nvm use` before running `yarn` to install node packages and `meteor` to install and run the application.

**Comment by mauriciovieira** [comment]
@brylie, @phanimahesh, @apinf/developers, what do you think?

**Comment by phanimahesh** [comment]
Let us require everyone to use nvm. Having .nvmrc in the repo ensures that the correct version will be used by all contributors if they use nvm.

**Comment by brylie** [comment]
As much as possible, our configuration and tooling should be transparent to the developers. I would be hesitant to require developers to use nvm, or other specific tools like yarn, unless there is clear and present need from the developer standpoint.

Meteor has taken care of a lot of things for us, such as handling node versions configuring building/bundling, based on the principle of **developer simplicity**. This is intended to make it easy for contributors to get started quickly and easily. 

I am not opposed to the devops team being safe about node versions for deployments, but I just don't see a common problem among developers to mandate a tooling change.

**Comment by mauriciovieira** [comment]
@brylie so you think we should just close this ticket?

**Comment by brylie** [comment]
Well, lets leave it open, so we can continue to season the idea. I see the benefit from the devops viewpoint, and just want to make sure changes to the developer workflow (particularly new developers) are warranted.

**Comment by marla-singer** [comment]
@mauriciovieira @brylie I think this issue doesn't make sence because *Meteor has its own version of node when it's run*.
For example, 
![2017-07-03 14 24 28](https://user-images.githubusercontent.com/20643403/27791913-f7db22da-5fff-11e7-8a4b-236a92bdefbb.png)
https://stackoverflow.com/questions/43876438/meteor-node-js-latest-version

**Comment by phanimahesh** [comment]
But unless we install yarn inside meteor's environment, using `meteor npm
install -g yarn`, and use it as `meteor yarn`, we will use external node.
Making sure both match is a good thing. Same goes for any other tools
beside yarn we end up using.
