### ISSUE TITLE
Homepage: Partially translated in Suomi view  

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2688]
# Steps  
1.Visit https://staging.apinf.io  v 0.46.0    
2.Change language to 'Suomi'  

# Findings  
Homepage partially translated in Suomi view  

# Screenshot  
![homepage_suomi_view_partially_translated](https://user-images.githubusercontent.com/13309358/27530752-a5e9d8e2-5a62-11e7-844f-dcb5663cf9cc.PNG)

**Comment by bajiat** [comment]
This is content created by an user and there is no method for having two versions of user created data.

**Comment by bajiat** [comment]
Closing as 'wontfix'
