### ISSUE TITLE
Organization view: Add related media redirects to homepage momentarily  

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2689]
# Steps  
1.Visit https://staging.apinf.io v 0.46.0  
2.Login as admin  
3.Go to 'Organizations'
4.Add organization  
5.Go to above added organization
6.Add related media : 
  - Enter 'Title' 
  - Enter 'URL'     
7.Click on 'Add related content'   
   
# Findings  
Adding related content in organization view redirects to homepage momentarily   

# Operating system 
Windows 10  

# Browser 
Google Chrome  Version 58.0.3029.110 (64-bit)

**Comment by 55** [comment]
@saralavanip what browser were you using?

**Comment by saralavanip** [comment]
@55 , Browser: Chrome Version 58.0.3029.110 (64-bit)
