### ISSUE TITLE
Create functional test suite for dashboard filter

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#269]
Test dashboard filtering functionality to ensure the filter widgets work and the chart elements update. (Includes defining the expectation.)
## Definition of done
- [ ] Create plain text description of expected behavior in project documentation folder.
- [ ] Write the test cases to guide an automated browser through the expected functionality.
- [ ] Add the test cases to /tests/client/integration.
- [ ] Ensure that the test cases are successful.

**Comment by Nazarah** [comment]
Next has a different dashboard than what existed while this issue was created. When we write automated/manual testcases for the dashboard in Next, we'll consider these. closing this.
