### ISSUE TITLE
Enable CLA for this project

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2690]
In order to hold the Copyright to all contributions to this codebase, APInf needs developers to sign a Contributor License Agreement (CLA). 

# Goal
Require contributors to sign a CLA before accepting contributions to this project. The CLA process should be as simple as possible (read: low friction).

# Resources
[CLAHub](https://www.clahub.com/) offers an automated CLA checking service for Github projects.

**Comment by Nazarah** [comment]
closing this. Irrevalent.
