### ISSUE TITLE
Quick start instructions for reporting issues

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2691]
# User Story
Along side APInfs' [guideline for contributing](https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md) to the repository, we should have a default template to help people outside APInf to have a quick start in reporting issues or feature request. Users can always have the time to read through the contribution guideline. However, on specifying a a bug-like behavior, people might want to report it as soon as possible. It wold be always in our hand to decide whether to consider this as bug or existing feature.

# Examples:
Here is an example from [Automattc/mongoose](https://github.com/Automattic/mongoose/issues/new) repository:
![mongoose example](https://user-images.githubusercontent.com/17976243/27578226-2200ac2a-5b2c-11e7-98f5-1e82eec37fdd.gif)
An example from [ckan/ckan](https://github.com/ckan/ckan/issues/new) repository
![ckanexample](https://user-images.githubusercontent.com/17976243/27578250-3cb53bd0-5b2c-11e7-8473-bc0bad5b69fb.gif)
Also a guideline from [GitHub](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

**Comment by bajiat** [comment]
Where do these projects keep the template?

**Comment by Nazarah** [comment]
@bajiat Here is the [instruction](https://help.github.com/articles/creating-an-issue-template-for-your-repository/#adding-an-issue-template) of creating and storing an issue template

In the list of files on the Main page of an repository, a markdown file (e.g. named as issue_template) needs to be created.
In the body of the file, the instructions for adding an issue in the repository can be added.

**Comment by brylie** [comment]
Thanks for suggesting this. What details would be useful for our issue template to contain? What types of issues do we anticipate people opening?

**Comment by Nazarah** [comment]
Possible issues can be one of the followings:
1. **Feature request** - Something a user feels should be included in APInf. This may require giving use cases defending the purpose of the feature request
2.  Bug - Here are two user flows.
      a. User may genuinely find a behavior that is breaking the UI or functionality of APInf.
      b. User may find the flow of action of an APInf feature as a bug. This can also be an usability issue.

In any case, APInf development team would have the final rights to decide whether or not to consider to implement a requested feature, put it in icebox for future implementation or suggesting the issue reporter an alternative approach to achieve is work goal using existing APInf features.

For bugs and usability issue, the same approach can be taken. If a seeming bug is normal action flow of APInf feature, some explanation can be given on why this behavior is adopted. We can also add a label for the such bug as won't fix.

Most importantly reported of an issue should be reached with swift feedback from our side. It

**Comment by Nazarah** [comment]
For requesting a feature @bajiat and I can come with an instruction

For reporting a bug, the user should give the following information

1. Reproduction steps
2. Results
3. Screenshots of UI/log files (preferably in GIF or PNG)
4. Expected Behavior (from user's POV)
5. Environment information - OS, Browser, APInf instance (nightly, staging or production)

**Comment by brylie** [comment]
Another common type of issue might be **support request**, e.g. where the user is having a bit of trouble that might not imply a bug or feature. I have opened a lot of support requests in various projects, and am grateful when I get a helpful response.

What details would our template include for each of the issue types?

- feature
- bug
- support

**Comment by Nazarah** [comment]
@brylie I'll write down instruction drafts for each of the above issue types. I'll proofread the draft for bugs and features with @bajiat and the support request with you. Assigning the task to myself.

**Comment by brylie** [comment]
Cool beans. 

The end goal is basically to have a single issue template, since Github only allows one. 

It would be nice if we could use a template for each issue type, to make it as easy as possible for the person submitting the issue.
