### ISSUE TITLE
Try Out response shows 'Failed to fetch' error

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2698]
# Steps  
1.Visit https://staging.apinf.io  v 0.46.0 
2.Login 
3.Add API 
4.Connect API to proxy  
5.Go to Documentation  
6.Click on 'Manage' 
7.Upload swagger file (eg. Uber API /Petstore API : http://editor.swagger.io/ )   
8.Select Try out methods (eg, GET/POST ) and save 
9.Go to Documentation view   
10.Click on 'Try out'  

# Findings  
- Try out response shows 'Failed to fetch error' for HTTPS request  
- Also checked with 'Petstore' swagger example(http://petstore.swagger.io/v2) , 'Try out' response  displays  'Network error' for HTTP request   

 # Operating system   
- Ubuntu 14.04 LTS    
- Windows 10   

# Browser  
- Chrome V 59.0.3071.115  
- Mozilla Firefox v 52.0.2

# Screenshot  
![get_response](https://user-images.githubusercontent.com/13309358/27636095-8abd07cc-5c12-11e7-973d-4a7f7619ae4a.PNG)

**Comment by matleppa** [comment]
The presence of header X-Api-Key causes CORS preflight request by browser.
That is an OPTIONS request sent to API Umbrella, which rejects it, because it does not contain X-Api-Key header.

Cure: configure API Umbrella to allow OPTIONS request without API key for this API.

**Comment by Nazarah** [comment]
@mauriciovieira could you please co-pilot this with @anarva ?
Also please discuss with @preriasusi about the solution.

**Comment by anarva** [comment]
Please see blocking issue #2696.

**Comment by anarva** [comment]
Can be closed as this is a known bug and the fix is known.
