### ISSUE TITLE
Create functional tests for catalog bookmarking

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#270]
Ensure the bookmark toggle button works as expected on the API catalog by writing a functional test suite. (Includes defining the expectation.)
# Definition of done
## Choose

We have chosen to work with [Mocha.js](http://mochajs.org/) and use the [Velocity](https://velocity.readme.io/) test runner. Velocity is the official tes runner for Meteor.js.
- [x] Research integration (end-to-end) testing frameworks, e.g.
  - [x]  [Casper.js](http://casperjs.org/) / [Slimer.js](http://www.slimerjs.org/)
  - [x] [Nightwatch.js](http://nightwatchjs.org/)
  - [x] [Pioneer.js](http://pioneerjs.com/)
- [x] Choose an integration testing framework based on research, bonus points for the following criteria:
  - [x] JavaScript based
  - [x] Meteor integration
## Document
- [ ] Create plain text description of expected behavior in project documentation folder. Including:
  - [ ] Add bookmark
  - [ ] Remove bookmark
  - [ ] View bookmarks
## Implement
- [ ] Write the test cases to guide an automated browser through the expected functionality. Test cases should include:
  - [ ]  Add bookmark
  - [ ] Remove bookmark
  - [ ] View bookmarks
- [ ] Add the test cases to /tests/client/integration.
## Test
- [ ] Ensure that the test cases are successful, i.e. they pass.

**Comment by bajiat** [comment]
@frenchbread Would you be able to take this task in addition to #327 and #76? If yes, could you estimate the size?

**Comment by mauriciovieira** [comment]
I suggest we take a look at [Velocity](http://info.meteor.com/blog/meteor-testing-framework-velocity), the official meteor package for testing.

**Comment by bajiat** [comment]
Moving this back to backlog, because there is a new testing plan proposed to Apinf. This task either to be re-used for the new plan or closed if new testing issues will be created.

**Comment by brylie** [comment]
@mauriciovieira it makes sense to use Velocity as our testing framework. Also, we chose [Mocha.js](http://mochajs.org/) in a previous task for writing our tests. Mocha.js can be used with Velocity.

**Comment by Nazarah** [comment]
closing this for the time being.
