### ISSUE TITLE
REST API: password in login is not encrypted

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2704]
When user is logging in with REST API, the password is given as text and encryption is done at the server end.
This is a possible security risk.

**Comment by bajiat** [comment]
Comment from @brylie: Check both creating and authenticating to users. Check how this is done with other APIs that require authentication w password.

**Comment by mauriciovieira** [comment]
It would be a security risk for non-https server, but not for normal https. The first API hit using https is encrypted by the protocol, anyways.

cc: @shaliko

**Comment by shaliko** [comment]
We don't have non-https setups. All setups use HTTPS and HTTP traffic will be forced to HTTPS.

Additionally, web server response contains "HTTP Strict Transport Security (HSTS)", which tells to browsers only interact with it using secure HTTPS connections.

**Comment by matleppa** [comment]
OK, it seems, that our current solution is secure enough. 
Here are also couple of agreeing opinions
* https://security.stackexchange.com/questions/7057/i-just-send-username-and-password-over-https-is-this-ok
* https://security.stackexchange.com/questions/55693/securing-passwords-for-rest-authentication

**Comment by brylie** [comment]
We can close this issue.
