### ISSUE TITLE
Manual testing for release 0.47.0

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2708]
Test the 0.47.0 release on the staging server. Report any bugs or enhancement needs to https://github.com/apinf/platform/issues.

See the new and improved features in the [release notes](https://github.com/apinf/platform/releases) 

# Definition of done
* [x] Test any new development based on the release notes, particularly
  * [x] Functionality related to REST API Users route
  * [x] Swagger: REST API user related functionality
* [x] Verify enhancements and the corrections for closed error reports (= bug fixes)
  * [x]  Warning for connected APIs whe Proxy is removed
  * [x]  Swagger UI: 
    * [x] Documentation links
* [x] Go through acceptance testing
* [ ] Update the testing document
  * [ ] Create a PR for docs

**Comment by saralavanip** [comment]
Reported issues: #2724, #2727
