### ISSUE TITLE
API Manager can't set the Try-out methods when Swagger file is uploaded as remote link

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2709]
### Steps for reproduce:
1. Navigate to managed API
2. Open Documentation tab -> Click on Manage button
3. Specify URL to Swagger file
![joxi_screenshot_1499081573534](https://user-images.githubusercontent.com/20643403/27791191-8897a590-5ffc-11e7-91a5-f4bd0eeaf8ab.png)

4. Go to Swagger UI and look at endoints

### Expected
- Swagger UI has Try out buttons

### Founded
- A user can't call any request
![joxi_screenshot_1499081687341](https://user-images.githubusercontent.com/20643403/27791250-cce186da-5ffc-11e7-92f9-c3745fe6c21d.png)
![joxi_screenshot_1499081573534 3](https://user-images.githubusercontent.com/20643403/27791213-a345112a-5ffc-11e7-842f-afe9a3d1394c.png)
![joxi_screenshot_1499081573534 2](https://user-images.githubusercontent.com/20643403/27791215-a460f808-5ffc-11e7-8769-afff05e2c4e4.png)
![joxi_screenshot_1499081727159](https://user-images.githubusercontent.com/20643403/27791314-0ec96fa4-5ffd-11e7-8574-bab878027371.png)

### Suggestions:

1. Let API Manager controls Try-out methods even if file is filled as URL
or
2. Set all methods are allowed by default for file is filled as URL

**Comment by bajiat** [comment]
I would say option 1, keep it consistent with adding as file.
