### ISSUE TITLE
Create functional tests for form filter field

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#271]
Write a functional test suite to ensure the API catalog filters the table when user enters text to filter field. (Includes defining the expectation.)
## Definition of done
- [ ] Create plain text description of expected behavior in project documentation folder.
- [ ] Write the test cases to guide an automated browser through the expected functionality.
- [ ] Add the test cases to /tests/client/integration.
- [ ] Ensure that the test cases are successful.

**Comment by Nazarah** [comment]
Next has a different UI and functionality for API and organization catalog. closing this.
