### ISSUE TITLE
Allow cataloging of API's which have no URL

### ISSUE THREAD

**Issue by xylix** [apinf/platform#2714]
# User Story

> As an API Owner, I want to add an API that I am designing currently and doesn't have an URL, so that I can continue working on it.

**Notes from @xylix** 
> We had a brainstorming session for OpenAPI-designer integration which will be starting in a couple of weeks. We realized that there's no way to add an API to the catalog which has no URL yet, even though when adding an API there is the option to select "Lifecycle Status: Design".
Could we allow the creation of API's which have their Lifecycle status set to "Design" without adding an API URL right away?
It could also be behind its own button, "design an API" or something.

**Comment by marla-singer** [comment]
@xylix You can always change the URL. I think you as a user can add some "placeholder" for that and change it when your API will be ready
