### ISSUE TITLE
REST API: API endpoint, PUT and DELETE, allow methods for admin

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2723]
When API endpoint methods PUT and DELETE are used, they must be allowed for admin user also.
It is not enough to allow them only for users included in API manager list.
*Additional information to correct original poor choice of words*:
Here allowed means, that operations has to be performed also in case admin sends a request via REST API.

**Comment by marla-singer** [comment]
@matleppa As I see, DELETE and PUT methods allow both roles delete or edit API. 

PUT method: https://github.com/apinf/platform/blob/develop/apis/server/api.js#L191-L194
DELETE method: https://github.com/apinf/platform/blob/develop/apis/server/api.js#L269-L272

**Comment by matleppa** [comment]
Yes, admin role is allowed. However, in program code there are checkings that if API exists AND user id is in manager list, the operation will be performed. I think that a third condition is needed: if (user id is in manager list OR user is admin).

**Comment by marla-singer** [comment]
>  However, in program code there are checkings that if API exists AND user id is in manager list, the operation will be performed. 

Please provide code example

**Comment by matleppa** [comment]
While completing the swagger file responses I did following test using REST API.
1) login as user A (not admin)
2) create API test-API
3) login as user B (admin)
4) try to delete test-API

Expected result
4) get response  200 "API successfully removed"

Unexpected result
4) get response 403 {
  "status": "Fail",
  "message": "You do not have permission for removing this API"
}

I got the unexpected result.

(Example is from apis/server/api.js, the method DELETE )

So I think that the in addition to 

      roleRequired: ['manager', 'admin'],

also a change in actual functionality is needed, so that also in case an admin is sending the request, the functionality is performed, following way:


        // Get ID of API
        const apiId = this.urlParams.id;
        // Get User ID
        const userId = this.userId;
        // Get API document
        const api = Apis.findOne(apiId);

	**// Check if user is admin
        const userIsAdmin = Roles.userIsInRole(requestorId, ['admin']);**
		
        // Make sure API exists & (user can manage or user is admin)
        if (api && 
		    (api.managerIds.includes(userId) **|| userIsAdmin**)) {
          // Remove API document
          Meteor.call('removeApi', api._id);

          return {
            statusCode: 200,
            body: {
              status: 'Api successfully removed',
              data: Apis.findOne(apiId),
            },
          };
        }
