### ISSUE TITLE
EMQ proxy view: Input text box for 'Value' misplaced in Firefox browser

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2724]
# Steps  
1.Visit https://staging.apinf.io v 0.47.0   
2.Login   
3.Add API   
4.Go to 'Proxy' view    
  
# Findings     
Input text box for 'Value' is misplaced    

# Operating System   
Ubuntu 16.04 LTS   

# Browser   
Mozilla Firefox 50.0

**Comment by matleppa** [comment]
Just to be on safe side: 
Is it this matter?

![image](https://user-images.githubusercontent.com/23265155/28365849-d347594e-6c92-11e7-9e65-6b9a68ec14ee.png)

**Comment by preriasusi** [comment]
can't find this anymore.
