### ISSUE TITLE
EMQ Proxy view: Repeat adding same user shows 'Internal server error' 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2727]
# Steps 
1.Visit https://staging.apinf.io v 0.47.0 
2.Login  
3.Add API 
4.Go to 'Proxy' view   
5.Select 'emq' proxy from drop down menu 
6.Enter 'Access Control Rules'  
7.Click on 'Save&Publish'  
8.Add user (eg. testuser1)  
9.Repeat the above step adding the same user as above  

# Findings 
Repeat adding the same user displays 'Internal server error [500]' 

# Operating system 
Ubuntu 16.04 LTS   

# Browser 
-  Firefox v 50.0   
-  Chrome v 52.0.2743.116   

# Screenshot       
![emq_add_same_user_error](https://user-images.githubusercontent.com/13309358/27908197-4eac133a-6253-11e7-8fe6-0c82b6b4b1d3.jpg)

**Comment by bajiat** [comment]
@phanimahesh Is this a bug or normal behavior?

**Comment by phanimahesh** [comment]
It should atleast not show internal server error. Normal behaviour should
be showing an error message.

**Comment by deligence-dharmendra** [comment]
Hi @marla-singer @matleppa 
I'm getting exception at the time of adding emo user.
````
{ [Error: getaddrinfo ENOTFOUND hosturl.com hosturl.com:443]
	code: 'ENOTFOUND',
	errno: 'ENOTFOUND',
	syscall: 'getaddrinfo',
	hostname: 'hosturl.com',
	host: 'hosturl.com',
	port: 443 
}
```
Please advise

**Comment by Nazarah** [comment]
Closing this. EMQ will not be available in SaaS/Cloud.
