### ISSUE TITLE
[tests] latency failing tests sometimes

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2729]
When you run all the tests about 1/10 runs some part will fail. This is caused by page not loading all elements at the same time and the test finds the keyword that it searches for in the page to determine if the page is loaded first. Or problem I only had this morning that the proxy settings take more than 10 seconds to update to the server.

![latency](https://user-images.githubusercontent.com/28555452/27948471-928cd044-6302-11e7-9f19-07924a11f129.png)

In this picture you can see it fails to click button that is visible on the screenshot. there is half a second delay between button click and taking the screenshot and the page has loaded during that time.

![latency2](https://user-images.githubusercontent.com/28555452/27950736-1838a120-630b-11e7-9687-86d4da1419d9.png)

This picture shows that top navbar did not load when it was pressed but in the screenshot it is there

**Comment by wuder4** [comment]
easy way to fix this is to run the test 2-3 times on new seed.

hard way to fix it is to add Sleep command on every page load.

**Comment by bajiat** [comment]
Or is it possible to add a "Wait for visible" for elements?

**Comment by wuder4** [comment]
I think that is what I did on most cases. There still is few cases where you need to use sleep command. 
but this issue is no longer an issue
