### ISSUE TITLE
Redirect user to organization page after creating organization

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2732]
When you add API that is done in a separate page and when its done it puts you in API catalog. 
OK this is fine.
But when you add organization there is a layer on top of the regular page and when organization is done you are forwarded to the organization you created.

In my opinion this is very confusing and to be honest creates a lot of unnecessary steps to automated testing. 

I think we should change either one to be like the other one. I think when you add API/org you should be forwarded to the item you just create NOT to the catalog. And when you are adding new item to the site it should be done on a separate page not some layer on top of regular page

# Goal
* After user has added a new organization, the user gets redirected to the new organization page

**Comment by marla-singer** [comment]
> When you add API that is done in a separate page and when its done it puts you in API catalog.

Please clear the browser cache or update develop branch. After adding API it redirects to API profile page

**Comment by wuder4** [comment]
So that works now thanks for the advice but there is still ½ of my concerns left. It would be better to make new page to add organization just like you add APIs.
