### ISSUE TITLE
Document REST API authentication

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/platform#2733]
## Description

Platform has a REST API but no explicit instructions of how to use it. The first step for a REST API user is learn how to authenticate, since the endpoints can be inferred from the code.

## User story 

1. As a Platform developer/user 
2. I need to read instructions about Platform REST API authentication
3. So that I am able to integrate other software to Platform

## Definition of Done

- [ ] Documentation written in the [Contributor Guide](CONTRIBUTING.md)

**Comment by bajiat** [comment]
The documentation about authentication should be in relevant Swagger file(s)
