### ISSUE TITLE
Swagger-ui validates API documentations with external server

### ISSUE THREAD

**Issue by xylix** [apinf/platform#2734]
When user enters their API page at apinf.io (e.g. https://apinf.io/apis/mau-lu)
they can expect a private API to be private. 
However because of swagger-uis (the swagger rich preview functionality) default configuration,
the swagger of an API is always sent to swagger.io for validation
Also if an user has private API, they might want to not host it publicly. Currently
the only way to provide swagger documentation for the apinf platform is via a 
swagger file that is publicly hosted on the web.

Swagger-UIs validation configuration should be discussed.

This feature is documented here https://github.com/swagger-api/swagger-ui#parameters parameter validatorUrl.

## User story
> As an API owner
I expect a private apinf API
to not provide my APIs informations
to other parties.

# Resources
The following libraries may be used to validate OpenAPI documents on the client/server, from within our codebase:

-[swagger-parser](https://github.com/BigstickCarpet/swagger-parser)
- [swagger-validate](https://www.npmjs.com/package/swagger-validate)
- [swagger-validator](https://www.npmjs.com/package/swagger-validator)

**Comment by bajiat** [comment]
@brylie Can you add a link to a JavaScript library that would validate the OpenAPI document on our server?

**Comment by brylie** [comment]
@bajiat I added links to the issue description.
