### ISSUE TITLE
Show Statistics of APIs owned by an user

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2740]
# Description
User sees a list of APIs s/he owns or manages (in an organization) on navigating to Dashboard view. 
Information in the table appears based on the type of APIs (REST or realtime).

# User Story
>" As an API owner I need an overview of the APIs I own so that I can see if they need my attention."

# Definition of Done
- [ ] APIs are grouped as My APIs, My Managed APIs (and/or) Other APIs (for site admin)
- [x] Row information REST API Dashboard:   API Name, Number of Calls, Average Response Time, Number of Unique Users. Each KPI has trend percentage and up/down arrow
- [ ] Row information Realtime API Dashboard: TBR

** Open Question **
1. Future Implementation: API endpoint and status?
2. View when only one API exists.

# Wireframe
**REST API Dashboard**
![dashboard1_admin](https://user-images.githubusercontent.com/17976243/28571416-7103e05a-714b-11e7-8bb8-079406a8d29f.png)

**Dashboard with only 1 API**
![dashboard1_oneapi](https://user-images.githubusercontent.com/17976243/28960125-1a7eaab8-7906-11e7-9aa2-4256dcefa173.png)

**EMQ Dashboard**
![emq](https://user-images.githubusercontent.com/17976243/29412498-bec88ed0-8361-11e7-9f42-5573e912f616.png)

If EMQ dashboard has only 1 API, it would follow the same design as that of REST API dashboard.

**Comment by marla-singer** [comment]
> Each KPI has trend percentage and up/down arrow

We need to remember about neutral value. For example, when a value of unique users is the same as on the previous interval.

**Comment by Nazarah** [comment]
@marla-singer yes you are correct. if the value remains same in the interval period, no need to show any up/down arrow.

**Comment by marla-singer** [comment]
@Nazarah @brylie @bajiat I faced with mathematics dilemma about comparing two periods.
For example:
- 2 users visited a site yesterday and 8 users visited a site today. What color of an arrow indicating and what number of percentage? I suppose a green arrow-up and 300%
- 8 users visited a site yesterday and 2 users visited a site today. What color of an arrow indicating and what number of percentage? I suppose a red arrow-down and 75%
- 0 users visited a site yesterday and 8 users visited a site today. What color of an arrow indicating and what number of percentage? I suppose a green arrow-up and 100%
- 8 users visited a site yesterday and 0 users visited a site today. What color of an arrow indicating and what number of percentage? I suppose a red arrow-down and 100%

**Comment by marla-singer** [comment]
@Nazarah @brylie @bajiat And another dilemma about Average response time.

- 5 ms was Average response time yesterday and 20 ms - today. What color of an arrow indicating and what number of percentage? I suppose a red arrow-down and 300%
- 20 ms was Average response time yesterday and 5 ms - today. What color of an arrow indicating and what number of percentage? I suppose a green arrow-up and 75% (??)
- 0 ms was Average response time yesterday and 20 ms - today. What color of an arrow indicating and what number of percentage? I suppose a red arrow-down and 100%
- 20 ms was Average response time yesterday and 0 ms - today.  What color of an arrow indicating and what number of percentage? I suppose a green arrow-up and 100%

**Comment by brylie** [comment]
> We need to remember about neutral value. For example, when a value of unique users is the same as on the previous interval.

I think we should show an icon to indicate there is no change.

**Comment by brylie** [comment]
Arrows should point the same direction as the trend. If the number gets larger, the arrow points up. If the number gets smaller, the arrow points down.

**Comment by brylie** [comment]
For coloration, lets keep it simple for now and use the same saturation regardless of magnitude.

E.g.
- users
    - increase: green
    - decrease: red
- avg response time
    - decrease: green
    - increase: red

**Comment by marla-singer** [comment]
@brylie The main idea is what percentage? If there was 2 and became 8? If there was 0 and became 8?

**Comment by brylie** [comment]
It is as a percentage of the previous value. So, 8 is 400% increase from 2.

**Comment by marla-singer** [comment]
@brylie Neh, It should be 300%. Because it increases on 300%

**Comment by brylie** [comment]
Lets see. 
- 100% would be 2, 
- 200% would be 4, 
- 300% would be 6, 
- 400% would be 8.

**Comment by brylie** [comment]
The point stands that we are basing it on the previous value.

**Comment by marla-singer** [comment]
If it was 2 and became 2 then would be 100%?

**Comment by brylie** [comment]
See above.

**Comment by marla-singer** [comment]
Umh, And if it was 2 and became 8 then it would be 300%.

`(8 - 2) / 2 * 100 = 300`

**Comment by brylie** [comment]
@marla-singer please quit.

**Comment by bajiat** [comment]
So increase would always be more than 100%?

**Comment by brylie** [comment]
Increase is allways greater than 0%.

**Comment by bajiat** [comment]
I'm totally confused now, but I'm not mathematically inclined... If last week is 2 and this week is 2, should that not be no change ( = 0) and not 100%?

**Comment by marla-singer** [comment]
> I'm totally confused now, but I'm not mathematically inclined... If last week is 2 and this week is 2, should that not be no change ( = 0) and not 100%?

it would be 0 (=no change)

**Comment by preriasusi** [comment]
Also the formula do calculate the decrease correctly, not only increase. :)

**Comment by brylie** [comment]
> If last week is 2 and this week is 2, should that not be no change ( = 0) and not 100%?

There was some initial confusion as to the idea that we are calculating change, rather than proportion to the original. We have reached a consensus that **no change = 0%**.

**Comment by brylie** [comment]
Also remember, increasing values always get an up arrow. Decreasing values always get a down arrow.

Regarding the icon for no change, go with your instincts and the wireframes (I stand aside).

**Comment by brylie** [comment]
Also, we will have to check that both values are not zero, to avoid a division by zero error.

**Comment by Nazarah** [comment]
>I think we should show an icon to indicate there is no change.
I think it is redundant adding icons in a small space.  When increase/decrease is shown with colored up/down arrows (context specific to KPIs), a neutral value automatically becomes unique and can be differentiated from others.

**Comment by bajiat** [comment]
@Nazarah has created a separate issue for grouping the APIs: #2828
