### ISSUE TITLE
Show detailed overview information for each REST API listed in Dashboard

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2742]
# Description
API owner should be able to see KPIs in large fonts, their percentage trend and small trend graphs before s/he decides to know more details about a particular API

# User Story
> "As an   API owner I need to know overview statistics about my API usage so that I can determine their usage trends. The details  should load in less than 5 seconds."

> "As an API owner I need to be able to access the dashboard from different platforms, so that I can view it from mobile, tablet or laptop."

# Definition of Done
- [x] Show API name ( in bigger fonts), Proxy used, number of 2XX calls.
- [x] Show **Number of API Calls**, **Average Response Time** and **Unique Users** in bigger and bold fonts.
- [ ] Show minimalized line charts associated with each KPI. (not required for mobile view)
- [x] Show percentile values for each metrics with arrows.
- [ ] On mouse hover, Show information about the change in percentile value for each metrics as tooltip.
- [x] View should be responsive for laptop and tablet view. Charts for mobile view are not mandatory.
- [ ] Data should load in less than 5 seconds.

# Wireframe

![dashboard2](https://user-images.githubusercontent.com/17976243/28616946-3c1ff2c2-7207-11e7-8331-691f262a58fb.png)

**Comment by Nazarah** [comment]
** Percentage value for each KPI **
1. For each of the metrics shown, percentile value with up/down arrow should appear
2. the percentile value would indicate increase or decrease in the value of metric in comparison to last 7 days
3. API calls: show green up arrow with increased value, red down arrow otherwise
4. Average response time: show red up arrow with increased value, green down arrow otherwise
5. Unique users: show green up arrow with increased value, red down arrow otherwise

**Comment by Nazarah** [comment]
**More information on tooltip**
1. On hovering mouse (mobile view tapping the metric number): tooltip should show how the metric value has increased or decreased in comparison with last 7 days
2. **Open question:** API calls: should also show number of failed calls (sum of HTTP status 4XX and 5XX calls)

**Comment by marla-singer** [comment]
@Nazarah What does mean "24 errors in last 7 days"? Is it related to Monitoring?

**Comment by marla-singer** [comment]
@Nazarah Please provide a wireframe for mobile view

**Comment by Nazarah** [comment]
> @Nazarah What does mean "24 errors in last 7 days"? Is it related to Monitoring?

I was thinking about errors information retrieved from the proxy to which the API is connected to. (e.g. sum of 4XX, 5XX statuses). when we have a highend monitoring functionality where we can set threshold values for (e.g. response time), we can always include them there. (e.g. API becomes slow in response time, or goes down because of the set threshold values for response time in a proxy).

> @Nazarah Please provide a wireframe for mobile view

Will be on it right after analytics view is designed.

**Comment by marla-singer** [comment]
>  Show percentile values for each metrics with arrows.
> 11% higher (lower) than in last 7 days

@Nazarah If no changes should there will be "No changes" or just an empty line?

**Comment by Nazarah** [comment]
> @Nazarah If no changes should there will be "No changes" or just an empty line?

@marla-singer leave it empty. There is no need to show any information or arrow when no change occurs in the KPI values.

**Comment by marla-singer** [comment]
@Nazarah Please provide a wireframe for mobile view :)

**Comment by Nazarah** [comment]
@marla-singer working on it. would be posted later today. :)

**Comment by Nazarah** [comment]
@marla-singer Mobile wireframes posted in this comment.
You don't have to show overview charts in mobile view.
For reference, see [GitHub API](https://status.github.com/) in mobile view (from your cellphone) :)

![mobiledashboar6](https://user-images.githubusercontent.com/17976243/29555113-41b01d88-872a-11e7-846a-d5447ef11d41.png)

![mobiledashboar7](https://user-images.githubusercontent.com/17976243/29555126-4a3dbe92-872a-11e7-84ff-9f245fbc260a.png)
