### ISSUE TITLE
Show API information in Dashboard view for last 7 days

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2745]
# Description
API User should be able to detect that the numerics and charts shown in the dashboard view is for last 7 days.

# User Story
> "As an API owner I want to know for what time period the dashboard data is being shown."

# Definition of Done
- [ ] Text on dashboard view: "Last 7 Days" 
- [ ] Shown data should be updated automatically in every 2 minutes

# Wireframe
![image](https://user-images.githubusercontent.com/17976243/28617525-4fd2de04-7209-11e7-99a8-f5394a282870.png)

**Comment by Nazarah** [comment]
**about updating dashboard**

If user is present in the dashboard view on 28.06.2017 from 10:00, then at 10:02 it should show information from the time range: 21.06.2017 10:02 to 27.06.2017 10:02..and so on.

**Comment by marla-singer** [comment]
> If user is present in the dashboard view on 28.06.2017 from 10:00, then at 10:02 it should show information from the time range: 21.06.2017 10:02 to 27.06.2017 10:02..and so on.

I think it is not good to this page :thinking: Maybe replace this feature to a detailed page?
cc:/ @bajiat @brylie

**Comment by Nazarah** [comment]
@marla-singer The idea is to give you a glance about what has been the trending of API calls, response time and users in last 7 days. When you click on more details, you would be able to see bigger charts along with list of errors and detailed usage information. Also the charts there would be filterable according to response type (2XX, 3XX, 4XX, 5XX) and endpoints. This is more convenient when you have multiple APIs to take care of and you need to see a glance of its status as overview before deciding to do further investigation. The wireframes are on the way.

In case u have only one API, you would be able to see it in the same page.

About refreshing the information, it is upto you all to decide how you want to do it. The Definition of Done can always be changed.

**Comment by marla-singer** [comment]
> About refreshing the information, it is upto you all to decide how you want to do it. The Definition of Done can always be changed.

It is that I wanted to hear
