### ISSUE TITLE
Date picker to render week range

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2746]
# Description

**idea1**: A date picker to select a   range of past 7 days to render the dashboard     
**idea2**: select  any of the past weeks (week1, week2,…) of   the current year to render the dashboard in any cases, dashboard should indicate the date range

# User Story
TBD

# Definition of Done
TBD

# Wireframes

**Comment by marla-singer** [comment]
@Nazarah As an example for inspiration. The dashboard of API-Umbrella uses this date-picker
![joxi_screenshot_1501826097320](https://user-images.githubusercontent.com/20643403/28955965-bf4ffcc2-78f2-11e7-99ea-ded372df3ec7.png)

As a User, I think it is really cool date-picker.

**Comment by Nazarah** [comment]
@marla-singer looks good to me.
We can start out with Last 7 days, last 30 days and yesterday perhaps.
If usability testing with Dashboard users points out that they need more customization, we can always proceed there. :)

**Comment by Nazarah** [comment]
@marla-singer I think you can start with the date pickers that you attached as screenshot. On clicking the last 7 days, that control should appear. I removed the wireframe dialog as I feel it doesn't need anything additional.
@bajiat if you still need a wireframe, I can put one.

**Comment by marla-singer** [comment]
@bajiat @Nazarah WHatset of timeframe do I leave?
"Last 7 days", "Last 30 months", "Customer range"?

**Comment by Nazarah** [comment]
@marla-singer @bajiat I suggest "Yesterday", "Last 7 Days", "Last 30 Days".
Kind of thinking back and forth about keeping custom time range. :-/
