### ISSUE TITLE
Search box to find a specific API

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2752]
# Description
User should be able to look for a particular API in Dashboard rather than browsing the entire list.

# User Story
> "As an API owner, I want to have search option on Dashboard view, so that I can look for a particular API"

# Definition of Done
- [ ] User should be able to type name of an API to make it appear on Dashboard.
- [ ] On typing the search string, matching result should be automatically populated in the dashboard
- [ ] No  of returned item in search result should be displayed
- [ ] "No APIs found" text should appear if search result returns nothing.
**Open question:** In case of a single result, should we show detailed view in the same page? (ref: #2753)

# Wireframes
![image](https://user-images.githubusercontent.com/17976243/28668579-2c34cd1a-72d9-11e7-985e-1ea31bb24256.png)

**Alternet Approach:** Is it possible to make the search option on Topbar contextual? So that when the view is in Dashboard, the search looks out for APIs in the Dashboard page, not the entire website.

**Comment by marla-singer** [comment]
>  User should be able to type name of an API to make it appear on Dashboard.

What about searching for a proxy_backend path or api path?

**Comment by marla-singer** [comment]
> On typing the search string, matching result should be automatically populated in the dashboard
This step would be a little painful :thinking:

**Comment by Nazarah** [comment]
@marla-singer 
> What about searching for a proxy_backend path or api path?

Lets start with simple search by API names. If it is feasible to implement this feature and we have usecase for it, we can always implement this later on.

> This step would will be a little painful

what about lazy loading? My main concern is that user needs to press enter, wait for the page to reload with the found result. If it is too much work, save it for later implementation.
