### ISSUE TITLE
Show Additional Details in Dashboard in case User has only one API

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2753]
# Description
If user has only one API, it is more convenient to show the additional details (e.g. bigger charts, error list, usage list, etc.) in the same view as Dashboard.
This reduces clicks and page loading

# User Story
> "As an API owner, I want to see additional details on dashboard for my only API, so that I don't need to navigate elsewhere."

# Definition of Done
TBD
- [ ] In case the API is slow or down, yellow or red exclamation sign should appear beside the API name to indicate that respectively.
- [ ] on hovering the exclamation mark, tooltip would give additional info about the status of the API

# Wireframe
![dashboard1_oneapi](https://user-images.githubusercontent.com/17976243/28967377-7919cbb2-7923-11e7-8258-5d0a7b7994bb.png)

**Comment by saransh-dev** [comment]
Hello Nazarah,

I am going to work on this issue. Please provide me some following details:-
1. provide me branch name from where I need to work.
2. how I get these APIs lists where yellow or red exclamation sign.

Thanks.
Regards,
Saransh

**Comment by bajiat** [comment]
@Nazarah We agreed that the next tasks for @saransh-dev would be related to meta tags. So you can ignore the previous comment.

**Comment by Nazarah** [comment]
@marla-singer can you please tag @ccsr in a comment and explain to him what complexities you faced while implementing UI for this feature? He would be able to know about the obstacles in this way.
