### ISSUE TITLE
REST API: study if it is possible to use markdown in swagger info

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2755]
Examine, it it is possible to write proper API descriptions within the structure, where from the swagger document is generated. 
* is it possible to have multi-line descriptions
* is is possible to use  markdown, to be added in generated swagger document.

**Comment by matleppa** [comment]
### General level descriptions ###
On most upper level the description texts can be added into 
_xxxx.swagger.meta.description_ 
part by using **backtick** operator.
Example:
```
MaintenanceV1.swagger = {
  meta: {
    swagger: '2.0',
    info: {
      description: `

   ## What is APInf?
```
In this case the markdown can be used, too.
However, there are some matters to be taken into consideration:
* formatting the program code examples with three backticks does not succeed (because the backtick is in use)
  * but there is a workaround: 
separate examples with empty lines and use four indentations.
* long lines (at least Atom with linter marks them), need to be just split with lf

**Comment by matleppa** [comment]
### Description within methods ###

The backtick operator is accepted by Atom (linter) on this level, too, so it can be used as separator, when long description texst are added here, too.
However, the description texts are displayed as program code examples, literally character by character, which means that markdown formatting does not work.
It needs more examination...

**Comment by bajiat** [comment]
@matleppa What is the status of this issue? It is "In progress", but it is not assigned to anyone.

**Comment by matleppa** [comment]
Can be closed. Research ids done and the answer is found.
