### ISSUE TITLE
API Analytics View

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2756]
# Description
Dashboard would include overview information for more that one APIs a user has developed or manages. 
To isolate a problematic API and to know more details about its usage, it is important that relevant information about the particular API appears in a separate view.

# User Story
> "As an   API owner I want to access details page so that I can interact with charts and select specific endpoints so that I can see more details about any   problems so that I know e.g. which endpoint to pay attention to."

# Wirefram
![dashboard3_details_alternate](https://user-images.githubusercontent.com/17976243/28866792-aefa7da6-777c-11e7-9581-f3dbcf20b8ad.png)

**Comment by marla-singer** [comment]
@Nazarah I'd like to notice that this page must contain all data about selected API. 
If API is connected to proxy and proxy_backend path is then all proxy_backend paths with start `/123/` is related to this API.

For example, API Manager connects API to proxy and sets proxy_backend path as `/music/`. It means all below paths are related to this API and Analytics View has to display statistic for these paths as well.

Related paths to `/music/`
```
/music/classis/
/music/pop/
/music/classic/groups/
/music/hip-hop/artists/
...
```

If something is not clear I will explain again

**Comment by Nazarah** [comment]
after a discussion with @marla-singer we propose that in the API Requests Timeline chart and API Response Time chart, we show the tredns based on the proxy)backend paths. The paths can be selected from the dropmenu associated with each chart.
![image](https://user-images.githubusercontent.com/17976243/28862283-2aa0abde-776d-11e7-931e-71da118873d5.png)

**Comment by Nazarah** [comment]
**Mobile View**

![mobiledashboard](https://user-images.githubusercontent.com/17976243/28963023-45ce53ee-7910-11e7-88b3-cfb134504fdc.png)

![mobiledashboard2](https://user-images.githubusercontent.com/17976243/28963031-4d550482-7910-11e7-9941-b7e17e367f0b.png)

![mobiledashboard3](https://user-images.githubusercontent.com/17976243/28963043-5d162f86-7910-11e7-94ec-5b60916bde94.png)

![mobiledashboard5](https://user-images.githubusercontent.com/17976243/28963062-6a672834-7910-11e7-9381-fa337d000689.png)

**Comment by marla-singer** [comment]
@bajiat @kyyberi @Nazarah I thought a lot of about this page while am implementing that. I don't really like that three little overview charts take a lot of place on the page and have duplicated information.
Block near Average response time chart contains the equaled data with API Response Time chart below. 

![joxi_screenshot_1502192688501 1](https://user-images.githubusercontent.com/20643403/29070913-de717338-7c49-11e7-9417-beba157e2379.png)

I suggest keeping three little charts in one line because it is just **overview data** and it is not main data for the user on the current page. Wireframe for a mobile view doesn't change.

![joxi_screenshot_1502192688501](https://user-images.githubusercontent.com/20643403/29071011-68727514-7c4a-11e7-8a8e-3d9f324242da.png)

**Comment by Nazarah** [comment]
@marla-singer 
> Block near Average response time chart contains the equaled data with API Response Time chart below.

The bigger chart functions in such a way that you can select a particular endpoint (if your API has more than one) to see the trendline of average response time in the last 7 days. 
The block at the top of the page shows a small trend graph based on the endpoint selected in the bigger chart. 
And it also gives the quick view information about all endpoints. 
But if all agree that it might look confusing, we can remove it.

> The next my question is related to block "4/4 Responsive Endpoints". I already asked Nazia about this block and my feeling, as an ordinary developer, is this block describes nothing. It looks raw and unuseful. As the first step, I suggest removing this block and redesigning it later.

This was a user requirement from @kyyberi . He wishes to know how the endpoints are performing. Later, if we have the feature to set threshold values in proxies to determine slow APIs, APi reaching a certain amount of requests, showing the status of the API endpoint would make sense.

I leave it to @bajiat and @kyyberi to decide upon the changes.

**Comment by marla-singer** [comment]
> The bigger chart functions in such a way that you can select a particular endpoint (if your API has more than one) to see the trendline of average response time in the last 7 days.
The block at the top of the page shows a small trend graph based on the endpoint selected in the bigger chart.

@Nazarah no, I meant only block with **"Endpoint1 100 ms, Endpoint2 200ms, Endpoint3 300ms, Endpoint4 112ms".** 
If you select Endpoint1 in the big chart API Response time then you will see 100ms under title "Average response time"
If you select Endpoint2 in the big chart API Response time then 200ms and so on.
![joxi_screenshot_1502192688501 3](https://user-images.githubusercontent.com/20643403/29111605-9d910536-7cf3-11e7-890e-8f4e08ec6227.png)

**Comment by Nazarah** [comment]
@marla-singer lets go with the above approach. In any case we will be doing user testing of the implemented one.

**Comment by bajiat** [comment]
I would say the responsive endpoints could be implemented later. I'm not sure I would as a user / API owner understand the visualisation there.

**Comment by marla-singer** [comment]
@Nazarah @bajiat @kyyberi The markup work is in a process and I have an impasse.
When I asked Nazia about **Why do we need overview (small) charts again on the Analytics View page?**, she answered me "_When you have multiple APIs, you 1st get to see some overview graphs (the small one) <..> When u click on show more details.. from dashboard, the appearance of all info would improve recognization, that u know familiar things from the previous page_"

But current realization doesn't have the familiar things on the focus. I preferred to keep all small charts in one line and now I don't know what the best place for selected area. If it contains the word "calls" then there is not enough place for digits. (2XX Calls case) and if it doesn't contain the word "calls" then it looks strange. What to do? :thinking: 

![joxi_screenshot_1502355683851 1](https://user-images.githubusercontent.com/20643403/29164437-0d074a04-7dc8-11e7-9a40-cac18c8a3ce6.png)

**Comment by marla-singer** [comment]
Also as you can see on my screen, it can be case when API endpoint calls don't have any error/users then I don't display an empty table (current screen - don't display table with Most frequent users)

**Comment by Nazarah** [comment]
>and now I don't know what the best place for selected area. If it contains the word "calls" then there is not enough place for digits. (2XX Calls case) and if it doesn't contain the word "calls" then it looks strange. 

@marla-singer please increase the height of the white background of the overview charts.
In the one for APi requests, add the responses as:
2XX: 50000 3XX: 500 4XX: 3000 5XX: 500

>Also as you can see on my screen, it can be case when API endpoint calls don't have any error/users then I don't display an empty table (current screen - don't display table with Most frequent users)

agree with that

**Some Improvements**
1. Please make the numberic values on bigger fonts.
And then display the KPI Name in smaller font below the numeric value.
e.g.
54000
API Requests

2. Keep more space between the Bookmark, Star rating and Proxy information

3. Can you remove the background scaling used in all the charts? It would make the GUI look cleaner.

**Comment by Nazarah** [comment]
**Some Improvements**
1. Please make the numberic values on bigger fonts.
And then display the KPI Name in smaller font below the numeric value.
e.g.
54000
API Requests

2. Keep more space between the Bookmark, Star rating and Proxy information

3. In the bigger API Request chart, there is no need to put a filter for API request trendline.
The idea is that this line will always be visible.
user can choose to see responses specific to certain HTTP status codes.

4. Can you remove the background scaling used in all the charts? It would make the GUI look cleaner.

5. Is there any other table styling in the CSS? for some reason they are not looking appealing to me. :-/
[Here](https://bootswatch.com/simplex/#tables) see the table styling of the white and grey rows. they lookk good to me.
besides there are other themes u can check out. :)

6. If there is no users, u can always leave the overview chart empty.
Also number of users cannot be negative.
So u can make both X-Axis and Y-axis of the chart positive.
So please keep this chart like the other two.

**Comment by marla-singer** [comment]
>In the bigger API Request chart, there is no need to put a filter for API request trendline.
The idea is that this line will always be visible.
user can choose to see responses specific to certain HTTP status codes

Don't understand this point. It is the legend for the chart and you can filter requests by status code. What kind of trend line are you talking about? 

> Can you remove the background scaling used in all the charts? It would make the GUI look cleaner.

Can't agree with this point. I prefer to keep background because it would make the UX clearer.

> Is there any other table styling in the CSS? for some reason they are not looking appealing to me. :-/
Here see the table styling of the white and grey rows.

Do you wanna make total grey, total white or striped table?
 
> If there is no users, u can always leave the overview chart empty.

My feeling is it will be over-engineering and don't easy for markup job because the white block doesn't have a static height, the height is auto-computed by CSS and depends on screen size (mobile or desktop) and the contained components (title, chart area, trend statistic). If there is not display the chart then this block will not have less height than neighbor blocks.

**Comment by Nazarah** [comment]
@marla-singer 
1.
>?![joxi_screenshot_1502438459527](https://user-images.githubusercontent.com/20643403/29205319-be101e18-7e84-11e7-9cc9-778e2960e7eb.png)

Correct!

2.
>Don't understand this point. It is the legend for the chart and you can filter requests by status code. What kind of trend line are you talking about?

![image](https://user-images.githubusercontent.com/17976243/29207037-3e341d44-7e8d-11e7-8327-396557189d22.png)
Do we actually need to filter the chart based on all calls?
My idea was to show the greyline all the time.
Then user can filter to see one or more lines showing 2XX, 3XX, 4XX or 5XX.

3.
![image](https://user-images.githubusercontent.com/17976243/29207135-b4a82fe2-7e8d-11e7-8df3-1fae3aec92c6.png)
The sample is from [this example](http://wrapbootstrap.com/preview/WB09JXK43)
(click on Dashboard V2 on left menu)
They have used scaling, but it is barely visible.
If u want to keep the scaling, make them lighter.

4.
>Do you wanna make total gray, total white or striped table? Right now the table is white and a row becomes gray on a mouse hover.

Now that I have got the idea, lets keep it as it is

5. 
>My feeling is it will be over-engineering and don't easy for markup job because the white block doesn't have a static height, the height is auto-computed by CSS and depends on screen size (mobile or desktop) and the contained components (title, chart area, trend statistic). If there is not display the chart then this block will have less height than neighbor blocks.

![image](https://user-images.githubusercontent.com/17976243/29207306-5c31ce30-7e8e-11e7-9e6b-111ce9fd8e38.png)

Sorry I could not explain correctly.
See both charts in the above image.
the left side one has the main axis starting from the bottom left corner.
I want the overview chart for the user to appear as same as that,

> If there is no users, u can always leave the overview chart empty.

I meant that there is no need to show any trendlines if the user number is 0.
Simply show the chart with axis and units.

Could I clarify myself? :)

**Comment by marla-singer** [comment]
> Do we actually need to filter the chart based on all calls?
My idea was to show the greyline all the time.
Then user can filter to see one or more lines showing 2XX, 3XX, 4XX or 5XX.

I didn't find any option to disable a legend for specified line in the docs. There displays a legend for all lines or no legend at all.

> If u want to keep the scaling, make them lighter.

I found the option to change color.  Default color is `#e6e6e6`, please provide a preferred color.

**Comment by Nazarah** [comment]
>I didn't find any option to disable a legend for specified line in the docs. There displays a legend for all lines or no legend at all.

Let's then continue with your implementation.
From seeing the actual GUI and user testing result, we can always modify things later if needed.

>I found the option to change color. Default color is #e6e6e6, please provide a preferred color.

Let's go with it.
