### ISSUE TITLE
Sorting option on Dashboard view

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2758]
# Description
It should be possible to sort the APIs based on the KPIs used in respective dashboards

# User Story
> "As an API owner, I want  to sort the APIs on dashboard, so that I can see their appearance based on some criteria."

# Definition of Done
TBD
*Ideas for REST APIs*: Highest API requests, Highest Response Time, API with most users
*Ideas for Realtime APIs:* Highest API Messages, Highest Message Publish Rate, API with Most Subscribed Clients.
- [ ] Sorted list will appear as descending order

# Wireframe
- for REST API dashboard
![filtering sorting](https://user-images.githubusercontent.com/17976243/28967101-49ff2c6a-7922-11e7-8ee0-4bbc985d263e.png)

- for realtime API dashboard: **Highest API Messages**, **Highest Message Publish Rate**, **API with Most Subscribed Clients**

**Comment by Nazarah** [comment]
@phanimahesh looking for your feedback about EMQ Dashboard

**Comment by Nazarah** [comment]
@marla-singer I have added the wireframe for sorting. I am waiting for @phanimahesh 's feedback about EMQ.

**Comment by phanimahesh** [comment]
I couldn't see the wireframe for EMQ dashboard, but the columns look good to me. All three of them provide meaningful and useful information when sorted in either order.

**Comment by Nazarah** [comment]
@phanimahesh I haven't yet added any wireframes but i just needed your opinion about the sorting criteria used for EMQ. If the mentioned ones are ok with you, we can go with them.

**Comment by phanimahesh** [comment]
Yep. They look good to me.

**Comment by marla-singer** [comment]
@Nazarah What about option "API name"?

**Comment by Nazarah** [comment]
@marla-singer let me ask from stakeholders how they feel about sorting with alphabets

**Comment by preriasusi** [comment]
@Nazarah Did you manage to catch stakeholder's
 feelings?

**Comment by Nazarah** [comment]
@preriasusi we can go with options for sorting with API names. 
Here two options should be available in the sorting dropmenu:
Name (A - Z)
Name (Z - A)

**Comment by marla-singer** [comment]
Reopened this issue as not still realisation
