### ISSUE TITLE
Show KPIs for REST APIs in API details view

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2760]
# Description
KPIs (API Requests, Average Response Time and No of users) for a particular API should appear in the details view helping API owners to investigate usage or potential problems

# User Story
> "As an API owner, I want to see API statistics overview in Detailed page, so that I don't need to recall them from Dashboard"

# Definition of Done
- [x] Show API requests numbers, Average Response Time and No of users information for a particular API in large fonts
- [x] Show percentile information about increase/decrease in KPI value and up/down arrow for each KPI
- [x] for Requests KPI, no. of 2XX, 3XX, 4XX and 5XX requests should appear (if any) in specific colors.
- [x] for Response Time KPI, response time of individual endpoints (if exists more than one) should appear.
- [ ] (FUTURE) show yellow/red exclamation sign is a particular KPI value exceeds defined threshold1/threhold2 value

# Wireframe
![image](https://user-images.githubusercontent.com/17976243/28869600-f13e579c-7785-11e7-8d15-2c01cf4b9d73.png)

![image](https://user-images.githubusercontent.com/17976243/28869632-06764304-7786-11e7-8ee5-cb1567b914bf.png)

![image](https://user-images.githubusercontent.com/17976243/28869640-0ff6a630-7786-11e7-9440-9f0c74259ddc.png)

![image](https://user-images.githubusercontent.com/17976243/28869660-1c26c444-7786-11e7-98b8-9b0138627746.png)

**Comment by marla-singer** [comment]
@Nazarah I suggest keeping number and title in one line
`54 000 API Requests`
`178ms Average response time`
`80 New API users`

What do you think?

**Comment by Nazarah** [comment]
@marla-singer I think there was a comment where u suggested to keep the number and title in the same line. I am not seeing the comment.
I don't feel strongly about that idea.
The 1st glance people would look at figures and then what the figure represents.
So keeping them not in the same line actually complements each other in terms of aesthetics and understanding.

**Comment by marla-singer** [comment]
> Show percentile information about increase/decrease in KPI value and up/down arrow for each KPI

@bajiat @kyyberi @brylie
I want to get some information about what data does need comparing? My idea was **Last 7 days** - Compare current week with previous week. But after discussion with @Nazarah I understood that my idea is incorrect :confused: Right is to compare today (09.08) and 7 days ago (02.08).
Is it so?

**Comment by brylie** [comment]
The median value would be calculated based on values from the previous week. The comparison value would compare this week's median with the previous week's median. That is my intuition.

**Comment by marla-singer** [comment]
> The median value would be calculated based on values from the previous week. The comparison value would compare this week's median with the previous week's median. 

I thought so and I've done

**Comment by brylie** [comment]
![screenshot_20170809_153702](https://user-images.githubusercontent.com/17307/29121768-9a8d11a2-7d18-11e7-8d06-ff92257bcda8.png)

**Comment by brylie** [comment]
Basically, since the metric (KPI) is 'median response time for past seven days' it is natural to compare another median response time from a different seven day interval.

**Comment by marla-singer** [comment]
Median for response time? 
Becuase I've taken data for comparing:
- a total number of requests for 7 days
- a total median response time for 7 days
- a total number of unique users for 7 days

**Comment by bajiat** [comment]
If the user selects a timeframe, then the **comparison** should be made between the user's selection (e.g. last seven days) and previous similar time frame. So I agree with @brylie and your original interpretation.

**Comment by brylie** [comment]
The metrics, to my understanding are

- past seven days (or other timeframe)
    - total number of requests
    - total number of unique users
    - median response time
