### ISSUE TITLE
Show a list of errors that occurred for an API

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2761]
# Description
User needs to see what errors occurred for his/her API for a specific time period. Proxy used for the API should be able to retrieve this information.

# User Story
> "As an API owner, I want to see a list of errors, so that I can figure out about a particular problem that happened for my API"

# Definition of Done
- [ ] list should include problem name, date and time of occurrence, affected endpoints.
- **Ideas:** Type of problems --> 
                       - 4XX/5XX responses of API calls made
                       - API response time exceeding set threshold
                       - API goes down
                       - one/all endpoints becoming slow/down, etc.
- [ ] downloadable log file

# Wireframe 
![image](https://user-images.githubusercontent.com/17976243/28867277-231a0854-777e-11e7-908a-0f1e07a5ef35.png)

Problem details
![image](https://user-images.githubusercontent.com/17976243/28867235-07656b12-777e-11e7-9013-0873f44bdf9e.png)

**Comment by marla-singer** [comment]
@Nazarah My opinion is to place "Download problem log" instead of "Show more" and not allow to display full statistic on a new page/modal window

**Comment by Nazarah** [comment]
@marla-singer I like your suggestion.
I am just wondering if user sees it on a mobile phone, would s/he be eager to download it?
or Just want to see it from the display?
@kyyberi would you be happy if we are showing 6 latest entries and then adding the option to download the error log?

**Comment by marla-singer** [comment]
> I am just wondering if user sees it on a mobile phone, would s/he be eager to download it?

I believe yes, but it needs research

**Comment by Nazarah** [comment]
let me initiate a poll n tweeter with APIOps community. I believe we can get some good feedback there.
