### ISSUE TITLE
Show information about Most Frequent API users and their usage in Details view

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2762]
# Description
User should be able to know who is using his/her APIs,  amount of the usage and what services are actually making the API calls

# User Story
> "As an API owner I want details about people and services using my API most frequently" so that I can monitor their usage or offer them help and support if needed.

# Definition of Done
- [ ] Show a table of API usage with the following information: Username (APInf?), No of calls made, URL making API calls, etc.
- [ ] The user with most calls should appear on top
- [ ] information should be shown for the last 7 days

**Open Question**: would it be possible to download usage information as excel file?

# Wireframe
![image](https://user-images.githubusercontent.com/17976243/28867111-adb64b54-777d-11e7-976d-62e2205f9e80.png)

User info
![image](https://user-images.githubusercontent.com/17976243/28867087-9d3b2484-777d-11e7-850f-e382101b2afe.png)

**Comment by marla-singer** [comment]
> Open Question: would it be possible to download usage information as excel file?

In my opinion, it needs to research and I'd like to provide a downloading file with statistic instead of display it on a new page/modal window.

**Comment by Nazarah** [comment]
@marla-singer 
Lets go with the same approach that gets decided in this issue
https://github.com/apinf/platform/issues/2761#issuecomment-320898081
![image](https://user-images.githubusercontent.com/17976243/29110533-9cddc556-7cef-11e7-8850-56851275130c.png)
