### ISSUE TITLE
[FIWARE] Enable Sign on with  FIWARE IDM

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/platform#2767]
# Description

On FIWARE we want to be able to login on APInf  using my FIWARE account.

# User Story

As a FIWARE user, I want to use my existing FIWARE account when logging into an  APInf instance

This EPIC is about  federated sign on, i.e.  "I need not to register again".   APInf would be similar to services that use Facebook, Google or Github authentication for sign in. User still needs e.g. to press a button to sign in with existing account from Facebook, Google or Github. User does not need to create a new, separate account for the new service.

There is a related EPIC for seamless single sign on, i.e.  "I need not to login again" 
See issue  #2823

# Goals

* User can use an existing FIWARE account to sign to and APInf instance.
* "Sign in with FIWARE" button appears on Sign in page 
* "Sign up with FIWARE" button appears on Sign up page 
* User should have as few steps as possible to sign up or to sign in
* When user clicks the "Sign up with FIWARE" button, a new Meteor user is created based on the data received from FIWARE Keystone

# References

oAuth in Meteor:
http://robfallows.github.io/2015/12/17/writing-an-oauth-2-handler.html
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-custom-oauth/custom_oauth_client.js

# Mock ups
<img width="384" alt="register with fiware" src="https://user-images.githubusercontent.com/11626388/29209700-8f261472-7e98-11e7-8db3-a328d8215a03.png">
<img width="372" alt="sign in with fiware" src="https://user-images.githubusercontent.com/11626388/29209710-9929bdac-7e98-11e7-86cb-826eba9f632d.png">

**Comment by ccsr** [comment]
Information of FIWARE Idm can be found at http://fiware-idm.readthedocs.io/en/latest/introduction.html

**Comment by mauriciovieira** [comment]
More information:

- [oauth2 authentication on fiware instance](http://fiware-idm.readthedocs.io/en/latest/oauth2.html)
- [create application on fiware lab](https://account.lab.fiware.org/idm/myApplications/create/#)

**Comment by bajiat** [comment]
@fdelavega, @mauriciovieira, @ccsr 

Can you check the open issue about whether we should implement federated sign on or seamless, single sign on?

**Comment by brylie** [comment]
The initial idea proposed was to use OAuth for federated sign-in with FIWARE ( #2611 ). This would be in alignment with GitHub authentication, and is becoming more common on the web in general.

This is why we are asking for clarification about the goals of this issue.

**Comment by mauriciovieira** [comment]
@bajiat 
> about whether we should implement federated sign on or seamless, single sign on?

I think we should implement both (if they are not the same).

The description of this task explains the federated login (duplicated #2611). We should have a way of telling Meteor which FIWARE server we want to connect to.

cc: @midyan @Vellames

**Comment by mauriciovieira** [comment]
I will pair program with @midyan and @Vellames on this task

**Comment by mauriciovieira** [comment]
Tasks:

- [ ] reverse engineer accounts-github, and create a package in `packages/` called _accounts-idm_
- [ ] parameterize IDM server on settings page (some work done at #2778)

**Comment by brylie** [comment]
Consider making a package that could be used in the wider Meteor/JavaScript ecosystem. If it is tied to Meteor Accounts, then it could be something like 'meteor-accounts-fiware', since 'accounts-idm' is somewhat vague.

**Comment by bajiat** [comment]
@mauriciovieira We have created a separate issue for SSO EPIC #2823
