### ISSUE TITLE
[FIWARE] REST-API: Add endpoint for Organizations part to manipulate managers

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2768]
Create the endpoint into Organizations part which allows to add/delete manager of current organization

**Comment by matleppa** [comment]
I think here we need to rewrite the code in PUT method in order to make it work same way as in APIs API, where values of single parameters can be manipulated one by one.
In current implementation it is expected, that some value is given to each parameter, which value can be altered.
If value is not given, the parameter value in DB is set to empty.

**Comment by marla-singer** [comment]
After discussion in PR #2797 with @matleppa we decided:
- close the current PR and open a new one
- create a new endpoint to work with Organization managers

**Endpoint** -- `/organization/{id}/managers`

**GET** `/organizations/{id}/managers` -- return list with managers. Provide information as e-mail, username, id of users.
**Query parameters**: username, e-mail. If parameters are filled then return list of users with specified e-mail OR username

**GET** `/organizations/{id}/managers/{id}` -- return a specified manager
**Path parameter:** ID of user to return

**POST** `/organizations/{id}/managers` -- add one or few managers into Organization.
**Body parameters:** e-mails field'

**DELETE** ``/organizations/{id}/managers/{id}` -- delete a specified manager
Path parameter: ID of user to remove

PUT method isn't needed.

**Permissions**:
- Administrator or Organization mamanager can manipulate.
- Organization manager or Administrator can't delete himself.

**Comment by matleppa** [comment]
@marla-singer 

Where is this request of ```or few managers``` based on?

```
POST /organizations/{id}/managers -- add one or few managers into Organization.
Body parameters: e-mails field
```

Adding only one manager at a time would make implementation more simple and clear. It also simplifies the handling of errors.

Do you think that we can drop the requirement of adding several managers at a time?

**Comment by marla-singer** [comment]
@matleppa Ok, let's start on easy implementation. 
if it would be critical in future we would improve it
