### ISSUE TITLE
[FIWARE] Add PEP username and PEP password

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/platform#2770]
**Title**:

[FIWARE] Add PEP username and PEP password

**Description**:

When [SSO](https://github.com/apinf/platform/issues/2767) is enabled, that means this APInf Platform instance is tied to FIWARE. So API configuration should also include PEP username and PEP password.

The logic of PEP is included in API Umbrella. So the logic of PEP proxy will be implemented by API Umbrella (TODO: find API-umbrella issue)

**Comment by bajiat** [comment]
Related to #2823
