### ISSUE TITLE
Password length limited when changing password

### ISSUE THREAD

**Issue by tulir** [apinf/platform#2771]
**Steps to Reproduce**: 
1. go to page: https://nightly.apinf.io/settings/account
2. try to enter password over 20 characters
                    
**Outcome**:
"New Password" and "Confirm new Password" do not allow passwords above 20 characters.
         
**Expected Behavior**:
Password fields should not limit the length of the password. Changing passwords should also be consistent with registration, so if there are any limits, they should be the same in registration and password change.

**Environment**:
Ubuntu GNOME 17.04, Firefox Developer Edition 55.0b10, APInf Nightly (https://nightly.apinf.io)

**Comment by matleppa** [comment]
Registration accepts password up to length of 75 characters.
However, for some reason, the lengths are limited followingly with updatePasswordSchema:

 * old psw:  50 chars
* new psw:  20 chars
* confirm new psw: 20 chars

**Comment by tulir** [comment]
Yeah, I traced the source of that form yesterday and found [this](https://github.com/yogiben/meteor-starter/blob/f6c2548a7a88ea88c022721604cac86f13489c58/both/NCSchemas.coffee#L12)

**Comment by bajiat** [comment]
Moved the issue from "In Progress" to Planning, since it is not assigned to anyone.
