### ISSUE TITLE
[FIWARE] REST API: manipulation with Private/Public status for API

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2772]
Now we can set the label "Private" only via UI. 

## Goals
- A user can set the label "private" or "public" when he/she is creating API via POST request
- A user can edit the label Private when he/she is editing an own API via PUT request

**Comment by matleppa** [comment]
Do we need here PATCH method to be able to update only one parameter at a time?
PUT updates whole item, so in that case all fields need to be present in request.

**Comment by matleppa** [comment]
#### methods PUT and POST ####
After examining and testing of REST API for API handling, the current implication already supports setting values for several fields in API entity with methods PUT and POST.
Also value of Private/Public label can be set.
Needs a swagger document update.

**Comment by matleppa** [comment]
However, with this flexibility via REST API it is possible to alter values af all fields, which name is known (e.g. bookmarkCount).

**Comment by marla-singer** [comment]
> Do we need here PATCH method to be able to update only one parameter at a time?
PUT updates whole item, so in that case all fields need to be present in request.

@matleppa Swagger doesn't support PATH method. As I remember I tested PUT method and I sent just couple fields and it worked as PATCH. Please check it
