### ISSUE TITLE
[FIWARE] REST-API: User must get the list of owned APIs

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2773]
Now a user can get the list of all APIs or with the specific APIs

### Goal
- Create endpoint to return all managed APIs for this user. It should use header "X-User-id"

**Comment by matleppa** [comment]
Should we add a new parameter into GET /apis method?

E.g.

myApis=true

If it is not given or has value 'false', it has no effect.

**Comment by marla-singer** [comment]
@matleppa Yeah, that's good. Let's create a new parameter "managed APIs" with boolean values (true or false).

Before make sure that we can leave  GET method for `/apis` without required authorization. 
Can we get value from headers? Because we can use `this.userId` into `action()` part only when authorization is required.

**Comment by matleppa** [comment]
I think we can get it this way:
  const requestorIdX = this.request.headers['x-user-id'];

As an another matter, I think existing parameter ```organization``` and this new parameter ```managesAPIs``` will be excluding, i.e. only one of them can be given at a time.

**Comment by marla-singer** [comment]
> I think existing parameter organization and this new parameter managesAPIs will be excluding, i.e. only one of them can be given at a time.

Can you describe this point? Why is one of them can be given?

**Comment by matleppa** [comment]
I was wondering, that which which of conditions were stronger.  
However, after re-thinking tha matter, the solution would be that in case both conditions were given, the response contains only those APIs, which belong to given organization AND are managed by given user.
