### ISSUE TITLE
[FIWARE] REST-API Endpoint for Branding.

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/platform#2774]
**Title**:

[FIWARE] REST-API Endpoint for Branding.

**Description**:

In the context of CKAN administration, it would be a better admin user experience if CKAN branding configuration could be smoothly propagated to the associated APInf Platform instance.

**User Story**:

As a Platform admin, I need an endpoint to manage Branding programatically so that I can configure Platform Branding from other applications.

**Comment by Nazarah** [comment]
@marla-singer is it ready for review or do you wish to reestimate the issue?

**Comment by marla-singer** [comment]
@Nazarah Came back from vacation and gonna finish it today
