### ISSUE TITLE
Recruiting message in code

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2782]
Add recruiting message in code

**Description**:

Add simple recruit message as comment in platform page. Samples below

![2017-07-23 17 55 40](https://user-images.githubusercontent.com/1927158/28500512-346f35ec-6fd2-11e7-8b61-3d1988e4262a.jpg)

![img_20170723_175212_913](https://user-images.githubusercontent.com/1927158/28500513-3bf6de50-6fd2-11e7-87d3-ec41c4e66da5.jpg)

## Tasks 

- [ ] Add apinf.com/positions page (design and add content)
- [ ] Add  in platform code in main view

**Comment by kyyberi** [comment]
There might also be another comment which encourages to contribute.

**Comment by kyyberi** [comment]
Third option is to add header "X-Recruit: apinf.com/positions" to platform APIs :)

**Comment by phanimahesh** [comment]
`X-` prefix has been deprecated ([BCP 178][]), so the header should read `Apinf-Recruit` if we do end up doing it. :P

[BCP 178]: https://tools.ietf.org/html/bcp178 'BCP 178: Deprecating the "X-" Prefix and Similar Constructs in Application Protocols'
