### ISSUE TITLE
Manual testing for release 0.48.0

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2785]
Test the 0.48.0 release on the staging server. Report any bugs or enhancement needs to https://github.com/apinf/platform/issues.

See the new and improved features in the [release notes](https://github.com/apinf/platform/releases) 

# Definition of done
* [x] Test any new development based on the release notes, particularly
  * [x] Swagger: REST API related functionality
* [x] Verify enhancements and the corrections for closed error reports (= bug fixes)
* [x] Go through acceptance testing
* [x] Update the testing document
  * [x] Create a PR for docs

**Comment by saralavanip** [comment]
Verified issues: #2728

**Comment by saralavanip** [comment]
@bajiat , completed task, closing the issue.
