### ISSUE TITLE
Take away 'No documentation link is available.' section from documentation tab

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#2788]
please!

**Comment by preriasusi** [comment]
![Screenshot from 2017-07-25 17-01-20.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550aa050e952617100a5cf13/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f37c3dd7b668ee1536515e424cac53444d04bea6d37ef5f22e7a98590eefd23f0a70923d17f8bd8016ba02ba20dd4e82e0bb8f5edcfa7f74b9dfd0126754505a9bf54f37a6934acd58f642e84c50ac123e6be5647b.png)

**Comment by marla-singer** [comment]
@preriasusi What do you suggest? If the remote documentation link is not provided then don't this section total?

**Comment by Nazarah** [comment]
@marla-singer The idea is that, if you have already a swagger document in your API profile, it might be confusing when an end user comes and see "no documentation link is available". For an API owner, seeing this text in his API profile when s/he has provided no documentation makes sense. However, if there is a Swagger uploaded already, the text should not appear.

**Comment by marla-singer** [comment]
@Nazarah APInf platform allows developers uploading and Swagger documentation and a link to remote documentation.

> However, if there is a Swagger uploaded already, the text should not appear.

For example, documentation of API-Umbrella: http://api-umbrella.readthedocs.io/en/latest/getting-started.html 
This is not Swagger document but there must be displayed. So I don't aggree

**Comment by Nazarah** [comment]
So in that case perhaps rephrase the text with "You can add an external link to your API Documentation." 
This removes all confusions as well as tells API owner about additional possible actions.

**Comment by marla-singer** [comment]
If a user is manager of current API then it displays text
![joxi_screenshot_1501055992217](https://user-images.githubusercontent.com/20643403/28610700-e00919c4-71f1-11e7-9511-8f225815ef7c.png)

I suggest if API manager doesn't provide link to external document then don't display this block for ordinary user but display for Admin or Manager

**Comment by Nazarah** [comment]
+1 to your idea.
In Addition, lets also remove "No Documentation is available." line from both Document block or swagger block. 
This is kind of a negative message. 
Besides, the 2nd line is self explanatory, as API manager comes and sees there is nothing but still s/he has the option to add something.
