### ISSUE TITLE
[PRODUCTION] Displaying of Swagger file doesn't work properly in some cases

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2791]
### Steps
1. go to page https://apinf.io/apis/openapi-space
2. navigate to Documentation tab
                    
### Found
- Turned on spinner
         
- Browser console: `Exception in delivering result of invoking 'parsedDocument': TypeError: Cannot read property 'schemes' of undefined`
- Server side console: `Error: Match error: Expected string, got null`
- Server side stack: `api_docs/server/methods/swagger.js in [object Object].Meteor.methods.parsedDocument at line 19:5`

### Expected
- Display Swagger file
                   
**Environment**:
APInf production site, v0.47.0
Google Chrome

### Guesses & Goals
- Uploading file doesn't work correctly. In some case, a user provides a link to documentation but saved type is `file`.
- Add the additional step of checking for error `TypeError: Cannot read property 'schemes' of undefined`

- Research the problem.
- Update the migration and double check

**Comment by bajiat** [comment]
@brylie Try to reproduce at least in development.

**Comment by marla-singer** [comment]
@bajiat I'm afraid it would happen because of early incorrect migration step. 
@brylie I think it could be reproduced if you would change develop to 0.43 version or 0.44, upload a swagger file or enter the link to the doc after that change the branch to the current release version.

**Comment by bajiat** [comment]
@marla-singer  Can you check with @shaliko if we need to clean up incorrect data manually?

**Comment by marla-singer** [comment]
@bajiat It is not a solution because this incorrect data are generated in our code

**Comment by bajiat** [comment]
@marla-singer Can you check whether this has affected production?

**Comment by marla-singer** [comment]
@bajiat It has affected to User Usability
![joxi_screenshot_1505723197054](https://user-images.githubusercontent.com/20643403/30533880-4a70ebba-9c64-11e7-8b75-b7650d60ea81.png)

**Comment by brylie** [comment]
What is the extent of the problem? How many APIs are affected? How likely is this to occur in other deployments?

**Comment by marla-singer** [comment]
> How many APIs are affected? 

I don't know how many APIs but this problem have been repeated 55 times during 2 months 
https://sentry.samposoftware.com/sentry/apinf-production/issues/30/

**Comment by brylie** [comment]
OK, it looks like it is happening a few times a day over the past couple of months. I am just wondering about the **effect size** of this bug. How might we assess how many APIs are affected?

**Comment by marla-singer** [comment]
@brylie I see as navigate through each API in catalog and check it by hand :thinking: 

> How might we assess how many APIs are affected?

**Comment by bajiat** [comment]
@brylie @marla-singer @matleppa Any volunteers to go through the APIs manually?

**Comment by matleppa** [comment]
I can go through the APIs.

**Comment by matleppa** [comment]
Apinf.io

#### Swagger documentation and status (2017-09-20) (0.50.0): ####
APInf Catalog REST API (fail) fails to open API
Customer Management API (OK)
Digitraffic Road metadata (Failed to load spec.)
GitHub (OK)
Laivadata - API (fail) fails to open API
Linked events (Turku) (OK)
Makeup API (OK)
MPASSid Register API (fail) API fails to open

OMDB API (fail) fails to open API
OpenAPI space (documentation does not open, perhaps swagger)
OpenAPI-webconverter (documentation does not open, perhaps swagger)
OpenWeatherMap (fail) fails to open API
  * Exception in template helper: TypeError: Cannot read property '_id' of undefined

Opintopolku Oppijanumerorekisteri (OK)
Petstore API (OK)
Product Catalog Management API (OK)
Product Inventory Management API (OK)
Salaxy Open API (OK)
Simple DX Poll REST API (OK)
Suomi.fi -palvelutietovaranto REST API (OK)
The NYT Article search (OK)
The NYT Books (OK)
TripGo (OK)
Trouble Ticket API (OK)
Turku Issue reporting API (OK)
Turku Street Maintenance API (OK)
Ylläs Events API (fail) API fails to open.
  * Exception in template helper: TypeError: Cannot read property '_id' of undefined

Ylläs transit routes as GTFS (OK)

#### Result ####
18 APIs with a loading swagger document
1 API with a swagger document failing to load
2 APIs, which possibly have a swagger document (timeglass just going on and on and on and on...)
6 APIs fail to open

Each operation causes lots of error log writings.
