### ISSUE TITLE
Dashboard Monitoring

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2795]
# Requirement

API owners need to determine if (some of) their APIs needs investigation and maintenance (spike in API requests, too much response time, lower users, etc). They also need to be informed if an emergency situation has occurred which need immediate attention (API end point is down).

# User Story

>As an API Owner, I want to monitor my APIs, so that I know how they are performing and if they require emergency maintenance.

**Comment by bajiat** [comment]
@Nazarah Can you please provide a description of the idea or user need?

**Comment by Nazarah** [comment]
@bajiat working on it.
