### ISSUE TITLE
If Apinf has only one API, front page could adapt to that better

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#2798]
https://educloudalliance.apinf.io/

ECA has only one API. Still it shows on front page "Latest APIs", and gives a button for more APIs.

In cutomer installations there may be one or two API(s) only. Still should not be confusing.

**Comment by Nazarah** [comment]
For a quick fix, we can always remove the More APis button from that section.
Also perhaps may be change the title of that pane as Featured APIs.

**Comment by bajiat** [comment]
We could also remove the section, when there are less than 3 or APIs. The same goes for Statistics section.

**Comment by Nazarah** [comment]
>We could also remove the section, when there are less than 3 or APIs. The same goes for Statistics section.

@bajiat I have my doubts if that would be something ideal to remove the API section from the front page.
If customer has only 1 API, neither the customer or its user would take the burden to discover the API from the catalog page.
It would be convenient for them if the one and only API is featured in the home page for quick access.
I agree on removing the statistics pane. And perhaps also the API catalog from nav bar.
