### ISSUE TITLE
Improve integration of OpenAPI designer

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2802]
In process of integration of OpenAPI Desginer into the platform @brylie raised the question about changes.

## Goals
- add 'OpenAPI Designer URL' to configuration settings page
- deprecate Swagger Editor setting

Related PR: https://github.com/apinf/platform/pull/2787

**Comment by Nazarah** [comment]
Closing this issue. Integration of OpenAPI Designer is being taken care separately.
