### ISSUE TITLE
[FIWARE] Diagram integration 'model' with FIWARE TMF Business API Ecosystem

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2807]
Create a diagram showing a hypothetical integration between APInf and [FIWARE TMF Business API Ecosystem](https://github.com/FIWARE-TMForum/Business-API-Ecosystem).

# Resources
- [Business API Ecosystem eLearning Course](https://edu.fiware.org/course/view.php?id=150)
- [Business API Ecosystem docs](http://docs.fiwaretmfbizecosystem.apiary.io/)

# Work in progress
- [Pull request #64 in APInf docs repo](https://github.com/apinf/docs/pull/64)
![screenshot_20170811_155431](https://user-images.githubusercontent.com/17307/29213781-61aaab10-7ead-11e7-8ebb-dcd620455412.png)

![screenshot_20170810_142204](https://user-images.githubusercontent.com/17307/29168385-5576a30c-7dd7-11e7-938b-8576ae3a94f6.png)

**Comment by bajiat** [comment]
Should we  list Dashboard as a component that needs to be linked/connected to the Business Ecosystem? Or is there some other way users can track their usage and costs? Maybe managers would also use Dashboard for viewing usage by users?

**Comment by bajiat** [comment]
Asset Type is duplicated

**Comment by brylie** [comment]
Fixed the issues you mention above.

**Comment by bajiat** [comment]
@brylie Add the diagrams  to the docs repository and close  this issue

**Comment by mauriciovieira** [comment]
http://apinf.org/docs/develop/Architecture/FIWARE-Business_API_Ecosystem-integration.jpg
