### ISSUE TITLE
Move all APInf packages' into /apinf_packages directory

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2810]
Our project structure is currently very flat, with the top level containing many directories. This can be a bit disorienting when first glancing the source code.

# Goal
Make the source code easier to understand by combining all project 'modules' under one directory.

- /
  - .meteor
  - .scripts
  - core/
  - docker/
  - apinf_packages/
    - apis/
    - branding/
    - catalog/
    - ...

  - tests/
- README.md
- ...

**Comment by saransh-dev** [comment]
Hi Brylie,

I would like to inform you that, we can use [meteor's suggest directory structure](https://guide.meteor.com/structure.html#example-app-structure). But it can take the time to change.

Please advise.

Thanks.
Regards,
Saransh

**Comment by brylie** [comment]
Thanks @saransh-dev. We have reviewed the suggested directory structure.

One of our mid-to-long term goals is to try publishing our APInf 'components' as NPM packages. All this PR is proposing is that we move all of our APInf 'packages' into a sub-folder, e.g. `/packages`. 

The structure of each package could follow the recommendations of the Meteor Guide.

**Comment by saransh-dev** [comment]
Yes, it's a good idea to convert in packages  @brylie

**Comment by brylie** [comment]
OK, thanks. So, do you think it is a reasonable step to move our current 'package-based' structure to a sub-folder? This is mainly for clarity and developer experience.

**Comment by brylie** [comment]
I am considering the directory name should be 'packages', since that word is used by both NPM and Bower. The previous idea about a 'modules' directory was inspired by Drupal.

**Comment by brylie** [comment]
Basically, everyone in favor of moving all of our APInf packages into a 'packages' directory, upvote this comment. If opposed, downvote.

**Comment by brylie** [comment]
Pull request is open for comment. WORK-IN-PROGRESS :smile_cat:

**Comment by mauriciovieira** [comment]
I am glad :-)

**Comment by brylie** [comment]
Thanks @mauriciovieira. We are on Experimentation Mondays today. Do you think you might have time to check out the branch and fix any of the errors you might encounter related to imports, etc., so we can finish this ASAP?
