### ISSUE TITLE
Research FIWARE IdM solution

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2812]
Research and potentially test single sign on with [FIWARE Keyrock](http://fiware-idm.readthedocs.io/en/latest/introduction.html#api). Start with the hosted SSO.

# Goal
* Document or diagram of integration between APInf platform and FIWARE IdP.
* List changes required to Settings view and Sign Up / Sign in views.

# Resources
- FIWARE uses [OpenStack Keystone](https://docs.openstack.org/keystone/latest/) for authentication, which has an [OAuth plugin](https://docs.openstack.org/keystoneauth/latest/authentication-plugins.html#v3-oauth-1-0a-plugins).
- There is a [discussion on Meteor Forums about adding a new OAuth SSO](https://forums.meteor.com/t/add-custom-authentication-method-openstack-keystone/38474).
- Related StackOverflow question: [How to add FIWARE/OpenStack Keystone authentication to Meteor app?](https://stackoverflow.com/questions/45547773/how-to-add-fiware-openstack-authentication-to-meteor-app)
- There is a [tutorial from 2015](http://robfallows.github.io/2015/12/17/writing-an-oauth-2-handler.html) describing how to create a custom OAuth 2 handler for Meteor.
- There may be several Meteor packages that have tried similar solutions for various OAuth proviers:
    - [JIRA auth package](https://github.com/optilude/meteor-jira-auth/)
- There are several [OpenStack Keystone packages on NPM](https://www.npmjs.com/search?q=openstack+keystone)

**Comment by mauriciovieira** [comment]
@bajiat @brylie Related #2767 

I sketched some code in #2778

**Comment by bajiat** [comment]
@mauriciovieira Can we close this issue, since we already have the implementation?
