### ISSUE TITLE
Don't display message about "This organization doesn't have any featured APIs"

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2814]
### Steps
- Login as Admin user
- Go to Organizations catalog and click on the button "Add organization"
- Fill in the form and Save a result
- Logout
- Login as user without permission (or create a new one)
- Navigate to the organization

### Expected & Found
- A user sees a message about "The organization doesn't have any featured APIs"

![joxi_screenshot_1502133748394](https://user-images.githubusercontent.com/20643403/29042408-77dcb806-7bbf-11e7-8323-c5700a6f98d8.png)

### Improve
- If a user is not admin or is not an organization manager then doesn't display any text about featured APIs
- If a user is an admin or is an organization manager then display message "You can feature APIs of your organization by pinning the related API card. You can choose upto four APIs to feature in your organization"

**Comment by Nazarah** [comment]
An alternative suggestion might be to change the text as: "You can feature APIs of your organization by pinning the related API card. You can choose upto four APIs to feature in your organization."
This message is more constructive and gives users an indication that this feature exists.

**Comment by bajiat** [comment]
@marla-singer Can  your provide  steps  to reproduce?

**Comment by bajiat** [comment]
@Nazarah The suggested  text is an enhancement, but nonetheless the user should only see it, if relevant to user's role (organization manager or admin)

**Comment by Nazarah** [comment]
yes I agree on that. It should be only the organization manager to see that text.

**Comment by matleppa** [comment]
What about the message "The organization doesn't have any connected APIs"? Should the same principle about restricting visibility according user role apply there also?



![no_connected_apis.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46e69ba5208d8da78aeaab46a062f1842055653f6b14b1247a80e03cfd1839545a5d4dfe145c0b44faad8c29afb33f708a0a0aea876a5a66da2f53fde6d640e258f075c95d8fa4bf8b46c1ed3d26e28c894d3c1c0c108aed10.PNG)

**Comment by Nazarah** [comment]
@matleppa you are right

**Comment by Vellames** [comment]
@matleppa i think that we should notify the user if the organization have no apis. if we remove the two messages i think that we need to add some other notification for user.

**Comment by Nazarah** [comment]
>@matleppa i think that we should notify the user if the organization have no apis. if we remove the two messages, i suggest add some other notification for user.

@Vellames The messages will only appear to organization managers when they go to the organization page and there is no connected or featured APIs there.
For normal users browsing the organization catalogue, we don't show related sections for their view.
