### ISSUE TITLE
Enable Single Sign On with FIWARE IDM

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2823]
# Description

On FIWARE we want to be able to automatically login on APInf if we have already logged in on IDM.

# User Story
As a FIWARE user, I need not to login again on integrated APInf instance if I am logged in on CKAN + FIWARE IDM.

**Comment by mauriciovieira** [comment]
So the behavior will be pretty similar to current Github login. A popup page might appear to let the user know s/he is authorizing through that FIWARE IdM instance. 

Currently we are working on https://github.com/apinf/apinf-accounts-fiware/ and https://github.com/apinf/apinf-fiware/, that will allow login to be done via IdM
