### ISSUE TITLE
Review document for APInf REST API guidelines

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2824]
Document is found in:
https://github.com/apinf/api-guidelines

**Comment by matleppa** [comment]
@kyyberi The discussion on 2017-08-16 about need of using API key when calling certain GET methods got some continuation today (2017-08-17). 
The solution is not necessarily straigh-forward, because the API keys are attached to a Proxy. 
* what happens, if an API is moved from one Proxy to another one
* user needs to use UI to get API key

@preriasusi might provide more detailed explanation of pros and cons of using API key in REST APIs.

**Comment by preriasusi** [comment]
Is the API key the same API key we get from proxy? 

We have cases where APInf is needed for the developer portal and API catalog, but no proxy features needed. In those cases there would not be API key to the proxies. Still catalog API surely needed. Is there any other way to identify users? OAuth? 

Also the case where's more then one proxy in APInf. Which API key to use? Or would any work?

**Comment by bajiat** [comment]
Closing the issue, since the review already took place.
