### ISSUE TITLE
Browser error:  Restivus is not a constructor

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2825]
** Follow the example given to submit a bug report **

**Title**: 

Mandatory fields are not identifiable

**Steps to Reproduce**: 
1. Pull a fresh `develop` branch
2. Run application
3. Open the main page and Open console in browser
                    
**Found**:
- Error stacktrace
```
Uncaught TypeError: Restivus is not a constructor
  at meteorInstall.rest_apis.catalog.js (catalog.js:9)  
  at fileEvaluate (modules-runtime.js?hash=2b888cb7873bacf38cf32f41d44ac3d4fd600b06:207)
  at require (modules-runtime.js?hash=2b888cb7873bacf38cf32f41d44ac3d4fd600b06:130)
  at app.js?hash=a744054b80fb482b18d545ed9fbc266cdf118cf7:58310
```
Problem in file -->  rest_apis.catalog.js @ catalog.js:9
         
**Expected Behavior**:
- No errors
                   
**Environment**:

Debian, Chrome browser, local environment v0.48.0, nightly.apinf.io

**Comment by matleppa** [comment]
Maybe the files 
* catalog.js 
* management.js 

should be in directory *apinf_packages/rest_apis/server* 
instead of *apinf_packages/rest_apis*, 
because their functionalities are meant to be on server side only.

**Comment by brylie** [comment]
Sounds good. Try it out.
