### ISSUE TITLE
Updating site logo requires page refresh

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2827]
# Description
Logo and image handling are confusing to users. When an image is uploaded for example as platform logo, there is a delay in updating and images first appear as broken images. 

Quote from a user: 
> If I remove the nonexisting logo and try to upload new one, nothing happens after file selection process is done
> Now it appeared but as broken image.

# Steps to reproduce
1. Log into nightly as admin
2. Go to settings menu by pressing the small icon next to your username
3. Select Branding
4. Delete the current logo for the site by pressing the trash can icon
5. Select OK to confirm the delete
6. Press upload logo
7. Select the image to upload

# Expected result 
Logo is immediately updated to Branding settings and to the upper left corner of the site

**Comment by brylie** [comment]
The steps to reproduce work correctly for me:

![peek 2017-09-26 11-47](https://user-images.githubusercontent.com/17307/30851220-a0a481ca-a2b0-11e7-9f4a-698c87b5ee2f.gif)

There may be a bit of delay from when the image seems to be uploaded, to when it is actually sent to the server and published back to the client.

**Comment by brylie** [comment]
I recommend we put this issue in icebox for the following reasons:
- the functionality works, although there are latency issues under some circumstances
  - it is not clear how often network latency will be high enough to cause significant confusion
- the situation is not common (i.e. it does not seem like Platform Branding Logo will be changed often)

I agree that the missing image placeholder is not ideal. I am just recommending that we icebox this issue among other priorities.

**Comment by preriasusi** [comment]
#3246 fixed this one.
