### ISSUE TITLE
Create a Login settings menu item and view

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2829]
# User story
As an admin user I need to be able to connect a FIWARE identity manager with an APInf instance by giving required settings

# Description
Admin should be able to give both Github OAuth and FIWARE OAuth login credentials. It could make sense to move the current Github secret settings from Settings view to a Login view and have a separate menu item for Login. (Compare with Proxies).

# Goal
* [ ] Admin can add the required OAuth settings for FIWARE sign in
* [ ] Admin can find this from a logical place together with Github id
* [ ] Admin can easily tell that they are giving details for Login
  * Note: Currently the Github settings for Github login only say Github, they do not mention login

This issue is related to #2767.

Open issue: list of required settings

# Wireframe
In Settings menu from APInf navbar, a new submenu called Login Platform is included.
Under the menu both Fiware and GitHub login credentials can be added..
This is supportive of listing future login and authentication platforms.

![image](https://user-images.githubusercontent.com/17976243/29771523-e9974bd0-8bfc-11e7-9a74-71ce2f62506b.png)

**Comment by mauriciovieira** [comment]
For FIWARE, since it can be more than one server instead of github, it makes sense to have an additional field to set the root-url of the IDM server

**Comment by Nazarah** [comment]
@mauriciovieira can you please list what would be the required fields for this to appear on the UI?

**Comment by Nazarah** [comment]
@mauriciovieira @bajiat wireframe is added. Please leave your feedback.

**Comment by mauriciovieira** [comment]
@Nazarah you got it! Thanks

**Comment by mauriciovieira** [comment]
@midyan got interested in changing the settings, so he'll do it and I'll review

**Comment by mauriciovieira** [comment]
@bajiat after deployment, I can setup a real FIWARE app for APInf in Production.
