### ISSUE TITLE
Deleting API doesn't delete API from umbrella

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2830]
While testing my automated tests, I noticed that even if i didn't have API connected to the umbrella proxy my proxy address still worked. I ran those tests hundreds of times and it only happened maybe 10 times. I don't know what causes this bug to occur. 
We are able to remove these manually from umbrella.
![proxy](https://user-images.githubusercontent.com/28555452/29506468-74cfd0a4-8654-11e7-8d08-3c353f6b5f96.png)

## STEPS
1. Create account and API
2. Connect API to apiUmbrella proxy
3. Remove API
4. Check if proxy address still works

Happened on:
chrome Version 60.0.3112.101 64bit
Apinf 0.48.0
API Umbrella 0.13

**Comment by bajiat** [comment]
We do not want to delete the API completely from Umbrella in order not to loose e.g. Analytics. But the calls should not be passed through the proxy any more. To be researched.

**Comment by wuder4** [comment]
this bug just happened again with nightly proxy while testing automated tests.
