### ISSUE TITLE
verifying email sends you to right page but the page is blank

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2848]
# Steps  
1.Visit https://staging.apinf.io  v 0.48.0
2.Create new account
3.Click link in email

# Findings 
* Page the link sends you has right address but it stays blank and wont load
* Reload fixes this problem

# Screenshot

![verify](https://user-images.githubusercontent.com/28555452/29664797-e1765e58-88d9-11e7-9ca2-f7822c3feee1.png)
You can see right address and page has finished loading

Tested on
Windows 8
Google Chrome latest (normal/incognito)
staging  v 0.48.0

**Comment by wuder4** [comment]
Was not able to reproduce in staging 0.50.0. Environment was same as in first test.

**Comment by marla-singer** [comment]
### Staging
1.Create a new user
2. Open e-mail and click on link
3. Redirect to home page, User is logged in and there displays a message about Verification (as Expected)
![2017-09-28 13-49-47](https://user-images.githubusercontent.com/20643403/30963099-ee01641a-a454-11e7-8988-e9404432d39e.png)

4. Log out and Click on link again
5. Redirect to home page, User is not logged in and there displays a message about Expired (as Expected)
![2017-09-28 13-55-23](https://user-images.githubusercontent.com/20643403/30963111-f2b7ea42-a454-11e7-86ed-7f666909625c.png)

**Comment by bajiat** [comment]
Closing as per suggestion.
