### ISSUE TITLE
Make API feedback private

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2849]
# Description

Based on customer feedback, some API owners may want either all or part of feedback be private.

# Goal

There is a setting
* [ ] to set all received feedback to be private
* [ ] to set an individual feedback item to be private
* [ ] When the feedback is set to private, it is still visible for
 * [ ] admin users
 * [ ] the API owner
 * [ ] the user who created the feedback (applies only to the feedback given by that particular user)

**Comment by Nazarah** [comment]
@bajiat API owner should have a controller in the Feedback tab for API profile for every comment posted about the API, right? to change the visibility of the feedback?

**Comment by Nazarah** [comment]
I also have a concern, that should making feedback private somehow will affect the transparency about users' feeling about the API usage and their state of interaction with the API owner?

**Comment by bajiat** [comment]
Would it be safer to only allow all the feedback be either open (visible) or private? For setting individual feedback private, I was thinking about feedback, e.g. error reports that could have security concerns.

**Comment by Nazarah** [comment]
>Would it be safer to only allow all the feedback be either open (visible) or private? For setting individual feedback private, I was thinking about feedback, e.g. error reports that could have security concerns.

For your concern, I suggest to make individual controller for each feedback to be hidden/visible. In Facebook, you can choose which comment(s) you wish to appear in the public view. Since deleting works the same with the current feedback functionality, I suggest wr implement show/hide feedback the same way.

**Comment by Vellames** [comment]
Can the admin also mark the feedback as private?

**Comment by Nazarah** [comment]
@Vellames site admin is a super user who becomes manager of all APIs added. S/he has the privilege to edit contents in an API profile. So by this rule, site admin should also get the privilege to make feedback private.

**Comment by Vellames** [comment]
@Nazarah Ok, thank you. Should i implement the button to make all feedbacks privates/publics?

**Comment by Nazarah** [comment]
@Vellames can you please confirm with Taija about implementing this? Because I am seeing this issue with Icebox label, meaning it is not currently in the prioritized list for implementation.

**Comment by bajiat** [comment]
@Nazarah This issue is confirmed to be implemented.

**Comment by Nazarah** [comment]
@Vellames @bajiat Please choose which version of the wireframe would you prefer to distinguish a private feedback from a public one?
1. indicating with **fa-eye-slash** icon
![apifeedback](https://user-images.githubusercontent.com/17976243/30314617-ecefc9c0-97a9-11e7-8c1e-0f9fd23407cb.PNG)
2. adding a transparent layer over the private feedback
![apifeedback2](https://user-images.githubusercontent.com/17976243/30314662-08fad394-97aa-11e7-96f7-9cb4ea3e3588.PNG)

I'll add the selected wireframe on the main comment of this issue.
