### ISSUE TITLE
Internationalize date formatting of charts

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2900]
### Goal
- Make date format for all charts depends on the current language

![joxi_screenshot_1505206783976](https://user-images.githubusercontent.com/20643403/30317153-f624d000-97b1-11e7-9501-d7e9b6494484.png)
![joxi_screenshot_1505207313774](https://user-images.githubusercontent.com/20643403/30317581-23eb90cc-97b3-11e7-92a5-dcbd3d777d7b.png)

**Comment by bajiat** [comment]
Would this be based on current language selection or user's locale?

**Comment by Nazarah** [comment]
@marla-singer @bajiat I vouch for user locale

**Comment by marla-singer** [comment]
> I vouch for user locale

Don't mind

**Comment by deligence-dharmendra** [comment]
Hi @marla-singer @Nazarah 
Dashboard link does not showing in my local environment, which branch we need to take pull request.Please advise.
