### ISSUE TITLE
REST API: Checking of DB errors and informing requestor is missing from most of the methods.

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2905]
## Description ##
When REST APIs are used in CRUD operations, it is possible, that DB operation fails because of some error situation in DB.
In these cases the API user must be informed in a controlled way with response message.

In some cases fulfilling one request needs several DB operations. When several DB collections are updated, the outcome must be consistent, either all operations succeed or no update at all is done, which requires some kind of rollback mechanism to be available.

**Comment by bajiat** [comment]
@matleppa Start by identifying and documenting the problematic cases

**Comment by matleppa** [comment]
There are different types of error case handling needed.

* in case nothing is gotten from DB
  * perhaps 204 instead of 200
    * GET /users , when list is empty
   * GET /users/{id}
* DB operation check needed
  * POST /users/{id}, 
    * check create + findOne (if not found, error)
 * PUT /users/{id}

**Comment by bajiat** [comment]
@matleppa What is this line in PUT users/{id}?
> check setting **company**

Do you mean organization?

**Comment by bajiat** [comment]
@matleppa Other than the previous comment, I'm ok with your proposal. Can you create issues for updating the error responses? After that we can close this issue.

**Comment by matleppa** [comment]
> @matleppa What is this line in PUT users/{id}?
check setting company
Do you mean organization?

This is one of the fields in User's profile. It is name as Company.

**Comment by matleppa** [comment]
Created issues 3056, 3057, 3058 and 3059.
