### ISSUE TITLE
Dashboard: exception when leaving the detail page

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2916]
## Prerequisite ##

There are APIs connected to a proxy.

## Steps ##
1. select Dashboard in Main menu
2. select an API
3. go to detail page (View details...)
4. select Dashboard in Main menu

## Result ##
4. Exception in browser development console 

Exception in template helper: TypeError: Cannot read property 'name' of undefined
    at Object.proxyName (http://localhost:3000/app/app.js?hash=126e8127224ddc0ae77dce6a05d6657e468a328a:4667:18)
 

## Expected result ##
4. No exception

**Comment by marla-singer** [comment]
@matleppa The last `develop` branch?

**Comment by matleppa** [comment]
@marla-singer Yes.
> The last develop branch?
