### ISSUE TITLE
Dashboard: API with no requests renders not correctly on narrow screen

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2917]
It seems, that an API without request data is rendered erroneously, when the screen is narrowed.
Probably because in that case the columns contain only response-time element and neither arrow element nor text-danger element.

### View on a broad screen ###

![dashboard_broad.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46ec95892b808ca89ded8041b652f1906b0a65633b0ba92e7391a172fd172e535c0d1ba815585910f9fb802ea5b63c268b5b5dead47f4366846c4ff8e7df46f554f832815d84beb68b49c0ed3e2ce28a8a4b3b1f060ac4.PNG)

### View on a narrow screen ###

![dashboard_narrow.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46ec95892b808ca89ded804da54fe29b3e046b313916ac217586f76ae5002e545d5c1cf9450c5f42a8fc8b22a3b53c70dc5d0cbbd6684d68d47f40f2ecdd42e64bef62994597b7b4804dc5e83a23e5898a4c3618061d9bb2.PNG)

Firefox 55.0.3
Chrome 61.0.3163.79

**Comment by Nazarah** [comment]
@matleppa can you please check if the issue still exists?

**Comment by matleppa** [comment]
This bug seems to be fixed with some corrections on Dashboard.
(Screen capture from nightly 2017-12-08)

![narrow_dashboard_window_ok.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46e69588318d94968be8ac4ba652f1862d79307a2700ac3c4f8ae86af3006b1300051bff054a5556f9fc8b28f4e338248a5a5fe8d3645a77c63d47adbfd418ba13a632c91edbe2e3d7158abd7f37ed998e47341f00198bf85e30a09a4ecc58ff59ac.PNG)
