### ISSUE TITLE
Server console error on Organization catalog page

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2918]
### Steps
1. Take the last develop
2. Sign in as Admin user
3. Create an Organization, connect anyAPI
4. Sign out
5. Navigate to Organization page

### Expected
No error

### Found
Error on a server console
```
Exception from sub organizationApisCount id e8MX2mTW5GPAWjNnM MongoError: $and/$or/$nor must be a nonempty array
  at Object.Future.wait (/home/daria/.meteor/packages/meteor-tool/.1.5.2.10g4bls++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
  at [object Object]._.extend.count (packages/mongo/mongo_driver.js:1091:51)
```

@Vellames I think it is related to issue when you made API count for Organization card

### Steps
1. Take the last develop
2. Sign in as Admin user
3. Create an Organization
4. Sign out
5. Navigate to Organization page

## Found
![2017-09-20 12-13-04](https://user-images.githubusercontent.com/20643403/30636337-d230e236-9dfd-11e7-9924-a0b2fa103008.png)

**Comment by Vellames** [comment]
I will take a look

**Comment by Vellames** [comment]
@marla-singer i tested the application but i don't saw any console message in organization profile

![screenshot_20170918_203745](https://user-images.githubusercontent.com/9345433/30569441-501bdee2-9cb1-11e7-98ce-c38ede12eb7b.png)

**Comment by marla-singer** [comment]
@Vellames 
1. Page is Organization catalog, not profile
2. Server console. not browser

**Comment by marla-singer** [comment]
@Vellames Sorry, try again and it happens if an organization doesn't have connected APIs :grimacing:

**Comment by Vellames** [comment]
> @Vellames Sorry, try again and it happens if an organization doesn't have connected APIs :grimacing:

No problem :)
