### ISSUE TITLE
Dashboard: Handling missing days in a timeframe

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2924]
# Description
If a user has selected a particular timeframe, e.g. Last 7 days, they should see those 7 days in the charts. This should happen even if there are days without any data, which should be represented as empty columns.

# Reason
- Our charts should be truthful: there should be an equal distance between days
- Our chart should fulfil the user expectation: seeing all of the last 7 days

# Screenshot
<img width="784" alt="dashboard-missing-ideas" src="https://user-images.githubusercontent.com/11626388/30479285-3c0279e8-9a1d-11e7-8b4a-3e65c6d19714.PNG">

**Comment by marla-singer** [comment]
@bajiat When data range is "Last 30 days" then chart doesn't render all 30 days and bars are too thin
![joxi_screenshot_1505482255755](https://user-images.githubusercontent.com/20643403/30484551-65435c30-9a33-11e7-9659-c0c3479e3219.png)

**Comment by bajiat** [comment]
Can you provide an image of what happens?

**Comment by marla-singer** [comment]
> Can you provide an image of what happens?

@bajiat I shared with you image where date range is "Last 30 days" and there displays all date that has a place to appear. I made it show you how it looks like.

**Comment by bajiat** [comment]
You don't necessarily have to have a label for each day, but the days should not be omitted totally.

**Comment by bajiat** [comment]
@marla-singer Are you interested in this task?

**Comment by marla-singer** [comment]
@bajiat Yes, I've started work on this task on Friday
