### ISSUE TITLE
Button "View Analytic" on an API Profile

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2925]
**Title**: 

Add the button "View Analytic" on an API Profile page

**Description**:

The button will redirect API manager from API profile directly to current API Analytic page

**Comment by Nazarah** [comment]
Like the idea. Perhaps we should also have a button in the Analytics page for an API that will redirect the user to API profile on clicking. :)

**Comment by kyyberi** [comment]
I would prefer to use "analytics" not singular
