### ISSUE TITLE
api name into url in dashboard

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2931]
I think it would be better to show API name instead of id in the url in dashboard.

![dashboard_url](https://user-images.githubusercontent.com/28555452/30532839-10ee3064-9c5f-11e7-81bf-ce9a221dda3e.png)

Also could we add back button from detailed view to overview of the dashboard.

**Comment by bajiat** [comment]
@brylie @Nazarah Should this we discuss these options:
- changing URL to slug
- moving detailed view to API profile

**Comment by Nazarah** [comment]
@bajiat originally we were thinking about showing analytics in the API profile itself. 
That would be more justifiable to associate analytics related to that API to the specific profile.
However, if we are going to keep the separate page, I vote for @wuder4 's suggestions.
