### ISSUE TITLE
White line between footer and info bar

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2935]
# Steps  
1.Visit https://staging.apinf.io  v 0.50.0
2.Scroll down

# Findings 
* Page has small white line between 2 same color blocks
* @Nazarah said that the info panel should after latest APIs
* This can be found in all sites

# Screenshot

![frontpage_footer](https://user-images.githubusercontent.com/28555452/30539101-9640cea6-9c79-11e7-9272-abfdf554511b.png)

In the screenshot, the position of the info panel is not shown very well. But in official sites its shown in wrong position.

Tested on
Windows 8
Google Chrome latest
staging  v 0.50.0
nightly  v 0.50.0
apinf.io v 0.47.0

**Comment by marla-singer** [comment]
@wuder4 As I remember It is feature, not bug

**Comment by bajiat** [comment]
Closing as wontfix
