### ISSUE TITLE
sorting in dashboard does not work

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2938]
# Steps  
1.Visit https://staging.apinf.io  v 0.50.0
2.Login and create 2 APIs
3.Connect APIs to proxy
4.Call API with API key
5.Check dashboard sorting

# Screenshot

![dashboard_sort](https://user-images.githubusercontent.com/28555452/30541381-da9047e4-9c83-11e7-9ad4-cb3fbbf7fa3f.png)

# Findings 
* There is no reverse order (eg z-a)
* Sorting does not change the order of the APIs

# enchancements
* Also names like highest response time is not as describing as eg. quickest or slowest
* There could be ascending and descending buttons as well (but rarely there is more than 5 APIs)
* According to @brylie there should not be placeholder buttons visible in the site (filter options button)

Tested on:
Windows 8
Google Chrome latest
staging  v 0.50.0 (localhost)

**Comment by marla-singer** [comment]
Close it because this feature hasn't been implemented yet 
#2758
