### ISSUE TITLE
Organization card: Misaligment elements

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2939]
### Place
Organization catalog
![joxi_screenshot_1505737236422](https://user-images.githubusercontent.com/20643403/30541724-3d070a7e-9c85-11e7-8311-4b913f4e685c.png)

### Expected
The alignment of Items must be in one line like for API card
![joxi_screenshot_1505738117892](https://user-images.githubusercontent.com/20643403/30542181-fe5515da-9c86-11e7-9b50-6002f1403778.png)

**Comment by bajiat** [comment]
@marla-singer Not sure what this issue is about. Can you please explain?

**Comment by marla-singer** [comment]
@bajiat 

### Actual result
![joxi_screenshot_1505811476637 1](https://user-images.githubusercontent.com/20643403/30584263-e5c14056-9d31-11e7-869a-6879e01b1276.png)

### Expected result
![joxi_screenshot_1505811476637](https://user-images.githubusercontent.com/20643403/30584271-e9cecae2-9d31-11e7-94e9-966aa61a31b3.png)
