### ISSUE TITLE
Error while import API config file

### ISSUE THREAD

**Issue by Vellames** [apinf/platform#2943]
**Steps**:

1. Go to the import api configuration file `/apis/import/`
2. Upload a API configuration file

**Description**

Nothing happens in the page but an error is shown in console:

![error import api](https://user-images.githubusercontent.com/9345433/30570285-a1337b6e-9cb6-11e7-9ad4-58d694a06ecd.png)

**Environment**

- Kubuntu 17.04
- Chrome Version 61.0.3163.79 (Official Build) (64-bit)
- Develop Apinf Branch

**Related Issues**

#2912, #2945

**Comment by brylie** [comment]
Can we remove the dropzone and ShareJS requirements here, and show a file select button instead? What other dependencies are used here (e.g. to parse the JSON/yaml)?

**Comment by Vellames** [comment]
> Can we remove the dropzone and ShareJS requirements here, and show a file select button instead? 

Yes, i think that a simple file input is the best solution 

> What other dependencies are used here (e.g. to parse the JSON/yaml)?

- **js-yaml** to parse YAML to JSON (NPM Package)
- **meteor/juliancwirko:s-alert** to show messages
- **meteor/cfs:filesystem** to iterate over each uploaded file

**Comment by brylie** [comment]
OK, lets try to simplify this view as discussed above. Basically, we will:

- deprecate ShareJS completely
- keep js-yaml (since it is useful in multiple places)
- keep cfs:filesystem (as it is, to my recollection, the way we are handling file uploads in our project)
- try not to add any more dependencies

**Comment by Vellames** [comment]
**Update: **

The method also shows an error when invoked

Server Console: 
`Exception while invoking method 'importApiConfigs' TypeError: Converting circular structure to JSON`

**Comment by Nazarah** [comment]
@Vellames what is the status of this issue? It has been in Progress for 2 months.

**Comment by marla-singer** [comment]
@preriasusi Closed this issue because it was resolved in the context of PR #2973
