### ISSUE TITLE
Manage API Documentation modal somewhat confusing

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2944]
# Context
The ManageAPI Documentation modal has two fields for linking remote API documentation. One field expects an OpenAPI Specification file, while the other field is used for any other type of link (e.g. a rendered API documentation portal).

# Problem
Having two fields with similar names is somewhat unclear:

- Link to API Documentation
- Link to other API Documentation

![screenshot_20170919_101914](https://user-images.githubusercontent.com/17307/30580080-ff5122d8-9d23-11e7-8c1c-fe18204518e1.png)

# Goal
Clearly differentiate the API Documentation fields. Help users understand how the fields work, and what type of link to provide (e.g. an OpenAPI Specification or plain HTML). 

Bonus: unify the fields, so the user does not have to differentiate the field types.

# Example
In the APInf.io API Catalog, the Apifonica - calls & SMS was configured with API Documentation. However, the configuration was incorrect, as a regular web page was provided in the field that expected an OpenAPI Specification file.

**Comment by Nazarah** [comment]
@brylie do you have any solution in your mind on how to address this?
Perhaps renaming the label so that it specifies that the file has to be OpenAPI specification or json/yaml file?

**Comment by brylie** [comment]
The solution could be as simple as changing the UI text, such as the form labels.

**Comment by Nazarah** [comment]
@brylie the info tool beside Add Documentation label already gives information about the file to be swagger json or yaml.
Also the label can be changed as: "**Provide Swagger or OpenAPI Documentation via**"
