### ISSUE TITLE
Design user flow for exporting and importing API configuration

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2945]
Our API Profile view currently has a tab where API owners can export API and Proxy settings. There is also a (currently broken) import page, which was designed for importing API settings (not proxy settings).

# Goals
- Allow users to easily export and import their API and Proxy settings.
  - Make exporting and importing easy to discover.
- Have a simple user experience related to exporting and importing API and Proxy settings. 
- Keep in mind the current user flow for adding an API, and offer an option to 'import existing API' during that process.

**Comment by brylie** [comment]
In case we remove the current import functionality, as part of cleanup in #2912, here are the files as they currently stand:

-
 https://github.com/apinf/platform/tree/55034ef7c170676355d83c3883f6d1aeb39466eb/apinf_packages/apis/client/import

**Comment by Nazarah** [comment]
@brylie in API profile, do we need to keep a separate tab for export/import API config?
the 1st thing we can offer is to do so when API owner is adding and API and s/he has preexisting config file.
From API profile, I believe the Settings tab can have this option for the API owner to export and import API config file from a distinguishable block.

**Comment by Nazarah** [comment]
@bajiat can u please mention the usecase for this?

**Comment by bajiat** [comment]
@Nazarah Exporting and importing the API settings in order to move or copy the API to another APInf instance. Minimizes the need to do manual copy-pasting. This is for the users who are not comfortable with using REST APIs to GET API data and to PUT/POST it with an API.

In order for this to be more useful, we should remove all instance specific data (like API id, manager id or logo image Id) from the exported files and have reusable data like name, logo URL etc.

**Comment by marla-singer** [comment]
@Nazarah @bajiat The wireframe is still not available. The logic of import has done but @Vellames can not finish it w/out wireframes

> Where should I add a button to call this screen?

**Comment by bajiat** [comment]
@55 Can you take a look at the design, since the logic should now be ready.

**Comment by 55** [comment]
@bajiat @marla-singer I will add those by the end of the day.

**Comment by 55** [comment]
![add-api](https://user-images.githubusercontent.com/7489044/31669414-af23ee08-b35d-11e7-8d4e-681ee72e1d84.png)

Text for subtitles can be checked from @bajiat.

**Comment by bajiat** [comment]
"Manually entering details" could be "Enter API details".

Can we add an 'OR' somewhere between the sections?

**Comment by bajiat** [comment]
By the way, has this comment been taken into account in the implementation?

> In order for this to be more useful, we should remove all instance specific data (like API id, manager id or logo image Id) from the exported files and have reusable data like name, logo URL etc.

**Comment by Vellames** [comment]
> "Manually entering details" could be "Enter API details".

Ok

> Can we add an 'OR' somewhere between the sections?

Yes, no problems

**Comment by Vellames** [comment]
> By the way, has this comment been taken into account in the implementation?

The import file ask for "name", "description", "url" and "lifecycleStatus". The manager id will be the id of  logged user.

**Comment by Vellames** [comment]
![api-import-add](https://user-images.githubusercontent.com/9345433/32029728-bec9cf9c-b9cc-11e7-8fb1-4dd14684eecb.png)

@55 @bajiat 
I added the input file here because the user can see and change the import file before effectively import the api.
Looks good?

**Comment by 55** [comment]
@Vellames go with it for now, looks alright.
