### ISSUE TITLE
Cover Image displayed incorrectly 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2948]
# Steps 
1.Visit https://staging.apinf.io v 0.50.0  
2.Login as admin  
3.Go to 'Branding' view  
4.Upload 'Cover image'  
5.Go to homepage  

# Findings  
Uploaded cover image displayed incorrectly  

# Operating system  
Windows 10  

# Browsers  
- Google Chrome Version 61.0.3163.91   
- Mozilla Firefox v 55.0.3    

# Screenshot  
![staging_0 50 0_uploaded_cover_image](https://user-images.githubusercontent.com/13309358/30586957-3aa68556-9d3a-11e7-9ea2-f0183add062d.PNG)

**Comment by bajiat** [comment]
I was able to reproduce the error:

![StagingCoverPhoto.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/551116a6d52f6a7100417fce/125516c66e82c728ace21e0d46db809b248b8daeace6a946b66df89b3d49653f6b14b1247a80e03cfd1839545a5d4dfe145c0b44faad8c29afb33f708a0a0aea876a5a66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3d23e7838b48361e051e8bed10.PNG)

**Comment by bajiat** [comment]
Expectation is that the picture fills the designated area for the cover picture
