### ISSUE TITLE
UI: easier way to browse through APIs

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2949]
## Description ##

Enhancements are needed to make browsing through APIs more user-friendly.

### Prerequisite ###
There are several APIs, the paging is in use.

### Steps ###
1. Go to another page (2/3/...) in API list view
2. Open an API
3. Press browser back button / APIs button in main menu

### Result ###
The first page in API list view is opened.

 ### Problem ###
In case user wants to go through APIs one by one, there are unnecessary steps needed in order to reach the following API.
1. scroll to end of API list view page
2. select page with pagination menu
3. scroll up or down to find next API (relatively to previously viewed API)

## Possible solution proposals (in random order) ##
- add paging menu also above the API list (partial help)
- add buttons [next API] and [previous API] into the single API view
- when browser's back button is pressed while viewing an API, it routes to previously open APIs page

**Comment by deligence-dharmendra** [comment]
Hi @matleppa,
api next and prev button behavior depends on api created date or its depend on client side  api sort by.

Please advise.

**Comment by 55** [comment]
@deligence-dharmendra don't start working on this task b/ API catalog UI will soon be completely changed.
