### ISSUE TITLE
User info. text not displayed in 'Table' view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2958]
# Steps 
1.Visit https://staging.apinf.io v 0.50.0  
2.Sign Up  
3.Go to 'APIs' catalog     
4.Go to filter tab 
5.Click on 'My APIs' and 'table' buttons  

# Expected Result  
User info. must be displayed both in grid and table views when no 'APIs found'    

# Actual Result  
User info. displayed only  in grid view and shows empty page in table view      

# Operating system  
Windows 10  

# Browsers  
- Google Chrome Version 61.0.3163.91   
- Mozilla Firefox v 55.0.3      

# Screenshot    
Table view: 

![staging_0 50 0_myapis_table_view_no_user_info](https://user-images.githubusercontent.com/13309358/30600742-f7f37546-9d68-11e7-9c4d-86df7646ef0e.PNG)   

![staging_0 50 0_mybookmarks_table_view_emptypage](https://user-images.githubusercontent.com/13309358/30600792-0e5300ea-9d69-11e7-9835-896ae7a2f1e2.PNG)

**Comment by bajiat** [comment]
The same error also when  you have no bookmarked APIs and you press My bookmarks in Table view: there is no user information, just empty space.

@saransh-dev Table view can be accessed by toggling the right most button
![grid and table view.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/551116a6d52f6a7100417fce/125516c66e82c728ace21e0d46ef869327c282a78ba9ab42a651f5d43f4f22646b48e13b628ae92dbc56395b4d5a4bae420a0a40a8f98f7fa3b43575895c0bbbd06a0973c32f0dbefad341eb5ee779c11ac7a4b6984ec0e23c20e78d8f473d19001d8ff65c27ed.PNG)

Grid view is the one where APIs appear as cards, table view is a single column table
