### ISSUE TITLE
Dashboard: dropdown menu selection label 'Yesterday' is misleading

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2960]
## Description ##
On Dashboard the time period for displaying data is selected with a dropdown menu.

The options are:
* Yesterday
* Last 7 Days
* Last 30 Days

When the 'Yesterday' option is selected, the dashboard shows the recent data, also today's data.
### Question ###

Should the label 'Yesterday' be more accurate, such as 'Last 24 hours' or 'Since yesterday'?

**Comment by marla-singer** [comment]
@matleppa Good question

**Comment by bajiat** [comment]
@Nazarah What is your view on this?

**Comment by Nazarah** [comment]
Sorry for the late reply
"Last 24 hours" sounds proper.
It gives a clear idea to the user from what time the data is being shown in the graph.
