### ISSUE TITLE
API Request Timeline spacing

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2975]
# Steps 
1.Visit https://staging.apinf.io v 0.50.0  
2.Sign Up  
3.Create new API  and connect to working proxy
4.Call API 2 times
5.Check API in dashboard detailed view
 

# Expected Result  
graph shows 0...1...2...

# Actual Result  
Graph shows 0...0.2...0.4....

# Operating system  
Windows 8

# Browser
- Google Chrome Version latest  

# Screenshot    

![apireq](https://user-images.githubusercontent.com/28555452/30793957-0ed70746-a1ce-11e7-853c-d731d0c48847.png)

**Comment by bajiat** [comment]
@wuder4 Do you disagree with seeing decimal numbers or with something else?

**Comment by wuder4** [comment]
To my knowledge you can not call API 1.5 times its either 1 or 2. So I think showing 1.4 calls should not be a thing.

**Comment by preriasusi** [comment]
Minor case. In real life couple call should happen only in testing, and even then too minor to fix.
