### ISSUE TITLE
UI: When an Organization is opened, it is scrolled down

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2976]
Similar issue as #2947, which concerns APIs.

Luckily in Organization case the phenomena is not as disturbing as with APIs, because in Organization case only part of cover image is not visible. 
However, the functionality is not logical.

## Description ##

When user selects an Organization from Organization catalog for viewing, the Organization is scrolled down in case user has scrolled down the Organization list view before selecting the Organization.

### Steps  ###
1. Open Organization Catalog (there must be more Organizations than can be displayed in one screen)
2. Scroll down Organization catalog view
3. Open an Organization 

### Result ###
Organization is scrolled down.

### Expected result ####
Organization is not scrolled down.

**Comment by marla-singer** [comment]
Tested it on nightly and it was fixed by #2989

**Comment by bajiat** [comment]
@marla-singer Thanks for checking.

Closing the issue as resolved.
