### ISSUE TITLE
Move dashboard 'data loading' indicator logic into own function

### ISSUE THREAD

**Issue by brylie** [apinf/platform#298]
The dashboard contains a 'loading data'/'data loaded, took ##ms' indicator block. The logic for updating this block is currently spread throughout the dashboard logic. Update the dashboard created and other relevant functions, so that there is only one function responsible for managing the 'data loading indicator'.

**Comment by bajiat** [comment]
@frenchbread Is this already taken care of?

**Comment by frenchbread** [comment]
@bajiat No, it is not. I can take this one for next sprint.

**Comment by bajiat** [comment]
Closing during icebox gardening.
