### ISSUE TITLE
Create a checklist for PR reviews

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2980]
PR reviews are essential for maintaining the quality of our source code. The code reviews should provide another perspective to the code and should check logic of the code as well as readability of the code. The code reviewer must not only check that the code fulfills the goal described in the original issue, but also that the reviewer and other developers would be able to maintain the code later.

Therefore it would be good to document what needs to be inspected in a PR review as a checklist.

**Comment by bajiat** [comment]
@brylie Should there be a checkpoint for migration? If the code changes existing database collection(s), migration has been written?

**Comment by brylie** [comment]
I added the 'migration' checkpoint to the above checklist.

**Comment by bajiat** [comment]
Any comments to the checklist from @marla-singer @matleppa or @mauriciovieira ?

**Comment by marla-singer** [comment]
No recommendation from my side

**Comment by mauriciovieira** [comment]
According to https://github.com/blog/2111-issue-and-pull-request-templates, we can just put `PULL_REQUEST_TEMPLATE.md` (and move `CONTRIBUTING.md` to this directory), right? I have small suggestions on Brylie proposal and will send a pull request with the template.

**Comment by matleppa** [comment]
Now, when the CONTRIBUTING.md is moved, perhaps we should also correct the links to point the correct destination.
