### ISSUE TITLE
Skills transfer

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2983]
# Items
- FIWARE
  - Business API ecosystem: API documentation, diagram
  - Overview and where APInf fits
- API Umbrella
  - Admin UI
  - Admin API
  - Elastic search
  - upstream requirements (existing and new)
  - documentation
- Open API designer, Open API space
- APInf platform and APInf in Github
  - APInf code space
  - PR review guidelines
  - repository awareness
  - Github presence

# To do
- [ ] Discussion and skills transfer sessions
- [ ] Document the sources of information

**Comment by brylie** [comment]
General guidelines, inspired by discussion with @bajiat:

General advice with regards to professional development:

# Study (seek continual personal enrichment)
Find a place to grow and seek out educational resources for personal enrichment, such as:

- Clean Code JavaScript (https://github.com/ryanmcdermott/clean-code-javascript)
- Modern JavaScript Cheatsheet (https://github.com/mbeaudru/modern-js-cheatsheet)

# Grow (extend beyond your comfort zone)
- Be receptive to constructive feedback, consider what is being offered
- Plan ahead and consider multiple solutions

# Practice (strengthen your craft)
- Be thorough when reviewiing pull requests
- Mentor your peers, 
  - share knowledge and 
  - offer constructive feedback
- Pay attention to detail

**Comment by brylie** [comment]
@bajiat, I sent invitations to @matleppa for a series of discussions over the next few days.

**Comment by brylie** [comment]
# Documentation sources
## FIWARE
### Business API Ecosystem
- [FIWARE Generic Enabler page](https://catalogue.fiware.org/enablers/business-api-ecosystem-biz-ecosystem-ri)
- [API Documentation](http://docs.fiwaretmfbizecosystem.apiary.io/#)

**Comment by brylie** [comment]
@bajiat I have added relevant documentation sources in the comment above.

@matleppa please respond to this thread to confirm that you are monitoring activity on Github, such as mentioning your name. This is important to make sure you are aware of what is going on with the team.

**Comment by brylie** [comment]
@bajiat I have co-assigned @matleppa, @mauriciovieira, and @marla-singer, so that we can all take responsibility for transferring important knowledge and duties.
