### ISSUE TITLE
API list title rows - background color needed?

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#2990]
On dashboard there are presented lists of APIs. 

![dashboard_lists_basic.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46ec95892b808ca89ded804fad4ee487164426602007e1673295f127b54778154d555ca9445a5c16a9fddd2ba0e23972835908edd13b5e73903a14bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8f493b1f04108ef95937a18b06.PNG)

Should the API list titles have background color in order to separate them better from API lines? (Does not necessarily be yellow)

![dashboard_title_background.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46ec95892b808ca89ded8057ad49fc91164426702203b124658be76af3006b1300051bff054a5556f9fc8b28f4e338248a5a5fe8d3645a77c63d47adbfd418ba13a632c91edbe2e3d7158abd7f37ed998e47341f00188ffa5c37a19842c958f559ac.png)

**Comment by marla-singer** [comment]
I think light grey color would be good

**Comment by Nazarah** [comment]
@matleppa try with the following colors #e1e1e1 and #f5f5f5 and see which color appears lighter and doesn't make the UI look heavy. use that one.

**Comment by marla-singer** [comment]
@Nazarah I've used #f5f5f5 color
![joxi_screenshot_1506937426248.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2814d778e3d0f005c2de7/125516c66e82c728ace21e0d46e29b822abd90aa9decba4db755ff80161772237f5df07c24d7b57aeb1a394d4d1f0cf31b0d0c00eef39b2ea3b43f22df585fedd7395a76cf3812acb8d41eb857bd25995397f4edd4189fb5646fb2c99d452c1f0c1288fa5d33a99a4ccc50fe43e84847e9.png)

**Comment by Nazarah** [comment]
@marla-singer  #f5f5f5 seems the perfect match. Go for it!
