### ISSUE TITLE
Low fidelity wireframes for eMQ dashboard

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2995]
# Description

Create low fidelity wireframes based on user / customer needs for eMQ dashboard
- overview
- details view

Get feedback on the wireframes and make a new version, if needed.

**Comment by Nazarah** [comment]
From the requirements discussed in HSL meeting, I came up with the following designs.
Also I sent those wireframes for review to the responsible personnel back in HSL.

# Dashboard

1. **Default View**
![image](https://user-images.githubusercontent.com/17976243/31269078-adaea9d4-aa87-11e7-918e-fd4199c0508f.png)

The default view has a table with columns for **MQTT Topic Tree**, **Average Bandwidth Utilization**, **Average Published Messages / Average Subscribed Messages** and **Clients Published / Clients Subscribed metrics**.
The default view appears for both incoming and outgoing messages.
Each cell contains a value for the related metric(s), an arrow and percentage number. The arrow and percentage number indicated the change in the value of the related metric.

2. **Expanded View**
![image](https://user-images.githubusercontent.com/17976243/31269110-d01f59aa-aa87-11e7-9e36-cf4859da85f3.png)

On clicking a row, it gets expanded and details about the metrics get displayed.
You can see that the value and information appearing are for both incoming and outgoing messages. (indicated within green rectangles)
To keep the UI simple and clean, trend graphs related to specific metrics are shown in the expanded view.
**Filtering** option allows you to view the dashboard as per **incoming**, **outgoing** or **both** types of messages. (within green rectangle)

3. **Filtered by incoming messages**
![image](https://user-images.githubusercontent.com/17976243/31269241-44da25a4-aa88-11e7-98b4-21359c732d4a.png)

When the dashboard is filtered for incoming messages, only the associated metrics, value or trends appear in the table and expanded view. (indicated within green rectangles.)
The filtering criteria gets displayed on top of the table, with a clear button for making the default view reappear.

4. **Filtered by Outgoing Messages**
![image](https://user-images.githubusercontent.com/17976243/31269296-81677346-aa88-11e7-834e-ed2aee197e56.png)

This works in the similar way as that described on 3rd wireframe.

**Comment by Nazarah** [comment]
# Analytics View

![emq3alternative](https://user-images.githubusercontent.com/17976243/31279163-b32efd90-aab0-11e7-8b96-dad4ac15493e.png)

On clicking details for a particular topic tree, the user is redirected to the analytics page for that topic.
The overview charts from the Dashboard view are repeated here.
In Addition, there are timelines charts to see trends of **Bandwidth usage**, **Average Message publication/delivery**, **No. of successfully delivered message vs. failed message** and **clients who published or subscribed to the topic**.
The default view is for both incoming or outgoing messages. This can be filtered by incoming or outgoing message. (except for the successful vs. failed message chart)
The timeline can be rendered for **last 24 hours**, l**ast 7 days** and **last 30 days.**

**Comment by Nazarah** [comment]
@phanimahesh can you please review the mockups and give me your feedback?
@55 looking for your comments as well.

**Comment by phanimahesh** [comment]
@Nazarah Looks good to me.

**Comment by Nazarah** [comment]
@55 and I have both agreed to take the ideas presented here for EMQ Dashboard and start making the actual designs. So closing this issue as it has been reviewed.
