### ISSUE TITLE
[production] KPIs not updated to Dashboard overview

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3003]
# Steps to reproduce
1. Login to apinf.io (e.g. as admin)
2. Go to dashboard
3. See the overview for APInf Catalog REST API
4. Open the detailed view for the same API and compare

# Expected result
See the same figures for Number of requests, Response time(median) and Users

# Actual result
Overview contains 0 for Number of requests, Response time(median) and Users, while Detailed view shows the actual figures

#Screenshots
<img width="881" alt="3003_production dashboard overview" src="https://user-images.githubusercontent.com/11626388/31069896-0d65cc96-a767-11e7-835c-d56998e9ba9f.PNG">

<img width="888" alt="3003_production dashboard detailed view" src="https://user-images.githubusercontent.com/11626388/31069897-0d65fd9c-a767-11e7-8b50-20705dae31c3.PNG">

**Comment by bajiat** [comment]
See also #2977 (duplicate)

**Comment by Nazarah** [comment]
![api dashboard](https://user-images.githubusercontent.com/17976243/31072613-3f052008-a771-11e7-88de-d86babc37e54.png)
Just to give the idea about how information for a particular API in Dashboard view looks like while in details view it has data for all charts.
Although not open for the same API, the overview charts don't appear and text "No information available" text appears when clicked on any row of the API table.
