### ISSUE TITLE
Move issue_template.md into .github folder

### ISSUE THREAD

**Issue by brylie** [apinf/platform#3010]
The project root folder contains a file called `issue_template.md`, which is used by Github when people create new issues. Github knows to look for this file in a special `.github` directory.

# Task
- [ ] move the `issue_template.md` into the `.github` directory

**Comment by kaptajnen** [comment]
Very low hanging indeed :)

**Comment by bajiat** [comment]
@kaptajnen Thanks for your contribution and interest towards APInf!
