### ISSUE TITLE
Median Response Time chart blank for APInf Management REST API

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3011]
**Steps to Reproduce**: 
1. go to page: https://apinf.io/analytic/Wn7B5BM82gaBcHax5
2. see median response time chart in the middle
                    
**Outcome**:

<img width="1182" alt="screenshot at lokakuuta 03 16-04-42" src="https://user-images.githubusercontent.com/1927158/31126484-95da1562-a854-11e7-89d7-df4e215f1d69.png">

         
**Expected Behavior**:
Something like what I see with APInf Catalog REST API

<img width="1151" alt="screenshot at lokakuuta 03 16-05-45" src="https://user-images.githubusercontent.com/1927158/31126523-bc9cfa0c-a854-11e7-8386-7f51b4439342.png">

**Environment**:

Mac, Firefox(55.0.3), APInf production site (https://apinf.io)

**Comment by marla-singer** [comment]
@kyyberi The value is 0
![2017-10-03 16-30-16](https://user-images.githubusercontent.com/20643403/31127747-5f9df3de-a858-11e7-889b-4e82c21498a6.png)

**Comment by kyyberi** [comment]
Ok. Is that true? I have difficulties to believr that everything always is performed under 1 millisecond. If that is the case, it's great.

**Comment by marla-singer** [comment]
If value is between 01 and 0.9 then it will round to 0

**Comment by kyyberi** [comment]
As acting end user my first impression is that it's broken dispite of the fact that api seems to be blazing fast. Perhaps that should be indicated to end user some other way than chart bar since that does not work in this case.

**Comment by Nazarah** [comment]
Perhaps a kudos message can be displayed for such APIs? ;)
like "The API responses fast! Good job!"
In color green.
Sometimes positive messages give good experiences to users and urge them to keep up the good work.

**Comment by marla-singer** [comment]
@kyyberi 
All endpoint that start from `//apinf/management/api/v1/organizations/*` returns 403 error and these endpoints have Mediam response time as 0ms. 
![joxi_screenshot_1507188797832](https://user-images.githubusercontent.com/20643403/31215545-a07182d4-a9b8-11e7-9da4-34f41b94df37.png)


If the response status is 2xx then response time isn't 0
![joxi_screenshot_1507188380457](https://user-images.githubusercontent.com/20643403/31215532-8be5bc04-a9b8-11e7-8a4e-9bbc78f25abb.png)

Don't see any trouble
