### ISSUE TITLE
arrow for percentage in API Response Time overview graph is displayed wrongly

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3014]
![image](https://user-images.githubusercontent.com/17976243/31215001-8e272e00-a9b6-11e7-8bf0-885d00aba7ba.png)

In the above picture, the API appears to have **very low response time**.
It is also 100% lower than the previous 7-days instance.
When an API responses very fast, it is performing well.
So when the response time is lower, there should be **green down arrow** indicating this.

# Cases
1. Response time is **higher** than a previous instance of time period (last 24 hours, last 7 days, last 30 days)
  - Show **red up arrow**
  - Show the **associated text in red**

2. 1. Response time is lower than a previous instance of time period (last 24 hours, last 7 days, last 30 days)
  - Show **green down arrow**
  - Show the **associated text in green**

**Comment by Nazarah** [comment]
@55 @kyyberi  any thoughts about this?

**Comment by 55** [comment]
@Nazarah amen to that.

**Comment by marla-singer** [comment]
@Nazarah @bajiat Have to be resolved in 0.51.0 release

**Comment by bajiat** [comment]
@marla-singer Did this get resolved with #2929?

**Comment by marla-singer** [comment]
@bajiat Nope. I researched it detailed. It is another bug and it happens when a request path doesn't have calls in the previous period. In this case, median response time was NaN and the current value is 0. 

Take it issue in work
