### ISSUE TITLE
Proxy URLs not shown in Catalog API

### ISSUE THREAD

**Issue by fdelavega** [apinf/platform#3016]
**Title**: 

Proxy URLs not shown in Catalog API

**Steps to Reproduce**: 
1. Create a new API providing the backend URL

<img width="1155" alt="captura de pantalla 2017-10-05 a las 11 19 37" src="https://user-images.githubusercontent.com/2911173/31220496-e94c86ae-a9c0-11e7-8610-5b249d85958d.png">

2. Configure the proxy for securing the API

<img width="1156" alt="captura de pantalla 2017-10-05 a las 11 20 25" src="https://user-images.githubusercontent.com/2911173/31220517-f336c954-a9c0-11e7-9b83-0b1f27dce29d.png">

<img width="1154" alt="captura de pantalla 2017-10-05 a las 11 20 35" src="https://user-images.githubusercontent.com/2911173/31220526-f7add8ec-a9c0-11e7-9364-3f9b680874f1.png">

3. Make a GET request to /rest/v1/apis to retrieve API Information

<img width="474" alt="captura de pantalla 2017-10-05 a las 11 19 49" src="https://user-images.githubusercontent.com/2911173/31220531-fdaf00f4-a9c0-11e7-9781-a3611a9cb321.png">
                    
**Outcome**:

The URL field included in the API resource of the Apinf REST API is always the backend URL used for creating the API, so when a proxy has been configured the API URL displayed in the portal and the one given by the catalog API are different.
         
**Expected Behavior**:

The URL field of the APIs resource should correspond to the API URL displayed in Apinf portal, which is the URL that should be used in order to access to the service
                   
**Environment**:

Apinf Docker image, develop tag

**Comment by bajiat** [comment]
If the API owner is using a proxy, they may not even want to disclose the real backend address to any other parties so that direct calls cannot be made. We need to consider thus whether we 
* want to include both backend URL and proxy URL
* or only proxy URL
for the APIs that are connected to a proxy.
