### ISSUE TITLE
trying to add API but I FAILED

### ISSUE THREAD

**Issue by ilarimikkonen** [apinf/platform#3017]
many many problems

**Comment by ilarimikkonen** [comment]
i have a separate doc, tryina addit somehow

**Comment by Nazarah** [comment]
@ilarimikkonen can you please mention the environment? (nightly, staging or production)
Doesn't seem to be a browser specific problem, but still please include the browser and OS version, as they are standards in our bug reporting process. :)

**Comment by ilarimikkonen** [comment]
[complaint_APINGF.zip](https://github.com/apinf/platform/files/1359003/complaint_APINGF.zip)

**Comment by ilarimikkonen** [comment]
YES!

**Comment by Nazarah** [comment]
>many many problems
Thank you Commadant Lassard!! :D 
![image](https://user-images.githubusercontent.com/17976243/31224134-5b5f48f8-a9d5-11e7-85a4-89ce6b0d2e10.png)
