### ISSUE TITLE
Clarification to the way dashboard calculates traffic by day

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3020]
For the discussion.

## Problem
It is not clear, how the traffic data (by days) is (or is wanted to be) presented in Dashboard.

There are two opinions about what one unit (a day) contains or should contain. 

### Days are 24 hour periods
According to one view, the Dashboard handles data in 24 hour units starting from the moment when a request was sent.
That way the units are always complete 24 hour periods.

E.g. a dashboard request is sent on 2 pm. The today unit (today/( last 24 hours) contains traffic data from yesterday 2 pm to today 2 pm. The yesterday unit contains data from day before yesterday 2 pm to today 2 pm, and so on.

### Days are days
According to another view the units are counted based on midnight. Then the today unit (day) were today from midnight to the moment the request was sent.  The previous unit (yesterday) were yesterday's traffic from midnight to midnight, and so on.
That way the current day is (almost) always not complete, but the previous ones are complete.

E.g. the dashboard request is sent on 2 pm. The today unit wil contain data from midnight to 2 pm, the yesterday unit contains whole yesterday data and so on.

In this case the option "Last 24 hours" in Dashboard period selection menu should be changed to "Today".

## What is the verdict?
Which alternative is the desired one?
This also affects the planned Flow REST API, because it and Dashboard need to function same way.

**Comment by matleppa** [comment]
@jarkko askeds a question on apinf-community channel.

Could we have a bit different line format (dashed) for the on-going day (from yesterday to this moment) to somehow indicate that it's not "ready". Previous days are fixed, but this day is alive?
![dashboard_timeline.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46ec95892b808ca89ded8057ad50f598204822316546b3397f8fe62bab0021435a5a4caf130d5b10fcffdd2ea4bf39738a5c5decd63b5871d42103eee9dc4be05ce36ade0d97bcae884dcae93825e0898f4c3e19001f8dfc4f78.PNG)

**Comment by jarkko** [comment]
Wrong Jarkko :-)

**Comment by matleppa** [comment]
Sorry 

# Matti

**Comment by Nazarah** [comment]
@kyyberi would be the actual Jarkko @matleppa :P 

>According to one view, the Dashboard handles data in 24 hour units starting from the moment when a request was sent.
That way the units are always complete 24 hour periods.

This is the functionality that I had in my mind when I was designing the overview and API request tiimeline charts. 
With the option **Last 24 Hours**, this sound more logical.

**Comment by Nazarah** [comment]
>Could we have a bit different line format (dashed) for the on-going day (from yesterday to this moment) to somehow indicate that it's not "ready". Previous days are fixed, but this day is alive?

One problem can arise from implementing a today line in the same chart it that it can create confusion among users who would get accustomed to render the dashboard and analytics view as Last 24 Hours, Last 7 Days and Last 30 days.
On selecting a specific period, all the lines and graphs get rendered accordingly.
So in such situation, if we introduce a single component indicating it to be a "Today" graph, not only it would create confusion along with the other lines (request, response ones) but might also create difficulties in integration.

One suggestion can be is to have a separate module in the current dashboard, which would monitor the selected endpoint live and provide related data
It can include a widget to show the response time of the endpoint, as well as plot a chart to show how the requests sent to the endpoint has varied from 12 AM of the current day.

Another option is to include a LIVE option in the time rendering option.
This would be used to show all the analytics starting from the 12 AM of the current day until the current local machine time.

**Comment by 55** [comment]
If there is a case for 24h let's just plan it and add.

ping: @marla-singer

**Comment by marla-singer** [comment]
@bajiat @matleppa @Nazarah 
I made research about what is timeframe used. 

### Date ranges
1. For current period that is displayed in charts
- from: Tue Oct 10 2017 03:00:00 GMT+0300 (MSK) (included parameter) 
- to: Wed Oct 11 2017 03:00:00 GMT+0300 (MSK) (excluded parameter)
2. For a previous period that is compared with the current period.
- from: Mon Oct 09 2017 03:00:00 GMT+0300 (MSK) (included parameter) 
- to: Tue Oct 10 2017 03:00:00 GMT+0300 (MSK) (excluded parameter)

It means the value is presented for "Today"

### Suggestion
1. Rename "Last 24 hour" to "Today" OR
2. Change logic to get data for last 24 hours

**Comment by bajiat** [comment]
@marla-singer In other words the timeframe in UTC is midnight to midnight today? So it is neither last 24 hours or Yesterday?

I would prefer option 2: Change logic to get data for last 24 hours.

The only thing I'm wondering, should the chart then also show if there are peaks of usage within the 24 hours. In other words, should there be a bar or line representing data for every hour or e.g. every three hours.

**Comment by Nazarah** [comment]
@marla-singer I'd prefer to use the logic for getting data in the last 24 hours.

>The only thing I'm wondering, should the chart then also show if there are peaks of usage within the 24 hours. In other words, should there be a bar or line representing data for every hour or e.g. every three hours.

@bajiat I'd recommend using sparklines to show peak usage timing in overview charts.
Sparklines are specifically designed to show peak values or given parameter.
[NVD3](http://nvd3-community.github.io/nvd3/examples/site.html) has such charts in its library.
Also we have seen client's preference to get sparklines to see trend of usages for a given period of time.

**Comment by marla-singer** [comment]
@bajiat As the first step, I display only time with value., look at the median Response time chart (other charts don't work with hour interval, I made test only on one chart)
![joxi_screenshot_1507824827720.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2814d778e3d0f005c2de7/125516c66e82c728ace21e0d46e29b822abd90aa9decba4db755ff80161772237e5cf17f28d7b47fed12394d4d1f0cf31b0d0c00eef39b2ea3b43f22df585fedd7395a76cf3812acb8d41eb857bd25995397f4edd4189fb5646fb2c99d452c1f021288fa5d32a89b4ec050fe4de74547e9.png)
![joxi_screenshot_1507824411073.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2814d778e3d0f005c2de7/125516c66e82c728ace21e0d46e29b822abd90aa9decba4db755ff80161772237e5cf17f24d4b278e811394d4d1f0cf31b0d0c00eef39b2ea3b43f22df585fedd7395a76cf3812acb8d41eb857bd25995397f4edd4189fb5646fb2c99d452c1f0d1288fa5d32a89b4ec051fe43e84447e9.png)

**Comment by Nazarah** [comment]
@marla-singer nice work with the axis showing time intervals for last 24 hours as well.
Please  show them for the other overview charts as well.
The original idea was to to include time interval when user selects last 24 hours time period.

What do you think about the sparklines?

**Comment by marla-singer** [comment]
@Nazarah  Well, sparklines chart doesn't impress me :D

**Comment by bajiat** [comment]
For the example chart, I would like to see the entire 24 hours even if there have been no calls at certain points of time. Could we for instance have 2-hour intervals for bars? That way the user always sees the 24 hours in the same way. And they can more easily understand whether the peaks occur during day or evening without staring so closely at the numbers represting the hours.

Also, might make sense to use 24-hour clock instead of 12-hour clock with AM and PM. Takes less room, faster to understand.

**Comment by marla-singer** [comment]
I googled about sparkline and it doesn't wait to display max and min value.

> A sparkline is a small embedded line graph that illustrates a single trend. Sparklines are often used in reports, presentations, dashboards and scoreboards. **They do not include axes or labels; context comes from the related content.** 

[Business Analytic site ](http://searchbusinessanalytics.techtarget.com/definition/sparkline)

> A sparkline is a very small line chart, typically drawn without axes or coordinates. It presents the general shape of the variation (typically over time) in some measurement, such as temperature or stock market price, in a simple and highly condensed way. Sparklines are small enough to be embedded in text, or several sparklines may be grouped together as elements of a small multiple. Whereas the typical chart is designed to show as much data as possible, and is set off from the flow of text, sparklines are intended to be succinct, memorable, and located where they are discussed.

[Wikipedia ](https://en.wikipedia.org/wiki/Sparkline)

Sparkline chart using Highcharts library. No min or max values on charts and they are so tiny!
https://www.highcharts.com/demo/sparkline

So the main idea of my comment - if a customer wants to see max and min value then the future task must describe this point because the definition of sparkline chart doesn't mean that on default

**Comment by Nazarah** [comment]
@marla-singer has there been any decision made about it?
@preriasusi would you like to make a new feature request regarding to this issue?

**Comment by marla-singer** [comment]
@Nazarah We should close this issue. Look at #3064 in the description box -- 
> Date picker: Change option of date range picker "Last 24 hours" to "Today". The charts will display data from midnight to current hour.

**Comment by Nazarah** [comment]
closing this issue as it would be fixed in #3064
