### ISSUE TITLE
Display SaaS pricing information

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3021]
# Description
* Users can view the pricing information on apinf.io
* The information needs to be on its own page, not on front page
* The link to the Pricing page needs to be customizable (not available in other deployments than SaaS)
* Any action buttons can be pressed and they will do the expected action.

# Wireframes

1. **New menu on NavBar**
![image](https://user-images.githubusercontent.com/17976243/31384041-f3c39aec-adc5-11e7-9a82-310a7af43bd8.png)

When a user has signed in, the menu would appear as the last one in the nav bar.
(if current nav bar style used) use font awesome icon "paper-bill" beside pricing text.

2. **Pricing menu on Footer**
![image](https://user-images.githubusercontent.com/17976243/31384282-f8f1d58c-adc6-11e7-8273-abcc3ebe5445.png)

3. **Pricing information in the new page**
![image](https://user-images.githubusercontent.com/17976243/31386680-4dcc7888-add0-11e7-9b58-02b5bccaa8a0.png)

The look and feel depends on the provided content styling in the HTML editor.

4. **HTML editor under Settings menu**
![image](https://user-images.githubusercontent.com/17976243/31385810-35963d4c-adcd-11e7-8804-7354819bae23.png

The custom editable HTML block exists in the same page.
However, there is a checkbox that allows the pricing menu to appear when checked.

**Comment by Nazarah** [comment]
based on a discussion with @bajiat, we agreed that the task would involve only placing the pricing layout shown at the front page of APInf platform to a new page.
The page can be accessed from the nav bar.
The existing html editor would be used to customize the pricing information and other clickable actions.
This would remain as it is as long as configurable pricing feature for APInf isn't designed and developed.

**Comment by 55** [comment]
@Nazarah yes, let's go with it.
For simplicity we just move existing layout to a separate page with minor changes.

**Comment by Nazarah** [comment]
@55 added the mockups for the new look.
Please take a look and give your feedback.
Especially to the location of custom html editor and associated functionalities. (4th wireframe)
