### ISSUE TITLE
REST API: Missing parameter description in logout endpoint

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3023]
## Description
In Catalog API and in Management API there are Logout endpoints.
The requests have mandatory parameters, but they are not properly described in swagger documentation,

### Following parameter definitions are missing:
Parameters
Name	Description
X-User-ID *
string
(header)	
X-Auth-Token *
string
(header)

![Logout_parameters.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46c49b9d2c9797969fe8ad42a958e4913b55653f6b14b1247a80e03cfd1839545a5d4dfe145c0b44faad8c29afb33f708a0a0aea876a5a66da2f53fde6d640e258f075c95d8fa4be8b46c1ed3d22e58b894c3c1f071c8aed10.PNG)

**Comment by matleppa** [comment]
The header parameters need not to be presented in Parameters section in swagger documents, because Swagger UI has its own way to handle them.  
There are buttons with picture of a lock opening an input form which is used to input header parameters.

**Comment by bajiat** [comment]
Closing as per suggestion.
