### ISSUE TITLE
Rest-API organization managers don't update to website UI and vice versa

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#3031]
# Steps 
1.Create organization with Rest-API
2.Add manager to that organization
3.Visit new organization as admin 
4.Check organization managers

# Expected Result  
both platforms show same data.

# Actual Result  
Rest-API and website have 2 different databases and only communicate when organization is created.

# Operating system  
Windows 8

# Browser
- Google Chrome Version latest  

# Screenshot    

![rest_api_org](https://user-images.githubusercontent.com/28555452/31335526-a10bcaf6-acfb-11e7-9b9f-dd238ad98749.png)

postman response is list of managers at the same time as we see different list of managers on website and minimongo.

**Comment by matleppa** [comment]
Could not repeat the problem.

![org_manager.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46e7869d1c8f82a78eeeba51e611b2843b492d762a10e17132d0b67aec407e550b5f48f8445a5641fff9897da7b16a778f4e17ff933c0120996048e6edc00db513b821814e80b6bb8c4ec1ea3f23e58a8c5d73.PNG)

Please re-check the test. 
E.g. the managerId might erroneously be given in endpoint.

**Comment by wuder4** [comment]
Could not repeat at nightly anymore so closing this issue.
