### ISSUE TITLE
You can't remove yourself from organization manager list

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#3032]
During making issue #3031 I noticed that you cant remove yourself from organizations manager list even if there are other managers in the organization. After consulting with @bajiat and @matleppa we decided to make this issue about this enhancement. 

# Screenshot

![rest_api_org2](https://user-images.githubusercontent.com/28555452/31335954-7b64d868-acfd-11e7-9e72-b92992f13267.png)

**Comment by bajiat** [comment]
Note that the option to delete yourself as the organization manager, is only available, when there is more than one manager, i.e. you are not the only organization manager.
