### ISSUE TITLE
Frontpage empty in Ubuntu Firefox 53.0

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3035]
**Steps to Reproduce**: 
1. go to page: https://apinf.io/
                 
**Outcome**:

Blank page and debugger says: 

![kuvakaappaus 2017-10-09 19-56-42](https://user-images.githubusercontent.com/1927158/31349520-409482cc-ad2c-11e7-8afe-4e25e2156204.png)

**Expected Behavior**:

Normal frontpage
                   
**Environment**:

Ubuntu 16.10, FF 53.0

**Comment by kyyberi** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return

**Comment by saransh-dev** [comment]
Hi @kyyberi,

I have opened https://apinf.io/ in FireFox and Chrome as well. I was not able to see the error `TypeError: can't convert undefined to object`and page has loaded well.
I have attached of both brower's screenshot below:-

## Chrome:-
### Version:- 62

![screenshot from 2017-10-25 16-38-28](https://user-images.githubusercontent.com/29011434/31995907-f6a41f54-b9a3-11e7-9236-dfcfc12d34c8.png)


## FireFox:-
## Version:- 56.0.0

![screenshot from 2017-10-25 16-39-36](https://user-images.githubusercontent.com/29011434/31995945-1e010f1c-b9a4-11e7-927c-115d908c3bd8.png)

**Comment by kyyberi** [comment]
Oh well, if it's just me and my ubuntu + firefox, then this is not a problem.
