### ISSUE TITLE
Navbar: Login platforms option unavailable in drop down menu for admins

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#3042]
# Steps 
1.Visit https://staging.apinf.io  v 0.51.0   
2.Login as admin  
3.Check the options in drop down menu on navbar   

# Findings  
-  'Login platforms' option unavailable.   
-  Whereas in other  views eg. Branding/Settings/Proxies/Account/Profile show the 'login platform' option in  left side menu bar   

# Screenshot 
![login_platforms_unavailable_dropdownmenu](https://user-images.githubusercontent.com/13309358/31533472-116dac22-affb-11e7-9411-7010708672d5.PNG)

**Comment by bajiat** [comment]
See also #2952.
