### ISSUE TITLE
Dashboard: click on 'Filter' icon not responsive  

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#3043]
# Steps   
1.Visit https://staging.apinf.io  v 0.51.0     
2.Login as admin    
3.Go to Dashboard   
4.Select Proxy 'Nightly Umbrella'    
5.Click on 'Filter' button  

# Findings    
Click on 'Filter' icon not responsive.      

# Screenshot  
![dashboard_filter_unresponsive](https://user-images.githubusercontent.com/13309358/31534674-98915bae-b000-11e7-8d46-908152eec26d.PNG)

**Comment by bajiat** [comment]
It is still a placeholder, not implemented yet.
