### ISSUE TITLE
FIWARE login gives internal server error

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#3051]
# Steps 
1.Make FIWARE account at https://account.lab.fiware.org/idm/
2.Login to staging using FIWARE account

# Expected Result  
successful login to staging.APInf.io

# Actual Result  
After you login to FIWARE and allow access to your account info it redirects you to APInf login and then it gives internal server error.

Same error when you try to register new account.

Also connecting to FIWARE server takes 10+ seconds.
# Operating system  
Windows 8

# Browser
- Google Chrome Version latest  

# Screenshot    

![fiwarelogin](https://user-images.githubusercontent.com/28555452/31609214-e4ccc77e-b27b-11e7-98bd-a65b7079ebae.png)

**Comment by bajiat** [comment]
@midyan Can you take a look at this error?

**Comment by midyan** [comment]
I have been looking into this issue for a few days, and PR #3070 should solve it too.

**Comment by preriasusi** [comment]
Still repro #3209

**Comment by Nazarah** [comment]
#3209 was closed. Closing this issue.
