### ISSUE TITLE
Dashboard: Change "yesterday" text to relevant value

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#3052]
Now date range picker on the Dashboard page has the option "Last 24 hours" instead of "Yesterday". The text about trend has still "yesterday" text

![joxi_screenshot_1508168176108](https://user-images.githubusercontent.com/20643403/31623417-0d663d9c-b2a8-11e7-969e-8cfab67c40dc.png)

@bajiat @Nazarah Please write the text is related to "Last 24 hours" for UI
- 0 errors in ???
- 100% higher than???

**Comment by bajiat** [comment]
I would suggest
0 errors in **last 24 hours**
100% higher/lower than **previous 24 hours**

Any comments from @Nazarah or @55 ?

**Comment by bajiat** [comment]
@marla-singer Do we need a new issue for changing the text as "Today" or can this be captured in any of the existing follow-up tasks?

**Comment by marla-singer** [comment]
@bajiat We can extend the exist issue #3068

**Comment by bajiat** [comment]
Have added details in #3068. Closing this issue.
