### ISSUE TITLE
Bug in API's import route

### ISSUE THREAD

**Issue by Vellames** [apinf/platform#3053]
**Steps**:

1. Create an API called "Import"
2. VIsit the API's page `/apis/import`

**Description**

The system loads the API's import page instead the API page

![import-api-name-error](https://user-images.githubusercontent.com/9345433/31643711-82196f40-b2c8-11e7-8159-ca067a8fda89.png)

**Environment**

- Kubuntu 17.04
- Chrome Version 61.0.3163.79 (Official Build) (64-bit)
- Develop Apinf Branch

**Comment by Vellames** [comment]
My suggestion is change the import route to `api/import` instead `apis/import`

**Comment by bajiat** [comment]
@marla-singer or @matleppa Any opinions?

**Comment by marla-singer** [comment]
@bajiat API import will remove from `apis/import` route and it will be resolved by #2973 PRs

**Comment by bajiat** [comment]
@vellames Please add to PR #2973 that it closes also this issue: Closes #...

**Comment by Vellames** [comment]
> @Vellames Please add to PR #2973 that it closes also this issue: Closes #...

Ok :)

**Comment by Vellames** [comment]
Done :)

**Comment by marla-singer** [comment]
Verified on nightly and it is resolved.
The issue was fixed by PR #2973
