### ISSUE TITLE
REST API: DB check, 204 when empty answer

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3056]
## Description

When GET method is used and response contains only an empty list, HTTP code 204 must be used instead of 200.

Concerns at least following methods:
    * GET /users , when list is empty
    * GET /users/{id}, when not found
    * GET users/updates, when list is empty
    * GET /apis, when not found
    * GET /organizations, when list is empty

**Comment by preriasusi** [comment]
It's done.
