### ISSUE TITLE
REST API: (organizations) verify DB operation outcome before sending response

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3057]
## Description

When DB collection content is altered during method call, it must be checked, if the operation was successful before sending response message.

In case operation failed, HTTP code 5xx is used in response message.

At least following methods are concerned:
  * POST /organizations
    * check insert + findOne (if not found, error)  
  * PUT /organizations/{id}
    * check update + findOne (if not found, error)  
  * DELETE /organizations/{id}
    * check removeOrganization 
  * GET /organizations/{id}/managers
    * check users find (looking for managers' user account)
  * POST /organizations/{id}/managers
    * check update (find after update check is OK)
  * GET /organizations/{id}/managers/{managerId}
    * check users find (looking for manager's user account)
  * DELETE /organizations/{id}/managers/{managerId}
    * check removeOrganizationManager

**Comment by deligence-dharmendra** [comment]
Hi @matleppa, I have used 500 status code for failure message, But I did not get any issue related to below topics, In both cases validation already exists.Can you more elaborate on below topics.

GET /organizations/{id}/managers
GET /organizations/{id}/managers/{managerId} 

Please advise

**Comment by matleppa** [comment]
It is possible, that the situation has changed after the issue was created.
Possibly within other implementations there have been additions to previous functionality, such as addition of error checking.

Just go through the code of all mentioned endpoints and add the error checking in places, where it is still missing.
