### ISSUE TITLE
Nightly FIWARE registration fails because of email verification

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3060]
# Steps to reproduce
1. Create an account to FIWARE Lab: https://account.lab.fiware.org/
Note: Please use an email you are not already using for APInf
2. Go to nightly.apinf.io
3. Press Sign up link
4. Press Register with FIWARE
5. In the Fiware Lab window that open, give your user credentials for FIWARE Lab and authorize APInf

# Expected result
User is registered to APInf and can sign in with the FIWARE credentials. No email verification should be done (compare with Github registration).

# Actual result
User gets a notification about Email being sent to user. User never gets an email to their mail and thus user cannot sign in. If user tries to sign in, they get the same notification about email.

<img width="700" alt="nightly-fiware-register-usernotification" src="https://user-images.githubusercontent.com/11626388/31708301-3e989ac2-b3f7-11e7-86a5-656e0c207ff8.PNG">

**Comment by midyan** [comment]
This might be due to faulty email verification when a new user is created. I will assign myself in this issue and create a PR to submit the bugfix

**Comment by midyan** [comment]
After some further checking, I could not reproduce this issue when running platform locally in my computer by running the develop branch. I need someone else to try and reproduce it.

**Comment by bajiat** [comment]
@midyan Did you enable email in Settings for localhost?

**Comment by wuder4** [comment]
I was able to reproduce this in nightly.

**Comment by midyan** [comment]
@bajiat I have not, that's why the login was successful when running on my machine. I have also tried to login on Nightly using the Github and the same bug happens. 
I do not believe that an email verification is necessary when registering with a third-party IDM. I will discuss a solution in the PR I have opened, we can continue from there

**Comment by mauriciovieira** [comment]
I think it might be related to not associating a new meteor account just like github does. I'll open an alternative PR with my idea.

**Comment by mauriciovieira** [comment]
@midyan notice that https://github.com/apinf/platform/blob/develop/apinf_packages/users/server/accounts_hooks.js#L41

 is called because there's no `else` for fiware case yet.

**Comment by mauriciovieira** [comment]
I mean 

```
Meteor.call('sendRegistrationEmailVerification', user._id);
```

**Comment by mauriciovieira** [comment]
http://www.meteorpedia.com/read/Merging_OAuth_accounts
