### ISSUE TITLE
Reconsider help text for tables "Most frequent users" & "Errors statistic"

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#3063]
In the process of refactoring request to Elasticsearch, I found not matching between the table values and the help text.

### Screen 1
- The actual number of users is 2 but the help text displays info about 4 users

![joxi_screenshot_1508414028243](https://user-images.githubusercontent.com/20643403/31769687-54e2e800-b4dd-11e7-9acb-8470d709b600.png)

### Screen 2
After changes on local environment:
- The actual number of users is 2 and the help text displays 2 as well but the table has 4 records
![joxi_screenshot_1508413996939](https://user-images.githubusercontent.com/20643403/31769670-428d5d34-b4dd-11e7-9bf0-2394d9edfd34.png)

### Suggestion
- Change the help text to correct value

BTW, the same stuff for "Errors statistic" table. It doesn't display "6 of 100 errors", it does "6 of 100 records"
![joxi_screenshot_1508413888261](https://user-images.githubusercontent.com/20643403/31769603-03ce4d38-b4dd-11e7-958d-03a95bf41778.png)

@bajiat @Nazarah @55 Wait for your feedback

**Comment by bajiat** [comment]
For the most frequent users (screen 1 and 2) can't we just show only unique users? Why show d.voutova twice for different endpoints? Can we combine the endpoints?

For screen 3, what is the difference between "errors" and "records"?

**Comment by marla-singer** [comment]
>  Why show d.voutova twice for different endpoints? Can we combine the endpoints?

@bajiat And how would look this table if we combine the endpoints?

> For screen 3, what is the difference between "errors" and "records"?

Look at the table. You can see that the table contains 6 records (rows, lines) but in date range between 3:00 AM - 3:05  AM it was 20+21+27+22+25+25=140 calls with 4XX response status codes. It means it was 140 errors during 5 mins. But the bold text tells you "Show **6** of 16724 errors"
The real number of errors is 140 that is presented in the table.

I think we should ice or event close this issue because #3064 perhaps will change it

**Comment by bajiat** [comment]
Right, got your point about the "records"

Probably the users should be affected as well. The API owners want to see, which particular users are the most frequent ones, hence we should show a sum for each individual user for the whole API.

Closing as per suggestion.
