### ISSUE TITLE
Design REST dashboard changes

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3064]
# Description
* API owners should be made aware of the fact that all times shown on the dashboard are server times.
* Unique users chart: figure shown at the top should be changed to Average users, the title of the chart could be API users
* Date picker: Change option of date range picker "Last 24 hours" to "Today". The charts will display data from midnight to current hour.
* Errors table: 
  * show the error rate above the table (errors from all calls) in the similar manner as you have a figure for API users or response times
  * consider showing the errors sorted as latest errors. 
  * Remove the number of calls per individual error
  * Consider whether user should be able to go to another view to look at more details on all errors for a timeframe or whether they would need to see details per individual error

**Comment by bajiat** [comment]
@55 See also the comments by @marla-singer in #3072

**Comment by Nazarah** [comment]
@bajiat need clarification for the following things.

> Unique users chart: figure shown at the top should be changed to Average users, the title of the chart could be API users

Do you mean to show average number of users for specific time period in the overview graph?
If we think about changing the graphs into sparklines (as original design), showing the exact number of users might be more favorable.
