### ISSUE TITLE
Dashboard last 24h chart

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#3068]
# Issue

How informing is the chart in last 24 hours? There is 1 bar that shows that days calls. 

# solution

Would it be possible to show bit more data eg. hours?

# Screenshot

![dashboard_info](https://user-images.githubusercontent.com/28555452/31881484-4ddcee36-b7ec-11e7-89ed-fe128d63e118.png)

I just don't see this as useful data. You could just ignore the chart and read the value above it.

# Description
(added by @bajiat 2017-10-26
* Pick a suitable time interval for showing the data for the past day: e.g. bar for each 2 hours.
  * There must be a placeholder also for timeunit that have no calls.
* The data to be shown should be "Today" instead of 24 hours or Yesterday. Today should start from 00:00 (server time) and end in current time
* Allow user to drill down to smaller time unit

**Comment by bajiat** [comment]
I agree with @wuder4 that the current day cannot be just one bar. We could consider showing bars for every 2 or 3 hours and then providing the user a possibility to select an even smaller timeframe for viewing.

I checked with a customer and their wish as the smallest timeframe user needs to be able to drill down to is 5 minutes. This does not need to be the default which we are showing on dashboard, but  it should be possible to see also this level.

**Comment by Nazarah** [comment]
@wuder4 @bajiat 
Might be a bit late to comment so as the timeline would be changed from "Last 24 Hours" to "Today".
So Just wanted to point out that if we are measuring upto current time (say it is 8 AM, and the time for todat starts from 12 AM), then we need to make a decision about a suitable hourly interval. 
e.g. 12-3-6-9 has three hour intervals within.
So for 8 AM: 12 3 6 8
for 10 AM: 12 3 6 9 10

Please give em your feedback if you understood my pov.

**Comment by Nazarah** [comment]
Feedback from @55 
The look and feel of the charts would change soon. So this would resolve this issue.
