### ISSUE TITLE
Dashboard: Break single ElasticSearch query to multiple queries

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3071]
# User story
As an API owner or administrator, I do not want to wait for the entire page to load before I can see any data on the dashboard Details view.

# Description
In the current Details view implementation, a single ElasticSearch query for the selected timeframe. This means that data for all charts and figures needs to be returned before anything gets shown on the dashboard. Hence with APIs with large amount of calls, users might be looking at the spinner for 30s.

# Goal
Single ES query is broken into multiple queries, perhaps query per chart.

**Comment by marla-singer** [comment]
# Probably solution
1. Overview charts
- Separate reques to get data for chart and another request to get data about total numbers  (sum requests, general medial time and unique users number)
- Make it reusable for Dashboard page

2. Response status codes
- Make a separate request
- Think about make it reusable for Dashboard page

2. Charts "API Request Timeline" and "API Response time"
- Make a separate request

3. Table "Errors statistic"
- Make a separate request
- Order by data on the server side

4. Table "Most frequent users"
- Make a separate request
- Order by calls on the server side

Nice to have:
- Set the records limit as 6
- When a user clicks on the link "Download all users" then send an additional request to get all data

**Comment by bajiat** [comment]
@marla-singer and @55 Can you look at the spinner design together?

**Comment by Nazarah** [comment]
@bajiat @55 I had proposed an custom APInf spinner idea in this issue #3030 
Could you consider this for our APInf instance?
