### ISSUE TITLE
UI: change title of button "More APIs" to e.g. "All APIs"

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3073]
## Description

In opening page of APInf there is either view of Featured APIs or view of Latest APIs.

Below them is a button "More APIs".

When button is clicked, the APIs page opens.

### Problem

Semantically the title of button feels not accurate, because clicking it does not add anything in current view, but moves the user to different page, which contains all APIs (, although they might not be visible at a time).

### Proposal 
When button were renamed to "All APIs", it would be more descriptive, because after clicking the button the user will be able to see all APIs without a division to Featured/Latest APIs.

**Comment by bajiat** [comment]
I don't see much of a difference between using "More APIs" or "All APIs" and the user expectation of either staying on the same page or going to another. Besides, user does not see all APIs when they go to catalog, only the first page of catalog.

Closing as 'wontfix'.
