### ISSUE TITLE
[API Analytics view] UI for charts when data isn't available or get error

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#3074]
## Actual result
Now an Analytic Page is like monolith and all process

If Elasticsearch responses with errors then the page looks:
![joxi_screenshot_1509009559537](https://user-images.githubusercontent.com/20643403/32045043-e8e2a9e0-ba47-11e7-9866-67d807b91543.png)

If no data is available for this timeframe/request path then the page looks:

![joxi_screenshot_1509009462877](https://user-images.githubusercontent.com/20643403/32044956-b175fc1e-ba47-11e7-8841-5b3a899d9be6.png)

### Goal 
I specified with red rectangle every area that is independent. Keep in mind that some request can return an error but other return success response. Keep in mind that some request can return an empty data (for example, tables)

1. Prepare UI when Elasticsearch responses with errors:
- How does the page look if one area display error message
- How does the page look if all requests return an error and all chart need to display error message

2. Prepare UI when no data is available for this timeframe/request path:
- How does the page look if one area doesn't have data to display it
- How does the page look if all chart don't have data to display it

![joxi_screenshot_1509009221603](https://user-images.githubusercontent.com/20643403/32044826-5145680c-ba47-11e7-9c42-d65645a3161d.png)

Related issue #3071

**Comment by Nazarah** [comment]
**Scenario 2:** _When No data is available for the analytics to show._
![screen shot 2018-07-19 at 12 22 16](https://user-images.githubusercontent.com/17976243/42934267-68d4d988-8b4f-11e8-8d28-a2b183989a14.png)
`No data available` text is shown below timeline dropmenu and on the placeholders for API Calls, Response Time, Unique users, API Request timeline, API Response Timeline, Error Statistics and Most Frequent Users.
There is no need to show initial chart plottings if no data is available to show.

**Scenario 2.2:** (If possible & implementation is easy) _one chart / table has no data to display_
![screen shot 2018-07-19 at 12 22 27](https://user-images.githubusercontent.com/17976243/42934391-b8e4e0d0-8b4f-11e8-84b5-a216e5747d61.png)
`No data available` text also appears in the placeholders for associated chart/table
(for overview charts) no need to show up/down arrow and changes  in percentage on KPI value
the following text can also be added (optional) below the chart/table: `No data is available for this chart for the selected time-period`

**Comment by Nazarah** [comment]
**Scenario 3:** _When an error occurs while fetching/loading API Data:_
![screen shot 2018-07-19 at 12 22 50](https://user-images.githubusercontent.com/17976243/42934941-16864282-8b51-11e8-8025-53d2f015ef90.png)
`Something went wrong. Please reload the page. If the problem remains, please call the site admin. `text is shown below timeline dropmenu and on the placeholders for API Calls, Response Time, Unique users, API Request timeline, API Response Timeline, Error Statistics and Most Frequent Users.
No need to show the initial chart plottings/table here.

**Scenario 3.2:** (If possible & implementation is easy) _Error occurs while loading data for a single chart/table:_
![screen shot 2018-07-19 at 12 22 59](https://user-images.githubusercontent.com/17976243/42935057-60c1fcd8-8b51-11e8-891f-feb47f19ee89.png)
**Something went wrong. Please reload the page. If the problem remains, please call the site admin.** text is shown on the placeholder for the chart/table
There is no need to show the chart in such condition.

**Comment by Nazarah** [comment]
**style attributes:**

font-style:**italic**
color (for normal texts): **#b5b5b5**
color (for error texts): **rgb(169,68,66)**
font-size (for text below time dropmenu): **20px**
font-size (for texton chart/table placeholders): **14px**

@55 wireframes are available and ready for review.

**Comment by 55** [comment]
@Nazarah it's alright

**Comment by ilarimikkonen** [comment]
iceboxed - pending analytics overall review

**Comment by Nazarah** [comment]
CLosing as Dashboards in Next will be different
