### ISSUE TITLE
UI: Restrict length of Organization name in API card

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3076]
## Description

In case name of Organization, in which an API is connected, is long, it increases the length of API card, which causes API cards in next line to be shown unevenly.

### Possible solution

Restrict the length of field for Organization name.
- only one line in a field
- or two lines, in which case the height of the field must always be set for two lines

**Comment by matleppa** [comment]
See API MPASS.id.
Organization name takes two lines, thus the card length increases, causing next line of APIs to be uneven.

![api_card_height.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46e984931c8182bb8bd6b746ad5af8806b0a65633b0ba92e7391a172fd172e535c0d1ba815585910f9fb802ea5b63c268b5b5dead47f4366846c4ff8e7df46f554f832815d84beb68b49c0e13d27e5888a4b3717020ac4.PNG)

**Comment by bajiat** [comment]
We could also consider if we need to use the words "Added by" before the user or organization name.

**Comment by 55** [comment]
@bajiat @matleppa let's remove "Added by" and use same logic as for "API Name" to truncate organisation name.

**Comment by bajiat** [comment]
Agree with truncating. Let's restrict the length to one line.

**Comment by Nazarah** [comment]
I actually prefer the idea of restricting the API name in 50 characters. Thing about Twitter where it gives u only 140 characters to express your feelings. Also practically, almost no1 prefers to use long names for anything. Just a thought.
(friendly reference below. :D )
![image](https://user-images.githubusercontent.com/17976243/32264358-0a93ab5e-bee7-11e7-8f05-a41b01735895.png)

**Comment by bajiat** [comment]
Also something to consider: smaller font in for organization or username?

**Comment by 55** [comment]
@bajiat looks fine for me. 
Also I can create quick right away for this issue.
