### ISSUE TITLE
Developers need to see logs in real time in servers Nightly and Staging

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3077]
## Description

In order to be able to debug, what happens in server, the developers need ability to browse server logs in real time.

### Use case
Developer needs to see, what happens in server, when a HTTP request is sent via a proxy.

In case request is not a simple request, the browser generates an OPTION request.
That can not be seen with browser tools only, but a support on server side is needed also.

**Comment by bajiat** [comment]
@shaliko Can you please comment this?

**Comment by shaliko** [comment]
@matleppa @bajiat The API-Umbrella docker image does not have the option to fetch logs from standard docker interface. So for able see logs developer need connect to the particular running container and found logs inside it (limitation from API-umbrella side).

**Comment by kyyberi** [comment]
Create generic account in the container for developers to access logs?

**Comment by anarva** [comment]
Exploring the monitoring and deployment options provided by Kontena for containers. SSH access to the sever logs can/will be granted on demand.

**Comment by anarva** [comment]
Once the developer has been granted the required access rights, here's the way to find the docker logs (including the errors with sing up) you need to do the following:
    Check the running instances with command "docker ps".
    Check the logs of a specific instance as described here, https://docs.docker.com/engine/reference/commandline/logs/.
