### ISSUE TITLE
Logic for filtering dashboard data by user

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3081]
# User story
As an API owner I want to see filter dashboard per one API user so that I can see how frequently that user is using my API.
As an API owner I want to see filter dashboard per one API user so that I can see if this user is getting errors.

# Description
API owner should be able to view the dashboard for one single user. In other words the user is one filter for the dashboard. Implement a query to API Umbrella ElasticSearch to get data for single API for single user.

Note that later user needs also to be filtered from data stored in MongoDB (see #3072)

Since it it not acceptable to disclose API consumers' API keys to API owners, figure out logic for selecting a user for filtering.

Here is a [document](https://github.com/apinf/docs/blob/master/docs/develop/Integration/Elasticsearch-data-structure.md) on available ElasticSearch fields.

# Goal
* How to filter single API data per API consumer (= API key) from ElasticSearch
* How select a user either by username or email. API keys should not be disclosed.

Related EPIC #1999.

**Comment by bajiat** [comment]
@55 Please add a link to your document on available ElasticSearch fields

**Comment by 55** [comment]
@bajiat added to the description.

**Comment by anarva** [comment]
Q: How to filter single API data per API consumer (= API key) from ElasticSearch?
A: Use the e-mail connected to the registered developer. This is recorded on each event.
Q: How select a user either by username or email. API keys should not be disclosed.
A: Remove confidential user data when moving the data to MongoDB.

Scenario: "Move or replicate all metrics/dasboard related data to MongoDB"
 
Replicate the ApiUmbrella events to an MongoDB instance on daily basis.
Remove confidential and unimportant data when importing the data to MongoDB.
Use the registered developer e-mail to identify and select the chart data.

Create a single index on both the "developer e-mail" field and "event date" to enable fast queries.
There is a MongoDB feature which automatically combines the single field indices as long as the sort order is the same in indices as in the search.

**Comment by anarva** [comment]
The issue was created as a pre-study required by dashboard implementation. This feature is now being implemented and this can be closed.
