### ISSUE TITLE
Unreachable code after return statement

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3088]
**Steps to Reproduce**: 
1. go to page: https://apinf.io
                    
**Outcome**:

Page is blank. Nothing is shown. Webconsole says: 

<img width="1043" alt="screenshot at marraskuuta 02 08-43-10" src="https://user-images.githubusercontent.com/1927158/32313228-7a572f42-bfaa-11e7-9ded-fd8a9a4f914a.png">

This bug has been verified by clients too. 
         
**Expected Behavior**:

Open and show apinf.io frontpage. 

**Environment**:

Linux Ubuntu, Firefox (v 53.0), APInf production site (https://apinf.io)

**Comment by bajiat** [comment]
See also #3091 for IE and Edge empty page on staging.

**Comment by anarva** [comment]
Could not reproduce with Firefox v.56 or Chrome v.61 on Linux Ubuntu.

**Comment by bajiat** [comment]
Is this a duplicate of #3035 ?

**Comment by kyyberi** [comment]
This might be related to FF v 53. Sorry for misleading information in previous issue reporting.

**Comment by preriasusi** [comment]
Seems to be related only for specific version of Firefox. Closing now.
