### ISSUE TITLE
Unable to disable API-key requirement for API

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3090]
**Steps to Reproduce**: 
1. go to page: https://apinf.io/apis/apinf-catalog-rest-api-1
2. open proxy tab
3. tick "Disable API key requirement"
4. Click Save
                    
**Outcome**:

Service gives an alert: 
<img width="464" alt="screenshot at marraskuuta 02 09-28-57" src="https://user-images.githubusercontent.com/1927158/32314411-754d221c-bfb0-11e7-9823-eed258201175.png">
Nothing else is changed, just ticked disable API key requirement
         
**Expected Behavior**:

Save settings. 

**Environment**:

Mac, FF browser (56.0.2 ), APInf production site (https://apinf.io)

**Comment by bajiat** [comment]
@kyyberi This is a bug related to editing the proxy details and saving. Should be resolved in #2950 in [release 0.51.0](https://github.com/apinf/platform/releases/tag/0.51.0).

**Comment by kyyberi** [comment]
When is release 0.51.0 expected to be released?

**Comment by marla-singer** [comment]
@bajiat Yes, agree

**Comment by marla-singer** [comment]
@kyyberi Test again this issue, the problem should be fixed

**Comment by preriasusi** [comment]
Tested. No more repro on Firefox. Open again if still repro.
