### ISSUE TITLE
Feedback: successful dialog gets misplaced and displayed until next click in Firefox browser

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#3092]
# Steps  
1.Visit https://staging.apinf.io v 0.51.0  
2.Login 
3.Go to APIs catalog 
4.Select any API   
5.Click on 'Feedback' tab   
6.Fill the form   
7.Click on 'Send' button   

# Findings  
Successful dialog gets misplaced and displayed until next click.  

# Operating system    
Windows 10  

# Browser  
Mozilla Firefox v 56.0.2

**Comment by krashna-deligence** [comment]
Hi @saralavanip i have checked thisnissue on window 10 and mozile Mozilla Firefox v 57.0.1 and i have not got this above error.

**Comment by Nazarah** [comment]
@krashna-deligence 
I checked it in staging (version 0.52.0 ) in Windows 10 with Mozilla Firefox (version 57.0.2)
I could reproduce it.
The GIF is attached.
The S alert vanishes only on a next click or when the screen is scrolled down.
![ffbugfeedbacksalert](https://user-images.githubusercontent.com/17976243/33760341-f0b54c3a-dc0d-11e7-8ad8-d4d9b80ed871.gif)
