### ISSUE TITLE
Rotate logs for API-Umbrella docker image

### ISSUE THREAD

**Issue by shaliko** [apinf/platform#3094]
**Rotate logs for API-Umbrella docker image**

We found that API-umbrella docker image not rotate Nginx and other logs, so we need investigate issue.

Api-umbrella version 0.13

Points for start investigation:

- https://github.com/NREL/api-umbrella/blob/master/build/package/files/etc/logrotate.d/api-umbrella
- https://github.com/NREL/api-umbrella/issues/365#issuecomment-300347288

**Comment by bajiat** [comment]
@shaliko How urgently should this be resolved?

**Comment by shaliko** [comment]
@bajiat Chandra will increase disk space, so that will not be so priority next couple of months. But I prefer to debug and fix it during this month.

**Comment by preriasusi** [comment]
@shaliko According to Chandra, adding sic space does not help. Do we need to get logs rotating? Or is there something else?

**Comment by shaliko** [comment]
@preriasusi We need to get log rotation for APIumbrella docker image, probably we can migrate on 0.14.0 for the fix that issues. Need to be tested.
