### ISSUE TITLE
[Dashboard page] UI for charts when data is fetching,  isn't available or get error

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#3095]
## Actual result
Now the Dashboard page is like monolith and all processes depend on one request

- If Elasticsearch data is fetching then the page looks:
![2017-11-03 13-44-33](https://user-images.githubusercontent.com/20643403/32370251-6483897e-c09d-11e7-9095-773cd6b073a8.png)

- If Elasticsearch responses with errors then the page looks:
![joxi_screenshot_1509706041942](https://user-images.githubusercontent.com/20643403/32370291-8b3a3bda-c09d-11e7-93e5-448e3fbd2ddf.png)

- If no data is available for this timeframe/request path then the page looks:
![joxi_screenshot_1509706041942 1](https://user-images.githubusercontent.com/20643403/32370332-b496df24-c09d-11e7-9655-d863a0fe07f6.png)

### Goal 
1. Prepare UI when Elasticsearch data is fetching:
- How does a table row (1) look if data is fetching
- How does an overview block (2) look if data is fetching

![joxi_screenshot_1509705300182 1](https://user-images.githubusercontent.com/20643403/32369981-7dcac31c-c09c-11e7-95b0-0361a04b12cb.png)

2. Prepare UI when Elasticsearch responses with errors:
- How does the page look if one area display error message
- How does the page look if all requests return an error and all chart need to display error message

![joxi_screenshot_1509705300182 3](https://user-images.githubusercontent.com/20643403/32370094-dc5df642-c09c-11e7-8391-6c2d066b3261.png)

3. Prepare UI when no data is available for this timeframe/request path:
- How do the charts of overview block look if all chart don't have data to display it

![joxi_screenshot_1509705300182 2](https://user-images.githubusercontent.com/20643403/32370070-c7fa07ea-c09c-11e7-8527-089c4bf66330.png)

Related issue #3071

**Comment by preriasusi** [comment]
@marla-singer is this valid still or done?

**Comment by preriasusi** [comment]
@55 Could you wireframe this one?

**Comment by preriasusi** [comment]
@marla-singer is this still neede? Should @55 or @Nazarah creare a wireframe?

**Comment by marla-singer** [comment]
@preriasusi Or course it is

**Comment by 55** [comment]
@Nazarah please, go ahead.

**Comment by Nazarah** [comment]
Wireframes are available. Changes into the UI are marked with green rectangle.

**Scenario 1:** _When elastic search data and chart is being loaded the 1st time user visits the dashboard or changes time period:_
![screen shot 2018-07-18 at 10 38 59](https://user-images.githubusercontent.com/17976243/42867326-fc893c92-8a77-11e8-8439-8d6bac6ce553.png)
`Loading data `text appears on the placeholders for API Calls, Response Time and Unique users.
A `loading animation` appears beside the loading data text.

**Scenario 1.1:** _User clicks 1 row to view the charts when data/ chart is being loaded_
![screen shot 2018-07-18 at 10 39 14](https://user-images.githubusercontent.com/17976243/42867511-78324fb4-8a78-11e8-851b-21bb7427490e.png)
`Loading data` text appears on the placeholders for API Calls, Response Time, Unique users and API information under its name.
`A loading animation` appears beside the loading data text.
You may/may not show the initial plotting for the chart depending on the ease of implementation while data is being loaded.

**Comment by Nazarah** [comment]
**Scenario 2:** _When No data is available for the Row to show (e.g. no API calls were made in the selected time frame):_
![screen shot 2018-07-18 at 10 39 25](https://user-images.githubusercontent.com/17976243/42867728-1c3cd4c6-8a79-11e8-8d32-5b3ada59ce5d.png)
`No data available` text is shown in the dashboard row on the placeholders for API Calls, Response Time and Unique users.
`No data available` text also appears in the placeholders for associated charts and information under API Name.
There is no need to show initial chart plottings if no data is available to show.

**Scenario 2.2:** (If possible & implementation is easy) _one KPI has no data to display:_
![screen shot 2018-07-18 at 10 40 48](https://user-images.githubusercontent.com/17976243/42868153-43c0c010-8a7a-11e8-8980-915a48677ff7.png)
`No data available` text is shown in the dashboard row on the placeholders for that KPI
`No data available` text also appears in the placeholders for associated chart
`No data is available for this chart for the selected time-period` text also appears under the chart for that specific KPI

**Comment by Nazarah** [comment]
**Scenario 3:** _When an error occurs while fetching/loading API Data:_
![screen shot 2018-07-18 at 10 41 06](https://user-images.githubusercontent.com/17976243/42868380-dacba830-8a7a-11e8-96e4-6fab567c2e44.png)
A single text `Something went wrong. Please reload the page. If the problem remains, please call the site admin.` appears on the Dashboard row for the API.

**Scenario 3.1:** _User clicks on the API row to see the overview charts (within error condition)_
![screen shot 2018-07-18 at 10 41 28](https://user-images.githubusercontent.com/17976243/42868519-335bcaac-8a7b-11e8-8cd8-8e2df32a33f0.png)
`Something went wrong. Please reload the page. If the problem remains, please call the site admin. `text appears below the placeholders for KPI overview charts.
No need to show the initial chart plottings here.

**Scenario 3.2:** _(If possible & implementation is easy) Error occurs while loading data for a single KPI_
![screen shot 2018-07-18 at 10 41 46](https://user-images.githubusercontent.com/17976243/42868882-23e3e3ce-8a7c-11e8-908d-1f134cf690bb.png)
`Something went wrong. Please reload the page. If the problem remains, please call the site admin. ` text appears both in the placeholder of the KPI in the row and associated chart.
There is no need to show the chart in such condition.

**Comment by Nazarah** [comment]
@55 wireframes are available and ready for review.

**Comment by 55** [comment]
@Nazarah it's alright

**Comment by ilarimikkonen** [comment]
iceboxed - pending analytics overall review

**Comment by Nazarah** [comment]
closing as Dashboard in Next will be different.
