### ISSUE TITLE
API view not loading - 特殊天

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3101]
**Steps to Reproduce**: 
1. go to page: https://apinf.io
2. Scroll down to "Latest APIs"
3. click topic of mysterious "Special day" API (screenshot below)
<img width="482" alt="screenshot at marraskuuta 06 20-10-29" src="https://user-images.githubusercontent.com/1927158/32456722-4190ce7e-c32f-11e7-8137-7311606f651e.png">
                    
**Outcome**:

On click, page goes to https://apinf.io/apis (the link in API card is also to https://apinf.io/apis)

**Expected Behavior**:

- Use proper link to API profile page in API card view
- Open selected API profile detailed view. 
                   
**Environment**:

Mac, FF (56.0.2), APInf production site (https://apinf.io)

**Comment by kyyberi** [comment]
<img width="766" alt="screenshot at marraskuuta 07 09-33-45" src="https://user-images.githubusercontent.com/1927158/32482082-ce28f522-c39e-11e7-8530-7a6b7ffa5a34.png">

**Comment by kyyberi** [comment]
This might be the answer or direction where to go https://github.com/lovell/limax

**Comment by matleppa** [comment]
I guess, that because the name of API is in Chinese, the management system has not been able to form a slug based on name. The link to API from API list consists of front page address + slug. So in this case only the front page address.

**Comment by matleppa** [comment]
A work-around: In API name there must be also latin characters.

In following example there are two APIs, one with name with no latin characters and another one with name partially latin characters.

![chinese_api_name.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46eb9c932d8790acb0e8af4a9b53f1992c046b313916ac217586f76ae5002e545d5c1cf9450c5f42a8fc8b22a3b53c70dc5d0cbbd6684d68d47f40f2ecdd42e64bef62994597b7bb804dc5e93d25e18e884a371c071f9bb2.PNG)

When a slug for API is formed. the latin character part is used. In DB dump  can be seen, that a slug is formed from latin part of API name.

![Chinese_api_no_slug.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46cb9c932d8790acb0e8af4a9b53ffab3a4a32746b48e13b628ae92dbc56395b4d5a4bae420a0a40a8f98f7fa3b43575895c0bbbd06a0973c32f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e68b8f493b160d1e88fc5527ed.PNG)

**Comment by kyyberi** [comment]
Nice work around but not something we can require from clients :)
