### ISSUE TITLE
Update to Meteor version 1.6.x

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3103]
**Description**:

The current Meteor version in use is 1.5.2. Consider updating Meteor to 1.6.x.
Refer to [Announcing Meteor 1.6](https://blog.meteor.com/announcing-meteor-1-6-abf30f29e2c6) for the features, which include npm5 support and reproducible installs (due to package lock) among other things.

The 1.6 release should be backwards compatible, but update will require heavy testing.

**Comment by phanimahesh** [comment]
@preriasusi How about we try the update and run a version on a new machine for a while to test? If it works, let's switch to meteor 1.6

**Comment by preriasusi** [comment]
Dube for #3487
