### ISSUE TITLE
Allow either API key or origin header in API calls

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3107]
# Description
At the moment, APInf and API Umbrella expect that there is either a requirement for API keys or the API key requirement is disabled.  Customer requirement is to allow using calls with API keys or with origin header. This means that the proxy should allow either.
Also, the calls with origin header should be shown on the dashboard.

**Comment by ilarimikkonen** [comment]
One or the other is not a behavior that exists in apiumbrella. When multiple options are set on an API, each option creates one bucket and a request uses tokens from all buckets.
