### ISSUE TITLE
Unreadable time label in organization card (in Finnish)

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3111]
**Steps to Reproduce**: 
1. go to page: https://seinajoki.apinf.io/organizations
2. In the footer change language to Finnnish.
3. Look at APInf organization card "Lisätty"
                    
**Outcome**:

<img width="316" alt="screenshot at marraskuuta 08 19-53-34" src="https://user-images.githubusercontent.com/1927158/32565151-e6e741b0-c4be-11e7-9191-b8e87a753742.png">

         
**Expected Behavior**:

Show when it was added. "Lisäksi kaksi ..." is not informative, it's waste of space.         
           
**Environment**:

MacOS, FF (56.0.2)

**Comment by wuder4** [comment]
At least now 19 days later the message is same on both languages.
