### ISSUE TITLE
Research origin header and Graph QL support in API Umbrella

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3114]
See issues #3107, #3106, #3105, #3104 for the related needs.

# Research options
- Check and try out the API Umbrella admin UI
- See related API Umbrella issues
- Check the code

Document the findings.

**Comment by Nazarah** [comment]
@preriasusi would you please reconsider putting it into prioritized backlog?
Team has their hands filled with tasks in In progress and  Planning column.
