### ISSUE TITLE
Enable showing API analytics dashboard publicly

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3118]
**Description**:

Customer who has dedicated installation wants to show API performace / dashboard publicly to consumers. Add option per API to show dashboard to API consumers. If that is enabled, add link from API profile to dashboard. Default period to see is week. 

**User Story**:

"As an API owner, I want API consumers to see dashboard for my APIs. I must be able to control which APIs performance is shown publicly."

**Comment by kyyberi** [comment]
This has been discussed earlier and now it came from client as a requirement

**Comment by Nazarah** [comment]
From settings tab in API profile, a check can be kept to make Dashboard for the API public.
I have one question.
Would consumers be able to see the public dashboard only if they log in to the platform?

**Comment by kyyberi** [comment]
That's a good question. It's another step for consumers to do. Is there a reason for that? Of course it could be that without login you see only KPI and with login you see more.

**Comment by Nazarah** [comment]
I can assume this scenario that without logging into the platform, the consumers would be able to see the KPIs on the dashboard view when the dashboard is made public.
Upon logging in, consumers can access the detailed view of that API.
Would this suffice?

**Comment by kyyberi** [comment]
That kind of implementation would serve our platform. It lures peopleto create account. I would go forward as you suggest.

**Comment by kyyberi** [comment]
Privacy issues must be solved eg not show email of users or API keys anywhere.

**Comment by Nazarah** [comment]
closing this. Won't be implemented unless specific client request is made.
