### ISSUE TITLE
Reload charts automatically in analytics page

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3121]
**Description**:

In Dashboard, the charts should automatically update content. Period in which update occurs could be fixed and perhaps every 10-15 minutes. Add item in dashboard which shows time left until the next update moment (count down). 

**User Story**:

"As an API owner, I want to use dashboard as a page to show in screen and see statistics updated without user intervention"

**Comment by kyyberi** [comment]
If I understood correctly, in the next release dashboard chart queries are separate and thus it could be easy to add timer to reload charts again after given period of time.

**Comment by kyyberi** [comment]
Perhaps add in platform configuration (/settings) a field where platform admin can set the update period ("Dashboard automatic update period") time in minutes. If the period is set to 60, then the dashboard charts are updated automatically every 60 minutes.

**Comment by marla-singer** [comment]
@preriasusi @kyyberi The Dashboard page gets precalculated charts data directly from MongoDB now. For current day data is updated every 30 minutes. That means If an Admin set timeout less 30 minutes (10, 15 and etc) then it doesn't make sense to reload charts every 10 minutes because MongoDB doesn't contain data for this time period

**Comment by preriasusi** [comment]
Well if the MongoDB gets updated in every 30 minutes, it doens't make sense to update any more often. I think in that case the idea would be to update MongoDB also.

Does the chats get updated every time the MongoDb gets updated?

**Comment by matleppa** [comment]
@deligence-dharmendra  @preriasusi 
According to comment ( on Dec 13 2017) from @marla-singer of MongoDB update period (30 minutes), wouldn't it be feasible to implement the automatic chart update to be triggered by database update? 

So after the analytics data is updated to MongoDB (successfully), the analytic data charts are updated to show the fresh information.
