### ISSUE TITLE
Open wanted tab in API view from url

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3123]
**Description**:

Now it's impossible to direct user to wanted tab in API view. Often it would be usefull if url would open for example documentation tab instead of details tab (which is always opened). Same applies to if I want to direct users directly to feedback tab. 

Example call as one url: https://apinf.io/apis/apinf-analytics-api#api-feedback would open the API view and feedback tab. 

**User Story**:

"As an API owner, I want to be able to provide url which opend API view with wanted tab"

**Comment by Nazarah** [comment]
@kyyberi Could you please give us usecases for this enhancement?
And if this feature is implemented, do you want it to be defined while adding an API to the platform?
Also would this be also applicable for API consumers? (e.g. if selected Feedback tab, users are redirected to the feedback section of the API profile?)

I am just guessing a possible confusion that might be appear among users. On navigation to a new page, people are expected to be the in the 1st view of the page, which in case of tabbed view, the 1st tab. If some other than the 1st tab is linked as default view, this might appear conflicting to users. Just a thought.

**Comment by 55** [comment]
@kyyberi this issue will be closed by already planned removal of current way of navigation.
New navigation will include URLs to navigate within the API Page.

**Comment by kyyberi** [comment]
API owners want to share URLs to their APIs in various places. In some cases they want user to access documentation directly without writing instructions like: 
- Open page
- select "Documentation" tab.

**Comment by kyyberi** [comment]
As an example I would have liked to share direct url to documentation of Analytics API in here: https://medium.com/apinf/apinf-analytics-rest-api-design-looking-for-review-ce767339d6e9

**Comment by Nazarah** [comment]
@deligence-dharmendra sorry for knocking to this closed issue, but can you please tell from where I can select the tab that would open in default in the API profile? 
Is it configured when an API is added or this can be set from the settings tab in API profile?

**Comment by 55** [comment]
@Nazarah this functionality doesn't exist, task was to have URLs to navigate within the API Page.
