### ISSUE TITLE
Function fileNameEndsWith must be case insensitive

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#3129]
The function `fileNameEndsWith` must be case insensitive of provided file extension. 

It will cover cases when a user try to upload an image with extension JPEG but it doesn't allow because the function expects `jpeg` extension.

![tuxntqfeg4](https://user-images.githubusercontent.com/17976243/32771372-249d795a-c92b-11e7-9e9b-7a3dcfa74f5c.gif)

**Comment by deligence-dharmendra** [comment]
Hi @marla-singer 
you are working on this issue or i will work on it?

**Comment by marla-singer** [comment]
@deligence-dharmendra I completed this task. It is waiting for review
