### ISSUE TITLE
Usability issue in feedback functionality for anonymous user

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3132]
**Description**:

Right now, on browsing feedback tab in an API profile, an anonymous user (not logged into the platform) doesn't get to see any option to add Feedback for an API.
This is crucial if an API developer is requesting from her/his potential consumers for backlog requirements or feedback about the documentation on an API s/he is designing.
1st time visitors would leave without giving any feedback, unless they see a feedback button or hint for signing in/up in order to add feedback to an API.
So some action prompt is needed from the platform to encourage users add their feedback.

Another possible case could be that, user might be reluctant to provide their feedback and avoid the hassle if registration/signing in the platform is mandatory to add feedback to an API.

_**Feedback view in non-logged in session**_
![image](https://user-images.githubusercontent.com/17976243/32943502-08a98c7c-cb95-11e7-865a-a3481a10c595.png)

_**Feedback view in logged in session**_
![image](https://user-images.githubusercontent.com/17976243/32943529-1c3fbd9c-cb95-11e7-9aff-f5718c3749d8.png)

**User Story**:

"As an API owner, I need options to prompt 1st time visitors to add feedback to my API so that I can collect backlog requirements and improvement suggestions"

**Possible Solutions**
1. Show Add Feedback button also for people not signed in into the platform.
On clicking the button a dialog would appear prompting the user to sign in/up to give feedback.

2.  Providing a simple email address field and text box to provide feedback in case users don't wish to sign in or register to the platform.
Only API owner would be able to know the email address, so that s/he can further contact the person.
Providing an email address won't sign up the user in the platform.

**Comment by 55** [comment]
@Nazarah please check the latest develop (nightly.apinf.io) for the new look of feedbacks.
Update description's screenshot or close this issue if necessary.

**Comment by Nazarah** [comment]
@55 I am changing the screenshots in the issue, but the task description would remain pretty much the same. The quick fix could be to simply make the Send Feedback button even if user is not logged in to the platform. On clicking, a simple dialog would appear to sign in/sign up to the platform to provide feedback to the API.

**Comment by saransh-dev** [comment]
@Nazarah can we use same layout of feedback form after signin with extra email field (if user don't want to siginin) and above of the form, we can provide a button for signin and signup. Please advice

**Comment by Nazarah** [comment]
@saransh-dev I'd come up with it tomorrow.

**Comment by krashna-deligence** [comment]
Hi @Nazarah 
i am facing some issues while submiting feedback without login. It throws error on browser console `can't read property 'username' of undefined` because  without login we don't have "author Id"  and we are not providing edit functionality for those feedback which are posted by anonymous user. So i have 2 options to implement this:-
1- We have to make some changes in the permission.js file of feedback collection and we have to allow all the users either user is login or not for insert like below: - 
```Feedback.allow({
  insert (userId) {
    return true;
  },
  update (userId, feedback) {
    // Check if user is allowed to edit feedback
    return (feedback && feedback.currentUserCanEdit());
  },
  remove (userId, feedback) {
    // Check if user is allowed to edit feedback
    return (feedback && feedback.currentUserCanEdit());
  },
});

```

2- We can create a seprate collection where anonymous user's feedbacks store and API user can see the feedback . 
Please advice.

**Comment by Nazarah** [comment]
@saransh-dev can we simply show Add Feedback button in the feedback page in non-logged in session?
When Anonymous user clicks on the button, a pop-up appears and asks user to register or login to APInf to provide feedback. 
@55 do you propose any suggestion for this?

**Comment by 55** [comment]
@krashna-deligence @Nazarah a redirect to `/sign-in` is enough.

**Comment by krashna-deligence** [comment]
@Nazarah  Yes we can show Add Feedback button in the feedback page in non-logged . Do i need to only ask user to register or login to APInf to provide feedback or also need to show feedback form below (if user does not want to register or login ) ?
Please Advice

**Comment by Nazarah** [comment]
@krashna-deligence just ask user to register or login to provide feedback.
