### ISSUE TITLE
Lifecycle label on API profile has no right padding

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3135]
**Steps to Reproduce**: 
1. go to page: https://nightly.apinf.io
2. go to API catalog
3. Click on an API card that has a lifecycle phase associated.
4. Observe the lifecycle phase label in the API profile

                    
**Outcome**:
No right padding appears in the lifecycle phase label
![image](https://user-images.githubusercontent.com/17976243/32943811-0b383870-cb96-11e7-92f7-c1740d3c5248.png)

         
**Expected Behavior**:
Lifecycle label should have same amount of leftside padding in the right side

                   
**Environment**:

Windows 8, Chrome (most recent version), nightly.apinf.io

**Comment by deligence-dharmendra** [comment]
Hi @Nazarah,
Can you more describe about the below topic.

Fields should indicate if they are mandatory with * sign.
Alert for related field should appear if they are left empty.
Page reload should not be possible if mandatory fields are left empty.

**Comment by Nazarah** [comment]
@deligence-dharmendra my mistake.
This was part of another issue.
I am changing the description.
Thanks for noticiing.
