### ISSUE TITLE
Troubleshooting Apinf installation

### ISSUE THREAD

**Issue by mapaas** [apinf/platform#3146]
Tried installing Apinf using the Docker image (https://hub.docker.com/r/apinf/platform/) and by following the simple instructions. However when trying the docker run command the following error is displayed:
`=> Starting app on port 3000...
/opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]`

We also tried building the container locally from the Dockerfile but ran into an error with Meteor installation.

Any help for the installation process is appreciated.

**Comment by krashna-deligence** [comment]
Hi @mapaas Do i need to install docker ? if yes, which edition need to install for ubantu ?

**Comment by preriasusi** [comment]
Docker images are difficult to get running one by one. Using docker-compose will help.
