### ISSUE TITLE
eMQ dashboard implementation

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#3149]
Let's keep this as a epic. To be splitted into tasks.

**Comment by marla-singer** [comment]
@preriasusi Will you add a description for the issue?

**Comment by preriasusi** [comment]
Tomorrow to choose technologies and split into taks

**Comment by marla-singer** [comment]
Link to wireframes https://marvelapp.com/b8b1209/screen/37002765

@phanimahesh I've got questions about behaviour of MQTT rules 

ACL page
1. The previous version of ACL rules that are available in APInf platform right now it allows to set Allow/Deny options.

**Current version of ACL**
<img width="1175" alt="screenshot at jan 10 17-03-35" src="https://user-images.githubusercontent.com/20643403/34776510-41897bf2-f628-11e7-9dda-f71e1ed0529e.png">

**Future version of ACL**
<img width="921" alt="screenshot at jan 10 17-04-26" src="https://user-images.githubusercontent.com/20643403/34776539-58064022-f628-11e7-80cd-0cecb1e93fb0.png">

**Is it still needed options and they're missed or it will be gone?**

2. What fields are required? 
Based on the existing version of ACL, it supposes that one of three fields (Username, ID, IP) is filled.
**Is it still so? What fields are required?**

MQTT Dashboard
How can I fetch data for Incoming/Outgoing Bandwith chart?

**Comment by phanimahesh** [comment]
The wireframe needs a couple of updates. I'll talk to Illya and get back to you. Regarding bandwidth, I still don't have a eaasy way of extracting it, will let you know once I have it. Expect to have a url returning json, with the bandwidth values in response.

**Comment by 55** [comment]
@marla-singer we had a call with @phanimahesh, I will apply discussed changes, confirm them and then add to mockup for implementation.

**Comment by marla-singer** [comment]
@phanimahesh I found some problem with "Delivered messages" 🤔 

The table "Wildcards" has the column "Delivered messages" then supposes to display a count of delivered messages for a particular topic. But the fetched data from Elasticsearch doesn't contain any field "topic" so I can't associate that with particular topic value. The same stuff is for chart Delivered Messages on the particular Topic view.

### Fetched data
```json
"_source" : {
          "client_id" : "mosqsub|4263-frozenlake",
          "event" : "message_delivered",
          "id" : "AAViz+71xm/EsgAABWq/mg==",
          "timestamp" : 1516020090390
        }
```

### Wireframes
<img width="1233" alt="screenshot at jan 16 18-37-20" src="https://user-images.githubusercontent.com/20643403/34997046-74a42050-faec-11e7-8c06-ba2a19f0d25c.png">
<img width="1248" alt="screenshot at jan 16 18-37-53" src="https://user-images.githubusercontent.com/20643403/34997047-753a55f2-faec-11e7-8ee1-37b04609f9c4.png">

What to do? Rethink "Delivered messages" or another thing?

**Comment by phanimahesh** [comment]
Sorry about that, looks like we weren't including topics in logs. I'll include it and redeploy. It's just a one line config change.

**Comment by marla-singer** [comment]
1. Charts (1) display data for ALL topics at all or for the starred topics that are shown in the "Starred Wildcards" table below?

2. Table "Starred wildcards". Is data updated every 5 seconds when "Last 24 hour" time frame is selected?

3. When the date range picker is changed to another value then chart data is updated to the related timeframe as well or not?

![joxi_screenshot_1516701720283 3](https://user-images.githubusercontent.com/20643403/35269913-8cfcf3c8-003e-11e8-99d9-0105ecd60a2a.png)


4. Topics page. Is table data updated every 5 seconds when "Last 24 hour" time frame is selected?
![joxi_screenshot_1516701720283 2](https://user-images.githubusercontent.com/20643403/35269851-526037f2-003e-11e8-9db6-5103248d8fdb.png)

**Comment by 55** [comment]
@marla-singer 
1. Yes, for all topics, not only starred.
2. No updates needed, just a data for 24 hours, week, month.
3. Same here, no updates, only data for selected period.

**Comment by ilarimikkonen** [comment]
@marla-singer @55 on points 1-4 I agree with Illya.

**Comment by ilarimikkonen** [comment]
about real time, IF i got this right I propose 24 hrs. reasoning being that if you look at the real time stats at 00.01, then you are screwed if it's from 00.00-00.01

**Comment by marla-singer** [comment]
@55 @ilarimikkonen If "Real time" and "Outgoing Bandwith" are selected then are other values must be updated every 5 seconds as well or not?
![joxi_screenshot_1516781884524 1](https://user-images.githubusercontent.com/20643403/35321701-a75ed24e-00f8-11e8-8dff-b525982786ee.png)

**Comment by 55** [comment]
@marla-singer correct.
When you click on number (and it gets highlighted) it changes chart, other numbers still have to be updated every 5 sec.

**Comment by phanimahesh** [comment]
Bandwidth updates every 5 seconds are not currently possible. We calculate bandwidth in a very roundabout way, the actual stats we have access to are the number of packets, and estimates from the monitoring server (nagios/reimann).
