### ISSUE TITLE
[emq plugin] elastic search

### ISSUE THREAD

**Issue by ilarimikkonen** [apinf/platform#3153]

**Comment by phanimahesh** [comment]
I'm not sure how to interpret the status labels on this one. The plugin has been ready, and has been through a few rounds of testing and code review sometime ago.

What is expected to be done before this issue can be marked done and closed?

**Comment by ilarimikkonen** [comment]
well there is definition of done that I know of. I'd say we keep it in "In review" status until we hear from HSL that it's "OK"
