### ISSUE TITLE
Unable to connect API to proxy

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3159]
**Steps to Reproduce**: 
1. go to page: https://apinf.io/apis/lipas-api
2. click Proxy tab and fill in the details
<img width="1162" alt="screenshot at marrask 24 21-08-50" src="https://user-images.githubusercontent.com/1927158/33221884-b6a68534-d15b-11e7-9e4a-8caa6fa66024.png">
3. Click save & Publish

                    
**Outcome**:

Error. Does not save and publish
<img width="369" alt="screenshot at marrask 24 18-50-51" src="https://user-images.githubusercontent.com/1927158/33221910-db990c90-d15b-11e7-9409-96f72fc0da60.png">

         
**Expected Behavior**:

Save and publish API proxy settings. On top of that error message is in raw format. End-user should see the error message only. The message could also be reformatted to something that serves the end-user. Now it seems to serve the platform developer purposes. 

This might also be [PEBKAC](https://www.urbandictionary.com/define.php?term=pebkac)
                   
**Environment**:

MacOS High Sierra 10.13.1, FF v 57.0, APInf production site (https://apinf.io)

**Comment by kyyberi** [comment]
Now it works, but then found #3189

**Comment by marla-singer** [comment]
Closed this issue as resolved

Notes from chart by @shaliko 

>  Fixed issue with Apinf.io by rollback api-umbrella DB data back to their Docker image.
For easy backups I moved Apinf DB and ApiUmbrella DB to one docker container, but looks like API_umbrella 0.13.0 can't work with external DB (Mongo DB should be in the same container)
![image](https://user-images.githubusercontent.com/20643403/33598277-32624d66-d9b3-11e7-94d8-2ca4f03ee0ba.png)
