### ISSUE TITLE
Create a repo under APInf project for Swagger UI component

### ISSUE THREAD

**Issue by anarva** [apinf/platform#3167]
**Task description:**

  We need to create a repo under APInf project for Swagger UI repo. The repo must include the current changes

**Note from @anarva:** Could you please make the new repo based on your fork of the Swagger UI repo?
Here's the fix I made, just comment a line of code on the project root folder,
_make-webpack-config.js - Code block starting from line 59:_

```
if( specialOptions.minimize ) {

   plugins.push(
      new webpack.optimize.UglifyJsPlugin({
	compressor: {
	  warnings: false
	}
      })/* ,
      new webpack.optimize.DedupePlugin() // fix for issues with Internet Explorer
      */
    )
```

**Comment by marla-singer** [comment]
@anarva The first step I've done https://github.com/apinf/swagger-ui

**Comment by marla-singer** [comment]
Done https://github.com/apinf/swagger-ui/pull/1
