### ISSUE TITLE
Proxy missing from most of the API cards in production.

### ISSUE THREAD

**Issue by Laura-Sampo** [apinf/platform#3168]

**Comment by Laura-Sampo** [comment]
Pls add better instructions for connecting the API to proxy. Looks like none of them are connected to proxy.

**Comment by Nazarah** [comment]
@Laura-Sampo we are designing a new procedure for adding APIs, where default settings and proxy configurations would be added manually upon adding an API to the platform.

**Comment by preriasusi** [comment]
This is accepted way to add API in current production. Issue is the lack of APIs using proxy, and the fix is to get "great" APIs highlighled so that these APIs without proxy, and also wihtout documentation are not the ones to find first.
