### ISSUE TITLE
staging.apinf.io page gets long time to load

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3172]
**Steps to Reproduce**: 
1. go to page: https://staging.apinf.io
2. open browser console and network tab
                    
**Outcome**:

Page loads at some point but it takes more than 10 seconds to load the full view
         
**Expected Behavior**:

Page should't take more than 2 seconds to load on providing URL
                   
**Environment**:

Windows 10, Chrome browser (latest), APInf staging site (https://staging.apinf.io)

**Comment by krashna-deligence** [comment]
Hi @Nazarah this problem occurs when we use font-awesome.

**Comment by Nazarah** [comment]
@krashna-deligence can you please give some detailed reasons for the problem related to font-awesome icons?
@55 since we were considering about switching to Material design icons from font-awesome, should we think about this problem and take the decision?

**Comment by 55** [comment]
@krashna-deligence post evidence of it happening b/ of font-awesome.

**Comment by krashna-deligence** [comment]
Hi @55 currently not getting same error on APInf staging site (https://staging.apinf.io), but i am facing same issue on local and getting same message on local. 
![screenshot from 2017-12-09 09-51-05](https://user-images.githubusercontent.com/33921151/33816982-dd3c0bd8-de62-11e7-8247-cdca2bedaea4.png)
