### ISSUE TITLE
Feature request for apinf platform

### ISSUE THREAD

**Issue by eliasrebecca2017** [apinf/platform#3179]
Here are a couple of things that we received as a feedback from an external survey that we recently conducted. 

1. The developer mentioned that he was using the Mashape platform and is able to test the API in different languages (curl, java, node, PHP etc) and he can't find this in the apinf platform. https://market.mashape.com/ismaelc/yoda-speak

2. Second, regarding categorizing APIs using different categories makes it easier to explore. 
https://market.mashape.com/explore

3. Documentation is not easily accessible. 

Is it possible to include these in the next version?

**Comment by Nazarah** [comment]
@eliasrebecca2017 we are redesigning the API profile and catalog which would address most of the above limitations.
Documentation would be quicker to access and API catalog would have category features.

**Comment by preriasusi** [comment]
I think first and third items are because of the fact that well documented APIs are difficult to find.  We have release coming to help this, and this is something we will focus in near future. Categorizing is something needing new UI, and it's on design team pretty much knows the issue.

**Comment by preriasusi** [comment]
Point taken. Next versions should fix this.
