### ISSUE TITLE
Analytics for apinf.io

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#3180]
Referring #2288

> As a APInf admin I want to be see from Google analytics how APInf.io user uses APinf.io, for example what paths he/she is using.

**Comment by krashna-deligence** [comment]
Hi @preriasusi we need "tracking_ Id" for this .

**Comment by 55** [comment]
@krashna-deligence you can use your own for testing purposes.

**Comment by krashna-deligence** [comment]
Hi @55 google analytics is not accept localhost url to check analytics. 
please advice how can i test it

**Comment by 55** [comment]
@krashna-deligence try starting with https://stackoverflow.com/questions/4375447/can-you-test-google-analytics-on-a-localhost-address
