### ISSUE TITLE
multiple link fields needed under Documentation for API UI

### ISSUE THREAD

**Issue by ilarimikkonen** [apinf/platform#3187]
we need to have multiple links for documentation, this is particular need for VRK / SOAP

**Comment by ilarimikkonen** [comment]
into this view
![issue3187.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d608343220330011111451/125516c66e82c728ace21e0d46e187893687d0f8d7befd0fe64de29b234324676b5ee17e25d7b02aba167f51590b4bae485d5c44fcaf882cf0b13962964e49bc8f3900299f7744eeaa880dbe08b0218e4e87b5b58b45c3ea3f21ee99c2.PNG)

**Comment by krashna-deligence** [comment]
Hi @ilarimikkonen do i need to create multiple input tag for link in same modal and store value in `remoteFileUrl` as array in db 
Please advice

**Comment by ilarimikkonen** [comment]
yes. The idea is that there is initially one link input field. and then there is a + button to add additional fields if more than one link is needed. also deletion of links should be possible somehow from UI (- button). This needs to be usable both when user wants to add additional links via UI and also via catalog API. Please limit max number of links to 8.
