### ISSUE TITLE
Proposal: Transition frontend to react

### ISSUE THREAD

**Issue by phanimahesh** [apinf/platform#3200]
### Background
Meteor is a great tool to kickstart projects, but it is highly opinionated, monolithic, and does not play well with the API ecosystem. Moreover, the build times of meteor projects in general, and apinf/platform in particular, are outrageously high.

I believe our UI and UX need a major overhaul, but that is a very ambitious and long term goal. More immediately, we need to be able to iterate faster. Over past conversations with our developers, it appears I am not alone in the opinion that meteor is slow, both to develop with and to run. Meteor no longer feels like the best tool for our job.

We have a lot of resources - time, code, and expertise - invested in meteor, and we can not walk away from it easily. Any transition should consider this and allow for partial, incremental updates that both provide incremental benefits, and should not introduce regressions.

This is a large problem. A small step would be to reduce our dependence on meteor. It is easier to do in the frontend than in the backend. Once we have a fully transitioned frontend, we can begin transitioning the backend away from meteor into a server exposing HTTP REST apis.

Meteor officially supports React instead of Blaze to describe frontend. Angular is also officially supported, but with all due respect to angular community, that is a can of worms best left unopened.

By transitioning our frontend to react, we will have faster compile times, access to all of react ecosystem, and overall a more functional approach in our code that allows better testing and refactoring. Previously there were concerns over react licensing, which are now resolved.

I believe the time is ripe for us to consider transitioning frontend to react.

### Plan:
```
meteor yarn add react react-dom react-template-helper react-mounter
meteor add gadicc:blaze-react-component react-meteor-data
```
- Any new pages/views/components being added to platform should be written in react.
- As much as possible, react components should be stateless and pure.
- Any new react components should be accompanied by tests.
- A top level blaze wrapper can be used to pass data to react components where necessary.

I will be available to assist in getting the team kickstarted and resolving any hiccups. Thoughts?

Reference: https://guide.meteor.com/react.html

**Comment by marla-singer** [comment]
@phanimahesh I believe the Angular would be better solution than React

**Comment by phanimahesh** [comment]
@marla-singer can you provide a few reasons why angular would be better?

I have had my hands burned very badly with angular on multiple previous occasions. Which version of angular? 1, 2 or 4? 4 is undoubtedly better than 2 which in turn is better than 1. However, the community is in a lot of flux, and most available resources are still stuck with 1, or migrating to 2. I have a strong personal preference against angular as much as I have a preference in favor of react, and recent developments in angular appear to be very much inspired by react and friends.

**Comment by marla-singer** [comment]
@phanimahesh I don't know how works react + meteor but in the general life react + nodejs The most for me that 

For example, what would we use to transit data between components and client-server side? Where is a lot of 

Also Angular + Typescript

**Comment by anarva** [comment]
Improving the test coverage with the new approach is a good point. We have reached the level of complexity in the project that really requires it. It will eventually improve the quality and speed of the development.

**Comment by preriasusi** [comment]
OK. I think this issue does not help in ice box. I close it now.
