### ISSUE TITLE
For new user to register, platform doesn't check validity of email address domain

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3202]
Mandatory fields are not identifiable

**Steps to Reproduce**: 
1. go to page: https://nightly.apinf.io
2. register a new user with invalid email domain and address (e.g. test@invalid.dom)
3. Click register
                    
**Outcome**:
Despite an invalid domain in the email address, the registration appears successful.
Notification about sent email appears prompting user to verify email address

**Expected Behavior**:
Platform should verify if entered email address is of valid domain.
If not, registration should not be successful.
User should be alerted about the invalidity of the given email domain and should be prompted to enter an email address with certified domain.
![image](https://user-images.githubusercontent.com/17976243/33819561-0e9ab14a-de43-11e7-9a93-f4e152b98331.png)

                   
**Environment**:

Windows 10, Chrome browser (latest), APInf nightly (https://nightly.apinf.io)

**Comment by preriasusi** [comment]
Checking is difficulta, and even may be prevented.  As a minor issue to be closed now.
