### ISSUE TITLE
GitHub Authorization window appears out of view in browser tab

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3204]
**Steps to Reproduce**: 
1. go to page: https://nightlyapinf.io
2. Click on Sign Up
3. Click on Sign Up with GitHub account
                    
**Outcome**:
Controllers (minimize, maximize, close) of GitHub authorization window doesn't appear in the browser tab.
The window can't be moved downwards either
It need to be closed by clicking the browser icon on desktop.
![githubauthorizationwindow](https://user-images.githubusercontent.com/17976243/33820755-8d093360-de59-11e7-9fc2-c4942ab0903c.gif)

         
**Expected Behavior**:
The controllers for manipulating the GitHub authorization window should appear in front of the user view
                   
**Environment**:

Windows 10, Chrome browser (latest), Nightly APInf

**Comment by 55** [comment]
macOS 10.13.1 Chrome 63 and Firefox 57 Github authorization window appears as expected.

**Comment by Nazarah** [comment]
Verified in Chrome latest version in Windows 10. The window needs to be shrinked manually for the controllers to appear. 
They should appear perfectly on their own without the requiring the user to manually adjust the window size

**Comment by 55** [comment]
Double-checked, works just fine:
- Windows 7 Chrome 62
- Windows 10 Chrome 62
