### ISSUE TITLE
Fiware Authorization window doesn't appear completely on browser view

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3206]
**Steps to Reproduce**: 
1. go to page: https://nightly.apinf.io
2. click Sign UP
3. Click "Sign in with Fiware"             
       
**Outcome**:
Fiware authorization window doesn't appear with its controllers (maximize, minimize or close).
All fields doesn't appear completely on the view
![fiwareauthorizationwindow](https://user-images.githubusercontent.com/17976243/33822156-3b8923aa-de5f-11e7-865d-1d07d42702a3.gif)

         
**Expected Behavior**:
Fiware authorization window should appear completely with all its controllers and the associated fields should appear completely on the browser view
                   
**Environment**:

Windows 10, Chrome browser (latest), Nightly APInf

**Comment by 55** [comment]
macOS 10.13.1 Chrome 63 and Firefox 57 Fiware authorization window appears as expected.

**Comment by Nazarah** [comment]
Verified in Chrome latest version in Windows 10. The window needs to be shrinked manually for the controllers to appear. 
They should appear perfectly on their own without the requiring the user to manually adjust the window size

**Comment by 55** [comment]
Double-checked, works just fine:
- Windows 7 Chrome 62
- Windows 10 Chrome 62
