### ISSUE TITLE
Login attempt with Fiware throws Internal Server error

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3209]
**Steps to Reproduce**: 

(required: Fiware login to be active in the environment)

1. go to page: https://staging.apinf.io
2. click Sign Up
3. Click register with Fiware.
4. Create a fiware account with required information (username, email address, password)
[you can use randomly generalized emails using http://www.throwawaymail.com/en]
5. Confirm email address in the sent email by clicking the link
6. go to page: https://staging.apinf.io and click sign in
7. click sign in with fiware
8. provide the used credentials on the fiware window and click sign in
9. click Authorize button

**Outcome**:
User can't sign in using created fiware account.
Page shows Internal Server Error
![fiwaresigninerror](https://user-images.githubusercontent.com/17976243/33826650-5969e65c-de6e-11e7-9166-032072df7a18.gif)

         
**Expected Behavior**:
Users should be able to sign in to APInf platform with valid credentials used for Fiware account.
                   
**Environment**:
Windows 10, Chrome browser (latest), IE11, APInf Staging (https://staging.apinf.io)
Fiware information in staging environment:
![image](https://user-images.githubusercontent.com/17976243/33825694-20deab5e-de6b-11e7-8db4-7c4d6961366a.png)

**Cases verified**
1. Creating a fiware account with completely new email address (never used in APInf) + attempting to sign in
2. Creating a fiware account with previously used email address (in APInf) + attempting to sign in

**Comment by Nazarah** [comment]
Verified in nightly.apinf.io with completely new email address used to register fiware account.

**Comment by fdelavega** [comment]
I have been able to debug this error.

It seems that meteor is expecting a username field to be provided, but this field is not being provided as part of the account data generated by apinf-fiware package.

So in AccountsServer.Ap._attemptLogin (packages/accounts-base/accounts_server.js) the field result.error contains something like "Missing Username field", which is then included in attempt.error which (not sure why) generates a  circular JSON error.

Anyway, I have included the username field within the serviceData provided by the package and that seems to solve the problem.

This have been provided in apinf-fiware repo in PR [23](https://github.com/apinf/apinf-fiware/pull/23), although I have not yet included the tests

**Comment by preriasusi** [comment]
https://github.com/apinf/apinf-fiware/pull/23 closes this.

**Comment by Nazarah** [comment]
reopening this issue as it has emerged in release 0.55.0 in https://staging.apinf.io

http://recordit.co/3e2bhFccY1

CC. @preriasusi

**Comment by preriasusi** [comment]
Works now fine on nightly and saas. Closing again

**Comment by madhu2910** [comment]
I am facing the same issue. The installation of APInf is done using docker-compose. I am using **apinf/api-umbrella:0.15.0-apinf2** docker image for API-Umbrella and **apinf/platform:0.58.0** docker image for APInf.
