### ISSUE TITLE
Confirm new password field remains highlighted with alert text even after successful update of password

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3211]
**Steps to Reproduce**: 
1. login to https://nightly.apinf.io
2. go to user>account
3. change password by giving current, new and confirmed new password.
4. click change password button (wait to see the successful update s-alert)
                    
**Outcome**:
Even after successful update, the confirm new password field remains highlighted with alert text
![image](https://user-images.githubusercontent.com/17976243/33828868-7fc956f4-de76-11e7-8bcd-e4e47cdb5d65.png)
         
**Expected Behavior**:
on successful update, all fields should get refreshed.
Fields should not remained highlighted and no alert text should appear.
                   
**Environment**:
Windows 10, Chrome browser (latest), APInf nightly.

**Comment by Nazarah** [comment]
The issue was identified while testing release 0.52 in staging and ´was verified in nightly.

**Comment by preriasusi** [comment]
@deligence-dharmendra could you confirm this with Windows. On my Ubuntu with Firefox I can't repro this.

**Comment by deligence-dharmendra** [comment]
@vesa, I will try to reproduce.

**Comment by deligence-dharmendra** [comment]
Hi @vesa, I have tested this functionality on windows as well as Linux environment. On Windows environment functionality working fine. But in Linux environment, I have seen the same issue. Please see the attached screenshot.
Linux test environment details below.
```
Ubuntu 14.04.5 LTS,
Mozilla Firefox 57.0.1,
Google Chrome 60.0.3112.78
```
![screenshot from 2018-01-10 11 02 01](https://user-images.githubusercontent.com/32898978/34757419-09a2898a-f5f7-11e7-883c-3eaa4323d8bb.png)
![screenshot from 2018-01-10 11 03 24](https://user-images.githubusercontent.com/32898978/34757458-4b7a6ee0-f5f7-11e7-8a1c-aaecaab15922.png)

**Comment by deligence-dharmendra** [comment]
Hi @marla-singer,
I have gone through the code and test the functionality. I have found that due to a single line of code "validation="keyup"" in updatePassword template this issue comes sometimes. Can I remove keyup validation? OR do you have any other approach?
```
<template name="updatePassword">
  {{# autoForm
    schema=updatePasswordSchema
    id="updatePassword"
    validation="keyup" }}
```
Please advise.

**Comment by marla-singer** [comment]
> Can I remove keyup validation? 

Yes, let's start with this change. Make sure that other validations work correct
