### ISSUE TITLE
Social media icons and link don't appear when field values are modified and updated in Branding page

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3213]
**Steps to Reproduce**: 
1. go to page: https://staging.apinf.io and login as admin
2. go to user>branding
3. Make sure all possible social media icons and links are present (Facebook, twitter and GitHub) or add them.
4. on the Social media section, deselect the Name field from the first social  media controller and click Update
5. (check the UI for social media icon in footer).
6. Now minimize the controller (the 1st controller Name field was deselected) and click Update
7. (check the UI for social media icon in footer).
8. Repeat step 6 again.
                    
**Outcome**:
On deselecting name field, the icon for that social media on footer gets broken in the UI.
On minimizing the controller, other social media icons starts to disappear or be broken.
On continuous minimization attempts, all social media icons get disappeared despite Branding page have those configured.
The icons reappear when the browser page is manually reloaded.
![socialmediabranding](https://user-images.githubusercontent.com/17976243/33831737-f0266d6e-de81-11e7-85a2-ed64bae7b437.gif)

         
**Expected Behavior**:
If social media and their links are configured in branding page, they should appear properly in the footer, despite the above mentioned action has taken place in the associated UI.
                   
**Environment**:
Windows 10, Chrome browser (latest), APInf staging site (https://staging.apinf.io)

**Comment by Nazarah** [comment]
The issue was identified in release 0.52 in staging and was verified in nightly apinf.

**Comment by marla-singer** [comment]
@Nazarah I think it would better to change UI for social media block and have the same UI as we have for Organization Social Media links. What do you think?
![joxi_screenshot_1513083256566](https://user-images.githubusercontent.com/20643403/33885567-c744e302-df54-11e7-9188-e7a382df5ec9.png)

**Comment by Nazarah** [comment]
@marla-singer go for it.
