### ISSUE TITLE
Travis build fails on PRs

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3215]
When Travis CI build is triggered by PR, it fails.

[chimp] Running...

  00 login
    1) "before all" hook

  0 passing (9s)
  1 failing

  1) 00 login "before all" hook:
     Uncaught unknown error: cannot determine loading status
from unknown error: missing or invalid 'entry.level'
  Error: unknown error: cannot determine loading status
      at SignInPage.open (tests/page-objects/page.js:18:13)
      at SignInPage.open (tests/page-objects/signin.page.js:34:5)
      at Context.<anonymous> (tests/end-to-end/ui/00-login.js:15:16)
      at node_modules/chimp/dist/lib/utils/fiberize.js:29:22
      from unknown error: missing or invalid 'entry.level'

Mocha failed
error Command failed with exit code 2.
Chimp exited with code 1
error Command failed with exit code 1.

The command "yarn test" failed. Retrying, 2 of 3.

yarn test v0.27.5
$ node .scripts/run-chimp.js
Warning: The --production flag should only be used to simulate production
bundling for testing purposes. Use meteor build to create a bundle for
production deployment. See: https://guide.meteor.com/deployment.html
Can't listen on port 3000. Perhaps another Meteor is running?

Running two copies of Meteor in the same application directory
will not work. If something else is using port 3000, you can
specify an alternative port with --port <port>.
Meteor App exited with code 254
error Command failed with exit code 254.

The command "yarn test" failed. Retrying, 3 of 3.

yarn test v0.27.5
$ node .scripts/run-chimp.js
Warning: The --production flag should only be used to simulate production
bundling for testing purposes. Use meteor build to create a bundle for
production deployment. See: https://guide.meteor.com/deployment.html
Can't listen on port 3000. Perhaps another Meteor is running?

Running two copies of Meteor in the same application directory
will not work. If something else is using port 3000, you can
specify an alternative port with --port <port>.
Meteor App exited with code 254
error Command failed with exit code 254.

The command "yarn test" failed 3 times.

The command "travis_retry yarn test" exited with 1.
0.01s
$ ./.scripts/docker_build.sh

if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_REPO_SLUG}" = "apinf/platform" ]
then
  docker build -t apinf/platform:$DOCKER_TAG .
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  docker push apinf/platform:$DOCKER_TAG
fi

The command "./.scripts/docker_build.sh" exited with 0.
before_cache
0.01s
$ rm -f $HOME/.meteor/log/*.log

cache.2
store build cache
0.01s
87.76s
change detected (content changed, file is created, or file is deleted):
/home/travis/.meteor/package-metadata/v2.0.1/packages.data.db-shm

changes detected, packing new archive
.
.
.
.
.
.
.
.
.
.
.
.
uploading archive

Done. Your build exited with 1.

**Comment by matleppa** [comment]
It seems, that the problem has begane to appear at least after 2017-12-07.

**Comment by matleppa** [comment]
Problem can be reproduced also locally.

 9.45.20,00_C:\Users\matleppa\api\apinf\platform>yarn run chimp-test
yarn run v1.3.2
$ chimp tests/chimp-config.js

[chimp] Running...



DevTools listening on ws://127.0.0.1:12205/devtools/browser/3a6304e3-cc8a-4acc-9a30-0ff59786f241
  00 login
[128472:128836:1212/094648.504:ERROR:shader_disk_cache.cc(238)] Failed to create shader cache entry: -2
    render
      1) should show email / username field


  0 passing (39s)
  1 failing

  1) 00 login render should show email / username field:
     Uncaught AssertionError: expected false to be true
      at doAsserterAsyncAndAddThen (node_modules\chai-as-promised\lib\chai-as-promised.js:293:29)
      at .<anonymous> (node_modules\chai-as-promised\lib\chai-as-promised.js:283:21)
      at get (node_modules\chai\lib\chai\utils\overwriteProperty.js:50:37)
      at Context.<anonymous> (C:/Users/matleppa/api/apinf/platform/tests/end-to-end/ui/00-login.js:20:7)
      at node_modules\chimp\dist\lib\utils\fiberize.js:29:22



Mocha failed
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by matleppa** [comment]
Switched on release 0.50.0. 
However, same result is still gotten, when the tests are driven locally.

**Comment by matleppa** [comment]
Failure also with release 0.49.0

 9.46.59,33_C:\Users\matleppa\api\apinf\platform>yarn run chimp-test
yarn run v1.3.2
$ chimp tests/chimp-config.js

[chimp] Running...



DevTools listening on ws://127.0.0.1:12091/devtools/browser/a87e5fe6-a7cc-4fb2-ae31-1f93240107b6
  00 login
[137932:135964:1212/113212.759:ERROR:shader_disk_cache.cc(238)] Failed to create shader cache entry: -2
    render
      √ should show email / username field (205ms)
      √ should show password field (68ms)
      √ should show github button (58ms)
      √ should show submit button (102ms)
      √ should show register link (155ms)
      √ should show forgot password link (129ms)
      √ should show forgot resend verification email link (56ms)
      √ should not show error alert (59ms)
    required fields
      email / username and password
        √ should be required (141ms)

  01 sign up
    render
      1) should show username field


  9 passing (45s)
  1 failing

  1) 01 sign up render should show username field:
     Uncaught AssertionError: expected false to be true
      at doAsserterAsyncAndAddThen (node_modules\chai-as-promised\lib\chai-as-promised.js:293:29)
      at .<anonymous> (node_modules\chai-as-promised\lib\chai-as-promised.js:283:21)
      at get (node_modules\chai\lib\chai\utils\overwriteProperty.js:50:37)
      at Context.<anonymous> (C:/Users/matleppa/api/apinf/platform/tests/end-to-end/ui/01-sign-up.js:20:7)
      at node_modules\chimp\dist\lib\utils\fiberize.js:29:22



Mocha failed
error Command failed with exit code 2.

**Comment by matleppa** [comment]
Locally the build succeeds sometimes, when tester has opened a browser window and web tools window is opened. 
However, does not succeed every time.

11.17.20,21_C:\Users\matleppa\api\apinf\platform\tests>yarn run chimp-test
yarn run v1.3.2
$ chimp tests/chimp-config.js

[chimp] Running...



DevTools listening on ws://127.0.0.1:12026/devtools/browser/70a306b6-ed80-493b-a896-6b4fd0bf929c
  00 login
    render
      √ should show email / username field (672ms)
      √ should show password field (175ms)
      √ should show github button (70ms)
      √ should show fiware button (101ms)
      √ should show submit button (212ms)
      √ should show register link (189ms)
      √ should show forgot password link (121ms)
      √ should show forgot resend verification email link (100ms)
      √ should not show error alert (111ms)
    required fields
      email / username and password
        √ should be required (130ms)

  01 sign up
    render
      √ should show username field (193ms)
      √ should not show username error field (133ms)
      √ should show email field (138ms)
      √ should not show email error field (96ms)
      √ should show password field (89ms)
      √ should not show password error field (68ms)
      √ should show confirm password field (162ms)
      √ should not show confirmPassword error field (215ms)
      √ should show github button (88ms)
      √ should show fiware button (108ms)
      √ should show register button (112ms)
    username
      √ should be required (536ms)
    email
      √ should be required (398ms)
      √ should be invalid for email without domain (1380ms)
      √ should be invalid for email with invalid domain (1050ms)
      - should be invalid for email space
    password
      √ should be required (459ms)
    confirm-password
      √ should be required (451ms)
      √ should be invalid if different from password (818ms)

  02 forgot password
[245868:246684:1213/112319.662:ERROR:shader_disk_cache.cc(238)] Failed to create shader cache entry: -2
    render
      √ should show email field (111ms)
      √ should not show email error field (231ms)
      √ should show submit button (214ms)
    email
      √ should be required (500ms)
      √ should be invalid for email without domain (1181ms)
      √ should be invalid for email with invalid domain (1456ms)
      - should be invalid for email space


  34 passing (1m)
  2 pending

Done in 91.31s.

**Comment by matleppa** [comment]
Versions in use
11.23.25,02_C:\Users\matleppa\api\apinf\platform\tests>yarn run chimp-test
yarn run v1.3.2
$ chimp tests/chimp-config.js
Chimp version:  0.48.0
ChromeDriver version:  ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f)
Java version:  No such file or directory
Selenium version:  3.0.1
Selenium drivers version:  chrome: 2.25, ie: 2.50.0, firefox: 0.11.1
OS version:  Windows_NT 10.0.16299
Node version:  v6.10.3

**Comment by matleppa** [comment]
A similar issue can be found:
https://github.com/xolvio/chimp/issues/516
However, there the Chromedriver version is 2.24, when we have version 2.33.506120

**Comment by matleppa** [comment]
Logs can be set on with following change in following file

tests\chimp-config.js

  // - - - - DEBUGGING  - - - -
  // Uncomment 2 lines below to print everything
  log: 'info',
  debug: true,
};

**Comment by matleppa** [comment]
0 passing (31s)
  1 failing

  1) 00 login render should show email / username field:
     Uncaught AssertionError: expected false to be true
      at doAsserterAsyncAndAddThen (node_modules\chai-as-promised\lib\chai-as-promised.js:293:29)
      at .<anonymous> (node_modules\chai-as-promised\lib\chai-as-promised.js:283:21)
      at get (node_modules\chai\lib\chai\utils\overwriteProperty.js:50:37)
      at Context.<anonymous> (C:/Users/matleppa/api/apinf/platform/tests/end-to-end/ui/00-login.js:20:7)
      at node_modules\chimp\dist\lib\utils\fiberize.js:29:22



Mocha failed
error Command failed with exit code 2.

And corresponding screen capture:

![0_00_login_render_should_show_email___username_field_(failed).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46b8abca73bd8fa688e0b17cb658fe902c541860210bb62774baf020b0554404020e17f02e373001bfaccb75f7eb691fdc055eb18502472297644df9ec9b0da313fa62d415d0e5f89846d2ed3827e4d9da4b6a1e034c8cfd5430a3994b9e59f11de64847b8017432b82269211ede4b373e617527a3f6de53868662a1bc162657cbe3e4e85b.png)

**Comment by matleppa** [comment]
Browser version:  chrome 63.0.3239.84

Did not help.

**Comment by anarva** [comment]
This recently posted question points to similar issues. On our test setup the latest stable version of  Chrome driver is always downloaded, so there could be some freshly introduced version conflict between Chimp and Chrome driver. Both versions should be defined explicitly to avoid such situations.  --> Trying to find suitable versions and configure the settings accordingly.

https://stackoverflow.com/questions/47727311/chimp-test-stopped-working-throwing-error-missing-or-invalid-entry-level

**Comment by kyleian** [comment]
@matleppa From my chimp error you tagged [here's the issue on the chromedriver end](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1547); don't see anything in their current issues list that looks the same at first glance. I recall seeing this with 2.29 as well occasionally; Chimp master looks like it's on 2.28 currently which is definitely out of date.

Any luck with bumping your chromedriver up to 2.34 locally to get around this?

**Comment by anarva** [comment]
Related configuration files: 
.travis.yml
tests/chimp-config.js

A possibly linked Travis update of Ubuntu based image as described here: https://github.com/travis-ci/travis-ci/issues/8870
Note that the tests are configured to run on a container (sudo: false) -  "container:true (etc.)" cannot be used as a workaround.
