### ISSUE TITLE
adding API with swagger file fails to load the swagger file into documents

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#3216]
# Steps  
1.Visit https://staging.apinf.io  v 0.52.0
2.Login and create API using url to swagger (e.g. https://nightly.apinf.io/gridfs/DocumentationFiles/id/408c6a718ba093e259682db7)
3.Check documentation tab

# Screenshot

![addby_swagger](https://user-images.githubusercontent.com/28555452/33873759-eea7dcc2-df24-11e7-9e72-060116cd14b9.png)

# Findings 
* Documentation fails to load
* Other settings are not copied over
* URL was not identical
* API swagger file description has 1000 character limit and that is really low

Tested on:
Windows 8
Google Chrome latest
staging  v 0.52.0

**Comment by marla-singer** [comment]
> Documentation fails to load

Swagger can't read file from nightly but if you provide a link to **available** specification then it would work as expected

> URL was not identical

What URL do you expect and **where**? API URL field is filled
![joxi_screenshot_1513075873807](https://user-images.githubusercontent.com/20643403/33880715-97457c86-df43-11e7-8e93-5d6475f3aff1.png)


> Other settings are not copied over

What kind of settings do you expect?

> API swagger file description has 1000 character limit and that is really low

APInf has this settings as limit in 1000 character for description

**Comment by wuder4** [comment]
I copied this swagger from nightly and there this API had https://shareitbloxcar.fi/api/vehicles/1 as URL

Other settings I realize you cant get from swagger so there is nothing else I can think of.

Almost all of the APIs in nightly that have swagger have over 1000 char description so they wont work here.

**Comment by marla-singer** [comment]
API profile gets data from Swagger file directly and the file contains the next data:

```yml
host: shareitbloxcar.fi
basePath: /api
schemes:
 - https
```
So API URL is correctly

> Almost all of the APIs in nightly that have swagger have over 1000 char description so they wont work here.

This is Usability issue of API schema at all and doesn't relate to feature of adding API with swagger file.

**Comment by marla-singer** [comment]
Closed it as outdated
