### ISSUE TITLE
Documentation tab doesn't load when API profile has swagger documentation 

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3217]
**Steps to Reproduce**: 
1. Login : https://staging.apinf.io
2. Go to AP Catalog
3. Click APInf Catalog REST API
4. Go to Documentation tab
                    
**Outcome**:

The view keeps on loading.
The swagger document never appears on the UI.
The following exception is caught in browser console
![33871698-3f094a06-df1c-11e7-9784-04efe6178e5c](https://user-images.githubusercontent.com/17976243/33875492-1327e302-df2b-11e7-9b95-d4bf779eb1e8.png)

![documentationtabload](https://user-images.githubusercontent.com/17976243/33875459-fceab7cc-df2a-11e7-8fa2-0e7d7f327357.gif)

Checked and verified with other REST API documentation by APInf and other APIs that have swagger documentation.

         
**Expected Behavior**:

Swagger documentation should load normally in the View section under documentation tab in API profile
                   
**Environment**:

Windows 10, Chrome browser (latest), APInf staging site (https://staging.apinf.io) - version 0.52

**Comment by Nazarah** [comment]
Comments from @saransh-dev 
>Yes, we need to check result also in onCreated at line number 33 inside apinf_packages/api_docs/swagger_ui/swagger_ui.js
Currently we have like if (result.schemes && result.schemes[0] === 'http') { and we need to make it like if (result && result.schemes && result.schemes[0] === 'http') {

**Comment by marla-singer** [comment]
**Investigate report**
In the time of investigation APIs catalog has 9 APIs with documentation
<img width="1266" alt="screenshot at dec 12 12-09-07" src="https://user-images.githubusercontent.com/20643403/33877989-3266d16e-df3b-11e7-9fd7-8e7d780650df.png">

**APIs have a link to incorrect specification**
[Geocode API](https://staging.apinf.io/apis/geocode-api)
[GitHub Issue](https://staging.apinf.io/apis/github-issue)
[haHAA](https://staging.apinf.io/apis/hahaa)
[Shareit Bloxcar public API (beta)](https://staging.apinf.io/apis/shareit-bloxcar-public-api-beta)
[Wikimedia REST API](https://staging.apinf.io/apis/wikimedia-rest-api)

Swagger parser returns the error and this error isn't caught

**Expected**
Display to user an error message

**APIs with correct swagger specification**
It throws error as
```
"Error downloading file "https://staging.apinf.io/rest/v1/catalog.json" 
connect ECONNREFUSED 172.18.0.2:443"
```

```
"Error downloading file "https://staging.apinf.io/gridfs/DocumentationFiles/id/909af5e4dcfcdf0914474a5f" 
connect ECONNREFUSED 172.18.0.2:443"
```

Regardless, the URLs are available via browser.
The follow-up issue to resolved this problem

**Comment by marla-singer** [comment]
@krashna-deligence The updated of this issue:
If the function returns error then display to user an error message

**Comment by Nazarah** [comment]
Found some similar results in the nightly.
For some apis, the documentation tab is loading. (eg. APInf Catalog REST API)
for some, e.g. aa ml api management, the documentation tab isn't loading. n the console gives the related error.

**Comment by preriasusi** [comment]
This happens on staging with 0.52.0. vamos.apinf.io is running 0.52.0, and swagger documenation does work.

Devops? @55 @ccsr ?

**Comment by marla-singer** [comment]
@Nazarah Please test it again

**Comment by Nazarah** [comment]
@marla-singer tested it in both staging.apinf.io and vamos.apinf.io. wuth 0.52 release
In aping staging, the problem still exists with the below exception
![image](https://user-images.githubusercontent.com/17976243/34032753-26518a62-e180-11e7-8829-6d73c0f49360.png)

In vamos, the documentation tab can load the swagger UI and the documentation can be viewed.

Test was done in Windows 10, Chrome
