### ISSUE TITLE
Several documentation links adding possibility catalog api

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#3220]
### Description
PR 3201 changes functionality and structure of Apidocs such a way, that it is possible to provide several external documentation links for one API.

### Changes needed in Catalog API
After the PR 3201 is implemented, the structure of ApiDocs is changed. A change is needed to Catalog API in order to write external documentation links correctly.

New endpoints are needed to handle adding and removing external documentation links
- external links can be added and removed one by one
- when a link is added, 
  - it is checked, that a duplicate link does not already exist
  - maximum limit of existing links is 8
- only an existing link can be removed

Also functionality of documentationUrl is moved to these new endpoints.

That way there is no need to handle different DBs in one endpoint, which increases integrity.

**Comment by matleppa** [comment]
After the PR 3201 is implemented, similar functionality (ability to provide several documentation links needs to be implemented to Catalog API also.

The structure of Apidocs is changed, so a correction is needed in Catalog API functionality in any case.

**Comment by matleppa** [comment]
### Changes needed
- Adding new external documentation link for API
  - a new endpoint is needed
  - POST /apis/{id}/externalDocumentation/<link-to-documentation>

- Removing an external documentation link for API
  - a new endpoint is needed
  - DELETE /apis/{id}/externalDocumentation/<link-to-documentation>

- Adding an API (POST /apis)
  - remove parameter externalDocumentation

- Updating an API (PUT /apis)
  - remove parameter externalDocumentation

### No changes needed

- GET /apis
- operation responses using same structure as GET
