### ISSUE TITLE
Error in summary titles in Latest APIs page in Suomi view

### ISSUE THREAD

**Issue by apicnic** [apinf/platform#3235]
** Follow the example given to submit a bug report **

**Title**: 

Error in summary titles in Latest APIs page of apinf.io in Suomi view

**Steps to Reproduce**: 
1. go to page: https://apinf.io
2. go to bottom of the page.
3. Change the languate to "Suomi".
4. Look the titles.
                    
**Outcome**:
<img width="1284" alt="screen shot 2017-12-13 at 3 01 43 pm" src="https://user-images.githubusercontent.com/29686179/33940571-273fc204-e018-11e7-9d6a-0fa89e084050.png">
         
**Expected Behavior**:

Titles should be translation from English including the same notation without ":".

English:
178 APIs
15 Organizations
216 Users

Suomi:
178 APIa
15 Organisaatiota
216 Käyttäjää
                   
**Environment**:

MacOS Sierra, Chrome browser (latest), APInf production site (https://apinf.io)

**Comment by marla-singer** [comment]
Closed it as already resolved on the production site v0.52
![screenshot at feb 01 17-49-19](https://user-images.githubusercontent.com/20643403/35684567-5cad96d2-0778-11e8-8e92-4e57c0059cd5.png)
