### ISSUE TITLE
Provide appropriate error message on attempt to provide link of invalid openAPI specification file.

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3237]
**Description**:

When attempt is made to provide link of an API documentation file having different extension than json, yaml, or yml, the s-alert shows error message [[Object object]].
This is not intuitive enough and doesn't tell users the reason for failed add operation (different file extension).

So if attempt is made to add link for an invalid file type, on clicking import, s-alert should alert the user about the incorrect form type and prompt the user to use json, yaml or yml file.

**User Story**:
"As an API owner, I wish to see intuitive error message, so that I can be aware of the incorrect file type that I attempted to provide for adding an API."

**Solution**
Have the following error message in s-alert: "Invalid file type. Please provide link of a json, yaml or yml file containing atleast API name and Endpoint URL."

**Comment by marla-singer** [comment]
@Nazarah Add details about environment and version of application

**Comment by Nazarah** [comment]
@marla-singer I tested and found this behavior in Vamos site, where release 0.52 had been deployed.
https://vamos.apinf.io
However, this can also be obtained from nightly. 
That is why it is reported as an enhancement issue.
