### ISSUE TITLE
Setting access control rules for EMQ proxy in an API shows internal server error 500

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3240]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login
2. Go to an API profile.
3. Go to Proxy tab
4. select EMQ proxy and create an access control rule.
5. Click Save and publish.
                    
**Outcome**:
Same s alert appears twice with message: iinternal server error 500
It is not understandable if configuration had been saved
![emqproxyerror](https://user-images.githubusercontent.com/17976243/33993659-244658ce-e0e0-11e7-88a5-18815d1fc232.gif)
         
**Expected Behavior**:
Setting up EMQ ACL should be successful and S-alert message should convey the information accordingly.
                   
**Environment**:
Windows 10, Chrome (latest), https://vamos.apinf.io (release 0.52)
The following EMQ proxy was set up from user>proxies menu
![image](https://user-images.githubusercontent.com/17976243/33993764-92d609b0-e0e0-11e7-8ea5-1aba0a3190ce.png)

Windows 10, Chrome browser (latest), APInf production site (https://apinf.io)

**Comment by Nazarah** [comment]
Tested in https://nightly.apinf.io and found that two different s alert appears on configuring an ACL in API profile (proxy tab). 
So this is also unclear if the setting was saved.
![image](https://user-images.githubusercontent.com/17976243/33993847-e9ff3a40-e0e0-11e7-9fe2-931993ae00e6.png)

**Comment by preriasusi** [comment]
I don't think there's any real emq proxy yet. Closing this now.
