### ISSUE TITLE
After configuring EMQ proxy in an API profile, revisiting the profile always show s alert with "Internal server error 500" message

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3241]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login as an admin
2. go to an API profile
3. Select EMQ proy from the Proxy tab, define an ACL and click Save and Publish
4. (ignore the red s-alert)
5. Go to another page
6. return to the API profile
                    
**Outcome**:
On navigating to API profile, S-alert pops showing message "Internal Server Error 500"
         
**Expected Behavior**:
This sort of s-alert should not appear when renavigating to API profile
                   
**Environment**:
Windows 10, Chrome browser (latest), https://vamos.apinf.io (release 0.52)

**Comment by Nazarah** [comment]
Tested in nightly apinf and confirmed the bug.

**Comment by preriasusi** [comment]
Not a valid bug. To be closed now.
