### ISSUE TITLE
Uploaded logo in API profile appears as broken image. Page needs refreshing for the logo to appear

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3246]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login
2. Go to the settings tab of an API profile.
3. Click on Upload logo and select an image file
                    
**Outcome**:
In API profile, the logo place holder shows broken image. The page needs to be refreshed for the logo to appear properly.
http://recordit.co/mbPGc8CkiM
         
**Expected Behavior**:
On upload, logo should instantly appear properly in API profile page
                   
**Environment**:
Windows 10, Chrome browser (latest), APInf vamos deployment (https://vamos.apinf.io) - Release 0.52

**Comment by marla-singer** [comment]
**Investigation report**

The API logo isn't broken, it needs more time to render. If you wait for 1-2 mins on the page then you will see that

I am changing the logic of uploading and add a spinner when a logo is uploading to improve UX
