### ISSUE TITLE
Adding link of a non  json/yaml file in Documentation tab can be saved. On saving, spinner remains on the page

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3250]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login as an APII owner
2. Go to documentation tab in an API profile.
3. Click on Manage button
4. Select URL, provide link of a non json/yaml/yml file and click save.
                    
**Outcome**:
Changes get save despite non json/yaml/yml file like is provided.
S-alert shows successful upload message.
spinner keeps on loading in the documentation view
![invalidswaggerurl](https://user-images.githubusercontent.com/17976243/34100588-9e536496-e3eb-11e7-9045-552909c7b81e.gif)
         
**Expected Behavior**:
Saving the URL should not be possible.
S-alert should appear promoting the feedback about invalid file type and sk user to provide URL of a valid file extension
                   
**Environment**:

Windows 10, Chrome browser (latest), APInf vamos site(https://vamos.apinf.io) - release 0.52

**Comment by Nazarah** [comment]
Tested in nightly.apinf.io and could reproduce the same error.

**Comment by marla-singer** [comment]
Should be fixed in the next release
