### ISSUE TITLE
Changing and saving Description field of API profile navigates user to catalog view

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3253]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login
2. go to an API profile.
3. go to settings tab, make some changes in the Details field and click Save
                    
**Outcome**:
User gets redirected to API catalog.
         
**Expected Behavior**:
User should remain in the Settings tab of the related API Profile
                   
**Environment**:

Windows 10, Chrome browser (latest), APInf vamos site (https://vamos.apinf.io) - release 0.52

**Comment by Nazarah** [comment]
tested in nightly.apinf.io and couldn't reproduce it.

**Comment by marla-singer** [comment]
@Nazarah It was fixed on the nightly and will be able in the next release
