### ISSUE TITLE
Some scenarios while testing API calls

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3258]
I discovered couple of things while testing PAI calls using Vamos API.
They are displayed below:

1. http://recordit.co/cRhmlvHqsW
In the video, it is shown that the given URL to make call to the API is simply put in Postman GET request.
Postman shows a status 200:OK, indicating the call was successful.
When returned back to API dashboard, the call is registered in number of calls for Last 24 hours period.
But it is not registered under 2XX calls.
On Details view, the call is shown to be registered under 3XX calls.
**Question:** Is this a bug? or did it register as 3XX as we made the call using postman.

2. http://recordit.co/PPQOWPQ8p5
In this video, it is shown that thr API key requirement is enabled from the API profile.
The Postman GET request is updated by adding the key.
On sending the request, a 403 Forbidden call appears.
In APInf dashboard, the call response is listed as 4XX in the last 24 hours timeline.
This means the recording of 4XX call is working perfectly.

3. http://recordit.co/FxuwXHFIH9
Some random settings are made to the API profile and postman request.
All apparent 2xx requests are logged as 3xx requests,

I believe we might be having a bug over here. 
This needs a bit detailed investigation from devs.

**Comment by Nazarah** [comment]
@marla-singer can you please take a look at this?

**Comment by preriasusi** [comment]
Tested on current production 0.52.0. All 2XX calls did go under 2XX calls in analytics. I tried on postman and curl with production and customer environment. I could not repro anymore. Close for now.
