### ISSUE TITLE
Organization Profile: On filtering API with a lifecycle phase, user view shifts towards organization cover photo

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3260]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io 
2. go to an organization (with APIs having different lifecycle)
3. click the filter icon, select a lifecycle status and click filter
                   
**Outcome**:
User view gets shifted towards organization cover photo.
User needs to scroll down to see the filtered APIs.
         
**Expected Behavior**:
On filtering action, user should remain in the same view of the filtered API.
                   
**Environment**:
Windows 10, Chrome browser (latest), APInf vamos site (https://vamos.apinf.io)

**Comment by Nazarah** [comment]
Tested and verified in https://nightly.apinf.io

**Comment by Nazarah** [comment]
This can be detected when filter is being cleared in the API section.
Also it happens when APIs are sorted.

**Comment by preriasusi** [comment]
Too minor issue to fix when we have this many open.
