### ISSUE TITLE
Deleting cover photo results with large amount of delay in showing fields under branding page

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3265]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login as platform admin
2. Go to User>Branding
3. Delete the cover photo (if no cover photo is available, 1st upload one, confirm it appears on the front page and then delete it)
4. Confirm deletion
5. Go to front page
6. return to User>Branding
2. click Save button without filling the fields.
                    
**Outcome**:
Page appears empty.
No Settings field for branding appears immediately
No navigation links to other menus appear immediately
The menus appear almost more than 5 minutes later.
This has to do something with the deletion of cover photo, which takes a lot more response time from the server to respond by removing the deleted picture.

Console shows following error:
SCRIPT16389: Unspecified error.
branding (1,1)
         
**Expected Behavior**:
After deleting cover photo, returning to branding page should immediately show fields under that page and other things
                   
**Environment**:
Windows 10, IE 11, APInf vamos site (https://vamos.apinf.io)

**Comment by Nazarah** [comment]
Some additional discovery.

During the time of deletion of the cover photo, if attempts are made to visit other menus (e.g. API catalog, Organization Catalog, Add API, etc.), the content doesn't get loaded.

**Comment by preriasusi** [comment]
Closing as a minor now.
