### ISSUE TITLE
Documentation tab doesn't show added swagger file

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3266]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io
2. go to  an API profile with added swagger/OpenAPI Specification document.
3. click Documentation tab
                    
**Outcome**:
Viewer in documentation tab doesn't show the added file.
In browser console the following exception is caught.
http://recordit.co/yf3l14MFJW
         
**Expected Behavior**:
Documentation tab should show the swagger properly.
                   
**Environment**:
Windows 10, IE, APInf vamos site (https://vamos.apinf.io)

**Comment by marla-singer** [comment]
The same stuff on my side. It's started after updating Swagger UI bundle and adding attribute "async".

![joxi_screenshot_1513756497537](https://user-images.githubusercontent.com/20643403/34197053-dadde20c-e575-11e7-925a-40f336b437d1.png)

**Browser console error**
`ReferenceError: SwaggerUIBundle is not defined`

**Environment**
Chrome 62, MacOs

**Verified**
nightly.apin.io, VAMOS site (v0.52)

At the same time If I navigate under incognito mode then it works as expected.
If I navigate directly to url then it works as expected

**Comment by preriasusi** [comment]
Closing this as this is very old. Swagger UI to be tested after a big upgrade anyway.
