### ISSUE TITLE
multi protocol support

### ISSUE THREAD

**Issue by ilarimikkonen** [apinf/platform#3269]
mahesh knows

**Comment by phanimahesh** [comment]
For documentation purposes, here we go:

IBM messagebox has a "feature" allowing both mqtt and mqtt over websocket connections on the same port. There is no easy way for HSL to identify who is relying on this "feature", and they would like to not break any existing systems in the wild.

Requirement: Support both MQTT and MQTT over Websockets on the same port.
We do it using some haproxy magic, inspecting the request and forwarding to the appropriate port on emq.

**Comment by phanimahesh** [comment]
Also for documentation and future reference:

To support mqtt and websockets on the same port, this works in frontend section of haproxy config.
```
  mode tcp

  acl mqtt_connect req.payload(0,1) -m bin 10
  acl http_request req.proto_http

  tcp-request content reject if !mqtt_connect !http_request

  use_backend mqtt-out if mqtt_connect
  use_backend http-out if http_request
  default_backend mqtt-out
```
Adapt as necessary.

#### Explanation
 - Websocket connections start as HTTP connections and then upgrade to a bidirectional pipe. At connection time we can check for a http request and select the websocket backend.
 - MQTT connections must start with a CONNECT packet, which starts with the byte `0x10`. We can select mqtt connections based on this.
 - `default_backend` should not be necessary logically, but haproxy seems to not like it if it's missing. Websockets weren't working without it and I'm not spending any time investigating why.

**Comment by phanimahesh** [comment]
Backend config for http:
```
backend http-out
  mode http
  option httplog
  # Rewrite GET / to GET /mqtt
  reqrep ^GET\ / GET\ /mqtt
  server hsl-mqtt-ws emqttd:8083
```
