### ISSUE TITLE
IE: Mail settings can't be saved as SMTP Port field doesn't recognize numeric value

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3270]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login as admin
2. go to user>settings
3. Enable Email settings, provide necessary and valid values to the fields and click Save
                    
**Outcome**:
SMTP Port field is highlighted and shows alert message: "SMTP Port number must be a number", despite numeric value is provided in the field.
In other browsers (e.g. chrome, FF) the field appears as controller to add numeric values using up/down arrows. 
However, in IE11, the controller doesn't appear.
![image](https://user-images.githubusercontent.com/17976243/34197869-f71ca958-e570-11e7-90cd-ca7404b82698.png)
         
**Expected Behavior**:
It should be possible to save valid field value.
Controller to add numeric values in a field should appear properly.
                   
**Environment**:
Windows 10, IE11, APInf vamos site (https://vamos.apinf.io) - Release 0.52

**Comment by deligence-dharmendra** [comment]
Hi @marla-singer @matleppa, I have tested the above issue on development as well as the nightly environment. In my development environment, it working fine with **windows 10 and IE 11**. But in case of nightly.apinf.io, I'm getting the same issue with **windows 10 and IE 11**. Are develop and the nightly codes same? Please see the attached snapshot. 
![imgpsh_fullsize](https://user-images.githubusercontent.com/32898978/35208523-fc10f000-ff6e-11e7-9afc-ea64d42c52c9.png)
![imgpsh_fullsize 1](https://user-images.githubusercontent.com/32898978/35208524-fc562724-ff6e-11e7-9ff4-1fbbfc33b2ef.png)
![imgpsh_fullsize 2](https://user-images.githubusercontent.com/32898978/35208525-fc98359c-ff6e-11e7-8225-bb6ce31d4f75.png)

**Comment by marla-singer** [comment]
> Are develop and the nightly codes same?
Yes, the code is the same
