### ISSUE TITLE
When User has only 1 API in the platform, the Dashboard view, API Request Timeline and API Response Time charts don't appear

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3271]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login as a non-admin user
2. make sure you don't have any APIs added by you.
3. Create a new API , configure and save its proxy base path and API base path from the API profile.
4. Click on Dashboard menu in the navbar.
                    
**Outcome**:
Dashboard shows the detailed view as only 1 API is available.
However, the Axis for API request Timeline and API Response Time charts don't appear.
Also chart labels (call types, medians) path dropmenus don't appear.
Only the label texts for them appear.
http://recordit.co/PGrtlCPHE5
         
**Expected Behavior**:
Axis, dropdowns and chart labels in both charts should appear accordingly even if no calls have been made to the API
                   
**Environment**:
Windows 10, Chrome browser (latest) and IE, APInf vamos site (https://vamos.apinf.io)

**Comment by marla-singer** [comment]
Should be fixed in the next release
