### ISSUE TITLE
IE: Browse button for uploading API configuration file in Add API page has no bottom padding around text

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3272]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login
2. Click Add API menu and browse to the Import API Configuration section
                    
**Outcome**:
text in the browse button doesn't have any bottom padding
![image](https://user-images.githubusercontent.com/17976243/34199320-0fd868d8-e576-11e7-892f-3c9313dbad56.png)
         
**Expected Behavior**:
text in button should have same amount of bottom padding as that of the top padding
                   
**Environment**:

Windows 10, IE11, APInf vamos site (https://vamos.apinf.io) - release 0.52

**Comment by marla-singer** [comment]
Not sure that we can handle it. @55 What do you think?

**Comment by 55** [comment]
@marla-singer we leave it in icebox for now.

**Comment by preriasusi** [comment]
Very minor feature, Browser and issue. Closing now.
