### ISSUE TITLE
Adding a reply to a feedback doesn't immediately appear on the view. Feedback tab needs to be accessed after a page refresh to see the reply

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3273]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login
2. Go to an APi that has no feedback
3. Add a new feedback.
4. Add a reply to the feedback and save
                    
**Outcome**:
The reply to the feedback doesn't immediately appear on the view.
The page needs to be reloaded and then the Feedback tab needs be accessed to make the reply appear on the view .
http://recordit.co/1VmQRpkafi
         
**Expected Behavior**:
On adding a reply, it should immediately appear on view.
                   
**Environment**:
Windows 10, Chrome browser (latest) & IE11, APInf production site (https://apinf.io)

**Comment by marla-singer** [comment]
Test it and it is reproduced on current develop branch
