### ISSUE TITLE
IE: When attempt is made to delete a feedback, user gets redirected to frontpage

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3274]
Mandatory fields are not identifiable

**Steps to Reproduce**: 
1. go to page: https://.vamos.apinf.io and login 
2. Go to an API that has feedbacks added previously
3. Go to Feedback tab and click delete on a feedback
                    
**Outcome**:
As the confirmation window for feedback appears on browser, user is redirected to front page.
User needs to go back to API profile to verify if the action took place (deletion or cancelling the deletion).
http://recordit.co/IkEfT8WlQp
         
**Expected Behavior**:
user should remain in the API profile's feedback tab when the confirmation window for deleting feedback arrive.
Clicking delete or cancel should keep user in the feedback tab.
                   
**Environment**:
Windows 10, IE11, APInf vamos site (https://vamos.apinf.io) - release 0.52

**Comment by preriasusi** [comment]
Not repro in latest nightly. Closing.
