### ISSUE TITLE
IE: Uploaded logo doesn't appear smooth in API profile

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3276]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login
2. Go to an API that you own and upload a logo picture
                    
**Outcome**:
In IE browser, the logo doesn't appear smooth 
![image](https://user-images.githubusercontent.com/17976243/34203634-8de7e0ba-e584-11e7-8fdf-443e9eb42de2.png)
         
**Expected Behavior**:
Like other browsers, the API logo should appear smooth.
                   
**Environment**:
Windows 10, IE11, APInf vamos site (https://vamos.apinf.io)

**Comment by preriasusi** [comment]
Closing this issue now to make space for bigger ones.
