### ISSUE TITLE
IE: making feedback public/private navigates user to the front page.

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3278]
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login
2. Go to an API that has feedbacks added previously
3. Change visibility of one feedback (private or public)
                    
**Outcome**:
User gets redirected to platform frontpage.
User needs to navigate back to Feedback tab to ensure if the visibility of feedback has been changed or not.
This happens when trying to change visibility of a single feedback.
         
**Expected Behavior**:
User should remain in the Feedback tab on changing visibility of a feedback                   

**Environment**:
Windows 10, IE11, APInf vamos production site (https://vamos.apinf.io) - release 0.52

**Comment by preriasusi** [comment]
@deligence-dharmendra To be verified and in case reproduced on nightly to be then fixed.
