### ISSUE TITLE
In table view of Catalog, some logos appear shrinked

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3280]
**Steps to Reproduce**: 
1. go to page vamos deployment and login
2. go to an API and upload the following logo3
![apinf_logo_black_2](https://user-images.githubusercontent.com/17976243/34208196-295bdcac-e596-11e7-973f-1fb1301747b8.png)
3. Go to APi catalog and switch into table view
                    
**Outcome**:
Added logo appears shrinked in the logo placeholder in table view.
![image](https://user-images.githubusercontent.com/17976243/34208262-6da0a938-e596-11e7-93a6-de8f23b20a7e.png)
         
**Expected Behavior**:
Logo should be rendered accordingly based on the size of the logo placeholder.

**Environment**:
Windows 10, Chrome browser (latest), IE11 APInf vamos deployment - release 0.52

**Comment by preriasusi** [comment]
In order to give space for bigger bugs, I'll close this now.
