### ISSUE TITLE
Proxy path saving failure

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#3286]
Steps to reproduce:

1. Go to API proxy settings
2. Modify 'API base path'
3. Push 'Save&Puplish' button:

Expected result:

  'Api base path' get's updated - Tested by caling API from API url.

Real result:

  'API base path' does not change on proxy.

Note: API base path gets updated only when 'Proxy base path' is modified also.

**Comment by deligence-dharmendra** [comment]
Hi @preriasusi @matleppa 
**I have tested this functionality on my local system and its working fine. I have used 3 browsers to test the functionality. See test environment details.**
```ruby
Ubuntu 14.04.5 LTS,
Mozilla Firefox 57.0.1,
Google Chrome 60.0.3112.78
chromium-browser 63.0.3239.84,
```
**Second, I have a question related to below code. I'm not familiar with Meteor.throw().**

```ruby
apinf/platform/blob/develop/apinf_packages/proxy_backends/client/form/autoform.js
        if (publishApiBackendOnApiUmbrellaError) {
           Meteor.throw(500, error);
```
**Third, what is the use of below response.result? I'm getting the huge amount of data in this response.**

```ruby
apinf/platform/blob/develop/apinf_packages/proxies/server/methods/api_umbrella.js
try {
      // Send the API Backend to API Umbrella's endpoint for creation in the backend
      response.result = umbrella.adminApi.v1.apiBackends.createApiBackend(backend);
```

Please advise

**Comment by preriasusi** [comment]
@deligence-dharmendra Test by calling hte API. The UI updates, but not the real path to make API calls.

**Comment by preriasusi** [comment]
I can't repro anymore on 0.52.0 in production.
