### ISSUE TITLE
Align values in dashboard overview

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3294]
**Steps to Reproduce**: 
1. go to page: https://seinajoki.apinf.io/dashboard?proxy_id=qegAXrKD9XAatPtKW&timeframe=7
2. Look at the Number of requests column.
                    
**Outcome**:

<img width="481" alt="alignment" src="https://user-images.githubusercontent.com/1927158/34416611-f3ab63e4-ebfc-11e7-82a5-04df7df4eb56.png">

Numbers are not aligned. 
         
**Expected Behavior**:
Numbers are aligned.

**Comment by marla-singer** [comment]
@kyyberi What do you expect the align?

**Comment by kyyberi** [comment]
Practically everything should be aligned, otherwise the view looks restless. But if you need an example, then look at the "number of requests" in My APIs. First and second row numbers are not even closely aligned.

**Comment by preriasusi** [comment]
See also #3299

**Comment by preriasusi** [comment]
Let's fix this in re-write of dashboard some day. Close for now.
