### ISSUE TITLE
Add loading/refreshing indicator to dashboard overview and API detailed view page

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3297]
**Description**:

In the dashboard overview page data is loaded async and all numbers are in the beginning 0s. UI needs an indicator that it's loading data. That might occasionally take long time and without any indicator end user often gets the impression that it's broken. 

Suggestion: 
When loading data
<img width="1178" alt="screenshot at jouluk 29 12-12-40" src="https://user-images.githubusercontent.com/1927158/34434950-a4de2396-ec92-11e7-86bb-d11e75ef1aa9.png">

After data has been loaded
<img width="1178" alt="screenshot at jouluk 29 12-12-40-done" src="https://user-images.githubusercontent.com/1927158/34435011-2064a850-ec93-11e7-9cee-7bb34900acf1.png">

And while page data is refreshing ( a feature of automatic page refresh has been done earlier)
<img width="1178" alt="screenshot at jouluk 29 12-12-40-refresh" src="https://user-images.githubusercontent.com/1927158/34435023-3787b2d4-ec93-11e7-867a-20b40d5101ed.png">

 

**User Story**:

"As an API owner, I want to see indicator that data is been loaded in dashboard to be able to know that everything works and I will soonish see the KPI values for APIs."

**Comment by kyyberi** [comment]
Same thing for API detailed view. 

https://www.youtube.com/watch?v=1O_ixfwiuEg 

Needs some indicator that dashboard is loading data in the background. Otherwise user might think that it's broken. The delay in updating charts is visible when switching from last 24 hours view to last 7 days view.

**Comment by preriasusi** [comment]
@marla-singer is this dube or related to #3095

**Comment by marla-singer** [comment]
@preriasusi It is the same that 3095

**Comment by Nazarah** [comment]
Duplicate. CLosing this.
