### ISSUE TITLE
Center Featured apis in page 

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3298]
**Description**:

List of featured apis (as grid) should be centered in page. Now they are aligned to left. 
<img width="1276" alt="center-please" src="https://user-images.githubusercontent.com/1927158/34436545-79d0f266-ec9f-11e7-993e-1e3e66387ff3.png">

**User Story**:

"As an API owner, I want to see featured apis centered in the page to make it more professional looking"

**Comment by marla-singer** [comment]
@kyyberi It supposes to display 4 APIs at row
What about 1,2,5,6,7 count of APIs? Should it be centered as well?

**Comment by kyyberi** [comment]
Whole block which contains the API cards should be centered IMHO.

**Comment by marla-singer** [comment]
@55 Leave your comment as well

**Comment by 55** [comment]
Agree, should be centered.

**Comment by preriasusi** [comment]
@55 is this still valid in next?

**Comment by 55** [comment]
nah
