### ISSUE TITLE
Overlapping arrow and numbers in analytics overview page

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3299]
**Steps to Reproduce**: 
1. go to page: https://apinf.io/dashboard?proxy_id=ABiucsGwCsZwjW3C7&timeframe=7
2. See APInf CAtalog REST API row and APInf Management REST API row
                    
**Outcome**:

Number value of requests overlaps green arrow. 
<img width="558" alt="screenshot at jouluk 29 18-02-01" src="https://user-images.githubusercontent.com/1927158/34441186-b7bc0638-ecc2-11e7-9bbe-f9197ac22a84.png">

**Expected Behavior**:

Number values and arrows do **not* overlap. 
                   
**Environment**:

MacOS, FF (57.0.1), APInf production site (https://apinf.io)

**Comment by preriasusi** [comment]
It looks like the number of requests is much higher in real life then in test environment. Add some space for billion calls.
