### ISSUE TITLE
Facebook media (link to public group page) fails in Related media

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3301]
**Steps to Reproduce**: 
1. go to page: https://apinf.io/apis/api-talous-101-rest-api
2. scroll to Related media
                    
**Outcome**:

Related media Facebook group link fails. 
<img width="866" alt="fb-fail" src="https://user-images.githubusercontent.com/1927158/34460824-c9f76fd4-ee22-11e7-9b3e-3563568b16a6.png">

Link in the FB item is https://www.facebook.com/groups/apitalous101/
         
**Expected Behavior**:

Show FB group link media as any other media. 
                   
**Environment**:

MacOS, Chrome 63.0.3239.108  + FF 57.0.1 , APInf production site (https://apinf.io)

**Comment by kyyberi** [comment]
FB group is public so that should not stop showing it.

**Comment by kyyberi** [comment]
It might be that FB does not allow linking group pages, but only content. https://developers.facebook.com/docs/plugins/embedded-posts/

**Comment by preriasusi** [comment]
https://www.facebook.com/help/community/question/?id=10152810511851364
Seems to be common issue.
