### ISSUE TITLE
When importing API with open API specification, skip the description

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#3305]
In current APInf when adding API with "Import OpenAPI Specification", the description to API card is taken from OpenAPI Specification. in case the description is longer then 1000 characters, error is give.

Remove the copying from OpenAPI Specification when importing. Leave the description to be empty.

Background: The API description should be short and selling text of the API. Many API descriptions are longer then 1000 charactes. Instead of copying it to the description, let's leave it away totally. It removes one error possibility when importing an API.

**Comment by matleppa** [comment]
Is this necessary?

Perhaps it would be better to refactor Add API functionality by combining it with API card tabs Settings and Proxy.

See comments in Issues 3236 and 3314.
