### ISSUE TITLE
Slug won't create while addid API by importing OpenAPI Specification and importing API Configuration.

### ISSUE THREAD

**Issue by saransh-dev** [apinf/platform#3332]
When user upload file in `Import OpenAPI Specification and Import API Configuration`, slug won't created.

## Current Behavior:- 
While uploading yaml/yml/json file, it creates only API but not slug for that API.

## Expected Behavior:- 
While uploading yaml/yml/json file, it should create a slug for that API as well.

## User Story:- 
Earlier when we create a API by add details or uploading file, it had created slug for that API automatically by using a package for slug. But now we are manually created slug for API while calling meteor.call from `autoform onSuccess` when adding API by Enter Details. But slug won't create while uploading file from `Import OpenAPI Specification and Import API Configuration` sections.

**Comment by saransh-dev** [comment]
I have fixed issue for it in issue #3305. Please check below PR:-
https://github.com/apinf/platform/pull/3324

**Comment by preriasusi** [comment]
So closing this one.

**Comment by marla-singer** [comment]
@preriasusi You closed it too early because the related PR hasn't been merged
