### ISSUE TITLE
Add admin toggle to hide development features

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#3338]
Add a toggle button to admin settings to hide development features so that features under development features can be set behind a flag that hides those from UI.

**Comment by preriasusi** [comment]
![spec](https://user-images.githubusercontent.com/7766712/35098221-fa318c1a-fc5b-11e7-9562-9979a1309c0f.png)

**Comment by preriasusi** [comment]
@55 How about this?

**Comment by deligence-dharmendra** [comment]
Hi @preriasusi, Can you more explain about **hide development features**. You mean API Lifecycle status == Development?

**Comment by preriasusi** [comment]
Nothing to do with API lifecylcle. Just a setting to turn on and off a flag that  can be used to hide UI components under a development.
