### ISSUE TITLE
UI: Unify delete buttons within lists

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3340]
### Description
In UI there are several occasions, where it is possible to remove some element. E.g. logo, external documentations, Authorized users, Organization managers.

Common for those is, that items can be deleted one by one, clicking button with Delete sign.

### Problem
Taking into account 'look-and-feel', it is not good, that the used Delete sign varies.

Upload API logo --> OK
![API_logo.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46c9a4b31c8e8cae80abf301b44fff9e2c4533317346f67e22d6e12deb462b570b5a4ca5445b5f44aaf88e7da1b32e6c981e5ab38532022d8c6853beb2901eb80bbb258a4983b4bc8e45c6e8392df5c6.PNG)

Organization logo and cover image --> OK
![org_logo_cover.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46e7869d1c8e8cae80d6bc4cb258e2d665043761260ea62864c7b96aea1729520d0a4af8415e0b41fef08c28a6b66a718d0a0ce8c3714d36976345f3e5db55ea43a82a994e8dbcbd8f4dc6ee3f24e78286483e1e1755.PNG)

API Authorized users --> change signs 
![API_authorized_users.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46c9a4b31c8396bd87e6ad4abe58f4ab3c5522613a46ef696097ec22ba416f43554d4ba9435b0d11f8ad892df2b33e798f5f0bed876c5822c13803b0aac04ee155e57dd205d0f4ae805ec1ef3724e28a89493c1e001e8efa5832b2d4.PNG)

Organization managers --> change signs
![Organization_manager.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46c7869d228c8ab38efdb64caa62fd95274720763b46ef696097ec22ba416f43554d4ba9435b0d11f8ad892df2b33e798f5f0bed876c5822c13803b0aac04ee155e57dd205d0f4ae805ec1ef3724e28a89493c1e0d1a8ffa5e32b2d4.PNG)

External documentation links  --> change signs and compress list
![external_links.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46ed8c8e26908da883d6b34aaa56e3d665043761260ea62864c7b96aea1729520d0a4af8415e0b41fef08c28a6b66a718d0a0ce8c3714d36976345f3e5db55ea43a82a994e8dbcbd8f4dc6ee3f25ee888f4d391d1755.PNG)

### Proposal
Unify used Delete signs and layout of lists
- use in every list same Delete sign fa-trash-o (as in logo and cover image items)
- remove spaces between lines in multiline lists (same way as in Authorized users and Organization managers)

**Comment by preriasusi** [comment]
Excellent point here!
