### ISSUE TITLE
Ask email confirmation when adding organisation manager.

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#3346]
# Task
1. After a manager added a new manager, email is sent.
2. When request is sent, it shows manager as a pending manager as in picture.
3. After email is confirmed, show as normal (without any label).
4. Change text to 
`An organization manager has the same rights as the original API manager to edit and delete the APIs which are connected to this organization.`

## Mock-up
![untitled](https://user-images.githubusercontent.com/7489044/35333271-cf1ce366-0116-11e8-9baf-ff91ffc0ac53.png)

## Resources
Label (use default one): https://getbootstrap.com/docs/3.3/components/#available-variations

**Comment by matleppa** [comment]
Should there be a minor fix also to the guidance text?

E.g.
"An organization manager has the same rights as the original API manager to edit, delete the API after an API has been connected to an organization."

-->

"An organization manager has the same rights as the original API manager to edit and delete the APIs which are connected to this organization."

**Comment by deligence-dharmendra** [comment]
Hi @vesa, @matleppa, Do we need to send the verification mail to the owner of the organization ?. Because when the owner adds the organization his email id automatically add to it.

**Comment by preriasusi** [comment]
@deligence-dharmendra We need to send the confirmation to the one who has been added as a manager. New manager will be responsible of the organisation, so he/she has to confirm it.

**Comment by deligence-dharmendra** [comment]
@preriasusi When a new organization creates by a user,  the login user is added as a manager at the time of organization creates. My question, Do we need to send the verification mail to the creator of the organization?

**Comment by preriasusi** [comment]
@deligence-dharmendra When user is creating organisation, he will become a manager for the organisation. No need to send email confirmation in that case to himself/herself.

**Comment by Nazarah** [comment]
>"An organization manager has the same rights as the original API manager to edit and delete the APIs which are connected to this organization."

In correct grammar, the sentence should be:
"An organization manager has the same rights as **those of** the original API manager to edit and delete the APIs which are connected to this organization." :P

**Comment by deligence-dharmendra** [comment]
@Nazarah OK.
