### ISSUE TITLE
Upgrade and test the recommended security update for JQuery

### ISSUE THREAD

**Issue by anarva** [apinf/platform#3350]
**Title**:

Upgrade and test the recommended security upgrade to JQuery version 3.

**Description**:
 
package.json update is suggested by the GitHub automated check: jquery ~> 3.0.0
The current version is 2.x, which contains some known vulnerability.
The upgrade may introduce bugs.

**Comment by anarva** [comment]
Created a new local branch to test the JQuery 3.0 compatibility.
Used this page as a basis of the experimentation, https://jquery.com/upgrade-guide/3.0/ .

Detected errors with JQuery 3.0 include at least unresponsive tabs on the API card. (See pic below.) 

![kuva](https://user-images.githubusercontent.com/32450355/35855364-ad1c3382-0b3b-11e8-94a8-d3c5a0a152a8.png)

**Comment by vinaytech** [comment]
We investigate the issue 3350, First We need to update the accounts-admin-ui@0.3.1 package which is depend on twbs:bootstrap@3.3.6,  as you see in the code 

api.use(['accounts-ui@1.0.0',
		'accounts-password@1.3.0',
		'kurounin:pagination-blaze@1.0.2',
		'session',
		'twbs:bootstrap@3.3.6',
		'underscore'
]);

So first we need to update the code of accounts-admin-ui than we can update the twbs:bootstrap@3.3.6 than we can update jQuery
