### ISSUE TITLE
[HSL] Authecation for Postgres via HTTP Request

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#3353]
### Current situation
The manipulation for ACL rule is implemented as HTTP requests (Get, Post, Patch, Delete) to particular URL. The requests are sent from Server side.

### Open question
The open question is does it need to secure requests by username, password?
If it needs then how can I do it?

**Comment by ilarimikkonen** [comment]
No auth needed because protected network. why user and pass in emq proxy settings? ->There is no need for user / pass.

**Comment by phanimahesh** [comment]
there is an option to set up authentication, however, we are going to deploy this such that the postgrest is on an internal vlan, and all traffic on internal vlan is implicitly trusted. Hence there is no need to set up separate authentication.

If it is needed, we can require authentication by enabling it on postgrest.

**Comment by marla-singer** [comment]
@phanimahesh @ilarimikkonen Okay, I got it, thanks.
Closed it as resolved
