### ISSUE TITLE
[HSL] Data for Bandwidth charts

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#3354]
1. How to get data for Bandwidth charts? (URL, documentation) 
2. Does it suggested that data can be aggregated on the server side by date, by topic?
3. What do "Incoming" and "Outgoing" definitions mean in the context of Bandwidth?
4. Can we get data every 5 seconds?

**Comment by ilarimikkonen** [comment]
value from ES. duration > one minute. aggregate / day etc..? aggregate / topic?

**Comment by Nazarah** [comment]
> What do "Incoming" and "Outgoing" definitions mean in the context of Bandwidth?
Bandwidth utilization for incoming and outgoing messages for a given time range.

**Comment by marla-singer** [comment]
Closed it as resolved
