### ISSUE TITLE
Custom templates for SignIn/SignUp pages

### ISSUE THREAD

**Issue by deligence** [apinf/platform#3362]
Not able to get the templates for creating the test cases regarding Sign In & sign up as we are using `at-form` for it.

## Current Behavior:-
Currently using `at-form` for SignIn/SignUp that generate UI for respective pages, but not able to test it's rendering.

## Expected Behavior:-
We will create custom templates for SignIn/SignUp and create test case for rendering.

## User Story:-
As we are using `at-form` for signIn/SignUp and write test cases for it's rendering, we are getting `undefine` for respective templates because we don't have any template file for both pages to import in test cases. 
1. If we import `AccountsTemplates` from `meteor/useraccounts:core` package then still getting `undefine` for respective templates 
2. If we import file where we have config for signIn/signUp AccountsTemplates then getting same `undefine`.

**Comment by preriasusi** [comment]
@anarva Is this ok?

**Comment by anarva** [comment]
@deligence, before proceeding with the task, could you please check the existing tests for similar cases in this directory: platform/tests/end-to-end/ui --The tests are run with command "npm run test"

@preriasusi If possible, the existing code should be used/reused.

**Comment by saransh-dev** [comment]
Hi @anarva ,

This is not working with Mocha because in there we use some classes and in that class, we use `browser`. And when these classes use with mocha then it shows error for `browser` i.e., `browser` is not defined.

**Comment by deligence** [comment]
Hello @preriasusi , @anarva , 

Can we go with Custom templates for same? Please confirm.

**Comment by 55** [comment]
@deligence please, go ahead
