### ISSUE TITLE
Add api feature: Add descriptions to all fields

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#3403]
- short description texts can be shown as disabled text within a field itself
- long description can be added as a tooltip with info icon.

**Comment by 55** [comment]
Add them as paragraphs, not as tooltips with info icon.
Almost everybody will open this info icon, because "adding API process" is not common knowledge, so even technical users will need this information. Also this way we avoid additional click.

**Comment by Nazarah** [comment]
**Field:** API Name
**Field Description:** Provide a meaningful name to understand the type of the API at a glance.
Example text inside field: "_e.g. Tampere Bus Service_"

Field: Description
Field Description: Briefly describe what your API does and what information can user access using this API.
Example text inside field: "_Plan your journey across Tampere city by getting up-to-date bus information, including real-time vehicle location detection and inter zone routing. You can lookup bus timing by line and stoppage._ "

**Field**: URL (suggestion to change the field name into API Endpoint)
**Field Description:** This indicates the the server address where your API is residing. This endpoint will be referenced while adding your API to a proxy. Provide a valid URL starting with 'https://..' to make real calls to your API.
**Example text inside field**: "_e.g. https://tampere-bus-service.fi_"

@55 please review.

**Comment by preriasusi** [comment]
"Plan your journey across Tampere city by getting up-to-date bus information, including real-time vehicle location detection and inter zone routing. You can lookup bus timing by line and stoppage. "

- This text suits for the app user, and app uses API. API is used by the developer who creates API. So "Get information to  journey across Tampere city by getting up-to-date bus information, including real-time vehicle location detection and inter zone routing. Bus timing availabel by line and stoppage. "

**Comment by preriasusi** [comment]
Could also be:
Example text inside field: "e.g. Local Bus Service"

**Comment by matleppa** [comment]
### placeholder
What is needed here, is the attribute "placeholder" with a suitable value to be shown in input element.

> Example text inside field: "e.g. Local Bus Service"

I'd vote against this "e.g." prefix in placeholder text, because the usual way to use it is to give an example of the very input text, which is supposed to be filled into the field.

### description text
I agree with the order of elements in this wireframe:
- title
- description text
- input field itself

**Comment by matleppa** [comment]
![3403_description_texts](https://user-images.githubusercontent.com/23265155/41642540-3a8c4bdc-7471-11e8-8134-2972825b68fd.PNG)
