### ISSUE TITLE
Padding, button placement and text wrapping issues in S alert.

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3408]
![image](https://user-images.githubusercontent.com/17976243/36528170-dffccde2-17bc-11e8-8677-59adc52dc43f.png)

The following one can be seen when visited to the API profile "0 _ 0 003708282559" in nightly:
![image](https://user-images.githubusercontent.com/17976243/36528248-195aea4c-17bd-11e8-87c7-715076edb429.png)

**Expected Behavior**:

1. S alert message dialog should have equal amount of top, left, bottom and right padding.
2. Long texts should be wrapped.
3. Placement of X button should be in correct position.
                   
**Environment**:

Windows 10, Chrome browser (latest), APInf nightly (https://nightly.apinf.io)

**Comment by preriasusi** [comment]
With the current amount of issues, let's get functionality first fixed. Closing this now.
