### ISSUE TITLE
Lessons for using the API

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#341]
As a newbi developer I would love to see codecademy and such lessons related to given API at hand. Could the information be pulled somehow? At least make background process which searches lessons from given services and suggests those in API profile page. http://techcrunch.com/2013/01/09/codecademy-api/

**Comment by kyyberi** [comment]
Simple concrete example: https://www.codecademy.com/apis

**Comment by kyyberi** [comment]
Of course the course can be just video in Youtube and some description of it. Simple as that, no need for codecademy :)

**Comment by kyyberi** [comment]
And when you have finished the course you will get a badge (on open badges) :)

**Comment by bajiat** [comment]
Related media (= oembed) can provide this. You can link e.g. Youtube videos, presentations, blog post for an API.

Closing during icebox gardening.
