### ISSUE TITLE
REST API: Add to Catalog API ability to connect an API to proxy

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3413]
## Description
- "As an API owner I want to connect my API to proxy using  REST Catalog API"
- "As an API owner I want to disconnect my API from proxy using REST Catalog API"
- "As an API owner I want to see endpoint and base addresses of my API, when it is connected to a proxy"

### New endpoints
~~ #### GET /proxies
- response contains list of available proxies (name, id, type) ~~ see Update: Proxy API

#### POST /apis/:id/proxy
Parameters (in URL)
- :id
  - Expected value: id of API in question

Parameter (in body)
-  "proxyId"
   -  expected value:  id of an existing proxy
-  "frontendPrefix", which is a string to be added to all proxy requests (identifies the API by proxy)
   - Expected value: a unique string
-  "backendPrefix", which is an identification of API on server
   - Expected value: a string 
- "apiPort", port number on API server
   - Expected value: a number within port number space
- "disableApiKey", whether API key is required or not
   - Expected value: "true" | "false"  

Functionality
  - if proxy with given proxy-id is found, the API is connected to that proxy
    - the newly created proxyBackend object is returned in response.
  - if proxy is not found, error response with code 400 is returned
  - if the API was already connected to a proxy, error response  with code 400 is returned
 
#### DELETE /apis/:id/proxy/:id
- if proxy backend with given proxy-id and id of API in question is found, the API is disconnected from proxy
- if proxy backend is not found, error response with code 400 is returned

#### GET /apis (and similar responses)
- when Admin is requesting API data, in addition to parameter url, return also
  - API backend URL (the address, which was given, when API was created)

#### GET /apis /:id 
- when Admin is requesting API data,  return also proxy backend data, if API is connected to a proxy

**Comment by matleppa** [comment]
Update: Instead of original plan, where Catalog API contains all new functionality, a new API is implemented to contain Proxy related operations
- create, edit and remove proxy

**Comment by ilarimikkonen** [comment]
vesa has reviewed this some time back; go vesa!
