### ISSUE TITLE
Developer engagement with list of low hanging fruits

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#342]
One thing is to push out information about low hanging fruits, easy picks for community to participate. Otherwise the barrier might be high for newbies. Add label to Github for low hanging fruits and use Github API to pull top 5 most simple features to work on the apinf.com page under topic "Call for action" or something.

**Comment by bajiat** [comment]
Label has been added.

**Comment by kyyberi** [comment]
works for me

**Comment by kyyberi** [comment]
Here's Jquery implementation who to add to website 

https://jsfiddle.net/kyyberi/21yzt39z/

**Comment by kyyberi** [comment]
Vote for close. This is done

**Comment by bajiat** [comment]
Closing during icebox gardening.
