### ISSUE TITLE
[HSL] getting back to main page from emq dash is not working

### ISSUE THREAD

**Issue by ilarimikkonen** [apinf/platform#3429]
user should be able to return to front page from emq dash, not just to Rest dashboard

**Comment by marla-singer** [comment]
@ilarimikkonen It's ossible if you click on Site logo or Site title.
If a site doesn't have anything then Add it in Branding settings

**Comment by preriasusi** [comment]
Agree with @marla-singer. Only thing was that icon was lost totally on a version we used yesterday.

The fix probably to update the icon of site logo.
