### ISSUE TITLE
API and Organization catalogs changes

### ISSUE THREAD

**Issue by 55** [apinf/platform#3435]
Description and tasks are yet to be confirmed.

- [ ] Include Organizations in API catalog
- [ ] Remove Organizations catalog
- [ ] Move user's APIs to own view
- [ ] Move user's organizaitions to user profile (instead of Company field)

**Comment by Nazarah** [comment]
Next has a new catalog UI for both APIs and Organizations. If new feature requests are needed there, we'll make separate issues. Closing this.
