### ISSUE TITLE
Change logic to have APIs private by default

### ISSUE THREAD

**Issue by 55** [apinf/platform#3436]
Now API is public by default.
User can change it to `Private` in settings.

Goal is to change this that by default APIs are private (and there is no label `Private`) and user can change them to Public (public APIs should be with label `Public`).

**Comment by Nazarah** [comment]
from UI perspective, will the label `public` appear only in the API profile? 
Because it is usual scenario that APIs that are public appear in catalog for general view.

**Comment by Nazarah** [comment]
Closing this.  The functionality has been implemented in Next and will be available after Next is merged with Develop.
