### ISSUE TITLE
Not allow user to connect an API to a proxy using /signup/ as frontend prefix

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#3440]
The list of forbidden prefix
- /signup/
- /admin/
- /admin/...
- /

These paths are used for API-Umbrella by itself

**Comment by ilarimikkonen** [comment]
![signup1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d608343220330011111451/125516c66e82c728ace21e0d46fb9d9d2d9793f8cda5fd53b652fa912a5265296b51f6792387e67cbb122d055a5d47a942585f12fdfedf2ca3a42062c80d55b98e30063e937f03a6aa8318b500bf23834981b5bd8f4cc4ec3837aa.PNG)

**Comment by ilarimikkonen** [comment]
for example /admin/this/ is not allowed,  so is this: https://nightly.apinf.io:3002/admin/login

**Comment by ilarimikkonen** [comment]
need to protect this with regex
