### ISSUE TITLE
On registration, loading the sent link shows  shows "Verify email link expired"

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3450]
**Steps to Reproduce**: 
1. go to page: https://staging.apinf.io
2. register in APInf using a non existing id and email (e.g. use fake email generator)
3. Wait in the fake email browser tab for incoming message.
4. Paste the sent link in browser and load the page
                    
**Outcome**:

On loading the home page, S alert shows the following message: "Verifying Email Link Expired"
User remains "not signed in" in the platform.
When signed in using admin credentials, the registered user (above) appears in the user list
![image](https://user-images.githubusercontent.com/17976243/38242986-e38a92b8-373e-11e8-9de6-27559b760f5e.png)

Unless checked without admin credentials, it appears that the user couldn't register him/herself in the 1st place.

![image](https://user-images.githubusercontent.com/17976243/38242294-1d2dcafa-373d-11e8-9d18-b2434793a2e4.png)
         
**Expected Behavior**:

On loading the page with given URL, user should be automatically signed in into the platform.
                   
**Environment**:

Windows 10, IE11, FF (latest), https://staging.aping.io
Release: 0.55.0

**Comment by preriasusi** [comment]
Not repro anymore.
