### ISSUE TITLE
Clicking anywhere outside Edit proxy modal closes the modal

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3458]
**Steps to Reproduce**: 
1. go to page: https://nightly.apinf.io and sign in as Admin
2. than the modal windowGo to user profile > Proxies
3. Click Edit button on one of the available proxies.
4. After the edit modal opens, click anywhere 
                    
**Outcome**:

Edit modal gets closed.
http://recordit.co/Tq0MnQFWC0

**Expected Behavior**:

When modal is open, background should remain inactive.
I.e. modal window should not get closed if there is click event anywhere outside it.
                   
**Environment**:

Windows 10, Chrome browser (latest), https://nightly.apinf.io

**Comment by preriasusi** [comment]
Closing  now as a minor. It is a bit annoying.
