### ISSUE TITLE
Dashboard: Indicate also case, when the trend is flat

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3460]
### Dashboard functionality
When there is a change in trend, it is indicated with a sign and a text above chart (Number of requests / API Response time / Unique API Users). 
Red/green triangle and amount of change told verbally.
### Problem
When there is no change from previous period, there is no indication of that, which may cause user to think, that something is missing.

### Solution
Add indication also in case, when the values in previous and last period are the same.
E.g. a small blue rectangle with text "Same as in previous day"

![3442_missing_flat_trend.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46bbc0ce71bd8ea09cfab64da362f698285218673b01ad2f32c9a138ad4d71040c1b5ca6535d5a46ffabdc2ff2b63a248f5e02e8d26d5f22c73a47abbd9003ad43eb7edf10d8eff6df0ed2e22f27e4818e4a3c1d031a8dfc5c3ca9984cda15.PNG)

**Comment by marla-singer** [comment]
@matleppa @Nazarah @55 
The possible prototype. Don't think a table line has to have any indicator of no trend (like dash or arrow or anything else)
![joxi_screenshot_1525347211643](https://user-images.githubusercontent.com/20643403/39574274-36551d62-4edf-11e8-9483-e53a173cd6dc.png)

**Comment by 55** [comment]
@marla-singer include dash for table

**Comment by matleppa** [comment]
@marla-singer @55 Yes, I still think, that an indicator is needed also in case the trend is flat. That way there is a similar layout in every case (indicator + text), which makes it faster for the observer to get the idea about trend.

**Comment by marla-singer** [comment]
@55 @matleppa 
![joxi_screenshot_1525679820877](https://user-images.githubusercontent.com/20643403/39691205-6e4ebb16-51e5-11e8-8afd-ac14e2ed2060.png)
![joxi_screenshot_1525679788744](https://user-images.githubusercontent.com/20643403/39691206-6e6e4a80-51e5-11e8-9d5c-ac8944920a5a.png)

**Comment by 55** [comment]
@marla-singer @matleppa just dash with no text is good enough

> Below charts I'd suggest a shortening, text to be "same as previous XXX days".
👍

**Comment by marla-singer** [comment]
@55 @matleppa 
Final decision

![joxi_screenshot_1525682749019](https://user-images.githubusercontent.com/20643403/39693317-4870b55a-51ec-11e8-899d-0ddbc23b74e3.png)
![joxi_screenshot_1525682721313](https://user-images.githubusercontent.com/20643403/39693368-7432cf0c-51ec-11e8-9815-d5572453686a.png)

**Comment by matleppa** [comment]
@marla-singer @55 OK, let's try this.
