### ISSUE TITLE
UI: input field labels place misleading with pre-defined host URL

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3471]
### Problem
In proxy settings the labels of input fields for Proxy base path and API base path are positioned misleadingly.
Same applies to Monitoring endpoint input field.

#### Proposal 1
- Move labels (keep bold font-weight) above the corresponding input fields.
- Add new labels (with normal font-weight) instead: API URL via proxy, API Host URL

#### Proposal 2
- Remove host URL parts, so that input fields are left aligned.
- Add separate fields, where the addresses (Host URL + base path) are updated automatically, when base paths are written.

**Comment by matleppa** [comment]
![proxy_path_names](https://user-images.githubusercontent.com/23265155/39750713-a0ab473a-52be-11e8-8abc-75724d0b6efc.PNG)

**Comment by Nazarah** [comment]
@matleppa proposing the following alternative:

1. On selecting a proxy from the dropdown (or in case of default proxy), the proxy host URL is populated in the related field. The text is non editable and appears with disabled text color. Similar design with the API base path.
<img width="632" alt="proxyurl" src="https://user-images.githubusercontent.com/17976243/39752515-5e0a20ee-52c4-11e8-98b2-84ac2e60303a.png">

2. User can input values for the proxy base path and API base path. Both text will appear as active and editable.
<img width="632" alt="proxyurl2" src="https://user-images.githubusercontent.com/17976243/39752560-80fb2f44-52c4-11e8-97c7-87bd23506c02.png">

**Comment by matleppa** [comment]
I still think that base paths need to be separated from the host URLs more clearly. And that in the input field (or similar construction) there is nothing else than what the label describes.

Perhaps:
- input fields only for base paths 
- and separate strings next to them to show, what the outcome will be, when the host URL and base path are separated.

**Comment by matleppa** [comment]
Perhaps the titles for input fields could look something like that:

![Base_path_2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46ca958926bd93a89be18011e611b2843b492d762a10e17132d0b67aec407e550b5f48f8445a5641fff9897da7b16a778f4e17ff933c0120996048e6edc00db513b821814e80b2bc8844c0ea3b20e2898c5d73.PNG)

This way there is an explanation to both parts of address and it is clearly visible, that which part is the base path.
