### ISSUE TITLE
Implement one user multiple account login into APInf

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3479]
### Description

Users may want to access the same account in the platform using different login methods available with it. 

### User Story:

> As an APInf user, I want to sign in to to my same APInf account using any of the available login platforms.
> As an APInf user, I want to add more than one login platform to access my already existing account

### UPDATE

Instead of implementing the functionality from scratch, we are using the following meteor package.
https://github.com/yubozhao/meteor-link-accounts

This package allows APInf user account to be connected to preferred social media platform.
In this implementation, User can access the same APInf account using his GitHub Credentials, provided the platform has GitHub Client ID and secret set in Login Platform page.

### New Feature

1. Under Username > Account, new module "**Add alternative login platforms**" should appear. 
Primarily it should support login using GitHub and Fiware.
2. (apart from local email that user used to sign up) user should be able to add both GitHub email/user name to access the same account.
3. User will need to give relevant credentials (username/email and password) to be able to access with alternative login method
4. User will be able to remove alternative login platforms.

### Cases:

new page: _username > account settings_: It is a combination of both existing profile and account page in APInf 

_**1. User signs up in local email/password (e.g. any domain email)**_
     - Under username > account settings, `**Registered Email Address**` should show the email addressed used to create the account.

_**1.1 From username > Account, user adds GitHub (and/or) Fiware credentials.**_
     -  Under username > account settings, added GitHub / Fiware email will appear in related place-holder under a new module Alternative Login Platform.

_2. **User signs up using GitHub/Fiware credentials**_
     -  Under username > profile, `**Registered Email**` should show the github/fiware email address 
     -  same email will also appear in specific placeholder (GitHub/Fiware) under Alternative Login Platform
     - User will not be able to add more than one GitHub/Fiware account
     - User will be given an option to add a local password in APInf for the email address used. User will be able to sign in into the same account in APInf using the email (for GitHub / Fiware signup) and password apart from the added login platform.

_**3. User wants to remove a platform**_
      - user will be prompted to add a local password to access the APInf account using the specific email address in future. User will not be able to remove a platform unless s/he provides a password.

_**3.1 User Signs Up with GitHub / Fiware and wants to remove the specific login platform**_
      - user will be prompted to add a local password to access the APInf account using the specific email address in future. User will not be able to remove a platform unless s/he provides a password.
      - After user adds a local password and removes the login platform, the password (encrypted) will appear under Registered Email Address field. The credentials (email and password) will get saved in APInf locally. User will be able to edit password.

_**4. User Readds deleted GitHub/Fiware login platform (same email/username)**_
      - GitHub/Fiware email will be populated in related field under Alternative Login Platform module.
      - Email address and password stored locally in APInf (see case 3.1) will remain

_**4. User Readds GitHub/Fiware login platform (new email/username)**_
      - new GitHub/Fiware email will be populated in related field under Alternative Login Platform module.

**Comment by preriasusi** [comment]
I think not only for developers. "A APInf user ..."

All other great.

**Comment by Nazarah** [comment]
### Wireframes

**1. Case: User wants to add an alternative login platform (GitHub or Fiware)**

* Under **User > Account** Settings, new module `Alternative Login Platform` appears
The module contains 2 buttons: `Add GitHub Account` and `Add Fiware Account`
![alternative login platform](https://user-images.githubusercontent.com/17976243/39997353-4db7ef2a-578b-11e8-9f2a-6ab09efa0e57.png)


* On clicking any button, related login platform appears in new browser tab.
User needs to give credentials if not signed into the platform previously. 
![githubsigninpage](https://user-images.githubusercontent.com/17976243/39997447-a8a67eba-578b-11e8-9e58-48ec1c166f9e.png)

* After user gives credentials for the relate platform, **username > account** is refreshed and user's email address (for that login platform)  appears beside the login platform. 
Email address appears as non-editable text.
Login platform can be removed by clicking the `red Delete button`
![alternative login platform github](https://user-images.githubusercontent.com/17976243/39997611-31d45c98-578c-11e8-9bd9-f66e7884c95b.png)

* Added email Address also appears under **username > profile** under new field label `Alternative e-mail`:
![alternativeemail](https://user-images.githubusercontent.com/17976243/39997685-643767e8-578c-11e8-9311-c14a13fdaeaa.png)

**Comment by Nazarah** [comment]
### Wireframe

**Case 2. User Adds both GitHub and Fiware Account**

* Under **username > Accounts**, the `Alternative Login Platform` contains email addresses for both GitHub and Fiware.
![alternative login platform fiware](https://user-images.githubusercontent.com/17976243/39998105-b8fc95cc-578d-11e8-82ff-550c0fb9869e.png)

* Under username > profile, GitHub and fiware emails appears under `Alternative e-mail 1` and `Alternative email 2` labels.
![alternativeemail2](https://user-images.githubusercontent.com/17976243/39998210-0cdb241a-578e-11e8-9382-0d832499dbf4.png)

**Comment by Nazarah** [comment]
### Wireframe 
tbd

**Case 3: User signs up with GitHub/Fiware at the very beginning**

* GitHub Email appears as Registered e-mail under username > profile

Case 3.1: User later adds Fiware credentials as alternative login platform.

* Fiware email appears under Alternative e-mail 1 under username > profile

* Fiware email appears under Alternative Login Platform.

**Comment by Nazarah** [comment]
### Wireframes

**Case 1: User has a local account in APInf and adds his/her GitHub / Fiware account:**

* APInf has new view under **username > Accounts Settings**. It is the combination of User Profile and Account.
* Account Settings page Displays **Username**, **Registered Email Address** and **Password**.
Username and Password can be edited from this page by clicking edit button in respective fields.
* A new module: **Alternative Login Platform** contains **two buttons** to add user's **GitHub** and **Fiware account**.
![newaccountpage](https://user-images.githubusercontent.com/17976243/40161089-5258d79a-59b8-11e8-8b54-5f2acdb979e6.png)

* On clicking Add GitHub Account / Add Fiware  Account, user is redirected to the login page of the specific platform  in a new browser.
After user provides credentials, Username > Account Settings page is refreshed and User's GitHub / Fiware Email Address appear under Alternative Login Platform

![newaccountpage github](https://user-images.githubusercontent.com/17976243/40161661-34d932bc-59ba-11e8-8945-0f3310c1e79f.png)

![newaccountpage fiware](https://user-images.githubusercontent.com/17976243/40161676-42f84cac-59ba-11e8-9ad0-6fad65733886.png)

* User can have both GitHub and Fiware accounts connected to the local account in APInf.
![newaccountpage all](https://user-images.githubusercontent.com/17976243/40161770-69198068-59ba-11e8-837a-83d98c0ba681.png)

**Comment by Nazarah** [comment]
### Wireframe

Case 2: User signs up using GitHub / Fiware Account

* Username > Account page:
   - User Name field will show user's GitHub / Fiware user name
   - Registered Email Address field will show user's email address used in GitHub / Fiware account.
   - Alternative Login Platform: related field will show the github / fiware email address used to sign up an account in APInf. User will not be able to add more than one GitHub / Fiware account.

![newaccountpage githubsignin](https://user-images.githubusercontent.com/17976243/40163793-6aa7d2a8-59c0-11e8-82a6-1f495b0d1991.png)


   - User can add a password that will be stored in APInf locally against the email address used.
   - User will be able to sign in locally in APInf (apart from GitHub/Fiware signing in) using the email address and given password.

![newaccountpage fiwaresignuplocalpassword](https://user-images.githubusercontent.com/17976243/40163880-a5685a16-59c0-11e8-9244-78a65edc425d.png)


   - After user adds a local password, it will appear below the Registered Email Address field.

**Comment by Nazarah** [comment]
### Wireframe

**Case 3: User wants to remove a login platform**

- On clicking remove button in a platform field, a modal appears letting user know about the consequence of removing a login platform.
- User is also prompted to add a local password for the email used to access APInf in future using the email address.
- User can only remove a login platform if s/he provides a local password for the email that was used in GitHub/Fiware platform login

![newaccountpage githubdelete](https://user-images.githubusercontent.com/17976243/40164648-d2ba4de2-59c2-11e8-8d23-a38af632ef1e.png)

**Comment by Nazarah** [comment]
Related Issue: #3480

**Comment by Nazarah** [comment]
Waiting for PR #3493 to be merged

**Comment by preriasusi** [comment]
@Nazarah #3493 us merged. Is this still blocked?

**Comment by Nazarah** [comment]
@preriasusi I may need an co-pilot to work with the logic around the authentication with fiware and github. if @matleppa has nothing in high prioity list, perhaps he can mentor me here.

**Comment by Nazarah** [comment]
###UPDATE

Instead of implementing the functionality from scratch, we are using the following meteor package.
https://github.com/yubozhao/meteor-link-accounts

This package allows APInf user account to be connected to preferred social media platform.
In this implementation, User can access the same APInf account using his GitHub Credentials, provided the platform has GitHub Client ID and secret set in Login Platform page.
