### ISSUE TITLE
Dashboard doesn't work properly after configuring proxy backend

### ISSUE THREAD

**Issue by 55** [apinf/platform#3488]
Dashboard doesn't work properly after configuring proxy backend: 

**Steps to Reproduce**: 
1. go to API Profile -> Proxy -> Fill required fields
2. click Save & Publish button 
3. go to dashboard by clicking "Dashboard" link in topbar
                    
**Outcome**:

Dashboard doesn't work properly, spinning never ends.

![thebug1](https://user-images.githubusercontent.com/7489044/40411955-9d3b4830-5e7a-11e8-820d-c5b22973e826.png)
                        
**Environment**:

macOS 10.13.4, Chrome browser (latest), latest develop branch

**Comment by ilarimikkonen** [comment]
I just dont know

**Comment by ilarimikkonen** [comment]
works great
