### ISSUE TITLE
Dashboard doesn't show analytics after configuring proxy backend

### ISSUE THREAD

**Issue by 55** [apinf/platform#3489]
Dashboard doesn't show analytics after configuring proxy backend: 

**Steps to Reproduce**: 
1. go to API Profile with proxy configuration already configured -> Proxy
2. change Proxy base path field
3. click Save & Publish button (make sure it saves it successfully) 
4. go to dashboard
                    
**Outcome**:

Dashboard doesn't show analytics

![bug1](https://user-images.githubusercontent.com/7489044/40412797-f6b401b6-5e7c-11e8-8ba2-0ee67fadf468.png)

                   
**Environment**:

macOS 10.13.4, Chrome browser (latest), latest develop branch

**Comment by ilarimikkonen** [comment]
devops issues, "fixed"
