### ISSUE TITLE
documentation loading fails with broken swagger documentation

### ISSUE THREAD

**Issue by ilarimikkonen** [apinf/platform#3496]
how to repro: create an API add attached in this issues documentation 
how it should work: doc loads
what goes wrong: it just loads and nothing happens

also, this seems to affect the whole stability of the platform! main page where apis load comes unsteady (API cards don't load always, amount of APIs is zero, etc.

**Comment by ilarimikkonen** [comment]
[trivoresawg1.json.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d608343220330011111451/125516c66e82c728ace21e0d46fc8693358d91ac9ce8a844f513fa872648653f6b14b1247a80e03cfd1839545a5d4dfe145c0b44faad8c29afb33f708a0a0aea876a5a66da2f53fde6d640e258f075c95d8fa4bd8346c1ed3f2de78289473a18001181ed10.txt)

**Comment by ilarimikkonen** [comment]
please note that i had to change the file name by adding .txt because waffle

**Comment by vinaytech** [comment]
HI The document has syntax issue.
You can verify here.
https://editor.swagger.io/
Thanks
