### ISSUE TITLE
UI, connect API to Org, dropdown enhancement

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3506]
When API is connected to an Organization (on Organization page), there is used a modal containing a drop-down list of available APIs.

### Enhancement ###
The list would be more clear, in case as first item on list there were instruction: "Select one" as a deactivated option.
That way it were similar with other dropdown list in UI.

![connect_api_org_dropdown.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46eb9b942d8780bdb0e8af4a9b52e2931642357c3900ac3c7ec7af6aaf50740b0a0c0abe4b4a5a41fefadb7ea2e23c76de5909e4d46e5f74903c16fabf870da313f871d51bdaebe5c01982fa3737e68c854e3b1c0d1c8cf95c34a69e4ecb4abb.PNG)

**Comment by Nazarah** [comment]
Interested, self assigning
