### ISSUE TITLE
UI: Tabs APIs and My APIs interworking with API page menu selections

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3510]
Functionality to be corrected after PR 3503 is merged.

### Problem ###
When moving between pages APIs / My APIs, the possibly selected "My bookmarks" or "APIs with documentation" works incorrectly.

All the APIs are displayed as the option "Show All" were selected, but the selection "My Bookmarks" or "APIs with Documentation" is indicated to be selected.

Steps:

1. open APIs page
2. select "APIs with Documentation"
3. open "My APIs" page

Expected results:
3. "Show all" is indicated, all APIs are shown

Current results:
3. "APIs with Documentation" is indicated, but all APIs are shown.

The same error with "My Bookmarks" and also when going from "My APIs" to "APIs".

**Comment by preriasusi** [comment]
See also #3504

**Comment by matleppa** [comment]
API sort changed in Next.
Issue not more relevant. Closing.
