### ISSUE TITLE
Include no host address when providing API Monitoring endpoint

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3535]
When API monitoring is activated, there needs to be given the endpoint to be monitored.

### Problem

At the moment whole path to endpoint, including host address must be given. It even  is not checked, whether the given URL matches with the API in question.

### Solution
**Accept only the endpoint in input field when starting monitoring**. The host address has already been given as API host, when API card is created. The given API host address and given monitoring endpoint are combined, when solving the address, to where the monitoring requests are sent.

Currently, when monitoring endpoint is given, it is expected to contain the complete path (also server address and API path). 

This is error prone and in addition to that makes it possible to set monitoring even to completely different API.

![image](https://user-images.githubusercontent.com/23265155/43521604-5638debe-959f-11e8-9f41-3c4e129509b6.png)

Giving the server address must not be possible. This should be implemented same way as when giving API base path when connecting API to proxy.

API host URL is shown, but not editable, and user gives the API base path (if not included in API host URL) and the actual endpoint.

When monitoring requests are sent, the URL is formed by combining API host url (in settings) with the input part given here.
The endpoint must also be stored in monitoring table and it must be displayed as part of monitoring data, so user can see also the endpoint, from where the response has come.

**In monitoring table there will be visible the input part given here**.

![image](https://user-images.githubusercontent.com/23265155/43522181-35c90c92-95a1-11e8-98c6-d2fe8a922602.png)

**Comment by matleppa** [comment]
@55 Would you like to comment the outlook of table for Status messages after the endpoint information is added into it?

**Comment by 55** [comment]
@matleppa yes, I will add it soon

**Comment by 55** [comment]
```
<th>Endpoint</th>
...
<td><a href="https://url.com/path-to-endpoint">/path-to-endpoint</a></td>
```

![333s](https://user-images.githubusercontent.com/7489044/44136603-0e9fcbda-a076-11e8-936e-169c394cd144.png)
