### ISSUE TITLE
FIWARE integration task#1

### ISSUE THREAD

**Issue by ilarimikkonen** [apinf/platform#3552]
APInf needs to expose two settings from API umbrella:

- global request settings: IDP App ID
- sub url settings: Required headers

see screencaps

**Comment by ilarimikkonen** [comment]
![task1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d608343220330011111451/125516c66e82c728ace21e0d46fc958928d3c1e5cdf9ad4cae58f3806b1c65267c56f02975d1e778e9462e53565a4dac410e5e43aafe8c39baa47e21d40854b088270a36d43703adb0881eba02bf218b4e83b2ba824dc6fa70.PNG)
![task2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d608343220330011111451/125516c66e82c728ace21e0d46fc958928d0c1e5cdf9ad4cae58f3806b1c65267c56f02975d1e778e9462e53565a4dac410e5e43aafe8c39baa47e21d40854b088270a36d43703adbf881eba02bf218b4e83b2ba824ac0fa70.PNG)
![task3.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d608343220330011111451/125516c66e82c728ace21e0d46fc958928d1c1e5cdf9ad4cae58f3806b1c65267c56f02975d1e778e9462e53565a4dac410e5e43aafe8c39baa47e21d40854b088270a36d43703adbf881eba02bf218b4e83b2ba824bc3fa70.PNG)

**Comment by ilarimikkonen** [comment]
screencaps are for illustration; changes via management API

**Comment by ilarimikkonen** [comment]
+ we need a task for APInf UI

**Comment by preriasusi** [comment]
Regex to be .* when writing Required Headers.

**Comment by fdelavega** [comment]
The required headers stuff under the sub-url parameters is used to specify tenants of the different datasets which are registered using the sub-url settings.

In this regard, if the required headers functionality is going to be supported, then the method and URL regex for sub-urls need to be also supported

**Comment by matleppa** [comment]
@fdelavega 
About parameter Required Headers (RH).
- Is the goal that the parameter RH can be given separately for each HTTP method in sub-URL request settings?
 So for each method is needed following fields for parameters
- HTTP method (is also "any" needed as a method
- regex
- Required Headers

 @vinaytech Changes needed to current implementation according to answers.

**Comment by ilarimikkonen** [comment]
confirmed with Ficodes: we need to support all methods including "any". Supporting multiple rules for same method is optional. we need to support regex.

**Comment by ilarimikkonen** [comment]
![ficodeintegrationUi.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d608343220330011111451/125516c66e82c728ace21e0d46ee9d992c8686a081fdba44b65ce49d2648127a6b48e13b628ae92dbc56395b4d5a4bae420a0a40a8f98f7fa3b43575895c0bbbd06a0973c32f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e48e86483c1e021188ff5927ed.png)

please use this style of ui implementation

**Comment by ilarimikkonen** [comment]
setting can be places after rate limits in the proxy setting UI. For initial implementation it can be visible all the time

**Comment by Nazarah** [comment]
@vinaytech please add me as a reviewer when u create a PR for this issue. I'd like to check the UI.
