### ISSUE TITLE
Compress parameter lists in DB in order to avoid empty parameter sets

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3559]
### Background ###
In some cases it is possible to give sets of similar parameters, e.g. when an API is connected to a Proxy, there can be given "Rate limits", which are sets of three parameters as well as "Required Header Setting", which also is a list of sets of three parameters. 

When these sets of parameters are given, they are stored into DB as lists of parameter sets.

### Problem ###
There can be empty slots in lists. They are space consuming and misleading in users point of view.

- In case a parameter set is removed, it just is removed from the list in DB and the list is not compressed, so removal causes an empty slot on list, which is also visible on UI
  - steps
    - add three sets of parameters
    - remove the second set
  - as a result there is a list where the first item contains values, second item is empty and third item contains values

- while adding parameters via UI, it is possible to leave an opened form for parameters empty thus also causing empty slots in list
  - steps
    - open a form (leave it empty)
    - open a form (fill values)
    - open a form (leave it empty)
    - open a form (fill values)
  - as result in DB (and on screen) there is a list with first item empty, second item with values, third item is empty and fourth item with values

## Solution ###
When saving values into DB, compress list by removing all empty parameter sets before writing it to DB

**Comment by ilarimikkonen** [comment]
this is similar to the ficodes integration task
