### ISSUE TITLE
Removal of login platform parameters partially fails

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3568]
### Background ###
It is possible to have several login methods. The logins with a confirmation of external sites need parameters to be stored in platform.
The parameters are stored in two DBs, in LoginPlatforms collection (platform's own collection) and in meteor_accounts_loginserviceConfiguration (used by external package related to login functionalities).
### Problem ### 
Adding and modifying login platforms' parameter are successful,
however, when a login platform's parameters are tried to remove, they are removed only from LoginPlatforms collection, not from meteor_accounts_loginserviceConfiguration collection.

### Reason ###
When login platform parameter set is modified, there is a checking related to update of meteor_accounts_loginserviceConfiguration collection: 
- there has to be a value in all fields of parameter set in question.

### Solution ###
Expand parameter set checking such a way, that the modification is accepted in meteor_accounts_loginserviceConfiguration collection in case either of conditions is met:
- all fields are filled
- not any of fields is filled

This way the the collections remain at same level, when parameters are modified.

**Comment by Nazarah** [comment]
Done. Fixed.
