### ISSUE TITLE
[MUST] ReadtheDocs Project is missing 

### ISSUE THREAD

**Issue by jason-fox** [apinf/platform#3697]
ReadtheDocs project available and styled using the FIWARE CSS and Chapter CSS - this is a requirement on all Incubated enablers within a reasonable time frame after onboarding
https://github.com/contact

- MUST requirement on all GEs from the TSC

**Comment by ilarimikkonen** [comment]
evaluation of the requirement started

**Comment by ilarimikkonen** [comment]
readtehdocs initial version in https://apinf-fiware.readthedocs.io/en/latest/
