### ISSUE TITLE
Create user.isBackendManager(backendId) method for permission check

### ISSUE THREAD

**Issue by brylie** [apinf/platform#382]
Damir wrote:
Found some code duplicating under update and remove, in the Api Backends allow rules. As there gonna be some actions performing inside conditional statements, what do you think if using isBackendManager method attached to user schema. So the conditional check would be ?

if (user.isBackendManager(backend_id)) {
    // ...
}

**Comment by brylie** [comment]
@frenchbread thanks for the suggestion

**Comment by bajiat** [comment]
Obsolete. Closing during icebox gardening.
