### ISSUE TITLE
Add API Backend form Frontend and Backend host fields are ambiguous

### ISSUE THREAD

**Issue by brylie** [apinf/platform#433]
Users are confused when presented with frontend and backend host fields for the first time. Help users determine what to put in the fields with example text, sensible defaults, inline documentation, or some similar method.

Related #427 
Related #464
## Definition of done
- [ ] Complete the task #427.
- [ ] Optionally, complete #464.

**Comment by bajiat** [comment]
Terminology already changed, e.g. Proxy base path.

Closing during icebox gardening.
