### ISSUE TITLE
Install video guide

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#441]
We in the APIOps community are starting to have Mini API Jams. Intention is to fool around APInf and create something to contribute every time. See more from https://tarinoitadigitalisaatiosta.wordpress.com/2015/09/05/api-jamming-concrete-contribution-every-time/ 

We will have a lot of newbies and installing anything might be new to some. Having a video with instructions to install API Umbrella and APInf on top of it, would lower the barrier a lot.

**Comment by Nazarah** [comment]
Closing this.
