### ISSUE TITLE
Automated deployment to Heroku from API description file

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#442]
As a API owner I want to deploy my API with automated process to Heroku to make it the easiest part of API development and get more time to fiddle with my product (API)

![apinf-heroku](https://cloud.githubusercontent.com/assets/1927158/9703159/bfb4922c-5482-11e5-9019-3626ea82bce9.png)

**Comment by kyyberi** [comment]
See more about app.json from https://blog.heroku.com/archives/2014/5/22/introducing_the_app_json_application_manifest

**Comment by kyyberi** [comment]
This is something we could try to do in first APIOps community API Jam. To be honest, we would just get started with this in one jam. We could try to make app.json manually and test the process with CLI tools.

**Comment by kyyberi** [comment]
This feature just adopts widely used opportunity to deploy apps from github to Heroku with similar approach. In other words, it's rock solid and works. Lets just make that for APIs as well.

**Comment by kyyberi** [comment]
In the UX we put Deploy to Heroku button if the user has linked Heroku account to profile 
 
<a href="https://heroku.com/deploy?template=https://github.com/heroku/node-js-sample">
  <img src="https://www.herokucdn.com/deploy/button.png" alt="Deploy">
</a>


Otherwise link to Heroku signup
![herokubutton](https://cloud.githubusercontent.com/assets/1927158/9703426/3cbc1c28-548c-11e5-9914-175d6fcef5e8.png)


See more https://devcenter.heroku.com/articles/heroku-button

**Comment by brylie** [comment]
For Heroku deployment, we can build an app.json based on the [Wekan app.json](https://github.com/wekan/wekan/blob/devel/app.json).

**Comment by Nazarah** [comment]
closing this.
