### ISSUE TITLE
Push existing API Backends from Apinf to API Umbrella, when mismatched

### ISSUE THREAD

**Issue by brylie** [apinf/platform#446]
# User story

```
As an admin
I want to ensure all API Backends exist in both API Umbrella and Apinf
so that I can make sure the platform data is consistent in both locations
```
# Observed behavior

Some API Backends, when created via the Apinf platform, do not appear when switching the API Umbrella backend. This may be due to the 'pull only' nature of Apinf data sync. I.e. API Backends are only pushed at the time of creation.
# Possible solution

Schedule a 'sync' method to ensure consistency of API Backends on both Apinf and API Umbrella.

**Comment by bajiat** [comment]
APIs are separate from the proxy by default. Also, we support multiple proxies. Synchronisation does not take place anymore, since we are decoupled.

Closing during the icebox gardening.
