### ISSUE TITLE
Basic Acceptance Tests for Dashboard

### ISSUE THREAD

**Issue by ashakunt** [apinf/platform#468]
Based on hackathon feedback: 

Traditionally, this should be done in a way that everything is tested. 
- [ ] Creating an Admin account
- [ ] Creating an ApiTalist account (api owner)
- [ ] Add an API from APITALIST account
- [ ] Check if the added api was synced
- [ ] Make a call to the added API from the umbrella url.

**Comment by bajiat** [comment]
@ashakunt Would you like to take this task?

**Comment by ashakunt** [comment]
Looking at the current state of the product and the fact that there are no "UNIT" tests or "PRE DEPLOYMENT" tests, I would propose that we should right now start with UI tests for the DEPLOYED product, for example, using jasmine or selenium or robot framework. We can take up items in iterations like: 

1. Able to register an account
1. Able to login to registered account
1. Able to add a backend api (and so on, as defined in the DOD). 

THis way, we will be able to test the end-to-end product. Although, "UNIT" tests MUST still be added.

**Comment by Nazarah** [comment]
Next will have new UI and functionality for Dashboard. Closing this.
