### ISSUE TITLE
Add SAML 2 authentication support

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#491]
Identify user with SAML2 IDP

**Comment by brylie** [comment]
We may be able to use the [Meteor Accounts SAML package](https://github.com/nate-strauser/meteor-accounts-saml).

**Comment by bajiat** [comment]
@preriasusi We are using OAuth and Meteor accounts package for authentication. The Meteor Accounts SAML package is not maintained. Hence, we suggest that this would not be an Apika feature (at least not APIKA MVP).

**Comment by ilarimikkonen** [comment]
nope
