### ISSUE TITLE
Open ID connect support

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#533]
OpenID Connect 1.0 is a simple identity layer on top of the OAuth 2.0 protocol. It allows Clients to verify the identity of the End-User based on the authentication performed by an Authorization Server, as well as to obtain basic profile information about the End-User in an interoperable and REST-like manner.

OpenID Connect performs many of the same tasks as OpenID 2.0, but does so in a way that is API-friendly, and usable by native and mobile applications. 

https://openid.net/connect/ 

Lets consider that APIs would use OpenID connect in addition to API keys and such.

**Comment by preriasusi** [comment]
See: https://github.com/apinf/api-umbrella-dashboard/issues/668
