### ISSUE TITLE
As API owner I want to take caching away from some APIs

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#550]
If an API that tells something in real time, like membership info, account status', credit status', those APIs should not have caching.

**Comment by kyyberi** [comment]
This was a requirement from National Board of Education. It was stated a few months ago.

**Comment by Nazarah** [comment]
API umbrella doesn't know the state of an API (real-time/static) and content of API response headers.
This might be API's own functionality.
Closing this for the time being.
