### ISSUE TITLE
Re-design project website

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#557]
It is a common pattern to have a separate page for the open source project and another for the product (apinf.io). The open source project will explain how to contribute, how to access source code, meet community etc.

**Comment by kyyberi** [comment]
+1

**Comment by bajiat** [comment]
Create the page in Github pages, they will rbe displayed in apinf.org
redirect apinf.com to apinf.org

**Comment by bajiat** [comment]
Related to #963

**Comment by bajiat** [comment]
Check also #958 Development manifesto

**Comment by philippeluickx** [comment]
As discussed, it might be a good idea to stick to the apinf.io brand consistently.
So apinf.io could be the page with all information about the company, SaaS model (in the future) etc.
Then we can have subdomains for actual deployments:
- catalog.apinf.io for a "real data" catalog
- demo.apinf.io for a demo sandbox where anyone can explore the admin section. We could reset this daily then.

**Comment by nnn** [comment]
Done: apinf.org
