### ISSUE TITLE
RSS/JSON feed for latest APIs

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#558]
As a community manager I want to promote APIs to users for example by listing APIs in other contexts. I might event create IFTTT widget for publishing API info to Twitter. In addition JSON formatted list would be nice and more usable in some use cases. 

Might be a duplicate, but I was not able to find any with quick search.

**Comment by kyyberi** [comment]
This is needed also because we want to automate tweeting (via @apinf_io account) of new public APIs added.

**Comment by bajiat** [comment]
Duplicate of #2310 Closing during icebox cleanup.
