### ISSUE TITLE
Add API to apis.io catalog with minimal work

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#560]
As API owner I want to add my API to apis.io discovery service with single action. Option is to make it automatic when finalizing all API details to apinf service. 

---

We basically have all information needed to generate apis.json file for every API (http://apisjson.org/). Then use apis.io API to add it to service (http://apis.io/apiDoc). This will add value to API owners and thus increases interest to use apinf platform.

**Comment by Nazarah** [comment]
Closing this.
