### ISSUE TITLE
Support HMAC 256 hash authentication

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#569]
http://websec.io/2013/02/14/API-Authentication-Public-Private-Hashes.html

http://restcookbook.com/Basics/loggingin/

**Comment by kyyberi** [comment]
http://ridinganelefant.tumblr.com/post/82309469357/hmac-authentication-for-rest-apis

**Comment by bajiat** [comment]
What is the use case and description for this issue?

**Comment by Nazarah** [comment]
closing it.
