### ISSUE TITLE
Support API OAuth2 authentication

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#570]

**Comment by kyyberi** [comment]
OAuth versions MUST be protected through SSL/TLS. They should not be used over plain HTTP.

**Comment by kyyberi** [comment]
![image](https://cloud.githubusercontent.com/assets/1927158/10862427/b7c3ee98-7faf-11e5-87a8-84bec727d736.jpeg)
Strongloop solution could be adapted

**Comment by kyyberi** [comment]
Perhaps we could utilize mpass solution, it supports saml, oauth, open id connect
https://github.com/Digipalvelutehdas/MPASS-proxy

**Comment by kyyberi** [comment]
Related to #533 #569

**Comment by kyyberi** [comment]
I asked the main developer of mpass if it could be harnessed for this purpose with minimal effort.

**Comment by bajiat** [comment]
@kyyberi This maybe an API Umbrella issue. In effect API Umbrella would pass the OAuth token to the 3rd party API. Needs to be further clarified.

**Comment by kyyberi** [comment]
ok

**Comment by brylie** [comment]
Possibly related to the following upstream feature request:

- https://github.com/NREL/api-umbrella/issues/38

**Comment by bajiat** [comment]
Description needed.

**Comment by Nazarah** [comment]
closing this.
