### ISSUE TITLE
Reset password - 'Dismiss' notification dialog shown even after sign out

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#575]
# Steps
1. Visit https://apinf.io
2. Go to sign in page
3. Enter email address
4. Click on 'Forgot password'
5. Click on 'Email Reset Link' button
6. Reset password according to the email instructions  
7. Dismiss notification dialog is shown
8. Sign out without clicking on 'Dismiss notification dialog'
# Findings

Dismiss notification dialog  is shown even after sign out and shows error message 'no data found' .  
# Screenshot

![dismiss_dialog_after_signout](https://cloud.githubusercontent.com/assets/13309358/10914824/c2ae7850-825c-11e5-9a44-258005dafe1c.png)

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://apinf.io and it is reproducible.  

Screenshot:  
![reset_pwd_dilaog_signout](https://cloud.githubusercontent.com/assets/13309358/19643659/0d93ebb6-99f4-11e6-9e38-5e0c88fb2fad.jpg)

**Comment by saralavanip** [comment]
@bajiat, verified on https://staging.apinf.io and it is reproducible.  

Screenshot: 
![selection_083](https://cloud.githubusercontent.com/assets/13309358/19804928/0b8d4abe-9d1a-11e6-822d-b7f2cdfdc308.jpg)

**Comment by bajiat** [comment]
Closing as wontfix.
