### ISSUE TITLE
Integrate/create  API designer UI

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#576]
RAML spec versio 1.0 is out and in the same time tools have been put out. 

"API Designer is a standalone/embeddable editor for RAML (RESTful API Modeling Language) written in JavaScript using Angular.JS. By default, the editor uses an in-browser filesystem stored in HTML5 Localstorage."

https://github.com/mulesoft/api-designer

**Comment by bajiat** [comment]
This issue was moved to apinf/open-api-designer#66
