### ISSUE TITLE
API design management

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#577]
Since we are supporting API design in apinf, we need to have management for the designs as well. Management is versioning, co-authoring, comparing designs (more than diff), sharing designs, collecting designs to groups.

**Comment by kyyberi** [comment]
and force to select license for the design.

**Comment by kyyberi** [comment]
It could become sort of thingiverse for APIs...

**Comment by philippeluickx** [comment]
+1 on the versioning, we should add changelogs too then.

**Comment by philippeluickx** [comment]
Created a new issue for versioning https://github.com/apinf/api-umbrella-dashboard/issues/960, so we can have 1 feature / 1 ticket

**Comment by philippeluickx** [comment]
Createad a new issue for licensing https://github.com/apinf/api-umbrella-dashboard/issues/1056

**Comment by bajiat** [comment]
This issue was moved to apinf/open-api-designer#67
