### ISSUE TITLE
Activated account - 'Dismiss' notification dialog  is shown  after sign out 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#589]
# Steps  
1. Visit https://apinf.io    
2. Click on sign up button  
3. Enter the email address  
4. Enter  the password  
5. Click on Register button  
6. Check the email  to activate the account  
7. Click on Activate button  
8. Activated account 'Dismiss' notification dialog is shown  
9. Sign out without clicking on 'Dismiss notification dialog'

# Findings 
Activated account 'Dismiss' notification dialog  is shown after sign out   

# Screenshot:  
![activate_account_dialogue_after_signout](https://cloud.githubusercontent.com/assets/13309358/10916630/febf04a6-8264-11e5-87ff-f43f604c9de0.png)

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://apinf.io and it is not reproducible. 
- This issue was also verified on https://nightly.apinf.io   : Email verification not sent to the user and registering leads to automatic login.

**Comment by bajiat** [comment]
@saralavanip Thanks for verifying. Closing the issue.
