### ISSUE TITLE
Editor page is empty

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#599]
Steps:  

1. Visit https://apinf.io   
2. Sign in    
3. Go to Menu  
4. Select Documentation    
5. Go to Editor  

- Editor page is empty    

Screenshot:  

![empty_editor_page](https://cloud.githubusercontent.com/assets/13309358/11029679/4f931a78-86d1-11e5-887e-946e954de2c4.png)

**Comment by brylie** [comment]
This may be due to downtime of Swagger Editor. We need to monitor the Swagger Editor service, and consider disabling the Documentation Editor feature if no Swagger Editor service is available.

**Comment by brylie** [comment]
> Mixed Content: The page at 'https://nightly.apinf.io/api/gdi5fjAqx38D8XHPT' was loaded over HTTPS, but requested an insecure resource 'http://editor.apinf.io/'. This request has been blocked; the content must be served over HTTPS.

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://apinf.io and https://nightly.apinf.io: cannot be reproduced because of latest changes in UI. This issue can be closed.  

Screenshot:  

![selection_043](https://cloud.githubusercontent.com/assets/13309358/19675384/b105b4ee-9a96-11e6-82be-7aaf73d886cb.jpg)

**Comment by bajiat** [comment]
Closing the issue.
