### ISSUE TITLE
Error messages while adding API Backend not explanatory

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#604]
# Steps
1. Visit https://apinf.io  
2. Sign in  
3. Select 'API Backends' from menu  
4. Click on 'Add API Backend'  
5. Enter API name  
6. Select the backend protocol from drop down menu  
7. Enter the details of servers:  
   -  Enter invalid Host  
   -  Enter Port  
8. Enter Frontend host and Backend host  
9. Enter URL matches: Frontend prefix and Backend prefix  
10. Click on 'Submit'  button  
# Findings

Error message is not explanatory and the error fields could be higlighted.  
# Screenshot

![frontend_prefix_error_make_explanatory](https://cloud.githubusercontent.com/assets/13309358/11058528/2d796c50-879c-11e5-8b7d-4d2a93d72434.png)

**Comment by bajiat** [comment]
Known usability issue, work already in progress.

**Comment by bajiat** [comment]
@mauriciovieira I guess you are already working on this.

**Comment by mauriciovieira** [comment]
@bajiat yes, I've been working on https://github.com/brylie/meteor-api-umbrella/ focusing to fix those errors.

**Comment by bajiat** [comment]
@mauriciovieira Can you tell us the status of this task?

**Comment by bajiat** [comment]
Closing during icebox cleaning.
