### ISSUE TITLE
Investigate recruiting SW development apprentices

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#612]
Determine where we can recruit people who are interested in learning to code to join our team as Apprentices. Contact appropriate staff, recruiters, organizers, etc. to explain the opportunity.
# Resources

The following organizations or sources may prove fruitful for recruiting apprentice team members:
- Tredu
- University
## Learning resources

Apprentices will work through a code curriculum, so they can independently gain proficiency in basic programming. We can offer mentorship along the way, but apprentices should demonstrate self determination.
- [Khan Academy - Computer Programming](https://www.khanacademy.org/computing/computer-programming)

**Comment by kyyberi** [comment]
Lets use APIOps community and API:Suomi community as well.

**Comment by bajiat** [comment]
Closing during icebox cleanup.
