### ISSUE TITLE
Add 'Guided Tour' feature to 'Add API Backend' form

### ISSUE THREAD

**Issue by brylie** [apinf/platform#614]
# User story

```
As an end user
I would like a guided tour of the Add API Backend form
so that I can quickly understand how to fill out the form
```

```
As an end user
I would like a 'Guided Tour' button that I can click
so I can quickly learn about any confusing page or site section
```
# Challenge

We are getting feedback through our end-user tests that the API Backend form is difficult to understand. We can improve the user experience by providing more context and information about the form itself.
# Task

Consider how to quickly 'onboard' new users, so they feel comfortable with the 'Add API Backend' form. This may take the form of a guided tour, simplified help text, or some other idea. 

For now, we can focus on a guided tour feature, as any created text can also be added as inline help, documentation, etc.
# Resources

There is a [Meteor package](https://atmospherejs.com/flowkey/bootstrap-tour) we can use to integrate [Bootstrap Tour](http://bootstraptour.com/) into our project.

**Comment by bajiat** [comment]
Add API form has been simplified (only 4 fields). So a guided tour is not needed for that. There is a guided tour for API profile page and the different tabs. Closing during icebox cleanup.
