### ISSUE TITLE
Design and implement API publish/unpublish feature

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#620]
As a API owner I want to publish API I manage.

**Comment by kyyberi** [comment]
and unpublish

**Comment by bajiat** [comment]
Related to #628 where last step of the flow can contain the option to "Publish"

**Comment by bajiat** [comment]
For unpublishing, we need to study how Api Umbrella handles that.

**Comment by Nazarah** [comment]
Publish feature is already working in current APinf . With Next, Unpublishing APi feature will also be available. Closing this.
