### ISSUE TITLE
Umbrella forces to HTTPS even if config says http

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#621]
I selected HTTP as protocol for my API (HTTPS optional option). Yet when trying it response was 
`Requests must be made over HTTPS. Try accessing the API at: https://umbrella.digipalvelutehdas.fi/lentodiilit/deals?api_key=pj451db7Unt2PPDBQPxxxxxxxxxxxxxrgCj`

**Comment by jykae** [comment]
@kyyberi HTTP selection you chose is obviously for server where API is physically. Umbrella uses always HTTPS.

**Comment by kyyberi** [comment]
Got it, thanks for the clarification.

**Comment by kyyberi** [comment]
But what is the point of using forcing HTTPS? If the secure chain is broken as it is between Umbrella and HTTP API (not HTTPS), it's at least in some cases falty sense of security.

**Comment by kyyberi** [comment]
I guess the question is, are there cases when something private is exchanged between Umbrella and unsecure API backend.

**Comment by bajiat** [comment]
@kyyberi This is an upstream bug.

**Comment by bajiat** [comment]
Closing during icebox cleanup.
