### ISSUE TITLE
Ensure api managers can disable API key check on Backends

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#622]
Original report (by @kyyberi)
----
Even if I selected that API key is optional (and also selected unlimited requests), when testing the API response was: 
`API_KEY_MISSING`

Definition of done (by @bajiat, by @brylie modified due to Multiproxy work)
---
* [ ] Make sure the disable api key field in added to and stored in Proxy backend collection
* [ ] Make sure the properties of the field are aligned with Api Umbrella
* [ ] Make sure the field is passed correctly to the Admin REST API
* [ ] Make sure it gets stored properly in API Umbrella
* [ ] There needs to be setting in the Proxy tab in API profile

**Comment by kyyberi** [comment]
Works with api_key parameter though

**Comment by bajiat** [comment]
@kyyberi To what server are you making the request? Specifically, are you making the request to Api Umbrella server? If that is the case, this is an upstream bug.

**Comment by kyyberi** [comment]
I'm using API managed by APIKA, but obviously the actual API calls go through Umbrella. In those cases, api_key is always required.

**Comment by bajiat** [comment]
@brylie Should we check the Edit API backend form that the data gets passed correctly?

**Comment by brylie** [comment]
@bajiat jep. Specifically, we need to make sure the configuration object sent to API Umbrella conforms to the REST requirements:

```js
{
  "api": {
    "id": "string",
    "name": "string",
    "sort_order": 0,
    "backend_protocol": "http",
    "frontend_host": "string",
    "backend_host": "string",
    "servers": [
      {
        "id": "string",
        "host": "string",
        "port": 0
      }
    ],
    "url_matches": [
      {
        "id": "string",
        "frontend_prefix": "string",
        "backend_prefix": "string"
      }
    ],
    "balance_algorithm": "least_conn",
    "settings": {
      "id": "string",
      "append_query_string": "string",
      "headers": [
        {
          "id": "string",
          "key": "string",
          "value": "string"
        }
      ],
      "headers_string": "string",
      "default_response_headers": [
        {
          "id": "string",
          "key": "string",
          "value": "string"
        }
      ],
      "default_response_headers_string": "string",
      "override_response_headers": [
        {
          "id": "string",
          "key": "string",
          "value": "string"
        }
      ],
      "override_response_headers_string": "string",
      "http_basic_auth": "string",
      "require_https": "required_return_error",
      "require_https_transition_start_at": "2016-01-12T09:23:24.660Z",
      "disable_api_key": true,
      "api_key_verification_level": "none",
      "api_key_verification_transition_start_at": "2016-01-12T09:23:24.660Z",
      "required_roles": [
        "string"
      ],
      "required_roles_override": true,
      "allowed_ips": [
        "string"
      ],
      "allowed_referers": [
        "string"
      ],
      "rate_limit_mode": "unlimited",
      "rate_limits": [
        {
          "id": "string",
          "duration": 0,
          "accuracy": 0,
          "limit_by": "ip",
          "distributed": true,
          "response_headers": true
        }
      ],
      "anonymous_rate_limit_behavior": "ip_fallback",
      "authenticated_rate_limit_behavior": "all",
      "pass_api_key_header": true,
      "pass_api_key_query_param": true,
      "error_templates": {},
      "error_data": {},
      "error_data_yaml_strings": {}
    },
    "sub_settings": [
      {
        "id": "string",
        "http_method": "any",
        "regex": "string",
        "settings": {
          "id": "string",
          "append_query_string": "string",
          "headers": [
            {
              "id": "string",
              "key": "string",
              "value": "string"
            }
          ],
          "headers_string": "string",
          "default_response_headers": [
            {
              "id": "string",
              "key": "string",
              "value": "string"
            }
          ],
          "default_response_headers_string": "string",
          "override_response_headers": [
            {
              "id": "string",
              "key": "string",
              "value": "string"
            }
          ],
          "override_response_headers_string": "string",
          "http_basic_auth": "string",
          "require_https": "required_return_error",
          "require_https_transition_start_at": "2016-01-12T09:23:24.663Z",
          "disable_api_key": true,
          "api_key_verification_level": "none",
          "api_key_verification_transition_start_at": "2016-01-12T09:23:24.663Z",
          "required_roles": [
            "string"
          ],
          "required_roles_override": true,
          "allowed_ips": [
            "string"
          ],
          "allowed_referers": [
            "string"
          ],
          "rate_limit_mode": "unlimited",
          "rate_limits": [
            {
              "id": "string",
              "duration": 0,
              "accuracy": 0,
              "limit_by": "ip",
              "distributed": true,
              "response_headers": true
            }
          ],
          "anonymous_rate_limit_behavior": "ip_fallback",
          "authenticated_rate_limit_behavior": "all",
          "pass_api_key_header": true,
          "pass_api_key_query_param": true,
          "error_templates": {},
          "error_data": {},
          "error_data_yaml_strings": {}
        }
      }
    ],
    "rewrites": [
      {
        "id": "string",
        "matcher_type": "route",
        "http_method": "any",
        "frontend_matcher": "string",
        "backend_replacement": "string"
      }
    ],
    "created_at": "2016-01-12T09:23:24.665Z",
    "creator": {
      "username": "string"
    },
    "updated_at": "2016-01-12T09:23:24.666Z",
    "updater": {
      "username": "string"
    }
  }
}
```

**Comment by brylie** [comment]
I think there are two possible candidate fields in the above configuration: 

```js
...
"disable_api_key": true,
 "api_key_verification_level": "none",
```

**Comment by kyyberi** [comment]
"disable_api_key": true is more self explanatory

**Comment by brylie** [comment]
Right, this is API Umbrella functionality though. So, we need to figure out which field(s) API Umbrella uses to control the API Key requirement.

**Comment by brylie** [comment]
As @kyyberi indicates, lets test the `disable_api_key` first, and issue a fix if that is the correct setting.

**Comment by brylie** [comment]
When submitting our Edit API Backend form, the 'disable api key' field data is not being updated on API Umbrella.  We need to make sure our integration code is passing the updates to all API Backend configuration fields.
Related to issue #833

**Comment by brylie** [comment]
Copied from #833:

> We have a field on the "Edit API Backend" form to toggle the API Key check, but the changes are not made on API Umbrella. We need to make sure our integration code is passing the updates to all API Backend configuration fields.

**Comment by jykae** [comment]
@nnn I will try to help with this as this is strongly related on my task, passing "rate limit" fields.

**Comment by jykae** [comment]
"disable_api_key" works from Umbrella UI, able to make calls without API key. Edit API backend did not have the right field, document about Admin API is outdated.
"disable_api_key" can have 3 states "inherit, required, disabled" and they are String values, not Boolean as docs say: https://api-umbrella.readthedocs.io/en/latest/admin/api.html

Got disabling working from Apinf edit form also.

**Comment by jykae** [comment]
When API key is not used, existing rate limits are applied to IP address by default. I will however test & verify this in #1190

**Comment by brylie** [comment]
@nnn and @jykae did you test that the 'disable API Key check' setting is published to API Umbrella when submitting the form? Ping @saralavanip for testing purposes.

**Comment by saralavanip** [comment]
Tested on nightly2.apinf.io and this is reproducible. Setting API key as optional and call API shows API_key_Missing  

Screenshot:  
![disabled_api_key](https://cloud.githubusercontent.com/assets/13309358/17846887/c472500c-6853-11e6-91a0-74dac485455d.png)

**Comment by brylie** [comment]
@saralavanip please provide us with steps to reproduce, so we can look at this issue again.

**Comment by saralavanip** [comment]
@brylie , please find the steps to reproduce added to the previous comment.

**Comment by brylie** [comment]
Thanks @saralavanip

**Comment by bajiat** [comment]
@jykae Could you check whether you can reproduce the error (see Sarala's comment above) and whether the value gets properly stored in Api Umbrella?

**Comment by jykae** [comment]
@bajiat The schemas related to this are now having changes for multi-proxy support. I propose taking this on tasklist after the base elements for new architecture has been done.

**Comment by bajiat** [comment]
@nnn Would you be interested in this task? It is blocked by #1233.

**Comment by Nazarah** [comment]
@nnn what are your ideas about how the interface should look? please let me know.

**Comment by Nazarah** [comment]
@nnn : I've added the wireframes. One is the checkbox you suggested and another is toggling option. Please review them and give your feedback.
Suggestions for the text is also welcomed.

P.S. I;ve added only the field for this task only, As there might be other fields in the proxy tab, but the UI is not yet ready, you can place this field where convenient.

**Comment by nnn** [comment]
I like with simple checkbox, let's go with it.

**Comment by bajiat** [comment]
@nnn What is the status?
