### ISSUE TITLE
Allow System Administrators to manage all API Backends

### ISSUE THREAD

**Issue by brylie** [apinf/platform#623]
# User Story

```
As a System Administrator
I would like to manage all API Backends
so that I can assign managers to orphan APIs, or at least delete them
```

```
As a System Administrator
I would like to manage all API Backends
so that I can troubleshoot client errors or detect abuse
```
# Feature

When syncing API Backends from API Umbrella, there may be API Backends that were not created in the new Apinf instance. This means that no user can manage the API Backend. Additionally, there may be other reasons for System Administrators to want to modify API Backends, such as to detect abuse or troubleshoot errors.

**Comment by brylie** [comment]
@apinf/developers might we need to create an administrative page for this? What are your thoughts on this feature?

**Comment by bajiat** [comment]
We don't have administrative page, but admins have the privileges to manage the apis. Closing during icebox cleanup.
