### ISSUE TITLE
Implement UI for managing API backend managers

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#640]
Refer to #343 for wireframe.

Create an UI for adding or deleting managers for a given API backend based on user email.
# Wireframe

![API Managers UI wireframe](https://raw.githubusercontent.com/apinf/docs/master/docs/design/%23343_tab-view%26manager-view.png)
# Definition of done
## Display manager emails
- [x] Create `apiBackends` collection helper to retrieve Meteor users based on the `managerIds` field
- [ ] Create user interface to show of API managers for a given API.
  - [ ] Show name if available in user profile
  - [ ] Otherwise, show email (`user.emails[0].address` for example)
- [ ] User interface should be in Bootstrap component
  - [ ] Each manager in list will have 'delete' or similar button (see below)
## Add managers by email
- [ ] Create user interface  (text input with button) to enter new email address
  - [ ] When user inputs email address and clicks button, start invitation flow for new manager
- [ ] For adding managers, implement invitation user flow.
  - [ ]  Manager enters user email.
  - [ ] System emails user an invitation.
  - [ ] User clicks invitation link.
  - [ ] Registration step if user is not registered
  - [ ]  System adds user ID to array.
## Manage existing managers
- [ ] Add delete button or trash can or equivalent for deleting managers.
  - [ ] Add confirmation for the action.
- [ ] Check whether existing managers have update permission on the API backends collection.
# Related documentation
- [Meteor Users collection (Accounts)](http://docs.meteor.com/#/full/meteor_user)
- [Collection Helpers](https://github.com/dburles/meteor-collection-helpers)
- [MongoDB $in](http://docs.mongodb.org/manual/reference/operator/query/in/)
- [Bootstrap components](http://getbootstrap.com/components/)

**Comment by bajiat** [comment]
@mauriciovieira You have already worked on this task earlier. Would you be interested in continuing with it?

**Comment by brylie** [comment]
@mauriciovieira, are you working on this task? We need to put it back in the backlog, if not.

**Comment by bajiat** [comment]
Blocked by #595.
