### ISSUE TITLE
Research using multiple proxy gateways with Apinf UI layer

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#655]
Research whether it is possible to use Apinf as UI layer for several API Umbrella and/or Kong proxies.

**Comment by bajiat** [comment]
![kansallinen-api-hallinta-kong-included_360](https://cloud.githubusercontent.com/assets/11626388/11395465/f8e64592-9373-11e5-965c-cab78e40341e.png)

**Comment by bajiat** [comment]
![kansallinen-api-hallinta-simple_360](https://cloud.githubusercontent.com/assets/11626388/11395476/10b34ddc-9374-11e5-9148-401d21710cbb.png)

**Comment by Nazarah** [comment]
closing this. We now have support for multiple proxy to which an API backend can be connected.
