### ISSUE TITLE
Redesign settings fields

### ISSUE THREAD

**Issue by jykae** [apinf/platform#723]
As admin user, I would like to add only settings fields that are necessary.

Could the Apinf "host" field be automatically get?
I would like only put Umbrella host URL & API key/token. 
Could "baseUrl" and "Elasticsearch" fields be at least autofilled?

Continuation and suggestion to PR, https://github.com/apinf/api-umbrella-dashboard/pull/682

**Comment by bajiat** [comment]
Closing as wontfix
