### ISSUE TITLE
When syncing API Umbrella API Backends, ensure managers can edit own API Backends

### ISSUE THREAD

**Issue by brylie** [apinf/platform#738]
On a clean install, when syncing API Umbrella API Backends, existing Apinf users are not automatically associated with existing API Umbrella Backends. This is due to there being no common identifier between the systems.

Determine how to link existing API Umbrella API Backends to existing Apinf users, where the unique identifiers (e.g. email or ID) match. Also, ensure there are no 'orphaned' API Backends in Apinf, e.g. API Backends with no manager.

**Comment by bajiat** [comment]
Closing as obsolete.
