### ISSUE TITLE
API profile

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#746]
Could be duplicate. Discoverability will be based on API profiles rather than API specs. Enable API profile which utilizes commonly used (or in context specific) vocabularies and taxonomies http://www.infoq.com/articles/description-discovery-profiles-primer

**Comment by brylie** [comment]
This idea seems to be the cornerstone of a backend agnostic system. E.g. the API Profile could have options such as **Add Proxy**, which would allow users to choose API Umbrella, Kong, etc.

**Comment by bajiat** [comment]
Closing during icebox cleanup.
