### ISSUE TITLE
Add boilerplate checklist for general 'definition of done'

### ISSUE THREAD

**Issue by brylie** [apinf/platform#761]
Issues have common definitions of done. Add a general 'definition of done' checklist to our repository. Make sure the definition of done checklist contains general principles such as:
- relevant internationalization tags are added
- code is linted prior to review
- approximately 50% of the lines of code are comments
- variable names and methods are semantic

**Comment by bajiat** [comment]
Most of this is covered in contributor guideline. Closing during icebox cleanup.
