### ISSUE TITLE
As a API owner I want to be able to indicate my API service level

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#797]
As API owner I want to be able to tell to developers if my API in catalog and front page is still under development, and I can't guarantee production level uptime.

Also I want to be indicate if my API is in production and under SLA

**Comment by philippeluickx** [comment]
+1
Part of http://apimanifesti.fi/en/

**Comment by bajiat** [comment]
Lifecycle tags available. SLA is available in metadata in API profile. Closing as completed.

**Comment by philippeluickx** [comment]
@bajiat SLA definition is not yet implemented - would that be in scope for monetization?
