### ISSUE TITLE
Add email configuration to UI; update configuration file

### ISSUE THREAD

**Issue by brylie** [apinf/platform#808]
The file `/lib/_config/emails.js` contains several configuration options used by our system when sending emails. Make sure the relevant settings are exposed via the settings UI, and remove the references to the global `Config` object.

In effect, refactor our email settings so that it is more concise, and remove any unused configuration code.

Specifically of note:
- `siteName` ([line 5](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/emails.js#L5))
- `Accounts.emailTemplates.siteName` ([line 8](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/emails.js#L8))
- `Accounts.emailTemplates.from` ([line 9](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/emails.js#L9)) - uses both `Config.name` and `Config.domain`
- `socialMedia` ([lines 11 - 14](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/emails.js#L11-L14)) - iterates through `Config.socialMedia`
# Definition of done
- [x] [/server/`smtp.js`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/smtp.js#L11-L15), gets SMTP settings from Settings collection
- [ ] when email feature is disabled all email related features are disabled
  - [ ] Contact form
  - [ ] Accounts related emails
- [x] [/server/methods/`contactForm.js`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/methods/contactForm.js#L15-L16) gets email settings from Settings collection
- [x] Email settings pass through relevant [`SimpleSchema.RegEx.Email`](https://github.com/aldeed/meteor-simple-schema#regex) validation
# Related issue
- #819 - determine whether to deprecate the [PrettyEmail package](https://github.com/yogiben/meteor-pretty-email/), particularly if we are not putting it to use.

**Comment by sebbel** [comment]
Would `siteName` and `Accounts.emailTemplates.siteName` ever be different?

**Comment by brylie** [comment]
They should be the same. We need to determine how the `siteName` value is used, as part of this task. My understanding is that `siteName` might be used by PrettyEmail while `Accounts.emailTemplates.siteName` is used for Meteor Accounts emails.

**Comment by brylie** [comment]
Would you like to take this task @sebbel?

**Comment by sebbel** [comment]
Yea, I can take it.

Am Freitag, 29. Januar 2016 schrieb Brylie Christopher Oxley :

**Comment by brylie** [comment]
@elnzv can you recall if we are using the PrettyEmail package for any purpose? E.g. is it used for our account confirmation emails or the contact form?

**Comment by brylie** [comment]
Thanks @sebbel!

**Comment by bajiat** [comment]
@sebbel Thanks for volunteering again, assigned the task to you.

**Comment by sebbel** [comment]
I would like to give this issue back as I have no time to work on it this week.

**Comment by sebbel** [comment]
I would like to resume this task.

**Comment by brylie** [comment]
OK, thanks @sebbel :-) go ahead and self-assign.

**Comment by sebbel** [comment]
Could [Done] pointers be added to this task? As far as I understood: References to the global Config object are to be removed and the relevance of each line checked and made editable via settings page.

**Comment by brylie** [comment]
Yep. Follow your pattern with the 'enable' feature from the 'API Documentation Editor' settings. If email setting is not entered, any code for sending email is diabled as well. When email setting is enabled, email sub-fields are marked as required.

**Comment by sebbel** [comment]
I will do that first and then move on to checking if we can chop-chop
variables.

Am Montag, 8. Februar 2016 schrieb Brylie Christopher Oxley :

**Comment by bajiat** [comment]
@sebbel What is the status of #808?

**Comment by sebbel** [comment]
in progress, awaiting feedback about if i understood task correctly

Am Donnerstag, 11. Februar 2016 schrieb Taija Björklund :

**Comment by brylie** [comment]
Where are you awaiting feedback?

**Comment by brylie** [comment]
Or, what is the specific question?

**Comment by sebbel** [comment]
If my commits to the pull request are pointing into the direction of completing this task.

**Comment by brylie** [comment]
OK, I have reviewed the PR and added clarifications to this issue description as well as the PR discussion.

**Comment by brylie** [comment]
I am not sure why I didn't notice your request for feedback. Sorry about that.

**Comment by bajiat** [comment]
@sebbel Thanks for being interested in continuing this task!

**Comment by bajiat** [comment]
Closing as completed. The missing part is that email is either on or off and cannot be toggled automatically. This means that email links are available always, even when there is no email settings.
