### ISSUE TITLE
Add fields within Config.legal to Branding

### ISSUE THREAD

**Issue by brylie** [apinf/platform#817]
Currently, the file `/lib/_config/_config.js` contains a [`legal` field](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/_config.js#L26-L30) with several sub-fields. Enable the legal information to be stored in the Branding collection.
# Definition of done
- [ ] Add the `legal` field/subfields to the [Branding collection](https://github.com/apinf/api-umbrella-dashboard/blob/develop/both/collections/branding.js#L3). 
- [ ] Remove the [`legal` field from `config.js`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/_config.js#L26-L30). 
- [ ] Use the Branding.legal data in place of `Config.legal` [within `/lib/_config/emails.js`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/emails.js#L16-L20). 
- [ ] Add the Branding.legal fields to the `homeFooter` template, [next to Social Media links](https://github.com/apinf/api-umbrella-dashboard/blob/develop/client/views/home/footer/home_footer.html#L5).
# Related issue
- #819 - determine whether PrettyEmail is used; deprecate if unneeded

**Comment by bajiat** [comment]
Closing as obsolete/completed.
