### ISSUE TITLE
Use Branding social media fields inside email templates; or deprecate

### ISSUE THREAD

**Issue by brylie** [apinf/platform#818]
Currently, the email configuration settings use social media links that are defined from Config.socialMedia. We allow users to configure social media links via the branding page, so the Config.socialMedia settings are no longer relevant. Deprecate the `Config.socialMedia` object and use the Branding collection instead.

# Definition of done
* [ ] Remove the [`socialMedia` field from `/lib/_config/_config.js`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/_config.js#L33-L50)
* [ ] [Configure PrettyEmail](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/emails.js#L11-L15) to use social media links from the Branding collection
* [ ] Optional, if PrettyEmail is no longer used, deprecate the package

# Related issue
* #819 - deprecate PrettyEmail package, if unneeded

**Comment by bajiat** [comment]
Not relevant any more. PrettyEmail is not used any more. Closing issue
