### ISSUE TITLE
Backend pairs should not be visible to other than admin

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#821]
Just came to my mind that IMHO backend pairs in API profile view should not be visible to other than admins. Why? We want developers to use proxy not the API directly. Developers do not need backend information. It might even confuse them.

**Comment by brylie** [comment]
Good suggestion. This is also a potential security issue. For example, the backend API could be completely open-access, with no access checks. This could lead to abuse.

**Comment by bajiat** [comment]
Closing as solved. The API URL is only visible to regular users if there is no proxy connected to the API. When the proxy is connected, UI shows the proxy URL. (It is still possible that data is published. @brylie Please double-check. If data is published, open an isue.
