### ISSUE TITLE
Database migrations package needed for the project

### ISSUE THREAD

**Issue by jykae** [apinf/platform#840]
Benchmark migrations packages with some simple case.

Options:
Percolate migrations: https://github.com/percolatestudio/meteor-migrations
Wekan migrations: https://github.com/idmontie/meteor-migrations

Related issue: https://github.com/apinf/api-umbrella-dashboard/issues/774 
PR: https://github.com/apinf/api-umbrella-dashboard/pull/829

**Comment by bajiat** [comment]
We have the package in place. Migrations are added as per need (changed datamodels). Closing during icebox cleanup.
