### ISSUE TITLE
Swagger support in APIKA fails API calls

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#842]
Steps:

Add Swagger JSON for API.

Go to documentation.

Go to view documentation.

Choose documentation, in this case ePerusteet.

Open 'api/arviointiasteikot'-

"Try it out!"

Expected result:
Request url set as: 
https://umbrella.digipalvelutehdas.fi/eperusteet-service/api/arviointiasteikot?api_key=zzzzzzzzzzzzzzz

Real result:

https://apika.digipalvelutehdas.fi/eperusteet-service/api/arviointiasteikot/api/arviointiasteikot?api_key= zzzzzzzzzzzzzzz

It's also not possible to delete Swagger JSON, or edit after upload. The double prefix is probably because of JSON issue, that can't be changed anymore.

**Comment by bajiat** [comment]
The prefix duplication is not happening any more. Also it is possible to delete Swagger files. Closing during icebox cleanup.
