### ISSUE TITLE
Service validation period not shown in 'Metadata' view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#852]
# Steps
1. Visit https://nightly.apinf.io 
2. Login
3. Add API Backend
4. Go to Manage API Backends
5. Click on 'View' button
6. Go to Metadata and click on 'Edit API Metadata'
7. Enter the following details:
   -  Organization: Name and Description
   -  Contact: Email id and phone number
   -  Service: Name, Description, Validation period and Service level Agreement
8. Click on 'Submit' button
# Findings

 'Service validation period' not shown  in 'Metadata' view

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and it is not reproducible.This issue can be closed.

**Comment by bajiat** [comment]
@saralavanip Thanks for verification. Closing the issue.
