### ISSUE TITLE
Mouse point on text fields shows text 'Edit' 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#857]
# Steps 
1. Visit https://nightly.apinf.io
2. Login
3. Add API Backend
4. Go to Manage API Backends
5. Click on 'View' button
6. Go to 'Backlog'
7. Add backlog item
8. Click on 'Edit' button 

# Findings 
Mouse point on text fields, 'update' button and  pushdown button under 'Priority' shows  text 'Edit'.

# Operating Systems
1. Linux : Ubuntu 14.04.03 LTS (Trusty)
2. Windows 10

# Browsers
1. Internet explorer 11
2. Mozilla Firefox 44.0 
3. Google Chrome 48.0.2564.103
4. Microsoft Edge 25.10586.0.0

# Screenshots

![mouse_point_edit_text](https://cloud.githubusercontent.com/assets/13309358/12862411/0f70ef04-cc74-11e5-8883-c3b74ea8de11.png)  

![mouse-point_edit_text1](https://cloud.githubusercontent.com/assets/13309358/12862481/b9a388b0-cc74-11e5-9065-01421993a704.png)

**Comment by jykae** [comment]
@saralavanip Operating system and browser info would be good to have in these bug reports.

**Comment by saralavanip** [comment]
@jykae , please find the Operating system and browser details added to bug reports.

**Comment by brylie** [comment]
Lets try to deprecate the `yogiben:autoform-modal` package, which underlies this bug. We can re-use the `apiBacklogForm` template, and simply toggle the form type.

**Comment by saralavanip** [comment]
@bajiat . verified this resolved issue on htps://nightly.apinf.io  and it is not reproducible. This issue can be closed.

Screenshot: New changes in 'Edit Backlog Item' page   
![selection_062](https://cloud.githubusercontent.com/assets/13309358/19725359/c01324ba-9b8d-11e6-8d49-782b43e9f7c3.jpg)

**Comment by bajiat** [comment]
@saralavanip Thanks for verifying. Closing the issue.
