### ISSUE TITLE
Refresh 'Suomi' page view changes to 'English' 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#880]
# Steps
1. Visit https://nightly.apinf.io  
2. Login  
3. Change language to 'Suomi'  
4. Go to dashboard  
5. Refresh/reload page  
# Findings

 'Suomi' page view changes to 'English'  language view.

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://nightly.apinf.io and it is reproducible.

**Comment by bajiat** [comment]
@saralavanip This error should not be reproducible because of the recent changes with refresh (#258). Please verify.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io   v 0.40.0 and it is not reproducible.

**Comment by bajiat** [comment]
@saralavanip Thanks. Closing the issue.
