### ISSUE TITLE
Click on 'Lähetä' changes  button title text  to English 'submit'

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#881]
# Steps
1. Visit nightly.apinf.io  
2. Change language to 'Suomi'  
3. Login 
4. Go to dashboard  
5. Add API Backend  
6. Go to Manage API Backends  
7. Click on 'Edit'  
8. Edit API name  
9. Click on 'Läheta' button
# Findings
-  Text title 'Lähetä'  on submit button changes to english text 'Submit'
-  Submit progress text shown in English as 'submitting'
-  Error message shown in English 

![edit_api_suomi_laheta_to_submit_](https://cloud.githubusercontent.com/assets/13309358/13103191/dc49c29e-d55c-11e5-9f2b-1a6da98773e8.png)

**Comment by nnn** [comment]
Related to #965

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and is not reproducible with latest UI. This issue can be closed.

**Comment by bajiat** [comment]
@saralavanip Thanks for verification. Closing the issue.
