### ISSUE TITLE
 'Suomi' home page view with partly translated text strings

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#883]
# Steps
1. Visit https://nightly.apinf.io  
2. Go to language and select 'Suomi'
# Findings
-  'Suomi' home page view includes partly translated text strings. 
-  Latest API list have untranslated text strings:  'Lisätty 4 hours ago / 10 days ago'
-  User 'Contact' details input field titles with untranslated text
              - 'Submit' and 'Reset' button titles untranslated.
# Screenshots

![untranslated_text](https://cloud.githubusercontent.com/assets/13309358/13170865/04a43750-d6f8-11e5-9774-660c28648886.png)  
![suomi_home_page_english_text](https://cloud.githubusercontent.com/assets/13309358/13170870/0d208ef6-d6f8-11e5-95d6-8dffc03efca6.png)

**Comment by nnn** [comment]
Related to #965

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io  

Findings:  
-  Latest API details has English text 
-  Input field titles in 'Contact form' are in English  

Screenshot:  
![screenshot 19](https://cloud.githubusercontent.com/assets/13309358/19965557/38da53b2-a1d0-11e6-8871-cff2e34fa37a.png)

![screenshot 17](https://cloud.githubusercontent.com/assets/13309358/19965500/edd0b3de-a1cf-11e6-94e7-d10cd5c20351.png)

**Comment by bajiat** [comment]
Verified in nightly. Contact form texts have been translated to Finnish. There are no English details in API cards in latest APIs. This issue can be closed.
