### ISSUE TITLE
Click on 'Create API documentation' button in 'Suomi' view changes to English language view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#886]
# Steps
1. Visit https://nightly.apinf.io  
2. Login  
3. Go to dashboard  
4. Add API Backend  
5. Go to Manage API Backends  
6. Click on 'Edit'
7. Go to 'Documentation'
8. Click on 'Create API documentation' button  
# Findings

'Suomi view' changes to English language view

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and it is not reproducible with latest UI. This issue can be closed.  

Screenshot:  
![screenshot 15](https://cloud.githubusercontent.com/assets/13309358/19964894/f5f549b0-a1cc-11e6-9331-11429c8b256f.png)

**Comment by bajiat** [comment]
@saralavanip Thanks for verification. Closing this issue.
