### ISSUE TITLE
Create API documentation error

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#888]
# Steps
1. Visit https://nightly.apinf.io  
2. Login  
3. Go to dashboard  
4. Add API Backend  
5. Go to Manage API Backends  
6. Click on 'Edit'
7. Go to 'Documentation'
8. Click on 'Create API documentation' button
# Findings
-  Create API documentation was blocked
-  Error was explanatory only in Firefox browser
-  User might need more instructions while creating API documentation
# Operating Systems
1. Linux : Ubuntu 14.04.03 LTS (Trusty)
2. Windows 10 
# Browsers
1. Internet explorer 11
2. Mozilla Firefox 44.0 
3. Google Chrome 48.0.2564.103
4. Microsoft Edge 25.10586.0.0
# Screenshots:

Firefox:  

![create-api-doc-error-firefox](https://cloud.githubusercontent.com/assets/13309358/13182245/82d88b26-d739-11e5-87b9-8af51dc384eb.png)

Chrome: 

![create_api_documentation_empty_firefox](https://cloud.githubusercontent.com/assets/13309358/13182227/67e4ee4a-d739-11e5-8312-8c7a48a5a64a.png)  

Edge:  

![create-api-error-edge](https://cloud.githubusercontent.com/assets/13309358/13182397/28abc27a-d73a-11e5-8959-101f4eac9ef5.png)

Internet Explorer:  

![create-api-error-ie](https://cloud.githubusercontent.com/assets/13309358/13182417/45ae5e78-d73a-11e5-82de-6b5e283e0ba0.png)

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and it is not reproducible with latest changes in UI. This issue can be closed.

Screenshot:  
![screenshot 14](https://cloud.githubusercontent.com/assets/13309358/19964771/59add194-a1cc-11e6-97ba-34c3e3f99c0a.png)

**Comment by bajiat** [comment]
@saralavanip Thanks for verification. Closing this issue.
