### ISSUE TITLE
 Edit 'custom rate limits' in 'Global request settings' shows error

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#894]
# Steps
1. Visit nightly.apinf.io  
2. Login  
3. Go to dashboard  
4. Add API Backend  
5. Go to Manage API Backends  
6. Click on 'Edit' and go to 'Global request settings'  
7. Go to Rate limit mode and select 'custom rate limits'  
   -  Enter Duration  
   -  Enter Accuracy: select any one option(seconds/minutes/hours) clicking on dropdown button  
8. Click on 'Submit' button  
# Findings

It shows error 'Accuracy must be a number'     

![edit-api-accuracy](https://cloud.githubusercontent.com/assets/13309358/13285895/4e570f6e-db06-11e5-9496-0c29bbaeeeb4.png)   

![edit-api-accuracy-number](https://cloud.githubusercontent.com/assets/13309358/13285898/577e35a4-db06-11e5-90dd-93ee7277b475.png)

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and it is not reproducible with latest UI changes.  This issue can be closed. 

Screenshot:  
![advanced_settings_new](https://cloud.githubusercontent.com/assets/13309358/19964608/65bf126e-a1cb-11e6-809b-9b34e840b578.png)

**Comment by bajiat** [comment]
@saralavanip Thanks for verification. Closing this issue.
