### ISSUE TITLE
Select 'Required roles' in 'global request settings' and submit error

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#895]
# Steps
1. Visit nightly.apinf.io  
2. Login  
3. Go to dashboard  
4. Add API Backend  
5. Go to Manage API Backends  
6. Click on 'Edit' and go to 'Global request settings'
7. Go to 'Required roles 'and select any of the 3 options shown below:
   -  api-umbrella-contact-form
   -  api-umbrella-key-creator
   -  write-access
8. Click on 'Submit' button
# Findings
-  It shows error 'You must specify at least two values''  
-  User might need help text / provision to select multiple values.
# Screenshots:

![edit-required-roles-error1](https://cloud.githubusercontent.com/assets/13309358/13286718/bfa22ae6-db0b-11e5-9b8a-09b61ffcbdb9.png)  

![req-roles-error2](https://cloud.githubusercontent.com/assets/13309358/13286725/ca64c98e-db0b-11e5-9172-7d6ed391478b.png)

**Comment by saralavanip** [comment]
@bajiat ,  verified on https://nightly.apinf.io and it is not reproducible because of latest changes in 'Settings' view. 

This issue can be closed.

**Comment by bajiat** [comment]
@saralavanip Thanks for verification. Closing this issue.
