### ISSUE TITLE
 Mismatch of default text and help text  in 'Global request settings' 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#897]
# Steps
1. Visit https://nightly.apinf.io  
2. Login  
3. Go to dashboard  
4. Add API Backend  
5. Go to Manage API Backends  
6. Click on 'Edit' 
7. Go to 'Global request settings'
# Findings
-  Default text for input field: 'Append query string parameters' and help text differ.
-  Help texts overlap
# Screenshot

![image](https://cloud.githubusercontent.com/assets/13309358/13312599/ae02ad48-dba0-11e5-8091-6bfce17322aa.png)

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and it is not reproducible because of latest changes in UI.
- Settings view doesn't include 'Global request settings' in latest UI. 

- This issue can be closed.

**Comment by bajiat** [comment]
@saralavanip Thanks for verification. Closing this issue.
