### ISSUE TITLE
'Suomi' language views with English text strings

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#898]
# Steps
1. Visit https://nightly.apinf.io  
2. Go to language and select 'Suomi'  
3. Sign in - click on 'kirjaudu'
4. Add API backend
5. Call API
6. Go through all the views in menu
   -  Analytics
   -  Manage API backend - View API Backend
   -  Catalog
   -  Documentation
# Findings
-  Analytics  views: Filter titles: 'loaded', 'export logs in'; Title text strings shown in English :  'Show' ; ' Search' ; 'Pages': Previous-'Next'; 'Showing'; 
-  Catalog view: English language text strings: 'View Details' Bookmark' 'Rating'
-  Add API Backend wizard  : Input field titles in English language
-  Manage -Edit API backend views :Partly translated, field titles text and help text shown in English language
-  Documentation - 'Viewer' : English language text: eg. 'Select Documentation file'
# Screenshots

Analytics view:  
![image](https://cloud.githubusercontent.com/assets/13309358/13314007/11ce27c6-dbab-11e5-9157-afa57a2bf9c2.png)  
![image](https://cloud.githubusercontent.com/assets/13309358/13314054/8f43a8e8-dbab-11e5-84e4-c9598c79dd34.png)

Catalog View:  
![image](https://cloud.githubusercontent.com/assets/13309358/13314041/7dbaff5e-dbab-11e5-83c0-ea1ad50f8d22.png)    

Add API Backend View:
![image](https://cloud.githubusercontent.com/assets/13309358/13314069/af0208dc-dbab-11e5-9af9-45d1b05d5e22.png)  

![image](https://cloud.githubusercontent.com/assets/13309358/13314110/dbd31356-dbab-11e5-9413-da6b0ebbce9a.png)

 View API Backend :  
![image](https://cloud.githubusercontent.com/assets/13309358/13314120/fa1eef24-dbab-11e5-9b3d-668644872e1f.png)

Documentation – Viewer
![image](https://cloud.githubusercontent.com/assets/13309358/13314128/09484f40-dbac-11e5-913e-2ba02f665406.png)

**Comment by nnn** [comment]
Related to #965

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io 

**Findings:**  
Suomi view with English text strings:  
- Dashboard view: Analytics ->Filter -> Calendar tab with English text 'from', 'to'  
- Add API Backend form - >Input field titles in English language  
- Settings view: Input field titles - > ' API Name' , 'Description' , 'Email '  
- Documentation view - > Manage view: info texts are in English language
- Users view: Manage roles, edit views in English language    

Screenshots:  
![screenshot 20](https://cloud.githubusercontent.com/assets/13309358/19966726/c48abec4-a1d5-11e6-80dc-0ef3c0bfe965.png)  

![screenshot 21](https://cloud.githubusercontent.com/assets/13309358/19966734/cd2355b4-a1d5-11e6-8688-2e290e777103.png)  

![screenshot 22](https://cloud.githubusercontent.com/assets/13309358/19966744/d7626b78-a1d5-11e6-8376-173a96851292.png)  

![screenshot 23](https://cloud.githubusercontent.com/assets/13309358/19966788/073531f0-a1d6-11e6-93b4-b1618753b830.png)

**Comment by bajiat** [comment]
Status verified in nightly

# Findings:
* Dashboard view: Analytics ->Filter -> Calendar is in English
* Add API form - >Field titles are now localised to Finnish
* Settings view: Field titles
  * ' API Name' , 'Description' > localised to Finnish
  * 'Email' > still in English
Documentation view - > Manage view: info texts are in English language > still in English
Users view: Manage roles, edit views in English language > still in English

**Comment by bajiat** [comment]
Closing this as too broad, outdated and largely completed. There have been several translation rounds after this. Up-tp-date localisation bug reports are created during each release testing round.
