### ISSUE TITLE
Call API : 'Err_Too_Many_Redirects' errors also show results in 'Analytics' 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#903]
# Steps
1. Visit https://nightly.apinf.io 
2. Login
3. Add API Backend
4. Make API Calls
5. Go to dashboard to view analytics
# Findings
-  Errors while calling APIs show result in 'Analytics' view.
-  e.g : Error: “Err_Too_Many_Redirects “ : multiple redirect attempts are also shown as results in  'Analytics '
-  Also shows the same for errors: 502:'Bad Gateway' ; 504: 'Gateway timeout'
# Screenshot

![image](https://cloud.githubusercontent.com/assets/13309358/13489009/2238edbc-e12d-11e5-8ead-13b6c1022753.png)  

![504_gateway_timeout](https://cloud.githubusercontent.com/assets/13309358/13489023/3a9f6f34-e12d-11e5-9d94-1d77e07687b8.png)

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io and it is reproducible. 

Screenshot:  
![selection_112](https://cloud.githubusercontent.com/assets/13309358/19926164/c39c13a8-a0fb-11e6-89d7-22354375d356.jpg)    

![selection_113](https://cloud.githubusercontent.com/assets/13309358/19926203/f22da2ea-a0fb-11e6-8c08-edae0253e1f2.jpg)

**Comment by marla-singer** [comment]
@preriasusi Closed it as outdated
