### ISSUE TITLE
'Users' view in Suomi language with English texts

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#904]
# Steps
1. Visit https://nightly.apinf.io 
2. Sign up
3. Get profile admin rights
4. Go to 'Users' on navigation bar
# Findings

'Users' is partly translated and contains English text strings
# Screenshots:

![image](https://cloud.githubusercontent.com/assets/13309358/13489145/fcff5e68-e12d-11e5-8d52-ce164e5636cc.png)

![image](https://cloud.githubusercontent.com/assets/13309358/13489155/09949378-e12e-11e5-8bfb-594e8491d01f.png)

![image](https://cloud.githubusercontent.com/assets/13309358/13489163/1d19eb8c-e12e-11e5-804e-3b27975b84af.png)

**Comment by bajiat** [comment]
This issue is related to meteor-accounts-admin-ui-bootstrap-3: add i18n support to package.

**Comment by nnn** [comment]
Related to #965

**Comment by saralavanip** [comment]
@bajiat , verified on https://nightly.apinf.io  and it is reproducible. 

Screenshot:  
![selection_099](https://cloud.githubusercontent.com/assets/13309358/19921546/0a56e53a-a0e7-11e6-80f9-cf42bb103ad9.jpg)    

![selection_103](https://cloud.githubusercontent.com/assets/13309358/19921640/90dce0be-a0e7-11e6-8382-18bd394c9917.jpg)

**Comment by preriasusi** [comment]
Not repro in nightly anymore.
