### ISSUE TITLE
Traffic shaping

### ISSUE THREAD

**Issue by tuukka** [apinf/platform#908]
Especially in the case of websockets and MQTT, it would be useful to be able to shape the proxied traffic: if there are many network packets sent per second to the client, they could be batched in the proxy to be sent once per second to save battery in the mobile device.

**Comment by bajiat** [comment]
@brylie As a first step, create an issue in Api Umbrella.

**Comment by brylie** [comment]
Since we are currently integrated with API Umbrella proxy, I have opened the ticket there. If/when we support other API proxies, we can open this discussion in the respective project backlogs.

**Comment by bajiat** [comment]
We are taking steps towards this goal using Node-RED this sprint.

**Comment by Nazarah** [comment]
Node-Red never happened. Also, MQTT has separate implementation-related issues. If this need arises in the future, a new issue will be created with detailed business and use cases. Closing this.
