### ISSUE TITLE
'Name' field shows email-id in 'Users' view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#909]
# Steps
1. Visit https://nightly.apinf.io  
2. Sign up  
3. Get profile admin. rights for above profile
4. Create a dummy profile
5. Login as admin 
6. Go to 'Users' on navigation bar  
# Findings
-  Name field shows 'email-id' instead of user name though 'user name' taken during sign up / registration 
-  Edit/Update dummy profile : 'Name' field with 'email id' as default text  
# Screenshot

![login_username_email](https://cloud.githubusercontent.com/assets/13309358/13522612/18e53320-e1f9-11e5-8e70-7907dbe7b1fb.png)  

![user-profile-edit-name_defaulttext-email](https://cloud.githubusercontent.com/assets/13309358/13522587/f89bb71a-e1f8-11e5-8ef6-916926a5a734.png)

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://nightly.apinf.io and it is reproducible.

**Comment by brylie** [comment]
@bajiat this could be improved while working on #1846 

In effect, we no longer have a 'name' field, so the 'Name' column should be updated to say 'email'. Alternatively, we could add a 'name' field to the user profile.

**Comment by bajiat** [comment]
@saralavanip This should be resolved. Name field shows a username. Please verify.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io v 0.40.0 and it is not reproducible.
