### ISSUE TITLE
Promote multi-domain support feature in API Umbrella backlog

### ISSUE THREAD

**Issue by brylie** [apinf/platform#924]
One important feature, for whitelabeling purposes, is that API Umbrella proxy should support multiple URLs. This would mean that one API Umbrella deployment would be accessible via multiple domains. We have opened an [upstream feature request](https://github.com/NREL/api-umbrella/issues/213), so this item is to track the progress of the upstream feature.

**Comment by brylie** [comment]
This might be a good usage case for our Bountysource resources.

**Comment by Nazarah** [comment]
Closing this issue. This is related to API Umbrella and the related issue mentioned above has no further progress after Oct 2016
