### ISSUE TITLE
Restructuring the project

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#936]
Using the Meteor Guide, and previous project experience/design decisions, propose a common module structure for the Apinf project. Reorganize code to follow the decided-on structure.

**Comment by philippeluickx** [comment]
There are a couple of frameworks proposed for meteor. Active discussion on https://forums.meteor.com/t/framework-discussion-mantra-vs-space-vs-space-kitty-vs-redwood-vs-etc/17734

There is also overlap and talk about integrating multiple efforst: http://blog.capsulecat.com/2016/01/08/integrating-mantra-with-space-kitty/

Might be a good idea to do an evaluation. Even if we chose not to work from a framework, they can definitely serve as an inspiration and point us to where development is heading to.


https://github.com/meteor-space/base
https://meteor-space.readme.io/docs/

https://github.com/CapsuleCat/SpaceKitty
http://spacekitty.capsulecat.com/

https://github.com/kadirahq/mantra
https://kadirahq.github.io/mantra/

https://github.com/themeteorchef/base
https://themeteorchef.com/base/
