### ISSUE TITLE
Generate JavaScript code snippet for API call

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#945]
Ensure that the code samples Apinf is providing for Api calls also contain code samples for Javascript. E.g. [ReDoc](https://rebilly.github.io/ReDoc/), a potential Swagger viewer, contains code samples for C#, PHP and JSON.

Upstream [issue](https://github.com/Rebilly/ReDoc/issues/52) created to ReDoc

**Comment by Nazarah** [comment]
We have a feature now to generate SDKs for different programming languages. Closing this.
