### ISSUE TITLE
Create an audit document for ApiConnect (IBM)

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#947]
Audit template: http://apinf-documentation.readthedocs.io/en/latest/research/api-management-tools/_audit-template/

**Comment by brylie** [comment]
There is an existing audit document for [IBM API Management](http://apinf-documentation.readthedocs.io/en/latest/research/api-management-tools/ibm-api-management/). The document is currently empty, so lets use it for this audit task.

**Comment by Nazarah** [comment]
Closing this issue.
