### ISSUE TITLE
Aggregator - search multiple catalogues

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#954]
# Allow developers to search across multiple API catalogues

The Google for APIs. One of the biggest issues is the fragmentation of APIs, which makes it hard to discover the API you need. We could aggregate multiple catalogues and crawl for metadata.
# User story

As a developer
I need the find the right API
so that I can create awesome applications
# Design

To be defined
# Definition of Done

The task is complete when the following criteria are satisfied:
- [ ] API developer can search for API metadata
- [ ] API developer can browse the results
- [ ] The best results get shown on top
- [ ] Anyone can add more catalogues

**Comment by kyyberi** [comment]
Add liityntäkatalogi as API catalogue source if open api is not requirement. Meta data can be retrieved via CKAN API. Example how-to is there: https://github.com/apisuomi/apisuomi-2.0/tree/master/components/harvester

**Comment by Nazarah** [comment]
Next has a new Catalogue for APis with differnet searching mechanism. If the need arises in future, new issue will be made with detailed business and usecases. closing this.
