### ISSUE TITLE
Development manifesto

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#958]
We should write clear guidelines on how we develop, as core team and community.

Ideas could include:
- only include stable, production-grade and actively maintained 3rd party packages
- PRs are welcome and should be created early on, so developers can support ongoing effort
- PRs will only be merged in if they include tests, docs and does not decrease test coverage
- Every PR is code reviewed by another developer

From core team, we could also commit to
- PRs are reviewed every sprint
- Issues are actively maintained
- Roadmaps will be published and enough time will be provided to gather feedback and optimize before sprints happen

**Comment by bajiat** [comment]
Should this be part of project page?

**Comment by philippeluickx** [comment]
Makes sense to me.
