### ISSUE TITLE
Add missing i18n tags to UI texts

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#965]
Based on an UI text audit, there is quite a large number of unlocalised UI texts. Refer to this file for complete list: https://github.com/apinf/api-umbrella-dashboard/wiki/Unlocalised-UI-texts

# Definition of done
- [ ] Check that all of the texts  listed in https://github.com/apinf/api-umbrella-dashboard/wiki/Unlocalised-UI-texts have i18n tags.
- [ ] Add any missing i18n tags.
- [ ] Alphabetize i18n strings in en.i18n.js

Note: the task may also require solving autoform internationalisation.

**Comment by Alapan** [comment]
@brylie @bajiat I had started working on this issue a while ago. If it is still relevant, I had a question related to the texts listed here: https://github.com/apinf/api-umbrella-dashboard/wiki/Unlocalised-UI-texts. Some of these strings appear to be in non-UI files. Do only strings present in client folders/files have to be tagged?

**Comment by brylie** [comment]
Any string that appears to an end-user should be internationalized. Some strings are generated in JavaScript files, so use the `TAPI18n.__("stringKey");` method. Is that what you are asking?
