### ISSUE TITLE
Add CII Best Practices badge to project README

### ISSUE THREAD

**Issue by brylie** [apinf/platform#968]
The [Linux Foundation Core Infrastructure Initiative](https://www.coreinfrastructure.org/) offers a ['Best Practices' badge](http://bestpractices.coreinfrastructure.org/) to [Free/Open Source projects who meet several quality standards](http://bestpractices.coreinfrastructure.org/projects). The badge displays a project's progress towards a 100% quality measurement. 

Lets consider adding the CII Best Practices badge to our README, so that we can show community members that we are dedicated to providing an high quality free/open source product.

**Comment by philippeluickx** [comment]
+1

**Comment by Nazarah** [comment]
Closing this.
