### ISSUE TITLE
APINF - UI Text Improvement

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#973]
Some UI texts in the APINF portal is not intuitive enough to convey their intent. We need to rewrite/improve those texts to make them more understandable

**Comment by bajiat** [comment]
This issue is too generic. Either we need to list the texts requiring improvements and include the list in this issue. The other alternative is to improve texts as we are improving the UI in general element by element, in which case we could close this issue. I prefer the latter.

**Comment by kyyberi** [comment]
I agree, it should be broken into pieces. Perhaps we can work on these on our weekly UX meetings? Lets pick one on each time and iterate a little more. At least that way we have a method and plan :)

**Comment by bajiat** [comment]
Closing as too generic.
