### ISSUE TITLE
Show most popular APIs on landing page

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#990]
# User story:

> As an Apinf user I want to see the most popular  APIs instead of most recent APIs when I first land into Apinf so that I don't get confused by test APIs.

Change the sorting the in the front page according user story #989 (bookmarking, average star rating). Default sorting should be configurable by sys admin.

**Comment by Nazarah** [comment]
Need to define the parameters and thresholds based on which most popular and most recent API card would be displayed in the landing page.

**Comment by Nazarah** [comment]
@bajiat  Which categories should we consider to show the APIs in Landing page?
No. of consumers
no. of times made favorite
uptime

Also, should er keep the current number of 8 APIS in the landing page? or do you want to change it?

**Comment by bajiat** [comment]
@Nazarah 
Popularity should be based on no of consumers or number of calls, bookmarking and voting. I would not consider uptime - that's related to reliability.

Number of apis depends on the design for cards, can't say.

**Comment by Nazarah** [comment]
Added Wireframes, Need a PR review for them.

**Comment by Nazarah** [comment]
New version of Landing page that has buttons for browsing API catalog and adding own API.
Here APIs are displayed either as Most Recent and Most Popular.
Popularity is defined in the help icon dialogue.


https://github.com/apinf/docs/blob/master/docs/Wireframes/LandingPage/LandingPageRecentAPI.png

https://github.com/apinf/docs/blob/master/docs/Wireframes/LandingPage/LandingPagePopularAPI.png

**Comment by bajiat** [comment]
We have now implemented "Featured APIs" to the frontpage, which are APIs selected by admins. Will stll keep this as an idea in icebox.

**Comment by Nazarah** [comment]
@bajiat I believe we can still close this issue. Logically admins would consider keeping APIs popular among its consider in the list of Featured APIs. So this would solve the dilemma of keeping a separate section for popular APIs. 
Its's a thought. Rest is upto you. :)
