### ISSUE TITLE
Apinf  Catalog and Mgmnt REST APIs

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#994]
This is an EPIC for providing a REST API endpoints for key Apinf features, such as catalog

**Comment by bajiat** [comment]
Could this be a relevant list for the APInf API: http://apievangelist.com/2015/10/15/establishing-a-common-api-definition-that-api-management-providers-can-use/ ?

**Comment by matleppa** [comment]
@bajiat  Should we rename REST APIs according to names used in header of this issue?
Catalog API (current APIs API) and Management API (current Maintenance API)

**Comment by matleppa** [comment]
REST APIs are renamed as suggested: Catalog API (current APIs API) and Management API (current Maintenance API)
