### ISSUE TITLE
Create get, post, put endpoints for API catalog API

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#995]
# User story

As a partnering external API catalog maintainer I want to be able to add API backends to Apinf catalog through a REST API so that my community / organization can use Apinf for API management

Related to #2102, #2336 and harvester

**Comment by brylie** [comment]
@matleppa is this done now?

**Comment by matleppa** [comment]
Yes, it is done.

**Comment by brylie** [comment]
@matleppa would you link to this issue from the related (closed) PR, and then close this issue?

**Comment by matleppa** [comment]
Closed with #.

**Comment by matleppa** [comment]
Closed with #2876.
