### ISSUE TITLE
Catalog filtering based on API owner

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#997]
# User story

> As an API consumer I want to be able to find or filter APIs based on API owner (= user who has added the API) so that I can find all APIs for an owner who provides APIs that interest me
# Definition of done
- [ ] Collection helper to fetch owner user name from API backend
- [ ] UI component to filter by user name
- [ ] Refer to wireframe to what UI component to use for filtering
- [ ] Choose a component library to choose owner from the actual owners
- [ ] Display the filtered results. Select from these probable options:
  - [ ] Filter inside of the template helper
  - [ ] Change the catalog subscription based on the selection
- [ ] Optionally, change the URL parameter (Result: makes it easier to reuse the filter when toggling between card view and table view)

**Comment by Nazarah** [comment]
Which user accounts should be considered?
users registered in APINF, GitHub, any other place?

**Comment by Nazarah** [comment]
I will work on the wireframes.

**Comment by bajiat** [comment]
@brylie Check if we have unique usernames, including Github registrants?

**Comment by jykae** [comment]
@bajiat @brylie Requiring unique username work was done last autumn in the beginning (or before Apika. But I can verify it.

**Comment by brylie** [comment]
@jykae cool. What additional work is required by this task?

**Comment by jykae** [comment]
At least I think learning aldeed:tabular package, how to extend filtering with that.

**Comment by brylie** [comment]
@bajiat what is the definition of done for this task? I.e. what are the expected outcomes?

**Comment by brylie** [comment]
@Nazarah is there a wireframe that shows an 'API owner' filter field? We could use the wireframe as reference for this task.

**Comment by bajiat** [comment]
@jykae Please check the definition of done: does your estimate 3 days still hold?

**Comment by brylie** [comment]
@bajiat and @Nazarah is there a wireframe related to this task?

**Comment by jykae** [comment]
@brylie Added "Blocked" label because had discussion we are changing from aldeed:tabular package.

**Comment by Nazarah** [comment]
@brylie : uploading the wireframes tonight as PR.

**Comment by Nazarah** [comment]
Wireframes

1. Contains separate dropdowns for all filterable ccriteria. Multiple selection can be made from each dropdown. Number of selected items appear on the filter pane. On checking one value, the Filter button gets activated. Clear All button clear all the selected valyes
https://github.com/apinf/docs/blob/master/docs/Wireframes/Filtering/FilterMenu1.png

https://github.com/apinf/docs/blob/master/docs/Wireframes/Filtering/FilterMenu1_AllMenuCollapsed.png

**Comment by Nazarah** [comment]
Version 2

Filter pane is separated in sections for each criteria: category, Protocol, Owner and organization, Lifecycle Phases, My APIs.
MyAPIs contains both own added and bookmarked APIs
The values appear as tags. Multiple tags can be selected and the selected ones are highlighted. 
Number of selected entries appear on pane.
Activating the filter button and clear button functions the same.

https://github.com/apinf/docs/blob/master/docs/Wireframes/Filtering/FilterMenu2.png
https://github.com/apinf/docs/blob/master/docs/Wireframes/Filtering/FilterMenu2_LifeCycle_Selected.png
https://github.com/apinf/docs/blob/master/docs/Wireframes/Filtering/FilterMenu2_MyAPIs_Selected.png
https://github.com/apinf/docs/blob/master/docs/Wireframes/Filtering/FilterMenu2_OwnerOrganization_Selected.png
https://github.com/apinf/docs/blob/master/docs/Wireframes/Filtering/FilterMenu2_Protocols_Selected.png
https://github.com/apinf/docs/blob/master/docs/Wireframes/Filtering/FilterMenu2_Result.png
https://github.com/apinf/docs/blob/master/docs/Wireframes/Filtering/FilterMenu2_Selected.png

**Comment by Nazarah** [comment]
Also when a filtering is made, the the main page should show how the filtering is done.
